### ISSUE TITLE
Users SBAT see CG-C$ price on blockscout

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-monorepo#1000]
- [ ] show C$ price for 1 CG in the graph top left using current exchange price
- [ ] CG prices seem to always show a conversion to $. Make sure those are correct and ideally show them as C$

**Comment by annakaz** [comment]
@aaitor see the Exchange contract wrapper in contractkit https://github.com/celo-org/celo-monorepo/blob/master/packages/contractkit/src/wrappers/Exchange.ts#L182

**Comment by diminator** [comment]
Thanks @annakaz 

Currently blockscout fetches the prices from the CoinGecko API.
I'll create a price fetcher that uses the `EthereumJSONRPC`

**Comment by diminator** [comment]
@mrsmkl this is about showing the right price graphs for cGLD and cUSD in blockscout. I think this might already be done, but assigning here
