### ISSUE TITLE
ASv2 README (high-level business overview)

### ISSUE THREAD

**Issue by isabellewei** [celo-org/celo-monorepo#10013]
[README.md](https://github.com/celo-org/identity/tree/ASv2/asv2):

- [x] overview of how asv2/odis works and why you should use it

**Comment by arthurgousset** [comment]
This is done [README.md](https://github.com/celo-org/identity/tree/ASv2/asv2).

But split [protocol overview](https://github.com/celo-org/identity/blob/ASv2/asv2/protocol.md) out of README, so protocol overview is still outstanding (maybe in scope for eng team)
