### ISSUE TITLE
Partner Integration: Kaala

### ISSUE THREAD

**Issue by isabellewei** [celo-org/celo-monorepo#10016]
they've tested it successfully and liked it, not sure progress on integrating into prod

**Comment by arthurgousset** [comment]
Done, integration worked (see demo recording)

**Comment by alecps** [comment]
leaving this open until production integration is released

**Comment by arthurgousset** [comment]
Needs instructions to switch away from legacy endpoint to ODISv2 (cc @therealharpaljadeja)
