### ISSUE TITLE
identity package can't be installed via yarn

### ISSUE THREAD

**Issue by sirpy** [celo-org/celo-monorepo#10030]
### Expected Behavior
`yarn add @celo/identity` should work

### Current Behavior
` ethereumjs-tx@npm:2.1.2 is deprecated: New package name format for new versions: @ethereumjs/tx. Please update.
➤ YN0001: │ Error: blind-threshold-bls@git+https://github.com/celo-org/blind-threshold-bls-wasm.git#e1e2f8a: Couldn't resolve "e1e2f8a" as either a commit, a tag, or a head - if a commit, use the 40-characters commit hash`

to fix release the bls package to npm or replace with a 40chars full commit hash

**Comment by aaronmgdr** [comment]
@isabellewei @alecps
