### ISSUE TITLE
isNullAddress bug (v1)

### ISSUE THREAD

**Issue by cajubelt** [celo-org/celo-monorepo#10045]
I'm not sure if you're still maintaining v1, but if so you might want to fix this bug.

### Expected Behavior

[isNullAddress](https://github.com/celo-org/celo-monorepo/blob/0871aec1c15bb780bb740dda432af725f4bf7c5b/packages/sdk/base/src/address.ts#L9) should return true when given `0x0000000000000000000000000000000000000000` as a parameter

### Current Behavior

It always returns false, because it trims the leading 0x and then compares the address to a constant with 0x as a prefix.

Actually, it would return true if it was called with `0x0x0000000000000000000000000000000000000000`, but that doesn't seem intended.

**Comment by aaronmgdr** [comment]
I think this might still be in issue in v2 too
