### ISSUE TITLE
Users SBAT see the name of a person in a QR code transaction in the feed

### ISSUE THREAD

**Issue by cmcewen** [celo-org/celo-monorepo#1005]
### Expected Behavior

If you've scanned someone's QR code which has their name in it, you should be able to see their name labeled in feed txs

### Current Behavior

Just see sent or received

**Comment by martinvol** [comment]
Some related work here: https://github.com/celo-org/celo-monorepo/pull/1010

**Comment by jeanregisser** [comment]
Part of #4846
