### ISSUE TITLE
Highlight ASv1 sunsetting "in progress" in docs.celo.org

### ISSUE THREAD

**Issue by arthurgousset** [celo-org/celo-monorepo#10058]
Todo (delegate exact decision to Amir):
- [x] Add banner sharing this is not maintained at the moment

**Comment by nestorbonilla** [comment]
Updates:

- The updated banner text was confirmed with Dave.
- [PR](https://github.com/celo-org/docs/pull/588) is ready to be approved and merged.

**Comment by arthurgousset** [comment]
Closing ticket because done:
- https://github.com/celo-org/docs/pull/588
