### ISSUE TITLE
Turn off cLabs Twilio traffic (bots etc)

### ISSUE THREAD

**Issue by arthurgousset** [celo-org/celo-monorepo#10056]
Ticket to remember this workstream (might be helpful to get a hand from @celo-org/devopsre to do this cleanly)

**Comment by arthurgousset** [comment]
Note to self: Speak to @lvpeschke for advice

**Comment by lvpeschke** [comment]
@alecps could you update https://www.notion.so/Twilio-account-f2d71a0713894761a7fc32ab761aedc3 and https://www.notion.so/clabsco/SMS-Provider-Accounts-MessageBird-Vonage-Nexmo-Twilio-a8dd8ceb6c5f4d74bc5aa8e317eb5153? I'm curious if these can be considered "Removed"?
