### ISSUE TITLE
Update emisianto for public launch

### ISSUE THREAD

**Issue by isabellewei** [celo-org/celo-monorepo#10089]
Repo: [github.com/celo-org/emisianto](https://github.com/celo-org/emisianto)

MUST DO:
- [ ]  update verification to Twitter 0Auth challenge

SHOULD DO:
- [x] use DEK for authentication
- [ ] create signer key for issuer
- [ ] add comments in code to describe what's being done
- [ ] update README

NICE TO HAVE:
- [ ] avoid repeating code in modals (?)
- [ ]  get rid of toast

**Comment by isabellewei** [comment]
get rid of toast

**Comment by arthurgousset** [comment]
Permissions:
- [x] Nestor needs access to cLabs Vercel
- [x] Nestor needs access to Github permission https://github.com/celo-org/emisianto
