### ISSUE TITLE
Devs SBAT to transfer balances when resetting the network

### ISSUE THREAD

**Issue by ashishb** [celo-org/celo-monorepo#1013]
### Expected Behavior

Devs SBAT to transfer balances when resetting the network

### Current Behavior

`alfajores` is unstable for the past few days. We want to reset the network but that means everyone will lose their balances. It would be good to have a tool, as a part of celotool, to dump and restore the state (or at least the account balances) to minimize the impact on the users.

**Comment by timmoreton** [comment]
we can do this at a genesis level now for CG and C$
