### ISSUE TITLE
Allow anyone to call resetSlashingMultiplier

### ISSUE THREAD

**Issue by pahor167** [celo-org/celo-monorepo#10137]
Currently resetSlashingMultiplier can by called only by validatorGroup that was slashed. Allow anyone to call resetSlashingMultiplier with slashed validator group address.

Also update getValidatorGroupSlashingMultiplier so it will automatically return correctly adjusted multiplier event when stored multiplier is not reset in storage variable yet. Make sure that this getter is used anywhere where we read multiplier during epoch rewards

**Comment by product-matt** [comment]
Note: Arthur's wish, see comments here: https://celo-org.slack.com/archives/CP5V8KF51/p1675426239492129

**Comment by product-matt** [comment]
can be executed by signer - decision: not to do so that validators always observe status

**Comment by soloseng** [comment]
Supporting [slack discussion](https://celo-org.slack.com/archives/CNJ7KTHQU/p1675183571737369?thread_ts=1675120858.858899&cid=CNJ7KTHQU)
