### ISSUE TITLE
investigate WETH as gas token

### ISSUE THREAD

**Issue by product-matt** [celo-org/celo-monorepo#10167]
See Volpes's document: https://docs.google.com/document/d/1jSlkY4l3P4Z9fqR_tAj722ubIR9gmNKuJVdHKxKBHFU/edit#heading=h.a5c38c5bpmui

**Comment by alecps** [comment]
https://www.notion.so/clabsco/WETH-as-Gas-Token-WIP-2ff368a0c4484566a868000e90ecc679
