### ISSUE TITLE
Create solidity wrapper for ZK precompiles

### ISSUE THREAD

**Issue by product-matt** [celo-org/celo-monorepo#10164]

**Comment by product-matt** [comment]
probably already exists said Tim

**Comment by montera82** [comment]
Seb brought this to our attention fyi 
https://github.com/celo-org/docs/pull/872

**Comment by montera82** [comment]
This task is a duplicate and is currently being worked on by Karl on the blockchain team.
He has covered the precompile available precompile ( see image )
From what i understand, testing this is a little bit tricky as it it must be done on the blockchain side. I am engaging with him and will update in our next tech talk.


![Image](https://github.com/celo-org/celo-monorepo/assets/8665738/701538e3-8093-48b4-81a0-8de16983263d)
image src https://deploy-preview-872--celo-docs.netlify.app/protocol/precompiles#available-precompiles
cc @martinvol @product-matt

**Comment by martinvol** [comment]
Are we good to close this?

**Comment by karlb** [comment]
Closed in https://github.com/celo-org/celo-monorepo/pull/10240
