### ISSUE TITLE
Add support for CIP-64 transaction type in celo-ethers-wrapper

### ISSUE THREAD

**Issue by arthurgousset** [celo-org/celo-monorepo#10169]
This issue was used to track efforts to add CIP-64 to the vanilla `ethers` library, but has since been repurposed for adding support to the `celo-ethers-wrapper` library.

Instead this issue used to continue tracking efforts to add CIP-64 to the vanilla `ethers` library:

- https://github.com/ethers-io/ethers.js/issues/3747

**Comment by arthurgousset** [comment]
Sprint planning: 
- @dckesler will check-in with @aaronmgdr on what help is needed
- Consider waiting for Ethers v6.1 which would make it easier to add a transaction type (currently v6.0)

**Comment by nicolasbrugneaux** [comment]
v6 supports via celo-ethers-wrapper for now: 
- https://github.com/celo-tools/celo-ethers-wrapper/pull/13

**Comment by nicolasbrugneaux** [comment]
following PR: 
- https://github.com/celo-tools/celo-ethers-wrapper/pull/14

**Comment by nicolasbrugneaux** [comment]
The v6 PR was merged
