### ISSUE TITLE
dappkit deprecation

### ISSUE THREAD

**Issue by nicolasbrugneaux** [celo-org/celo-monorepo#10207]
Following this convo:
- #9912

Hello there, the topic of "moving the core-contract types so they can more easily be imported in typescript" has come up again during the apptooling meeting and we're gonna try to separate into their own package. The only question is whether to move them to a different package or even outside of the monorepo.

The current trend seems to be to cleanup the monorepo a bit, but having the types stay here actually makes tons of sense (no tooling to reinvent, no submodules to handle)

Any thoughts?

**Comment by nicolasbrugneaux** [comment]
Tagging @celo-org/default-owners

**Comment by arthurgousset** [comment]
Reflecting discussion from weekly sync: 
- We agreed the scope here is less to make a new package and more 
  - [x] to understand the uses of contractkit within cLabs (CLI, primitive team release, identity SDK, etc)
  - [x] to understand the packages used in contractkit
  - [x] fully map out the dependencies of contractkit and if they are used standalone
  - [x] to understand who cares if we propose to sunset contractkit for the public (the goal is not to sunset per se, but to find out who needs contractkit and why)
  - [x] get rid of dappkit??

Note: 
- We already know contractkit is often necessary in conjunction with the gas fee currency feature

**Comment by nicolasbrugneaux** [comment]
WIP findings https://www.notion.so/clabsco/WIP-celo-contractkit-830cce5acffe4d65bbe9a61724364f63, I will keep updating that doc as I gather more info

**Comment by nicolasbrugneaux** [comment]
Scheduled a call with Valora which seems to be the only users of dappkit to talk about sunsetting

**Comment by nicolasbrugneaux** [comment]
Dappkit sunsetting post https://forum.celo.org/t/sunsetting-dappkit/5336

**Comment by nicolasbrugneaux** [comment]
Contractkit _public_ sunsetting post https://forum.celo.org/t/sunsetting-contractkit/5337

**Comment by nicolasbrugneaux** [comment]
Todo following the two blog posts:
- [x] make a migration guide from contrackit 
- [x] set a deprecation notice for contractkit in npm (by Wed, Mar 22)
- [x] start killing dappkit (by Wed, Mar 22)
  - [x] add a deprecation notice on npm
  - [x] remove the package from the monorepo

Context: 
- You can't delete code from npm once it's been downloaded. But you can set a **deprecation notice**.

**Comment by arthurgousset** [comment]
- [x] Get feedback at https://github.com/celo-org/celo-monorepo/discussions/10157

**Comment by nicolasbrugneaux** [comment]
Migration guide
- celo-org/celo-monorepo/pull/10228

Removal of dappkit
- celo-org/celo-monorepo/pull/10230

**Comment by nicolasbrugneaux** [comment]
Closing this and following issue specific to contractkit can be found here: https://github.com/celo-org/celo-monorepo/issues/10289
