### ISSUE TITLE
0xB0aF00891c2E0bD32ea37b6E56c030D12a6cF21c

### ISSUE THREAD

**Issue by alfiomy** [celo-org/celo-monorepo#10215]
https://github.com/celo-org/celo-monorepo/blob/c1f72b8918d8d6f1da2d988afd410bbd0ebad96a/packages/protocol/contracts/common/Accounts.sol#L266

**Comment by alfiomy** [comment]
ahmed.hassan.omran1@gmail.com

**Comment by karlb** [comment]
It is unclear what this issue is about.
