### ISSUE TITLE
Write up how fee currencies work on Celo

### ISSUE THREAD

**Issue by arthurgousset** [celo-org/celo-monorepo#10223]
Context:

- In an ideal world, any Ethereum-compatible dapp is able to make custom fee currency transactions on Celo with their existing client library of choice
- This requires adding support for Celo transaction types in the most popular client libraries (e.g. viem, ethers, web3js, ...)

From a dev perspective demo transactions using their preferred library are sufficient, but for those more interested, it could be useful to cover the fee currency feature from the feeCurrencyWhitelist, to the debit/credit functions in fee currency tokens, and validator block payments.

**Comment by 0xarthurxyz** [comment]
Taking notes in this Google doc [[1p] Explainer: How gas fee currency works](https://docs.google.com/document/d/1R60PzZB4pOFGQUUabRtvrNGtrtpg8Ly4T4jjwadmalo/edit?usp=sharing)

**Comment by aaronmgdr** [comment]
https://github.com/celo-org/celo-labs/issues/1020
