### ISSUE TITLE
Users should see a customized messaging on the lock screen

### ISSUE THREAD

**Issue by jmrossy** [celo-org/celo-monorepo#1022]
### Expected Behavior

Pass custom title and description to be displayed on the lock screen. Some Android versions allow customizing the title and the messaging of the lock screen. As a part of this issue, figure out which versions/devices respect such customization. 

Title: Celo Security
Message: Keep your account secure

Following is an example from API 28
<img width="426" alt="tmp1" src="https://user-images.githubusercontent.com/389236/48652288-8e436780-e9b3-11e8-96ae-7d65e97b350b.png">

### Current Behavior

The lock screen shows up with the default system-defined text.

**Comment by jmrossy** [comment]
*From Corey:*
Some copy suggestions.
Title: "Please enter your Android PIN"
Message: "Unlock to access Celo funds"

If there's character limit issues on the title, perhaps: "Enter your Android PIN" or "Enter Android PIN".

**Comment by annakaz** [comment]
Closing as this is no longer relevant with custom PIN screen
