### ISSUE TITLE
snap add gas estimation

### ISSUE THREAD

**Issue by alecps** [celo-org/celo-monorepo#10259]
- replace hard coded gas parameters with a gas estimation that happens within the snap, and takes the alternate fee currency into consideration
- look into adding code that intelligently selects the user's feeCurrency based on their balance

**Comment by montera82** [comment]
should we close this tasks? @alecps @martinvol 
given the comment on https://github.com/orgs/celo-org/projects/171/views/1?pane=issue&itemId=27249623

**Comment by martinvol** [comment]
I'd close this one after the implementation is ready and leave this issue to track that.
