### ISSUE TITLE
Core contract upgrade to Node 18: CLI, Celo tool, SDK

### ISSUE THREAD

**Issue by product-matt** [celo-org/celo-monorepo#10251]

**Comment by soloseng** [comment]
- [x] Passing CLI test
- [ ] Passing env-test
- [x] Passing phone-number-privacy/combiner test
- [x] Passing phone-number-privacy/common test
- [x] Passing phone-number-privacy/monitor test (no test found)
- [x] Passing phone-number-privacy/signer test
- [x] Passing sdk/base test
- [x] Passing sdk/connect test
- [x] Passing sdk/contractkit test
- [x] Passing sdk/cryptographic-utils test
- [x] Passing sdk/encrypted-backup test
- [x] Passing sdk/explorer test
- [x] Passing sdk/governance test( no test found)
- [ ] Passing sdk/identity test
- [x] Passing sdk/keystores test
- [x] Passing sdk/network-utils test
- [x] Passing sdk/phone-utils test
- [x] Passing sdk/transaction-uri test
- [x] Passing sdk/utils test
- [x] Passing sdk/wallets/wallet-base test (no test found)
- [x] Passing sdk/wallets/wallet-hsm test (no test found)
- [x] Passing sdk/wallets/wallet-hsm-aws test 
- [x] Passing sdk/wallets/wallet-hsm-azure test
- [x] Passing sdk/wallets/wallet-hsm-gcp test
- [x] Passing sdk/wallets/wallet-ledger test
- [x] Passing sdk/wallets/wallet-local test
- [x] Passing sdk/wallets/wallet-remote test
- [x] Passing sdk/wallets/wallet-rpc test
- [ ] All test passing in CI

**Comment by soloseng** [comment]
Closed in favor of #10273
