### ISSUE TITLE
[investigate] snap gas estimation

### ISSUE THREAD

**Issue by montera82** [celo-org/celo-monorepo#10287]

**Comment by montera82** [comment]
The blockchain team seems to suggest that using the gasPrice minimum should be OK.
But on trying that i get the below error, making me inclined towards using the 10x as recommended by the wrapper library.
Happy to close this investigation though.

Ref slack discussion : https://celo-org.slack.com/archives/CNJ7KTHQU/p1683803702820669

cc @alecps @martinvol 


`
error: {"reason":"processing response error","code":"SERVER_ERROR","body":"{"jsonrpc":"2.0","id":51,"error":{"code":-32000,"message":"intrinsic gas too low"}}\n","error":{"code":-32000},"requestBody":"{"method":"eth_sendRawTransaction","params":["0xf87e2b850323be0a98826aa494874069fa1eb16d44d622f2e0ca25eea172369bc1808094b35cc72f7d9adc3aea731a8e815dd4825b56fafd018083015e0aa0bc157edc933b5b643b1cc5e646c6d83bb5dc85dfff3bd2ebeac7c7f027067ca5a01ef590f989e2278767b1b2f6ea2efb9cfb663990454fec14cdb01652bb7fb9b9"],"id":51,"jsonrpc":"2.0"}","requestMethod":"POST","url":"https://alfajores-forno.celo-testnet.org","transaction":{"nonce":43,"gasPrice":{"type":"BigNumber","hex":"0x0323be0a98"},"gasLimit":{"type":"BigNumber","hex":"0x6aa4"},"feeCurrency":"0x874069Fa1Eb16D44d622F2e0Ca25eeA172369bC1","gatewayFee":{"type":"BigNumber","hex":"0x00"},"to":"0xb35CC72F7d9adc3aea731A8e815dd4825b56FAfd","value":{"type":"BigNumber","hex":"0x01"},"data":"0x","chainId":44787,"v":89610,"r":"0xbc157edc933b5b643b1cc5e646c6d83bb5dc85dfff3bd2ebeac7c7f027067ca5","s":"0x1ef590f989e2278767b1b2f6ea2efb9cfb663990454fec14cdb01652bb7fb9b9","from":"0x504135A5D7D1bec283E8F63A14142b6d3544F723","hash":"0xac9ea5bce5405a24e31c01a81a77fc63e34d7bc230a1136ff180df3107dddcdd"},"transactionHash":"0xac9ea5bce5405a24e31c01a81a77fc63e34d7bc230a1136ff180df3107dddcdd"}
`

**Comment by martinvol** [comment]
Good from my side
