### ISSUE TITLE
npm packages census

### ISSUE THREAD

**Issue by nicolasbrugneaux** [celo-org/celo-monorepo#10292]
After a quick look, we have 58 npm packages shared across 3 organisation (`@celo`, `@celo-tools`, `@clabs`).
We need to investigate and summarize what's up with that. Which ones are up-to-date, deprecated, abandoned, etc.

**Comment by arthurgousset** [comment]
Good onboarding ticket. 
Good way to get on board and learn about the various npm packages.
Currently low prio assigned to @yerdua as a good first issue.

**Comment by arthurgousset** [comment]
@nicolasbrugneaux:

- [ ] Please add link here to your Notion doc for NPM package census

**Comment by aaronmgdr** [comment]
whats next here

**Comment by arthurgousset** [comment]
@shazarre wrote a neat script that fetches NPM package metadata via an API. 
He had a lovely Google Sheet with the output. 

Next step is:
- linking the sheet here (at minimum), copy/pasting a bullet list of the packages here for reference (at best)
- reviewing packages e.g. 
  - which do we (@celo-org/devtooling) want to maintain, which do we (@celo-org/devtooling) want to deprecate
  - which do we want to bring to other team's attention (so they decide on maintenance/deprecation)

Probably part of the Monorepo breakup and modernization epic:
- https://github.com/celo-org/celo-labs/issues/1022

(added this to the epic ✅)
