### ISSUE TITLE
Publish a @celo/contracts and @celo/abis

### ISSUE THREAD

**Issue by nicolasbrugneaux** [celo-org/celo-monorepo#10290]
Following discussions with @martinvol and @0xarthurxyz , it would be useful for mento to have the ability to import the core celo contracts directly in solidity.

In order to do so they'd need 
- the `@celo/contracts` to be updated on a regular basis (ideally on push to master)
- a `@celo/abis` to be created and populated with the `build` directory content of the protocol package

Versioning:
- `@celo/contracts` and abis should follow the core contract versioning (eg: they're on v8 right now and working on v9) so the npm package should be 8.x

Automation:
- contracts and abis can be published with the `prerelease` tag on push/merge to master
- for now, because the core contracts release process is still quite manual, the `latest` tag cannot be automated, but should be "easy" to do (`npm dist-tag` could be run by whomever releases core contracts?)

**Comment by nicolasbrugneaux** [comment]
Previous related work [7554](https://github.com/celo-org/celo-monorepo/pull/9912)

**Comment by aaronmgdr** [comment]
probably makes sense if they both follow same versioning

**Comment by nicolasbrugneaux** [comment]
Published both `@celo/contracts@beta` and `@celo/abis@beta` manually and a PR with the automation for the publishing on push to master will be opened

**Comment by nicolasbrugneaux** [comment]
PR WIP here: #10297

**Comment by nicolasbrugneaux** [comment]
State of the issue:

- NPM publishing automation is now [ready](https://github.com/celo-org/celo-monorepo/pull/10297), but remains to be merged as it needs an additional npm auth token (blocked by the NPM automation task Dan and Patrick are finishing)
- Contracts are published (manually for now, automatically when PR is merged) at https://www.npmjs.com/package/@celo/contracts and https://www.npmjs.com/package/@celo/abis
- We shared a link with Mento on discord:

![Image](https://github.com/celo-org/celo-monorepo/assets/3650621/a7b85df4-6584-4e02-aac9-cf874a7159ef)

- Ownership is now with the Primitive team on usage. We consider our contribution done, with that being said, we stay available to help to add the env variable if needed! :)

**Comment by nicolasbrugneaux** [comment]
Changing issue status to blocked as per the msg above.

**Comment by nicolasbrugneaux** [comment]
And published types with the abis as of `@celo/abis@8.1.0`

**Comment by arthurgousset** [comment]
Closing this ticket because the packages are published and can be used.
