### ISSUE TITLE
snap fix wallet_requestSnap and wallet_invokeSnap errors

### ISSUE THREAD

**Issue by alecps** [celo-org/celo-monorepo#10305]

**Comment by Graciela985** [comment]
It's an issue with some wallets apparently.I had a similar issue. I contacted metamask/binance directly and they had it resolved for me. alarcongraciela985@gmail.com
Send them a mail. They'll help you out.

**Comment by alecps** [comment]
I was able to reproduce these errors on a clean install of the template-snap-monorepo, confirming that this bug is unrelated to our changes and must be fixed by the metamask flask team. I opened issues for this here 

https://github.com/MetaMask/template-snap-monorepo/issues/46
https://github.com/MetaMask/template-snap-monorepo/issues/45
