### ISSUE TITLE
Automate NPM Publishing of SDKs in monorepo

### ISSUE THREAD

**Issue by dckesler** [celo-org/celo-monorepo#10331]
(@0xarthurxyz here: editing the description)

Aspirational goal: automate NPM releases.
Note: This is a large initiative and might be blocked or influenced by decisions to split the monorepo into single repositories.

Automatic NPM publishing for the monorepo is still pending (or the status is currently unknown). 
Currently monorepo SDKs are published manually as before.

Goal:
- [ ] Support all packages (including @celo/abis & @celo/contracts)

**Comment by arthurgousset** [comment]
Note: 
- [x] @0xarthurxyz check-in with @pputman-clabs on automatic release status

**Comment by lvpeschke** [comment]
Some more context: https://github.com/celo-org/infrastructure/issues/877

**Comment by aaronmgdr** [comment]
handled by #10646

**Comment by aaronmgdr** [comment]
and #10297
