### ISSUE TITLE
Users SBAT link to metadata

### ISSUE THREAD

**Issue by nambrot** [celo-org/celo-monorepo#1038]
### Expected Behavior

Users should be able to communicate various information to other users in the ecosystem as specified in https://github.com/celo-org/CIPs/pull/1 and https://github.com/celo-org/CIPs/pull/4:
- The service URL of the attestation service for a validator
- The name/affiliation/picture of the validator, etc.

As per https://github.com/celo-org/CIPs/pull/4, we should:
- Add the ability to set a `metadataURL` property on the `Account` struct
- Have the metadata contain the above information.

### Current Behavior

There is no way to do this.

**Comment by nambrot** [comment]
The metadata MVP data format for now would look as followings. It's basically a chain of statements, where each statement has the following format (inspired by keybase):

- `payload` - the data of the statement itself, as stringified JSON
- `signature` - the signature of the `payload` by the account
- `parent` - the hash of the previous statement
- `hash` - the hash of the payload + signature + parent

(For constraint purposes, we might skip the signature and chain part of things, though it shouldn't be much work).

The payloads that we should support at first are:
- `type: 'name', name: 'Nam Chu Hoai"` Make a statement about an account's name
- `type: 'profile_picture', profile_picture: 'https://gravatar.com/avatar/88015b5f37696b11e5d8fd829f9fec87"` Make a statement about an account's profile picture
- `type: 'proof_dns', domain: 'nambrot.com'` Make a statement about controlling a domain name
- `type: 'proof_twitter', username: 'nambrot', 'tweet': 'https://twitter.com/nambrot/status/948959322008154112'` Make a statement about controlling a twitter account
- `type: 'attestation_url', url: 'https://nambrot.com/celo/attestations'` Make a statement about where users should reveal the phone number to


https://github.com/celo-org/celo-monorepo/issues/300

**Comment by timmoreton** [comment]
So I'm guessing the reason you want to chain these statements together is to do revocation on them? Otherwise I'm not sure I see why that's necessary. Each stands on their own. Also, if they are separate files in a directory, you can find the latest of a specific type immediately without parsing and validating the whole chain.  that's important for e.g. `attestation_url`

**Comment by nambrot** [comment]
So the chain part is a nice bonus in the case where you might not have full control over your host. Without a chain part, the host could pick and choose statements, with a chain, the host can only hide from the end of the chain. I certainly agree it adds complexity and processing, but I imagine each chain is going to be incredibly small (< 10 statements). Also if you didn't care about the chain, you could still just find the statement that you care about and not validate the chain.

**Comment by timmoreton** [comment]
Rather than a chain why not a signed index which lists all of the claims present? Then you get random access and the ability to only DoS all or nothing (not even end of chain). I also wonder whether we should include a timestamp.

**Comment by nambrot** [comment]
The data will be actually handled with https://github.com/celo-org/celo-monorepo/issues/1104
