### ISSUE TITLE
Deprecate gateway fee in ContractKit

### ISSUE THREAD

**Issue by palango** [celo-org/celo-monorepo#10394]
### Expected Behavior

In [CIP-57](https://github.com/celo-org/celo-proposals/pull/383/files) the gateway fee is deprecated and with the Gingerbread hardfork any tx that has `gatewayFee` or `gatewayFeeReceiver` set to non-zero values is rejected.

ContractKit (and maybe other libs) should therefore not expose those to the user any more. However, as the transaction format doesn't changed, those fields should be filled with the respective zero value instead.

**Comment by aaronmgdr** [comment]
this has been handled as of ck 5.1
