### ISSUE TITLE
Replace current phone hashing with scrypt and add salt in mobile

### ISSUE THREAD

**Issue by nambrot** [celo-org/celo-monorepo#104]
### Expected Behavior

- [x] Add a salt and switch encryption library
- [x] Prefix the phone number prior to hashing with `tel://`

### Current Behavior

no salt, using sha

**Comment by nityas** [comment]
FYI @nambrot, unassigned you so someone can pick it up this coming sprint. If you're planning on working on it, feel free to self-assign

**Comment by nambrot** [comment]
Noting that this can't be merged until https://github.com/celo-org/celo-monorepo/issues/1040 is ready.

**Comment by nambrot** [comment]
@jmrossy

**Comment by nambrot** [comment]
Linking https://github.com/celo-org/celo-monorepo/issues/515 which should be done with this ticket

**Comment by jmrossy** [comment]
Plan is no longer to use Scrypt. Closing this.
