### ISSUE TITLE
Create ContractWrapper for GasPriceMinimum

### ISSUE THREAD

**Issue by yerdua** [celo-org/celo-monorepo#1042]
### Expected Behavior

A wrapper should exist in `contractkit` for `GasPriceMinimum`.

### Current Behavior

It does not currently exist, and #475 is blocked. The mobile app needs to be able to estimate gas and relies on this contract to do so. Until this wrapper exists, `walletkit` can't be removed from the mobile app.

**Comment by mrsmkl** [comment]
I have a beginning for this at #1041, but it only has few methods to access data that is needed for that PR

**Comment by aaronmgdr** [comment]
I see one exists. closing this
