### ISSUE TITLE
Investigate GoodDollar's use of `eth_getLogs` RPC calls to Forno and indexed data alternatives

### ISSUE THREAD

**Issue by arthurgousset** [celo-org/celo-monorepo#10475]
⚠️ _Draft: Github issue is doesn't have all context_

Context in this [Slack thread](https://celo-org.slack.com/archives/C05K0V9KF7D/p1691510241415579).

Look into their code base (it’s open source). I think this might be the relevant repo: [GoodDollar/GoodDAPP](https://github.com/GoodDollar/GoodDAPP) (Hadar’s username is sirpy to track commits/PRs he made to optimise RPC calls).

> It seems they have already paused almost all the requests when the tab is not active.
> That may have been the fix they pushed yesterday.

**Comment by arthurgousset** [comment]
@shazarre shared the research on Slack and pinged G$ on Telegram. 

+ [x] Next step:  follow up with them until they migrate to the celoscan API (away from calling Forno directly).

As of today, G$ clients have still been making a lot of ethLogs request per minute in the last days (see chart, source: [grafana](https://clabs.grafana.net/explore?panes=%7B%225qv%22:%7B%22datasource%22:%22--%20Mixed%20--%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22sum%28rate%28%7Bcontainer%3D%5C%22kong%5C%22%7D%20%7C%3D%20%60gooddollar%60%20%7C%3D%20%60getLogs%60%20%5B1m%5D%29%29%20%2A%2060%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22ovysjDTVk%22%7D,%22editorMode%22:%22code%22%7D,%7B%22refId%22:%22B%22,%22expr%22:%22sum%28rate%28%7Bcontainer%3D%5C%22kong%5C%22%7D%20%7C%3D%20%60gooddollar%60%20%7C%3D%20%60getLogs%60%20%5B1m%5D%29%29%20%2A%2060%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22eDNLjvTVz%22%7D,%22editorMode%22:%22code%22%7D%5D,%22range%22:%7B%22from%22:%22now-2d%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1)).



![Image](https://github.com/celo-org/celo-monorepo/assets/46296830/35432b47-3e35-4169-a59f-2cabfd7a112b)


Once they migrate, I’d expect that chart to reflect a significant drop in requests.

**Comment by jessan-clabs** [comment]
Do we have any timeline for this migration to celoscan?

Thanks!

**Comment by arthurgousset** [comment]
It looks like GoodDollar has a PR ready to be merged to replace Forno with the [celoscan.io](http://celoscan.io/):
- https://github.com/GoodDollar/GoodDAPP/pull/4060

I asked if anything else is blocking a release with this PR and shared that we're happy to help if they need any guidance/advice before merging the change.

**Comment by arthurgousset** [comment]
Closing this issue because [GoodDollar has released their wallet](https://github.com/GoodDollar/GoodDAPP/pull/4060#issuecomment-1725351579) and migrated away from using Forno. 
We can see that reflected in the Forno traffic:
<img width="1426" alt="image" src="https://github.com/celo-org/celo-monorepo/assets/46296830/efe0ef90-71cb-477e-80a9-dab4dd4c34b8">

Source: [grafana](https://clabs.grafana.net/explore?panes=%7B%225qv%22:%7B%22datasource%22:%22--%20Mixed%20--%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22sum%28rate%28%7Bcontainer%3D%5C%22kong%5C%22%7D%20%7C%3D%20%60gooddollar%60%20%7C%3D%20%60getLogs%60%20%5B1m%5D%29%29%20%2A%2060%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22ovysjDTVk%22%7D,%22editorMode%22:%22code%22%7D,%7B%22refId%22:%22B%22,%22expr%22:%22sum%28rate%28%7Bcontainer%3D%5C%22kong%5C%22%7D%20%7C%3D%20%60gooddollar%60%20%7C%3D%20%60getLogs%60%20%5B1m%5D%29%29%20%2A%2060%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22eDNLjvTVz%22%7D,%22editorMode%22:%22code%22%7D%5D,%22range%22:%7B%22from%22:%22now-7d%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1)

**Comment by arthurgousset** [comment]
Still looking good

Source: [grafana](https://clabs.grafana.net/explore?panes=%7B%225qv%22:%7B%22datasource%22:%22--%20Mixed%20--%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22sum%28rate%28%7Bcontainer%3D%5C%22kong%5C%22%7D%20%7C%3D%20%60gooddollar%60%20%7C%3D%20%60getLogs%60%20%5B1m%5D%29%29%20%2A%2060%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22ovysjDTVk%22%7D,%22editorMode%22:%22code%22%7D,%7B%22refId%22:%22B%22,%22expr%22:%22sum%28rate%28%7Bcontainer%3D%5C%22kong%5C%22%7D%20%7C%3D%20%60gooddollar%60%20%7C%3D%20%60getLogs%60%20%5B1m%5D%29%29%20%2A%2060%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22eDNLjvTVz%22%7D,%22editorMode%22:%22code%22%7D%5D,%22range%22:%7B%22from%22:%22now-7d%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1)

<img width="1476" alt="image" src="https://github.com/celo-org/celo-monorepo/assets/46296830/172de061-4e38-4035-90a3-5a8c14411f0b">

<img width="1476" alt="image" src="https://github.com/celo-org/celo-monorepo/assets/46296830/67945667-dad0-4ade-ac85-34e2e2eeb75b">
