### ISSUE TITLE
Upgrade Ledger Signer to be able to sign tx besides celo legacy

### ISSUE THREAD

**Issue by aaronmgdr** [celo-org/celo-monorepo#10487]
### Expected Behavior

can sig eip1559 and the new celo tx with feecurrecy but no gatewayfee

### Current Behavior

only signs celo legacy transactions

**Comment by aaronmgdr** [comment]
needs someone smarter than me

**Comment by aaronmgdr** [comment]
@0xarthurxyz can you help figure out who has the knowledge of C and crypto needed to implement this? / who will own?

**Comment by arthurgousset** [comment]
Thanks for logging this here @aaronmgdr!
Brief note for future reference that @timmoreton kindly assigned @kobigurk and took ownership to ping him on TG.

**Comment by arthurgousset** [comment]
Asked for an owner (re point of contact with Kobi) on [Slack](https://clabsco.slack.com/archives/C014SRL4URY/p1707922441630239).

**Comment by aaronmgdr** [comment]
from @marekolszewski 
> On the topic of ledger support, 
@ericnakagawa  is working with a dev shop called Blooo right now to add support for newer transaction types to our ledger app. I would check in with him to confirm that Blooo is not adding anything that might be deprecated soon.


https://clabsco.slack.com/archives/C014SRL4URY/p1709335978942099?thread_ts=1709302433.634719&cid=C014SRL4URY

**Comment by aaronmgdr** [comment]
https://clabsco.slack.com/archives/C014SRL4URY/p1709335978942099?thread_ts=1709302433.634719&cid=C014SRL4URY
