### ISSUE TITLE
`governance:show` CLI command is slow

### ISSUE THREAD

**Issue by arthurgousset** [celo-org/celo-monorepo#10481]
Copy/pasting notes from this [Slack thread](https://celo-org.slack.com/archives/C014SRL4URY/p1691476764159769):

> Does anyone know why the `governance:show` cli command is so slow nowadays?

> I run into the same, so I just checked this with `DEBUG=*`  and (if I read the logs correctly, I’m not very familiar with this), the cli is doing almost 1200 requests to answer.

> First guess would be it iterates over each potential proposal number (there have been ~120 proposals, so would match your number if there's around 10 txs per proposal). Or something with iterating over all validators. And potential retries?

```zsh
DEBUG=* ./bin/run governance:show --proposalID=121 --node https://forno.celo.org/
```

> Looks like there's a ton of requests to `0x41822d8a191fcfb1cfca5f7048818acd8ee933d3`, the GovernanceApproverMultiSigProxy.

**Comment by aaronmgdr** [comment]
BEFORE
```
Running Checks:
   ✔  139 is an existing proposal
newCheckBuilder: 53.773ms
getProposalRecord: 1:02.515 (m:ss.mmm)
proposalToJSON: 10.284s
```

**Comment by arthurgousset** [comment]
(for visibility)
Re-opened the issue and marked it as "QA". So we can close it when the CLI is released in production after QAing.

**Comment by aaronmgdr** [comment]
released!
