### ISSUE TITLE
Release new @celo/identity SDK version (to unblocked ODIS signer release)

### ISSUE THREAD

**Issue by arthurgousset** [celo-org/celo-monorepo#10530]
Releasing ODIS v3.0.0 is blocked by a new release of the `@celo/identity` SDK.
@alecps has been working on the ODIS v.3.0.0 release here: 
- https://github.com/celo-org/celo-monorepo/pull/10462

Once the new `@celo/identity` SDK is released, @alecps is unblocked to release ODIS v3.

**Comment by aaronmgdr** [comment]
looks like this was completed by #10536
