### ISSUE TITLE
Fix warning build.ts in protocol

### ISSUE THREAD

**Issue by martinvol** [celo-org/celo-monorepo#10564]
### Expected Behavior

It builds with now warnings

### Current Behavior

/build/contracts/GasPriceMinimum.json: ENOENT: no such file or directory, open './build/contracts/GasPriceMinimum.json'

**Comment by aaronmgdr** [comment]
I think this happens because GasPriceMinimum is in the 0.8 folder

**Comment by aaronmgdr** [comment]
I fixed
