### ISSUE TITLE
Add CIP-64 support to viem

### ISSUE THREAD

**Issue by yerdua** [celo-org/celo-monorepo#10627]
todo: make an issue in the viem repo, rather than this placeholder thing

**Comment by arthurgousset** [comment]
When this is completed, this small issue will be unblocked:

- https://github.com/0xarthurxyz/txtypes/issues/1

**Comment by arthurgousset** [comment]
Linking the viem PR for this issue (for future reference): 

- https://github.com/wagmi-dev/viem/pull/1379

**Comment by aaronmgdr** [comment]
closing time?

**Comment by arthurgousset** [comment]
Yes
