### ISSUE TITLE
Alias "celocli releasegold" commands to also work for "celocli releasecelo"

### ISSUE THREAD

**Issue by arthurgousset** [celo-org/celo-monorepo#10688]
Question from Tim on [Slack](https://celo-org.slack.com/archives/C014SRL4URY/p1698437130698789): 

> can we alias `celocli releasecelo` commands to also work for `celocli releasegold` ?

Edit: This is a "nice to have" feature and has no urgency [according to Tim](https://celo-org.slack.com/archives/C014SRL4URY/p1698633819030339?thread_ts=1698437130.698789&cid=C014SRL4URY):
> P4, nice to have

**Comment by aaronmgdr** [comment]
to be clear: when I type celocli releasecelo ** i should receive same behavior as what currently happens for celocli releasegold **

**Comment by arthurgousset** [comment]
> to be clear: when I type celocli releasecelo ** i should receive same behavior as what currently happens for celocli releasegold **

Yes, that's my understanding.
