### ISSUE TITLE
Smart contract devs SBAT expect on-chain configuration to be handled uniformly across smart contracts

### ISSUE THREAD

**Issue by m-chrzan** [celo-org/celo-monorepo#1069]
### Expected Behavior

For each configurable `parameter`

* provide a `setParameter` function that
  * validates the argument 
  * emits a `ParameterSet` event on success
* use these setters inside of `initialize` functions.

### Current Behavior

Sometimes we assign to storage variables directly in `initialize`, sometimes we call a `set<parameter>` helper.

Sometimes we emit an event, sometimes we don't.

**Comment by nambrot** [comment]
@yorhodes Do you think this still applies? Agree with @aslawson to close
