### ISSUE TITLE
Notice to Deprecate MetaTransactionWallet and MetaTransactionWalletDeployer Wrappers in ContractKit

### ISSUE THREAD

**Issue by aaronmgdr** [celo-org/celo-monorepo#10766]
The MetaTransactionWallet, MetaTransactionWalletDeployer contracts were created to solve an issue of onboarding new users to Attestation Service v1 which (oversimplifying here) required funds to be sent to pay for sms codes and a small deterence on spamming the system. Since of course new users have no funds typically the MetaTransaction System was setup to allow a third party to pay. The reset of the system (ASv1, Komenci , etc) have all been deprecated and removed) 

These are not governance owned contracts. And the original use case is no longer relevent. As such Contractkit will be considering its wrappers for these as Deprecated shortly and will be remove after. 

as of writing this does not refer to the actual contracts themselves only the wrappers / use in contract kit

however if you need something similar consider an Account Abstraction standard.

**Comment by martinvol** [comment]
Contracts are expected to get deleted soon, and will not be included in the release 12 of the contracts.

Work in progress here: https://github.com/celo-org/celo-monorepo/pull/10859
