### ISSUE TITLE
possible bug in faucet

### ISSUE THREAD

**Issue by sirpy** [celo-org/celo-monorepo#1080]
https://github.com/celo-org/celo-monorepo/blob/8dacf1eb43a914c8d3b612936ad73ed727d0417d/packages/faucet/src/database-helper.ts#L260

First Thanks for open sourcing everything.
While browsing to check how you solved similar challenges we have at GoodDollar, the above line of code seems incorrect to me as trySetLock returns a promise so using it in an if condition would always return true. It should probably be ``&& (await trySetLock)`` or am I missing something?

**Comment by ashishb** [comment]
Thanks, @sirpy for opening this issue. I am assigning it @mcortesi who last touched this code.
