### ISSUE TITLE
[Wallet] Users SBAT send transactions even after disabling security on their phone

### ISSUE THREAD

**Issue by martinvol** [celo-org/celo-monorepo#1090]
### Expected Behavior

If a user disables security on their phone they should see an educational screen to encourage them to enable it again.

### Current Behavior

The app fails and users are unable to send a TX, see https://github.com/celo-org/celo-monorepo/pull/1054#discussion_r326250748 for reference.

**Comment by nityas** [comment]
dupe of #1322
