### ISSUE TITLE
Add integration tests for Anvil migrations

### ISSUE THREAD

**Issue by arthurgousset** [celo-org/celo-monorepo#10999]
The current migration script that generates the Anvil devchain has no tests. Effectively, the devchain is generated and not tested. 

DevTooling wants to start using the Anvil devchain for its test suite and CI, so we need to assert the devchain is setup correctly. For example: 
- https://github.com/celo-org/developer-tooling/pull/243

The goal is to add automated tests that assert the devchain has been generated correctly. 

The Anvil migration script deployed and configures a long list of contracts, each of which probably needs to be tested somehow. On the other hand, we have existing Foundry tests.

**Comment by arthurgousset** [comment]
Idea:

1. Run Anvil with migrations (in another terminal)

    ```sh
    ./migrations_sol/create_and_migrate_anvil_devchain.sh
    ```

1. Run existing tests again local Anvil instance with `--rpc-url` flag

    ```sh
    forge test \ 
    -vvv \ 
    --match-path "test-sol/common/*" \
    --rpc-url=http://127.0.0.1:8546
    ```

**Comment by arthurgousset** [comment]
Ideas for invariants in the integration tests:

1. assert that the core number or list of contracts are deployed
2. assert that they are initialized correctly
3. assert that they are registered in the `Registry`

- [ ] Check if there are integration tests in the ganache devchain setuo

**Comment by arthurgousset** [comment]
~~Started working on this today~~

_Edit: I didn't work on this yet, instead we agreed to prioritise this last week:_
- https://github.com/celo-org/celo-monorepo/pull/11003

**Comment by arthurgousset** [comment]
I'm starting work on this today.

**Comment by lvpeschke** [comment]
Weekly commitment check-in: @arthurgousset can you provide a status update?

**Comment by arthurgousset** [comment]
This issue is closed by this PR:
- https://github.com/celo-org/celo-monorepo/pull/11002

The PR is functionally complete and ready for review. 
The reason it's blocked is an unrelated failing test on CI that I'm debugging. 
Including PR review, I expect this issue to be closed tomorrow Tue, Jun 4.

The progress on this issue is in line with the estimated timeline. The estimated completion was set at Tue, Jun 4.

I'll start working on my new weekly commitment tomorrow as estimated in that issue: 
- https://github.com/celo-org/celo-monorepo/issues/11015
