### ISSUE TITLE
Refactor the storage checks to use Foundry. The current tooling takes the new and old artifacts, and tells you if you have a storage conflict.

### ISSUE THREAD

**Issue by arthurgousset** [celo-org/celo-monorepo#11079]
First starting with this smaller issue: 
- https://github.com/celo-org/celo-monorepo/issues/11083

https://github.com/Rubilmax/foundry-storage-check  [https://book.getfoundry.sh/reference/forge/forge-inspect](https://book.getfoundry.sh/reference/forge/forge-inspect?highlight=layout)

**Comment by lvpeschke** [comment]
@arthurgousset can you either close or move to an epic and milestone?

**Comment by arthurgousset** [comment]
I removed this from the Cel2 board. It's being tracked by our primitive boards and if this is in scope (i.e. required for Cel2) we'll add it back.

**Comment by arthurgousset** [comment]
If relevant this task is tracked here:
- https://github.com/celo-org/celo-monorepo/issues/11098

If it's not tracked, it was effectively a duplicate.
