### ISSUE TITLE
[Epic] Migrate release tooling from Truffle to Foundry

### ISSUE THREAD

**Issue by arthurgousset** [celo-org/celo-monorepo#11078]
```[tasklist]
### Tasks
- [ ] https://github.com/celo-org/celo-monorepo/issues/11079
- [ ] https://github.com/celo-org/celo-monorepo/issues/11082
- [ ] https://github.com/celo-org/celo-monorepo/issues/11083
```

**Comment by martinvol** [comment]
Potentially cose this in favour of https://github.com/celo-org/celo-monorepo/issues/11098

**Comment by lvpeschke** [comment]
@arthurgousset @martinvol the tasks listed here aren't tracked anywhere else.
Are they no longer planned (please close) or still relevant (please move to relevant epic)?

**Comment by arthurgousset** [comment]
Great question, if relevant the tasks are tracked here:
- https://github.com/celo-org/celo-monorepo/issues/11098

If they are not tracked, they were effectively duplicates.
