### ISSUE TITLE
Support devchain with L2 already transitioned

### ISSUE THREAD

**Issue by martinvol** [celo-org/celo-monorepo#11103]
Currently the devchain is created with latest contracts in the commit it is built. The devtooling team ready wants to start working on celi/contractkit changes that require an L2 enabled.

It could be acheived by, after the job that builds L1 (current one) finishes, applying a second set of migrations that:
1. import the state into a new anvil version.
1. Sets the bytecode of `proxyAdminAddress (0x4200000000000000000000000000000000000018)` (this enables the transition)
1. Calls functions to fully enable the contract (for example `CeloDistributionSchedule.activate(...)`)
1. Exports a new state that it's L2.

**Comment by arthurgousset** [comment]
Extra context from [Slack](https://clabsco.slack.com/archives/C02LN9FRME1/p1719416942194519)

**Comment by arthurgousset** [comment]
Starting to work on this today.

**Comment by arthurgousset** [comment]
Marked the PR ready for review: 
- https://github.com/celo-org/celo-monorepo/pull/11107

**Comment by arthurgousset** [comment]
This done in: 
- #11107

**Comment by arthurgousset** [comment]
Follow-on task here: 
- https://github.com/celo-org/celo-monorepo/issues/11139
