### ISSUE TITLE
Migrate remaining unit tests to foundry

### ISSUE THREAD

**Issue by arthurgousset** [celo-org/celo-monorepo#11150]
Follow-on from: 
- https://github.com/celo-org/celo-monorepo/issues/10319

```[tasklist]
### Tasks
- [ ] https://github.com/celo-org/celo-monorepo/issues/10802
- [ ] https://github.com/celo-org/celo-monorepo/issues/10801
```

**Comment by arthurgousset** [comment]
Currently working on `FeeHandlerSeller` tests here:
- https://github.com/celo-org/celo-monorepo/pull/11155

**Comment by arthurgousset** [comment]
I'm estimating around 4 days ("most likely") per contract to migrate. That means 8 days ("most likely") in total for two contracts (2x 4 days). Let's see how I fare.

**Comment by arthurgousset** [comment]
Marked this PR as ready for review:
- https://github.com/celo-org/celo-monorepo/pull/11155

**Comment by arthurgousset** [comment]
Working on `UniswapFeeHandlerSeller` tests here:
- https://github.com/celo-org/celo-monorepo/pull/11171

**Comment by arthurgousset** [comment]
Marked this PR as ready for review:
- https://github.com/celo-org/celo-monorepo/pull/11171

**Comment by arthurgousset** [comment]
Done ✅ Took less time than expected 👍

**Comment by lvpeschke** [comment]
@arthurgousset can you please update "Elapsed + remaining (hours)" and "Time elapsed (hours)"?
