### ISSUE TITLE
Backup Key should have non similar words to reduce possibility / collision of random zero balance wallets.

### ISSUE THREAD

**Issue by rohit-dua** [celo-org/celo-monorepo#1124]
### Expected Behavior

1. The backup key should have words that are not similar to each other and are not within 1 _(or 2)_ edit distance of each other. This will reduce the likelihood of a user entering an invalid word during backup and getting into a zero balance account.

2. The position of words in backup key could still be swapped _(by chance)_ and could result in invalid zero balance account. Investigate the use of backup key where each position has different set of words. eg. 1st word always starts with an 'a' etc. This should have enough entropy to be secure.

### Current Behavior

The backup key has random words which may/may not be very similar to each other. eg: users can enter `bet` instead of `bat` and they would be taken to a zero balance account instead of original account.

**Comment by annakaz** [comment]
We can update the wordlists in our fork of react-native-bip39 
https://github.com/celo-org/react-native-bip39

**Comment by annakaz** [comment]
Should also check that the swap is not already done by the validatemnemonic function- https://github.com/celo-org/react-native-bip39/blob/master/index.js#L91

**Comment by annakaz** [comment]
Closing as the words listed here https://github.com/celo-org/react-native-bip39/blob/master/wordlists/en.json seem to already be chosen to avoid single letter swaps. Note that the "bet"/"bat" example does not occur in the wordlist
