### ISSUE TITLE
Alert Policies/Metrics should provide more context

### ISSUE THREAD

**Issue by mcortesi** [celo-org/celo-monorepo#1136]
### Expected Behavior

For the person "on call", it's important to be able to have some context of what the alert "means"

For example, there's the "blockchain-api-feed-event-counts-absent-alfajores
" policy; whose message is:

```
logging/user/blockchain-api-feed-events for alfajores [SUM]
Violates when: Any logging.googleapis.com/user/blockchain-api-feed-events stream is absent for greater than 1 day
```

For that doesn't really tell anything, unless you already know what you are looking for.

You can extract that:

1) it's about the blockchain api
2) Some log is missing "logging.googleapis.com/user/blockchain-api-feed-events"
3) no idea what that log is for, not what it indicates.

Surely, the one defining the policy has more context, and should provide it within the policy documentation

**Comment by annakaz** [comment]
Also, the alert should list the correct corresponding network. 
This is not the case right now, for example alert " notification-service-querying-absent-alfajoresstaging" was actually an issue with the integration notification service. (https://portal.victorops.com/client/celo#/incident/3640/alertDetails)
