### ISSUE TITLE
Blockchain api should watch for Network Fee changes

### ISSUE THREAD

**Issue by annakaz** [celo-org/celo-monorepo#1144]
### Expected Behavior

The notification service keeps track of `InflationFactorUpdated` events emitted from the StableToken smart contract so app users can see a Network Fee in their feeds. 

### Current Behavior

No tracking of Network Fee

**Comment by annakaz** [comment]
Setting this on the back burner for now cc @nityas

**Comment by jmrossy** [comment]
@annakaz Do you mean blockchain api instead of notification service?
https://github.com/celo-org/celo-monorepo/blob/master/packages/blockchain-api/src/blockscout.ts#L176

**Comment by annakaz** [comment]
Yes, updated thanks!
