### ISSUE TITLE
Better Notifications Grouping for Escrow payments and outstanding requests

### ISSUE THREAD

**Issue by nityas** [celo-org/celo-monorepo#1170]
### Expected Behavior

Escrow payments and outstanding requests should have a grouped screen
[figma link](https://www.figma.com/file/mdNgkyVi2impjf5HRBLq3H/Notifications?node-id=41%3A797) - copy for summary page titles being finalized

<img width="1821" alt="notification_center" src="https://user-images.githubusercontent.com/51388535/66445542-f9e35880-e9fb-11e9-8790-677b3f6e5900.png">

### Current Behavior

each notification is displayed individually

**Comment by coreycelo** [comment]
Updated designs.
