### ISSUE TITLE
Users SBAT select a hosted node setup when in Low Connectivity

### ISSUE THREAD

**Issue by nityas** [celo-org/celo-monorepo#1171]
## Expected Behavior

Goal: get the setup for prompting a sync mode switch/toggle in place with some reasonable starting parameters that can be fine tuned.

### _New Modal_:

We propose a modal that provides a user with the option to enable 'Celo-Lite' mode.

NOTES:
- If geth has restarted more than twice, or syncing has taken longer than 15s, but there is still some internet connection(eg type:unknown) show the modal below.
- same modal template as the 'Are you sure?' Backup Key Modal, with enable being the primary cta:
- a user should only see this modal after they have completed the 'Welcome to Celo' screen
- once ‘Dismiss’ is pressed, we should not show the modal again, to avoid an overly intrusive or confusing experience.

(TODO: are there other signals we can use to fine tune this?)

_____________
**Switch Connection Mode?**

We’ve noticed you’re having some trouble connecting. We recommend enabling **Celo-Lite** mode to allow you to keep using the Celo Wallet with intermittent connection.

Celo-Lite allows you to communicate with the Celo Network through a trusted, hosted node, which can give faster performance than running a node on your device. You can always change this mode in Settings.

[Dismiss]  [Enable Celo-Lite]
_____________

### _Settings Changes_:

In Settings/Preferences (see https://github.com/celo-org/celo-monorepo/issues/1239), add a section called 'Celo-Lite', which leads to the following (same pattern as 'Analytics' Tab)

_____________
Enable Celo-Lite <- >

celo-lite mode allows you to communicate with the Celo Network through a trusted node. You can always change this mode in app settings.
_____________

## Current Behavior

working as a separate build

**Comment by nityas** [comment]
@annakaz - have some ideas on how we can productize this, but I'd like to get your view on what feasible to detect from the OS regarding a device's state. Let's perhaps brainstorm on this later this week?

**Comment by ashishb** [comment]
@annakaz In its current form, the switching is not possible. Here's how it can be enabled.

1. Always write the key in `src/web3/saga.ts` by calling `savePrivateKeyToLocalDisk` in  both ZeroSync and non-zero sync mode => user will be able to switch from geth to hosted node setup (zero sync mode)
2. When the user starts the app for the first time in local geth mode, check if the key exists by calling for `getPrivateKeyFilePath(accountName)` (you already have the account name elsewhere) and checking if the file exists. If it does, get the pincode (which might prompt the user for security screen), get the decrypted key and import it in geth.

**Comment by annakaz** [comment]
Split low connectivity into separate issue- see https://github.com/celo-org/celo-monorepo/issues/1559
