### ISSUE TITLE
Hosted node setup on VM testnets

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-monorepo#1184]
Notes for implementation

- [x] Needs an HTTPS load balancer https://cloud.google.com/load-balancing/docs/https/

- [x] Get SSL certificate via https://www.terraform.io/docs/providers/acme/r/certificate.html, requires moving over to google DNS

- [x] Create DNS RR for {env}-infura.{domain}

Do we keep an internal lb for blockscout? Initial feeling is yes

**Comment by ashishb** [comment]
I had a chat with Trevor, he has some ideas around how to make the Google proxy on VMs work.
