### ISSUE TITLE
Web faucet doesn't transfer funds to escrow

### ISSUE THREAD

**Issue by jmrossy** [celo-org/celo-monorepo#1213]
### Expected Behavior

Web faucet transfers to escrow successfully and app onboarding works with those invite codes

### Current Behavior

Escrow payments made by the web faucet during invite code generation have no value transferred to escrow.
Confirming this by doing the mobile onboarding with an invite code from celotool (works) and another from the web faucuet (escrow contract reports no funds)

**Comment by aaronmgdr** [comment]
just did a run of it and it seemed to work? 

here is what firebase reported back


```
"t":"c","d":{"t":"h","d":{"ts":1570210952489,"v":"5","h":"s-usc1c-nss-261.firebaseio.com","s":"bS6w9mbuKkDHZ28S6OQRlUQBfJhrxkqx"}}} | 132 | 10:42:32.523
-- | -- | --
{"t":"d","d":{"r":1,"a":"s","b":{"c":{"sdk.js.6-6-2":1}}}} | 58 | 10:42:32.525
{"t":"d","d":{"r":2,"a":"q","b":{"p":"/alfajores/requests/-LqMrQ3BHC0co2PTxOoX","h":""}}} | 89 | 10:42:32.526
{"t":"d","d":{"r":1,"b":{"s":"ok","d":""}}} | 43 | 10:42:32.581
{"t":"d","d":{"b":{"p":"alfajores/requests/-LqMrQ3BHC0co2PTxOoX","d":{"beneficiary":"c0669fab24d7422813072f18b6e1888c44c78ebd","status":"Pending","type":"Faucet"}},"a":"d"}} | 173 | 10:42:32.582
{"t":"d","d":{"r":2,"b":{"s":"ok","d":{}}}} | 43 | 10:42:32.608
{"t":"d","d":{"b":{"p":"alfajores/requests/-LqMrQ3BHC0co2PTxOoX","d":{"status":"Working"}},"a":"m"}} | 100 | 10:42:32.744
{"t":"d","d":{"b":{"p":"alfajores/requests/-LqMrQ3BHC0co2PTxOoX","d":{"goldTxHash":"0x3378b09e09fb4089a147e8868e9ab02b0db878dd80bdaf35907374a45ea72a09"}},"a":"m"}} | 163 | 10:42:33.098
{"t":"d","d":{"b":{"p":"alfajores/requests/-LqMrQ3BHC0co2PTxOoX","d":{"dollarTxHash":"0x48eeb8a188fd05779698d924b3399fb7626c4f48337b267c959ee72aec1ca9b9"}},"a":"m"}} | 165 | 10:42:37.497
{"t":"d","d":{"b":{"p":"alfajores/requests/-LqMrQ3BHC0co2PTxOoX","d":{"status":"Done"}},"a":"m"}} | 97 | 10:42:42.518
{"t":"d","d":{"r":3,"a":"n","b":{"p":"/alfajores/requests/-LqMrQ3BHC0co2PTxOoX"}}}

```

address I used  "c0669fab24d7422813072f18b6e1888c44c78ebd" (i generated this address awhile ago like july) 

This was done while running on localhost. 

Has there been a change in network?  its using `alfajores` for all right now.

**Comment by aaronmgdr** [comment]
Oh im sorry I misunderstood this issue. 

You're saying for Invite there are no escrow funds.  not that faucet in general is broke.

**Comment by aaronmgdr** [comment]
id start here projects/faucet/src/database-helper.ts
