### ISSUE TITLE
[Web] Flag of country is not shown while country search suggestion is shown when user enter the country name in “Country” field.  

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#1226]
**Repro on**  Chrome (77.0)
**Does not repro on** Firefox (69.0.1)
**Priority:** Low
**Web URL:** https://celo.org/build/wallet  
**Repro Steps:** 
1. Launch the web URL. 
2. Click on Country fields. 
3. Enter the country name. 
4. Observe 

**Impact:**  Bad user experience. 
**Investigation:** The issue does not repro for mWeb. 
**Current Behavior:**  Flag of country is not shown
**Expected Behavior:** Flag of country should be shown 
**Attachment:** Web_FlagOfCountryIsnotShown.png
![Web_FlagOfCountryIsnotShown](https://user-images.githubusercontent.com/55572027/66313624-4cefd980-e930-11e9-8609-0febcaf23fc7.PNG)

**Comment by Lss-Ankit** [comment]
While doing ad-hoc testing on lower-end devices it is observed that the flag of the country is not shown on country search suggestion while sign up
**Repro devices:** Samsung s4 mini (4.4.2), Samsung Galaxy Grand Prime (5.1.1), Samsung  Galaxy S4 (5.0),  HTC one m9+ (5.0.2),
**Does not repro on** Moto E (4.4.4), Samsung Galaxy A5 (6.0.1),  Samsung Galaxy A5 (7.0). 
Attachment: Android_FlagIssue.png
![Android_FlagIssue](https://user-images.githubusercontent.com/55572027/66627087-2d9aca00-ec18-11e9-8bd7-309f2911d63f.png)

**Comment by aaronmgdr** [comment]
If this is happening on both web and application its likely an issue in celo/utils

**Comment by tarikbellamine** [comment]
@aaronmgdr should this still be open?

**Comment by aaronmgdr** [comment]
I think we can close as this webpage no longer has this feature

**Comment by Lss-Ankit** [comment]
Hi @tarikbellamine @aaronmgdr I have verified this issue for latest Android Internal Build v1.2.0 (1004294314) on lower end devices and observed that issue is still reproduced.
**Repro on devices:** Samsung Galaxy S4(4.4.2) , Samsung Galaxy A3(5.0.2)
**Does not repro on devices:** Samsung Galaxy A5(7.0)

**Comment by aaronmgdr** [comment]
please open a different issue this was for web

**Comment by Lss-Ankit** [comment]
FYI, @aaronmgdr filed issue for Mobile. here is the ticket for the same : https://github.com/celo-org/celo-monorepo/issues/5442
CC: @tarikbellamine
