### ISSUE TITLE
[Android] "You've received # celo Gold" text is shown on received notification for user B even when user  A has sent cUSD. 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#1230]
**App version:** Play store build v1.5.0
**Does not repro:** v1.4.2 
**Repro on:**  Samsung Galaxy S4 (5.0.1), Samsung j7 prime (6.0.1), Samsung Galaxy A8+ (8.0.0) 
**Priority:** Medium
**Testing Account:** (315) 678-6563/[Backup Kay](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit?usp=sharing)

**Pre-condition:** User B app should be running in the background while user A sending the payment. 
 
**Repro Steps:** 
1. Launch the app. 
2. Tap on + tab. 
3. Select any celo user i.e User B. 
4. Proceed the payment. 
5. Make sure the app is running in the background. 
6. Observe received notification for user B. 

**Investigation:** Issue does not reproduce when user B received the notification for payment request. 
**Impact:** Users may get confused as they received cUSD but seeing notification of cGLD. 
**Current Behavior:**  "You've received # celo Gold" text is shown on received notification
**Expected Behavior:** “You’ve received # celo dollar” text should be shown on a received notification. 
**Attachment:** [Android_NotificationIssue.mp4](https://drive.google.com/file/d/1FrSvZg0QMFeJjsCm51Owk9NngAscfzC7/view?usp=sharing) (Bug observe after 1:20 sec)

**Comment by Lss-Ankit** [comment]
@annakaz  I am blocked to verify this issue on new zero-sync build v1.5.0 due to this issues #1339

**Comment by Lss-Ankit** [comment]
Verified with iOS test flight build v1.5.0 (10) and observed that issue: "You've received # celo Gold" text is shown on received notification for user B even when user A has sent cUSD. 

Attachment: IOS_PushNotificationIssueuGLD.png
![IOS_PushNotificationIssueuGLD](https://user-images.githubusercontent.com/55572027/67474915-dca4c000-f672-11e9-9851-71226d89e500.PNG)

**Comment by Lss-Ankit** [comment]
@jmrossy Verified Android build v1.5.1 (Pilot Network) and iOS build 1.5.1 (14) observed that issue is fixed as "You've received # celo Dollar" text is shown on received notification for user B when user A has sent cUSD.

**Comment by jmrossy** [comment]
Yes, this was fixed yesterday, thanks!
