### ISSUE TITLE
[Android]  “Payment Request”  section is not getting removed from “Payment requests” screen even when user  has already proceed for that payment direct from received notification.

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#1231]
**App version:** Play store build v1.5.0
**Repro on:**  Samsung Galaxy S4 (5.0.1), Samsung j7 prime (6.0.1), Samsung Galaxy A8+ (8.0.0) 
**Priority:** Medium 
**Testing Account:** (315) 678-6563/[Backup Kay](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit?usp=sharing)

**Pre-condition:** 
1. User B app should be running in the background while user A sending the payment request. 
2. User B should not have any payment requests before.
 
**Repro Steps:** 
1. Launch the app from device 1. 
2. Tap on the + tab and select any celo user. 
3. Send a payment request for user B. 
4. Make sure User B’s app is running in the background. 
5. from device 2, User B tap on received payment request notification. 
6. Proceed for payment to user A. 
7. The observe Payment request section is not getting removed.
 
**Investigation:** Payment Request section is not shown if the user proceeds for payment after tapping on the Review button on the “Payment request” section. 
**Impact:** Users may get confused about seeing the Payment request section for which they had already done the payment.  
**Current Behavior:**   “Payment Request”  section is not getting removed 
**Expected Behavior:** “Payment Request”  section should be removed 
**Attachment:** [Android_PaymentRequestIssue.mp4 ](https://drive.google.com/file/d/1eaLwGlp6qFtMaJUGYunvCWp4e00ClrKp/view?usp=sharing)(Bug observe after  1:20  sec)

**Comment by jmrossy** [comment]
@i1skn did you fix this recently?

**Comment by jmrossy** [comment]
Just tested, confirmed fixed

**Comment by Lss-Ankit** [comment]
Verified with Android play store build v1.6.0 and found that issue is fixed
