### ISSUE TITLE
Create 'Preferences' and 'Help' sections in Settings

### ISSUE THREAD

**Issue by nityas** [celo-org/celo-monorepo#1239]
### Expected Behavior

Create two new nested sections

Preferences Section:
Celo-Lite (toggle, once added)
Analytics (toggle)
Language > (no change, routes to current language screen)
Currency > (no change, routes to currency screen)

Help Section:
FAQ > (routes to FAQ page on website)
Send Issue Report > (no change, routes to issue report share sheet)
Terms of Service > (routes to TOS page on website)
Licenses > (no change, routes to licenses screen)

### Current Behavior

We are starting to see some clutter in the settings screen

**Comment by nityas** [comment]
Note that, once completed, The toggle option for https://github.com/celo-org/celo-monorepo/issues/1171, should be the second option within the Preferences Screen.

**Comment by annakaz** [comment]
Closing as this is no longer relevant with new resdesign
