### ISSUE TITLE
Visitors SBAT see Privacy page in same style/layout as FAQ

### ISSUE THREAD

**Issue by aaronmgdr** [celo-org/celo-monorepo#124]
### Expected Behavior

Keep Visual consistency and put titles on side. and use our new fonts

### Current Behavior

Old layout / typography

**Comment by tjlahey** [comment]
[figma link](https://www.figma.com/file/HzDfZq4jvFNgUvPuPmeC80Ss/Website-3.0?node-id=2454%3A78)

**Comment by tjlahey** [comment]
[figma link](https://www.figma.com/file/HzDfZq4jvFNgUvPuPmeC80Ss/Website-3.0?node-id=2454%3A156)
