### ISSUE TITLE
Texts with our custom font are not vertically centered when lineHeight is set

### ISSUE THREAD

**Issue by jeanregisser** [celo-org/celo-monorepo#1242]
### Expected Behavior

Texts should be vertically centered within their bounding box when we are using our custom font (HindSilguri) and `lineHeight` is set.

### Current Behavior

Texts are not vertically centered within their bounding box when their are using our custom font (HindSilguri) and `lineHeight` is set.

This makes it difficult to center align things vertically.

Example showing the problem (added background color to make it clear):
![Screenshot 2019-08-06 at 15 01 37](https://user-images.githubusercontent.com/57791/66379527-de555f00-e9b5-11e9-920e-dd6cc23a6ebd.png)

**Comment by jmrossy** [comment]
*From @jeanregisser on Slack:*
there's something off with RN and our custom font, here I'm facing a slight jump in TextInput when there's a placeholder value in it on Android.
With the default font it doesn't happen
I'll leave it for now, but hope we can fix it. Probably linked to the same thing that makes us specify the lineHeight too.

**Comment by jeanregisser** [comment]
This doesn't happen anymore with the font used in the new design. Closing.
