### ISSUE TITLE
Wallet should calculate tobin tax for gold exchanges

### ISSUE THREAD

**Issue by jmrossy** [celo-org/celo-monorepo#1249]
### Expected Behavior

The contract should be queried to get the actual fee

### Current Behavior

The UI is all done for #955 but the fee is hardcoded

**Comment by annakaz** [comment]
Will want to call `computeTobinTax()` on Reserve contract

**Comment by annakaz** [comment]
Blocked on this until a new network is deployed with an updated Reserve contract 

Edit: can actually use .call() to avoid sending a transaction but get the updated fee

**Comment by annakaz** [comment]
We will either have to start using contractkit, or update the deprecated walletkit to interact with the Reserve contract

**Comment by jmrossy** [comment]
Or just hack in the Reserve contract manually into the wallet, though I don't recommend that.
I'd _prefer_ to use contract kit but realistically we may just have to update wallet kit for now.
@annakaz WDYT?

**Comment by annakaz** [comment]
Good point- we can use contractkit to expose the raw contract, then manually call it from there
