### ISSUE TITLE
Users SBAT see switched currency order on home screen

### ISSUE THREAD

**Issue by nityas** [celo-org/celo-monorepo#1261]
### Expected Behavior

[Figma](https://www.figma.com/file/Pp1N48FwfpBzb4b2ggpsjR/Local-Currency?node-id=0%3A1) (includes examples)

**Wallet Balance**
<img width="2172" alt="balance" src="https://user-images.githubusercontent.com/51388535/66526502-c3feac80-eaad-11e9-927c-be321c8b9b95.png">
Changes:
* "Celo Dollar" text removed
* Local currency and CUSD swapped in priority

Note: The local currency mockup shows both the currency symbol (€) and acronym (EUR). This is a bit redundant for Euro, but not so with $/MXN. 
Some options: 
* Only show acronym
* Be dynamic based on country (sometimes show symbol, sometimes show both)
* Always show both

**Transaction Feed** 
<img width="2451" alt="feed" src="https://user-images.githubusercontent.com/51388535/66444816-8b050000-e9f9-11e9-91bd-1db7acda5d30.png">
Changes:
* CUSD value is removed
* Local currency elevated
* Currency symbol added

**Transaction Drilldown**
<img width="1600" alt="drilldown" src="https://user-images.githubusercontent.com/51388535/66444811-85a7b580-e9f9-11e9-8165-3dda3bdbf1ab.png">
Changes:
* CUSD balance added for Non-USD local currency
* Text weight for text displaying comment went from Light -> Regular

### Current Behavior
- cUSD on top
- both currencies in feed
- no cUSD in drilldown

**Comment by coreycelo** [comment]
Added designs.

@nityas Check out note under Wallet Balance above.

**Comment by Pedro-vk** [comment]
@nityas @jmrossy 
The scope of this user story is "_Users SBAT see switched currency order on home screen_" or all the changes that are in the description?

**Comment by nityas** [comment]
@Pedro-vk the scope is the changes in the description- thanks for clarifying!

**Comment by nityas** [comment]
Noticed on the latest build that the order at the top of the home screen is switched. However, the transaction feed and drilldown changes have not been implemented, reopening
