### ISSUE TITLE
Validators SBAT use ephemeral node keys

### ISSUE THREAD

**Issue by asaj** [celo-org/celo-monorepo#1268]
### Expected Behavior

Validators do not need to explicitly set their nodekey, and a random one will be set automatically, and validator direct connections will still work.

### Current Behavior

Validators explicitly set their nodekeys to their consensus private key

**Comment by asaj** [comment]
According to @kevjue, setting the nodekey to the consensus key should no longer be necessary, so this may be as easy as modifying our infrastructure and validator instructions to no longer do this.

**Comment by nambrot** [comment]
Since we are basically reverting https://github.com/celo-org/celo-blockchain/pull/348, would you remind removing this code as well?
