### ISSUE TITLE
[Android] User is unable to scan the QR code after canceling the payment send or request and navigate back to QR code scanner screen. 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#1270]
**App version:** Play store build v1.5.0
**Repro on:**  Samsung j7 prime (6.0.1),  Moto z play (7.0), Samsung Galaxy A8+ (8.0.0) 
**Priority:** Medium 
**Testing Account:** (315) 678-6563/[Backup Kay](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit?usp=sharing)
 
**Repro Steps:** 
1) Launch the app. 
2) Tap on “QR code icon”.
3) Tap on the Scan code button. 
4) Scan the QR code of another user.  
5) Make sure QR code is scanned and the user is redirected to the “Send or Request” screen. 
6) Tap on the “Cancel” button. 
7) Tap on the “Cancel” button on the “Send or Request” screen with the contact screen. 
8) Make sure the user is redirected to the QR code scanner screen. 
9) Try to scan the QR code of another user. 
10) Observe. 

**Investigation:** Issue also repro when user taps on “Scan Code to send or request payment” on “Send or request” screen with contact number if user canceling the payment send or request 

**Impact:** User is blocked to scan the QR code. 

**Current Behavior:** User is unable to scan the QR code
**Expected Behavior:** User should be able to scan the QR code. 

**Suggestion:** User should redirect to QR code scanner screen instead “Send or request” screen with contact number after canceling the payment send or request. 

**Attachment:**[Android_QRCodeIssue.mp4](https://drive.google.com/file/d/16ILdVzOx2whw9Lz8T2I5jeu1K1RLL7eu/view?usp=sharing) (Bug observe after 25 sec)

**Comment by Lss-Ankit** [comment]
@jmrossy Verified with iOS Test Flight build v1.5.0 (10) and found that issue is reproduced for iOS
 => User is unable to scan the QR code after canceling the payment send or request and navigate back to QR code scanner screen

Attachment: [iOS_QRScanningIssue.MP4](https://drive.google.com/file/d/1wFvpr6Xa0caSN5oOdrjQDpXjRCBr7-rP/view?usp=sharing)

**Comment by jmrossy** [comment]
@Lss-Ankit Thanks for checking but a v.1.5.0 build won't have the fix. For all fixes, you'll need to wait until the next version. Please verify again with v.1.5.1 which we're planning to ship later this week.

**Comment by Lss-Ankit** [comment]
@jmrossy Thanks for the update! will verify this issue once v1.5.1 will be released.

**Comment by Lss-Ankit** [comment]
Verified with iOS test flight build 1.5.1(14) , Android Play store build v1.5.1 (104694405) and found that issue is fixed
