### ISSUE TITLE
 [Android] Continuous loading indicator is shown  on “Review Invite” screen when user re invite the same user.

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#1271]
**App version:** Play store build v1.5.0
**Repro on:**  Samsung j7 prime (6.0.1),  Moto z play (7.0), Samsung Galaxy J7 pro (8.1.0) 
**Priority:** Medium 
**Testing Account:** (315) 678-6563/[Backup Kay](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit?usp=sharing)
 
**Repro Steps:** 
1) Launch the app. 
2) Tap on the Cog icon. 
3) Tap on the “Invite” option. 
4) Tap on any celo contact user. 
5) Tap on “Invite with SMS” or “Invite with Whatsapp” option. 
6) Make sure the invitation has been sent and the user is redirected “Wallet” screen. 
7) Repeat steps 2 to 4. 
8) Observe Continues loading indicator is shown. 

**Investigation:** The issue does not repro after cold launch the app. 
**Current Behavior:** Continues loading indicator is shown  
**Expected Behavior:** “Invite with SMS” or “Invite with Whatsapp” and Cancel options should be shown.
**Attachment:** [Android_ContinuesLoadingIndicatorisshown.mp4](https://drive.google.com/file/d/1etg2S3q2miuCwpiRp8b4-w_uShNxZbbh/view?usp=sharing) (Bug observe after 1:21 sec)

**Comment by Lss-Ankit** [comment]
@jmrossy Verified with Android v1.5.2 (101548777) integration build  and observed that issue is still reproduced. 

- Continuous loading indicator is shown on “Review Invite” screen when user re invite the same user.

Attachment: [Android_ContinuosLoading_InviteScreenIssue.mov](https://drive.google.com/file/d/1Ekwj6iPmiI_-25--2ZnDgk7tcT4nCZ5t/view?usp=sharing)

**Comment by jmrossy** [comment]
Tested on iOS and Android, confirmed this no longer happens.
Must have been fixed with a few other invite-flow related fixes we've made over the past month

**Comment by Lss-Ankit** [comment]
Hi @tarikbellamine I have verified this issue using latest Android internal build v1.3.0(1004294316) and found issue is fixed
Repro on devices: Vivo V11 pro (10)
