### ISSUE TITLE
[Android] [Suggestion] “New account balance” should be shown on “Review Payment” screen instead of “Send or Request” screen while sending cUSD. 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#1272]
**App version:** App store v1.4.2, Celo staging v1.4.2, Play store v1.5.0
**Repro on:**  Samsung Galaxy A5 (6.0.1), Moto z play (7.0), Google Pixel XL (8.1.0)
**Priority:** Medium 
**Testing Account:** (315) 678-6563/[Backup Kay](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit?usp=sharing)
 
**Repro Steps:** 
1. Launch the app. 
2. Tap on “+” button. 
3. Select any contact user who has celo app. 
4. Enter an amount in amount fields. 
5. Observe “Estimate fee: #” and “New account Balance: #” is shown on “Send or Request” screen. 

**Impact/Suggestion:** “Send or request” screen should not include the New account balance which shows only the calculation with respect to “Send amount” which leads to confusing the user with the new balance amount.  
**Current Behavior:** “New account balance” is shown on  “Send or Request” 
**Expected Behavior:** “New account balance” should be shown on “Review Payment”  
**Attachment:** [Android_Suggestion_NewAccountBalance.mp4](https://drive.google.com/file/d/1PDitxYVCX5S60-3Ahydang9SPwhMHgx0/view?usp=sharing) (Observe after 10 sec)

**Comment by annakaz** [comment]
Closing as this is no longer relevant following the redesign

**Comment by Lss-Ankit** [comment]
Thanks @annakaz for the update
