### ISSUE TITLE
[Android] White space is not trimmed before the text on ‘Review Payment’ page when user enter text with space in ‘For’ field while sending money. 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#1273]
**App version:** Play store v1.5.0
**Repro on:**  Samsung Galaxy A5 (6.0.1), Moto z play (7.0), Samsung Galaxy Note 9 (8.1.0), Google Pixel 2 XL (9.0)
**Priority:** Low
**Testing Account:** (315) 678-6563/[Backup Kay](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit?usp=sharing)
 
**Repro Steps:** 
1. Launch the app and register in the app. 
2. Tap on the ‘Payments’ app. 
3. Select any contact user to send money. 
4. Enter an Amount into the ‘Amount’ field. 
5. Enter Text with white space in the ‘For’ field. 

**Impact:** Bad user experience. 
**Current Behavior:**  White space is not trimmed 
**Expected Behavior:**  White space should be trimmed 

**Attachment:**  [Android_WhiteSpaceShouldBetrimed.mp4](https://drive.google.com/file/d/11SN7XHldpZsAaalqSjPY3di_3pzBCGlK/view?usp=sharing) (Bug Observed at  24 and 51 secs)

**Comment by Lss-Ankit** [comment]
Verified with iOS test flight build v1.5.0 and observe the same issue: White space is not trimmed before the text on ‘Review Payment’ page when user enter text with space in ‘For’ field while sending money. 

Attachment: IOS_WhiteSpaceIssue.png
![IOS_WhiteSpaceIssue](https://user-images.githubusercontent.com/55572027/67489752-b3465d00-f68f-11e9-8cee-c3d694db2b52.PNG)

**Comment by annakaz** [comment]
Closing out outdated issues

**Comment by Lss-Ankit** [comment]
Hi @annakaz Issue is still reproduced for me on latest Android play store (Internal build) v1.8.2. 
For now i am reopening this ticket. 
Attachment: WhiteSpaceTrimIssue.png
![WhiteSpaceTrimIssue](https://user-images.githubusercontent.com/55572027/83095964-1d116400-a0c2-11ea-9df5-eb53007bca94.png)

**Comment by annakaz** [comment]
Outdated after redesign

**Comment by Lss-Ankit** [comment]
Verified with latest IOS test flight build v1.9.1(41) and observed that issue is still Repro
- White space is not trimmed before the text on ‘Review Payment’ page when user enter text with space in ‘For’ field while sending money.
- **Device Used:** iPhone 6(12.4.7)
- **Attachment:** [WhiteSpaceShouldBetrimed.MP4](https://drive.google.com/file/d/1VaA9QfTkSWa1pgiEPietndiEjkgMk9MC/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
Hi @tarikbellamine I have verified this issue using latest Android internal build v1.3.0(1004294316) and found issue is fixed
Repro on devices: Vivo V11 pro (10)
