### ISSUE TITLE
[Android] Another currency amount is not shown for “Exchange” Activity when user select different currency  from setting > currency screen. 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#1285]
**App version:** Play store build v1.5.0
**Repro on:**  Samsung Galaxy S4 (5.0.1), Samsung j7 prime (6.0.1), Samsung Galaxy A8+ (8.0.0) 
**Priority:** High 
**Testing Account:** (315) 678-6563/Backup Kay
 
**Repro Steps:** 
1) Launch the app. 
2) Tap on the Gold tab. 
3) Tap on the Exchange button. 
4) Enter cUSD amount and Tap on the Continue button. 
5) Enter a mobile PIN. 
6) Make sure Exchange activity is shown on the Wallet tab. 
7) Tap on the Cog icon. 
8) Tap on Currency option
9) Select any currency for Example CAD. 
10) Navigate back to the “Wallet” tab. 
11) Observe. 

**Impact:** User is unable to see the exchange amount in other currency. 
**Current Behavior:** Other currency amount is not shown for “Exchange” Activity. 
**Expected Behavior:** Other currency amounts is should be shown for “Exchange” Activity. 
**Attachment:** Android_OthercurrencyAmountIssue_Exchange.png
![Android_OthercurrencyAmountIssue_Exchange](https://user-images.githubusercontent.com/55572027/66562079-71d68d80-eb78-11e9-997c-c9c153ddc772.png)

**Comment by Lss-Ankit** [comment]
Issue also reproduced on the "Payment Requests" screen. 
Attachment: [Android_RequestPlaymentScreen_CurrenyIssue.mov](https://drive.google.com/file/d/1PkLeSx0ODhNXGqWzWinjlbtj5eUTkM7s/view?usp=sharing)

**Comment by nityas** [comment]
Closing out, taking this on as part of a new feature request (gold/exchange tab) [Exchange], and request grouping #1170

**Comment by Lss-Ankit** [comment]
Another currency amount is not show for "payment activity" Or "Exchange  Activity" 
please let me know is it expected?

**Comment by Lss-Ankit** [comment]
@nityas Another currency amount is not show for "payment activity" Or "Exchange Activity"
please let me know is it expected?
