### ISSUE TITLE
 User blocked to send the invitation via Facebook Messenger/Hangout app.  

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#1308]
**App version:** Play store build v1.5.0
**Repro on:**  Samsung s4 mini (4.4.2), Samsung Galaxy Grand prime (5.1.1), Samsung Galaxy A5 (7.0). 
**Priority:** Medium 
**Testing Account:** (315) 678-6563/[Backup Kay. ](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit?usp=sharing)

Pre-condition: Inviter and invitee should have an account on the Messenger/Hangout app. 
 
**Repro Steps:** 
1) Launch the app. 
2) Tap on the Cog icon. 
3) Tap on Invite option. 
4) Select non-celo contact users. 
5) Tap on “Invite with SMS” option. 
6) Select the Messenger/Hangout app for sending the invitation. 
7) Observe user is not redirected to the respective user's thread and the invitation message is copied. 

**Investigation:** The issue does not repro when the user sends the invitation via device message app and WhatsApp. 
**Impact:** User blocked to send the invitation via Messenger/Hangout app.
**Current Behavior:** User is not redirected to respective user's thread and invitation message is copied
**Expected Behavior:** Users should be able to send the invitation via Facebook Messenger/Hangout app.  
**Attachment:** [Android_InviteVia_Messanger.mp4 ](https://drive.google.com/file/d/1no-iSX1MsJ25O7QEXzJ_2c5rEFgp-4TK/view?usp=sharing)(Bug observe at 1:15  sec)

**Comment by Lss-Ankit** [comment]
@nityas Verified with Test flight build v1.5.0 (10) and found the following: 
Issue: Invitation message is not copied on the "WhatsApp web"  

Note: In iPod Touch 6 (12.4), iPad 5th Gen (13.1), we can not download the WhatsApp app hence verified with WhatsApp web and found the above issue. 
Attachment: [iOS_InviteViaWhatsWeb.mp4](https://drive.google.com/file/d/1Xbcxe_QZMAULRwdIGN7c1-2EGpM9vgST/view?usp=sharing)

**Comment by tarikbellamine** [comment]
Closing because we are no longer supporting FB Messenger or Hangout.
