### ISSUE TITLE
 [Android] [Device Specific] User is unable to enter a decimal value in the “Amount” field on “Send or Request” screen while proceeding for “ Send or request “ payment. 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#1309]
**App version:** Play store build v1.5.0
**Repro on:**  Samsung s4 mini (4.4.2), Samsung Galaxy Grand prime (5.1.1), 
**Does not repro on:** Moto E (4.4.4), Samsung  Galaxy S4 (5.0), Samsung Galaxy A5 (6.0.1), Samsung Galaxy A5 (7.0).  
**Priority:** Medium 
**Testing Account:** (315) 678-6563/[Backup Kay](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit?usp=sharing)
 
**Repro Steps:** 
1) Launch the app. 
2) Tap on + tab. 
3) Tap on Celo contact user. 
4) Enter an amount and tap on “.” (Dot) button on the keypad. 
5) Observe 

**Impact:** User is blocked to send the dollar amount with cent while proceeding for payment. 
**Current Behavior:** User is unable to enter a decimal value in the “Amount” field
**Expected Behavior:** User should be able to enter a decimal value in the “Amount” field
**Attachment:** [Android_BlockedToSendDollarWithCent.mp4](https://drive.google.com/file/d/1m3BQcB9muKeJIYLV9U9Z9o_N5YaXhgPn/view?usp=sharing) (Bug observe at 14 sec)

**Comment by annakaz** [comment]
Closing as this is no longer relevant following the redesign

**Comment by Lss-Ankit** [comment]
I have verified this issue on Valora build v1.0.0(10) and observed that user is not able to enter the decimal value in amount field 
**Verified on devices**: 
1. Samsung galaxy S4(4.4.2)
2. Samsung Galaxy Grand Prime(5.1.1)

**Does not repro on:** Samsung Galaxy A5(7.0)

**Attachment:** [DecimalValue.MOV](https://drive.google.com/file/d/1gLv91VED7MIMOueQn39pa9LJQgybfEbv/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
Hi @gnardini 
I have verified this issue on Android internal build 1.2.0(1004294314) for Withdraw CELO page and Add Funds page also and observe that it is still reproduced.
Repro on devices: Samsung Galaxy A3(5.0.2) , Samsung galaxy S4(4.4.2)

**Comment by Lss-Ankit** [comment]
Hi @gnardini
I have verified this issue on Android internal build 1.3.0(1004294316) for Withdraw CELO page and Add Funds page also and observe that it is still reproduced.
Repro on devices: Samsung Galaxy A3(5.0.2)

**Comment by Lss-Ankit** [comment]
Hi @gnardini Verified with task with using Android play store (internal build) v1.4.0 (1004294317) and found the following: 
- Dot or Comma is not shown when user is on CELO Buy/ Sell screen. 
Verified On device Samsung Galaxy A3(5.0.2) 
Hence reopening the ticket.

**Comment by ValoraQA** [comment]
Hi gnardini, I have verified this issue using Android internal build V1.15.1 & Test Flight build V1.15.1 & observed that issue is fixed now. User is able to enter decimal amount.
**Verfied On Devices:** Samsung Galaxy S4 (4.4.2), Samsung Galaxy S4 (5.0.1)
