### ISSUE TITLE
 [Android] Secuirity PIN is not asked again while proceeding for payment for the second time. 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#1321]
**App version:** Play store build v1.5.0
**Repro on:**  Samsung Galaxy A5 (7.0).  Samsung Galaxy J7 Prime (6.0.1), Samsung Galaxy A8+ (8.0.0)
**Priority:** High
**Testing Account:**310 307 0077/[Backup Kay](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit?usp=sharing)
 
**Repro Steps:** 
1) Launch the app. 
2) Tap on +Tab. 
3) Select celo contact user 
4) Enter an amount and tap on Send button. 
5) Tap on the Send button on the payment review page. 
6) Enter device PIN which is asking for confirmation. 
7) Make sure the amount is sent and the receiver received the amount. 
8) Make a payment to the same user or another user. 
9) Observe payment sent without asking authentication PIN. 

**Investigation:** The issue is repro for both PIN i.e Set PIN as devicePIN and Enter the PIN from the app. 
**Impact:** Any malicious user is able to proceed for successful payment. 
**Current Behavior:** Device PIN is not asked again while proceeding for payment.
**Expected Behavior:** Device PIN should be asked each time when user proceeding for payment
**Attachment:** [Android_DevicePINNotAsked.MOV](https://drive.google.com/file/d/1NZAf3MYF8woCsGOG-r0i02HDFr5sY72e/view?usp=sharing) (Bug observe after  1:20 sec)

**Comment by nityas** [comment]
Good find! this one's not a bug, we're looking to improve the security here: #https://github.com/celo-org/celo-monorepo/issues/1328

**Comment by Lss-Ankit** [comment]
@nityas I have verified this issue again on Android build 1.8.0 (104994308) and found that security PIN not asking every time while transaction  and exachnge activity. 

Attachment: [SecurityPINIssue.mp4](https://drive.google.com/file/d/1-wf2Bz4OJTgceGlq4uDInoeGgH2kPuIb/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
@nityas I have verified issue on latest Android internal build v1.1.0  (1004294309) and Test flight build v1.1.0 (21) and found the following: 

- Security PIN is asked after 5 min when user proceed for payment for the second time. 
as per the comment in task https://github.com/celo-org/celo-monorepo/issues/1328#issuecomment-603975048 it is seems expected hence i am closing this ticket.
