### ISSUE TITLE
[Android] “Incorrect PIN” error message is shown when user proceeding for payment after removing the device PIN.

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#1322]
**App version:** Play store build v1.5.0
**Repro on:**  Samsung Galaxy A8+ (8.0.0), Samsung Galaxy A5 (7.0). 
**Priority:** High
**Testing Account:** 310 307 0077/[Backup Kay](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit?usp=sharing)

**Pre-condition:** Device PIN is set as Celo app security PIN. 
 
**Repro Steps:** 
1) Launch the app. 
2) Proceed for payment. 
3) Make sure Device PIN is asked while proceeding for payment. 
4) Remove the device PIN from the device setting. 
5) Proceed for payment in the app. 
6) Observe “Incorrect PIN” error message is shown 

**Investigation:** while reproducing the issue also observe some time that User is able to send the payment without confirming the PIN if the user is removed the device PIN before proceeding for payment. 
**Impact:** User is blocked to proceed for payment. 
**Current Behavior:** “Incorrect PIN” error message is shown
**Expected Behavior:** Device PIN is a compulsory screen that should display when user removes the PIN from the device.   
**Attachment:** [Android_IncorectPiNisShown.mp4](https://drive.google.com/file/d/1ic81GrgIPBcdcQMSIQdfZ9q05YN80QPk/view?usp=sharing) (Bug observe after 1:04 sec)

### Expected Behavior
<img width="1347" alt="Screen Shot 2019-11-26 at 4 26 05 PM" src="https://user-images.githubusercontent.com/51388535/69683374-79d78780-1069-11ea-992f-aa4a1fc1bfee.png">

[Figma link](https://www.figma.com/file/rheO8jgL6gr7Wgr3BZiRHS/Device-PIN-Changes?node-id=0%3A1)

**Comment by coreycelo** [comment]
Added a Figma link above. There are a few questions in there, adding for thoughts/feedback.

**Comment by coreycelo** [comment]
Added designs

**Comment by jmrossy** [comment]
https://doridori.github.io/android-security-the-forgetful-keystore/#sthash.OldH50oi.GqwncnkP.dpbs

**Comment by jeanregisser** [comment]
We don't use OS PIN anymore.

**Comment by Lss-Ankit** [comment]
Yes thanks @jean for the update
