### ISSUE TITLE
 [Android] ‘cUSD’ balance is not updated automatically when user receives an amount from other users. 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#1335]
**App version:** Zero - sync  build v1.5.0, Play store build v1.5.0
**Repro on:** Samsung Galaxy S6 (7.0), Samsung Galaxy S7 (8.0.0)
**Testing Account:**  680 208 0265/[Backup Kay](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit?usp=sharing)
 
**Repro Steps:** 
1) Launch the app and register into the app as User A from device1. 
2) Register into the app as User B from device2.
3) User A sends a ‘cUSD’ to user B. 
4) Make sure the transaction process successful. 
5) Observe on user B from device 2 ‘cUSD’ balance amount is not get updated automatically

**Investigation:** 
1) ‘cUSD’ balance is shown updated after user sending ‘cUSD’ to other users. 
2) ‘cUSD’ and ‘cGLD’ balance is shown updated when user exchange ‘cUSD’ to ‘cGLD’ or ‘cGLD’ to ‘cUSD’.
3) Balance amount is shown updated after refresh the balance.

**Impact:** User is not updated with the current balance without refreshing the page.  
**Current Behavior:**  ‘cUSD’ balance is not updated automatically 
**Expected Behavior:** “cUSD” balance should update automatically. 
**Attachment:** [Android_CeloDollarsUpdateIssue.mov](https://drive.google.com/file/d/1hpn8LVpSHaS8eb9lOAxLLpjHloQQGWbX/view?usp=sharing) (Bug observe after 44  sec)

**Comment by Lss-Ankit** [comment]
@jmrossy Verified with Android build v1.5.1 (Pilot Network) and observed that issue is fixed as now ‘cUSD’ balance is getting updated automatically when a user receives an amount from other users.

**Can we close this ticket?**
Attachment: [Android_cUSDupdateIssueFixed.mp4 ](https://drive.google.com/file/d/1mLresa_oop0F_5KWDS5LhFAazdXJg9sk/view?usp=sharing)

**Comment by i1skn** [comment]
From the video it seems that the issue was fixed.

**Comment by Lss-Ankit** [comment]
@jmrossy and @i1skn Verified with Android Staging build v1.5.2 and observed that the issue is reintroduced. 
- ‘cUSD’ balance is not updated automatically when user receives an amount from other users.

Attachment: [Android_UpdatedcUSDBalance.mp4 ](https://drive.google.com/file/d/10WKIFxFnLW4fK_9vZUS6NWyEaZwb_Bwp/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
@jmrossy , @i1skn Verified with Android v1.5.2 (101548777) integration build and observed that issue is still reproduced. 

- ‘cUSD’ balance is not updated automatically when user receives an amount from other users

Attachment: [Android_BalancenotUpdated.mov](https://drive.google.com/file/d/1fWsM0lLik-SqYAjMXSdt5DGHg5K44Xme/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
Verified with Android internal Celo staging v1.5.2 (104794304) and observe that issue is fixed as ‘cUSD’ balance is updated automatically when user receives an amount from other users.

**Comment by Lss-Ankit** [comment]
@i1skn , @jmrossy Verified issue with latest Android build Android Celo Alfa build : v1.7.1  and observed that issue is reintroduced. 
- [Android] ‘cUSD’ balance is not updated automatically when user receives an amount from other users

Attachment: [DollarUpdateIssue.mov](https://drive.google.com/file/d/1KlhDH4ZOlD5eymGQf5iP14aU1AqNDU4O/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
@jeanregisser and @jmrossy Verified with Android latest Celo Alfa build v1.8.0 (101848577) and found  that issue is still reproduced. 

Attachment:[CUSD_UpdateIssue.mov](https://drive.google.com/file/d/1u6zVj4nuRSk9f8fHDShorGD8xlPmz-GZ/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
@jeanregisser Verified issue on latest test flight build v1.8.0 (31) and found that issue is reproduced. 

- ‘cUSD’ balance is not updated automatically when user receives an amount from other users. 

Attahcment:[ UpdateIssue.mp4](https://drive.google.com/file/d/1aWlPV8Lc39JQLX1fri33I-TNmYdWQWXu/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
@jmrossy Verified with Android play store (Internal build) v1.8.2 and found that issue is still reproduced. 

Attachment: [CUSD_UpdateIssue.mov](https://drive.google.com/file/d/1h1isq4fSD0LCzRTLWJo5pf8dEDe8ILLT/view?usp=sharing)
