### ISSUE TITLE
[Android] Payment requests is not removed on “Payment Requests > Requests” screen even when user has proceeded for that payment request. 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#1336]
**App version:** Zero - sync  build v1.5.0
**Does not Repro on:** Play store build v1.5.0. 
**Repro on:** Samsung Galaxy S6 (7.0), Samsung Galaxy S7 (8.0.0)
**Testing Account:**  680 208 0265/[Backup Kay](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit?usp=sharing)
 
Pre-condition: User should receive at least one Payment request 
**Repro Steps:** 
1) Launch the app. 
2) Tap on the Review button on the “Payment Request” section. 
3) Tap on any Requests from the “Requests” section. 
4) Tap on the Pay button.
5) Enter a Security PIN. 
6) Observe payment is processed but Payment request is not removed
 
**Investigation:** The issue also repro when users decline the payment. 
**Impact:** Users may feel that the requested payment is not processed yet. 
**Current Behavior:**  Payment requests is not removed 
**Expected Behavior:** Payment requests should removed after processed.  
**Attachment:**  [Android_PaymentRequestIssue.mp4 ](https://drive.google.com/file/d/1Il6BSPcFfmoWgMkFi9upXvnXry4jC017/view?usp=sharing)(Bug observe after 06 and 25 sec)

**Comment by Lss-Ankit** [comment]
@nityas Verified with iOS Test flight build v1.5.0 (10) and found the following: 
1) Payment requests are not removed on the “Payment Requests > Requests” screen even when the user has proceeded for that payment request. 
2) Payment requests are not removed on the “Payment Requests > Requests” screen even after declining the requested payment. 

Attachment: [IOS_PaymentRequestNotRemovedIssue.mp4 ](https://drive.google.com/file/d/1C1PdKkVl-QQYICInpcSgLXhjunUIdIL8/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
@jmrossy Verified with Android build v1.5.1 (Pilot Network) and observed that the Payment request is removed when the user proceeded for requested payment or decline the payment.

**Comment by jmrossy** [comment]
Thanks @Lss-Ankit!
