### ISSUE TITLE
[Android] [Localization] “.” (Dot) is shown instead of “,” (Comma) for payment request decimal amount on “Payment Request” section from “Wallet” tab when app language is “Espanol (America Latina)”. 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#1337]
**App version:** Zero - sync  build v1.5.0, Play store build v1.5.0
**Repro on:** Samsung Galaxy S6 (7.0), Samsung Galaxy S7 (8.0.0)
**Testing Account:**  680 208 0265/Backup Kay

Pre-condition: 
Payment request decimal amount should show on “Payment Request” section from “Wallet” tab  
App language should be “Espanol (America Latina)”. 

 
**Repro Steps:** 
1) Launch the app. 
2) Make sure Decimal amount is shown in Payment request section. 
3) Observe. 

**Investigation:**  Issue also repro for “Exchange Fee” amount on “Review Exchange” page. 
**Current Behavior:** “.” (Dot) is shown instead of “,” (Comma) for payment request decimal amount 
**Expected Behavior:** “,” (Comma) should show for every decimal amount if app language is “Espanol (America Latina)”. 
**Attachment:** Android_DotIsShown.png 
![Android_DotIsShown](https://user-images.githubusercontent.com/55572027/66830318-d4fa6280-ef72-11e9-9b32-7b536e795084.png)

**Comment by Lss-Ankit** [comment]
@nityas  I have verified this issue on  Android internal build v1.1.0 & iOS test flight build v1.1.0(20) and found issue is still repro 

(Dot) is shown instead of “,” (Comma) for payment request decimal amount on “Payment Request” section from “Wallet” tab when app language is “Espanol (America Latina)

**Device:** iPhone 11 (14 beta 6), Samsung Galaxy A70(9.0)
**Attachment:** [DotISShown.PNG](https://drive.google.com/file/d/1t1IBX0baRPGDR5EcR1a9MxCQur93Xq_j/view?usp=sharing)

**Comment by jeanregisser** [comment]
This is the expected behavior now. Comma / Dot depends on the user locale settings. And not the language selection.
