### ISSUE TITLE
[Android] Push notification is not received for user B when user A proceed for payment 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#1339]
**App version:** Zero - sync  build v1.5.0, 
**Does not repro: ** Play store build v1.5.0
**Repro on:**  Samsung Galaxy S6 (7.0), Samsung Galaxy S7 (8.0.0)
**Testing Account:** 680 208 0265/[Backup Kay](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit?usp=sharing)
 
**Repro Steps:** 
1) Launch the app and sign up as user A. 
2) Launch the app and sign up as user B. 
3) Put the app in the background for user B. 
4) User A sends a dollar to User B. 
5) Observe for user B Push notification is not received. 

**Investigation:** Payment request push notification is received for User B when user A Proceed for Payment request. 
**Impact:** User did not get the idea about received payment if an app is a background. 
**Current Behavior:** Push notification is not received
**Expected Behavior:** Push notification should be received
**Attachment:**[ Android_PushNotificationIssue.MOV](https://drive.google.com/file/d/1jOSKVL_J_R__yTFqpLibacR-nAW9Up86/view?usp=sharing) (Bug observe after 44 sec)

**Comment by Lss-Ankit** [comment]
Also, observe that "Payment received" in-app notification is not received for user B when user A proceed for payment.
**Pre-condition:** App should foreground.  
**Note:** "Payment request"  in-app notification is received for user B when user A sends a payment request. 
[Attachment: ](https://drive.google.com/file/d/1WGCGlA7Iw5AjKeK-Hzk9MR4A_hTE4_oe/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
@jmrossy and @cmcewen Verified with Android build v1.5.1 (104694405) (Internal Early Access) and observe that the issue is still reproduced. 

Issue: 
1.  Push notification is not received for user B when user A proceed for payment
2.  "Payment received" in-app notification is not received for user B when user A proceed for payment.

[Attachment](https://drive.google.com/file/d/1X8X06SJeDA9-xGjh7ux5vkSXRJf2HIwa/view?usp=sharing)

**Comment by jmrossy** [comment]
Ivan and I just tested a payment and it works now. I believe it was just a misconfigured firebase db and/or the address normalization issue Ivan fixed.

**Comment by Lss-Ankit** [comment]
@jmrossy Verified with Android build 1.5.1 (Pilot network) and observed that issue is fixed now Push notification of Payment sent and Payment request is shown.

**Comment by Lss-Ankit** [comment]
@jmrossy and @i1skn Verified with Android staging build v1.5.2 and observed that the issue is reintroduced. 
- Push notification is not received for user B when user A proceed for payment. 
**Investigation:** Push notification is received for user B when user A proceeds for the payment request.

Attachment: [Android_PushNotificationIssue.mp4 ](https://drive.google.com/file/d/13orjiwl1W4J5Z00oh4_jEDAk8tG0KW0h/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
@jmrossy and @i1skn Verified with Android Staging build v1.5.2 (104694505) and observed that issue is fixed as both "Payments received" and "Payment Requested" Notifications are received. 
Hence, closing the ticket.

**Comment by Lss-Ankit** [comment]
@jmrossy Verified with Android v1.5.2 (101548777) integration build and observed that issue is reintroduced.hence reopen the ticket. 

- Push notification and in-app notification is not received for user B when user A proceed for payment and payment request. 

Attachment: [Android_In-App&PushNotificationIssue.mov](https://drive.google.com/file/d/1pp3Td0X25MPtohHM9ObBEpEsUpAc0KPs/view?usp=sharing)

**Comment by i1skn** [comment]
It did not work yesterday, but today I've received a bunch of notifications from yesterday and I've tested now and notifications work just fine on `integration`. Hence closing this one.

**Comment by Lss-Ankit** [comment]
Verified with Android v1.5.2 (101548777) integration build and observed that issue is fixed now.

Verified on Devices : Samsung Galaxy S5 (6.0.1), Redmi Note 7 Pro (9.0)

**Comment by Lss-Ankit** [comment]
@jmrossy Verified with Android build 1.7.0 (104894304) and found that issue is reintroduced 

- Push notification is not received for user B when user A proceed for payment and payment request.

Attachment: [Notification.mov](https://drive.google.com/file/d/1hVUCnMvFlhW4BexKYKstGjOh5MD6zsgE/view?usp=sharing)

**Comment by i1skn** [comment]
@cmcewen I think this might be related to `- blockscout logs api doesn’t work, which affects the notification service`, rigth?

**Comment by Lss-Ankit** [comment]
@jmrossy Verified with Android build Android Celo Alfa build : v1.7.1  and found that issue is still repro

- Push notification is not received for user B when user A proceed for payment and payment request.

Attachment: [ANdroid_NotificationIssue.mov](https://drive.google.com/file/d/1Z_0VL_xz6wbNkRIOSdbS2DoWYFv8bQAM/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
@jmrossy @i1skn Verified with iOS test flight build : v1.7.1 (28) and found that issue is still reproduce. Verified on : iPhone 11 Pro (13.3).

- Push notification is not received for user B when user A proceed for payment and payment request.

Attachment : [iOS_Push notification is not received](https://drive.google.com/file/d/167HU4hbrv6CyUGmYQJKOCxnACicGUM5x/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
@jmrossy @annakaz  Verified with Android build: Celo (Dev)_1.7.1 (101748676) and found that issue is still reproduce. 
Push notification is not received for user B when user A proceed for payment and payment request.
Attachment : [NotificationIssue.mp4](https://drive.google.com/file/d/14GTmUiq214iyJUL4y7wmDVqL1i3k7ste/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
@jmrossy and @jeanregisser Verified issue on Android latest celo alfa build v1.8.0 (101848577) and fund the following: 
**Issue:**
- Push and in-app notification is not received by User A when user B send the payment request to User A. 
**Fixed:**
- Push and in app notification is received for User A when user B send the payment to User A
Hence i am reopening the ticket. 
Attachment: [NotificationIssue.mov](https://drive.google.com/file/d/1PpRHij4VIFQXYZLSWYmnHrLEeYoI_K1k/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
@jeanregisser Verified issue on latest test flight build v1.8.0 (31) and found that issue is still reproduced. 
- In- app & Push notification is not received for user B when user A proceed for payment and paymente request. 

Attachment:[ NotificationIssue.mp4](https://drive.google.com/file/d/1FY49I6hl-QxOUPym1jnPuSpeBFzMKLib/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
Hi @annakaz and @jmrossy I have verified this issue again on Android build 1.8.0 (104994308) and found the following 
- Push and in-app notification is not received by User A when user B send the payment request to User A.
Fixed:
- Push and in app notification is received for User A when user B send the payment to User A
Hence i am reopening the ticket.

**Comment by jmrossy** [comment]
While we were investigating the crash yesterday, I found a potential issue that may explain the flakiness of this feature. I'll include the potential fix in with wallet 1.8.2

**Comment by Lss-Ankit** [comment]
@jmrossy Verified with Android play store (Internal Build) v1.8.2 and found that issue is still reproduced. 

- Push and in-app notification is not received by User A when user B send the payment request to User A.

- Push and in app notification is received for User A when user B send the payment to User A
Hence i am reopening the ticket.
Attachment: [NotificationIssue.mov](https://drive.google.com/file/d/1dSOmOiUke4SOnSrcHbR2C8x29qq7RgR4/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
@annakaz @jeanregisser Verified with Celo Alfajores Wallet (Internal early Access) v1.9.4 (105094704) and found the following : 
- Push notification is not received for user B when user A proceed for payment or payment request. 
- Push notification is also not received when user A remind for the payment request to User B. 

Verified on : Google Pixle XL (8.1)

**Comment by Lss-Ankit** [comment]
Hi @annakaz @jeanregisser  I have verified this issue with Android internal build v1.1.0(1004294309) & iOS test flight build v1.1.0(21) and found the following:
Issues: 
- Push notification is not received for user B when user A send payment request.
- Push notification is also not received to user B when user A remind for the payment request .
Fixes: 
- Push and in-app notification are received when user B received payment from User A. 
- Push and In-app notification are received when user B received CELO amount from User A.
 
**Verified on Devices:** iPhone 11 (14 beta 6) , , Samsung Galaxy A70(9.0)

**Comment by Lss-Ankit** [comment]
Hi @annakaz @jeanregisser I have verified this issue with Android internal build v1.2.0(1004294314) & iOS test flight build v1.2.0(26) and found the following:
**Verified on Devices:** iPhone 11 (14 beta 6) , Samsung Galaxy A70(9.0)
**Issues:**
Push notification is not received to user B when user A remind for the payment request .

**Fixes:**
Push notification is received for user B when user A send payment request.

**Comment by Lss-Ankit** [comment]
Hi @annakaz @jeanregisser I have verified this issue with Android internal build v1.2.0(1004294314) on lower end devices and observed that issue is still reproduced.
**Repro on devices:**  Samsung galaxy S4(4.4.2) , Samsung Galaxy A3(5.0.2)

**Comment by Lss-Ankit** [comment]
Hi @tarikbellamine  @jeanregisser I have verified this issue with latest Android Internal Build v1.3.0.(1004294316) & Test Flight Build v1.3.0 (27). and found the following:
Verified on Devices: iPhone 6 (12.4.5) , Vivo V11 pro (10)
Issues:
Push notification is not received to user B when user A remind for the payment request .

**Comment by Lss-Ankit** [comment]
Hi @tarikbellamine @jeanregisser I have verified this issue with latest Android Internal Build v1.3.0.(1004294316) on lower end devices and observed that issue is still reproduced.
**Verified on Devices:** Samsung Galaxy A3(5.0.2), Samsung Galaxy A5(7.0)
**Issues:**
Push notification is not received to user B when user A remind for the payment request .

**Comment by Lss-Ankit** [comment]
Hi @tarikbellamine @jeanregisser I have verified this issue with latest Android Internal Build Test flight build v1.4.0(28) and Android play store internal build v1.4.0(1004294317).
**Verified on Devices:** Vivo V11 pro (10), iPhone 6+(12.4.5)
**Issues:**
- Push notification is not received to user B when user A remind for the payment request .

**Comment by Lss-Ankit** [comment]
Hi @tarikbellamine @jeanregisser I have verified this issue with latest Android Internal Build Test flight build v1.5.1(30) and Android play store internal build v1.5.1(1004294319).
Verified on Devices: Samsung Galaxy A5(7.0),iPhone SE (13.5.1)
Issues:

Push notification is not received to user B when user A remind for the payment request .

**Comment by Lss-Ankit** [comment]
Hi @tarikbellamine @jeanregisser I have verified this issue with latest Android Internal Build Test flight build v1.5.5(34) and Android play store internal build v1.5.5(1004294323).
Verified on Devices: Samsung Galaxy A5(7.0),iPhone SE (13.5.1)
Issues:

Push notification is not received to user B when user A remind for the payment request .

**Comment by Lss-Ankit** [comment]
Hi @tarikbellamine @jeanregisser I have verified this issue with latest Android Internal Build Test flight build v1.6.0(36) and Android play store internal build v1.6.0
Verified on Devices: Samsung Galaxy A5(7.0),iPhone SE (13.5.1)
Issues:

Push notification is not received to user B when user A remind for the payment request .

**Comment by Lss-Ankit** [comment]
Hi @tarikbellamine @jeanregisser I have verified this issue with  Play store Build  V1.6.0 & App store build V1.6.0.
**Verified on Devices:** Samsung Galaxy A5(7.0), iPhone SE (14.2)
Issues:

- Push notification is not received to user B when user A remind for the payment request .

**Comment by Lss-Ankit** [comment]
Hi @tarikbellamine @jeanregisser I have verified this issue with latest Android  internal build V1.7.2(1004294329) & Test Flight build V1.7.2(39) & observed that issue is still reproduced.
**Verified on Devices:** Samsung Galaxy A5(7.0), iPhone XR (14.2)
**Issues:**

- Push notification is not received to user B when user A remind for the payment request .

**Comment by Lss-Ankit** [comment]
Hi @tarikbellamine @jeanregisser I have verified this issue with latest Android internal build V1.8.0 & Test Flight build V1.8.0(40) & observed that issue is still reproduced.
Verified on Devices: Samsung Galaxy A5(7.0), iPhone 6+ (12.4.5)
**Issues:**

- Push notification is not received to user B when user A remind for the payment request .

**Comment by Lss-Ankit** [comment]
Hi @tarikbellamine @jeanregisser I have verified this issue with  latest Android Internal Build V1.9.2(1004294334) & Test Flight Build V1.9.2(44) & observed that issue is still reproduced.
**Verified on Devices:** Samsung Galaxy A5(7.0), iPhone SE (13.4.1)
Issues:

- Push notification is not received to user B when user A remind for the payment request .

**Comment by ole-nov** [comment]
Was fixed by the changes done to the notification service.

**Comment by ValoraQA** [comment]
Hey @aleksey-nov   I have verified this issue using Android internal build V1.15.1 & Test flight build V1.15.1 & observed that issue is fixed now.

- [x] User is able to see Push Notification when user A send payment request to user B. [Attachment](https://drive.google.com/file/d/1AIX6KKa0H0Okx9eNFnlpbJb4e-7VS5NR/view?usp=sharing)
- [x] Also user B get push notification when user A remind to user B by tapping on "Remind" button.[Attachment](https://drive.google.com/file/d/1AIX6KKa0H0Okx9eNFnlpbJb4e-7VS5NR/view?usp=sharing)
- [x] User is able to get In-app notification when user B reminds for request by tapping on "Remind" button. [Attachment](https://drive.google.com/file/d/1jdcUQevIzSf3bgxW-Hh0LMtksYBBvVdE/view?usp=sharing)
**Verified On Devices:** Samsung Galaxy A5(7.0), Samsung Galaxy J5 Prime (8.0), iPhone SE (14.2)
Thanks..!!

**Comment by ValoraQA** [comment]
Hey @aleksey-nov, We have verified this issue using Latest Test flight Build V1.21.0 & observed that User is not able to get in-app notification when user B reminds by tapping on "Remind" button for the amount request sent.

**Devices:** iPhone 12(15.0)
**Attachment:** [Notification not received for remind.mp4](https://drive.google.com/file/d/195PUI0Io41e0vlUsyc18fOUUSYilniQu/view?usp=sharing)
Thanks..!!

**Comment by ValoraQA** [comment]
Hey @MuckT,  We have re-verified this issue on Latest Android Internal Release build, Test flight Release build V1.32.0 & observed that the issue is still reproducible.
We are closing this issue as we have filed the new issue. 
[Issue Link](https://github.com/valora-inc/wallet/issues/2484)
Thanks..!!
