### ISSUE TITLE
Users SBAT historic gold prices in gold tab

### ISSUE THREAD

**Issue by nityas** [celo-org/celo-monorepo#1341]
### Expected Behavior

<img width="1067" alt="Gold Tab" src="https://user-images.githubusercontent.com/51388535/66884612-a38b9200-ef86-11e9-875d-6d2c8da4df34.png">

[Figma](https://www.figma.com/file/Iqu4mAgePHVgKhvKTrGrUP/Gold-Approaches?node-id=10%3A0)

Scope:
* add graphs with historical price + portfolio value
* [out of scope] color changes, design system update coming soon.

To Be decided in kickoff:
- What price granularity is available in charts?
- Which, if any, timeframes to enable/display on graphic initially?

### Current Behavior

What is the current behavior?

**Comment by coreycelo** [comment]
Designs added.

**Comment by annakaz** [comment]
Splitting this into two issues- this one is one related to new Gold Tab graphs, and the other updating the exchange screen UI- https://github.com/celo-org/celo-monorepo/issues/1728
