### ISSUE TITLE
Android] User should not able to proceed for the payment or payment request using his/her own number. 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#1355]
**App version:** zero-sync build: Staging build v1.5.0 (101548577)
**Repro on:**  Galaxy Grand Prime (5.1.1), Samsung J7 Prime (6.0.1)
**Testing Account:**  680 208 0265/[Backup Kay](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit?usp=sharing)
 **Pre-Condition:** User should save his/her number in the contact list. 
**Repro Steps:** 
1) Launch the app. 
2) Tap on + Tab. 
3) Search the user’s own number. 
4) Tap on it and try to proceed for payment. 
5) Observe Payment received activity is shown on the Activity section from the wallet tab. 

**Investigation:** total Celo dollars amount is not changed. 
**Impact:** Total Celo dollars amount does not match with Activity shown on the Activity section.  
**Current Behavior:** User should not be able to proceed for the payment or payment request using his/her own number. 
**Expected Behavior:** User-friendly message should show. 
**Attachment:** [Android_PaymentWithOwnNumber.mp4](https://drive.google.com/file/d/1PgHTw4EgkV20Ex_8DpePRXGQIzLUiYl7/view?usp=sharing) (Bug observe after 39 sec)

**Comment by jmrossy** [comment]
We intentionally want to allow sending to yourself. It's useful for dev testing and/or users who want to test a transaction without losing money

**Comment by Lss-Ankit** [comment]
Okay, thanks for the update.
