### ISSUE TITLE
[Android] [Device specific] App get crashed when user launch the app after installing. 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#1356]
**App version:** zero-sync build: Staging build v1.5.0 (101548577)
**Repro APK:** 1) App-x86_64-alfajores.apk, 2) app-arm64-v8a-alfajores.apk, 3) app-x86-alfajores.apk. 
**Does not repro APK:** app-armeabi-v7a-alfajores.apk.
**Repro on:** Samsung Galaxy S4 mini (4.4.2)  
**Does not Repro:** Moto E (4.4.4), Galaxy Grand Prime (5.1.1), Samsung J7 Prime (6.0.1)
**Testing Account:**  680 208 0265/Backup Kay
 
**Repro Steps:** 
1) Install the using given APK file. 
2) Launch the app. 
3) Observe. 

**Investigation:** In APK file: app-armeabi-v7a-alfajores.apk. Error “Importing Wallet Failed” is shown when user sign up using backup key
**Impact:** User is blocked to use the app and sign up using the backup key 
**Current Behavior:** App get crashed
**Expected Behavior:** User should be able to launch the app successfully and sign up with a backup key. 
**Attachment:**
 1) [Android_4OS_AppCrashed.MOV](https://drive.google.com/file/d/1kMhuniJdQYbbz89SrwO5HK4EKnfRSRpB/view?usp=sharing) (Bug observe after  1:34 sec)
2) [Android_4OS_ImportingFailed_BackupKeyissue.MOV](https://drive.google.com/file/d/1Xe6tw5J_Rtu7D6koNzByc7Lmry1OrIPj/view?usp=sharing) (Bug Observe at 1:08)
3) [Crashlog.txt](https://github.com/celo-org/celo-monorepo/files/3734353/Crashlog.txt)

**Comment by ashishb** [comment]
Crash
```
10-11 17:50:14.350: E/AndroidRuntime(14466): FATAL EXCEPTION: main
10-11 17:50:14.350: E/AndroidRuntime(14466): Process: org.celo.mobile.alfajores, PID: 14466
10-11 17:50:14.350: E/AndroidRuntime(14466): java.lang.UnsatisfiedLinkError: Couldn't load jndcrash from loader dalvik.system.PathClassLoader[dexPath=/data/app/org.celo.mobile.alfajores-2.apk,libraryPath=/data/app-lib/org.celo.mobile.alfajores-2]: findLibrary returned null
10-11 17:50:14.350: E/AndroidRuntime(14466): 	at java.lang.Runtime.loadLibrary(Runtime.java:358)
10-11 17:50:14.350: E/AndroidRuntime(14466): 	at java.lang.System.loadLibrary(System.java:526)
10-11 17:50:14.350: E/AndroidRuntime(14466): 	at ru.ivanarh.jndcrash.NDCrash.<clinit>(Unknown Source)
10-11 17:50:14.350: E/AndroidRuntime(14466): 	at org.celo.mobile.MainApplication.c(Unknown Source)
10-11 17:50:14.350: E/AndroidRuntime(14466): 	at org.celo.mobile.MainApplication.onCreate(Unknown Source)
10-11 17:50:14.350: E/AndroidRuntime(14466): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
10-11 17:50:14.350: E/AndroidRuntime(14466): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4729)
10-11 17:50:14.350: E/AndroidRuntime(14466): 	at android.app.ActivityThread.access$1600(ActivityThread.java:174)
10-11 17:50:14.350: E/AndroidRuntime(14466): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1367)
10-11 17:50:14.350: E/AndroidRuntime(14466): 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-11 17:50:14.350: E/AndroidRuntime(14466): 	at android.os.Looper.loop(Looper.java:146)
10-11 17:50:14.350: E/AndroidRuntime(14466): 	at android.app.ActivityThread.main(ActivityThread.java:5593)
10-11 17:50:14.350: E/AndroidRuntime(14466): 	at java.lang.reflect.Method.invokeNative(Native Method)
10-11 17:50:14.350: E/AndroidRuntime(14466): 	at java.lang.reflect.Method.invoke(Method.java:515)
10-11 17:50:14.350: E/AndroidRuntime(14466): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
10-11 17:50:14.350: E/AndroidRuntime(14466): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
10-11 17:50:14.350: E/AndroidRuntime(14466): 	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by ashishb** [comment]
Cause might be https://stackoverflow.com/a/19681444

**Comment by ashishb** [comment]
https://github.com/KeepSafe/ReLinker might fix this.

**Comment by annakaz** [comment]
Unassigning myself for now as after looking into it, I don't believe this crash is specific to the zeroSync build- can look into this more later but OOF next week
