### ISSUE TITLE
Keep cached inverse of Attestations mapping in Blockchain Api

### ISSUE THREAD

**Issue by jmrossy** [celo-org/celo-monorepo#1360]
Currently, the wallet app lookups every phone number in a user's contact list during the onboarding flow to form a two-way mapping of phone numbers <-> addresses.
This technique is problematic because the view calls get rate limited, causing multiple errors. It's also slow for large contact lists.

A better alternative would be for some service, e.g. blockchain api, to keep a cached list of the inverse mappings for the entire smart contract and decorate activity feed data with this information.

**Comment by annakaz** [comment]
Closes as this no longer seems possible after phone number privacy changes
