### ISSUE TITLE
Make tickets for lockedgold/pos operations in CLI

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-monorepo#1362]

**Comment by nategraf** [comment]
The following issues have been created for the known gaps in CLI feature coverage:
* https://github.com/celo-org/celo-monorepo/issues/1378
* https://github.com/celo-org/celo-monorepo/issues/1377
* https://github.com/celo-org/celo-monorepo/issues/1375
* https://github.com/celo-org/celo-monorepo/issues/1374
* https://github.com/celo-org/celo-monorepo/issues/1373
