### ISSUE TITLE
Use fixidity in "FactionMulExp" precompile

### ISSUE THREAD

**Issue by mcortesi** [celo-org/celo-monorepo#1366]
### Expected Behavior

We don't use fractions anymore, but fixidity. Change the precompile to work with fixidity values.

Usage example in `StableToken`
```solidity
    (numerator, denominator) = fractionMulExp(
      inflationState.factor.unwrap(),
      FixidityLib.fixed1().unwrap(),
      inflationState.rate.unwrap(),
      FixidityLib.fixed1().unwrap(),
      timesToApplyInflation,
      decimals_
    );
```

Tasks:
 - [ ] Change ganache precompile
 - [ ] Change celo-blockchain precompile
 - [x] Change use of fractionMulExp in solidity smart contracts

**Comment by jfoutts-celo** [comment]
```
celo-monorepo/packages/protocol/contracts/common/UsingPrecompiles.sol:29:5:
TypeError: This type is only supported in the new experimental ABI encoder.
Use "pragma experimental ABIEncoderV2;" to enable the feature.
    FixidityLib.Fraction memory a,
    ^---------------------------^
```
So fractionMulExp will need to use unwrapped values.

**Comment by jfoutts-celo** [comment]
Due the current precompile's increased extensibility (that we use for the `decimals` parameter controlling a `StableToken`'s divisibility), and the fact that not much efficiency is gained (looks like just packing and unpacking args), we choose to leave the existing precompile.
