### ISSUE TITLE
electValidators should get the electionGroups more efficiently

### ISSUE THREAD

**Issue by asaj** [celo-org/celo-monorepo#1380]
### Expected Behavior

Use a priority queue such that the first group in the list is always the next group to elect a validator.

### Current Behavior

We fetch the election groups by iterating through the list of eligible groups twice

**Comment by asaj** [comment]
https://github.com/celo-org/celo-monorepo/pull/1292/files#r335014408

**Comment by BatiGencho** [comment]
@asaj  reserved for Ventsi @ Limechain
