### ISSUE TITLE
 [Android] [Random]“Payment sent” transaction is shown twice on “Activity” Section from “Wallet” tab when user proceed for payment while device network connectivity is low. 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#1386]
**Frequency:** 40%
**App version:** zero-sync build: Staging build v1.5.0 (101548577)
**Repro on:**  Galaxy Grand Prime (5.1.1), Samsung Galaxy A8+ (8.0.0)
**Testing Account:**  680 208 0265/Backup Kay

**Pre-condition:** Make sure device network connectivity should be low i.e 2G/3G
 
**Repro Steps:** 
1) Launch the app. 
2) Tap on + tab. 
3) Select any celo contact user. 
4) Proceed for sending cUSD. 
5) Make sure “payment Sent ” Confirming...”  message is shown on the Activity section from the wallet tab. 
6) Wait for a moment. 
7) Observe.
 
**Investigation:** 
1) Issue does not reproduce if device network connectivity is good. 
2) One of Payment Sent section is shown with Confirming… message and another is shown as payment sent with date and time. 
3) After cold launch the app issue Payment sent with confirming message is get removed from the Activity section.
 
**Impact:** User may get confused and assumed that Payment is not sent. 
**Current Behavior:** “Payment sent” section is shown twice 
**Expected Behavior:** Payment sent section is shown only once if user proceed it for only one time. 
**Attachment:** Android_PaymentSentShownTwice.png 
![Android_PaymentSentShownTwice](https://user-images.githubusercontent.com/55572027/66996483-6e9a4f00-f0ee-11e9-8345-1cc2ef2624a6.jpg)

**Comment by annakaz** [comment]
I think what's happening here is the pending notification does not disappear since it is not connected to the network (but somehow the other notification is been able to come through). We can use notification IDs to ensure we don't show the pending notification if the corresponding notification is already in the feed

**Comment by Lss-Ankit** [comment]
@jeanregisser Verified with iOS test flight build v1.5.2 (17) and observed that same issue. 

- “Payment sent” transaction is shown twice on the “Activity” Section from the “Wallet” tab when the user proceeds for payment while device network connectivity is low. 

**Note:** Data saver toggle is enabled. 

Attachment: IOS_TrasactionShownTwice.png

![IOS_TrasactionShownTwice](https://user-images.githubusercontent.com/55572027/71153696-cb85c300-225f-11ea-8495-fbeaf537c072.PNG)

**Comment by Lss-Ankit** [comment]
@jeanregisser While doing smoke testing on IOS Test flight build v1.5.2 (17) and observed that Exchange Activity/transaction is shown twice on the "Gold Activity" section from Gold tab and “Activity” Section from “Wallet” tab if device network connectivity is low. 

**Note:** After cold launch, the app Confirming... text shown transaction/Activity is removed. 

Attachment: IOS_ExchangeActivityTwiceIssue.png

![IOS_ExchangeActivityTwiceIssue](https://user-images.githubusercontent.com/55572027/71254238-59d97200-2350-11ea-97cb-0c19dad8c2ca.PNG)
