### ISSUE TITLE
[Android] Keypad is open for exchange fee tutorial screen  when user open “Exchange Fee” tutorial from “Exchange” screen. 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#1395]
**App version:** zero-sync build: Staging build v1.5.0 (101548577)
**Repro on:** Sony Xperia C4 (5.0), Samsung J7 Prime (6.0.1), Samsung Galaxy A9 Pro (8.0)
**Testing Account:**  680 208 0265/[Backup Kay](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit?usp=sharing)
 
**Repro Steps:** 
1) Launch the app. 
2) Tap on the Gold tab. 
3) Tap on any gold activity. 
4) Tap on “!” beside Exchange free text. 
5) Observe 
**Investigation:** Issue does not reproduce when user taps on “!” beside Exchange fee from the “Review Exchange” screen
**Current Behavior:** Keypad is open for exchange tutorial screen
**Expected Behavior:** Keypad should not open for any tutorial screen. 
**Attachment:** [Android_ExchangeTutorialIssue.mp4](https://drive.google.com/file/d/1W3inAmtsQrT2lblFZZ9084khffHQsCzg/view?usp=sharing) (Bug observe at 03 sec)

**Comment by annakaz** [comment]
Fixed in new exchange trade screen https://github.com/celo-org/celo-monorepo/pull/2167
