### ISSUE TITLE
Devs SBAT reference issues from all contract TODOs

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-monorepo#140]
### Expected Behavior

Audit TODOs in contracts -> raise and prioritize tickets

**Comment by clrblmt** [comment]
List of TODOs here: https://docs.google.com/document/d/1WJVhJtjMpTc3xkpmaLIfXnknTS5t1xgQV6blMzqR3W8/edit#

**Comment by clrblmt** [comment]
https://github.com/celo-org/celo-monorepo/issues/301
https://github.com/celo-org/celo-monorepo/issues/300
https://github.com/celo-org/celo-monorepo/issues/299
https://github.com/celo-org/celo-monorepo/issues/298
https://github.com/celo-org/celo-monorepo/issues/297
https://github.com/celo-org/celo-monorepo/issues/296
