### ISSUE TITLE
Exiting backup flow should show confirmation modal

### ISSUE THREAD

**Issue by jmrossy** [celo-org/celo-monorepo#1400]
### Expected Behavior

https://www.figma.com/file/HGX4zx5XSUeejjfGGI5x3R/Backup-Key-and-Recovery?node-id=170%3A363
When this is fixed, I recommend fixing #195  as well

### Current Behavior

No modal shown.
Modal was partly implemented here: 
https://github.com/celo-org/celo-monorepo/pull/965

**Comment by annakaz** [comment]
Modal exists, closing out this old issue
