### ISSUE TITLE
Backup flow should request pin confirmation before showing backup key

### ISSUE THREAD

**Issue by jmrossy** [celo-org/celo-monorepo#1401]
### Expected Behavior

Get user pin and confirm it before showing the backup key.
This won't be too hard for the typical case where we run a light node but it's tricky for the zero sync mode. See web3/saga.ts

### Current Behavior

No pin required

**Comment by i1skn** [comment]
I've create a separate issue for Forno case - https://github.com/celo-org/celo-monorepo/issues/1557
