### ISSUE TITLE
Wallet needs spanish translations for the new backup flow

### ISSUE THREAD

**Issue by jmrossy** [celo-org/celo-monorepo#1402]
### Expected Behavior

Yes spanish for packages/mobile/locales/en-US/backupKeyFlow6.json
And also packages/mobile/locales/es-419/nuxRestoreWallet3.json

### Current Behavior

No spanish for packages/mobile/locales/en-US/backupKeyFlow6.json

**Comment by jmrossy** [comment]
@nityas Do you know who do ask about this?

**Comment by nityas** [comment]
@jmrossy definitely, can use our translation service-- are the two files you mentioned the ones we need copy for?

**Comment by jmrossy** [comment]
@nityas I believe so yes.
