### ISSUE TITLE
 [Android] User is unable to enter decimal amount in “Amount” field while user proceeding for payment if user has selected Espanol (America latina) language. 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#1411]
**App version:** zero-sync build: Staging build v1.5.0 (101548577)
**Repro on:**  LG Nexus 5 (6.0.1), Samsung Galaxy J7 Pro (8.1.0) 
**Testing Account:**  680 208 0265/[Backup Kay](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit?usp=sharing)

**Pre-Condition:**  Espanol (America Latina) language should be selected as app language from a language setting.  
 
**Repro Steps:** 
1) Launch the app. 
2) Tap on + tab. 
3) Tap on any celo user. 
4) Try to enter the decimal amount in the Amount field. 
5) Observe. 

**Impact:** User is blocked to enter a decimal amount. 
**Investigation:** The issue does not reproduce when a user has selected English as app language. 
**Current Behavior:** User is unable to enter a decimal amount.  
**Expected Behavior:** User should be able to enter decimal value even if the user has selected a different language. 
**Attachment:** [Android_DecimalAmountIssue.mp4](https://drive.google.com/file/d/10UUFVie7TRn4vk1pwhFZV3BGR-Eruic1/view?usp=sharing) (Bug observation at 35 sec)

**Comment by jmrossy** [comment]
This is because for the latin locales, a comma is used to denote decimals instead of a period.

**Comment by Lss-Ankit** [comment]
@jmrossy I have verified with Android play store build 1.5.1 and able to enter decimal amount using comma. 
Also, verified with iOS test flight build v1.5.1 and observed that the comma button is not shown on keypad hence the user is not able to enter a decimal value when language "Espanol (America Latina) " is selected.  


Attachment: [iOS_UnabletoEnterDecimalValue.mp4](https://drive.google.com/file/d/1Wu2mUtwPvu5omk0CaRgbjDvZ24CiRo_M/view?usp=sharing)

**Comment by jmrossy** [comment]
Okay thanks for confirming!

**Comment by Lss-Ankit** [comment]
@jmrossy I have verified with Android internal build 1.2.0 (1004294314) with iOS test flight build v1.5.1 and observed that the comma button is not shown on keypad hence the user is not able to enter a decimal value when language "Espanol (America Latina)" is selected.
**Attachment:**  [CommaIsNotDisplaying.mp4](https://drive.google.com/file/d/1tu9M3jJvTn8czHdwi2eYbxS_7sfAf5ox/view?usp=sharing)

**Comment by gnardini** [comment]
The comma vs dot depends on the language of the OS, not the setting on Valora. If the user has an Argentinian OS for example they see a comma. Feels more P3 than P2 to me.

**Comment by Lss-Ankit** [comment]
Hi @gnardini I have reverified this issue using latest Android internal build 1.2.0 (1004294316) & iOS test flight build v1.3.0(27). Previously user is not able to see ,(Comma) and .(Dot) but now user is able to see dot(.) instead of comma(,) in Espanol language and able to enter decimal amount 
Hence changing priority to P3.

**Comment by Lss-Ankit** [comment]
Hi @gnardini I have verified this issue using latest app store build V1.6.0 & observed that  user is able to see dot(.) instead of comma(,) in Espanol language.
**Repro on devices:** Samsung Galaxy A5(7.0), Samsung Galaxy S4(4.4.2)

**Comment by ole-nov** [comment]
closing because works as intended

**Comment by ValoraQA** [comment]
Hey @aleksey-nov  I have verified this issue using Android internal build V1.15.1  & observed that issue is fixed now. User is able to enter decimal value using "Espanol (America Latina )" language.
**Verified On Devices:** Samsung Galaxy J5 Prime(8.0.0),  Samsung Galaxy A5 (7.0), LG K7i(6.0)
**Attachment:** [UserAbleToEnterDecimalValueInEspanolLang.wmv](https://drive.google.com/file/d/1wixM4ikfM9BW2Zv02R5dmBbtkwSKB1m-/view?usp=sharing)
