### ISSUE TITLE
[Android] [Suggestion] User A should be able to see “Requested Payment” action in “Activity” section on “Wallet” tab when user A send payment request to user B.  

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#1412]
**App version:** zero-sync build: Staging build v1.5.0 (101548577)
**Repro on:** Sony Xperia C4 (5.0), Samsung J7 Prime (6.0.1), Samsung Galaxy A9 Pro (8.0)
**Testing Account:**  680 208 0265/[Backup Kay](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit?usp=sharing)
 
**Repro Steps:** 
1) Launch the app. 
2) Tap on the “+” tab. 
3) Tap on Celo contact user. 
4) Enter an amount. 
5) Tap on the Request button. 
6) Tap on “Request” button from Request payment screen
6) Observe

**Impact:** User does not get to know for how many users he/she has sent payment request. 
**Investigation:**  User B is able to see the Payment Requests on Payment requests screen. 
**Current Behavior:** User is unable to see any action related to send payment requests. 
**Expected Behavior:** Users should be able to see activity related to send payment requests.  
**Attachment:**[ Android_PaymentRequest.mp4](https://drive.google.com/file/d/1pwPz3okAqlbixkpr7Z0PHCTPyoDcIHNE/view?usp=sharing) (Bug observe at 11 sec)

**Comment by annakaz** [comment]
Closing as this is outdated with new redesign, please re open if you observe it again @Lss-Ankit
