### ISSUE TITLE
[Bug Report] Error retrieving mnemonic

### ISSUE THREAD

**Issue by tkporter** [celo-org/celo-monorepo#1415]
### Expected Behavior

Mnemonic is retrieved normally

### Current Behavior

This is the only info I have, originally posted on Discord #developerchat

![image](https://user-images.githubusercontent.com/20362969/67226392-a7397180-f3e9-11e9-80cc-1b63d5a300e9.png)

**Comment by nityas** [comment]
closing out, resolved per new social recovery flow
