### ISSUE TITLE
“Failed to sync” screen is shown after 2 mins when in Geth sync mode

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#1422]
**Frequency:** 60%
**App version:** Staging build v1.5.0 (103645729), (101548577)
**Repro on:**  Samsung Galaxy A8+ (8.0.0), LG nexus 5 (6.0.1) 
**Testing Account:**  680 208 0265/[Backup Kay](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit?usp=sharing)
 
**Repro Steps:** 
1) Launch the app. 
2) Tap on the ‘cog’ icon. 
3) Tap on ‘Celo Lite’ option. 
4) Turn off celo lite toggle. 
5) Proceed for payment by selecting any celo user from the + tab. 
6) Observe. 

**Investigation:** [Random] Error “Could not calculate fee” is shown while user proceeding for payment after turning off the celo lite toggle. 
**Current Behavior:** Sorry something went wrong error message is shown. 
**Expected Behavior:** User should be able to send payment without getting any error after turning off the toggle 
**Attachment:**[ Android_SomthingWentWrong.mp4](https://drive.google.com/file/d/1yIcYfDIqGlq8M2_Hf5m666Q41C9VUkci/view?usp=sharing) (Bug observe at 1:02 sec)

**Comment by Lss-Ankit** [comment]
@annakaz Verified with Android staging build v1.5.0  (101548577) on lower ended devices using low network connectivity and observed that "Sorry Something Went wrong" screen is shown always after turning OFF the "Celo lite" toggle from the setting. 
Due to the above issue, we are blocked to test the Celo Lite toggle OFF related scenarios. 

**Repro devices:** Samsung Galaxy Grand Prime (5.1.1), Samsung Galaxy s5 (6.0.1) 
**Network Bandwidth:** Selected 2G/3G as a mobile network. 
**Note:** The issue does not repro Celo Lite toggle is ON.   
Attachment: [Android_ErrorShownForLowerEndDevice.mp4](https://drive.google.com/file/d/1t6beZbzaL16ySvJX2nm47lnJMq0JvWJ_/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
@jeanregisser @annakaz  Verified with Test Flight build v1.5.1(14), Android Play store build 1.5.1 and observed that issue: Error “Something went wrong” is shown when a user disabled the “Celo Lite” toggle from “Celo Lite” page. 
**Repro devices:** iPhone 7 (13.1), iPhone 7+ (12.4), Samsung Galaxy A8+ (8.0.0), Sony Xperia z3 (6.0.1)
Attachment: [Android_iOS_SorrySomthingWrongError.mp4](https://drive.google.com/file/d/1sCxcAI9n0VTySM0mp6HImRy7RDC4xIRn/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
@jmrossy Verified with pilot network build v1.5.1 and observed the below issue: 
“Sorry, Something went wrong” screen is shown when the user proceeds for payment after turning off the “Celo Lite” toggle. 
**Investigation:** After enabling the Celo lite toggle, the user is able to proceed for payment. 
**Impact:** User is blocked to proceed for payment if Celo lite toggle is OFF. 
**Attachment:**[ Android_CeloLiteOffIssue.mp4 ](https://drive.google.com/file/d/1Xp5mSVL9ws0kAVOLjvpMToUCWW4q8Y0N/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
@jmrossy and @annakaz Verified with Android staging build v1.5.2 (104694505) and observed that issue is still repro 

- “Sorry, Something went wrong” screen is shown when the user proceeds for payment or stays in the "Wallet" tab after turning off the “Celo Lite” toggle. 

"Investigation:" Sorry Something went the wrong screen is shown after a few minutes 

Attachment: [Android_SorrySomthingWentScreenISShown.mp4](https://drive.google.com/file/d/14j-YoVFX4nEmpr-rMVLP2bfCd3NLRgve/view?usp=sharing) (Bug Observed at 2: 25)

**Comment by jeanregisser** [comment]
Thank you @Lss-Ankit, I'm observing something very similar here.
Could you confirm that it happens even without trying to do a transaction?
Specifically launch the app, just let it stay on the wallet home screen without doing anything. And wait about 2 mins.

Here I'm seeing it triggers the "Failed to sync" error screen this way.

**Comment by Lss-Ankit** [comment]
@jeanregisser I have verified it again on iOS test flight build v1.5.2 (16) and Android staging build v1.5.2 (104694505) and now, observed that "Failed to sync" error screen is trigger when a user stay on Wallet tab for 2 minutes. 

**Investigation:** 
1. App closed after a few seconds when a user is on "Failed to sync" error screen 

Attachment: [IOS_FailSync_ErrorScreen.mp4 ](https://drive.google.com/file/d/1dvjlXnNF9VkTrO8V3NAnSeU61uymJhPq/view?usp=sharing)
