### ISSUE TITLE
[iOS] Continues Loading indicator is shown on “Reclaim Payment” screen when user navigate back to “Reclaim Payment” screen from “Enter PIN” screen without entering PIN. 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#1455]
**Frequency:** 100%
**App version:** Test Flight build v1.5.0(10) 
**Repro on:** iPod Touch 6 (12.4), iPad 5th Gen (13.1)
**Testing Account:**  680 208 0265/[Backup Kay](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit?usp=sharing)
 
**Repro Steps:** 
1) Launch the app. 
2) Tap on the “Reclaim Payment” button from the “Remind to Accept Payment” section. 
3) Wail for a moment and tap on the “Confirm” button. 
4) The user is redirected to “Enter PIN”. 
5) Tap on the Back “<” button from the Enter PIN screen. 
6) Observe.    
**Impact:** User is blocked to Reclaim a payment if the user navigates back to “Reclaim Payment” from “Enter PIN”. 
**Investigation:** 
Payment is reclaimed if the Enter PIN screen is not shown. 
The issue also repro when users navigate back to “Reclaim Payment” even after cold launch the app. 
**Current Behavior:** Continues Loading indicator is shown
**Expected Behavior:** User should be reclaimed payment even after navigate back from Enter PIN screen. 
**Attachment:** [IOS_ContinuesLoadingIndicatorIsShown.mp4](https://drive.google.com/file/d/1b5EwoqWYFOr7REpAxotT91HeudG64iBs/view?usp=sharing) (Bug observe at 12 sec)

**Comment by ValoraQA** [comment]
We have verified this issue on latest build Android internal build V1.15.1 & Testflight build V1.15.1(64) and found issue is fixed.
Devices: iPhone 6+ (12.4.5), Vivo v11 pro (10)
