### ISSUE TITLE
  [iOS] Celo Gold amount is cut from bottom on “Exchange” page while user exchanging the cUSD to cGLD. 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#1456]
**Frequency:** 100%
**App version:** Test Flight build v1.5.0(10) 
**Repro on:** iPod Touch 6 (12.4), iPad 5th Gen (13.1)
**Testing Account:**  680 208 0265/[Backup Kay](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit?usp=sharing)
 
**Repro Steps:** 
1) Launch the app. 
2) Tap on the ‘Gold’ tab. 
3) Tap on the Exchange button. 
4) Observe. 

**Investigation:** Issue also repro for cUSD if user taps on the switcher button. 
**Current Behavior:** Celo Gold amount is cut from the bottom side. 
**Expected Behavior:** The amount should not be cut from any side. 
**Attachment:** CeloGoldValueCutFrfomBottom.png
![CeloGoldValueCutFrfomBottom](https://user-images.githubusercontent.com/55572027/67484268-5e9de480-f685-11e9-8498-6bb855c25d6a.jpeg)

**Comment by annakaz** [comment]
No longer relevant after redesign

**Comment by Lss-Ankit** [comment]
Verified with latest IOS test flight build v1.9.1(41) and observed that issue  issue is fixed due to design changes 
- **Device Used:** iPhone 6(12.4.7)
