### ISSUE TITLE
 [iOS] Sorry something went wrong is shown when user taps on Licenses option from the setting

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#1459]
**Frequency:** 100%
**App version:** Test Flight build v1.5.0(10) 
**Repro on:** iPod Touch 6 (12.4), iPad 5th Gen (13.1)
**Testing Account:**  680 208 0265/Backup Kay
 
**Repro Steps:** 
1) Launch the app. 
2) Tap on the Cog icon. 
3) Tap on the “Licenses” option. 
4) Observe. 

**Impact:** User is blocked to see licenses of the app. 
**Investigation:** Error “Something went wrong” is shown when users navigate to the Licenses screen. 
**Current Behavior:**  App get crashed 
**Expected Behavior:** Users should be able to see the licenses of the app. 
**Attachment:** [AppCrash_Licence_Quit.mp4](https://drive.google.com/file/d/1v3PRhyOG8b_38LIAjpPMVgSfES-qQ0Gb/view?usp=sharing) (Bug observe at 11 sec)

**Comment by Lss-Ankit** [comment]
Note: As per this ticket #1424  in iOS, we can not restart the app hence user force out from the app by tapping on the "Quit" button.

**Comment by nityas** [comment]
closing as a duplicate of #1424

**Comment by Lss-Ankit** [comment]
@nityas I do get your point that this ticket is related to #1424 where user Exits the iOS app when tapped on the Quit button. 
However, as per the given title in this ticket, my main concern was the Error message Shown "Something went wrong".  Which is blocking the user to view the License data of the App. 
Hence, as per me this bug is not a duplicate to #1424 and should be in open state. 
Please correct me if my understanding is different.

Also, I have verified this ticket with the latest iOS build  v1.5.1 (14) and Error loading page is shown when user taps on the "Licenses" option. 
 **Attachment:** iOS_LicensesIssue.png
![iOS_LicensesIssue](https://user-images.githubusercontent.com/55572027/68757633-43921500-0632-11ea-8f50-e81f7b459b26.PNG)

**Comment by Lss-Ankit** [comment]
@jeanregisser Verified with IOS test flight build v1.6.1 (23) and found that issue is still reproduced. 

- "Error loading page" is shown when user taps on Licenses option from the setting 

Attachment: IOS_Licenses_ErrorScreen.png
![IOS_Licenses_ErrorScreen](https://user-images.githubusercontent.com/55572027/75860294-9716b180-5e21-11ea-98d6-42c6e81c5b80.PNG)

**Comment by Lss-Ankit** [comment]
Verified with latest IOS test flight Valora build v1.0.0(6) and observed that issue is reintroduced
- "Error loading page" is shown when user taps on Licenses option from the setting
- **Device Used:**  iPhone 6(12.4.7)
![77091](https://user-images.githubusercontent.com/55572027/88898741-cf081080-d26a-11ea-8958-29e207a2ef2f.jpg)

**Comment by Lss-Ankit** [comment]
@jeanregisser Verified with Latest test flight valora build v1.0.0 (11) and found that Blank screen is shown when user taps on Licenses option from setting. 

Note: Issue is not repro on Android Valora build v1.0.0 (12)

**Comment by Lss-Ankit** [comment]
@annakaz i have Verified this issue with Latest test flight valora build v1.0.0 (15) and found that Blank screen is shown when user taps on Licenses option from setting.
Device: iPhone 6+(12.4.5)
Note: Issue is not repro on Android Valora build v1.0.0 (12)

**Comment by Lss-Ankit** [comment]
I have verified this issue using using  iOS test flight build v1.1.0(21) and found issue is fixed
Device : iPhone 6+ (12.4.5),iphone 7+ (13.3.1)
