### ISSUE TITLE
[iOS,Android] Error “Failure sending invite” is shown when user send an invitation via SMS. 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#1460]
**Frequency:** 100%
**App version:** Test Flight build v1.5.0(10) 
**Repro on:** iPhone 7+ (12.4), iPad 5th Gen (13.1)
**Testing Account:**  680 208 0265/Backup Kay
 
**Repro Steps:** 
1) Launch the app. 
2) Tap on the Cog icon. 
3) Tap on the “Invite” option. 
4) Selected non celo user. 
5) Tap on Invite with the SMS button. 
6) Wait for a moment and observe. 

**Impact:** User is blocked to send an invitation via SMS. 
**Investigation:** Issue does not repro when user send an invitation via Whatsapp. 
**Current Behavior:** Error “Failure sending invite” is shown
**Expected Behavior:** User should be able to send an invitation without getting any error. 
**Attachment:**[ IOS_FailToSendInvitationViaSMS.mp4 ](https://drive.google.com/file/d/13Qa6Zfwp2V9L69mCi3CRQrKuDqug06XG/view?usp=sharing)(Bug observe at 30 sec)

**Comment by Lss-Ankit** [comment]
@jmrossy Verified with Android build 1.7.0 (104894304) and observed that issue repro

- Error “Failure sending invite” is shown when user send an invitation via SMS. 

Attachment: [invitationissue.mov](https://drive.google.com/file/d/1xOL8or1sZg2dYwRMM_ycV06IkgZb1rRs/view?usp=sharing)

**Comment by jeanregisser** [comment]
Tested the following:
- Android 1.7.0 public build from the Play Store: invite is failing as shown in @Lss-Ankit video above
- Android build from master (b67ac5c19acc49d4259c449e47c45735658e3516): invite works
- iOS 1.7.0 public build from App Store: invite works
- iOS build from master (b67ac5c19acc49d4259c449e47c45735658e3516): invite works

We'll prepare a new build for you to confirm this @Lss-Ankit.

**Comment by Lss-Ankit** [comment]
Thanks @jeanregisser for the update, waiting for the build!

**Comment by Lss-Ankit** [comment]
@jeanregisser Verified with Android build Android Celo Alfa build : v1.7.1  and ios test flight build iOS Test flight build : 1.7.1 (28) and observed that issue is not reproduced.
hence closing this ticket.
