### ISSUE TITLE
Devs should have a centralized/unilateral ganache config

### ISSUE THREAD

**Issue by yorhodes** [celo-org/celo-monorepo#1478]
### Expected Behavior

One file for editing ganache server config
`packages/protocol/truffle-config.js` is a good candidate for other packages to source from.

### Current Behavior

Multiple locations for different ganache server configurations
To name a few...
`packages/protocol/scripts/devchain.ts`
`packages/protocol/runTests.js`
`packages/contractkit/src/test-utils/ganache.setup.ts`

**Comment by BatiGencho** [comment]
@asaj Reserved for limechain @ Ventsi

**Comment by nambrot** [comment]
@yorhodes Is this still relevant?
