### ISSUE TITLE
Remove secp256k1 public key when registering validators

### ISSUE THREAD

**Issue by kobigurk** [celo-org/celo-monorepo#1493]
### Expected Behavior

Validators should only register with their BLS public key and proof-of-possession.

### Current Behavior

Validators have to generate a random public key when registering a validator. I think this was originally meant to be used for encryption, though it wasn't picked up eventually.

Would love to see if we can remove this. @asaj @kevjue maybe?

**Comment by kevjue** [comment]
Hey @kobigurk -  We're going to still need the validator's ecdsa public key when it's registered.  It'll be used to encrypt the validator's enodeURL in the announce message.

**Comment by kobigurk** [comment]
Alright, that answers it! I guess at some point it will stop being the random one in the docs.
