### ISSUE TITLE
Incorrect banner message after completing payment request

### ISSUE THREAD

**Issue by jmrossy** [celo-org/celo-monorepo#150]
### Expected Behavior

Correct banner message

### Current Behavior

[Nitya]: I completed a payment request, but the ‘payment received’ banner flashed

**Comment by jeanregisser** [comment]
I haven't been able to reproduce this.
The "Request Paid" toast message appeared as seen in the screenshot.
I have also checked the code.

@nityas is there a specific way to reproduce this?

![Screenshot_1564560253](https://user-images.githubusercontent.com/57791/62194802-defcc400-b37a-11e9-82e2-10f5fd380e4f.png)

**Comment by nityas** [comment]
I don't have a ton of background on this one- @jmrossy do you know where this issue was raised initially?

**Comment by jmrossy** [comment]
No additional context to share, sorry.
@jeanregisser I think you've tested it adequately. Feel free to close for now.

**Comment by jeanregisser** [comment]
Thanks, closing this.
