### ISSUE TITLE
Contacts when inviting are not sorted

### ISSUE THREAD

**Issue by tkporter** [celo-org/celo-monorepo#1514]
Happened on iOS 13.2, iPhone 8

### Expected Behavior

Going to Settings -> Invite shows all contacts that are sorted in some way (first name or last name)

### Current Behavior

Going to Settings -> Invite shows all my contacts, but they're not sorted and super hard to navigate

**Comment by nityas** [comment]
Note: they appear to be sorted by phone number, not name

**Comment by tkporter** [comment]
Mine aren't sorted by phone number either, weird
