### ISSUE TITLE
Settings table view rows seem shifted to the right

### ISSUE THREAD

**Issue by tkporter** [celo-org/celo-monorepo#1515]
iOS 13.2, iPhone 8

### Expected Behavior

Rows should take up the full width of the screen

### Current Behavior

The table view rows seem to be shifted to the right (I believe this is not intentional? correct me if I'm wrong, it just feels weird). I also see this on the "Edit Profile" view

![IMG_3892](https://user-images.githubusercontent.com/20362969/67815033-00954680-fa63-11e9-98a1-c3c5690077e9.PNG)

**Comment by annakaz** [comment]
Closing as this is no longer relevant with new redesign
