### ISSUE TITLE
Settings table view arrows are slightly clipped

### ISSUE THREAD

**Issue by tkporter** [celo-org/celo-monorepo#1516]
iOS 13.2, iPhone 8

### Expected Behavior

Arrows should not be clipped at all

### Current Behavior

The green arrows on the rows are very very slightly clipped at the bottom of the arrow

![IMG_3892](https://user-images.githubusercontent.com/20362969/67815033-00954680-fa63-11e9-98a1-c3c5690077e9.PNG)

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified this task using Latest Android Internal build and Test flight build V1.24.1 and added the observation in below sheet.

**Sheet Link**:
https://docs.google.com/spreadsheets/d/15nGo3iJAEVJ76wHae9PvYuWI7S2bovKAQPX_edtwPEI/edit#gid=240285760

**Bug Link**: https://github.com/celo-org/celo-monorepo/issues/1339

**Devices** : Samsung Galaxy M40 (10.0)

CC: @tkporter 
Thanks..!!
