### ISSUE TITLE
Choose language view after onboarding should allow you to cancel

### ISSUE THREAD

**Issue by tkporter** [celo-org/celo-monorepo#1517]
### Expected Behavior

A view more similar to the "Select Currency" one would feel closer to what is expected as a user. This includes a back arrow or cancel option in the navigation bar.

### Current Behavior

Settings -> Language Settings will show the "Choose Language" view that is used for onboarding. This is not continuous with the rest of the settings views, and feels jarring.

**Comment by annakaz** [comment]
No longer relevant after redesign
