### ISSUE TITLE
Enable Celo Lite has some UI problems

### ISSUE THREAD

**Issue by tkporter** [celo-org/celo-monorepo#1518]
iOS 13.2, iPhone 8

### Expected Behavior

Toggle has a slight color to it when disabled, font style of the Celo Lite description fits the app style

### Current Behavior

When the on/off toggle is disabled, the toggle is just all white-- this feels weird and it's not immediately clear what a user should do. The description of Celo Lite mode also feels a little off-- either the font style is different from "Enable Celo Lite", the font weight is too heavy, or the color is too "black"-- it's hard to tell, but feels weird.

![IMG_3893](https://user-images.githubusercontent.com/20362969/67815544-6f26d400-fa64-11e9-8aa8-98a17f53c679.PNG)

**Comment by annakaz** [comment]
Switch UI on iOS fixed in this PR- https://github.com/celo-org/celo-monorepo/pull/1718
