### ISSUE TITLE
Settings -> Licenses error loading page

### ISSUE THREAD

**Issue by tkporter** [celo-org/celo-monorepo#1519]
iOS 13.2, iPhone 8

### Expected Behavior

Licenses are correctly shown

### Current Behavior

![IMG_15E486CF8721-1](https://user-images.githubusercontent.com/20362969/67815854-4e12b300-fa65-11e9-8d5c-553c805a8006.jpeg)

**Comment by jmrossy** [comment]
Dupe of #1459
