### ISSUE TITLE
Status bar changes background color for no clear reason when scrolling in feed

### ISSUE THREAD

**Issue by tkporter** [celo-org/celo-monorepo#1520]
iOS 13.2, iPhone 8

### Expected Behavior

Either the status bar background color is always white (IMO this looks better and is more consistent with iOS app designs), or we make sure that the status bar does not abruptly change to white when scrolling down a lot

### Current Behavior

The status bar is white when at the top of the feed, as expected:

![IMG_3897](https://user-images.githubusercontent.com/20362969/67816770-443e7f00-fa68-11e9-9215-176068d58b57.PNG)

Then it slowly turns grey when scrolling down:

![IMG_3895](https://user-images.githubusercontent.com/20362969/67816806-66380180-fa68-11e9-8b4a-9bdab2259cf1.PNG)

But if I scroll down a lot, it very abruptly changes back to white:

![IMG_3896](https://user-images.githubusercontent.com/20362969/67816898-98496380-fa68-11e9-9fcd-9f5fcd5f1e6d.PNG)

**Comment by annakaz** [comment]
No longer relevant after redesign
