### ISSUE TITLE
Sending yourself cUSD only shows received in the feed

### ISSUE THREAD

**Issue by tkporter** [celo-org/celo-monorepo#1525]
iOS 13.2, iPhone 8

### Expected Behavior

Payment Sent should show up in the feed as well. Or maybe even don't allow users to send themselves money?

### Current Behavior

Tried sending myself money, only "Payment Received" showed up in the feed. 

![IMG_3904](https://user-images.githubusercontent.com/20362969/67818033-114aba00-fa6d-11e9-9d6f-9d9e52e90f26.PNG)

**Comment by nityas** [comment]
dupe of #4888
