### ISSUE TITLE
Users SBAT use an API to retrieve from blockscout the leader board information

### ISSUE THREAD

**Issue by aaitor** [celo-org/celo-monorepo#1527]
### Expected Behavior

As a user I would need to use an API in GraphQL or RPC format allowing to retrieve the information from Blockscout (Postgresql database) required to draw the leader board page.

That API should retrieve the top X addresses (50 by default) sorted by: 
* Sum of cGLD
* Sum of cUSD
* locked-up balance

This calculation requires the usage of:
* Address multiplier
* Exchange rate (Contract: SortedOracles.sol, Event:  [MedianRates](https://github.com/celo-org/celo-monorepo/blob/master/packages/protocol/contracts/stability/SortedOracles.sol#L53)

The API will support the following optional parameters:
* List of addresses. If it's given the calculation will be only be calculated over the list of addresses given. If it's not given the calculation will use all the database addresses.
* Number of addresses: 50 by default.
* Sort field (always DESC). Options: cGLD, cUSD, lockedup

This issue depends on 
- [ ] #1290 
- [ ] #1291 
- [ ] #1611 
- [ ] #1612 

### Current Behavior

This API doesn't exist so there is no a way to build a frontend/mobile app to show the leader board in an easy way.

**Comment by diminator** [comment]
closed in favor of #1800
