### ISSUE TITLE
[iOS/Android] “Set up Safeguards” and “View Backup key” button is shown instead of “View backup key” and “View safeguards” button for user who has already proceed for set up safeguards. 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#1530]
**Frequency:** 100%
**App version:** Test Flight build v1.5.1(14)
**Repro on:** iPhone 7 (13.1), iPhone 7+ (12.4)
**Testing Account:** 315 954 3987/Backup Kay

**Pre-condition:** Users should sign up in-app and have backup key. 
 
**Repro Steps:** 
1) Launch the app. 
2) Sign up with the backup key. 
3) Tap on the “Cog” icon. 
4) Tap on “Backup and recovery” option. 
5) Observe. 

**Impact:**  User might feel that backup key is changes due to which “Set up Safeguards” and “View Backup key” button is shown
**Investigation:** View Backup key and view safeguard button is shown when user completes the safeguards process after fresh sign up. 
**Current Behavior:** “Set up Safeguards” and “View Backup key” button is shown
**Expected Behavior:** “View backup key” and “View safeguards” button should be shown 
**Attachment:** IOS_SafeGuardsIssue.png

![IOS_SafeGuardsIssue](https://user-images.githubusercontent.com/55572027/67857232-3fe39600-fb3c-11e9-8d80-1f49c0e19051.PNG)

**Comment by Lss-Ankit** [comment]
Verified with the Android Play store build v1.5.1 (104694405) and observe the same issue: “Set up Safeguards” and “View Backup key” button is shown instead of “View backup key” and “View safeguards” button for user who has already proceed for set up safeguards

**Comment by jmrossy** [comment]
This is the desired behavior for now :)

**Comment by Lss-Ankit** [comment]
@jmrossy it is also observed that “Set up Safeguards” and “View Backup key” button are shown when the user signs up with a backup key even if the user has not proceeded for getting/confirm a backup key yet.
