### ISSUE TITLE
 [iOS] Toast message “Backup Key copied” is not shown when taps on “Copy” button from “Your Backup Key” screen 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#1532]
**Frequency:** 100%
**App version:** Test Flight build v1.5.1(14)
**Repro on:** iPhone 7 (13.1), iPhone 7+ (12.4)
**Testing Account:** 315 954 3987/[Backup Kay](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit?usp=sharing)
 
**Repro Steps:** 
1) Launch the app. 
2) Tap on the Cog icon. 
3) Tap on View backup key. 
4) Tap on the Copy button. 
5) Observe 

**Impact:** Users do not get the idea of whether the key is a copy or not. 
**Investigation:** The issue does not repro for Android. 
**Current Behavior:** Toast message is not shown. 
**Expected Behavior:** Toast message should be shown. 
**Attachment:** [IOS_ToastMessageIsNotShown.mp4](https://drive.google.com/file/d/1nGfVko-S8tf42IK_ReVmDd-mtUVkS1e3/view?usp=sharing) (Bug observe at 06 sec)

**Comment by nityas** [comment]
@Lss-Ankit is this issue true for all toasts in the app, or only for the backup key one?

**Comment by Lss-Ankit** [comment]
@nityas Issue is for all toasts in the app, it seems like all toasts messages are broken on iOS.

**Comment by Lss-Ankit** [comment]
Verified with latest test flight build 1.1.0 (23) and found that issue is fixed now as toast message is shown when user taps on Account No. from Hamburger menu, Sending payment
