### ISSUE TITLE
[iOS/Android] Request payment is not received for `user B` when `user A` send the payment request to `user B` 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#1533]
**Frequency:** 100%
**App version:** Test Flight build v1.5.1(14)
**Does not Repro on: ** 1.5.0 (10)
**Repro on:** iPhone 7 (13.1), iPhone 7+ (12.4)
**Testing Account:**  315 954 3987/[Backup Kay](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit?usp=sharing)
 
**Repro Steps:** 
1) Launch the app. 
2) Sign up in two devices as User A and User B 
3) User A sends the payment request to User B. 
4) Observe Payment request is not received to user B 

**Impact:** User is blocked to see how many users have sent the payment requests. 
**Current Behavior:** Request payment is not received for `user B` 
**Expected Behavior:** Request payment should be received for `user B` 
**Attachment:** [IOS_PaymentRequestIssue.mov](https://drive.google.com/file/d/1mF2vucGA3Xz3RUfFHh5KHgLlnRp4OQOb/view?usp=sharing) (Bug observe at 1:15 sec)

**Comment by Lss-Ankit** [comment]
@jmrossy Verified with the Android Play store build v1.5.1 (104694405) and observed the same issue: Request payment is not received for `user B` when `user A` send the payment request to `user B`

**Comment by jmrossy** [comment]
Thanks @Lss-Ankit , we'll have a look at this next week :)

**Comment by Lss-Ankit** [comment]
@jmrossy Verified with Android build v1.5.1 (Pilot Network) and observed that is issue is fixed as the Payment request is received now. 

Also, Verified with iOS build v1.5.1 (14) and observed that the issue is still reproduced. 
Attachment:[ IOS_PaymentReuqest.mp4](https://drive.google.com/file/d/1-_pgJCPe99LmT9keQtOtl7tKcmcgJ7Mc/view?usp=sharing)

**Comment by i1skn** [comment]
@Lss-Ankit As far as I know 1.5.1 was built 15 days ago, so it does not have the fix that was merged 4 days ago. Let's keep it open until we bump a new version!

**Comment by Lss-Ankit** [comment]
@i1skn Thanks for the information! I have verified this ticket on the latest Test Flight build 1.5.1 (14) as I did not see the latest updated build on test flight. 
I will verify this ticket again on iOS when a new build is generated on a Test Flight.

**Comment by Lss-Ankit** [comment]
I have verified this ticket on latest valora app build v1.0.0(11) and test flight build v1.0.0 (11) observe issue is still repro

**Attachment:** [NotReceivedRequest.MOV](https://drive.google.com/file/d/1HPR6EDMAV-vtBgQ3qFOKbE36Ijk5j-7O/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
@annakaz I have verified this ticket on latest valora app build v1.0.0(12) and test flight build v1.0.0 (11) observe issue is still repro
- Request payment is not received for `user B` when `user A` send the payment request to `user B`
Device: Google Pixel Xl (8.1) | iPhone 6+ (12.4.5)

Attachment: [RequestNotification.mp4](https://drive.google.com/file/d/1e7Tc8JHcydMW2Fh19FubfrmgQUFApiD8/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
@annakaz, @i1skn  I have verified issue using Android Valora Mainnet build v1.0.0 (16), Test Flight build Valora app build v1.0.1 (17) and observe issue is still repro

- Request payment is not received for user B when user A send the payment request to user B

Device: Google Pixel Xl (8.1) | iPhone 7+ (13.3.1)

**Comment by Lss-Ankit** [comment]
Verified issue on latest build Android internal build v1.1.0 (1004294309)& iOS test flight build v1.1.0(21) and found that issue is fixed now. user B is getting payment request when user A sent payment request.
