### ISSUE TITLE
NDK crash when starting Geth

### ISSUE THREAD

**Issue by jmrossy** [celo-org/celo-monorepo#154]
https://sentry.io/organizations/celo/issues/1123965781/?project=1250733&query=is%3Aunresolved
https://sentry.io/organizations/celo/issues/1123977955/?project=1250733&query=is%3Aunresolved
https://sentry.io/organizations/celo/issues/1123977939/?project=1250733&query=is%3Aunresolved

**Comment by ashishb** [comment]
All the three links posted by @jmrossy are for Pixel 2 (ARM64) device. So, something ARM64 specific is happening in this case as well.

**Comment by timmoreton** [comment]
@jmrossy is this still a real issue? can we close?

**Comment by jmrossy** [comment]
@timmoreton Since the sentry links are dead, we can close this for now. Will reopen if this resurfaces
