### ISSUE TITLE
Multi Currency Exchange Screens inconsistancies

### ISSUE THREAD

**Issue by aaronmgdr** [celo-org/celo-monorepo#1548]
### Expected Behavior

When exchanging the confirmation should be show in same currency unit As the input. Id also like to see what type of currency im looking at especially on screens where we show both stable coin as cusd and as a local

### Current Behavior

When using a currency such as MXN  The "gold" screen lists our stable coin in  cusd as does the exchange screen, but the confirm screen for confirm exchange shows MXN to gold. 

<img width="375" alt="Screenshot 2019-10-30 at 6 44 48 PM" src="https://user-images.githubusercontent.com/3814795/67911999-ac16c780-fb45-11e9-8387-10c3ef1d16e3.png">
<img width="375" alt="Screenshot 2019-10-30 at 6 45 07 PM" src="https://user-images.githubusercontent.com/3814795/67912000-ac16c780-fb45-11e9-9f3c-2bedb8859bd0.png">
<img width="375" alt="Screenshot 2019-10-30 at 6 45 22 PM" src="https://user-images.githubusercontent.com/3814795/67912001-ac16c780-fb45-11e9-8b55-c582cc403e0f.png">
<img width="375" alt="Screenshot 2019-10-30 at 6 45 46 PM" src="https://user-images.githubusercontent.com/3814795/67912002-ac16c780-fb45-11e9-8af0-3607d5ed8ef2.png">

**Comment by nityas** [comment]
addressed by #1341 , closing out
