### ISSUE TITLE
Error: cannot set pin twice

### ISSUE THREAD

**Issue by jmrossy** [celo-org/celo-monorepo#155]
See sentry error:
https://sentry.io/organizations/celo/issues/813698141/?project=1250733&query=is%3Aunresolved

**Comment by sallyjyl** [comment]
This is from the old onboarding flow, and the error has been fixed with the new onboarding flow in JoinCelo screen. It only navigates to Pincode screen if the pincode hasn't been set, and skips to EnterInviteCode screen otherwise.
