### ISSUE TITLE
Backup flow should request pin confirmation before showing backup key (Forno case)

### ISSUE THREAD

**Issue by i1skn** [celo-org/celo-monorepo#1557]
### Expected Behavior

Get user pin and confirm it before showing the backup key when in Forno (Zero Sync) mode.    

Initial Issue - #1401 
Implementation for Light node scenario https://github.com/celo-org/celo-monorepo/pull/1556.

### Current Behavior

It will show the backup key without confirming PIN.

**Comment by jmrossy** [comment]
@i1skn please remember to label new issues :)
