### ISSUE TITLE
Users SBAT be prompted to switch to forno when experiencing connectivity issues

### ISSUE THREAD

**Issue by annakaz** [celo-org/celo-monorepo#1559]
### Expected Behavior

(Copied over from #1171, splitting into two issues- cc @nityas )

We propose a modal that gives users with connectivity issues the option to enable Forno mode.

NOTES:

If geth has restarted more than twice, or syncing has taken longer than 15s, but there is still some internet connection(eg type:unknown) show the modal below.
same modal template as the 'Are you sure?' Backup Key Modal, with enable being the primary cta:
a user should only see this modal after they have completed the 'Welcome to Celo' screen
once ‘Dismiss’ is pressed, we should not show the modal again, to avoid an overly intrusive or confusing experience.
(TODO: are there other signals we can use to fine tune this?)

_____________
**Switch Connection Mode?**

We’ve noticed you’re having some trouble connecting. We recommend enabling **Celo-Lite** mode to allow you to keep using the Celo Wallet with intermittent connection.

Celo-Lite allows you to communicate with the Celo Network through a trusted, hosted node, which can give faster performance than running a node on your device. You can always change this mode in Settings.

[Dismiss]  [Enable Celo-Lite]

### Current Behavior

Working as toggle from settings screen

**Comment by nityas** [comment]
upgrading to P1- we'd like this to be in for Liberia

**Comment by annakaz** [comment]
Related to https://github.com/celo-org/celo-monorepo/issues/68
