### ISSUE TITLE
RangeError: Invalid time value

### ISSUE THREAD

**Issue by jmrossy** [celo-org/celo-monorepo#157]
See sentry error:
https://sentry.io/organizations/celo/issues/1113888689/?project=1250733&query=is%3Aunresolved

@jeanregisser Could this be related to your notification fix?

**Comment by jeanregisser** [comment]
That's the one I fixed yes, original issue is here: https://github.com/celo-org/celo-monorepo-old2/issues/7

**Comment by jmrossy** [comment]
Nice, thanks!
