### ISSUE TITLE
Users SBAT activate, revoke votes via CLI

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-monorepo#1594]
- [x] Implementation
- [x] Documentation

**Comment by H34D** [comment]
i think it makes sense to base it on this PR: https://github.com/celo-org/celo-monorepo/pull/1750

**Comment by H34D** [comment]
Documentation is here:

https://github.com/celo-org/celo-monorepo/blob/master/packages/docs/command-line-interface/election.md#activate
https://github.com/celo-org/celo-monorepo/blob/master/packages/docs/command-line-interface/election.md#revoke
