### ISSUE TITLE
Stability fee should be zero then kick in automatically after ~18months

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-monorepo#1597]
In StableToken.sol, a stability fee is implemented via the `InflationFactor`. This inflation factor should remain 1.0 until 18 months after launch, after which it should update every `inflationState.updatePeriod` seconds

**Comment by mcortesi** [comment]
We should use `block.time` to compute time; not `block.number`

**Comment by mrsmkl** [comment]
Looks like the update period is currently 18 months, so the current code should have the required behaviour.
