### ISSUE TITLE
Exchange fallback function should not be payable

### ISSUE THREAD

**Issue by asaj** [celo-org/celo-monorepo#1601]
### Expected Behavior

No fallback function, particularly not one that's payable. This would allow users to send the exchange Celo Gold without it being withdrawable.

### Current Behavior

Payable fallback function. Possibly needed for testing. If this is the case, we can create a separate `ExchangeTest.sol` that inherits from `Exchange` that adds a payable fallback function.

**Comment by BatiGencho** [comment]
reserved for evgeni@limechain
