### ISSUE TITLE
Validators SBAT faucet themselves on Baklava

### ISSUE THREAD

**Issue by diminator** [celo-org/celo-monorepo#1610]
Example
Deploy a full node and CLI [and connect to Baklava] 
Generate betanet addresses: 1x Validator Group (VG) address and 1x Validator (V) address
Install Keybase on machine and log into account
Run a command like `celocli identity:create-metadata --account $V && celocli identity:add-claim --account $V --type keybase  --username KEYBASE_USERNAME` which will put the appropriate proof in the directory below

See more details here: https://docs.google.com/document/d/13I9wQfSriiQOWMZKb5YRkrdclZ4SowEoz3YusOSCtsU/

To check: how to resolve and make available the identity claim

**Comment by timmoreton** [comment]
Dupe of #816 @diminator  ?

**Comment by diminator** [comment]
closed in favor of #816
