### ISSUE TITLE
Devs SBAT to resolve the multipliers that are required for the GCSO

### ISSUE THREAD

**Issue by diminator** [celo-org/celo-monorepo#1612]
The multipliers are hosted on a public spreadsheet and need to be made available to the leaderboard app. Potentially crawled and indexed by blockscout

**Comment by timmoreton** [comment]
* We will need to extract from the spreadsheet a list of tuples of `(address, multiplier)` . 
* the sheet will calculate multiplier by summing up a bunch of other data -- that could be in columns, or it could be a separate table that logs "Address" "Multiplier Reward"  and we add them up with a SUMIF.
* The sheet should be world-readable and only writeable by Claire and Marek.
