### ISSUE TITLE
Devs SBAT see code coverage of Solidity 0.5 contracts

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-monorepo#162]
### Expected Behavior

Please describe the behavior you are expecting

### Current Behavior

What is the current behavior?

**Comment by jeamick** [comment]
Hello @timmoreton,

Does https://github.com/sc-forks/solidity-coverage can do the trick ?
And afte be able to export it to a dashboard where people can see it from the readme page?

With a modification om https://github.com/celo-org/celo-monorepo/blob/master/package.json
 by adding a script like solidity-covarage and modifying a bit of code to make the package compliant with the current folder structure that should work I think...

Thanks
Jean-Mickael
