### ISSUE TITLE
End-to-end test of governable block gas limit

### ISSUE THREAD

**Issue by asaj** [celo-org/celo-monorepo#1639]
### Expected Behavior

We have an end-to-end test of the governable block gas limit.

### Current Behavior

No end-to-end test

**Comment by asaj** [comment]
This could be expanded more generally into an end-to-end test of the `BlockChainParameters` interactions, perhaps repurposing `end-to-end-exit-test` to be `end-to-end-block-chain-parameters-test`

**Comment by mrsmkl** [comment]
Was handled by #1245
