### ISSUE TITLE
Devs SBAT know greater availability of hardware ID attestation

### ISSUE THREAD

**Issue by trianglesphere** [celo-org/celo-monorepo#164]
### Expected Behavior

We want to know the availability of this ID attestation API in our target markets. We can do this through looking into support on devices that are common in our target markets.

### Current Behavior

We don't know the availability of this API in our target markets.
Can't even do this step until #165  is working, but then we need to get the ID certificates from a bunch of phones to determine how widely supported it is.

**Comment by nityas** [comment]
Closing these out-- not exploring hardware attestation for now
