### ISSUE TITLE
[Bug Report] Users SBAT see invite text messages when tapping link from signup flow in iOS Celo Wallet app

### ISSUE THREAD

**Issue by clrblmt** [celo-org/celo-monorepo#1662]
### Expected Behavior

Expecting to see in Messages app: Celo invite codes not "new message" UI

### Current Behavior

What is the current behavior?

When click link from Celo wallet iOS app to see invite codes in Messages app, see "new message" UI instead

![Image from iOS](https://user-images.githubusercontent.com/15363063/68618817-7b7e4880-04ca-11ea-8249-63f58c4fa639.png)

**Comment by nityas** [comment]
resolving per new invite screen in onboarding(no messages redirect), closing out.
