### ISSUE TITLE
 “Verification has failed” error pop up is shown on “Submit code” screen after pasting the received three verification 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#1667]
**Frequency:** 100%
**App version:** Pilot build v1.5.1
**Repro on:** Google Pixel XL (8.1), Google Pixel XL 2 (9.0)

**Repro Steps:** 
1) Launch the app. 
2) Enter the name, Country code and phone number. 
3) Paste the invitation code. 
4) Start the phone number verification code. 
5) Paste the received code. 
6) Wait for moment and observed. 

**Impact:** User is blocked to sign up with phone number verification and user will not get the cUSD and cGLD after skipping verification. 
**Investigation:** User is able to sign up in app after skipping the verification. 
**Current Behavior:**  Verification has failed” error pop up is shown
**Expected Behavior:** User should be able to sign up with phone number verification. 
**Attachment:** [Android_VerificationIssue.mp4](https://drive.google.com/file/d/1LWUgE31q17cD0CotRqJptKomBodpilM7/view?usp=sharing)  (Bug observe at 35 sec)

**Comment by Lss-Ankit** [comment]
@cmcewen @jmrossy Verified with Android v1.5.2 (101548777) integration build and observed that issue is still reproduced.

Verified on Devices : Samsung Galaxy S5 (6.0.1), Redmi Note 7 Pro (9.0)

Verification failed popup is shown after 'Almost Done' screen is shown and before entering three verification code

Attachment : [Android_Verification failed error message is shown.mp4](https://drive.google.com/file/d/1qkQ94iiQckZ10ryZNrgjgjkpPJblKmMJ/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
@cmcewen @jmrossy Verified with Android Android Celo Alfajores Wallet Playstore build (1.6.0 (104794306)) and observed that issue is still reproduced.

Verified on Devices : Google Pixel 2 XL (10), LG W30 (9.0), Google Pixel 2 (10)

Verification failed popup is shown after 'Almost Done' screen is shown and before entering three verification code

Attachment : [Android_Verification failed error message.mp4](https://drive.google.com/file/d/1XEPqHcg6Xhmbn_P_TxTUXeCRAA5X7PYX/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
Hi @jmrossy i verified issue using Android play store build v1.6.0 and found the following:
**Issue:**
- “Verification has failed” error pop up is shown  only when user sign up with received invitation code which as sends by any Celo user 
Attachment: Android_verificationFailed_Invitation.mov (https://drive.google.com/file/d/13rGxagpBB6fvgNnSnCTAvADNRAEPIRg-/view?usp=sharing). 
Logs: [logs1.txt](https://github.com/celo-org/celo-monorepo/files/4198547/logs1.txt)

**Fixed Issue**
- The issue does not repro when used when the user gets an invitation code from https://celo.org/build/wallet  and then verify the phone number. 
- Also, I have performed the below scenario and found that issue does not repro, 
      - The phone number gets verified when the user uses different phone numbers for the existing backup key. 

We can close this issue ticket as issue is fixed. 
For the invitation issue we have separate ticket https://github.com/celo-org/celo-monorepo/issues/2242#issue-537558107

**Comment by jmrossy** [comment]
Ok thanks for clarifying!
