### ISSUE TITLE
devs SBAT deploy set exchange rate script

### ISSUE THREAD

**Issue by trianglesphere** [celo-org/celo-monorepo#167]
## In Progress

On branch `yorhodes/oracle-report-cli`

### Expected Behavior

There should be a helm chart for the set exchange rate cron job.

### Current Behavior

No chart or script.

**Comment by tkporter** [comment]
Helpful: https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/

**Comment by timmoreton** [comment]
dupe
