### ISSUE TITLE
everyone SBAT understand whether hardware Key Attestation will solve sybil resistance ? on rewards app 

### ISSUE THREAD

**Issue by trianglesphere** [celo-org/celo-monorepo#168]
### Expected Behavior

Investigate hardware key attestation and whether imposing this requirement will allow us to proceed with investing further work on the rewards app.

Constraints: We'd like to allow the rewards app to only be run on mobile devices. If possible, this gives us strong Sybil guarantees.

Not deal-breakers, but an additional question to address:
- will this or something similar work for iOS in addition to android?

https://developer.android.com/training/articles/security-key-attestation

### Current Behavior

Unknown what the benefit/capability of this is

**Comment by nityas** [comment]
Closing these out-- not exploring hardware attestation for now
