### ISSUE TITLE
Celo repro maintainer SBAT reward Gitcoin developers in ETH

### ISSUE THREAD

**Issue by clrblmt** [celo-org/celo-monorepo#1682]
### Expected Behavior

Create an ethereum smart contract to reward Celo GitHub contributors in ETH via Gitcoin. Rewards will be in ETH but priced in USD.

Ref: [Gitcoin Repo Maintainer Guide](https://docs.google.com/document/d/1_U9IdDN8FIRMGAdLWCMl2BnqCTAv558QvyJiSWQfkbs/edit#heading=h.er6xyj8n12u9)

### Current Behavior

No Celo Gitcoin integration.

**Comment by asaj** [comment]
Not doing this.
