### ISSUE TITLE
Users SBAT see faster, always working invite code redemption

### ISSUE THREAD

**Issue by cmcewen** [celo-org/celo-monorepo#1689]
### Expected Behavior

Invite code always works

### Current Behavior

Invite code can hang or just fail to complete on certain phones

**Comment by cmcewen** [comment]
[celo_logs (14).txt](https://github.com/celo-org/celo-monorepo/files/3842760/celo_logs.14.txt)

**Comment by tarikbellamine** [comment]
I believe this is a duplicate of #4655 and has been addressed by #4780 as part of the 1.1 release
