### ISSUE TITLE
Developers SBAT read % of C Labs attestation requests completed by a validator

### ISSUE THREAD

**Issue by clrblmt** [celo-org/celo-monorepo#1702]
### Expected Behavior

Read on-chain data to calculate % of C Lab attestations requests completed during TGCSO. @nambrot can help with read details. 

Post % to leaderboard metrics sheet. This number will be used to calculate final BTU multiplier boost for TGCSO. Calculations in sheet. 

*TGCSO = The Great Celo Stake Off

### Current Behavior

Cannot read % of attestations completed by a validator.

**Comment by mrsmkl** [comment]
Currently, blockscout stores the requested and fulfilled attestations to the account table, and they can be seen from the Celo info page.
They are not currently  reflected in the leaderboard score in real time, I was thinking that the multipliers would be added after the challenge is over. This can be done by making a DB query that will update the values of `attestation_multiplier` for competitors. But now that we have the data, it should be easy enough to do it however we want to.
