### ISSUE TITLE
App get crashed when user taps on extra “Backup keyWord” tag on “Confirm Your Backup Key”. 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#1715]
**Frequency:** 50%
**App version:** Pilot build v1.5.1
**Repro on:** Redmi Note 7 pro (9.0), 
**Does not repro on:** Google Pixel (8.1), Samsung Galaxy A8+ (8.0.0), Google pixel XL 2 (9.0)
**Testing Account:**7228953526/[Backup Key ](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit?usp=sharing)
**Does not repro on:** 315 543 5666/[Backup key](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit?usp=sharing)

**Repro Steps:** 
1) Launch the app. 
2) Sign up in app using invitation code. 
3) Tap on Cog icon after sign up. 
4) Tap on Backup and recovery option
5) Tap on Get your key button. 
6) Tap on continue button after enabling toggle. 
7) Tap on Backup keyword tag. 
8) Observed extra keyword tags are shown. 
9) Tap on Extra backup keyword tag. 
10) Observed. 

**Impact:** User is blocked to get the backup key. 
**Investigation:** Extra backup keyword are shown on Confirm Your backup key. 
**Current Behavior:** App get crashed when user taps on extra “Backup keyWord” tag 
**Expected Behavior:** Extra backup keyword tag should not be shown.
 
**Attachment:** 
1. [Android_AppCrashed_BackupandRecovery.mp4](https://drive.google.com/file/d/14K1wiA68wLz6Rwp2mFjoLq9DWtwfiEHU/view?usp=sharing) (Bug observe at 39  sec)
2. [appcrash_Backup.txt](https://github.com/celo-org/celo-monorepo/files/3846138/appcrash_Backup.txt)

**Comment by Pedro-vk** [comment]
I've tried to reproduce it but I was not able to see it.

**Comment by Lss-Ankit** [comment]
@Pedro-vk and @jmrossy while doing smoke testing on Android staging build v1.5.2 (104694505) i have observed the crash once while confirming backup key 

Attachment: [AppgetCrashBackUpKey.mp4 ](https://drive.google.com/file/d/1IxFP71k6XBIL9etDSy04CipA2cSFGkSG/view?usp=sharing)
[Appcrashlog.txt](https://github.com/celo-org/celo-monorepo/files/3961172/Appcrashlog.txt)

**Comment by annakaz** [comment]
Fixed in https://github.com/celo-org/celo-monorepo/pull/2857
