### ISSUE TITLE
Invite text message deeplinking SBAT work on iOS

### ISSUE THREAD

**Issue by nityas** [celo-org/celo-monorepo#1729]
### Expected Behavior

deeplinking works with iOS and android devices

### Current Behavior

deeplinking presently works with android only

**Comment by annakaz** [comment]
Subset of #1512

**Comment by i1skn** [comment]
Ok, so this one was stale for quite a while, so it's time to finish it! :) 
I had a chat with @martinvol and it appeared, that the main blocker is that final invitation text is too long for an SMS - https://github.com/celo-org/celo-monorepo/pull/1983/files#r374251754. @nityas  can we get this text under 160 or what should we do?

**Comment by nityas** [comment]
Invite w/o escrowed payment
```Welcome to the Celo Wallet! Get the app at https://celolink.page.link/SZ1EeUaCHdrDsd9x9 and enter your Celo Code: RDfQlvthTUOf1VtZIJawRBU+dWCKJyndP/M0emKwSjc=``` (158 chars)

Invite w/ escrowed payment
```I've paid you with Celo! Redeem with the Celo Wallet at https://celolink.page.link/SZ1EeUaCHdrDsd9x9 and Celo Code: RDfQlvthTUOf1VtZIJawRBU+dWCKJyndP/M0emKwSjc=``` (160 chars)
