### ISSUE TITLE
Users SBAT read updated transaction, gas pricing, and full node incentive docs

### ISSUE THREAD

**Issue by clrblmt** [celo-org/celo-monorepo#1733]
### Expected Behavior

Update following docs:

- [ ] [transactions](https://github.com/celo-org/celo-monorepo/tree/master/packages/docs/celo-codebase/protocol/transactions)
- [ ] [gas pricing](https://github.com/celo-org/celo-monorepo/blob/master/packages/docs/celo-codebase/protocol/transactions/gas-pricing.md) 
- [ ] [full node incentives](https://github.com/celo-org/celo-monorepo/blob/master/packages/docs/celo-codebase/protocol/transactions/full-node-incentives.md) 

### Current Behavior

Aljfaojres testnet docs (those currently online) do not reflect changes made to transactions, gas pricing, and full node incentives for Baklava testnet.

**Comment by nategraf** [comment]
Fixed by https://github.com/celo-org/celo-monorepo/pull/2022
