### ISSUE TITLE
[Wallet] Users on 3g network SBAT get tx receipts more reliably

### ISSUE THREAD

**Issue by cmcewen** [celo-org/celo-monorepo#1741]
### Expected Behavior

We always get tx receipts and handle properly

### Current Behavior

Sometimes the app will be waiting for a tx to go through even though it was successful. Example - user gets three texts, app submits the txs, but the last one hangs for multiple minutes. User restarts the app and the verification flow is completed right away without any other txs

User sends money, tx appears hanging in feed for a long time and a duplicated transaction shows up

![WhatsApp Image 2019-11-15 at 2 20 18 PM](https://user-images.githubusercontent.com/1307633/68950328-d4dcc500-07b3-11ea-88db-f87a351e48b4.jpeg)

**Comment by annakaz** [comment]
Adding this to 12/11 as it may be related to https://github.com/celo-org/celo-monorepo/issues/2003

**Comment by annakaz** [comment]
Updated title as this issue occurs in geth mode and forno mode when using a slow connection
