### ISSUE TITLE
Grouped Notifications should include outstanding payment requests

### ISSUE THREAD

**Issue by nityas** [celo-org/celo-monorepo#1744]
### Expected Behavior
When a payment request is sent, a notification should be added to the notification center giving the user the option to either 'remind' or 'cancel' the payment request
[figma link](https://www.figma.com/file/mdNgkyVi2impjf5HRBLq3H/Notifications)
Once the payment request is completed, this notification should be removed from the notification center.

### Current Behavior

payment requests are not displayed.

**Comment by i1skn** [comment]
@nityas I've notice that these two text have different prepositions in Figma file. Should not we use the same instead? Just curious :) 
<img width="411" alt="Screenshot 2019-11-27 at 16 33 20" src="https://user-images.githubusercontent.com/6160124/69736971-d2735700-1133-11ea-82d2-f012252b1db6.png">

**Comment by nityas** [comment]
The image on the left contains a summary of the information on the screen
to the right. If someone had 10 notifications, line items would not be
visible for all the requests, but it is still valuable information for a
user to know how many total requests they have hence the decision to put
the number before the label (the two titles are otherwise identical --
though I'd be very in favor of changing both to read 'for you'. @coreycelo
thoughts?)

**Comment by coreycelo** [comment]
👍  for consistent language—"for you" is great.
