### ISSUE TITLE
When on Celo Lite mode, should not see 'Connecting to Celo...'

### ISSUE THREAD

**Issue by nityas** [celo-org/celo-monorepo#1745]
### Expected Behavior

When Lite mode is enabled, would expect to see the 'Bad Connection' banner(if there is no internet connection) or no banner(if there is a connection)

### Current Behavior

when enabling celo-lite, the 'Connecting to Celo...' banner is displayed

cc @annakaz

**Comment by annakaz** [comment]
Fixed in https://github.com/celo-org/celo-monorepo/pull/1708
