### ISSUE TITLE
Internal audit of signer/account usage

### ISSUE THREAD

**Issue by asaj** [celo-org/celo-monorepo#1762]
### Expected Behavior

We should:
- have an internal audit that we are using signers correctly, 
- that they are in the right spots
- determine that we have appropriate tooling
- documenting their existence as well as how a key rotation, especially for validating, looks like

### Current Behavior

In `Accounts.sol`, we have so called "signers" to which accounts can delegate specific actions to. As of right now, they are for:
- voting
- validating
- attestation signing

**Comment by nambrot** [comment]
Some prior docs work https://github.com/celo-org/celo-monorepo/tree/nambrot/accounts-audit
