### ISSUE TITLE
Secure Send

### ISSUE THREAD

**Issue by nityas** [celo-org/celo-monorepo#1777]
### Expected Behavior

three text messages should be treated as verified, any less should be considered 'unverified'

[Figma](https://www.figma.com/file/i3KEZWz9sKiIl3gcwQeqHn/Secure-Send?node-id=178%3A0)

### Current Behavior

one text treated as verified, three texts required to redeem from escrow

**Comment by jmrossy** [comment]
Related: https://github.com/celo-org/celo-monorepo/issues/2438

**Comment by coreycelo** [comment]
Added Figma link
