### ISSUE TITLE
Users SBAT reference updated docs on "running a full node"

### ISSUE THREAD

**Issue by clrblmt** [celo-org/celo-monorepo#1788]
### Expected Behavior

Update https://github.com/celo-org/celo-monorepo/blob/master/packages/docs/getting-started/running-a-full-node.md taking into account new Terraform template.

### Current Behavior

Current instructions are depreciated.

**Comment by aaitor** [comment]
Instructions for running a full node using Docker containers are updated in the similar way those instructions were available for alfajores.
