### ISSUE TITLE
Implement latest design for in-app notifications

### ISSUE THREAD

**Issue by i1skn** [celo-org/celo-monorepo#1808]
### Expected Behavior

Notifications in the app should look like here: https://www.figma.com/file/mdNgkyVi2impjf5HRBLq3H/Notifications?node-id=0%3A1

### Current Behavior

They look differently

**Comment by i1skn** [comment]
There are a couple questions I've came up with during working on this one:

1) On the Home screen I see only "Requests waiting on you" notification box is presented. Can we have as well "Payment's You've Requested" and "Pending Invitation" and how they would look like? Also for cases with 1 and >2 notifications waiting?
2) What if payment requests (both incoming and outgoing) were done by address and not by a phone number or a contact?
3) On "Payment's You've Requested" and "Requests waiting on you" screens amount is negative, should it be positive?
4) On "Pending Invitations" screen we can have a situation, when we do not know the phone number of invitee anymore (after wallet restore). What should we do then? Also in notification box on Home screen?

If the answers could be reflected in design - this is preferred :)
Thanks a bunch in advance!

**Comment by nityas** [comment]
1. defer to corey
2. Great point -- I'd say for that we would need to display 'Unknown User' or similar, and include the address (cc @coreycelo we probably need a design)
3. having the displayed number always be positive within the context of notifications makes sense to me (maybe we can indicate directionality more clearly with design on that screen?)
4. i'd fall back to 'Unknown Number'/'Unknown User' and remove the remind option in this case. I might even go so far as to say we should automatically recall these outstanding requests on app open -- thoughts?

**Comment by coreycelo** [comment]
1. Added designs for each of these versions. 
2. Added designs using "Unknown".
3. Updated these with a slightly different layout. This removes the directionality issue. There's some finicky-ness now with long names, but added some notes there.
4. Also mocked up with "Unknown".

**Comment by i1skn** [comment]
I see the changes in the Figma file! Thanks a lot! I have a couple of questions regarding the latest version:

1) In Escrow payments there is `Cancel` button now, which should cancel the notification. Before we had a `Reclaim` button instead, so the user can take their money back and remove this notification. How would a user reclaim the money now? 
2) In Escrow payments, when a phone number is unknown - there is really now way to remind the requestee (cause we do not know who is it). Should we hide `Remind` button in this case? 
3) When we just no the phone number (not the name), how would the notification look like? 
4) When we just know the address (0x123...), how would the notification look like? 
5) In the notification boxes at Home screen amounts have no currency, is that intentional?
6) On "Request from Others" amounts have different thickness, is that intentional?
<img width="116" alt="Screenshot 2019-12-05 at 14 53 36" src="https://user-images.githubusercontent.com/6160124/70241245-06233200-176f-11ea-8a1d-58eca653ec36.png"> 
Thanks!

**Comment by coreycelo** [comment]
1. Fixed—I copied and pasted the styling over, but forgot to switch out the label copy.
2. Yes, fixed.
3. Added this—we should display the number in place of the name. 
4. This should get covered with the "Unknown" example. I've updated the notes to clarify.
5. Fixed.
6. Fixed.
