### ISSUE TITLE
Update running a validator documentation to separate running the proxy from running the validator

### ISSUE THREAD

**Issue by asaj** [celo-org/celo-monorepo#1868]
### Expected Behavior

Separate sections on running the proxy and running the validator, making the relationship between the two clear, and that they should be run on different machines

### Current Behavior

Very tightly coupled

**Comment by asaj** [comment]
This would also allow us to use 8545 for both, which means we don't need additional instructions on how to configure the CLI to talk to 8547

**Comment by aaitor** [comment]
I changed the default ports of the `celo-proxy` and `celo-validator` containers allowing users to use the CLI talking to the `celo-validator:8545`.
