### ISSUE TITLE
Validator quickstarts not appearing on docs.celo.org for master

### ISSUE THREAD

**Issue by asaj** [celo-org/celo-monorepo#1884]
The new validator quickstart guide for baklava does not appear on `https://docs.celo.org/v/master/`. We should be sure to include it

I also think we should fold all of the instructions into a single `Running a Validator` page. We don't need separate pages for `alfajores` and `baklava`, since we can just have different branches (i.e. `https://docs.celo.org/v/master/`, `https://docs.celo.org/v/alfajores`, `https://docs.celo.org/v/baklava/`)

Finally, we should update (on master), this page to baklava:
https://docs.celo.org/v/master/getting-started/alfajores-testnet

**Comment by aaitor** [comment]
Consolidated in one page `running-a-validator.md`. Added `baklava-testnet` page, but pending to figure out where to change the link in the left column of the docs website

**Comment by aaitor** [comment]
changed reference to baklava-testnet in left menu
