### ISSUE TITLE
Swap order of BLS ENV variables in quickstart docs

### ISSUE THREAD

**Issue by asaj** [celo-org/celo-monorepo#1885]
Command outputs SIgnature, Public Key but we list the env vars in the quickstart guide as PublicKey, Signature. Let's just reorder them to be consistent.

**Comment by aaitor** [comment]
I think the variables are already listed always in the same order (Public Key, Signature) in the documentation PR:
https://github.com/celo-org/celo-monorepo/pull/1854/files#diff-71b2d40d03c43f6adacb322893b82dadR134
