### ISSUE TITLE
CLI introduction documentation out of date

### ISSUE THREAD

**Issue by asaj** [celo-org/celo-monorepo#1886]
On the following page, https://docs.celo.org/v/master/command-line-interface/introduction, we should remove the old Docker instructions. I would also add full nvm instructions to help people switch to node 10:

curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.1/install.sh | bash
nvm install 10
nvm use 10

On the following page, https://docs.celo.org/v/master/command-line-interface/introduction, we should tell people that they need python2 installed to install celocli.

**Comment by KoenBal** [comment]
Testing https://docs.celo.org/v/master/command-line-interface/introduction
on Windows 10 using PowerShell. 
> PS C:\Users\koen_\celo> npm -v
> 6.11.3
> PS C:\Users\koen_\celo> node -v
> v10.17.0

The log of my (I think) successful install is attached.
[celocli successful install log.txt](https://github.com/celo-org/celo-monorepo/files/3901098/celocli.successful.install.log.txt)

**Comment by KoenBal** [comment]
Created an environment py2 using Miniconda.
Ran the commands npm install -g @celo/celocli again.

> gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer
> gyp ERR! find VS looking for Visual Studio 2015
> gyp ERR! find VS - not found
> gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
> gyp ERR! find VS
> gyp ERR! find VS **************************************************************
> gyp ERR! find VS You need to install the latest version of Visual Studio
> gyp ERR! find VS including the "Desktop development with C++" workload.
> gyp ERR! find VS For more information consult the documentation at:
> gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows

**Comment by KoenBal** [comment]
Install https://github.com/nodejs/node-gyp before running the commands!
The optional "Windows 10 SDK (10.0.17763.0)" during the Visual Studio Build Tools installer is required!

**Comment by KoenBal** [comment]
How to check if my install was successful?

**Comment by KoenBal** [comment]
Should I ignore the following warnings?

`npm WARN deprecated core-js@2.6.10: core-js@<3.0 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3. npm WARN deprecated tar.gz@1.0.7: ⚠️ WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support`

**Comment by KoenBal** [comment]
`To enable parallel build, please add the "/m" switch.`
Can this be used to reduce the celocli build time? Should it be added to the install call?
The whole install procedure is quite lengthy. Only the celocli install already took 967s.

**Comment by KoenBal** [comment]
Relevant warnings?
`npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\@celo\celocli\node_modules\ganache-core\node_modules\fsevents): npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})`

**Comment by KoenBal** [comment]
I already have a full node running and I'm not a Node.js developer, is this the easiest setup procedure possible? Should I always have to build the package myself?
In the "Get started" section maybe some lines could be added that start with
"
Choose an installation with NPM package manager if:
...
Choose an installation with Docker if:
...
"

**Comment by KoenBal** [comment]
How should I go about uninstalling the client (and all the prerequisites)?

**Comment by KoenBal** [comment]
Do you recommend asking all the questions in one post? Now I subdivided them on purpose so each question could have its own thread using the "Quote Reply" feature.
