### ISSUE TITLE
Users SBAT reference documentation explaining  celocli config:set parameters

### ISSUE THREAD

**Issue by clrblmt** [celo-org/celo-monorepo#1896]
### Expected Behavior

Update CLI docs to mention format of expected parameters for `celocli config:set` 

### Current Behavior

Add help info for CLI Issue: we should add help info for `celocli config:set` since currently it doesn’t mention the format of expected params like other commands do. For reference the parameter is `--node {Address}`- currently it doesn’t mention the format of expected params like other commands do. For reference the parameter is `--node {Address}`

**Comment by daithi-coombes** [comment]
Housekeeping... think this could be closed.

`celocli config-help` currently details usage: 
```
$ celocli config --help
Configure CLI options which persist across commands

USAGE
  $ celocli config:COMMAND

COMMANDS
  config:get  Output network node configuration
  config:set  Configure running node information for propogating transactions to network
```
