### ISSUE TITLE
Users SABT use  “run-docker-validator-network" script that works

### ISSUE THREAD

**Issue by clrblmt** [celo-org/celo-monorepo#1898]
### Expected Behavior

Fix or remove it from the running-a-validator.md file.

### Current Behavior

The “run-docker-validator-network.sh” does not work / bugs.

`./run-docker-validator-network.sh: /usr/bin/bash: bad interpreter: No such file or directory`
- Shebang should be `#!/usr/bin/env bash` instead of `#!/usr/bin/bash`

Does not support manually running individual commands:
- `./run-docker-validator-network.sh pull` (OK)
- `./run-docker-validator-network.sh accounts` (OK)
- `./run-docker-validator-network.sh deploy` (FAILS with ./run-docker-validator-network.sh: line 153: CELO_PROXY_ADDRESS: unbound variable)

`./run-docker-validator-network.sh pull,accounts,deploy,run-validator,status` fails if `screen` command is not installed

**Comment by diminator** [comment]
fixed in #1934
