### ISSUE TITLE
How should I ask questions about very specific parts of the documentation which are not necessarily issues or incorrect?

### ISSUE THREAD

**Issue by KoenBal** [celo-org/celo-monorepo#1911]
1) Use reference links to sections (like below) You can't refer to specific lines or words in the docs, can you?
2) [Hypothesis](https://web.hypothes.is/) - Annotate the web, with anyone anywhere Which has the benefit that you can discuss about specific words.
3) Use a PR (Note that I do not have a concrete improvement suggestion.)
4) Another method to have a discussion about the docs?
5) Use the forum and reference links?

Example reference links:
https://docs.celo.org/v/master/getting-started/running-a-full-node#create-an-account-and-get-its-address
`docker run -v $PWD:/root/.celo --entrypoint /bin/sh -it $CELO_IMAGE:$CELO_NETWORK -c "geth account new"`

Question:
Is `$PWD` an environment variable which I should have declared earlier?
What exactly does this code `-v $PWD:/root/.celo` do?

PS: The example can be ignored here.

About the [contributing guidelines](https://docs.celo.org/community/contributing):
Should I be able to assign someone?
label the issue?

**Comment by clrblmt** [comment]
At this stage the easiest is to post questions on https://forum.celo.org/c/protocol and reference the code or docs https://docs.celo.org/celo-codebase/protocol. 

The contributing guidelines are going to get reworked along with the process with the launch of the bounty program. It should be up and live by EOY 2019, early 2020.  

All suggestions welcome!
