### ISSUE TITLE
Why are you "SBAT" ing all over the place? :)

### ISSUE THREAD

**Issue by KoenBal** [celo-org/celo-monorepo#1939]
Apologies for my ignorance but what does "SBAT" mean?
https://www.abbreviations.com/SBAT
Are we talking about sports betting? 
Should it be added to Glossary?
Any other Issue title guidelines that could be added to the [contributing page](https://docs.celo.org/community/contributing)?

**Comment by clrblmt** [comment]
SBAT = Should Be Able To
SBNAT = Should Not Be Able To 

The objective is to get the issue writer to think through who the solution is for and what benefit  they'll get out of it. 

Good point. Will add to glossary and contribution page or feel free to do a PR with proposed change(s).

**Comment by clrblmt** [comment]
Created an issue to address 
https://github.com/celo-org/celo-monorepo/issues/1947
