### ISSUE TITLE
GitHub users SBAT to understand what SBAT and SNBAT means

### ISSUE THREAD

**Issue by clrblmt** [celo-org/celo-monorepo#1947]
### Expected Behavior

SBAT = Should Be Able To
SBNAT = Should Not Be Able To

Add above explanation to:
- [ ] [glossary](https://docs.celo.org/getting-started/glossary)
- [ ] [contribution docs](https://docs.celo.org/community/contributing)

### Current Behavior

No explanation of acronyms.

**Comment by annakaz** [comment]
Fixed by https://github.com/celo-org/celo-monorepo/pull/1949
