### ISSUE TITLE
[terraform] Race Condition with deploy upgrade vm-testnet --reset 

### ISSUE THREAD

**Issue by jcortejoso** [celo-org/celo-monorepo#1959]
### Current Behavior

Running `celotooljs.sh deploy upgrade vm-testnet --reset -e myenv` under some conditions (i.e.: 'big' number of nodes/resources to recreate), terrarform fails with the next error:
```
Error: Error deleting InstanceGroup: googleapi: Error 400: The instance_group resource 'projects/my-project/zones/us-west1-a/instanceGroups/myenv-tx-node-lb-group-aee25bcf6c49b9c2' is already being used by 'projects/my-project/global/backendServices/myenv-tx-node-lb-external-service', resourceInUseByAnotherResource
Error: Error deleting InstanceGroup: googleapi: Error 400: The instance_group resource 'projects/my-project/zones/us-west1-a/instanceGroups/myenv-tx-node-lb-group-aee25bcf6c49b9c2' is already being used by 'projects/my-project/global/backendServices/myenv-tx-node-lb-external-service', resourceInUseByAnotherResource
```

The reason why it fails is because a load balancer (`external-tx`) has an attached instance group (`tx-node-lb-group`) and when terraform tries to delete the instance group is failing. 
If you retry a second time after the error with `celotooljs.sh deploy upgrade vm-testnet -e myenv`, then the load balancer has been destroyed, so the instance group and the instances attached can be destroyed and everything finish fine.

The issue around is that the failed-to-delete instances in the first try keep running, and potentially can connect to the network and transfer the chain information to the new nodes, so the `--reset` does not happens.

### What should happen

Ideally the command `celotooljs.sh deploy upgrade vm-testnet --reset -e myenv` finishes without error and the resources are recreated in the correct order.

**Comment by tkporter** [comment]
I was able to reproduce this with a small testnet (2 validators, 2 tx nodes). I never saw this before but we upgraded terraform so maybe that’s the problem
