### ISSUE TITLE
[Blockscout] Blockscout should refer to Betanet as Baklava

### ISSUE THREAD

**Issue by annakaz** [celo-org/celo-monorepo#1984]
### Expected Behavior

Celo Betanet should be referred by its name, Celo Baklava. This follows the pattern we've used to refer to Celo Alfajores. 

### Current Behavior

Celo Betanet is listed, probably because we hadn't yet named the betanet.
After selecting Betanet, users are redirected to https://betanet-blockscout.celo-testnet.org/, but following our convention should redirect to https://baklava-blockscout.celo-testnet.org/

<img width="407" alt="Screen Shot 2019-12-02 at 9 25 20 AM" src="https://user-images.githubusercontent.com/16907027/69971641-dad9e200-14e5-11ea-95fd-13a7be4a35dc.png">

**Comment by lucasege** [comment]
Created a PR on blockscout: https://github.com/celo-org/blockscout/pull/43
