### ISSUE TITLE
Fee is not calculating, when the Debug mode is ON

### ISSUE THREAD

**Issue by i1skn** [celo-org/celo-monorepo#2004]
### Expected Behavior

Fee should be calculating, when the Debug mode is ON

### Current Behavior

Fee is not calculating, when the Debug mode is ON

**Comment by annakaz** [comment]
Couldn't find a quick fix, but created this issue to track: https://github.com/celo-org/celo-monorepo/issues/2187
Going to close this for now as it will be fixed with the above issue
