### ISSUE TITLE
[wallet] Devs SNBAT use react-native-device-info to check Android referrer data

### ISSUE THREAD

**Issue by martinvol** [celo-org/celo-monorepo#2016]
### Expected Behavior

Should use the function `getInstallReferrer()` inside the dependency `react-native-device-info`. 

### Current Behavior

We have an extra dev `react-native-install-referrer` that increases bundle size and we maintain a fork: https://github.com/celo-org/react-native-install-referrer.

This feature is actually broken and it doesn't work to my knowledge.

**Comment by tarikbellamine** [comment]
Believe this has been taken care of
