### ISSUE TITLE
Issues found on Blockscout

### ISSUE THREAD

**Issue by diminator** [celo-org/celo-monorepo#2033]
- https://baklava-blockscout.celo-testnet.org/address/0xcb2d8116b15cf08a23663f22993f777c7b3e9225/read_contract
errors

- https://baklava-blockscout.celo-testnet.org/address/0xd63f87e766efc3b59825209099034f1945b28cf8/transactions

No celo account info

- ttps://baklava-blockscout.celo-testnet.org/address/0xcb2d8116b15cf08a23663f22993f777c7b3e9225/celo

errors

**Comment by mrsmkl** [comment]
Error with https://baklava-blockscout.celo-testnet.org/address/0xcb2d8116b15cf08a23663f22993f777c7b3e9225/celo
should be fixed in https://github.com/celo-org/blockscout/pull/46

**Comment by aaitor** [comment]
@jcortejoso and I are investigating this. It could be caused because a problem in the order of the requests for validating the contracts. The best solution possible should be to make the verification independent of the order in the Blockscout RPC API.

**Comment by aaitor** [comment]
First error is a reported issue in blockscout: https://github.com/poanetwork/blockscout/issues/2907
It happens when solidity output functions have a `address[]`

**Comment by aaitor** [comment]
Second issue should be fixed with https://github.com/celo-org/blockscout/pull/50 and  https://github.com/celo-org/truffle-plugin-blockscout-verify/pull/4

**Comment by aaitor** [comment]
Read contract error: https://github.com/celo-org/blockscout/pull/52

**Comment by aaitor** [comment]
This issue was fixed via different Pull Requests
