### ISSUE TITLE
App users SBAT import contacts on a budget phone

### ISSUE THREAD

**Issue by annakaz** [celo-org/celo-monorepo#206]
### Expected Behavior

App users on budget phones should be able to import their contacts relatively quickly. 

### Current Behavior

App users on budget phones get stuck on the "Import Contacts" screen. For example, it took at least 5 minutes to Import Contacts on a BLU phone that only had two contacts. Many budget phone users must choose skip to get through the onboarding flow in a reasonable amount of time.

**Comment by sallyjyl** [comment]
Did this happen in the case you skipped the enter invite screen? This would happen because state.web3.account is null if the temporary account has not been created yet from the invite code/importing wallet.

**Comment by annakaz** [comment]
I don't think so because eventually the contacts did import, but I'll double check. Also, I'm curious if there are any budget phones in Berlin people are testing with?

**Comment by sallyjyl** [comment]
Fixed by #223. Seems to work fine with the budget phones in Berlin
