### ISSUE TITLE
Internal server error for block signer address from Blockscout

### ISSUE THREAD

**Issue by hqueue** [celo-org/celo-monorepo#2062]
### Expected Behavior
There can be two possible expected behaviors.

1.  No "Celo Info" tab for signer address which is neither a validator nor a group.
2. Show information about signer address when clicking "Celo Info" tab without error

### Current Behavior

Example of my block signer address  which is neither a validator nor a group.
https://baklava-blockscout.celo-testnet.org/address/0x355eca0d3c48c4b8a3359644c7c83db01c6ac594/validations

There is a "Celo Info" tab for signer address which is neither a validator nor a group.

![image](https://user-images.githubusercontent.com/9247907/70248505-5970a100-17be-11ea-8de1-ba94985b7112.png)

When click "Celo Info", it shows `Internal server error`

**Comment by mrsmkl** [comment]
Thanks for reporting, should be fixed with https://github.com/celo-org/blockscout/pull/46
Let's add another issue tracking when we get behaviour 2
