### ISSUE TITLE
On refresh Ethstats thinks latest block was more recent than it was

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-monorepo#2124]
### Expected Behavior

* Last block time says correct time (plus all the last block time fields for every validator)

### Current Behavior

* When a block hasn't been mined in a while, blockscout will show correct last block time, but behavior in ethstats seems to vary as to whether the window has been left open or recently refreshed.  Last block time value is often too low.  Sometimes refresh will show no info for a while, and then sometime later start showing info from the most recent block but as though it had just been mined (not based on the time It actually had been mined).

**Comment by diminator** [comment]
https://github.com/celo-org/ethstats-server/blob/master/src/client/js/controllers.js#L176-L179
