### ISSUE TITLE
User is blocked to proceed for Transaction and Exchange. 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#2147]
**Frequency:** 100%
**App version:** Staging build v1.5.2
**Repro on:** Samsung Galaxy Note 5 (7.0), Samsung Galaxy s5 (6.0.1)  
**Testing Account** 518 468 2551/[BackupKay ](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit#gid=0&range=A3)

**Repro Steps:** 
1) Launch the app. 
2) Tap + tab. 
3) Select celo contact user. 
4) proceed for transaction and tap on send button. 
5) Observe “Failure Sending Payment” message is shown 

**Impact:** User is blocked to send money and exchange the cUSD to cGLD. 
**Investigation:**
1. “Failure Sending Payment” message is shown when user tap on Send button. 
2. Sometime Confirming… text is shown on “Payment Sent” transaction while proceed for transaction and exchange
3. User is able to send request payment. 
4. Issue is always repro either celo CLI toggle is enabled or disabled 

**Current Behavior:** Confirming… text is shown on “Payment Sent” transaction while proceed for transaction and exchange
**Expected Behavior:** User should be able to send the payment and exchange the cUSD to cGLD. 
**Attachment:** [Blocked_Transaction&Exchange.mp4](https://drive.google.com/file/d/1WzQCsHczZap9LdlzSz6H2D6xzOj0wQH2/view?usp=sharing) (Bug observe at  13 sec)

**Comment by Lss-Ankit** [comment]
@jmrossy it is observed that I am able to send transactions and Exchange the cUSD to cGLD or cGLD to cUSD after uninstalled and re-install the app. 

I have taken the below logs for the same: 
Logs for blockage where the issue was observed : [BlockageLogs.log](https://github.com/celo-org/celo-monorepo/files/3943952/BlockageLogs.log)
Logs after reinstalling the app and app is working fine: [AfterReinstalltheapp.log](https://github.com/celo-org/celo-monorepo/files/3943951/AfterReinstalltheapp.log)

**Comment by jmrossy** [comment]
@Lss-Ankit Thanks for sharing the logs! For the future, it would help if you can filter the adb logs to just our app. I can recommend a tool called `pidcat` which helps greatly with this. The command would be `pidcat -t "GoLog" -t "Go" -t "ReactNativeJS" -t RNGeth` or `pidcat org.celo.mobile.BUILD_VARIANT_HERE`

**Comment by Lss-Ankit** [comment]
@jmrossy Thanks for the update!! I will provide the logs by filtering the adb command with PID.

**Comment by Lss-Ankit** [comment]
@jmrossy Update on Issue: 
Verified with Android staging build v1.5.2 (104694505) and found the following: 
- "Failure Sending payment" error message is shown when a user taps on the "Send" button if a user has given white space in the "For" field while proceeding for payment. 

**Note:** Previously issue was repro randomly. 

Attachment: [Android_FailureSendingPaymentIssue.mp4](https://drive.google.com/file/d/1rAZhMZLYakvO5_Xt_XoXQ_bK7dqZ6U-Z/view?usp=sharing) (Bug observed at 26 sec)

**Comment by Lss-Ankit** [comment]
Hi @tarikbellamine I have verified this issue using latest Android internal build v1.3.0(1004294316) & Test Flight Build v1.3.0(27). and found issue is fixed
In app keyboard is open when user select any contact 
Repro on devices: Vivo V11 pro (10),iPhone 6+(12.4.5)
