### ISSUE TITLE
Blockscout shows strange coin balance history

### ISSUE THREAD

**Issue by hqueue** [celo-org/celo-monorepo#2157]
### Expected Behavior

Only valid coin balance change should be listed at "Coin Balance History" tab of account.

### Current Behavior
In the "Coin Balance History" of [0xe7c85a3f18d18d40d713041a69d4795f36339f7d](
https://baklava-blockscout.celo-testnet.org/address/0xe7c85a3f18d18d40d713041a69d4795f36339f7d/coin_balances), there is a balance change at block 81360.
![image](https://user-images.githubusercontent.com/9247907/70550354-f5cce600-1bb8-11ea-8206-52eba8a26cc5.png)

However block 81360 contains no transaction at all and I found no clue of balance change for above account.
![image](https://user-images.githubusercontent.com/9247907/70550742-98856480-1bb9-11ea-8d4e-6429d9cc6ff4.png)

**Comment by nategraf** [comment]
@mrsmkl do you think this is an issue with Blockscout?

**Comment by mrsmkl** [comment]
I guess 81360 was an epoch change block. Epoch change doesn't generate transactions, but it generates a lot of logs. I'll check why it makes an address balance change.
