### ISSUE TITLE
Currency Name is not shown for transaction activity other than the exchange activity in “Activity” Section when user has selected currency other than USD.

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#2181]
**Frequency:** 100%
**App version:** Staging build v1.5.2
**Does not repro:** Play store build v1.5.2. 
**Repro on:** Samsung Galaxy Note 5 (7.0), Samsung Galaxy s5 (6.0.1)  

**Pre-condition:** User must have Exchange activity in Activity section. 

**Repro Steps:** 
1) Launch the app. 
2) Tap on Cog icon. 
3) Tap on Currency option. 
4) select a currency other than the USD. 
5) Navigate back to wallet tab. 
6) Observed. 

**Impact:** Inconsistency in the Activity section as currency name is shown for only exchange activity/transaction, not for other transactions. 

**Investigation:**
 1. Issue does not repro when USD currency is selected
2. Issue does not repro for other activities such as Sent transaction,Received transactions, Verification fee.  

**Current Behavior:** Currency name is shown for exchange activity. 
**Expected Behavior:** Currency name should not display for only one activity
**Attachment:** Android_ExchangeActivityIssue.png
![Android_ExchangeActivityIssue](https://user-images.githubusercontent.com/55572027/70600128-f4c9a200-1c14-11ea-8e5b-52ad7ae10ebe.jpg)

**Comment by Lss-Ankit** [comment]
@jeanregisser Verified with iOS Test flight build v1.5.2 (17) and observed the same issue. 
- Currency Name is not shown for transaction activity other than the exchange activity in “Activity” Section when user has selected currency other than USD.

Attachment: IOS_CurrencyIssue.png

![IOS_CurrencyIssue](https://user-images.githubusercontent.com/55572027/71238639-9e521700-232a-11ea-844b-7190c475733a.PNG)

**Comment by jeanregisser** [comment]
Thanks @Lss-Ankit, fixing this now. 
Currency code shouldn't appear for exchange items in the feed to be consistent with the other items (Having the 3 letters code makes the value quite unreadable and we decided to drop it for now).

**Comment by Lss-Ankit** [comment]
@jeanregisser Verified with iOS test flight build v1.5.2 (18) and found that the issue is fixed as Currency Name is not shown for Exchange Activity. 

**Note: ** will close the ticket when an issue is fixed for Android.
