### ISSUE TITLE
[Suggestion]Add sub-section which shows the payment Request history for each user.

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#2184]
**Frequency:** 100%
**App version:** Staging build v1.5.2
**Repro on:** Samsung Galaxy Note 5 (7.0), Samsung Galaxy s5 (6.0.1)  

**Pre-condition**: Make sure user has proceeded for Payment request. 

**Repro Steps:** 
1) Launch the app from device A.  
2) Launch the app from device B. 
3) User A sends the request to user B from Device A. 
4) Make sure the Payment you’ve requested section is shown. 
5) Tap on the Review button. 
6) Tap on the “Cancel” button. 
7) Observed Requested payment is removed for User A and User B as well. 

**Impact:** The user will not be able to view the transaction requests history made by him/her if the request is canceled or declined.
**Current Behavior:** Requested payment is removed for User A and User B as well
**Expected Behavior:** Need to add Add sub-section which shows the payment Request history for each user
**Attachment:** [Android_RequestSuggesion.mp4 ](https://drive.google.com/file/d/11cFwAruLhjzsg3uL4uehoTWDejPIrC7t/view?usp=sharing)

**Comment by tarikbellamine** [comment]
@nityas not really sure how we want to treat feature requests in github so assigning to you for now

**Comment by ole-nov** [comment]
close because it's fixed

**Comment by Lss-Ankit** [comment]
Hi @aleksey-nov  we are using v1.9.1 on Android and IOS but we are not able to see payment Request history in this version, can you please let us know is it fixed in another version ?
