### ISSUE TITLE
Updrage i18next library to the latest version

### ISSUE THREAD

**Issue by i1skn** [celo-org/celo-monorepo#2185]
We are using `react-i18next#8.3.8` which is 1 year old (current version is 11.2.5). Sometimes features in the documentation (for the latest version) are missing in our version and this is a bit frustrating… E.g. `tOptions` is not in prop types for `<Trans/>` in our version, but in the latest.

Not a blocker, though. `// @ts-ignore` most of the time would solve the problem.

**Comment by jeanregisser** [comment]
Done in https://github.com/celo-org/celo-monorepo/pull/2311
