### ISSUE TITLE
[Wallet] Devs SBAT use debugger while in ZeroSync mode

### ISSUE THREAD

**Issue by annakaz** [celo-org/celo-monorepo#2187]
### Expected Behavior

Devs can use react native debugger while in zeroSync mode

### Current Behavior

When react native debugger is enabled in zeroSync mode, `TypeError: Cannot read property 'getReader' of undefined` is thrown. Devs use pidcat instead

**Comment by annakaz** [comment]
Could be related to our web3 version, see https://github.com/ethereum/web3.js/issues/3044
Will wait to investigate further until after we bump our web3 version

**Comment by tarikbellamine** [comment]
I don't believe this is relevant anymore
