### ISSUE TITLE
Users SBAT send money to verified users from any sequence of app screens

### ISSUE THREAD

**Issue by annakaz** [celo-org/celo-monorepo#2213]
### Expected Behavior

Sending money to a verified contact does not throw a `sendPaymentFailed` if coming from a payment originally created for a non verified contact

### Current Behavior

Sending money to a verified contact fails if a user edits the payment from one originally created for a non verified contact. 

To reproduce: 
- Open send payment and select a non verified contact
- Enter amount/comment and proceed to Review payment
- Tap edit to go back to "Send or Request" Screen, then click back to see contact list
- Select a verified contact and try to send them money
- Throws `sendPaymentFailed`

**Comment by i1skn** [comment]
So, I did the following (**bold** show things I did different or on top of initial steps to reproduce):
* Open send payment and select a non verified contact
* Enter amount/comment and proceed to Review payment **by pressing Invite button**
* Tap edit to go back to "Send or Request" Screen, then click back to see contact list
* Select a verified contact and try to send them money
* **Enter PIN**

and then transaction went through successfully.

@annakaz can you please double check is it still reproducible for you or it was side-fixed already as a part of some other changes? Thanks!

**Comment by annakaz** [comment]
Thanks @i1skn ! Fixed by the commentEncyprtion type error you found here https://github.com/celo-org/celo-monorepo/pull/2250
