### ISSUE TITLE
Skip button is shown enabled  on “import Contact” screen even after user is tapped on “Enable Contact Access” button. 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#2218]
**Frequency:** 100%
**App version:** Staging build v1.5.2
**Repro on:** Samsung Galaxy Note 5 (7.0), Samsung Galaxy s5 (6.0.1)  

Pre-condition: Make sure user has proceeded for Payment request. 

**Repro Steps:** 
1) Install the app  
2) Enter the Name, selected country and enter a phone number. 
3) Set Security PIN. 
4) Paste Invite code or Backup key. 
5) Make sure the Import Contact screen is shown. 

**Impact:** Continues loading is shown when user navigate to the “Import Contact” screen from Verify phone number when user taps on the “Enable Contact number” button and then skip the contact flow. 
**Current Behavior:** Skip button is shown enabled  on “import Contact” screen
**Expected Behavior:** Skip button should be shown disable when user taps on the “Enable Contact Access” button. 
**Attachment:** [Android_ContinuesLoading.mp4](https://drive.google.com/file/d/1J09ATi_XcqigaatQh-9XAU50HqkO0t3c/view?usp=sharing) (bug Observe after 5 sec)

**Comment by ValoraQA** [comment]
Hi @Pedro-vk We have verified this issue on latest build Android internal build V1.15.1 & Testflight build V1.15.1(64) and found issue is fixed as per the new changes.
Thanks!
