### ISSUE TITLE
“Verification Failed” error pop up is shown when invited user try to sign up and already exist user sign up with backup key but using different number. 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#2242]
**Frequency:** 100%
**App version:** Staging build v1.5.2 (104694505)
**Does not repro: ** Play store build v1.5.1
**Repro on:** Samsung Galaxy A8+(8.0.0), Samsung Galaxy Note 5 (7.0)

Pre-condition: 

**Repro Steps:** 
1) Launch the app. 
2) Enter the name, select the country and enter the valid phone number. 
3) Set Security PIN.
4) Paste the Invitation code or backup key. 
5) Wait for moment and observed Verification Failed Error pop up is shown. 

**Impact:** User is blocked to verify their phone number. 

**Investigation:** 
1. Issue also repro when user Verify the phone number from the setting screen after skip the verification. 
2. Sometimes, user will not get the three verification code. 

**Current Behavior:** “Verification Failed” error pop up is shown
**Expected Behavior:** User should be able to verify the phone number. 
**Attachment:** [Android_VerificationFailed.mp4](https://drive.google.com/file/d/1X2Iw-sv6V-qCbH_acLmZYFwBgYfKBgC3/view?usp=sharing) (Bug observed at 1: 31 sec)

**Comment by Lss-Ankit** [comment]
@jeanregisser Verified with iOS test flight build v1.5.2 (16) and observed the same issue: 

- “Verification Failed” error pop up is shown when invited user try to sign up and already exist user sign up with backup key but using different number.
- Issue also repro when user Verify the phone number from the setting screen after skipping the verification.

Attachment:[ IOS_VerificationFailed.mp4 ](https://drive.google.com/file/d/1dM9Sj0Z9yIgYHc927CqVJ47BBOEF-a7i/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
@jmrossy Verified with Android v1.5.2 integration build and failed to verify the phone number as getting "Verification Failed" pop up is shown while sign up. 

Attachment: [Android_Three_VerificationCode.mp4](https://drive.google.com/file/d/1fvWdxa1_vcFO1cVad1dlTIthiwZH4ySM/view?usp=sharing)

**Comment by i1skn** [comment]
I was able verify successfully two phone numbers (during the on-boarding and after it) on integration network. So, I assume, it was a network related issue on alfajoresstaging, hence I'm closing this one.

**Comment by Lss-Ankit** [comment]
Verified with iOS Celo Alfajores Wallet (1.6.0 (21)) and Android Celo Alfa v1.6.0 and found the following: 

"Verification Error" pop up is shown while user verifies phone number while sign up with invitation code. 

**Impact:** user is not able to verify their phone number. 
**Note:** User is able to sign up after skipping the verification flow 

Attachment: [Android and iOS_ Verification issue.mp4](https://drive.google.com/file/d/1JO8-Ioe_3DKjkg6ni9Dq9EkEI_qNSjk8/view?usp=sharing)

**Comment by jmrossy** [comment]
@Lss-Ankit I believe I fixed this on Friday evening when I increased the invite amount.
Can you try again with new invite codes from the faucet (https://celo.org/build/wallet)?

Thanks!

**Comment by jmrossy** [comment]
FYI, there is still a known issue with escrow withdrawal after verification though: https://github.com/celo-org/celo-monorepo/issues/2707

**Comment by Lss-Ankit** [comment]
@jmrossy Verified with Android Celo Alfajores Wallet Playstore build : 1.6.0 (104794306) and found the following:
1. "Verification Error" pop up is shown while user tried to verify real phone number (non celo user) using invitation code (which receives from other celo user to non celo user)
2. Number gets verified when user send invitation code from celo wallet (https://celo.org/build/wallet) and try to sign up using logged in number in 2nd line app 
3. Number gets verified when user restores the account using existing backup key and try to sign up using logged in number in 2nd line app 

So, Issue is partially fixed now. Issue repros for Invited user only. 

**Impact:** user is not able to verify their phone number.

Attachment: [Android_Verification failed error is shown.mp4](https://drive.google.com/file/d/1fYcih-6KZ2ZCRPpHTx45-XXPyq6yHHQ0/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
@jmrossy and @jeanregisser Verified issue on latest iOS test flight build v1.6.1 (23) and found the following: 

- Three verification code are not received when user (Non Celo user) trying to sign up with invitation code which was sent by Celo user 
- Some times only 1 verification code is received but after pasting it "Invalid Verification code" error message is shown. 

Verified on Devices:  iPhone 6+ (12.4.5), iPhone 8 (13.3.1)

Attachment: [IOS_Verification_Failure_InviteFlow.mov ](https://drive.google.com/file/d/1Mc4jVGDyo4qQ9Txg31KYjKp78sz938Ek/view?usp=sharing)

**Comment by jmrossy** [comment]
@Lss-Ankit I watched the video. The 1 verification code you received arrived *before* you started the verification process, so it could not have been for that verification attempt. It must have been for a previous attempt.
I think the problem here is that the SMS messages are not reaching your Indian number in a timely manner. Do you agree?

**Comment by Lss-Ankit** [comment]
@jmrossy Yes, i have verified the invitation flow using US number and able to sign up successfully also received the send Escrow payment which was sent while inviting a user. 

- It is possible that 1 verification code was received for previous attempt. 
- Now, issue is three verification codes are not received for Indian number when user A invite User B on Indian phone number.
- I have tried to sign up with Indian phone number and observed that some times three verification code are received and sometimes only 1 or 2 verification are received.  

Can you please let me know if i should close this ticket and raise a separate ticket for the same?

**Comment by jmrossy** [comment]
@Lss-Ankit Yes please do close this and open a new issue :)

**Comment by Lss-Ankit** [comment]
@jmrossy Thanks for the update! As per last comment i have closed this issue and filed a separate issue for indian number : https://github.com/celo-org/celo-monorepo/issues/3039#issue-576925913
