### ISSUE TITLE
 loading indicator is shown for while on “Welcome to Celo Wallet” screen when user navigate to Country field to select a country. 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#2243]
**Frequency:** 100%
**App version:** Staging build v1.5.2 (104694505)
**Repro on:** Samsung Galaxy A8+(8.0.0), Samsung Galaxy Note 5 (7.0)

**Repro Steps:** 
1) Launch the app. 
2) Choose the language and tap on the continue button.
3)  Enter name and tap on the Country field. 
4) Observed. 

**Investigation** The issue does not repro if "Continue with" pop is shown. 
**Current Behavior:** Loading indicator is shown for a while. 
**Expected Behavior:** Loading indicator should not be shown or if any user number 
**Attachment:** [Android_ContinuosLoadingIsShownForWhile.mp4](https://drive.google.com/file/d/1HGLKl6kR3drtf81YdPsFSH1brneq-R1Y/view?usp=sharing) (bug observed at 06 sec)
![ContinueWithPopup](https://user-images.githubusercontent.com/55572027/70805140-43766800-1dde-11ea-958b-b61aa93734e7.png)

**Comment by annakaz** [comment]
No longer relevant following redesign

**Comment by Lss-Ankit** [comment]
Verified with latest Android internal build v1.9.1 and observed that issue is still Repro
**Device Used:** Samsung Galaxy A5(7.0)
- loading indicator is shown for while on “Welcome to Celo Wallet” screen when user navigate to Country field to select a country.
- **Attachment:** [Continuosloadingisshownforawhile.Mp4](https://drive.google.com/file/d/186d7wlmqwmvrIPV5NMj4a3K_Txlz767h/view?usp=sharing)
![Android_continousloadingisshownforawhile](https://user-images.githubusercontent.com/55572027/88254544-39e9a280-ccd3-11ea-8f48-05670e6304b8.png)
