### ISSUE TITLE
 Continuous loading indicator is shown on “Reclaim Payment” screen when user taps on “Reclaim” button while reclaim the money from “Pending Invitation” screen.

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#2246]
**Frequency:** 100%
**App version:** Staging build v1.5.2 (104694505)
**Repro on:** Samsung Galaxy A8+(8.0.0), Samsung Galaxy Note 5 (7.0)

**Pre-condition:** User must have invited to other users and the invitation is still pending. 

**Repro Steps:** 
1) Launch the app
2) Tap on “Review” button on “Pending Invitation” section
3) Tap on the Reclaim button on the “Pending Invitation” screen. 
4) Observe Continuous loading is shown. 

**Investigation:** Sometime Could not calculate fee error message is shown on “Reclaim Payment” screen. 
**Impact:** User is blocked to reclaim the payment. 
**Current Behavior:** Continuous loading indicator is shown
**Expected Behavior:** User should be able to reclaim the payment. 
**Attachment:** [Android_ReclaimPaymentContinuosLoadingIndicatorIsShown.mp4](https://drive.google.com/file/d/1QKSqfSrPSBqAT4IKlKKKLXtE2y7zCFA8/view?usp=sharing) (Bug observed at 09 sec)

**Comment by i1skn** [comment]
I've tried three times to invite -> reclaim and everything worked just fine. @Lss-Ankit can you please try to reproduce it once again? Probably some other change fixed that already. Thanks!

**Comment by Lss-Ankit** [comment]
@i1skn I have send the invitation to few numbers, 
i am waiting for the  "Pending Invitation" section on "Wallet" tab. 
Once i will get the Pending Invitation section, i will verify the issue and give updates here

**Comment by Lss-Ankit** [comment]
@i1skn Verified with Android Staging build v1.5.2 and able to reclaim the payment. hence, we can close ticket.
