### ISSUE TITLE
loading indicator is remain when users navigate back to  “Wallet” tab from any other screen while loading indicator is shown on “Wallet” tab. 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#2258]
**Frequency:** 100%
**App version:** IOS test flight build v1.5.2 (16)
**Repro on:** iPhone 7+ (12.4),  iPod Touch 6th Gen (12.4)

Pre-condition: 

**Repro Steps:** 
1) Launch the app. 
2) Manually scroll the Wallet tab. 
3) Navigate any other screen 
4) Navigate back to the Wallet tab. 
5) Observed. 

**Current Behavior:** Continuous loading indicator remains on Wallet tab 
**Expected Behavior:** Loading indicator is not shown after the user navigates back to the wallet tab.
**Attachment:** [IOS_LoadingIndicator](https://drive.google.com/file/d/1ppT6mW0FXknxqidmYBQQ9Hn78DlmXcKK/view?usp=sharing) (Bug observed at 12 sec)

**Comment by annakaz** [comment]
Outdated after redesign

**Comment by Lss-Ankit** [comment]
Verified with latest IOS test flight build v1.9.1(41) and observed that issue is Fixed
**Device Used:** iPhone 6(12.4.7)
