### ISSUE TITLE
Wrong type for `getDataEncryptionKey` in ContractKit

### ISSUE THREAD

**Issue by i1skn** [celo-org/celo-monorepo#2265]
### Expected Behavior

In generated `packages/contractkit/lib/wrappers/Accounts.d.ts` it should be:
```
getDataEncryptionKey: (account: string) => Promise<string>;
```

### Current Behavior

In generated `packages/contractkit/lib/wrappers/Accounts.d.ts` it is now:
```
getDataEncryptionKey: (account: string) => Promise<string[]>;
```

When this is done - revert the changes done here - https://github.com/celo-org/celo-monorepo/pull/2250

**Comment by tarikbellamine** [comment]
@i1skn has this been addressed?

**Comment by i1skn** [comment]
Yeah, I see that has been done already!
