### ISSUE TITLE
Link for the consensus Page is not working

### ISSUE THREAD

**Issue by jeamick** [celo-org/celo-monorepo#23]
### Expected Behavior

I read carefully the documentation you provided at https://docs.celo.org/celo-codebase/protocol/consensus and went on https://github.com/celo-org/celo-monorepo/blob/master/packages/docs/celo-codebase/protocol/consensus/README.md and I wad expected that the "proposed" link would work to go on the consensus page (https://medium.com/celohq/bftree-scaling-hotstuff-to-millions-of-validators-7d6930ee046a) or even the whitepaper(https://storage.googleapis.com/celo_whitepapers/Celo__A_Multi_Asset_Cryptographic_Protocol_for_Decentralized_Social_Payments.pdf)

### Current Behavior

What is the current behavior?
 The links presented in this page  https://docs.celo.org/celo-codebase/protocol/consensus are not working

**Comment by marekolszewski** [comment]
Nice catch @jeamick! We'll fix these right away.

**Comment by jeamick** [comment]
I suppose that the paper concerning the Modified version of istanbul (Correctness Analysis of IBFT) is the current implementation your team is targeting right ?

Or is to use the Modified draft version of Hotstuff using a tree of validator to scale a bit the consensus validation ?

Very cool project by the way !!

**Comment by marekolszewski** [comment]
Yes, we are starting with IBFT, but moving to BFTree longer term :)

Issue fixed by #21 

Thanks for reporting it!
