### ISSUE TITLE
User address is shown instead of “Phone number” on “Payments You’ve Requested” screen when user sent the payment request to other user. 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#2305]
**Frequency:** 100%
**App version:** IOS test flight build v1.5.2 (17)
**Repro on:** iPhone 7 (13.3), iPhone XS Max (13.2), iPhone 7+ (12.4)

Pre-condition: User should have “Payment you’ve requested” section on the Wallet tab. 

**Repro Steps:** 
1) Launch the app. 
2) Tap on + Tab. 
3) Select any celo contact user. 
4) Tap on the Request button. 
5) Make sure the “Payments You’ve Requested” screen is shown. 
6) Tap on the review button and observed. 

**Current Behavior:** User address is shown on the “payments you’ve sent” screen. 
**Expected Behavior:**  “Phone number” should be shown on the “payments you’ve sent” screen. 
**Attachment:** IOS_UserAddressIsShown.png
![IOS_UserAddressIsShown](https://user-images.githubusercontent.com/55572027/71171962-077f4f00-2285-11ea-8eec-f1bc19675e6a.PNG)

**Comment by Lss-Ankit** [comment]
@jeanregisser Update on an Issue: 

- I have observed that the User's Address is shown only in which case if a user has not added the requestor's contact number in their device. 
- If the user added the contact number then user name is shown on Payment requested. 
- After deleting the Saved contact number, a User Phone number is shown.

**Comment by jmrossy** [comment]
Hey @Lss-Ankit 
This is expected behavior. We will only show the user's name or number if they are in the requestor's contact list :)
