### ISSUE TITLE
User is blocked to return back from "Pay Request" screen  

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#2306]
**Frequency:** 100%
**App version:** IOS test flight build v1.5.2 (17)
**Repro on:** iPhone 7 (13.3), iPhone XS Max (13.2), iPhone 7+ (12.4)

Pre-condition: User should receive at least one payment request 

**Repro Steps:** 
1) Launch the app. 
2) Tap on Review button from Request from other sections.
3) Tap on the “Pay” button from Request from other screens. 
4) Observed there is no back button hence user won’t be able to navigate back to the wallet tab. 

**Impact:** User is blocked return back from the Pay Request screen
**Investigation:** 
1. User has to complete an action either Pay or decline the request to navigate back wallet tab
2. After the cold launch, the app user redirects to the Wallet tab and the Payment request is persisted on wallet tab. 

**Current Behavior:** No back button on the Payment request screen. 
**Expected Behavior:**  Back button should be shown on the Pay Request screen. 
**Attachment:** [IOS_PayRequestBackIssue.mov (](https://drive.google.com/file/d/15sAPDHqQQ71v3eiJcHWJHnXgJqJxPZ0G/view?usp=sharing)Bug observed at 06 sec)

**Comment by tarikbellamine** [comment]
I think this has been addressed.

**Comment by Lss-Ankit** [comment]
@tarikbellamine i have verified this issue latest build Android internal build v1.1.0 (1004294311) and Test flight build v1.1.0 (23) and found issue is fixed
Device: iPhone 11 (14iOS), Samsung Galaxy A70(9.0)
