### ISSUE TITLE
“Data saver” toggle is enabled without entering Security PIN

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#2307]
**Frequency:** 100%
**App version:** IOS test flight build v1.5.2 (17)
**Repro on:** iPhone 7 (13.3), iPhone XS Max (13.2), iPhone 7+ (12.4)

Pre-condition: Data saver toggle is disabled in initial state.  

**Repro Steps:** 
1) Launch the app. 
2) Tap on Cog icon. 
3) Tap on Data Saver option. 
4) Turn ON data saver option. 
5) Make sure Enter Security PIN screen is shown. 
6) Tap on the Back button on enter PIN screen. 
7) Observed. 

**Current Behavior:** User is able to enable the toggle without entering the PIN. 
**Expected Behavior:** User should not be able to enable the toggle without entering the PIN.
**Attachment:** [IOS_DataSaver_ToggleEnablewithoutPIN.mov](https://drive.google.com/file/d/1gjUngPWgf6A10soCyB2OQNS4qxAiZIVn/view?usp=sharing) (Bug observed at 10 sec)

**Comment by i1skn** [comment]
I have a question: here I see that we first changing `zeroSync` mode and then we ask for a pin to ensure private keys are accessible in new mode.
https://github.com/celo-org/celo-monorepo/blob/b298ff937d90fdf87732be6bf01c2723c795b257/packages/mobile/src/web3/saga.ts#L488-L501
So, the correct behavior will be to rollback the `zeroSync` mode change if PIN was entered incorrectly or discarded?

cc: @celo-org/wallet

**Comment by annakaz** [comment]
Yes that's the correct behavior! Since we may not have the private key needed for zeroSync mode

**Comment by jmrossy** [comment]
@i1skn that seems reasonable to me if it's not too difficult to implement.
Keep in mind there's a limit on how many times we can toggle btwn the two without an app restart. @annakaz knows more
