### ISSUE TITLE
“0,00” amount is shown for the “Total” field on “Buy/Sell gold” confirmation screen when the user proceeds for Exchange activity if the user has selected “Espanol (America Latina)” language. .  

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#2322]
**Frequency:** 100%
**App version:** IOS test flight build v1.5.2 (17)
**Repro on:** iPhone 7 (13.3), iPhone 7+ (12.4)

**Precondition:** User has selected “Espanol (America Latina)” language. 

**Repro Steps:** 
1) Launch the app. 
2) Tap on the “Gold” tab. 
3) Tap on the “Buy” button. 
4) Enter an amount in the Amount field.
5) Tap on the Review button and observe.

**Impact:** User not able to see total amount in the review/confirmation screen.  
**Current Behavior:** “0,00” total amount is shown. 
**Expected Behavior:** Correct total amount should be shown. 
**Attachment:** [ IOS_0_AmountisShown.mov ](https://drive.google.com/file/d/1cFS5iL147qhBbs8O7c7Uq0ac3TzNjRvr/view?usp=sharing)(Bug observed at 28  sec)

**Comment by annakaz** [comment]
Duplicate of https://github.com/celo-org/celo-monorepo/issues/2580

**Comment by ValoraQA** [comment]
This ticket is duplicate of #2580
