### ISSUE TITLE
Three values are shown after decimal point on “Buy/Sell” Review screen. 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#2323]
**Frequency:** 100%
**App version:** IOS test flight build v1.5.2 (17)
**Repro on:** iPhone 7 (13.3), iPhone 7+ (12.4)

**Repro Steps:** 
1) Launch the app. 
2) Tap on the “Gold” tab. 
3) Tap on the “Buy” button. 
4) Enter an amount with the decimal value. For example, 1.234
5) Tap on the Review button and observe. 

**Current Behavior:** Three values are shown after the decimal point. 
**Expected Behavior:** Two values should be shown after the decimal point. 
**Attachment:** IOS_ThreeValuesareShown.png

![IOS_ThreeValuesareShown](https://user-images.githubusercontent.com/55572027/71253026-a9b63a00-234c-11ea-804b-a3957e5503b8.PNG)

**Comment by tarikbellamine** [comment]
I believe this has been addressed

**Comment by Lss-Ankit** [comment]
Hi @tarikbellamine I have verified this issue using latest Android internal build v1.3.0(1004294316) & Test Flight Build v1.3.0(27). and found issue is fixed.

Repro on devices: Vivo V11 pro (10),iPhone 6+ (12.4.5)
