### ISSUE TITLE
Amount is not shown round up on “Buy # Gold” button from “Buy Gold” Review screen when a user buys gold by entering the USD amount. 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#2336]
**Frequency:** 100%
**App version:** IOS test flight build v1.5.2 (18)
**Repro on:** iPhone 7 (13.3), iPhone 7+ (12.4), iPad pro 2nd Gen (13.2.2)

**Repro Steps:** 
1) Launch the app. 
2) Tap on Gold tab. 
3) Tap on the “Buy Gold” button. 
4) Tap on “Switch to Gold” link. 
5) Enter an USD amount and tap on the Review button. 
6) Observe on Buy # Gold button. 

**Investigation:** 
1. Issue also reproduced in the “Gold Activity” section when exchange activity is under progress. 
2. Issue does not repro after completing the Exchange process. 
3. Issue does not repro when a user sells Gold by entering the USD amount. 

**Current Behavior:** Amount is not shown round up
**Expected Behavior:** Amount should be shown round up. 
**Attachment:** IOS_RoundUpIssue_GoldTab.png. 
![IOS_RoundUpIssue_GoldTab](https://user-images.githubusercontent.com/55572027/71397635-234b7200-2644-11ea-8a3c-05cc75d8d14b.PNG)

**Comment by tarikbellamine** [comment]
I believe this has been addressed

**Comment by Lss-Ankit** [comment]
@tarikbellamine I have verified this issue using latest build Android internal build v1.1.0  (1004294311) and Test flight build v1.1.0 (23) and found issue is fixed
Device: iPhone 11 (14 iOS)
