### ISSUE TITLE
“Pending Invitation” section is not shown on the “Wallet” tab even when a user has invited other users.  

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#2337]
**Frequency:** 100%
**App version:** IOS test flight build v1.5.2 (18)
**Repro on:** iPhone 7 (13.3), iPhone 7+ (12.4), iPad pro 2nd Gen (13.2.2)
**Testing Account** 914 745 2564/ [Backupkey](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit?usp=sharing)

**Repro Steps:** 
1) Launch the app. 
2) Tap on the “Cog” icon. 
3) Tap on the “Invite” option. 
4) Send an invitation to any non-celo user. 
5) Make sure an invitation is sent and the Invitation sent activity is shown with an Invitation fee. 
6) Observed.
 
**Note:**I have wait up to 1 day but still did not get the Pending Invitation section. 

**Current Behavior:** “Pending Invitation” section is not shown 
**Expected Behavior:** “Pending Invitation” section should be shown 
**Attachment:** IOS_pendingInvitation.png

![IOS_pendingInvitation](https://user-images.githubusercontent.com/55572027/71399552-fb5f0d00-2649-11ea-8a60-38931b3ad962.PNG)

**Comment by jmrossy** [comment]
@Lss-Ankit the time is currently set to 2 days but I will change it to 1
