### ISSUE TITLE
validator group locked gold requirements not enforced correctly in baklava branch

### ISSUE THREAD

**Issue by zviadm** [celo-org/celo-monorepo#2365]
On Baklava test network it is possible to accept one extra validator in the validator group even when the group doesn't meet locked gold requirements described in the documentation.
https://docs.celo.org/celo-codebase/protocol/proof-of-stake/validator-groups#changing-group-members

Bug is most likely because check happens before new member is added in the group, thus it undercounts number of members by one:
https://github.com/celo-org/celo-monorepo/blob/baklava/packages/protocol/contracts/governance/Validators.sol#L693

This seems already fixed on master. I am not sure how important it is to fix this for the baklava network and stake-off though. Probably useful to patch it (or merge changes from master that fixes the bug)

This is also an example transaction that should have failed but passed on the test network: https://baklava-blockscout.celo-testnet.org/tx/0x32f759a2e5336b5745127596058c7b4ad0a55331de0addb1a2525cfede0be8e1/logs

**Comment by nategraf** [comment]
I can't seem to find it right now, but I am fairly certain there is an issue where we discuss this. Thanks for filing an issue. As for remediation, we will be [deploying a new version of the network tomorrow](https://forum.celo.org/t/announcing-a-new-date-for-phase-2-launch/262) (as seen by San Franciscans) which will include the fix.
