### ISSUE TITLE
Cash In Integration with Moonpay

### ISSUE THREAD

**Issue by nityas** [celo-org/celo-monorepo#2373]
### Expected Behavior

User SBAT cash in and out with moonpay.io API. [Full Spec](https://docs.google.com/document/d/1xfnIZtPutiJOO6tLiTZqgVblbqGbvoJcdSPtbgCYWj4/edit#)

### Current Behavior

no integration

**Comment by annakaz** [comment]
Update: 
Moonpay widget merged, disabled with a feature flag: https://github.com/celo-org/celo-monorepo/pull/2710
Handling the request signing with a firebase function: https://github.com/celo-org/celo-monorepo/pull/2749

Waiting on Moonpay to integrate with our testnet, expected end of week (2/14) perhaps spillover to the weekend (2/16)

**Comment by annakaz** [comment]
Removed Cash Out from this issue!

**Comment by annakaz** [comment]
Closing this out as other work is captured in Cash In redesign
