### ISSUE TITLE
Invalid link to the discord channel

### ISSUE THREAD

**Issue by come-maiz** [celo-org/celo-monorepo#2413]
### Expected Behavior

The discord link in the [main repo README](https://github.com/celo-org/celo-monorepo#-ask-questions-find-answers-get-in-touch) takes me to the discord channel.

### Current Behavior

The link is an invalid invite:
https://discordapp.com/invite/JvJ66Wc

**Comment by nategraf** [comment]
Thanks for creating an issue!
