### ISSUE TITLE
TGCSO users SBAT see BTU boost from buddy rewards on learderboard

### ISSUE THREAD

**Issue by clrblmt** [celo-org/celo-monorepo#2442]
### Expected Behavior

Add mentor/mentee pairs. Capture: mentors get 5% of their mentee BTUs added to their BTUs. This is incremental. Mentee BTUs remains unchanged, they get to keep all of their earned BTUs.

### Current Behavior

Mentor/mentee pairs not captured on stake off leaderboard.

**Comment by barbaraliau** [comment]
No longer relevant.
