### ISSUE TITLE
Failing to verify some contract (Accounts, Exchange, ExchangeProxy, Governance)

### ISSUE THREAD

**Issue by jcortejoso** [celo-org/celo-monorepo#2447]
When verifying contracts on blockscout (command `bin/celotooljs.sh deploy initial verify-contracts -e baklava --verbose`), the next contract fails to verify:
```
Verifying Accounts
Contract at 0x976B5c1ebF9feCC0010E3BF9eB307Ec70e1D8E55 source code not verified yet
Contract Accounts at address 0x976B5c1ebF9feCC0010E3BF9eB307Ec70e1D8E55 not verified yet. Let's do it.
Error Error: null
```

And  Exchange, ExchangeProxy, Governance fail with no message.

**Comment by yorhodes** [comment]
related: https://github.com/poanetwork/blockscout/issues/1151

**Comment by jcortejoso** [comment]
Could verify all the contracts (including `Accounts, Exchange, ExchangeProxy, Governance` on https://baklava-blockscout.celo-testnet.org/. Important to have the correct code&abi files when verifying. (eg: https://baklava-blockscout.celo-testnet.org/address/0x976B5c1ebF9feCC0010E3BF9eB307Ec70e1D8E55/contracts)
