### ISSUE TITLE
CeloCLI add flags to the account:balance cmd to show normal numbers

### ISSUE THREAD

**Issue by mabalaru** [celo-org/celo-monorepo#2451]
### Expected Behavior
$ celocli account:balance $CELO_VALIDATOR_ADDRESS ---SOMEFLAG
All balances expressed in units of 10^-18.
gold: 1459608309031026859
**lockedGold: 18361947566144991167782**
usd: 1196616722628684722
**total: 18364597188276480077283**

Please describe the behavior you are expecting
celocli account:balance should have a flag to return only normal numbers

### Current Behavior
$ celocli account:balance $CELO_VALIDATOR_ADDRESS
All balances expressed in units of 10^-18.
gold: 1459608309031026859
**lockedGold: 1.8361947566144991167782e+22**
usd: 1196616722628684722
**total: 1.8364597188276480077283e+22**

What is the current behavior?

**Comment by szym** [comment]
Perhaps a flag `--exp N` that presents all numbers as units of `1eN` so `--exp 0` would mean do not truncate.
