### ISSUE TITLE
Savings Circle Dapp cannot connect with wallet app

### ISSUE THREAD

**Issue by jmrossy** [celo-org/celo-monorepo#2469]
### Expected Behavior

Dapps should be able to connect and send txs via dappkit + wallet without error

### Current Behavior

Connecting the Savings Circle dapp to the wallet via DappKit causes the app to hit the error screen.

See thread on discord for details: https://discordapp.com/channels/600834479145353243/607994529311883274

**Comment by i1skn** [comment]
#2612 fixes the error during connection, but the other errors occur after successful connection. I've created an issue if `savings-circle-demo` to keep track of it - https://github.com/celo-org/savings-circle-demo/issues/5

**Comment by davidmitesh** [comment]
Is this issue closed. I am still getting the error message right after cello wallet connects with the app.
![Screenshot_2020-06-08-11-33-45-214_host exp exponent](https://user-images.githubusercontent.com/29304788/83996534-24672600-a97c-11ea-8872-a6a632600292.png)
