### ISSUE TITLE
Validators SBAT reference list of monitoring alerts to have for TGCSO Master Validator Challenge

### ISSUE THREAD

**Issue by clrblmt** [celo-org/celo-monorepo#2474]
### Expected Behavior

Create list  of monitoring alerts  for TGVSO Phase 3 Master Validator Challenge OPSEC audit

### Current Behavior

No guidance for system monitoring and alerts for OPSEC validator audit

**Comment by nategraf** [comment]
We've moved forward with the audits without this. Closing this issue.
