### ISSUE TITLE
Web  (Edge & IE Specific) : Country suggestion list is not shown when user enters country name in ‘Country’ text field on Home page

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#2484]
**Repro on Browsers :** Microsoft Edge 42.171341098.0, Microsoft Edge 44.18362.449.0, IE 11 
**Does not repro Browsers:**  Chrome (77.0), FireFox (69.0)
**Priority:** High
**URL:** https://celo.org/build/wallet  

 **Repro Steps:** 
1. Launch the URL.
2. Enter any country name 
3. Observe 

**Bug:**  Country suggestion list is not shown

**Impact:**  User is blocked to send invitation 

**Attachment:** [Web_Country suggestion list does not get loaded](https://drive.google.com/file/d/1_nHlSwgELKcLztqsHvm0hURI0JRr21k4/view?usp=sharing)  (Bug observe at 07 sec)

**Comment by aaronmgdr** [comment]
closing as this code is no longer on website
