### ISSUE TITLE
TGCSO users SBAT see detailed leaderboard sorted by BTU rank

### ISSUE THREAD

**Issue by clrblmt** [celo-org/celo-monorepo#2485]
### Expected Behavior

Display TGVCSO [detailed leaderboard](https://docs.google.com/spreadsheets/d/1Me56YkCHYmsN23gSMgDb1hZ_ezN0sTjNW4kyGbAO9vc/edit#gid=0) ranked by BTU from 1st (most BTUs) to last (least BTUs)

### Current Behavior

Detailed leaderboard is not sorted by BTU rank

**Comment by diminator** [comment]
Is this on the webapp or sheets?
