### ISSUE TITLE
Continuous loading indicator and “Loading Exchange Rate...” is shown when a user navigates to the “Gold” tab. 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#2494]
**Frequency:** 100%
**App version:** Integration build v1.5.2 (101548777) 
**Repro on:** Google Pixel XL 2 (9.0), Samsung Galaxy A8+ (8.0.0) 

**Repro Steps:** 
1) Launch the app.  
2) Tap on “Gold” tab. 
3) Observed  

**Investigation:** 
1. Issue also repro even if a user has Gold activity. 
2. The gold exchange rate is not shown 

**Impact:** Users will not able to see the Gold Activity graph and exchange rate. 
**Current Behavior:** Continuous loading indicator and “Loading Exchange Rate...” is shown
**Expected Behavior:** Gold activity graph should be shown and the exchange rate should be calculated 
**Attachment:**[Android_LoadingIndicatorIsShown.mp4](https://drive.google.com/file/d/13nNK56xfRYcxE17ffowj-7w5OO4QyUZZ/view?usp=sharing) (Bug Observed after 3 sec)

**Comment by Lss-Ankit** [comment]
@jeanregisser @jmrossy Verified with Android v1.5.2 (101548777) integration build and observed that issue is still reproduced.

Verified on Devices : Samsung Galaxy Note 9 (9.0), Samsung Galaxy J7 Pro (8.1.0)

Continues loading indicator is shown & 'Loading Exchange Rate' is shown on 'Gold' tab

Attachment : [Android_loading indicator and loading exchange rate is shown.mp4](https://drive.google.com/file/d/1pdxnfyTrMTn8EKGum5knJlWP_9ZUjbWn/view?usp=sharing)

**Comment by jeanregisser** [comment]
From @cmcewen:
> gold screen spinning only appears when your currency is set to USD fyi

**Comment by Lss-Ankit** [comment]
Verified with  Android internal Celo staging v1.5.2 (104794304) and found that issue is fixed as now Exchange Rate and Gold chart is shown on Gold tab for USD and other currencies. 

**Verified Devices:** 
Samsung Galaxy A5  (7.0) , Samsung Galaxy A8+ (8.0.0)

**Comment by Lss-Ankit** [comment]
@jeanregisser @jmrossy Verified with Android Celo Alfajores Wallet build : v1.6.0 (101648579) and observed that issue reproduced again.

Verified on Devices : Samsung Galaxy A5 (7.0), Samsung Galaxy J7 Prime (6.0.1)

Continuous loading indicator and “Loading Exchange Rate...” is shown when a user navigates to the “Gold” tab. 'Couldn't load exchange rate' error is shown after page gets loaded for some times

Attachment : [Continuous loading indicator is shown.mp4](https://drive.google.com/file/d/1XHk2KOkdyiZIxauU5BfLi3WAE4KWQRpy/view?usp=sharing)

So, reopened this issue

**Comment by jmrossy** [comment]
Related: https://github.com/celo-org/celo-monorepo/issues/2879

**Comment by Lss-Ankit** [comment]
@jeanregisser @jmrossy Verified with Play store build v1.6.1 and observed that issue is reproduce with random frequency. 

**Note:** Content gets loaded after 3-4 minutes of loading gold tab by killing-relaunching the app

Verified Device: Samsung Galaxy A5 (7.0), Samsung Galaxy S5 (6.0.1)

**Comment by Lss-Ankit** [comment]
@jmrossy I have verified this issue again on Android build 1.8.0 (104994308) and found that issue still reproduced for some time: 
Verified on devices: Galaxy A8+ (8.0),Pixel XL (8.1.0), Samsung Note 9 (10),Pixel XL 2 (10),Samsung Galaxy A50 (9.0),Samsung Galaxy A70 (9.0), Samsung Galaxy M30S (9.0) 
Attachment: [GoldtabIssue.mp4](https://drive.google.com/file/d/1StMy6vvkJagqq1IT-gB0j0vWlhdjtW8b/view?usp=sharing)

**Comment by tarikbellamine** [comment]
@Lss-Ankit can you please check if this is still an issue with the latest build?

**Comment by Lss-Ankit** [comment]
Hi @tarikbellamine i have verified an issue on Android play store build v1.8.2 and found that issue is fixed now user is able to see gold chart. 

However, i have also verified the issue on Test flight build v1.8.2 (39) and found that issue is still reproduced. 
- Continuous loading indicator is shown when user navigate to the  Gold tab. 
Attachment: [GoldTabIssue.mp4](https://drive.google.com/file/d/10GBPstiISxkgStUbE_Qd01gNEql-W_Hq/view?usp=sharing)

Verifiy On: Iphone 6+ (12.4.5), Google pixel XL (8.1)

**Comment by tarikbellamine** [comment]
That's great!

The issue on the test flight build is related to a mismatched firebase connection. This is a known and separate issue. Can you please open a new issue for it? Please mention that it is firebase related and lower the priority to P1.

**Comment by Lss-Ankit** [comment]
FYI: I have created https://github.com/celo-org/celo-monorepo/issues/4196 on same day with adding respective details.

**Comment by Lss-Ankit** [comment]
I have verified this issue on Valora app build v1.0.0 (10) and iOS  test flight build v1.0.0 (11) and found issue is fixed .
