### ISSUE TITLE
Test audit script, including on SELinux

### ISSUE THREAD

**Issue by tkporter** [celo-org/celo-monorepo#2499]

**Comment by tkporter** [comment]
Audit script: https://github.com/celo-org/celo-monorepo/pull/2547

**Comment by jcortejoso** [comment]
Some notes around running the validator/proxy/fullnode with selinux in `enforcing` and following the Celo documentation:

- Docker daemon have to be configured with `--selinux-enabled --seccomp-profile=/etc/docker/seccomp.json` (or configure `daemon.json` with the equivalent properties). Default centos 7/rhel 7 already has docker configured this way, but may be missing in some environments or worth checking it is there with `docker info` command.

- When running the docker containers and mounting local directories as volumes, the volume has to have the `z` label included to allow access to those folders inside the container (https://prefetch.net/blog/2017/09/30/using-docker-volumes-on-selinux-enabled-servers/).

Apart from those things, everything works as expected.

From the script perspective it works as expected. @timmoreton should we include some note about running with selinux `enforcing` somewhere?
