### ISSUE TITLE
Users SBAT recover assets through social recovery

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-monorepo#25]
### Expected Behavior

Users who forget and lose their recovery phrase can have a subset of pre-selected trusted friends give them part of their recovery phrase, which combined recreates their recovery phrase so that they can access their account.

### Current Behavior

Users who forget and lose their recovery phrase cannot access their account.

**Comment by drklee3** [comment]
Superseded by individual issues: #741, #767, #768, #769, #770 

[Design doc](https://docs.google.com/document/d/1CYx9mM0Q6DrM-kETRxnfyzWLRrxURheXWo88uJBdUYk/edit#) and [spec](https://docs.google.com/document/d/19g8_CDBi6RhnCfRXlda8HYW8AGT8n9VpeehVZQIsT1g/edit#).
