### ISSUE TITLE
rewards:show command is very resource intensive

### ISSUE THREAD

**Issue by nategraf** [celo-org/celo-monorepo#2505]
`celocli rewards:show` is very resource intensive, with various reports of the command tanking the node that serves it. The root cause of this is most likely that the command leans heavily on the usage of event logs which are expensive to query. This command likely needs to be reworked in order to perform better.

**Comment by mrsmkl** [comment]
Looks like fetching the affiliates took all the time, so just removing that will fix this problem. I'll check if getting the affiliates could be made faster, too.
