### ISSUE TITLE
Vesting schedules migration complete

### ISSUE THREAD

**Issue by asaj** [celo-org/celo-monorepo#2516]
### Expected Behavior

Celo Gold vesting schedules can be written to json file, migration that reads these schedules and deploys vesting instances.

May be easiest to just create a command that takes a json file and deploys vesting instances, idempontently.

**Comment by lucasege** [comment]
Per our conversation, the plan moving forward with this is to create a tool (script) that will be run by each separate entity serving grants (LLC, cLabs, etc.). This script will:
* Consume some JSON format (likely just the parameters to `ReleaseGoldFactory.createInstance`) of grants
* Create a `ReleaseGoldFactory` contract, specific to that entity.
* The total gold for all grants about to be granted by this entity will then be transferred to the factory.
* Iterate through that entity's grants and create a `ReleaseGoldInstance` contract behind a proxy for each grant. The gold for each grant will go to the proxy, and will be released according to the logic of the underlying `ReleaseGoldInstance` contract at runtime (may be updated).

Tasks to be done include: 
* Settle on JSON format
* Update releasegold contract to allow instance proxies
* Finish releasegold contract review changes
* (Possibly out of scope) Work out plan for obtaining addresses from grantees and obtain them
