### ISSUE TITLE
Update migrations config for RC

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-monorepo#2517]
- [ ] set {min, max}ElectableValidators
- [ ] update slashing parameters
- [ ] reset time based params, eg epochSize
- [ ] make validator 0 the Foundation 
- [ ] only run validators migration during tests or internal testnets

**Comment by asaj** [comment]
Also need to set a more sensible value for maxGroupsVotedFor. Ideally this would be greater than or equal to maxElectableValidators, which effectively allows a single address to split their votes between as many groups as they might reasonably choose to vote for. The only limitation on increasing this is the additional gas that's needed for `getAccountTotalLockedGold`, which is used in a few places
