### ISSUE TITLE
Visitors SNBAT outdated / incorrect copy on the website

### ISSUE THREAD

**Issue by aaronmgdr** [celo-org/celo-monorepo#253]
### Expected Behavior

all "marketing" copy accurately describes the celo system

### Current Behavior

we mention or allude to things like mobile phone based verifier app and other things which are no longer true

**Comment by aaronmgdr** [comment]
<img width="1202" alt="Screen Shot 2019-08-07 at 12 12 59 PM" src="https://user-images.githubusercontent.com/3814795/62650925-bc375600-b90c-11e9-99d7-30d6250e023a.png">

**Comment by aaronmgdr** [comment]
earn with celo section should reference being a validator (or full node?) not a verifier

**Comment by aaronmgdr** [comment]
also learn more link in build section should go to build page

**Comment by timmoreton** [comment]
How about for (2)
"Powered by our community" 
"Celo's platform is powered by the community. Users can earn currency by hosting software that forwards mobile devices' requests or validates their transactions."

and I would suggest swapping 2 and 3

**Comment by tjlahey** [comment]
Updated Figma with Tim's asks
