### ISSUE TITLE
Exchange commands sometimes run out of gas

### ISSUE THREAD

**Issue by nategraf** [celo-org/celo-monorepo#2541]
### Expected Behavior

As observed by Chainflow on Discord using the `exchange:dollars` command will sometimes fail. An example of this are transactions `0xfdfe2f8ed85a04e63a549bc4d27655220e8d079e788aff8e555a1a34690bec37` and `0x96e0fe5d75984e8113492f529013f2e07d130add37b76c4b5b3cb01708e7b213` on the Baklava phase 2 network. The first appears to have run out of gas, while the seconds succeeded. Both were the result of running the command with the same parameters. 

It seems likely that this is a result of the `exchange` smart contract method having a state-dependent step to update the uniswap buckets. If the transaction gas estimation is run against a state that would not result in an update, that gas will not be added to the gas limit. If the transaction is included in a block were it would update the buckets, the transaction will subsequently fail.

https://github.com/celo-org/celo-monorepo/blob/ee4ffdd9cc8941cd930915e4772c64bd2f5b4c43/packages/protocol/contracts/stability/Exchange.sol#L101

One potential solution to this is to measure the upper bound of this transaction and set it in the CLI instead of using gas estimation.

**Comment by mrsmkl** [comment]
Looks like most gas used by successful transaction is 211518. These probably succeed because the transferred value is 0. Probably setting to 300000 or something should work.
