### ISSUE TITLE
improve language of cookie consent banner

### ISSUE THREAD

**Issue by aaronmgdr** [celo-org/celo-monorepo#2555]
<img width="1041" alt="Screen Shot 2020-01-24 at 4 18 32 PM" src="https://user-images.githubusercontent.com/3814795/73201959-f2e96e80-40ee-11ea-9b1c-380f9c4001a0.png">

consider moving from our current privacy consent language to something that A) sounds more volitional and B) gives them a reason to Opt in. 

Most important remove the language that implies that by using site you agree to X because i'ts not true. what actually happens is below

#### WHAT HAPPENS WHEN YOU 

PRESS DISAGREE
- we set a tiny cookie letting us know not to bug you again

PRESS AGREE
- we set two cookies; one that you have opted In, one so we don't bug you again
- we load our analytics code which lets us know how the site is being used.
- we load our error reporting code which lets us know when things break for you

### possible new language

To help us create the best possible experience, please agree to let us track your use of this site. Please see Privacy Policy or Source Code for more information.

**Comment by tjlahey** [comment]
@aaronmgdr Please change the buttons to Sentence case from Capital Case

**Comment by aaronmgdr** [comment]
AMENDMENT:  "by continuing to use this site"  becomes  "By selecting Agree..."
