### ISSUE TITLE
StableToken transfers should be freezable/unfreezable

### ISSUE THREAD

**Issue by asaj** [celo-org/celo-monorepo#2560]
### Expected Behavior

StableToken transfers are frozen at mainnet launch, and can be unfrozen via governance proposal.

This allows the network to launch before Celo Gold is integrated into exchanges, after which StableToken transfers can be turned on via governance proposal.

### Current Behavior

StableToken transfers on by default

**Comment by m-chrzan** [comment]
Should they be unfreezable only once, without the possibility of freezing again?
