### ISSUE TITLE
Exchange transaction shows zeroes until confirmed

### ISSUE THREAD

**Issue by i1skn** [celo-org/celo-monorepo#2566]
### Expected Behavior

When exchange transaction is confirming user SBAT see the real amounts.

### Current Behavior

User sees zeroes until transaction is confirmed

### Screenshot

![7d4SrsEBkEttoDZhSuoMJLyo9IUcsr5g](https://user-images.githubusercontent.com/6160124/73260687-654c7280-4205-11ea-906c-e5d724a410d1.png)

**Comment by jeanregisser** [comment]
Fixed in https://github.com/celo-org/celo-monorepo/pull/3032
