### ISSUE TITLE
ContractKit SBAT to read addresses from the Registry contract

### ISSUE THREAD

**Issue by ashishb** [celo-org/celo-monorepo#257]
### Expected Behavior

ContractKit SBAT to read addresses from the Registry contract

### Current Behavior

The hard-coded addresses are read from the artifacts

**Comment by ashishb** [comment]
This issue is blocked by https://github.com/celo-org/celo-monorepo/issues/302

**Comment by mcortesi** [comment]
Some specs on this:

- [x] contract addresses should be fetched on first use (lazily)
- [x] optionally: provide a way to fetch all addresses
- [ ] sdk should be initialized with an environment address (url/ipc). And addresses should be maintained as local state to it. Allowing the sdk to be initialized for multiple environments within the same process **no global/module caching of addresses**
- [ ] Core contract adapters will depend on this sdk instance.

An example:

```ts
import { ContractKit, CeloCurrency } from '@celo/contractkit'

const celo = new ContractKit('http://localhost:8545')
// nothing is fetched here

celo.setDefaultTxArguments({
   from: '',
   gasCurrency: CeloCurrency.CDollar
});

// when using a specific contract will get & cache the address

// some ideas here
const tx = await celo.erc20.sendGold(to, amount)

await tx.getReceipt()

// or
const erc20 = celo.getErc20()
// same as before



```

**Comment by ashishb** [comment]
>  contract addresses should be fetched on first use (lazily)

I agree with this and that's the current behavior. Unless @yerdua makes a major change, this behavior will persist.

> sdk should be initialized with an environment address (url/ipc). And addresses should be maintained as local state to it. Allowing the sdk to be initialized for multiple environments within the same process no global/module caching of addresses

I think its a bit too early to make this change since ABIs are hard-coded to a particular environment anyways.
