### ISSUE TITLE
Couldn’t connect to notification service banner on app restart

### ISSUE THREAD

**Issue by jmrossy** [celo-org/celo-monorepo#2578]
That generally means firebase failed to start.
We should find the root cause and while we're at it, change the error message to be more accurate.

I recommend starting by upgrading our RN firebase libs

**Comment by jeanregisser** [comment]
Unable to reproduce this on iOS sofar.
Now trying on Android.

**Comment by jmrossy** [comment]
@jeanregisser we saw this yesterday occasionally on the android APKs we sent to Ankit

**Comment by jmrossy** [comment]
Can't repro with debug or integration builds. Closing for now
