### ISSUE TITLE
 Invitation code gets pasted automatically when user navigates to ‘Enter Invite Code’ page after coping invitation code 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#2590]
**Frequency:** 100%
**App version:** Integration build v1.5.2 (101548777) 
**Repro on:**  Samsung Galaxy S5 (6.0.1), Redmi Note 7 Pro (9.0)

**Precondition:** Invitation code should be copied 
 
**Repro Steps:** 
1. Launch the app and log in with test account
2. Enter all the information's on ‘Welcome to Celo Wallet’ page 
3. Tap on the ‘Continue’ button 
5. Enter the authentication screen 
6. Make sure redirects to ‘Enter Invite Code’ page and Observe 

**Investigation:** Issue does not repro on verification code text fields 
**Current Behavior:** Invitation code gets pasted automatically 
**Expected Behavior:** Paste icon should be shown ‘Invite Code’ textbox 

**Attachment:** [Android_Invitation code gets pasted.mp4 ](https://drive.google.com/file/d/1N9xaK1xQJNOTWvngqnvqfbobkxWdzh57/view?usp=sharing)(Bug Observed after 12 sec)

**Comment by jmrossy** [comment]
This is intentional behavior :)

**Comment by ValoraQA** [comment]
Hi @jmrossy thanks for information
