### ISSUE TITLE
Validators SNBAT use the attestation signer key or vote signer key for managing validators/groups

### ISSUE THREAD

**Issue by yorhodes** [celo-org/celo-monorepo#2601]
### Expected Behavior

`getAccounts().validatorSignerToAccount(msg.sender)` for all Validators.sol account related actions

### Current Behavior

What is the current behavior?

`getAccounts().signerToAccount(msg.sender)` is used for Validator registration, affiliation, and key rotation

This could lead to a scenario where the ephemeral attestation or vote signing key is compromised and someone's validator is manipulated as a result

Changed on #1643

**Comment by yorhodes** [comment]
the `DowntimeSlasher.sol` and `DoubleSigningSlasher.sol` also use `signerToAccount` despite explicitly a Validator signer key

**Comment by mrsmkl** [comment]
In `DowntimeSlasher.sol` and `DoubleSigningSlasher.sol` we have to use `signerToAccount` because `validatorSignerToAccount` requires the current validator signer.

**Comment by mrsmkl** [comment]
Looks like these have already been changed.
