### ISSUE TITLE
Reserve spender should only be able to transfer gold to other reserve addresses

### ISSUE THREAD

**Issue by asaj** [celo-org/celo-monorepo#2602]
### Expected Behavior

In `Reserve.transferGold`, there is a check that the `to` address is one of the `otherReserveAddresses`.

### Current Behavior

`to` can be any address

**Comment by mrsmkl** [comment]
Looks like `Exchange.exchange` calls `Reserve.transferGold`, looks like it won't work without `to` being any address...

**Comment by nategraf** [comment]
We could find a way. Two initial ideas:
1. Split the reserve transaction into two steps. First transfer the gold to the exchange contract, the transfer it to the recipient.
2. Add a restricted function `Reserve.transferGoldUnsafe` that allows transferring to any address. Although I don't immediately know how to implement that restriction.
