### ISSUE TITLE
“Unknown” text is shown instead of a Phone number/User Name of invitee on the “Invite Sent” section.  

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#2607]
**Frequency:** 100%
**App version:** Integration build v1.5.2 (101548777) 
**Repro on:**  Samsung Galaxy S5 (6.0.1), Redmi Note 7 Pro (9.0)
**Test Accounts:** (516) 217-3399/[BackUp Key](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit?usp=sharing)

**Pre-condition:** User should have invited at least one user and have a Reclaim payment section. 

**Repro Steps:** 
1) Launch the app and sign up with a testing account. 
2) Make sure the user is on the wallet tab. 
3) Observe on Invite sent section. 

**Current Behavior:** “Unknown” text is shown
**Expected Behavior:**  Phone number or user name should be displayed. 
**Attachment:** Unknown_Text.png
![Unknown_Text](https://user-images.githubusercontent.com/55572027/73448960-18dd7000-4388-11ea-996d-7b0243c15a2f.png)

**Comment by jmrossy** [comment]
Expected behavior

**Comment by Lss-Ankit** [comment]
verified with play store build v1.6.0 and observed that Issue does not repro when user does not reset or uninstall & re-install the app  after sending an invitation.
