### ISSUE TITLE
[wallet] VirtualizedLists should never be nested inside plain ScrollViews

### ISSUE THREAD

**Issue by martinvol** [celo-org/celo-monorepo#2608]
### Expected Behavior

Devs should not see errors in the sign up flow.

### Current Behavior

In development, shows the following warning when following the sign up flow. Remember I also spotted this on Android a while back, although this screenshot is on iOS emulator. This can potentially break e2e tests.

![image](https://user-images.githubusercontent.com/698027/73468722-84720e00-4385-11ea-8bf2-0cf97cc5aa9d.png)

![image](https://user-images.githubusercontent.com/698027/73469778-30682900-4387-11ea-8ec5-0d990855e308.png)

**Comment by ole-nov** [comment]
closed because fixed
