### ISSUE TITLE
Disable `celotooljs deploy upgrade contracts` command

### ISSUE THREAD

**Issue by ashishb** [celo-org/celo-monorepo#262]
### Expected Behavior

Disable `celotooljs deploy upgrade contracts` command should fail since it no longer works.

### Current Behavior

`celotooljs deploy upgrade contracts` command should fail since it no longer works but it produces a misleading success

**Comment by yerdua** [comment]
Should the command be entirely removed? Or do we plan on reviving this command?

**Comment by ashishb** [comment]
> Should the command be entirely removed? Or do we plan on reviving this command?

May be remove it altogether. We can revive it later if we want it back. Check with @asaj aswell.
