### ISSUE TITLE
“Request Paid” toast message is shown instead of “Payment Sent” when user A sent money to user B. 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#2631]
**Frequency:** 100%
**App version:** Celo staging build v1.5.2 (104794304)
**Does not repro on:** Android v1.5.2 (101548777) integration build 
**Repro on:** Redmi Note 7 pro (9.0), Google pixel Xl (8.1)
**Testing Account:** 7228953526/[backup Key](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit?usp=sharing)

**Repro Steps:** 
1) Launch the app and login with testing account.
2) Tap on + tab. 
3) Select any celo user. 
4) Send a few amounts to the user. 
5) Observe. 

**Current Behavior:** “Request Paid” toast message is shown
**Expected Behavior:**  “Payment request” toast message should be shown
**Attachment:** [Android_ToastmessageIssue.mp4 ](https://drive.google.com/file/d/1TQvDHXLfngzDXk1pQR_4tSBUCLRv1An-/view?usp=sharing)(Bug observed at 11 sec)

**Comment by jmrossy** [comment]
@i1skn this is because of this line you introduced here: https://github.com/celo-org/celo-monorepo/commit/409dc3c2182372341dcdcb0a275e376e34a327bc#diff-80696334501c4fe07234cfda1d92a6b3R165

Removing that for now in #2636

**Comment by Lss-Ankit** [comment]
Verified on play store build v1.8.2 and found that taost message is not shown after sending the dollar. 
hence blocked to verify the issue. 
Attachment: [ToastMessage.mp4](https://drive.google.com/file/d/1ObETaIJY5f0EiJrx4dXYEX6RWfMZJTUt/view?usp=sharing)
