### ISSUE TITLE
Make invite codes accessible from the invite tx drilldown or reclaimable

### ISSUE THREAD

**Issue by jmrossy** [celo-org/celo-monorepo#2639]
### Expected Behavior

Two ways we can solve this:
1. Make invite codes accessible from the tx drilldown. We still need a way to redeem invite codes after onboarding though, like a settings menu option linking to the redeem invite screen
2. Save the temp invite codes in the store and take back the money from the temp wallet whenever a user reclaims an escrow payment.

### Current Behavior

We open SMS or WhatsApp with the code pre-populated. But if that doesn't work (or the user has neither app installed), the code is simply lost, along with the funds in the temp wallet.

**Comment by tarikbellamine** [comment]
I think part of this will be addressed by #4944 and the other part will be addressed by feeless attestations.
