### ISSUE TITLE
[Wallet] Sync incoming transaction and balance update

### ISSUE THREAD

**Issue by i1skn** [celo-org/celo-monorepo#2647]
This issue is a result of discussion started here: https://github.com/celo-org/celo-monorepo/pull/2548#issuecomment-579541351

### Expected Behavior

When user receives incoming transaction, we need to show it on the list and also update the balance. We should present these two actions to a user at the same time or explicitly communicate in the UI, that one of them is about to get refreshed. Exact behavior TBD (@nityas @coreycelo)

### Current Behavior

When user receives incoming transaction, first user would see it in the list and a couple of seconds later balance would update itself.

**Comment by nityas** [comment]
One question: do the two calls take about the same amount of time? or is one much faster/slower?

As far as preferences, would be preferable to communicate both at the same time to the user-- don't think the extra overhead of building an interaction to tell the user we are updating would be justified.

One edge case might be if one of the calls fails. In this case retrying but updating any state we have already fetched successfully would be ideal.

**Comment by i1skn** [comment]
The main problem is we are using two different mediums to fetch transaction and balance. So, we poll GraphQL for transactions every 10 seconds and if we get something - we trigger balance refresh from Smart Contract (around 1-2 sec). To achieve simultaneous update I see two ways:
1. Move/Duplicate balance logic to GraphQL. In this case we can get both transaction and balance at the same time from GraphQL.
2. Artificially "hold" new transaction from appearing, until we get new balance from Smart Contract and only then show it.
