### ISSUE TITLE
Security PIN is not asked every time when a user turns ON the “Data Saver” toggle. 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#2653]
**Frequency:** 100%
**App version:**  Android internal Celo staging v1.5.2 (104794304)
**Repro on:** Samsung Galaxy A5 (7.0), Samsung Galaxy A8+ (8.0.0)
**Testing Account:** 7228953526/[backup Key](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit?usp=sharing)

**Repro Steps:** 
1) Launch the app and login with testing account.
2) Tap on Cog icon. 
3) Tap on Data Saver option
4) Turn ON the data saver toggle  
5) Tap on “I understand” button on “Beware of restart” pop up. 
6) Observe.  

**Investigation:** 
- Sometime it will ask a security PIN after turning on the toggle. 

**Current Behavior:** Security PIN is not asked every time
**Expected Behavior:** Security PIN should ask every time when user turn ON toggle. 
**Impact:** User  is able to data saver toogle ON without Security PIN
**Attachment:** [Android_Random_DataServar_SecurityPINIssue.mp4](https://drive.google.com/file/d/1cdJ3EgiRJWhqtm5VsqqRI6jnFOvxhOl1/view?usp=sharing) (Bug observed at 06 sec)

**Comment by tarikbellamine** [comment]
@nityas do we want to prompt for the pin when toggling between data saver and pin on app start? Right now I don't think we require the user to the enter their pin for either action.

**Comment by nityas** [comment]
I don't think we need to... I wonder if this happens intermittently bc of geth access and the intermittence (rather than absence) of the prompt is the issue?

**Comment by tarikbellamine** [comment]
Gotcha. I don't think Geth access requires the pin code. Probably safe to close this for now as I haven't been able to repro.
