### ISSUE TITLE
Miscellaneous announce protocol / proxy related changes for Mainnet

### ISSUE THREAD

**Issue by nategraf** [celo-org/celo-monorepo#2669]
[ ] Remove Announce gossip guardrails
[ ] Encrypt enodeURLs
[ ] Create placeholder istanbul messages for threshold signatures
[X] Proxy filter consensus messages from non validator machines
[ ] Restrict announce messages to only elected validators + 10 (as opposed to all registered and elected validators)

**Comment by barbaraliau** [comment]
Old.
