### ISSUE TITLE
Participants are able to earn BTUs by running full nodes

### ISSUE THREAD

**Issue by nategraf** [celo-org/celo-monorepo#2675]

**Comment by nambrot** [comment]
I just tried to connect light clients on both baklava-phase-2 and baklava-phase-3 commits to random nodes on the network and in all permutations I have tried, it works smooth? I.e. I can't seem to reproduce for when this doesn't work (which presumably it didn't at some point in the past)

**Comment by nambrot** [comment]
Just tried again on blank VMs, and a 1.8 ultralight client can discover other nodes in the network just fine?
