### ISSUE TITLE
Create a script to compile the security audit scores

### ISSUE THREAD

**Issue by nategraf** [celo-org/celo-monorepo#2684]
To compile the final security audit scores, there will need to be a script which can look at the historical memberships to a group and compile calculate the audit score of each group from its unique participants over Phase 3

**Comment by mrsmkl** [comment]
Here is a version of the script,  https://github.com/mrsmkl/celo-monorepo/blob/baklava-analysis/packages/leaderboard/src/checkMembers.ts
Part of this PR https://github.com/celo-org/celo-monorepo/pull/2702
