### ISSUE TITLE
Celostats UI 2.0: Useability & design improvements

### ISSUE THREAD

**Issue by Pedro-vk** [celo-org/celo-monorepo#2691]
### Bugs/Improvements:
- [x] Pending transactions values are inconsistent compared with the previous UI
- [x] Define better colors code for validators number (100 is green, another value is not green)
- [x] Improve the visualization of "n time ago" (show seconds, minutes or hours depending on the value)

### Features:
- [x] Pin nodes at the beginning of the list
- [ ] Improve design following Celo style rules
- [x] Add propagation time charts for each node
- [ ] Create a filtering panel to be able to filter the nodes following some rules
- [x] Show the number of signatures in the last block
- [ ] Show chart of gas spent by the transaction (similar to gas spent by block)
- [x] Show validator group name instead of the address
- [ ] Settings:
  - [ ] List styles: compact or normal (normal could show charts in the cells, compact shouldn't)
  - [ ] Be able to stop the updates
  - [ ] Change refreshing rate
- [ ] Store some configuration
  - [ ] Save the last sorting or set it in the route
  - [x] Save settings config (list style, refreshing rate)

**Comment by Pedro-vk** [comment]
> Show chart of gas spent by the transaction (similar to gas spent by block)

@H34D, The transactions are not correct, is always: `[1, 0, 0, 0, 0, ... , 0, 0]`

**Comment by H34D** [comment]
most of this is blocked by: https://github.com/celo-org/celo-monorepo/issues/2824
