### ISSUE TITLE
App get crashed by tapping on ‘Save Image’ option from share menu options while sharing code image 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#2694]
**Frequency:** 100%
**App version:** iOS Test flight build 1.6.0 (21)
**Repro on:** iPod Touch 6th Gen (12.4), iPhone XS Max (13.1 beta)
**Testing Account:** 7166253911/[backup Key](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit?usp=sharing)

**Repro Steps:** 
1) Launch the app and login with testing account.
2) Tap on ‘QR Code’ icon 
3) Tap on ‘Share Code Image’ button 
4) Tap on ‘Save Image’ icon from share menu option and Observe 

**Current Behavior:** App gets crashed by tapping on ‘Save Image’ option 
**Expected Behavior:** QR code image should be saved in device 
**Attachment:** [iOS_App get crashed by tapping on Save Image.mp4](https://drive.google.com/file/d/1s4sNegR1zS75zgp4VoGtcTMWX5SwrDaZ/view?usp=sharing) (Bug observed at 12 sec)

**Comment by nityas** [comment]
Sentry Links: https://sentry.io/organizations/celo/issues/1499400550/?project=1250733&query=is%3Aunresolved
https://sentry.io/organizations/celo/issues/1499413650/?project=1250733&query=is%3Aunresolved

**Comment by Lss-Ankit** [comment]
Verified with IOS test flight build celo integration wallet v1.8.2 (37) and found that issue is fixed.

**Comment by Lss-Ankit** [comment]
Verified with IOS test flight build celo integration wallet v1.8.2 (37) and found that issue is fixed.
