### ISSUE TITLE
“Confirming...” text is continuously shown on transaction from Wallet > Activity section while proceeding for transaction when “Data saver” toggle is ON. 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#2704]
**Frequency:** 100%
**App version:** Internal Android Celo Alfa v1.6.0. 
**Repro on:** Google Pixel XL 2 (9.0), Samsung Galaxy A8+ (8.0.0), 
**Testing Account:** 7228953526/[backup Key](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit?usp=sharing)

**Pre-condition:** Make sure Data Saver toggle is ON. 

**Repro Steps:** 
1) Launch the app and login with testing account.
2) Tap on + tab. 
3) Tap on any celo user. 
4) proceed for transaction. 
5) Navigate to the Wallet tab and observe “Confirming...” text is shown continuously.

**Investigation:** 
1. I have waited until 5-10 minutes but still unable to proceed for the transaction. 
2. User is able to proceed for transactions when Data saver toggle is OFF. 
3. Issue does not repro in IOS test flight build 1.6.0 (21). 
4. After cold launch the app confirming Transaction activity is removed.  

**Current Behavior:** “Confirming...” text is continuously shown
**Expected Behavior:** Users should be able to proceed for transactions. 
**Impact:** User is blocked to proceed for transaction when data saver toggle is ON
**Attachment:**  [Android_ConfirmingIssue.mp4 ](https://drive.google.com/file/d/11gO59sM-XJC3F3Sb0z-vgBq3msgjQxp6/view?usp=sharing)(Bug observe at 19 sec)

**Comment by Lss-Ankit** [comment]
Verified on iOS Celo Alfajores Wallet (1.6.0 (21)) and Android Celo Alfa v1.6.0 and found the following 

Continuous loading indicator is shown when user invite any user if  “Data saver” toggle is ON
Impact: user blocked to invite any user when data Saver toggle is ON. 
Attachment: [Continous_LoadingIsShown.mp4 ](https://drive.google.com/file/d/1T_wcGS_mmsKWeS0lubf1aRPhYKEadX-Q/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
@annakaz @jmrossy Verified with the Android Celo Alfajores Wallet Playstore build (1.6.0 (104794306)) and found that the issue is still reproduced on mobile data when “Data saver” toggle is ON.

**Note:** Issue does not reproduce with wifi connection when 'Data saver' toggle is ON.

Verified on Devices : Samsung Galaxy A5 (7.0), Redmi Note 7 Pro (9.0)

'Confirming..' text is continuously shown on transaction from Wallet > Activity section while proceeding for transaction and Continues loading indicator is shown while inviting any user 

**Impact:** User is blocked to proceed with transaction & invite any user when data Saver toggle is ON.

Attachment1: [Android_Confiming text is shown continuoesly.jpg](https://drive.google.com/file/d/1NzoSeGVkKtomPiJoT9nhXR5auRb9LbU7/view?usp=sharing)
Attachment2: [Android_Continuous loading indicator is shown](https://drive.google.com/file/d/1GjfdICwjtBicXl4nDJPS6nbI4kSWc-Mu/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
@annakaz @jmrossy Verified with the Android Celo Alfajores Wallet Playstore build v1.6.1 and found that the issue is still reproduced on mobile data when “Data saver” toggle is ON.
Verified on Devices : iPhone 6+ (12.4.5) | iPhone 8 (13.3.1)

'Confirming..' text is continuously shown on transaction from Wallet > Activity section while proceeding for transaction and Continues loading indicator is shown while inviting any user

**Impact:** User is blocked to proceed with transaction & invite any user when data Saver toggle is ON.

Attachment: [IOS_Confirming_Issue_DataSaver_ON.MP4](https://drive.google.com/file/d/1CbwC2K1mQEkgqeY3BzUEt9vetf7Hsx-J/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
Verified with Android Celo Alfa RC build : 1.6.2 (101648776) & (104794504) and found that issue is fixed now. 'Confirming..' text gets removed from Wallet > Activity section and balance gets changed when Data saver toggle is 'On' 

Verified on Device: Samsung Galaxy A8 Pro (8.1.0), Google Pixel XL 2 (9.0)

Attachment : [Android_Confirming text gets removed](https://drive.google.com/file/d/19ciQWnkqPSWHGFGEUUp4JbLHsxhjs33y/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
@annakaz @jmrossy Verified with Android Celo Alfa RC build : 1.6.2 (101648776) & (104794504) and found that issue is fixed now. 'Confirming..' text gets removed from Wallet > Activity section and balance gets changed when Data saver toggle is 'On' 

Verified on Device: Samsung Galaxy A8 Pro (8.1.0), Google Pixel XL 2 (9.0)

Attachment : [Android_Confirming text gets removed](https://drive.google.com/file/d/19ciQWnkqPSWHGFGEUUp4JbLHsxhjs33y/view?usp=sharing)

Verified with iOS Celo Test flight build : 1.6.2 (24) and found that issue is fixed now. 'Confirming..' text gets removed from Wallet > Activity section and balance gets changed when Data saver toggle is 'On' 

Verified on Device : iPhone 7+ (13.3.1)

Attachment : [iOS_Confirming text gets removed](https://drive.google.com/file/d/19swAi2Fe_5TGkU7U2swfbI5wzyESy_PM/view?usp=sharing)

Hence, Closing this task. Thanks!

**Comment by Lss-Ankit** [comment]
@jmrossy  @annakaz Today Verified with Android Celo Alfa RC build : (104794504) and found that issue is reproduce again. 'Confirming..' text is shown on Wallet > Activity section and balance does not get changed when Data saver toggle is 'On'

Verified on Device: Samsung Galaxy Note 9 (10.0)

Attachment : [Android_Confirming text does not get removed](https://drive.google.com/file/d/1IEqs_MTEGY3Jb4sLf_F0usMtvWRFeXMR/view?usp=sharing)

Verified with iOS Celo Test flight build : 1.6.2 (24) and found that issue is reproduce again. 'Confirming..' text is shown on Wallet > Activity section and balance does not get changed when Data saver toggle is 'On'

Verified on Device : iPod Touch 6th Gen (12.4)

Attachment : [iOS_Confirming text does not get removed](https://drive.google.com/file/d/1FxwdqSaBfw1-MnBqFDHXqziZ58m2ebH8/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
@jmrossy and @annakaz Verified issue with Android play store (Internal build) v1.8.2 and found the following: 

- “Confirming...” text is continuously shown on transaction from Wallet > Activity section while proceeding for transaction for requested payment when “Data saver” toggle is ON

**=> Impact:** User is not able to proceed for requested payment when data saver is ON 

**Attachmet:** [PaymentIssue.mp4](https://drive.google.com/file/d/1DsfX-BXZ50OfdNGusPT405C8wbCAB6tR/view?usp=sharing)

**Invesigation:** 
- Verified user is able  to proceed for transaction for requested payment when data saver is OFF. 
- Verified user is able to proceed for transaction from + tab even when data saver is ON / OFF.

**Comment by tarikbellamine** [comment]
I believe this has been addressed. There is some general flakiness around the "Confirming..." text being indefinitely but looks more like a blockchain API issue than anything related to data saver mode.

**Comment by Lss-Ankit** [comment]
Verified with latest Test flight build v1.2.0 (25) , Android internal build 1.2.0(1004294313) and found that issue is fixed 
- User is able to do transaction when data saver toggle is ON. 

Devices used: Google Pixel Xl (8.1) iPhone 6+ (12.4.5)
