### ISSUE TITLE
Governance proposal transaction silently failing

### ISSUE THREAD

**Issue by yorhodes** [celo-org/celo-monorepo#2713]
### Expected Behavior

`celocli governance:propose` pushes a proposal to the queue

### Current Behavior

`celocli governance:propose` succeeds and displays `txHash` from receipt but no `ProposalQueued` event is emitted and `celocli governance:list` shows no existing proposals

checkout branch `yorhodes/baklava-attestations-upgrade`
steps to repro:
1. apply [patch](https://github.com/celo-org/celo-monorepo/pull/2645) of `Attestations.sol` to baklavastaging artifacts
2. deploy Attestations to baklavastaging by port-forwarding and running a new migration `25_new_attestations.ts`
3. construct a governance proposal using `ProposalBuilder.addProxyRepointTx` with the newly deployed contract's address and submit using `celocli governance:propose`
4. inspect network state with `celocli governance:list` and/or blockscout etc.

**Comment by yorhodes** [comment]
see https://baklavastaging-blockscout.celo-testnet.org/tx/0x7778693334153deb880571082890afcb0643dd4e70fb8d24a042d9649f51d3be/raw_trace

**Comment by mrsmkl** [comment]
Looks like the interface of `propose` was changed, so this call went to the fallback function. Perhaps we should check in the fallback that input is empty?
