### ISSUE TITLE
Add new assets to backup key + safeguards flow

### ISSUE THREAD

**Issue by nityas** [celo-org/celo-monorepo#2716]
### Expected Behavior

New Assets for interstitial screen before safeguard+backup key flows added here: [Figma](https://www.figma.com/file/HGX4zx5XSUeejjfGGI5x3R/Backup-Key-and-Recovery?node-id=0%3A1)

### Current Behavior

currently using default phone icon

**Comment by coreycelo** [comment]
Updated with Figma link
