### ISSUE TITLE
Celostats Beta missing tooltip on the validator names

### ISSUE THREAD

**Issue by H34D** [celo-org/celo-monorepo#2729]
### Expected Behavior

<img width="259" alt="Screenshot 2020-02-11 at 15 42 40" src="https://user-images.githubusercontent.com/13647606/74246776-5970ae00-4ce5-11ea-8dee-f9170549a72f.png">

### Current Behavior

There is no info tooltip on the validator names

### Related
https://github.com/celo-org/celo-monorepo/issues/3804

**Comment by Pedro-vk** [comment]
Not sure if it is useful. If I'm not wrong, in the feedback document someone said that.

**Comment by H34D** [comment]
> Not sure if it is useful. If I'm not wrong, in the feedback document someone said that.

Let's delay this till the new design is finished. I would like to avoid doing this twice.

**Comment by H34D** [comment]
given up for #3804
