### ISSUE TITLE
‘Could not refresh exchange rate’ error and continues loading indicator is shown on ‘Graph’ section while frequently navigating on ‘Gold’ tab after killing-relaunching the app when “Data saver” toggle is ON  

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#2754]
**Frequency:** 80%
**App version:** Play Store build : 1.6.0 (104794306)
**Repro on:** Samsung Galaxy A5 (7.0), Redmi Note 7 Pro (9.0)
**Testing Account:**13158358979 /backup Key

**Pre-condition:** Make sure Data Saver toggle is ON. 

**Repro Steps:** 
1) Launch the app and login with testing account.
2) Kill-Relaunch the app
3) Frequently navigate to ‘Gold’ tab 
4) Observe ‘Could not refresh exchange rate’ error and continues loading indicator is shown

**Investigation:** Issue does not repro when data saver is Off 
*Current Behavior:**  ‘Could not refresh exchange rate’ error and continues loading indicator is shown
**Expected Behavior:** ‘Could not refresh exchange rate’ error should not shown and Graph should be get loaded 

**Attachment:** [Android_Could't exchange rate' error is shown.mp4](https://drive.google.com/file/d/1dTu7OCv6GOB4u8WyErI6ioE8zQ-Q0t5S/view?usp=sharing) (Bug observe at 13 sec)

**Comment by Lss-Ankit** [comment]
@jmrossy Verified with Android build 1.7.0 (104894304) and observed issue is still repro randomly

- ‘Could not refresh exchange rate’ error and continues loading indicator is shown on ‘Graph’ section

Note: Data Saver toggle is not shown on Android build 1.7.0 (104894304)

Attachment:[GolTabIssue.mp4](https://drive.google.com/file/d/1W_CatyPVybWvULFoyqQBDWpCeiyy744v/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
Verified with latest IOS test flight Valora build v1.0.0(6) and observed that issue is Not Repro
- **Device Used:** iPhone 5(12.4.5)

**Comment by tarikbellamine** [comment]
@Lss-Ankit I am unable to reproduce. Please reopen if you can reproduce with the latest build.

**Comment by Lss-Ankit** [comment]
@tarikbellamine I have verified this issue using  latest build Android internal build v1.1.0 (1004294311) and Test flight build v1.1.0 (23) i will reopen this issue if i face it again for now it is fixed 
Graph is shown when user tap on celo button if Data saver is in enable mode 
**Device:** Samsung Galaxy A70(9.0)
