### ISSUE TITLE
Fix iOS warnings for wallet in App Store Connect

### ISSUE THREAD

**Issue by cmcewen** [celo-org/celo-monorepo#2828]
### Expected Behavior

We don't get emails

### Current Behavior

ITMS-90381: Too many symbol files

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information

**Comment by ole-nov** [comment]
closed because fixed
