### ISSUE TITLE
[Wallet] Security fee underestimated in Send screen

### ISSUE THREAD

**Issue by annakaz** [celo-org/celo-monorepo#2868]
### Expected Behavior

Fee estimate should be relatively accurate, and if it is off we should provide an overestimate

### Current Behavior

Fee estimate displayed is about half of what is actually charged- $0.0047 displayed but $0.0095 charged

![Screen Shot 2020-02-21 at 10 01 39 AM](https://user-images.githubusercontent.com/16907027/75059142-35555f80-5491-11ea-8f69-325a39886531.png)
![Screen Shot 2020-02-21 at 10 00 30 AM](https://user-images.githubusercontent.com/16907027/75059149-371f2300-5491-11ea-8f98-ff4194d24c96.png)

**Comment by annakaz** [comment]
This could be due to the gateway fee not being included cc @jeanregisser

**Comment by tarikbellamine** [comment]
@annakaz is this still an issue?

**Comment by ole-nov** [comment]
Discuss this with the blockchain circle / CAP

**Comment by ole-nov** [comment]
The issue seems to be resolved.
