### ISSUE TITLE
[Wallet] Contact photos only sometimes display when not verified

### ISSUE THREAD

**Issue by annakaz** [celo-org/celo-monorepo#2875]
### Expected Behavior

Photos always display when not verified

### Current Behavior

Photos don't display when not verified. But if a user navigates to the invite screen then the photos start to display. Note that this is not about importing contacts- the user has to navigate to the invite screen for each new app session in order to see the photos (and is not prompted for Contacts permissions)

<img width="343" alt="Screen Shot 2020-02-21 at 12 12 19 PM" src="https://user-images.githubusercontent.com/16907027/75068186-88381280-54a3-11ea-8b56-542fc257409b.png">

<img width="340" alt="Screen Shot 2020-02-21 at 12 12 37 PM" src="https://user-images.githubusercontent.com/16907027/75068180-866e4f00-54a3-11ea-9788-3e62e320020f.png">

**Comment by tarikbellamine** [comment]
Don't believe this is relevant anymore given the imminence of CIP8
