### ISSUE TITLE
Wallet should refresh balance on receiving payment notification

### ISSUE THREAD

**Issue by jmrossy** [celo-org/celo-monorepo#2878]
### Expected Behavior

Refreshed balance

### Current Behavior

Stale balance, and autorefresh wasn't working for some reason (tested in Nigeria on my iPhone)

**Comment by Lss-Ankit** [comment]
@jmrossy I have verified this issue in iOS Testflight build : 1.6.1 (23). Verified on Device : iPhone XS Max (13.1). 
Verified with Nigeria user : 2348153353131/**Backup key**(upset tumble shell wire advice wink muscle betray write excess menu gauge original nothing medal student broken settle limit mad stamp bright weird hard)

- I have verified issue with US and Nigeria number 
- Wallet balance gets updated automatically after receiving payment and also get always new push notification for each payment request & send payment 

Attachment : [US number payment receive](https://drive.google.com/file/d/19Q5XH94gShZDn2KdDaIUjNXfctGeS93l/view?usp=sharing) & [Nigeria number payment receive](https://drive.google.com/file/d/1BjfahhX5XzPaSDgzWEwSfdgWgY1e2oI8/view?usp=sharing)
