### ISSUE TITLE
‘Submit’ button does nothing from ‘Enter Pin’ page after entering invitation code  

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#2935]
**Frequency:** 100%
**App version:** iOS Testflight build : 1.6.1 build 22
**Repro on:** iPhone 7+ (13.3.1), iPhone X (13.3)
**Does not repro:** iPhone 6+ (12.4.5). 

**Repro Steps:** 
1) Launch the app and Register with new account
2) Enter invitation code and Tap on ‘Continue’ button 
3) Enter pin number and Tap on ‘Submit’ button 
4) Observe 

**Current Behavior:** ‘Submit’ button does nothing from ‘Enter Pin’ page 

**Expected Behavior:** User should be redirected to ‘Verification’ page 

**Attachment:** [iOS_Submit button does nothing.mp4](https://drive.google.com/file/d/16Bo90M7Fhh-Xeqv4Eef2hRnyWggsN1ls/view?usp=sharing) (Bug observe at 20 sec)

**Comment by jeanregisser** [comment]
I think the bug is that the registration was interrupted by killing the app.

There's a fix for that in https://github.com/celo-org/celo-monorepo/issues/2935

**Comment by Lss-Ankit** [comment]
@jeanregisser Issue also reproduce while going through the registration flow by submitting pin number. It does not reproduce only after killing the app.

**Comment by Lss-Ankit** [comment]
Verified with IOS test flight build celo integration wallet v1.8.2 (37) and found that issue is fixed.
