### ISSUE TITLE
App gets restarted automatically when user kill & relaunch the app   

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#2936]
**Frequency:** 100%
**App version:** Android Celo Alfajores Wallet build : v1.6.0 (101648579), Android Playstore build : 1.6.0 (104794306)
**Repro on:** Samsung Galaxy A5 (7.0), Samsung Galaxy J7 Prime (6.0.1), Samsung Galaxy J7 Pro (8.1.0), LG W30 (9.0)
**Testing Account:** 17542278234 /backup Key

**Repro Steps:** 
1) Launch the app and Login with test account 
2) Navigate to home page 
3) Kill-relaunch the app and Observe 

**Current Behavior:** App gets restarted after kill-relaunch the app  
 
**Expected Behavior:** App should not get restarted after kill-relaunch the app
 
**Attachment:** [App gets restarted.mp4](https://drive.google.com/file/d/1fXb0ucpaaQk8lBc9BTnylRWexps-E28-/view?usp=sharing) (Bug observe at 14 sec)

**Comment by jmrossy** [comment]
This looks like stale Geth instances still hanging around, which causes the app to restart so we can kill them

**Comment by Lss-Ankit** [comment]
verified with Android play store build v1.8.2 and observed that app is not getting restart after cold launch the app.
