### ISSUE TITLE
‘Fail to import contact’ error is shown and contact does not get synced when user navigates to ‘Send or Request’ page 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#2937]
**Frequency:** 90%
**App version:** Android Celo Alfajores Wallet build : v1.6.0 (101648579), Android Playstore build : 1.6.0 (104794306)
**Repro on:** Samsung Galaxy A5 (7.0), Samsung Galaxy J7 Pro (8.1.0), LG W30 (9.0),  Samsung Galaxy J7 Prime (6.0.1)
**Testing Account:** 17542278234 /backup Key

**Repro Steps:** 
1) Launch the app and Login with testing account
2) Tap on ‘+’ icon and Make sure syncing contact process is on
3) Wait for some time till syncing gets completed and Observe 

**Current Behavior:** ‘Fail to import contact’ error is shown and contact does not get synced 

**Expected Behavior:** Contact should be synced successfully 

**Attachment:**  [Fail to import contact error is shown.mp4](https://drive.google.com/file/d/1JA_a3W_uHxPixfDXvU8fOFII_1a2gcTo/view?usp=sharing) (Bug observe at 40 sec)

**Comment by Lss-Ankit** [comment]
@jmrossy Verified with Android Play store build v1.6.1 and observed that issue is still reproduced 

Verified on Device: Samsung Galaxy A5 (7.0), Samsung Galaxy S5 (6.0.1)

**Comment by Lss-Ankit** [comment]
@jeanregisser and @jmrossy  Verfied with iOS Test Flight Build v1.6.1 (23) and observed that issue is still reproduced. 

- ‘Fail to import contact’ error is shown and contact does not get synced when user navigates to ‘Send or Request’ page

Attachment: [IOSFailToContactError.mp4](https://drive.google.com/file/d/1Ta8QZaXTSeOmIL3ZJvntxbGAEaIKWEO_/view?usp=sharing)

**Comment by jmrossy** [comment]
@Lss-Ankit Can you share the logs after seeing this failure?

**Comment by Lss-Ankit** [comment]
Sure @jmrossy Please find the logs after seeing error message. 
[Invitelogs.txt](https://github.com/celo-org/celo-monorepo/files/4285609/Invitelogs.txt)

**Comment by jmrossy** [comment]
@Lss-Ankit Thanks for this but I need react native + geth logs.
Can you go to the app settings screen and use the Send Logs option?

**Comment by Lss-Ankit** [comment]
Sure @jmrossy Please find the logs from "Send as Issue Report" option from setting screen. 
Log: [celo_logs.txt](https://github.com/celo-org/celo-monorepo/files/4291081/celo_logs.txt)

**Comment by jmrossy** [comment]
@Lss-Ankit I've had a look at the logs. It seems like it wasn't just the contact sync that failed but also the fee calculation.

The logs suggest that geth (our blockchain client) didn't initialize properly. Can you clarify which build you tested with here? Can you also try killing the app and reopening it to see if that still occurs?

**Comment by Lss-Ankit** [comment]
@jmrossy I have verified this issue in Android play store build : 1.6.1 (104794404)
Verified on Devices : Samsung Galaxy A5 (7.0), Samsung Galaxy S5 (6.0.1)

- I have verified this scenario in device having ~100+ contacts. 
- Contact does not get imported for the first time, it shows 'Fail to Import contacts' error message. 
- 50 contacts gets imported after killing-relaunching the app first time 
- All contact gets imported after killing-relaunching the app second time 

Attachment : [Contact does not get imported](https://drive.google.com/file/d/1Nw4nZMK8PBpj3DwBn1gDngYx34yZqLDe/view?usp=sharing)

Device log : [error is shown for contact import](https://drive.google.com/file/d/19y0c74kXgUvMUPUd8MzodvLsuuH6e98J/view?usp=sharing)

**Comment by tarikbellamine** [comment]
@Lss-Ankit are you able to reproduce this on latest build? If so, please feel free to reopen it.

**Comment by Lss-Ankit** [comment]
Hi @tarikbellamine i have verified that issue on Play store build v1.8.2 and Test flight celo integration build v1.8.2 (40) and observed that issue is not reproduced.
