### ISSUE TITLE
[Android 7 OS & Above Specific] Nothing happens when user taps on “Get Youkey” button on “Backup & Recovery” page while user get the backup key 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#2938]
**Frequency:** 100%
**App version:** Android Celo Alfajores Wallet build : v1.6.0 (101648579)
**Not repro App version:** Android Playstore build : 1.6.0 (104794306)
**Repro on:** Samsung Galaxy A5 (7.0), Samsung Galaxy J7 Pro (8.1.0), LG W30 (9.0)
**Does not repro on:** Samsung Galaxy J7 Prime (6.0.1)

**Repro Steps:** 
1) Launch the app and Register with new account 
2) Navigate to home page and Navigate to ‘Backup & Recovery’ page 
3) Tap on ‘Get Your Key’ button and Observe 

**Investigation:** Randomly issue is also repro for 6 os device 

**Current Behavior:** ‘Get YourKey’ button does nothing on ‘Backup & Recovery’ page     

**Expected Behavior:** User should be redirected to ‘Your Backup Key’ page 
**Impact:** User is blocked to set up backup and recovery key & not able to logined again if they lost account. 
**Attachment:** [7 Os & above specific_button does nothing](https://drive.google.com/file/d/1zDIdVzB6gJ1avkzkPCARV_xPyp961umx/view?usp=sharing) (Bug observe at 8 sec)

**Comment by jmrossy** [comment]
@i1skn Could this be related to the pin check before loading the backup key?

**Comment by Lss-Ankit** [comment]
@jmrossy and @i1skn Verified with Play store build v1.6.1 and found the following: 

- Nothing happens when user taps on "Get Your Key" on Backup and Recovery if user has set device security PIN. 
- User is redirects to Your Backup Key screen when user taps on "Get Your Key" button on Backup and recovery screen if user has enter security PIN manually.
- Issue is also reproduce for 'Setup Safeguard' button 

**Verified Device:** Samsung Galaxy A5 (7.0),

**Attachment:** [Android_Get backup key does not get tappable.mp4](https://drive.google.com/file/d/1pTeLcxPN2gDti8OjNpINYHjzTZI0KhgW/view?usp=sharing)

**Comment by jmrossy** [comment]
@cmcewen has found this to be related to pincodes. He has a patch here:
https://github.com/celo-org/celo-monorepo/compare/cmcewen/pincode?expand=1

**Comment by i1skn** [comment]
Fixed in https://github.com/celo-org/celo-monorepo/commit/a437bef2bdba96d57d9dfab9592e962b754d7121

**Comment by Lss-Ankit** [comment]
@i1skn & @jmrossy Verified with Android Celo Alfa build : 1.6.2 (101648776). Verified on Device : Moto Z Play (8.0), Samsung Galaxy J7 Prime (6.0.1). 

- Issue is fixed now. User redirects to 'Your Backup key' page by tapping on ''Get Your Key' button from 'Setup Your Backup key' page for the user who has added phone authentication or creates a pin 

Attachment : [Android_Get Your key button is accessible](https://drive.google.com/file/d/1xsEyWaEHJIad6wifUnJcL0-SrH3uEw9u/view?usp=sharing)
