### ISSUE TITLE
Move to lottie-light

### ISSUE THREAD

**Issue by aaronmgdr** [celo-org/celo-monorepo#3037]
Lotttie-web is really big. 

there exists a smaller version. key difference is it only supports svg render. however simply changing the import from  `lottie-web` to 'lottie-web/build/player/lottie_light'`  drastically changed the reported build sizes

# Lottie Light on Left vs Lottie on RIght
<img width="683" alt="Screen Shot 2020-03-05 at 3 34 34 PM" src="https://user-images.githubusercontent.com/3814795/76036034-d7486380-5ef7-11ea-96a6-96008c11f868.png">

**Comment by aaronmgdr** [comment]
https://github.com/airbnb/lottie-web/issues/929

**Comment by aaronmgdr** [comment]
decided not to as it would limit what we ca do with lottie to much

**Comment by honeyamin** [comment]
can use interactivity by lottie_light?? tnx
