### ISSUE TITLE
Address Tech Debt in Firebase (coupling w/ app, project structure, etc)

### ISSUE THREAD

**Issue by nityas** [celo-org/celo-monorepo#3060]
### Expected Behavior

Please describe the behavior you are expecting

### Current Behavior

What is the current behavior?

**Comment by i1skn** [comment]
Reference to an issue with upgrading react-native firebase library to v6 https://github.com/celo-org/celo-monorepo/issues/2571

**Comment by tarikbellamine** [comment]
@nityas should this still be open?

**Comment by ole-nov** [comment]
closed as fixed
