### ISSUE TITLE
Address High Priority Wallaby Issues

### ISSUE THREAD

**Issue by nityas** [celo-org/celo-monorepo#3068]
### Expected Behavior

Please describe the behavior you are expecting

### Current Behavior

What is the current behavior?

**Comment by i1skn** [comment]
Here is the doc with all the issue so far https://docs.google.com/document/d/1vnRlIipah7PPKvTAxPFl1PHVMrSccKZx0HklrUl7UrQ/edit.
I plan to convert them to github issues one by one, when ready to consume and update the doc accordingly.

cc: @nityas
