### ISSUE TITLE
Adversarial testing of stability protocol

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-monorepo#3078]
Create a table with columns described below and fill it with all attacks you can think of.

Table columns:
- attack category
- attack
- how easy attack is - CVSS score vector-  https://chandanbn.github.io/cvss/ )
- impact of attack (service availability, time, cost, reputation, etc)
- metric(s) by which this attack could be identified and by which an alert could be triggered
- remediation time 
- possible mitigations (and cost/effort of each)

**Comment by jose-compu** [comment]
Added a possible attack (non-critical) and a solution:

**Testing timining attack with no bucket updates. https://github.com/celo-org/celo-monorepo/pull/3283**

**Comment by diminator** [comment]
spreadsheet with possible attacks and network conditions ranked according to likelihood and impact:
https://docs.google.com/spreadsheets/d/1OjX6ahXjv3E89C3HNRmmYxHos2Ft9CNpDZk9fiipJTk/
