### ISSUE TITLE
Whole network blackbox load/scale/failure tests

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-monorepo#3079]
Whole network blackbox load/scale/failure tests:  "Staggered start"  
* High latency validator connections
* Transaction throughput test
* Scale to 150,200 validators, 500 regd groups+vals
* Scale to 100 full nodes, 10,000 light clients 
* Load testing with full/light/lightest tx load
* Audit alerts and metrics received

**Comment by jcortejoso** [comment]
Tested the quorum tests with the latests master commits from `celo-blockchain` and `celo-monorepo` and the results are good. Validators are able to reconnect quite fast if quorum is lost but also when quorum is not lost.

**Comment by jcortejoso** [comment]
https://docs.google.com/document/d/1YzH7NczCtCRPiqGUumKUTrGj1lsNdWE9ILsfj_ydYIg/edit#heading=h.aem24wibg9rc
