### ISSUE TITLE
Validator Explorer add URL attestations for domain

### ISSUE THREAD

**Issue by diminator** [celo-org/celo-monorepo#3081]
- [x] fetch URL attestations from blockscout
- [x] design attestations in frontend
https://www.figma.com/file/OklIpLbUEkxGZ4RMUoZyO2/Validator-Experience?node-id=0%3A1
- [x] implement design

**Comment by aaitor** [comment]
Blockscout Graphql query can be found here: https://github.com/celo-org/celo-monorepo/issues/3086#issuecomment-606508958
