### ISSUE TITLE
Web : ‘Unable to complete’ error message is shown after clicking on ‘Get Started’ button by adding required fields on ‘Celo Wallet’ page 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#3119]
**Frequency:** 100%
**Repro on Browser:** Google Chrome 80.0.3987.132, Firefox 74

**Repro Steps:** 
1) Launch the Website https://celo.org/developers/wallet
2) Select any country and enter any country’s number (US, Ukraine, India, France number)
3) Select any platform and Checked ‘I’m not a robot’ checkbox
4) Click on ‘Get Started’ button (Bug)

**Current Behavior:** ‘Unable to complete’ error message is shown

**Expected Behavior:** ‘Get Started’ button gets changed to ‘Received SMS in 1-2 min’ and respective number should receive invitation code 

**User Impact:** User does not received invitation code 

**Investigation:** Issue is also reproduce for US, Ukraine, India, France number
 
**Attachment:**  [Unable to complete error message is shown.mp4](https://drive.google.com/file/d/1_9PaHLr0xyOntAYrCDKqcuoJf9MFPp1p/view?usp=sharing) (Bug observed at 0:41 secs)

**Comment by Lss-Ankit** [comment]
@jmrossy Issue is also reproduce for while fauceting address from 'Fund Your Test Account' page after clicking on 'Get Started' button 

Attachment : [error is shown while fauceting](https://drive.google.com/file/d/1LOzHNao1RCnClGWbmM0--LHR-i_kncvH/view?usp=sharing)

**Comment by jmrossy** [comment]
Account was out of gold

**Comment by Lss-Ankit** [comment]
Verified and found that issue is fixed now user is getting the Celo invitation and able to faucet account too.
