### ISSUE TITLE
Android : Samsung Galaxy J7 Pro (8.1.0) Specific : App get crashed when user turned on ‘Data saver’ toggle after exchanging cUSD to cGLD 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#3135]
**Frequency:** 50%
**Android App version:** Celo Alfa RC build : 1.6.2 (101648776)
**Repro on Android Device:** Samsung Galaxy J7 Pro (8.1.0)
**Does not repro on Android Device:** Samsung Galaxy A9 Pro (8.1.0), Google Pixel XL 2 (9.0), Samsung Galaxy A8+ (8.1.0)
**Testing Account:** 3155641283 /backup Key

**Repro Steps:** 
1) Launch the app and Login with test account 
2) Make sure data saver toggle is turned off 
3) Exchange the cUSD to cGLD and Make sure transaction is proceed 
4) Navigate to Settings > Data Saver option > Turn on ‘Data Saver’ toggle (Bug)

**Current Behavior:** App get crashed when user turned on ‘Data saver’ toggle

**Expected Behavior:** ‘Data saver’ toggle should be turned on 

**Investigation:** Issue does not reproduce if user enables the toggle before exchanging cUSD to cGLD in disabled toggle 

**Attachment:**  [Android_app get crashed by turning on data saver toggle.mp4](https://drive.google.com/file/d/1toTPlVAdz9lK-J7B65ZWXDEt18HtMjRn/view?usp=sharing) (Bug observed at 1:25 mins)

**Comment by tarikbellamine** [comment]
I believe the crash when switching between geth and forno has been resolved by @annakaz

**Comment by Lss-Ankit** [comment]
- Verified issue with latest build Test flight build v1.2.0 (25), Android internal build 1.2.0(1004294313) and found that issue is fixed.

Devices used: Samsung Galaxy A70(9.0)
