### ISSUE TITLE
 “Transaction Failed” error message is shown when trying to make a payment with Data Saver toggled on. 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#3155]
**Frequency:** 100%
**App version:** Test flight v1.6.2(24)
**Repro on:** iPhone 7+( 13.3.1)
**Does not Repro on:** iPhone 5S(12.41.)
**Testing Account:** 6504908232/backup Key
**Pre-condition:** Make sure Data Saver toggle is ON.

**Repro Steps:**
1. Tap on  + icon from home page. . 
2. Initiate a payment. 
3. Enter amount and tap on Send button. . 
4. Wait for the confirmation of the payment. 
5. Observe 

**Current Behavior:** Transaction failed Error message is shown after 2 minutes of initiating the transaction.  
**Expected Behavior:** Payment should be done successfully. 
 
**Investigation:** Issue is not repro if we request for any payment with Data Saver toggle on. 
 
**Attachment:**[ iOS_TransactionFailed.mp4](https://drive.google.com/open?id=1jt3SmlMnGQN1AZ30bFT6UkwmCnmpN0_v) (Bug observe at 10 sec)

**Comment by Lss-Ankit** [comment]
@jeanregisser Verified with iOS Test flight build : v1.6.3 (25). Verified on Device : iPhone SE (13.3) and Observed that issue is still reproduced. 'Transaction Failed, please retry' error message is shown when user trying to exchange cGLD with Data Saver toggle on.

Attachment : [iOS_Transaction Failed error message is shown](https://drive.google.com/file/d/1geB8SCCBSXssepQr8Qby-Wx6EhK4FFjO/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
@jeanregisser Verified with iOS Test flight build : v1.6.3 (25). Verified on Device : iPhone SE (13.3), iPhone 6+ (12.4.5) and Observed that issue is still reproduced. 'Transaction Failed, please retry' error message is shown when user trying to exchange cGLD with Data Saver toggle on/off

Attachment : [iOS_Transcation failed error shown](https://drive.google.com/file/d/1YsTRUK83J2zOrbUedvnlhSMlvtuY52sY/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
@jeanregisser @annakaz Verified with latest test flight build v1.8.2 (40) and found that issue is reintroduced. 

- "Transaction fail..." error message is show when user proceed for payment with data saver toggle ON. 
Also, Observed that Incorrect PIN is shown even though user entering correct PIN while enter PIN for Account Key setup, make payment with Data saver toggle ON. 

**Device used:** Iphone 11 (13.1) , Iphone 6+ (12.4.5) 

**Attachement:** 
1. [TransactionIssue.mp4](https://drive.google.com/file/d/1y-q1W5q0svqCYyZQS2Xdp3XEF9cIc1z7/view?usp=sharing)
2. [IncorrectPInIssue.mp4](https://drive.google.com/file/d/1nOgaZFAZtb7jb_gfnRe9cDrMfNK8Zc9c/view?usp=sharing)

**Comment by tarikbellamine** [comment]
I think this is general transaction flakiness rather than something specific to data saver mode.

**Comment by Lss-Ankit** [comment]
Verified on latest build Test flight build v1.2.0 (25) , Android internal build 1.2.0(1004294313) and found that issue is not able to repro.

Devices: Devices used: Google Pixel Xl (8.1) iPhone 6+ (12.4.5)
