### ISSUE TITLE
Add coverage and coverage report for Protocol

### ISSUE THREAD

**Issue by jose-compu** [celo-org/celo-monorepo#3197]
### Expected Behavior

We should have truffle coverage metrics or similar for unit testing. Testing is already excellent in detail.

### Current Behavior

No coverage per module, no coverage summary.

**Comment by jose-compu** [comment]
Trying `yarn run truffle coverage` but fails due to compiling issued (solc version?)"

```
> Compiling solidity-bytes-utils/contracts/BytesLib.sol

> solidity-coverage cleaning up, shutting down ganache server
Error: CompileError: * Line 1, Column 1
  Syntax error: value, object or array expected.
* Line 1, Column 3
  Extra non-whitespace after JSON value.
```
Was `solidity-coverage` added to `package.json`:

`"solidity-coverage": "0.7.2",`


and to truffle plugins at `truffel-config.js:

```
module.exports = {
    plugins: ['truffle-security', 'truffle-plugin-blockscout-verify', 'solidity-coverage'],

```

**Comment by nambrot** [comment]
Dupe of #5411
