### ISSUE TITLE
Add end-to-end testing for Reserve, Exchange or SortedOracles

### ISSUE THREAD

**Issue by jose-compu** [celo-org/celo-monorepo#3198]
### Expected Behavior

End-to-end 5-validator command-line testing for Reserve, Exchange or SortedOracles, similar to e2e tests:

- 'end-to-end-slashing-test': https://app.circleci.com/pipelines/github/celo-org/celo-blockchain/3137/workflows/fc057f80-ee73-41f4-81cc-8d7e54b53557/jobs/28360
 - 'end-to-end-governance-test': https://app.circleci.com/pipelines/github/celo-org/celo-blockchain/3137/workflows/fc057f80-ee73-41f4-81cc-8d7e54b53557/jobs/28365

### Current Behavior

No e2e test for this use cases.

**Comment by nambrot** [comment]
Closed with #6393
