### ISSUE TITLE
Users SBAT see the skip button on the Get Backup Key screen

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-monorepo#32]
### Expected Behavior

As a user, I should be able to see the entirety of the "Skip" button, no matter what android device I'm using.

### Current Behavior

On an LG phone with model number LM-X410ULMG, the skip button is covered by the phone's controls. The screen is not scrollable.

![Image from iOS](https://user-images.githubusercontent.com/1222891/61382396-00ef4480-a8ad-11e9-93d0-1d4665b6450f.jpg)

**Comment by sallyjyl** [comment]
@ashishb which phone was this having problem with?
Checked the LM-X410ULMG again, and it seems to be fine
![Screenshot_2019-08-06-12-53-11](https://user-images.githubusercontent.com/25536485/62535050-be38e080-b84a-11e9-932f-52ed3bbd1fc4.png)
