### ISSUE TITLE
Make pendingWithdrawals index internal

### ISSUE THREAD

**Issue by jose-compu** [celo-org/celo-monorepo#3200]
### Expected Behavior

Index should be internal or at least clearly documented on command line client.

### Current Behavior

@jansel suggestion: The documentation does not warn about Index reordering of PendingWithdrawal, that is error prone for Withdrawals. Can be mitigated with Documentation on the following Milestone, but is still error prone until fixed, possible in the Milestone following the next one. Hide the index internally? Reordering on `deletePendingWithdrawal()`.

**Comment by jose-compu** [comment]
On https://github.com/celo-org/celo-monorepo/blob/b689f90c57d8e2ed7f86b56a69d3a4e765e643a0/packages/cli/src/commands/lockedgold/withdraw.ts#L31 if we have 2 pending withdrawals the second withdrawal (index 1) should break because the first withdrawal (index 0) is deleting the first item from the array.

**Comment by asaj** [comment]
Nice catch! Can we aim to merge a fix by Friday, and include a test so we don't accidentally break this again?

**Comment by jose-compu** [comment]
@asaj Yep, we can aim.

**Comment by jose-compu** [comment]
Before fix:

` FAIL  src/commands/lockedgold/withdraw.test.ts (6.31s)
  lockedgold:lock cmd
    ✕ can withdraw multiple withdrawals simultaneously (4371ms)

  ● lockedgold:lock cmd › can withdraw multiple withdrawals simultaneously

    expect(received).toBe(expected) // Object.is equality

    Expected: "25"
    Received: "75"`

**Comment by aslawson** [comment]
@asaj was this fixed?
discussion indicates it may have been worked on, but looks like this line is still the same in the codebase
https://github.com/celo-org/celo-monorepo/blob/master/packages/cli/src/commands/lockedgold/withdraw.ts#L31
