### ISSUE TITLE
Relock() command of LockedGold not documented for client

### ISSUE THREAD

**Issue by jose-compu** [celo-org/celo-monorepo#3205]
### Expected Behavior

Have `relock()` as an option. 

### Current Behavior

Command line client has no relock or is not documented:

[](https://docs.celo.org/command-line-interface/lockedgold
)

**Comment by timmoreton** [comment]
Asa: This is intentional to make the user facing API more friendly. When you call `lockedgold:lock` it first tries to re-lock any pending withdrawals before going to you regular gold balance
