### ISSUE TITLE
.env file should contain the config which will be deployed not what was deployed

### ISSUE THREAD

**Issue by ashishb** [celo-org/celo-monorepo#321]
### Expected Behavior

Files like https://github.com/celo-org/celo-monorepo/blob/master/.env.integration should contain the config which will be used on the next deployment. This is similar to how source code changes reflect future deployment and not what has been deployed. `celotool` should automatically upload the deployed config to Google cloud storage, for example to `gs://env_config/<network_name>/<timestamp>`.

### Current Behavior

`.env.<envname>` is expected to contain the config post-deployment not what has been deployed.

**Comment by tkporter** [comment]
Completed by #1086
