### ISSUE TITLE
“Phone authentication , Create new pin” buttons are disabled when the app is killed and relaunched after multiple (Five) failure attempts of phone authentication.

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#3212]
**Repro Build:** Play store v1.6.2
**Repro devices:** Google Pixel (8.1)
**Frequency:** 100%

**Repro Steps:**
1. Install the app. 
2. Enter a Phone number and tap on continue button. 
3. Tap on use phone authentication  button.
4. Enter incorrect password for 5 times. 
5. Wait until the error message is shown for wait for 30 second and retry. 
6. Kill the app and reopen it. 
7. Tap on the continue button after entering  phone number. 
8. Observe.  

**Investigation:** 
user should need to clear app data or reinstall the app for further attempts

**Attachment**:  Buttons_Disabled.mov https://drive.google.com/open?id=1pMJvnwgK0W3raToj9_b2ODrVFe9mlPn9

**Comment by i1skn** [comment]
Phone Authentication method was removed, so this issue is not relevant anymore.
