### ISSUE TITLE
Android & iOS : “cUSD” & “cGLD” amounts are not shown into the app when the user navigates into the app without entering the invitation code. 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#3236]
**Frequency:** 100%
**Android App version:** Android Play store build : v1.6.2
**iOS App version:** iOS Play store build : v1.6.2
**Repro on Android Device:** Samsung Galaxy J7 Prime (6.0.1)
**Repro on iOS Device:** iPhone 11 Pro (13.3)

**Repro Steps:** 
1) Launch the app and Enter the phone number
2) Tap on ‘Continue’ button and Add security pin 
3) Navigate to ‘Invitation Code’ page and Tap on ‘Continue without’ link 
4) Navigate into the app and Observe on wallet and gold tab 

**Current Behavior:** “cUSD” & “cGLD” amounts are not shown into the app

**Expected Behavior:** “cUSD” & “cGLD” amounts should be shown into the app

**Attachment:** [Android_Dolloar amount is not shown on wallet page](https://drive.google.com/file/d/1cxYzPe8IaCTMqsBP3WQlc7TUGvCT--S6/view?usp=sharing) (Bug observed at 52 secs)

**Comment by annakaz** [comment]
Fixed following redesign

**Comment by Lss-Ankit** [comment]
Verified with latest IOS test flight build v1.9.1(41) and observed that issue is Fixed
**Device Used:** iPhone 6(12.4.7)
