### ISSUE TITLE
Add currency options in the Celo wallet

### ISSUE THREAD

**Issue by critesjosh** [celo-org/celo-monorepo#3240]
Parent:  #3642 
### Expected Behavior

The following currency options should be added in the Celo wallet settings:
Turkey(TRY)
Argentina(ARS)
Brazil(BRL)
Chile(CLP)

### Current Behavior

It is not listed.

**Comment by jmrossy** [comment]
@critesjosh Please don't forget to add labels to new issues

**Comment by nityas** [comment]
cc @jmrossy updated with the list of countries!

**Comment by tarikbellamine** [comment]
Done
