### ISSUE TITLE
[Wallet] Incorrect balance shown upon first app load in non USD currency

### ISSUE THREAD

**Issue by annakaz** [celo-org/celo-monorepo#3243]
### Expected Behavior

Loading icon / no balance shown instead of assuming 1:1 rate before it's fetched

### Current Behavior

Short moment when exchange rate is loading that incorrect balance is shown as 1:1 rate is assumed- this can be a scary experience as the balance can be 100 times smaller for Kenyan Shillings for example. Note that this is more pronounced in low connectivity environments

**Comment by tarikbellamine** [comment]
I believe this has been addressed
