### ISSUE TITLE
[Wallet] App gets stuck on blank green screen (not geth related)

### ISSUE THREAD

**Issue by annakaz** [celo-org/celo-monorepo#3249]
### Expected Behavior

App users see an error screen if necessary

### Current Behavior

In low connectivity environment on slower phones, upon opening the app it sometimes gets stuck on blank green (no celo logo). Waiting several minutes the app remains stuck, but killing the app and reopening it fixes it. In the past we've seen this with geth issues but this was happening in forno mode as well. This is not much info to go on but I didn't grab logs, just creating this issue to track in case we see it again

**Comment by nityas** [comment]
closing as not reproducible currently-- will reopen if occurrences are seen again
