### ISSUE TITLE
Investigate Translation SAAS like crowdin

### ISSUE THREAD

**Issue by aaronmgdr** [celo-org/celo-monorepo#3255]
Investigation Findings 
Crowdin ✅
	- free for open source
		* saving money
	- used by ethereum, Facebook, etc 
		* proven, community knows how to use
	- integrates with GitHub
		* easy to keep translations up to date

**Comment by comradekingu** [comment]
Crowdin isn't free for libre software, it is only "free" for non-commercial libre software.
 > If you're building awesome non-profit projects that could use the power of Crowdin, we're happy to help.
https://crowdin.com/pricing#annual 

Crowdin itself is unfree closed source, with tracking left right and center https://support.crowdin.com/cookies/.
Most libre software projects use Weblate.
Crowdin has a terrible voting system, and sub-par navigation.

Crowdin is a mess to administer.

**Comment by aaronmgdr** [comment]
oh good to know!

**Comment by aaronmgdr** [comment]
Weblate looks real good. I can't believe I had not found it before.  Thanks for pointing us to it.

**Comment by orangesunny** [comment]
Greetings from Weblate! Thank you for the kind words! We will be happy to welcome a new libre project in our community! As a maintainer, @aaronmgdr, please fill the form on https://hosted.weblate.org/hosting/ and we will set it up if you want! Have a great day!
