### ISSUE TITLE
Locked gold requirement prompts should pull params from chain

### ISSUE THREAD

**Issue by asaj** [celo-org/celo-monorepo#3267]
### Expected Behavior

Confirmation prompts for `validatorgroup:member` and `validator:affiliate` pull the locked gold requirement params directly from the chain rather than have them be hard coded

**Comment by aslawson** [comment]
https://github.com/celo-org/celo-monorepo/blob/master/packages/cli/src/commands/validatorgroup/member.ts#L62

https://github.com/celo-org/celo-monorepo/blob/master/packages/cli/src/commands/validator/affiliate.ts#L44
