### ISSUE TITLE
Celostats&Celo-blockchain: Proxied nodes are not able to reconnect to celostats

### ISSUE THREAD

**Issue by jcortejoso** [celo-org/celo-monorepo#3273]
### Expected Behavior
If the connection celostats<-->proxy<-->validator is closed for any reason, celostats should be able to reconnect again.

### Current Behavior

The proxied validators are not able to reconnect to celostats if the connection is lost for any reason. 
There is not any log difference between the non-proxy node (able to reconnect) and the proxied node.

**Comment by H34D** [comment]
fixed by unlocking the etherbase account on the proxy
