### ISSUE TITLE
How to handle ABI changes when upgrading smart contracts from protocol

### ISSUE THREAD

**Issue by H34D** [celo-org/celo-monorepo#3288]
### Expected Behavior

Once a contract gets upgraded with the governance process, its effect will come into place. When this contract implements a change to the ABI (that might be breaking or non breaking) it has to be propagated to the consuming applications.

There are several strategies to handle this issue:

1. Sliding: hold two versions of the ABI at the same time and switch once the contract was switched
2. Addition only: changes are not allowed to be breaking and the ABI can be rolled out once the feature is going to be implemented in the consuming application
3. ... tbd

### Current Behavior

No ABI handling in place

**Comment by nambrot** [comment]
Closing in favor of #4954
