### ISSUE TITLE
iOS: ‘Nan’ text is shown for ‘Estimation fee’ on ‘Sell gold’ confirmation screen while selling gold 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#3316]
**Frequency:** 100%
**iOS App version:** iOS Testflight build : v1.6.3 (25)
**Repro on iOS device:** iPhone SE (13.3), iPhone XS Max (13.1), iPhone 6+ (12.4.5)
**Testing Account:** 3155641283 /backup Key

**Repro Steps:** 
1) Launch the app and Login with test account
2) Navigate to gold tab > Tap on ‘Sell’ button 
3) Enter any amount and Tap on ‘Review’ button 
4) Navigate to ‘Sell gold’ confirmation screen and Observe ‘Estimation fee’ 

**Current Behavior:** ‘Nan’ text is shown for ‘Estimation fee’ on ‘Sell gold’ confirmation screen 

**Expected Behavior:** Respective estimation fee should be shown 

**Investigation:** 
1) Issue does not reproduce in Android 
2) Issue does not reproduce while buying gold 

**Attachment:** [iOS_Nan text is shown.png](https://drive.google.com/file/d/1nlMvjN7bpHTLzrDvhxpmLhnTObfpVdOw/view?usp=sharing)

**Comment by tarikbellamine** [comment]
I think this is addressed

**Comment by Lss-Ankit** [comment]
@tarikbellamine i have verified this issue latest build Android internal build v1.1.0 (1004294311) and Test flight build v1.1.0 (23) and found issue is fixed
Device: iPhone 11 (14iOS), Samsung Galaxy A70(9.0)
