### ISSUE TITLE
Wallet transaction limits $500 cUSD/day

### ISSUE THREAD

**Issue by jmrossy** [celo-org/celo-monorepo#3329]
### Expected Behavior

Wallet can't send more than $500 USD / day
Part of #3063

### Current Behavior

No limits

**Comment by nityas** [comment]
designs here: https://www.figma.com/file/PyK5VI7mE2fpHLeRPL0yxB/Transaction-Limit?node-id=0%3A1
cc @etuleu @jmrossy @coreycelo
