### ISSUE TITLE
User Education screens around tx limits

### ISSUE THREAD

**Issue by jmrossy** [celo-org/celo-monorepo#3330]
### Expected Behavior

1. When user hits send if the amount entered will put them over the daily limit show the red banner (see figma) 

2. on onboarding the legal disclaimers are now on their own screen

Part of #3063

### Current Behavior

1. no tx limit warnings

2.disclaimers on same screen as the user info

**Comment by nityas** [comment]
designs here: https://www.figma.com/file/PyK5VI7mE2fpHLeRPL0yxB/Transaction-Limit?node-id=0%3A1

cc @aaronmgdr @jmrossy @coreycelo

**Comment by jmrossy** [comment]
@nityas is that the right link? Don't see anything about tx limits

**Comment by nityas** [comment]
Oops! Updated with the correct link

**Comment by aaronmgdr** [comment]
This about the red banner that shows how much of daily limit has been used on  (each or just when approaching limit?) send?

**Comment by jmrossy** [comment]
@aaronmgdr This is just about the new screens. @etuleu is working on the underlying changes in the saga code to enforce the limit
