### ISSUE TITLE
Devs SBAT verify nested translations exist in all languages

### ISSUE THREAD

**Issue by drklee3** [celo-org/celo-monorepo#334]
### Expected Behavior

Nested locale strings should be verified to exist in all languages.

### Current Behavior

Currently Circle does verify that locale strings' keys exist in both languages, but does not include *nested* keys such as in `nuxNamePin1.json`:

```bash
$ cat packages/mobile/locales/es-AR/*.json | jq -r '[paths | join(".")][]' | sort > es
$ cat packages/mobile/locales/en-US/*.json | jq -r '[paths | join(".")][]' | sort > en
$ diff es en
461a462
> systemAuth.secure
```

The `systemAuth.secure` key is missing from the Spanish translations.

**Comment by jeamick** [comment]
Hello @drklee3,

Does the goal is to provide multiples language support to enable more " language inclusion"?
Thanks
JM

**Comment by drklee3** [comment]
The goal is just to check if there are any missing translations in the json locale files.

An example is given in the issue description, where the [`systemAuth.secure`](https://github.com/celo-org/celo-monorepo/blob/master/packages/mobile/locales/en-US/nuxNamePin1.json#L77) locale string doesn't exist in the [Spanish file](https://github.com/celo-org/celo-monorepo/blob/master/packages/mobile/locales/es-AR/nuxNamePin1.json#L77-L83).
