### ISSUE TITLE
Clean up signing libraries

### ISSUE THREAD

**Issue by codyborn** [celo-org/celo-monorepo#3410]
### Expected Behavior

Remove usage of `eth-lib` (should use `ethereumjs-util` instead).
Consolidate definition of Signature object (v,r,s) that performs type validation. 

### Current Behavior

Currently we have a variety of different signing libraries/utilities (signatureUtils & signing-utils) that perform similar operations.

**Comment by oneeman** [comment]
@barbaraliau I happened upon that library and saw this in its README:

> Lightweight Ethereum libraries. This is a temporary repository which will be used as the basis of an implementation on Idris (or similar).
>
> Edit: please, don't use this lib. I worked on it for a few days and stopped to create Formality. Eventually I'll make Ethereum libraries in Formality and compile them to JavaScript. Right now, if you need Ethereum stuff on the browser, consider alternatives (web3, ethers, ethereumjs, etc.). Also, for account signing and creation, consider http://github.com/maiavictor/nano-ethereum-signer

Should this issue be prioritized given that the library's author recommends it not be used?
