### ISSUE TITLE
[wallet]Users SBAT to run the app in an infura-like setup

### ISSUE THREAD

**Issue by ashishb** [celo-org/celo-monorepo#342]
### Expected Behavior

Users SBAT to run the app in an infura-like setup where the app holds the keys, signs transactions locally while a remote node acts as a full node and syncs with the network.

### Current Behavior

The app runs an ongoing Celo node which runs in an ultralight sync mode.

**Comment by jeamick** [comment]
hello @ashishb,

Is it a geth node or a Celo node(similar to geth node..) ? Like be able to setup a cloud node and directly connect a light node to it right ?

Thanks

**Comment by ashishb** [comment]
@jeamick It is about being able to connect to a Celo node and let it do the heavy-lifting associated with running the blockchain, fetching blocks, fetching the merkle proofs, and waiting for the transactions to be approved.
