### ISSUE TITLE
end-to-end-geth-governance-test Failing on Epoch Rewards

### ISSUE THREAD

**Issue by jose-compu** [celo-org/celo-monorepo#3429]
### Expected Behavior

Not failing tests.

Many tests are encapsulated on a single epoch rewards test (`should distribute epoch payments at the end of each epoch`). Stacktrace is not allowing to observe which assert is failing.

The failing assert is using `assertVotesChanged` that is used two times on:

- `await assertVotesUnchanged(blockNumber)` for blocks that are not the last block of the epoch.
- `await assertVotesChanged(blockNumber, expectedVoterRewards)` for last block of the epoch.

### Current Behavior

Two tests are failing. The rewards test is only failing in more than 0.0000123% of the reward (5000000000000 of 400529569070325000000).

`  10 passing (14m)
  2 failing

  1) governance tests
       when the validator set is changing
         should distribute epoch rewards at the end of each epoch:
     AssertionError: expected 34158793538676421760 to almost equal 40529569070325000000 +/- 5000000000000
      at Object.assertAlmostEqual (src/e2e-tests/utils.ts:111:5)
      at Context.<anonymous> (src/e2e-tests/governance_tests.ts:667:9)
      at Generator.next (<anonymous>)
      at fulfilled (src/e2e-tests/governance_tests.ts:5:58)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  2) governance tests
       when rotating keys
         key rotation should have worked:
     AssertionError: Unspecified AssertionError
      at /home/circleci/app/packages/celotool/src/e2e-tests/governance_tests.ts:1045:7
      at Generator.next (<anonymous>)
      at /home/circleci/app/packages/celotool/src/e2e-tests/governance_tests.ts:8:71
      at new Promise (<anonymous>)
      at __awaiter (src/e2e-tests/governance_tests.ts:4:12)
      at Context.it (src/e2e-tests/governance_tests.ts:1044:54)`

Related to https://github.com/celo-org/celo-monorepo/issues/2220.

**Comment by jose-compu** [comment]
Mabye 0.0000123% is too sensitive?

bigger than: `delta: BigNumber = new BigNumber(10).pow(12).times(5)`

**Comment by mrsmkl** [comment]
I think the reason they are failing is that some of the validators gets lower score. Not exactly sure why it's happening, perhaps it misses all blocks in an epoch. I think one way to make this test less flaky would be to increase epoch size or block time.
