### ISSUE TITLE
When reminding an invited user from notification, the text message is blank

### ISSUE THREAD

**Issue by nityas** [celo-org/celo-monorepo#3436]
### Expected Behavior

The text message should contain the original invite code along with the reminder message(I believe one used to exist -- can provide copy if not!)

### Current Behavior
When reminding an invited user from notification, the text message is blank

cc @coreycelo

**Comment by tarikbellamine** [comment]
Getting the reminder message to display the original invite code is tied into [issue #2639](https://github.com/celo-org/celo-monorepo/issues/2639)
