### ISSUE TITLE
CLI works incorrectly when used with ledger nano X on New Baklava testnet

### ISSUE THREAD

**Issue by hqueue** [celo-org/celo-monorepo#3448]
### Expected Behavior

`node:accounts` should show accounts specified with `--ledgerAddreses` or `--ledgerCustomAddresses` options.

```
$ celocli config:set --node https://alfajores-forno.celo-testnet.org/
$ celocli node:synced
true

$ celocli node:accounts --useLedger --ledgerAddresses 1
Retrieving derivation Paths [ 0 ]
[ '0xA34EACD65b36AC07bE7CEB981aF6FB53A9C66506' ]

$ celocli node:accounts --useLedger --ledgerCustomAddresses "[0,1,2]"
Retrieving derivation Paths [ 0, 1, 2 ]
[ '0xA34EACD65b36AC07bE7CEB981aF6FB53A9C66506',
  '0xC27559031497BED23d51915435Ac21de2781374E',
  '0xA6A86DdA216301c8B5Bc4b9A3cbf1ede9E25d0b0' ]
```

### Current Behavior
It works correctly on Alfajore testnet.
However it shows weird results for Baklava testnet.

```
$ celocli config:set --node https://baklava-forno.celo-testnet.org
$ celocli node:synced
true
$ celocli node:accounts --useLedger --ledgerAddresses 1
Retrieving derivation Paths [ 0 ]
[ '0xAbA89B8DF5ab1dEB6780A2a35EAAB7094743D529',
  '0xA34EACD65b36AC07bE7CEB981aF6FB53A9C66506' ]

$ celocli node:accounts --useLedger --ledgerCustomAddresses "[0,1,2]"
Retrieving derivation Paths [ 0, 1, 2 ]
[ '0x07c4353b8F836Edec989501b98Ea0F546a49D437',
  '0xA34EACD65b36AC07bE7CEB981aF6FB53A9C66506',
  '0xC27559031497BED23d51915435Ac21de2781374E',
  '0xA6A86DdA216301c8B5Bc4b9A3cbf1ede9E25d0b0' ]
```

It shows one additional random address as the first address.

**Comment by asaj** [comment]
Thanks for flagging! Currently `celocli node:accounts --useLedger` shows both keystore addresses (i.e. from private keys stored on disk) and ledger addresses. The extra address you see on baklava appears to be a keystore account on the forno node.

There's been feedback that showing keystore addresses when `--useLedger` is set is confusing, @gastonponti has sent https://github.com/celo-org/celo-monorepo/pull/3444 which clarifies things a bit
