### ISSUE TITLE
App crashed while scanning QR code

### ISSUE THREAD

**Issue by jmrossy** [celo-org/celo-monorepo#348]
See details here in bug report (ask Rossy)

**Comment by sallyjyl** [comment]
Can't reproduce this. However, I did see "Run out of gas?" error screen couple days ago when I followed the repro steps, but now the error is caught and an error banner is displayed instead (#584).

**Comment by jmrossy** [comment]
@sallyjyl Try on at least more more phone. If you still can't repro the QR scanner crash, then feel free to close

**Comment by sallyjyl** [comment]
Tried with Nokia TA-1045 too, and still unable to reproduce :) Instead the error banner as described above shows up.
