### ISSUE TITLE
Regression in flexibility and security for creating validator signer keys

### ISSUE THREAD

**Issue by zviadm** [celo-org/celo-monorepo#3490]
Just wanted to report a regression that has happened with validator signer keys after the "Release Gold" introduction.

### Expected Behavior

Previously, it was possible to do following:
1) Using automation, without need of any keys:
** Launch a new validator instance
** Create new validator signer address on the instance itself
** Setup everything to prepare node to become new validator

2) Manually, with access to validator locked gold address (i.e. address on hw ledger)
** Authorize new validator signer
** Complete key rotation process to switch to new validator node starting next epoch, WITHOUT needing access to signer address and by using the validator address itself.

This gave us ability to create validator signer keys, that were created completely by automation, tied to a single machine only, and would never be accessed by a human or by anything else, other than "root" user on the validator node itself.

### Current Behavior

With "release gold" changes it is no longer possible to do step 2. 

New commands for validator:register and (or validator:update-bls-public-key), require "--from $CELO_VALIDATOR_SIGNER_ADDRESS"

Which requires $CELO_VALIDATOR_SIGNER_ADDRESS to be unlocked. I believe this is a pretty big regression, because now, validator signer keys need to actually be transferred from validator nodes to accounts nodes too. 

Or, alternatively, celocli would need to run on validator node itself, which is also an unnecessary extra dependency and a risk to run a tool with as complex dependency set as "celocli" on validator nodes. (and in addition to that, i am guessing validator node would need to open up the rpc port for celocli to connect to it on localhost?)

**Comment by asaj** [comment]
Thanks @zviadm for flagging. It's worth noting that registration is only required once, so any future key rotations will not require access to the validator signer

**Comment by zviadm** [comment]
@asaj that is incorrect? rotation requires updating of public bls key?
```
celocli validator:update-bls-public-key --from $CELO_VALIDATOR_SIGNER_ADDRESS \
        --blsKey $CELO_VALIDATOR_SIGNER_BLS_PUBLIC_KEY \
        --blsPop $CELO_VALIDATOR_SIGNER_BLS_SIGNATURE
```

To expand further on this. Right now key rotation is neither easy, nor safe. Key rotation right now is one of the most dangerous operations, and mistakes can be made very easily.

To do key rotation two commands need to be run:
```
	celocli releasegold:authorize --contract $CELO_VALIDATOR_ADDRESS --role validator \
		--signature 0x$CELO_VALIDATOR_SIGNER_SIGNATURE \
		--signer $CELO_VALIDATOR_SIGNER_ADDRESS
	celocli validator:update-bls-public-key --from $CELO_VALIDATOR_SIGNER_ADDRESS \
		--blsKey $CELO_VALIDATOR_SIGNER_BLS_PUBLIC_KEY \
		--blsPop $CELO_VALIDATOR_SIGNER_BLS_SIGNATURE
```

If you run authorize only, and forget bls-public-key update in same epoch, that will cause full epoch unrecoverable downtime!. That is way too dangerous. 


The easiest solution i can think of at least for RG addresses, is to add new command to release gold contract. 

We need "authorizeAndUpdatePublicKey" command, that will both authorize new signer key and update public key in single atomic transaction. That will also solve the problem of needing access to signer key because "authorizeAndUpdatePublicKey" command would be run through beneficiary address directly

**Comment by zviadm** [comment]
oh wow, nvm, it looks like authorize now has "--bls-key" and "--bls-pop" arguments. that actually resolves this problem completely. 

so my suggested fix is already implemented :D 

The only change that might be useful is to add safety check to "authorize" call to make sure bls key and signature are set, because i was able to run authorize without providing those arguments

**Comment by asaj** [comment]
@zviadm thanks again for raising this issue, definitely appreciate your attention to detail and dedication to security 🙏Glad what you were flagging appears to be supported
