### ISSUE TITLE
Blockscout error-ing out with 500s on VALIDATOR_RG address

### ISSUE THREAD

**Issue by zviadm** [celo-org/celo-monorepo#3492]
### Expected Behavior

Not get 500 error

### Current Behavior

Going to blockscout URL for VALIDATOR_RG in baklava:
https://baklava-blockscout.celo-testnet.org/address/0x71f6ef75c6417d66ed2b01620a0335f714c90a56/transactions

causes 500.

Other addresses work fine (like GROUP_RG address)
https://baklava-blockscout.celo-testnet.org/address/0x59186b71b33f4d96ec525e9ee21a8cf989d5ace7/celo

I recently did few key rotations and also setup attestation metadata, so not sure exactly which one is causing blockscout errors.

**Comment by haferman** [comment]
Seeing the same on 16 June with
https://explorer.celo.org/address/0xb33e9e01e561a1da60f7cb42508500e571afb6eb/celo

**Comment by hqueue** [comment]
Same here on 17 June for RG contract for running validator.

https://explorer.celo.org/address/0x588ed7deeff8df7c00ff187c398936b101583ec7/celo

**Comment by mrsmkl** [comment]
Looks like it's working now, for some reason an outdated version of blockscout web server was deployed.
