### ISSUE TITLE
Auth sbat work in dappkit when wallet is not already open

### ISSUE THREAD

**Issue by nityas** [celo-org/celo-monorepo#351]
### Expected Behavior

If wallet is not open yet, we need to pop the modal

### Current Behavior

right now modal doesn’t open, we just open wallet at home screen

**Comment by jmrossy** [comment]
@nityas @nambrot I just tested this and it worked for me! Any more context to share?

**Comment by nambrot** [comment]
The wallet properly opened and brought you to the auth screen? In my experience it works very rarely? My thought was that my hack at https://github.com/celo-org/celo-monorepo/blob/master/packages/mobile/src/app/App.tsx#L62 is probably not what we would actually want to do. Instead it should live somewhere closer to https://github.com/celo-org/celo-monorepo/blob/master/packages/mobile/src/app/saga.ts#L56 ?
