### ISSUE TITLE
Contractkit: cannot use arguments in `sendAndWaitForReceipt()` outside of monorepo

### ISSUE THREAD

**Issue by yerdua** [celo-org/celo-monorepo#3514]
### Expected Behavior

When using contractkit outside of the monorepo, code like this works, without resulting in Typescript errors: 
`tx.sendAndWaitForReceipt({ from: '0x.....' })`

### Current Behavior

This error occurs when trying to build:
`Argument of type '{ from: string; }' is not assignable to parameter of type 'Pick<any, "to" | "value" | "feeCurrency" | "gatewayFeeRecipient" | "gatewayFee" | "from" | "gas" | "gasPrice" | "nonce" | "chainId" | "common" | "chain" | "hardfork">'.
  Type '{ from: string; }' is missing the following properties from type 'Pick<any, "to" | "value" | "feeCurrency" | "gatewayFeeRecipient" | "gatewayFee" | "from" | "gas" | "gasPrice" | "nonce" | "chainId" | "common" | "chain" | "hardfork">': to, value, feeCurrency, gatewayFeeRecipient, and 8 more.`

This seems to be caused by the `Tx` type not existing outside of the monorepo context.

This is what I see when viewing the function documentation within the monorepo. It defines the optional params as `Pick<Tx, ...>`
<img width="262" alt="Screen Shot 2020-04-21 at 14 54 56" src="https://user-images.githubusercontent.com/1222891/79868419-27b04d80-83e0-11ea-87ab-a53f806f5fee.png">

Here's what I see when viewing the same thing in a different repo, where `@celo/contractkit` is a dependency. That same set of params is shown as `Pick<any, ...>`
<img width="361" alt="Screen Shot 2020-04-21 at 14 54 05" src="https://user-images.githubusercontent.com/1222891/79868924-f08e6c00-83e0-11ea-8fb4-eef485886320.png">

@mrsmkl found a workaround for this that involves copying over contractkit's `web3-celo.d.ts` and the normal web3 types, and then pointing tsconfig.json at that new file.

While this workaround _works_, it shows that being able to pass params into `sendAndWaitForReceipt` does not work out of the box.

**Comment by mrsmkl** [comment]
There was also a more simple workaround that I found from celo-monorepo/packages/celotool, it's adding the following to the top of the file that had errors
```
// tslint:disable-next-line:no-reference (Required to make this work w/ ts-node)
/// <reference path="../node_modules/@celo/contractkit/types/web3-celo.d.ts" />
```

**Comment by gastonponti** [comment]
Including the contractkit types in the `tsconfig.json` works for now
```
"include": ["src", "./node_modules/@celo/contractkit/types"]
```

I added this issue #3515, that will cover this error.
For now use the workaround.

I'm closing this issue because will be cover in the other one.
