### ISSUE TITLE
Move common functionality for dappkit into web3 getter

### ISSUE THREAD

**Issue by nityas** [celo-org/celo-monorepo#352]
So I don't fully remember what we referenced here but I think it might reference one of two things:

1) Most people use Truffle to develop smart contracts and we imagine any interesting dapp has to develop their own smart contracts. However, contractkit uses web3 contracts as the preferred interface. Thus we should provide a copy of our tooling that can produce web3 contracts from the ABIs and network address the same way we do.

2) It could just mean that we should provide some base for people to develop on.

I think its 1)

**Comment by nambrot** [comment]
Taking out of sprints for now
