### ISSUE TITLE
Random.sol does not allow access to past randomness from each last epoch block

### ISSUE THREAD

**Issue by nategraf** [celo-org/celo-monorepo#3523]
### Expected Behavior

Random.sol should allow access to the historical randomness from last block of each epoch for use in validator ordering when determining the proposer of a particular block.

### Current Behavior

Random.sol uses a flawed pre-check to determine if the randomness if stored before retrieving it that does not allow access to randomness expect the most recent last epoch block, even though it is stored.

https://github.com/celo-org/celo-monorepo/blob/12046fcd8adbea999fc94509717971eaebc9b4c3/packages/protocol/contracts/identity/Random.sol#L153-L169

As a result, nodes which wish to reconstruct old state cannot use this function as intended to do so.

https://github.com/celo-org/celo-blockchain/blob/15d280e12fb720b7e82d69d2862f7684444fdb67/consensus/istanbul/backend/backend.go#L765-L780

Errors may appear in logs for full nodes and validators that look like this:

```

ERROR[04-20|19:26:56.635] Error in calling the EVM                 funcName=getBlockRandomness                transactionData=0xfc4847260000000000000000000000000000000000000000000000000000000000032a00 err="evm: execution reverted"
ERROR[04-20|19:26:56.635] Error when invoking evm function         err="evm: execution reverted"       funcName=getBlockRandomness                static=true  address=0x2b3A515119695cEec51885c4E40cB5AF43265F3E args=[+207360] gas=2000000 gasLeft=1996896 value=<nil>
ERROR[04-20|19:26:56.635] Error in executing function on registered contract function=getBlockRandomness                registryId=0x02dfe2d0485b616b61db1800f30f4a14b26754b328fa09ba4ec73ee7276766cc err="evm: execution reverted"
WARN [04-20|19:26:56.635] Failed to set randomness for proposer selection block_number=224640 hash=c45e82…c9706c error="evm: execution reverted"
```

**Comment by mrsmkl** [comment]
Are you sure this doesn't remove it?
https://github.com/celo-org/celo-monorepo/blob/12046fcd8adbea999fc94509717971eaebc9b4c3/packages/protocol/contracts/identity/Random.sol#L105

Anyway, we should store more of them so that we get rid of errors.

**Comment by nategraf** [comment]
@mrsmkl you are right, I actually missed that line when creating this issue.

It's not important to the function of validator client to have access to past epoch randomness. The only reason you'd need this is to query past proposer orderings, which is useful in diagnosing errors, in which case it's reasonable that you'd need to run an archive node, which would have access to past epoch randomness in a past EVM state. Given that, it'd be better to keep this contract as is than add all past epochs to the EVM state.

I'm going to close this issue and suggest we address https://github.com/celo-org/celo-blockchain/issues/999 in the blockchain client.
