### ISSUE TITLE
[wallet] Backup/import mnemonic has to also store/ask the language

### ISSUE THREAD

**Issue by gastonponti** [celo-org/celo-monorepo#3554]
### Expected Behavior

For backups/imports, it has to ask/store the language of the mnemonic. This is required to validate that the words are from a valid bip39 dictionary
To take in count:
A user could have a mnemonic in english and have the app in spanish, so it shouldn't be tied to the app. 

### Current Behavior

Works for the default language (english)

**Comment by gnardini** [comment]
Fixed by https://github.com/celo-org/celo-monorepo/pull/5825
