### ISSUE TITLE
celocli identity:test-attestation-service documentation error?

### ISSUE THREAD

**Issue by zviadm** [celo-org/celo-monorepo#3588]
### Expected Behavior

```
celocli identity:test-attestation-service --help
OPTIONS
  --from=0xc1912fEE45d61C87Cc5EA59DaE31190FFFFf232d  (required) Your validator's signer or account address
```

expect when using `--from=<validator signer address>` or `--from=<validator rg address>` command would work

### Current Behavior

celocli identity:test-attestation-service only works with `--from=<attestation signer address>`.

It is definitely at a minimum a documentation bug. But also it would be nice if it was possible to test attestations without needing to have access to `<attestation signer address>` key. Best would be if it would be possible to test it with `<validator rg address>`.

**Comment by zviadm** [comment]
```
celocli identity:test-attestation-service --from 0xa7681958b7f07f4fb8bd5b0e075fb2aa2b021d59 --phoneNumber=XXXXX --message="hello world"
Failed to initialize libusb.
Running Checks:
   ✔  0xa7681958b7f07f4fb8bd5b0e075fb2aa2b021d59 is Signer or registered Account 
   ✔  Account can sign 
Request was not successful
Status: 422
Response: {"success":false,"error":"Invalid signature provided"}
Request successful```

**Comment by mrsmkl** [comment]
If we want to get it work, have to change something around here https://github.com/celo-org/celo-monorepo/blob/master/packages/attestation-service/src/requestHandlers/test_attestation.ts#L25

**Comment by nambrot** [comment]
I think that is a great suggestion!
