### ISSUE TITLE
Separate management and block signing purposes of the validator signer key 

### ISSUE THREAD

**Issue by nategraf** [celo-org/celo-monorepo#3590]
Celo Accounts can currently split their permissions into three signing addresses: validator, voter, and attester keys. The validator key can perform a number of actions including signing blocks to participate in the consensus layer protocol, and can register and manage validator information in the smart contract layer.

These functions, of block signing and on-chain validator management must currently be managed by the same address, but a number of benefits would be gained by allowing these responsibilities to be split.
1. On-chain actions could be managed by a smart contract, such as a multisig contract, instead of requiring the possession of a private key for the address due to the requirement of block signing.
2. The block signing key could be generated on the validator machine and never moved or otherwise accessed.

**Comment by gbunea** [comment]
While there is room to improve keys management and keys usage I would be very careful in moving ahead with point 1. Private keys are a more secure approach than any form of smart contracts. And to sustain my point I am just reminding about the multiple parity multisig bugs discovered along the way

**Comment by nambrot** [comment]
Once CIP10 makes it through, this should become easier to do

**Comment by nambrot** [comment]
@pranaymohan Would be curious how important you see this ticket?
