### ISSUE TITLE
ERR 404 on running npm install

### ISSUE THREAD

**Issue by NickHung1982** [celo-org/celo-monorepo#3592]
Hi, here is running error 404 message, it seems link is incorrect.

NICK:mobile XXXX$ npm install
npm WARN deprecated @types/graphql@14.5.0: This is a stub types definition. graphql provides its own type definitions, so you do not need this installed.
npm WARN deprecated @types/react-native-fs@2.13.0: This is a stub types definition. react-native-fs provides its own type definitions, so you do not need this installed.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated deep-assign@3.0.0: Check out `lodash.merge` or `merge-options` instead.
npm WARN deprecated @types/bignumber.js@5.0.0: This is a stub types definition for bignumber.js (https://github.com/MikeMcl/bignumber.js/). bignumber.js provides its own type definitions, so you don't need @types/bignumber.js installed!
npm WARN deprecated json3@3.3.0: Please use the native JSON object instead of JSON 3
npm WARN deprecated core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated mkdirp-promise@5.0.1: This package is broken and no longer maintained. 'mkdirp' itself supports promises now, please switch to that.
npm WARN deprecated fsevents@1.2.12: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
### npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@celo%2freact-components - Not found
npm ERR! 404 
npm ERR! 404  '@celo/react-components@1.0.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'mobile'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/XXXX/.npm/_logs/2020-04-24T19_54_48_976Z-debug.log

**Comment by cmcewen** [comment]
hi @NickHung1982 - we require the use of yarn in order to develop in the monorepo. please follow the setup instructions here: https://github.com/celo-org/celo-monorepo/blob/master/SETUP.md
