### ISSUE TITLE
iOS: ‘Could not connect to firebase’ error is shown for fraction of seconds on ‘Invitation code’ page while processing with invitation code.

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#3622]
**Frequency:** 100%
**iOS App version:** iOS Testflight build : v1.7.1 (28)
**Repro on iOS device:** iPhone 11 Pro (13.3)

**Repro Steps:** 
1) Launch the app and Enter the phone number
2) Tap on ‘Continue’ button and Add security pin 
3) Navigate to ‘Invitation Code’ page and Enter invitation code 
4) Make sure process gets start and Observe while processing 

**Current Behavior:** ‘Could not connect to firebase’ error is shown for fracation of seconds

**Expected Behavior:** ‘Could not connect to firebase’ error should be not be shown 

**Investigation:** 
1) Issue does not reproduce in Android 
2) Randomly, Same error is shown when user navigating into the app 

**Attachment:** [iOS_Couldn’t connect to Firebase error is shown](https://drive.google.com/file/d/10A0fqnkMTde73j3IZpMjDgDs39NU11tk/view?usp=sharing) (Observe the issue between 0:32 to 0:37 secs)

**Comment by Lss-Ankit** [comment]
Hi @jeanregisser , @annakaz @nityas Verified with Android Valora Mainnet build v1.0.0 (16) and found that 
iOS: ‘Could not connect to firebase’ error is shown for fraction of seconds on home screen after sign up with new account and sign in with account key. 

**Note:** Issue does not repro on IOS test flight build v1.0.0 (15) 
**Attachment:** 

![Android_FirebaseIssue](https://user-images.githubusercontent.com/55572027/91400444-835a6f80-e7f4-11ea-9fb1-b5b9cc6b358a.png)

**Comment by jeanregisser** [comment]
Thanks, could you try with iOS build v1.0.1 (17) when you get a chance?

**Comment by annakaz** [comment]
It seems like this is happening intermittently throughout the app, unrelated to invite code redemption. @Lss-Ankit can you confirm whether this consistently happens during invite redemption, or only sometimes?

**Comment by Lss-Ankit** [comment]
@annakaz , @jeanregisser Issue is reproduced when user navigate to Home tab after sign up with new account or sign in with existing account using account key. also some time i have observed issue after cold launch the app. 

currently issue is not observed during invite redemption.

However i have verified issue again on Android Valora Mainnet build v1.0.0 (16), Test Flight build Valora app build  v1.0.1 (17) and not observe error message after sign up / sign in or cold launch the app. 
Verified on:  Google Pixel Xl (8.1) , iPhone 7+ (13.3.1)

hence closing ticket. 
Thanks!

**Comment by Lss-Ankit** [comment]
Hi @annakaz , @jeanregisser I have verified this issue using latest Android Internal Build v1.30(1004294316) on lower end devices and observed that issue is still reproduced.
User get 'Could not connect to Firebase' error massage when user login with new account by tapping on 'Create new account' option after tapping on 'Don't have an invite code' button.
**Repro on devices:** Samsung Galaxy A5(5.0.2) , 
**Frequency:** 80%
**Attachment:** [CouldNotConnectToFirebase.mp4](https://drive.google.com/file/d/1Y8qQX1fNex4UTxQk_zQYjtCWBpP73RDl/view?usp=sharing)

**Comment by ValoraQA** [comment]
Hi @jeanregisser I have verified this issue using latest Android Internal Build v1.15.2  on lower end devices and and found issue is fixed so, we are closing this ticket.
**Devices:** Samsung Galaxy A5(5.0.2)
