### ISSUE TITLE
Android & iOS: ‘Confirming..’ text is shown for current and previous transaction on ‘Wallet’ and ‘Gold’ tab when first transaction is in confirming state and user scroll up-down the page.

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#3624]
**Frequency:** 50%
**iOS App version:** iOS Testflight build : v1.7.1 (28)
**Android App version:** Android Celo Alfa build : v1.7.1
**Repro on iOS device:** iPhone 11 Pro (13.3)
**Repro on Android device:** Samsung Galaxy J7 Prime (6.0.1)
**Testing Account:** 3155641283 /backup Key

**Repro Steps:** 
1) Launch the app and Login with test account
2) Proceed with buy/sell gold and make sure ‘confirming..’ text is shown
3) Scroll up & down the page and Observe 

**Current Behavior:** ‘Confirming..’ text is shown for current and previous transaction on ‘Wallet’ and ‘Gold’ tab

**Expected Behavior:** ‘Confirming..’ text should be shown for current transaction only

**Attachment:** [iOS_Confimring text is shown](https://drive.google.com/file/d/1gfkg9o8gD2UrzpO0vqCWmYeyrFrN7X4l/view?usp=sharing) (Observe the issue between 0:02 to 0:14 secs)

**Comment by jmrossy** [comment]
Should be fixed by #3887
