### ISSUE TITLE
Add ability to choose between SMS and WhatsApp for escrow reminders

### ISSUE THREAD

**Issue by tarikbellamine** [celo-org/celo-monorepo#3636]
### Expected Behavior

When a user gets a notification to remind or reclaim an escrowed payment, the reminder option should prompt the user to choose between reminding their invitee via SMS or WhatsApp, then open and populate a message on their chosen platform with the relevant data.

### Current Behavior

Currently, the reminder option automatically opens the default SMS messaging app with a populated message (no opportunity to choose WhatsApp).

**Comment by nityas** [comment]
closing, invite code related
