### ISSUE TITLE
Instrument wallet performance metrics

### ISSUE THREAD

**Issue by cmcewen** [celo-org/celo-monorepo#3653]

**Comment by jose-compu** [comment]
1. How many Txs are failing?
2. What is the average time of confirmation/receipt received?

**Comment by jose-compu** [comment]
3. What is the Start time?
4. What is the Sync time?

**Comment by jose-compu** [comment]
5. How much time to get Peers?

**Comment by jose-compu** [comment]
Time To Initialize = tti

https://github.com/celo-org/celo-monorepo/blob/master/packages/mobile/src/app/App.tsx#L56

`CeloAnalytics.track(DefaultEventNames.appLoadTTIInMilliseconds, { tti }, true)`

**Comment by tarikbellamine** [comment]
Address by #4599
