### ISSUE TITLE
Wallet Analytics: Account Key

### ISSUE THREAD

**Issue by nityas** [celo-org/celo-monorepo#3658]
Parent Epic: #3641 
### Expected Behavior

https://docs.google.com/document/d/1OGNJBijiWp7bWc2I0p8yyJ72EMCj9pNRT1VWxJJu5JY/edit#heading=h.crz3fi6kkwp8

### Current Behavior

What is the current behavior?

**Comment by aaronmgdr** [comment]
- [x] backup_start: ‘set up now’ button click
- [x] backup_snooze: ‘wait one hour’ button click

- [x] backup_setup_info: info button is clicked
- [x] backup_setup_toggle_complete: “I have written down my key” is toggled to enabled state
- [x] backup_setup_toggle_incomplete: “I have written down my key” is toggled to disabled state

- [x] backup_setup_cancel: cancel button is clicked
	params: name of screen
- [x] backup_setup_cancel_confirm: action is taken on cancel modal
	params: option selected
- [ ] backup_setup_screenshot_warning: ‘okay’ button click
	Q: possible to log an event when the modal is launched?
- [x] backup_quiz_submit:
	param: number of deletes, time from first input word to submit
- [x]  backup_quiz_success:
	param: time from submit to validate
- [x]  backup_quiz_incorrect:
	param: time from submit to validate

- [x]  backup_quiz_cancel: cancel button is clicked
	param: name of screen
- [x]  backup_quiz_cancel_confirm: action is taken on cancel modal
	param: option selected
- [ ]  backup_quiz_screenshot_warning: ‘okay’ button click
	Q: possible to log an event when the modal is launched?

- [ ] backup_error: error in backup flow
	params: error identifier(or message)
- [x] backup_educate_1_next: next button on 1st edu screen
- [x] backup_educate_2_next: next button on 2nd edu screen
- [x] backup_educate_3_next: next button on 3rd edu screen
- [x] backup_educate_4_next: next button on 4th edu screen

- [x] backup_educate_1_cancel: cancel button on 1st edu screen
- [x] backup_educate_2_cancel: cancel button on 2nd edu screen
- [x] backup_educate_3_cancel: cancel button on 3rd edu screen
- [x] backup_educate_4_cancel: cancel button on 4th edu screen

**Comment by aaronmgdr** [comment]
TODO: tracking of error in analytics.

add an error boundary? 

add lots of try catchs? 

both?

neither?
