### ISSUE TITLE
Developers SBAT to use contractkit/utils packages

### ISSUE THREAD

**Issue by nambrot** [celo-org/celo-monorepo#366]
### Expected Behavior

SDK should be installable and usable from NPM

### Current Behavior

When installing the packages, there are various errors around postinstall, utils not actually including the libs files etc.

**Comment by mcortesi** [comment]
IMO, we are misusing the `postinstall` script.

By definition:
```
postinstall: Run AFTER the package is installed.
```

So, it runs whenever we do `yarn add @celo/contractkit`; and that's not the desired behaviour.

We currently use postinstall to download and genereate ts files for contract. This is a `prebuild` step.
