### ISSUE TITLE
iOS: ‘NaN’ text is shown with ‘Subtotal’ or ‘Celo Gold’ on ‘Buy GLD’ screen when user has 0 dollar & 0 gold in Wallet

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#3679]
**Frequency:** 100%
**iOS App version:** iOS Testflight build : v1.7.1 (28)
**Repro on iOS device:** iPhone 11 Pro (13.3)
**Testing account:** 7864900848/Backup key

**Prerequisite:** User should have 0 dollar & 0 gold

**Repro Steps:** 
1) Launch the app and Login with test account
2) Navigate to ‘Gold’ tab and Make sure only ‘Buy’ button is shown 
3) Tap on ‘Buy’ button and Observe 

**Current Behavior:** ‘NaN’ text is shown with ‘Subtotal’ or ‘Celo Gold’ on ‘Buy GLD’ screen 

**Expected Behavior:** Respective gold amount should be shown on ‘Bug GLD’ screen 

**Investigation:** Issue does not reproduce in Android 

**Attachment:** [iOS_NaN is shown at subtotal](https://drive.google.com/file/d/1GhD1AVk7-C3xZFybw6c_0Mf9MnBD-eSd/view?usp=sharing) (Observe the issue between 0:10 to 0:13 secs)

**Comment by tarikbellamine** [comment]
@i1skn has this been closed with the Gold redesign?

**Comment by Lss-Ankit** [comment]
Verified with IOS Test flight Celo interation build v1.9.1 (41)  and observed issue is still reproduced
**Attachment:** [NAn&InfinityIssue.mp4](https://drive.google.com/file/d/1ZLnJYEt4JQdWNLpsdxtANa7J4CsYg1dO/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
Verified with IOS Test flight Celo interation build v1.9.1 (41) and observed issue is Fixed
**Device Used:** iPhone 6(12.4.7)

**Comment by Lss-Ankit** [comment]
Verified with latest IOS test flight build v1.9.1(41) and observed that issue is still Repro
- ‘NaN’ text is shown with ‘Subtotal’ or ‘Celo Gold’ on ‘Buy GLD’ screen when user has 0 dollar & 0 gold in Wallet
- **Device Used:** iPhone 6(12.47)
- **Attachment:** [Nan&InfinityIssue.MP4](https://drive.google.com/file/d/19iXNlH75hMZMDst4uDowMiEdoBExIyiL/view?usp=sharing)

**Comment by i1skn** [comment]
@Lss-Ankit `v1.9.1(41)` is 11 days old, so we will see the fix only in the next build. Also you can check recent mainnet build `Valora 1.0.0(5)`, which has this fix already.

**Comment by Lss-Ankit** [comment]
Hi @i1skn thanks for the update!. 
In test flight currenly, i can see only Celo integraion build v1.9.1(41), also i have checked in App store celo application is not shown it may be alfajores network reset. 
Can you please do the needful so i can get the latest Valora app v1.0.0(5). 
Thanks!

**Comment by Lss-Ankit** [comment]
Verified with latest IOS test flight build v1.0.0(4) and observed that issue is still Repro
- ‘NaN’ text is shown with ‘Subtotal’ or ‘Celo Gold’ on ‘Buy GLD’ screen when user has 0 dollar & 0 gold in Wallet
- **Device Used:** iPhone 11(14.0)
![InfinityIssue](https://user-images.githubusercontent.com/55572027/88621264-a1319900-d0bd-11ea-8574-dc51d738789a.png)
![NANissue](https://user-images.githubusercontent.com/55572027/88621268-a262c600-d0bd-11ea-88cf-bfd395c57a3c.png)

**Comment by Lss-Ankit** [comment]
Verified with latest IOS test flight Valora build v1.0.0(6) and observed that issue is Fixed
- **Device Used:** iPhone 6(12.4.7)
