### ISSUE TITLE
BlockExplorer shows all vote history and doesn't distinguish between current vs past

### ISSUE THREAD

**Issue by zviadm** [celo-org/celo-monorepo#3684]
### Expected Behavior

Go here and see current votes (and history of votes separately):
https://explorer.celo.org/address/0x7c75b0b81a54359e9dccda9cb663ca2e3de6b710/celo

### Current Behavior

Right now it shows both current and historical votes in same list so it makes it impossible to know which are active vs which are past:

```
Group voters
10,000 cGLD: 0x2062–162005
10,000 cGLD: 0x6ac7–71c213
10,000 cGLD: 0xcea0–70b583
10,000 cGLD: 0xab98–e5739b
1,500,000 cGLD: 0xef28–110647
27,998 cGLD: 0x3703–5cff26
30,000 cGLD: 0x7c75–e6b710
Groups voted
30,000 cGLD: 0x4d5a–38dadc
30,000 cGLD: 0x7c75–e6b710
```

0x7c75–e6b710 -> voting 30k for -> 0x7c75–e6b710 is no longer active. It is just historical voting.

**Comment by mrsmkl** [comment]
One problem is that the revoke vote event was split into two, and so blockscout didn't detect them. Going to fix that soon.
