### ISSUE TITLE
Deploy @celo/client package update 

### ISSUE THREAD

**Issue by jmrossy** [celo-org/celo-monorepo#369]
### Expected Behavior

Next version with fixes for 64-bit on arm and bls changes

### Current Behavior

@celo/client v.0.0.80

**Comment by jmrossy** [comment]
@cmcewen @kobigurk

**Comment by asaj** [comment]
Please also consider rename to be consistent with celo-blockchain?

**Comment by ashishb** [comment]
Not required once https://github.com/celo-org/celo-blockchain/pull/384 is merged.
