### ISSUE TITLE
User SNBAT paste the same verification code twice

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-monorepo#37]
### Expected Behavior

An error message that prevents the user from pasting the same verification code twice.

### Current Behavior

The user can paste the same code twice, which leads to failing verification.

**Comment by jmrossy** [comment]
This can happen in the time between the user clicks paste and the time we process and ingest the code. With the new identity changes, we now validate the code via a contract call.
The solution is to disable the button temporarily while we process the code and accept/reject it.
