### ISSUE TITLE
[PGPNP] User errors are reported as service failures

### ISSUE THREAD

**Issue by codyborn** [celo-org/celo-monorepo#3722]
### Expected Behavior

User input related failures should be logged as a user error and not create an alert.

### Current Behavior

Passing in an invalid blinded phone number causes the service to log a failure:
https://portal.victorops.com/ui/celo/incident/4780/details/
> Threshold exceeded for BLS signature computation errors

Example request:
curl -v "https://us-central1-celo-phone-number-privacy-stg.cloudfunctions.net/getBlindedSalt" -H "Content-Type:application/json" -d '{"blindedQueryPhoneNumber": "xfVo/qxqTXWE8AXzev8KcqJ2CG8sMqNQfn/0X2ch7dKGJyBGG8YjhFyNSmX1e1cB9n4ARdq6kYr0vZTAebx1Nudl3zR9ij0aIJY5wzhsR89uLPj/31H0Ks4FMf42oD4A/5ny0+AA1As0oUFvTpVr99Uk4+GxbRjX/iHgTa2qkM15ih/3Qot/tw/vt9LmDZAByogwM3EAHZFC+BLyYfgt8Tws/2jwiie61wET0Ms/JLOVZjiTZafwJJ74Wqlk/IgAAA==", "account":"0xAd69caB2613Bfc25a4b2ecFa20ed66a9A8e8eA28", "hashedPhoneNumber":"+15555555555"}'

**Comment by jmrossy** [comment]
This was fixed when I split apart the warnings from the errors in the signer and combiner Error Message enum
