### ISSUE TITLE
Foldout menu not clickable in small display view in blockscout

### ISSUE THREAD

**Issue by H34D** [celo-org/celo-monorepo#3723]
### Expected Behavior

When blockscout is in responsive / mobile / small display view it should be possible to switch between celo info / transactions and other information

### Current Behavior

The pull down menu is clickable but will always reload the page instead of folding out as seen here: https://explorer.celo.org/address/0x2fd49e97262d505fd76bb6e0e06ec10e1fd54589/celo 

<img width="423" alt="Screenshot 2020-05-05 at 09 41 58" src="https://user-images.githubusercontent.com/13647606/81044480-b6c76600-8eb4-11ea-9b9a-58cebcbfbfef.png">

**Comment by mrsmkl** [comment]
Looks like this has something to do with generating the assets, I just removed the static files locally and regenerated, and it started to work here...

**Comment by H34D** [comment]
fixed with the current release of blockscout thanks @mrsmkl
