### ISSUE TITLE
Celo Stats inconsistent display of data / dropping validator names

### ISSUE THREAD

**Issue by aaronmboyd** [celo-org/celo-monorepo#3763]
### Expected Behavior

Consistent validator listing showing _both_ validator and validator group names.

### Current Behavior

Validator names are consistently disappearing for a subset of the validator list on https://stats.celo.org

Bouncing proxy and/or validator appears to 'refresh' Celo stats and validator name and group reappear. 

While this may appear a cosmetic issue, branding and visibility on the official Celo stat site is important and not resolving this issue unfairly affects the organisations that are consistently affected.

**Some questions:**
1. Do the validator and proxy names have to be the same when reporting to ethstats?
2. Do you even need to login to ethstats on the validator?
3. Are there any server logs on Celo stats showing dropped connections to certain validators?
4. What further information would you need from the validator community to pin this down?

**Selected anecdotes from forum:**

peterldowns: `WARN [05-07|07:26:05.511] Failed to decode stats server message    err="websocket: close 1006 (abnormal closure): unexpected EOF"`

> There was a little talk in this channel at some point about Celo Stats and names disappearing. We have been afflicted with similar issues, and in one case the validator just fell off the board (even though all was well). One possible issue for us is that on reboots of the proxy, the enode id was changing. This certainly has an effect on the validator's ability to get blocks, but I think it was also causing issues in Celo Stats. We have stabilized our enode ids for proxies, rebooted, and the stats seem to be okay now.

BisonD: 

> following up on this, I'm still seeing my validator/proxy drop off the rc1 stats page from time to time. restarting my proxy seems to fix it; my proxy has a consistent enode across restarts

> Another data point on this is the proxy continually says Stats login failed                       err="login timed out" even tho its reporting. Perhaps the validator is properly reporting (since data is showing up)

> Cross post here. My enode id hypothesis turned out to not be a factor in Celo stats issue.  Our proxy starts up, says “Stats login failed” a number of times but then seems to start reporting correctly. All stats show up correctly for an hour or so and then they just stop.

> Update for Celo stats issue. Stable enode id did not solve it. Names are cleared again from mainnet and baklava Celo stats pages. Our genesis validator no longer appears on the board

Thylacine:

> `WARN [04-27|09:52:09.967] Failed to decode stats server message    err="websocket: close 1006 (abnormal closure): unexpected EOF`" this message on my proxy, and now my name has again disappeared from celostats. Is this related?

gunray:

> WARN [04-25|15:20:45.649] Stats server pinger seems to have died 

mbay2002:

> We're not showing on stats.celo.org
> We do have  --ethstats=<YOUR-VALIDATOR-NAME>@stats-server.celo.org
> on both validator and proxy, account unlocked on proxy
> Worked on baklava. What's the magic incantation? :woozy_face:

Wade:

> Another validator found it was a problem with two differing addresses between proxy and validator. --ethstats=ThePassiveTrust@stats-server.celo.org has to be the same for both proxy and validator.
> 
> I just restarted both with this but it didnt work for me.

**Comment by timmoreton** [comment]
Thanks for raising this! We will try and get to the bottom of it

**Comment by H34D** [comment]
> We're not showing on stats.celo.org
> We do have --ethstats=@stats-server.celo.org
> on both validator and proxy, account unlocked on proxy
> Worked on baklava. What's the magic incantation?

it is very important to put some name before the @ otherwise the validator will show up with empty name on celostats which makes it look like it is offline

Edit: as a workaround it is possible to assign the validator or validator signer address as the name.

**Comment by H34D** [comment]
> `WARN [04-27|09:52:09.967] Failed to decode stats server message err="websocket: close 1006 (abnormal closure): unexpected EOF`" this message on my proxy, and now my name has again disappeared from celostats. Is this related?

I recently updated the websocket module inside celo blockchain. This can solve the issue but i am not sure because it cannot be reproduced locally. https://github.com/celo-org/celo-blockchain/pull/1033
