### ISSUE TITLE
Devs SBAT know which contracts are close to bytecode limit

### ISSUE THREAD

**Issue by m-chrzan** [celo-org/celo-monorepo#379]
This will be useful for #378.

**Comment by yorhodes** [comment]
We can use a slightly modified version of [this script](../blob/master/packages/protocol/scripts/python/checkBytecodeLen.py) and do a simple percentage calculation

With github actions it might be possible to raise this output in a nice UI on PRs

**Comment by m-chrzan** [comment]
Fixed by https://github.com/celo-org/celo-blockchain/pull/421
