### ISSUE TITLE
Devs SBAT build app for 64 bit and run contracts correctly

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-monorepo#38]
### Expected Behavior

Wallet can run all contract calls on 64 bit

### Current Behavior

The verification flow works fine on the emulator, but did not work on a physical device (Google Pixel 2 XL), and it failed when receiving a code - specifically at `validateAttestationCode` (https://github.com/celo-org/celo-monorepo/blob/master/packages/mobile/src/identity/verification.ts#L336), where it returned the null address. Nam ran the exact same contract call with the exact same inputs on one of the validators, and it returned a non-null address.

I was able to fix this issue by disabling 64 bit builds, running on my device and the contract call succeeded. We need to fix this by August 1st (https://android-developers.googleblog.com/2019/01/get-your-apps-ready-for-64-bit.html)

**Comment by ashishb** [comment]
Our laptops are 64-bit X86 and this code works on them as well. So, I believe this issue is specific to 64-bit ARM architecture.
