### ISSUE TITLE
[Wallet] Users SBAT know when each Cash In provider was last used

### ISSUE THREAD

**Issue by annakaz** [celo-org/celo-monorepo#3847]
### Expected Behavior

Users can see the most recent date they used a cash in provider, mocks here: 
https://www.figma.com/file/zt7aTQ5wuXycIwxq5oAmF9/Wallet--Refresh?node-id=3136%3A0

<img width="305" alt="Screen Shot 2020-05-20 at 8 41 55 AM" src="https://user-images.githubusercontent.com/16907027/82466872-c8dd0300-9a75-11ea-92b1-1272281a3b24.png">

### Current Behavior

No tracking of when a Cash In provider was last used

**Comment by tarikbellamine** [comment]
This is not present in most recent CICO designs
