### ISSUE TITLE
[Blockchain API] Devs SBAT easily label known entities in transaction feed

### ISSUE THREAD

**Issue by annakaz** [celo-org/celo-monorepo#3849]
### Expected Behavior

Simple mapping for outside devs to add themselves to the wallet transaction feed, allowing them to choose a name and icon

Would be nice to require proof of possession, but this can be left until later as adding an address will still require a PR approval

### Current Behavior

It is not obvious to an outside developer how to get an address listed in the wallet tx feed. Known addresses like the faucet are defined in a .env file

**Comment by ole-nov** [comment]
it is already supported
