### ISSUE TITLE
Explorer is displaying invalid "Groups voted" data

### ISSUE THREAD

**Issue by kphed** [celo-org/celo-monorepo#3859]
### Expected Behavior

Group voted for account `0x8b57c57fd37f748aa3302e72a3b201e23d2b3c22`:
- 626,125.13 votes for group `0xAF2b000bAed202fA7de0d9DCeB6F6612De348011`

### Current Behavior

Group voted for account `0x8b57c57fd37f748aa3302e72a3b201e23d2b3c22`:
- 626,024.883 votes for group `0xAF2b000bAed202fA7de0d9DCeB6F6612De348011`
- 626,024.883 votes for group `0x8493BD3De67AC341D4cC11531f96a1A2cdBf29aD`. 

According to the owner of the 2nd group (`0x849...`), those votes were previously revoked but is still showing up.

**Comment by carterqw2** [comment]
It displays correct data right now.
