### ISSUE TITLE
‘cUSD’ balance is not updated automatically after adding fund from Add fund option from setting

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#3861]
**Frequency:** 100%
** App version:** 1.7.1 (101178676)
**Repro on device:** Google pixel XL (8.1)
**Tested Account:** 272 381 9637/[Back up key ](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit#gid=0)
**Repro Steps:** 
1) Launch the app and Login with test account
2) Tap on Cog icon. 
3) Tap on Add funds. 
4) Enter an amount and tap on Buy Now button 
5) Check the Term check box and tap on Buy Now button
6) make Funds are added 
7) Navigate to Wallet tab 
8) Observe that the CUSD balance is not updated automatically. 

**Current Behavior:** CUSD balance is not updated automatically 
**Expected Behavior:** CUSD balance should updated automatically 
**Investigation:**After refreshing the Wallet tab CUSD balance is shown update. 
**Attachment:** [CUSDupdateIssue.mp4](https://drive.google.com/file/d/1VdylQbLHOJdQokVSS5ATWbcrOnVBVV62/view?usp=sharing) (Bug observe at 45 Sec)

**Comment by tarikbellamine** [comment]
I believe this is addressed

**Comment by Lss-Ankit** [comment]
Hi @tarikbellamine I have verified this issue using latest Android internal build v1.3.0(1004294316) & Test Flight Build v1.3.0(27). and found issue is fixed
Repro on devices: Vivo V11 pro (10),iPhone 6+(12.4.5)
