### ISSUE TITLE
Validator explorer group uptime issues

### ISSUE THREAD

**Issue by mrsmkl** [celo-org/celo-monorepo#3868]
### Expected Behavior

A useful and intuitive behaviour.

### Current Behavior

One problem is that affialiated and unelected non-elected validators are included in calculation.

Another issue is that it is confusing that new validators have low uptime.

Some feedback:

zviad | wotrust.us Yesterday at 8:05 PM
it would probably be most accurate if score is calculated by only considering elected validators from "election:current", or "election:run", taking even fully accepted members would still be incorrect if some of the validators arent getting elected.

zviad | WOTrust | celovote.com Today at 12:28 AM
one suggestion would be to completely remove value from group uptime column, and only keep "per validator" uptime-s, that you show only if you expand the group row. The group's average uptime isn't really relevant for anything, and because new validators start with 0% uptime it only creates confusion unless you are really familiar with all the different scores that exist in the system.

Peter [ChainLayer.io] Today at 12:29 AM
Or just the (average) last epoch uptime of the validators in the group since that is what the voter rewards are based on anyway if im not mistaking

**Comment by marekolszewski** [comment]
Since the uptime column is not accurate, can we hide it temporarily? CC @aaronmgdr

**Comment by aaronmgdr** [comment]
sure Ill do a quick hide

**Comment by Fouda-volt** [comment]
1. There is no explanation for all the metrics that are shown in simple words for newcomers. An info pop-up can be really useful.
2. The percentages listed in the three votes columns are very confusing and I feel don't give any insight about the validator 

![image](https://user-images.githubusercontent.com/62042003/82624543-d8ad3200-9bb0-11ea-8c74-b708a1186d73.png)

**Comment by cfl0ws** [comment]
Can someone please point me to the uptime calculation?

**Comment by cfl0ws** [comment]
> 1. There is no explanation for all the metrics that are shown in simple words for newcomers. An info pop-up can be really useful.
> 2. The percentages listed in the three votes columns are very confusing and I feel don't give any insight about the validator
> 
> ![image](https://user-images.githubusercontent.com/62042003/82624543-d8ad3200-9bb0-11ea-8c74-b708a1186d73.png)

I agree that tooltips or something like that explaining each metric would be very helpful.

**Comment by zviadm** [comment]
To give more suggestions, first step would be identifying who the validators page is for. I can see two distinct groups that would care about validator and groups but in very different ways:
* Celo gold holders.
* Group and validator owners.

Celo Gold holders mostly care about:
* Group information and credentials
* Estimated or somehow approximated returns that they should expect to get if they were to vote for a group. Best would be if this is represented in easy to understand terms, like 6% annual returns, or X% monthly returns. 

Group and validator owners care about:
* Group information and credentials
* Group's commission split, current votes and current place in elections
* Individual validator information and credentials
* Validator's uptime history, cumulative 'validator uptime score' and other metrics that show overall validator stability and current potential for epoch rewards
* In ideal scenario, there could even be some sort of match making portal, to make it easier for group and validator owners to connect with each other. 


I think trying to service both of these use-cases with same page is going to be difficult and cause confusion for both sides. Having separate space for these different use cases would make it much easier to provide accurate useful information for each.

**Comment by aaronmgdr** [comment]
> Can someone please point me to the uptime calculation?

we temporarily removed as its calculation was creating confusion

**Comment by zviadm** [comment]
btw @aaronmgdr @mrsmkl , there is i think similar confusing "Average validator score", that is displayed in: "celocli rewards:show --voter" command.
```
$ celocli rewards:show --voter=0x6ac7E3D0BDeb78ddcF3d9b15208B50C08271C213
Voter rewards:
Address                                    Addresspayment                           Group                                      Averagevalidatorscore Epochnumber 
0x6ac7E3D0BDeb78ddcF3d9b15208B50C08271C213 1601575033783157916.65463219078342769128 0x7C75B0B81A54359E9dCCDa9cb663ca2e3De6B710 0.878423345407        30        
```

The issue here is that, this is showing "average cumulative validator uptime score", but that is irrelevant for voter rewards. It should show average validator uptime score for that single epoch. Which in this case would have been "1.0".
