### ISSUE TITLE
 “Gold Activity” page is shown for a while before asking for a security PIN while buying / selling gold from the “Gold” tab.

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#3886]
**Frequency:** 100%
** Repro App version:** Android build v1.8.0 (104994308)
**Repro on device:** Google pixel XL (8.1),  Samsung Galaxy A50 (9.0),
**Tested Account:** 318 232 6248 / [Backup key ](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit#gid=0)

**Repro Steps:** 
1) Launch app and login with tested account
2) Navigate to Gold tab. 
3) tap on Buy button. 
4) Enter an amount and tap on the Review button. 
5) Tap on Buy # Gold button. 
6) Observe Gold Activity page is shown before asking for Security PIN

**Current Behavior:** Gold Activity page is shown before asking for Security PIN
**Expected Behavior:** Security PIN should ask without opening Gold Activity page. 
**Attachment:** [GoldPageIsShownBeforePIN.mp4](https://drive.google.com/file/d/1h9gbWBXeu7fA7OWOOsPt3LLYV7BWWsbf/view?usp=sharing) (Bug observe at 13 sec)

**Comment by tarikbellamine** [comment]
This has been addressed

**Comment by Lss-Ankit** [comment]
@tarikbellamine I have verified this issue using latest build Android internal build v1.1.0 (1004294311) and Test flight build v1.1.0 (23) and found issue is fixed
"Enter Security Pin page is shown while buying/ Selling gold 
**Devices:** iPhone 11 (14 iOS) , Samsung Galaxy A70(9.0)
