### ISSUE TITLE
Blockscout and celocli signed-blocks do not match signers list

### ISSUE THREAD

**Issue by aaronmboyd** [celo-org/celo-monorepo#3889]
### Expected Behavior

Blockscout and `celocli validator:signed-blocks` should report the exact same signers for any particular block.

### Current Behavior

Blockscout doesn't report the same signatories for any given block that the `celocli` does. May have a 0 or 1 based index issue when determining the signers.

### Example

Consider block **794402**: https://baklava-blockscout.celo-testnet.org/blocks/794402/signers
For the signer `0x8c517B3BaB0e2d65D5cdF3750CA360ff05B3fc1D`, Blockscout reports downtime.

1. Using `celocli validator:signed-blocks --signer 0x8c517B3BaB0e2d65D5cdF3750CA360ff05B3fc1D --at-block 794410 --lookback 10 --width 10`
Result:
` 794400 ✘.........`

**This implies the missed block should be 794401, not 794402**

2. A simplified JS version using `istanbul.parseBlockExtraData`;
```
const contractkit = require("@celo/contractkit");
const istanbul = require("@celo/utils/lib/istanbul");

const signedParent = async (signer, blockNumber) => {

	const kit = contractkit.newKit("https://baklava-forno.celo-testnet.org");
	const block = await kit.web3.eth.getBlock(blockNumber);
	const election = await kit.contracts.getElection();
	const electedSigners = await election.getValidatorSigners(blockNumber);
	
	const isSigner = (element) => element === signer;

	const signerIndex = electedSigners.findIndex(isSigner);
	const bitmap = istanbul.parseBlockExtraData(block.extraData).parentAggregatedSeal.bitmap;

	const signed = istanbul.bitIsSet(bitmap, signerIndex);
	console.log(`Signer ${signer} signed blockNumber ${blockNumber} (${block.hash}) == ${signed}`);
	return signed;
}

const run = async () => {

	const signer = "0x8c517B3BaB0e2d65D5cdF3750CA360ff05B3fc1D";
	const blocksToCheck = [794399, 794400, 794401,794402];
	const results = [];

	for(let i = 0; i<blocksToCheck.length;i++){
		results.push(await signedParent(signer, blocksToCheck[i]));
	}
};
run();
``` 
Result:
```
Signer 0x8c517B3BaB0e2d65D5cdF3750CA360ff05B3fc1D signed blockNumber 794399 (0x3a607cd697cfb25dc1467c31f1af62f41bac6eb595d6db854db14bff03c04513) == true
Signer 0x8c517B3BaB0e2d65D5cdF3750CA360ff05B3fc1D signed blockNumber 794400 (0xa49e21e358e0e67c55a2327f09b72eeb16b006638d979179a18b3d2f188d05b2) == true
Signer 0x8c517B3BaB0e2d65D5cdF3750CA360ff05B3fc1D signed blockNumber 794401 (0xf8d2f1daeea8bdbecc275d6420d155bcb0514b190975f1dce2618d4d9fed7ecd) == false
Signer 0x8c517B3BaB0e2d65D5cdF3750CA360ff05B3fc1D signed blockNumber 794402 (0xfe50195c7f2c4f3eecb96f78858ea28cae48af774e3ca30b53182b25f8a7d2c7) == true
```
**This also implies the missed block should be 794401**

**Comment by mrsmkl** [comment]
This should be fixed already, looks like baklava blockscout hasn't been upgraded for a while. Note that the missed block is 794400 (parent of 794401).

**Comment by aaronmboyd** [comment]
@mrsmkl So for clarification, when calling `celocli validator:signed-blocks` what's reported is always actually a missed signature on block-1 ?
