### ISSUE TITLE
Data saver toggle is shown ON even when the user turn off data saver toggle  after tapping on the “Restart To Switch” option from “Restart To switch OFF data saver” pop up. 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#3921]
**Frequency:** 100%
**Repro App version:** Play store (Internal Build) v1.8.2
**Does not repro:** Celo Alfa 1.8.0 (101848577)
**Repro on device:** Google pixel XL (8.1), Vivo 1606 (6.01)
**Tested Account:** 319 553 5090 / [Backup key](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit#gid=0) 
**Repro Steps:** 
1) Launch app and login with tested account
2) Tap on the Cog icon from the wallet tab. 
3) Tap on  Data saver option from setting 
4) Turn ON data saver toggle. 
5) Enter PIN and make sure Toggle is ON now. 
6) Turn OFF Data saver toggle. 
7) Tap on Restart To switch option from “Restart To Switch OFF data Saver” pop up. 
8) After Restart App navigate to Data saver and observe Data saver toggle is shown ON.  

**Current Behavior:** Data saver toggle is shown ON even after user turned it OFF.
**Expected Behavior:**Data saver toggle should Turn OFF. 
**Investigation:**
Some time Restart To switch OFF data saver” pop up is not shown and user is able to turn off dat saver toggle. 

**Attachment:** [DatasaverIssue.mp4](https://drive.google.com/file/d/1F7qHgaFZ6ETrSvbpJH-PSezXDDzh0SGt/view?usp=sharing) (Bug observe at 1:27 sec)

**Comment by Lss-Ankit** [comment]
@jeanregisser Verified with App store v1.8.0 and able to reproduced the issue
- Data saver toggle is shown ON even when the user turn off data saver toggle after tapping on the “Restart To Switch” option from “Restart To switch OFF data saver” pop up. 

Attachment: [DataSaverIssue.mov](https://drive.google.com/file/d/1MvSuIDh_ruFmcY93fO-sxMAYg33muopR/view?usp=sharing)

**Comment by nityas** [comment]
Does not reproduce on v1.8.2

**Comment by Lss-Ankit** [comment]
Hi @nityas i have verified issue on iOS test flight celo integration buid v1.8.2 (39) and Android: Play store build v1.8.2 and found that issue is still reproduced. 

- Data saver toggle is shown ON even when the user turn off data saver toggle after tapping on the “Restart To Switch” option from “Restart To switch OFF data saver” pop up.

Verified on : Iphone 6+ (12.4.5) , Google Pixel XL (8.1)

Please find the attachment for the same: 
Attachment : [IOS_DataSaverIssue.mp4](https://drive.google.com/file/d/1PvahjePAVJx4T1VP4M6EGRWLaI-qIclG/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
Verified with latest IOS test flight Valora build v1.0.0(6) and observed that issue is Fixed
- **Device Used:** iPhone 5(12.4.5)
