### ISSUE TITLE
[celocli/rewards] rewards calculation seems slightly inaccurate

### ISSUE THREAD

**Issue by zviadm** [celo-org/celo-monorepo#3933]
### Expected Behavior

Lets take an example address:
0x6ac7E3D0BDeb78ddcF3d9b15208B50C08271C213

This started with total balance of: 
10001e18
At the time of writing this issue, it has balance of: 
10016140457079575417652

At the time of writing this epoch rewards look like:
```
:~$ celocli rewards:show --voter=0x6ac7E3D0BDeb78ddcF3d9b15208B50C08271C213 --epochs=11
Failed to initialize libusb.
Running Checks:
   ✔  0x6ac7E3D0BDeb78ddcF3d9b15208B50C08271C213 is a registered Account 
Calculating rewards... done

Voter rewards:
Address                                    Addresspayment                           Group                                      Averagevalidatorscore Epochnumber 
0x6ac7E3D0BDeb78ddcF3d9b15208B50C08271C213 0                                        0x7C75B0B81A54359E9dCCDa9cb663ca2e3De6B710 0.8332281830026       27          
0x6ac7E3D0BDeb78ddcF3d9b15208B50C08271C213 0                                        0x3FEf91a3422F4dA394C08f115632D3e075d0EFFd 0.8332281830026       27          
0x6ac7E3D0BDeb78ddcF3d9b15208B50C08271C213 0                                        0xD018838832f6112dE72EE6CC9967C56B333a0d1C 0.8327484277939       27          
0x6ac7E3D0BDeb78ddcF3d9b15208B50C08271C213 0                                        0x602B65795BCc64b2fb329AC004236E194f077158 0.8332281830026       27          
0x6ac7E3D0BDeb78ddcF3d9b15208B50C08271C213 0                                        0x0d4f8cEA48cDaDEAe345431577a64983c0535B12 0.8332281830026       27          
0x6ac7E3D0BDeb78ddcF3d9b15208B50C08271C213 0                                        0xd25c6a9FEf4744E8d4F90Bf6bdFAF7686909d799 0.8332281830026       27          
0x6ac7E3D0BDeb78ddcF3d9b15208B50C08271C213 0                                        0xDaDBd6Cfb29b054aDC9c4c2Ef0F21f0BBdb44871 0.8332281830026       27          
0x6ac7E3D0BDeb78ddcF3d9b15208B50C08271C213 711006035191757677.80209479366623549644  0x7C75B0B81A54359E9dCCDa9cb663ca2e3De6B710 0.8499053647018       28          
0x6ac7E3D0BDeb78ddcF3d9b15208B50C08271C213 1601374114344352814.1310064696244673615  0x7C75B0B81A54359E9dCCDa9cb663ca2e3De6B710 0.8649148282309       29          
0x6ac7E3D0BDeb78ddcF3d9b15208B50C08271C213 1601575033783157916.65463219078342769128 0x7C75B0B81A54359E9dCCDa9cb663ca2e3De6B710 0.878423345407        30          
0x6ac7E3D0BDeb78ddcF3d9b15208B50C08271C213 1601795188497001216.31044159381475173458 0x7C75B0B81A54359E9dCCDa9cb663ca2e3De6B710 0.8905810108663       31          
0x6ac7E3D0BDeb78ddcF3d9b15208B50C08271C213 1602004440393422048.80630913175831190134 0x7C75B0B81A54359E9dCCDa9cb663ca2e3De6B710 0.9015229097794       32          
0x6ac7E3D0BDeb78ddcF3d9b15208B50C08271C213 1602211949618597825.45224290551231709888 0x7C75B0B81A54359E9dCCDa9cb663ca2e3De6B710 0.9113706188011       33          
0x6ac7E3D0BDeb78ddcF3d9b15208B50C08271C213 1574755843751283662.05246762414059918423 0x7C75B0B81A54359E9dCCDa9cb663ca2e3De6B710 0.9202335569209       34          
0x6ac7E3D0BDeb78ddcF3d9b15208B50C08271C213 1487924793624875414.34541227664070801345 0x7C75B0B81A54359E9dCCDa9cb663ca2e3De6B710 0.928210201228        35          
0x6ac7E3D0BDeb78ddcF3d9b15208B50C08271C213 1575662277620117920.8400319454995220592  0x7C75B0B81A54359E9dCCDa9cb663ca2e3De6B710 0.9353891811052       36          
0x6ac7E3D0BDeb78ddcF3d9b15208B50C08271C213 1587387323077494478.46215136020888943212 0x7C75B0B81A54359E9dCCDa9cb663ca2e3De6B710 0.9418502629945       37          

```

When you sum these rewards up, it doesnt match the total, it is a little bit smaller.
I found this, because I have different method of calculating rewards on https://celovote.com and those actually sum up correctly to the current balance.

Other reasons why `celocli` version is most likely slightly wrong:
* rewards per epoch should be increasing because group that this address was voting for has had 100% uptime, and its locked & voting balance would have been increasing from epoch to epoch. Thus its rewards must be increasing every epoch, but that is not the case in `celocli` version.

Also as an added note, I think it is possible to calculate voter rewards using only events from:
* election.ValidatorGroupVoteActivated
* election.ValidatorGroupActiveVoteRevoked
* election.EpochRewardsDistributedToVoters

using these events removes dependency on `gcmode=archive` and is also orders of magnitude faster compared to what celocli does right now for calculating voter rewards. (i can share a quick gist of the code that does calculation using events only)

**Comment by zviadm** [comment]
this is what the rewards look like on celovote.com
![image](https://user-images.githubusercontent.com/517937/83302261-00138880-a1c9-11ea-9bb7-b38661a63797.png)

```
10001e18 + 15.1405e18 ~= 10016.140457079575417652
```
(note how the per epoch values don't match to celocli values, celocli is underestimating rewards by 0.01e18-0.02e18 cGLD)

**Comment by jamescowling** [comment]
I was looking into some of this myself and it seems that epoch rewards actually *are* inaccurate, not just as shown in the CLI. In the epoch I checked I received slightly more than 1.00016 return. I've also confirmed that the numbers shown on celovote appear to be the correct returns I'm actually receiving, it's just that they're more than should be dictated by the protocol.

Seems this is another precision issue. Feels important to be very precise here if people end up using rewards as the basis for financial instruments.

**Edit:** Actually I don't know which numbers to believe so maybe this is just a cli issue? Hard to know exactly where this precision is being lost.

**Comment by zviadm** [comment]
> I was looking into some of this myself and it seems that epoch rewards actually _are_ inaccurate, not just as shown in the CLI. In the epoch I checked I received slightly more than 1.00016 return. I've also confirmed that the numbers shown on celovote appear to be the correct returns I'm actually receiving, it's just that they're more than should be dictated by the protocol.
> 
> Seems this is another precision issue. Feels important to be very precise here if people end up using rewards as the basis for financial instruments.
> 
> **Edit:** Actually I don't know which numbers to believe so maybe this is just a cli issue? Hard to know exactly where this precision is being lost.

i forgot to reply to this before. rewards payed out arent statically defined as x0.00016 per epoch, since actual paid out rewards depends on current CELO supply vs predefined CELO supply curve. in the beginning, we were behind the curve slightly so rewards paid out were higher than x0.00016 per epoch. However right now we are slightly ahead of the curve so rewards paid out are actually going to be slightly lower than x0.00016. If even more people lock CELO and start voting, we will be even more ahead of the curve and per locked CELO rewards will actually drop even more.

**Comment by zviadm** [comment]
attaching the gist: https://gist.github.com/zviadm/1ad9e91fe5f36063a93f4f39bcf3057c
its not the cleanest code in the world but general idea should be understandable from it
