### ISSUE TITLE
App get crash when user taps on device back button after navigating to  "Licenses" page 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#3956]
**Frequency:** 100%
** Repro App version:** Play store v1.8.2
**Repro on device:** redmi note 6 pro Android (9.0), Samsung Galaxy M30s  (9.0)
**Does not repro on** Google Pixel XL (8.1), 
**Tested Account:** 4422379165 / Backup key 

**Repro Steps:** 
1) Launch app and login with tested account
2) Tap on cog icon click on Licenses option 
3) Tap on device back button once or twice and observe 
 
**Current Behavior:** App is getting crashed
**Expected Behavior:** Should get back to Celo home screen 

**Attachment:** 
1. Suddencrashinlicensesbackbutton.mp4 (Bug observe at 30 sec)
2. [celo_logs.txt](https://github.com/celo-org/celo-monorepo/files/4724101/celo_logs.2.txt)

**Comment by tarikbellamine** [comment]
@i1skn please look out for this while finishing the Settings redesign
