### ISSUE TITLE
Create and implement a protocol to handle flaky tests

### ISSUE THREAD

**Issue by gastonponti** [celo-org/celo-monorepo#3991]
- [x] Design document on how we could isolate and take actions over a flaky test
- [x] Implementation (Automate?)

**Comment by aslawson** [comment]
@alecps @barbaraliau do we know the status on this? is it blocked by something?
it appears all the checkbox items have been completed above

**Comment by alecps** [comment]
@aslawson This has been finished for a while. I built the flake-tracker back in June but it could probably use some more love. We had to disable it on a couple test suites and unfortunately the monorepo CI experience is still less than perfect as a result. I'd be happy to chat more about the flake-tracker with you or anyone else that may be working on it.
