### ISSUE TITLE
CLI governance:view/show improvements

### ISSUE THREAD

**Issue by gastonponti** [celo-org/celo-monorepo#4000]
Current behavior:
governance:view and governance:show display `timeUntilStages` fields before a proposal has been dequeued. These are misleading because the stage times are set when the proposal is dequeued.

Desired behavior:
Do not print out `timeUntilStages` if stage is Queued

**Comment by eelanagaraj** [comment]
I think this should be fixed/made irrelevant by this PR: https://github.com/celo-org/celo-monorepo/pull/6475

Overlaps enough with [this issue](https://github.com/celo-org/celo-monorepo/issues/6081).

(The field will be removed entirely and replaced with `schedule`, displayed in a different/more readable form.
