### ISSUE TITLE
Handle TX failure/tx fee edge cases

### ISSUE THREAD

**Issue by annakaz** [celo-org/celo-monorepo#4010]
### Expected Behavior

Please describe the behavior you are expecting

### Current Behavior

What is the current behavior?

**Comment by cmcewen** [comment]
Transaction reverted by the EVM: https://sentry.io/organizations/celo/issues/1526588141/?project=1250733&query=is%3Aunresolved

**Comment by cmcewen** [comment]
Could not decode reason: https://sentry.io/organizations/celo/issues/1648484432/?project=1250733&query=is%3Aunresolved&statsPeriod=14d
