### ISSUE TITLE
[Bug Report] Connecting banner overlaps logo on iOS integration build 

### ISSUE THREAD

**Issue by annakaz** [celo-org/celo-monorepo#4011]
![IMG_5691](https://user-images.githubusercontent.com/16907027/83824611-d4dade80-a68b-11ea-8704-787da8ed1125.PNG)

### Expected Behavior

No overlap on banner

### Current Behavior

Connecting to celo banner overlaps logo

**Comment by tarikbellamine** [comment]
I believe this has been addressed
