### ISSUE TITLE
[Bug Report] "Undefined" shown in balance for 0 in sidebar in iOS integration build

### ISSUE THREAD

**Issue by annakaz** [celo-org/celo-monorepo#4012]
![IMG_5697](https://user-images.githubusercontent.com/16907027/83824727-179cb680-a68c-11ea-9efa-b0a3490fe5fa.PNG)
### Expected Behavior

0 shown when balance is 0 

### Current Behavior

Undefined shown when balance is 0

**Comment by tarikbellamine** [comment]
Not sure which PR this was fixed in but confirmed closed by @cmcewen
