### ISSUE TITLE
[Bug Report] Gold screen loads indefinitely on iOS integration build

### ISSUE THREAD

**Issue by annakaz** [celo-org/celo-monorepo#4013]
![IMG_5698](https://user-images.githubusercontent.com/16907027/83824777-3b5ffc80-a68c-11ea-956e-35458b5f3bcf.PNG)

### Expected Behavior

Can see gold chart and gold exchange rate

### Current Behavior

Loading icon hangs indefinitely

**Comment by i1skn** [comment]
This was due to firebase configuration and should be good now
