### ISSUE TITLE
[Bug Report] Wallet stuck on white screen then crashes with iOS integration build

### ISSUE THREAD

**Issue by annakaz** [celo-org/celo-monorepo#4015]
### Expected Behavior

App does not crash, or shows error screen if it crashes

### Current Behavior

Left the app running in the background, came back to a white screen that was unresponsive. Reopened the app and got an iPhone modal that the app had crashed. Sent the crash report to the app store account so we can get logs
![IMG_5701](https://user-images.githubusercontent.com/16907027/83825211-8a5a6180-a68d-11ea-9453-c57534215bdb.png)

**Comment by tarikbellamine** [comment]
Closing this as it is now captured by #4867
