### ISSUE TITLE
No result for " Bead" is shown on "Send or Request" screen when user enter last 4 digit address of user B

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#4020]
**Frequency:** 100%
** Repro App version:** Play store v1.8.2
**Repro on device:** Google Pixel XL (8.1)
**Tested Account:** 319 553 5090/ Backup key 

**Repro Steps:** 
1) Launch app and login with tested account
2) Tap on “+” tab. 
3) Enter last 4 digit of another user’s address.
4) Observe  

**Current Behavior:** No result for " Bead" is shown 
**Expected Behavior:** User should be able to get the address while enter last 4 digit

**Attachment:** 
1. [RecipientAdd.png](https://drive.google.com/open?id=1SW5UdzrUsV0F_MgO9cb_dg2Oehz260pX
) 

2.[AddNotFound.mp4](https://drive.google.com/open?id=15cp5Nyr52M_EyJjvqDWVea_MXhip0FOT) (Bug observe at 10 sec)

**Comment by tarikbellamine** [comment]
This was a misunderstanding around testing Secure Send functionality. Addresses should not be searchable using last 4 digits exclusively.

**Comment by Lss-Ankit** [comment]
Yes @tarikbellamine thanks for the updates.
