### ISSUE TITLE
“Back” and “Cancel” button both are shown on “Verifying” screen while verifying phone number.  

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#4033]
**Frequency:** 100%
** Repro App version:** Play store v1.8.2
**Tested Account:** 503 447 5958 / Backup key 
**Repro Steps:** 
1) Launch app and login with tested account
2) Tap on Hamburger menu. 
3) Tap on Setting option
4) Tap on Verify Phone Number option. 
5) Tap on Start Verification button. 
6) Observe. 
 
**Current Behavior:** Back and cancel button both are shown.
**Expected Behavior:** Only one button should show either cancel or 

**Attachment:** Back&CancelIssue.png
![Back cancelButtonIssue](https://user-images.githubusercontent.com/55572027/83944053-5b272a00-a81e-11ea-9ccc-ca8187ce4bef.png)

**Comment by ValoraQA** [comment]
Hi @tarikbellamine I have verified this issue using  Test Flight build V1.15.1 & observed that issue is fixed now. User is able to see "Cancel" button while verifying phone number is on going.
**Verified On Devices:** iPhone SE (14.2), iPhone SE 1st Generation (14.6), iPhone 6+ (12.4.5)
