### ISSUE TITLE
User is able to get back from QR code screen when tapping on top left corner even Back icon is not shown

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#4048]
**Frequency:** 100%
**Repro App version:** Test flight build v1.8.2(35)
**Repro on device:** iPhone XS max (13.1)

**Repro Steps:**
1.launch the app
2. Home page> tap on scanner icon
3. Tap on top left corner
4.observe user get back from scanner Qr code page

**Current Behavior:** User is able to get back from QR code screen when tapping on top left corner even Back icon is not shown
**Expected Behavior:** Back button should show on scanner QR code screen
Attachment: IOS_BackButtonIssue.mp4 (Bug observed at 08 sec)

**Comment by tarikbellamine** [comment]
Fixed by #4017

**Comment by Lss-Ankit** [comment]
@tarikbellamine Issue also repro for data saver screen. 

- User is able to back to setting screen by tapping on top left corner on Data saver screen even though back icon is not shown. 

Attachment: [backButtonIssue.mp4](https://drive.google.com/file/d/17U35A2E1p944jna_Yj3bl58-wZS8YEuZ/view?usp=sharing)

**Comment by tarikbellamine** [comment]
Is this using the latest integration build? It should be closed by #4161, which contains a redesign of the settings screen that doesn't use back buttons. Please reopen if you see this on the latest build with the new settings.

I will look into if something strange is happening with the navigation bars.

**Comment by Lss-Ankit** [comment]
Hi @tarikbellamine , yes i am usinng latest test flight Celo integration wallet build v1.8.2 (40) and observed that < arrow is not shown howeever User is able to back to setting screen by tapping on top left corner on Data saver screen even though back icon is not shown.

can you please let me know is it expected behaviour?

**Comment by tarikbellamine** [comment]
It is not expected but let's wait until we can reproduce on the next build before reopening.

**Comment by Lss-Ankit** [comment]
Thanks @tarikbellamine for the update!
sure i will verify issue on next build and update the issue.

**Comment by Lss-Ankit** [comment]
Hi @tarikbellamine I have verified this issue using latest Android internal build v1.3.0(1004294316) & Test Flight Build v1.3.0(27). and found issue is fixed
Repro on devices: Vivo V11 pro (10),iPhone 6+(12.4.5)
