### ISSUE TITLE
 Nothing happens  by tapping on “Submit” button when user came slide back from account key page 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#4058]
**Frequency:** 100%
** Repro App version:** Celo integration build v1.8.2 (35)
**Repro on device:** iphone 6+ (12.4.5)
**Repro Steps:** 
1) Launch app and login with tested account
2) Tap on hamburger menu> Account key
3) Tap on set up key button
4) Enter pin and tap on submit button
5) get back from account key page by sliding the page
6) tap on submit button and observe nothing happens 
 
**Current Behavior:** Nothing happens  tapping on submit button when user came slide back from account key page 
**Expected Behavior:** User should submit the pin when user came back from Account key page 
**Attachment:** [NothingHappenTappingOnSubmitButton.mp4](https://drive.google.com/file/d/1Yl01Hbd16BfJHBf7dxilhhN9s_Ofc9vK/view?usp=sharing)

**Comment by tarikbellamine** [comment]
I believe this was fixed in #4098

**Comment by Lss-Ankit** [comment]
Yes @tarikbellamine Due to Design changes now submit button is not shown whie entering the PIN and Also, user redirect to Account Key walkthrough when user slide back hence issue is fixed.
