### ISSUE TITLE
Update Exchange Icon for CELO

### ISSUE THREAD

**Issue by aaronmgdr** [celo-org/celo-monorepo#4066]
https://drive.google.com/drive/folders/1t5wiM2-ZPVCBVW4uvNYQyDD0thDqmRCZ

**Comment by laurencedelisle** [comment]
Exchange Icon Text here: https://docs.google.com/document/d/1TY_Vtf35oGM7PAtjsgqLLxpUDuZPFbkSshg5QQHv53c/edit

Figma with updated icons here: https://www.figma.com/file/HAe97Ol6f1O0suiF1oE83Z/BrandKit-1.0
