### ISSUE TITLE
CI SBAT use integration tests against alfajoresstaging once it's deployed with BLS

### ISSUE THREAD

**Issue by kobigurk** [celo-org/celo-monorepo#407]
### Expected Behavior

Integration tests should work against alfajoresstaging once it's re-deployed.

### Current Behavior

Integration are disabled against alfajoresstaging.

**Comment by timmoreton** [comment]
@kobigurk can you remind me which tests you mean?

**Comment by kobigurk** [comment]
Fixed by https://github.com/celo-org/celo-monorepo/pull/617 already, my bad.
