### ISSUE TITLE
“Oops ! something went wrong text is shown when user taps on data saver button from settings page

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#4074]
**Frequency:** 100%
** Repro App version:** Celo integration build v1.8.2 (36)
**Does not repro:** app store build v1.8.0
**Repro on device:**iPhone XS max (13.1)
**Repro Steps:** 
1) Launch app and sign up in the app
2)Home> tap on Hamburger menu
3) Tap on settings button
4) Tap on data saver button and observe 

 
**Current Behavior:** “Oops ! something went wrong text is shown when user taps on data saver button from settings page
**Expected Behavior:** Data saver toggle button should show 
**Impact:** User is blocked to turn on / off data saver toggle. 
**Attachment:**[OopsSomethingWentWrong.mp4 ](https://drive.google.com/file/d/1oZPzZfFtoO5ohbUtkfBQd7LdpgA5n1tB/view?usp=sharing)(Bug observed at 0.6 sec)

**Comment by annakaz** [comment]
Should be fixed by https://github.com/celo-org/celo-monorepo/pull/4068

**Comment by Lss-Ankit** [comment]
Verified on latest test flight Valora app build v1.0.0 (6) and found that issue is fixed.
