### ISSUE TITLE
User avatars often show up as blank circles

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#4084]
**Frequency:** 100%
** Repro App version:** Celo integration build v1.8.2 (36)
**Does not repro:** app store build v1.8.0
**Repro on device:**iPhone XS max (13.1), iphone 6+ (12.4.5)
**Backup Key** 503 447 5958/ [Backup key](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit#gid=0)

**Repro Steps:** 
1) Launch app and login with tested account. 
2) Tap on Hamburger menu. 
3.) Observe.
 
**Current Behavior:**  Blank circle is shown instead first letter of user name.
**Expected Behavior:** First letter should be shown. 
**Attachment:**[ ProfilePicIssue .png ](https://drive.google.com/file/d/1sIZa9Gg_nHfnkK8VRMiaBgvId_6hJR07/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
Verified with latest IOS test flight build v1.0.0(4) and observed that issue is still Repro
- Blank circle is shown instead first letter of user name on Profile pic from left panel menu.
- **Device Used:**  iPhone 6(12.4.7)

**Comment by Lss-Ankit** [comment]
Verified with latest IOS test flight build v1.0.0 (15) and found that issue is still reproduced. 
- Blank circle is shown instead first letter of user name on Profile pic from left panel menu.
Note: issue does not repro on Android valora app build v1.0.0 (14) 
Verified devices: iPhone 7+ (13.3.1)

**Comment by Lss-Ankit** [comment]
Verified with latest IOS test flight build v1.3.0 (27) and found that issue is still reproduced.

- Blank circle is shown instead first letter of user name on Profile pic from left panel menu.

Verified devices on: iPhone SE 2 (13.5), 

Does not repro on Android  build v1.3.0(1004294316) Google pixel Xl (8.1).

**Comment by ole-nov** [comment]
will be fixed with CIP8 profile photo storage

**Comment by Lss-Ankit** [comment]
Hi @aleksey-nov @nityas I hve Verified this issue with latest Android Internal Build V1.9.1(1004294332) & Test Flight Build V1.9.1(42) ) and found that issue is still reproduced.

- Random profile picture is shown instead of first letter of user name on Profile pic when user clicks on hamburger menu

**Note:** Also it is observed that profile changes according to first letter only on Setting page.
**Verified devices:** iPhone SE (MXD02)+ (13.4.1),Pixel (10)

**Comment by ValoraQA** [comment]
Hi @aleksey-nov I have verified this issue using latest  Android Internal Build V1.11.0(1004294337) & Test Flight Build V1.11.0(47) & observed that issue is fixed now. User able to see first letter of profile name in Hamburger menu.
**Verified on Devices:** Samsung Galaxy A5(7.0), iPhone SE (13.4.1)
**Attachment:** [UseAbleToSeeFirstLetter.png](https://drive.google.com/file/d/11_CUlHpSHB8WPa94l5bCqlfE0u-WS-3Z/view?usp=sharing)
