### ISSUE TITLE
Users account is not getting frozen even though user get “Get backup key” Blue color header when user has not set up their account key. 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#4085]
**Frequency:** 100%
** Repro App version:** Celo integration build v1.8.2 (36)
**Does not repro:** app store build v1.8.0
**Repro on device:**iPhone XS max (13.1), iphone 6+ (12.4.5)

**Pre-Condition:** Get back up key blue banner is shown after some times when user has not set up their back up key. 

**Repro Steps:** 
1) Launch app and sign up with new account
2) Wait for few hrs and remained logged in account. 
3) Make sure user will see “Get Back up” blue banner on Home screen. 
4) Tap on Get backup key button from blue banner. 
5) Tap on Hamburger menu and observed. 

 **Current Behavior:** Account is not getting frozen when Get backup key blue banner is shown. 
**Expected Behavior:** Account should froze when get back up key blue banner is shown. 
**Impact:** User is able to use the application even though user has not set up account key 
**Attachment:**  [GetbackupKeyIssue.mp4](https://drive.google.com/file/d/1jgNqnjigWYg7WYvOHwPIwCN6R6MjBWoZ/view?usp=sharing) (Bug observed at  sec)

**Comment by Lss-Ankit** [comment]
@annakaz Verified issue on latest build v1.0.0 (6) and found that issue is still repro. 
Verified on : iPhone 6+ (12.4.5)

**Comment by Lss-Ankit** [comment]
@annakaz  Verified with latest Android Valora app build v1.0.0 (12) & IOS test flight build v1.0.0 (11) and found that issue is still repro 
- Users account is not getting frozen even though user get “Get backup key” Blue color header when user has not set up their account key.

**Verified on Devices:**
Google Pixel Xl (8.1) | iPhone 6+ (12.4.5)

**Comment by Lss-Ankit** [comment]
@jeanregisser @annakaz Verified issue with latest Android internal build v1.1.0(1004294309) & iOS test flight build v1.1.0(21) and found that issue is still reproduced. 

- Users account is not getting frozen even though user get “Get backup key” Blue color header when user has not set up their account key.

Verified devices: iPhone 7+ (13.3.1) , Google Pixel Xl (8.1)

**Comment by tarikbellamine** [comment]
@nityas probably worth scoping out what exactly we want to happen here.

@gnardini assigning to you for now but feel free to pass this on if need be.

**Comment by jeanregisser** [comment]
@Lss-Ankit could you confirm you've seen the blue banner asking to get the backup key in the latest build (23 and 1004294311)? And it stays on top until you complete the backup process?

The only problem is even if it's displayed on top, the user can still navigate and do other actions, right?

**Comment by Lss-Ankit** [comment]
Hi @jeanregisser i have not observed Back up Key Blue banner on (23 and 1004294311) till now as i have setup account key for my accounts. 
For Android internal build v1.1.0(1004294309) & iOS test flight build v1.1.0(21) i am getting blue banner but user is able to navigate and do actions even though banner is displayed on top. so can you please confirm is it expected now? 

will verify issue on latest build and update the bugs for the same.

**Comment by Lss-Ankit** [comment]
@jeanregisser I have verified this issue using Android internal build v1.1.0(1004294311) & iOS test flight build v1.1.0(23) and observe the following 
- User is able to do actions even when Back up Key Blue banner is shown 
Device: iPhone 11 (14iOS), samsung galaxy m40

**Comment by gnardini** [comment]
I don't understand this issue, if the user hasn't completed their Account Key, should they be blocked from doing anything else? That sounds a bit extreme. In what situation should that happen?

**Comment by Lss-Ankit** [comment]
Hi @gnardini 
- User is able to see the blue color banner for get backup key when user not setup account key  but user is able to do other actions. 
- And previously, user is not able to do actions if account is frozen (If Get Backup Key blue banner is shown).
