### ISSUE TITLE
“Unknown” text is shown when user getting the escrew payment or adding amount from Add and Withdraw option 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#4086]
**Frequency:** 100%
** Repro App version:** Celo integration build v1.8.2 (36)
**Does not repro:** app store build v1.8.0
**Repro on device:**iPhone XS max (13.1), iphone 6+ (12.4.5)

**Repro Steps:** 
1) Launch app and sign up in the app 
2) Make sure the user has verified the phone number. 
3) Make sure user is got the escrow payment 
4) Observe Unknown text is shown. 
5) Add amount form Add & Withdraw option. 
6) Observe Unknown text is shown. 

 **Current Behavior:**  Unknown text is shown
**Expected Behavior:** Appropriate text should be shown instead of Unknown text. 
**Attachment:**  UnknownText.png

**Comment by Lss-Ankit** [comment]
@tarikbellamine  I have verified this issue using latest build Android internal build v1.1.0  (1004294311) and Test flight build v1.1.0 (23) and observe issue is again repro So i am reopening this ticket
“Unknown” text is shown when user getting the escrew payment & when user received payment
**Device:** iPhone 11 (14 iOS),Samsung Galaxy A70(9.0)
**Attachment:** [UnknownText.PNG](https://drive.google.com/file/d/13zUcGP3AVom7-Tb8sVtE1goHNSewXRVQ/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
@gnardini Verified issue on latest build Android play store internal build v1.3.0(1004294316) & Test Flight build v1.3.0(27) and found that issue is still repro for IOS  Test Flight build v1.3.0(27). 

- Unknown text is shown on transaction feed for IOS when Android user is sending an amount to IOS user. 

Verified devices: 
- Google Pixel Xl (8.1) , iPhone SE 2 (13.5) , iPhone XS max(13.5.1) , Samsung Galaxy M30s(9.0)

**Comment by nityas** [comment]
@Lss-Ankit closing this out as we have a separate issue #https://github.com/celo-org/celo-monorepo/issues/5975 that should hopefully resolve everything not handled by the QR Name Display-- please feel free to open if this is a misunderstanding!

**Comment by Lss-Ankit** [comment]
Hi @nityas thanks for information, yes we have understood.
