### ISSUE TITLE
Blank screen is shown for while when user open a “Add and Withdraw” screen after cold launch the app. 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#4094]
**Frequency:** 100%
** Repro App version:** Celo integration build v1.8.2 (36)
**Repro on device:**iPhone XS max (13.1), iphone 6+ (12.4.5)
**Tested Account:** 503 447 5958 / Backup Key
Pre-condition: Application is launch after cold launch the app. 
**Repro Steps:** 
1) Launch app and login with tested account 
2) Tap on Hamburger menu. 
3) Tap on Add And withdraw option 
4) Observe blank screen is shown for while. 
 
**Current Behavior:**  Blank screen is shown while. 
**Expected Behavior:** Add & withdraw screen should show immediately. 
**Impact:** User will get frustrated by seeing blank screen even they have solid internet connection. 
**Attachment:** [ AddAndWithdrawLoadIssue.mp4](https://drive.google.com/file/d/1gy8zuMD8VlR20SvfgtGdFGiXHxMtGyJn/view?usp=sharing) (Bug observed at 40  sec)

**Comment by annakaz** [comment]
Should be resolved with new Cash In flow, please reopen this if it's still observed @Lss-Ankit

**Comment by Lss-Ankit** [comment]
Verified with latest IOS test flight build v1.9.1(41) and observed that issue is Fixed

**Comment by Lss-Ankit** [comment]
Hi @tarikbellamine I have verified this issue using latest Android internal build v1.3.0(1004294316) & Test Flight Build v1.3.0(27). and found issue is fixed
Repro on devices: Vivo V11 pro (10),iPhone 6+(12.4.5)
