### ISSUE TITLE
Blank circle is shown on the Get back up  walkthrough screen when the user taps on the “Set up Now” button while creating a backup key. 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#4103]
**Frequency:** 100%
** Repro App version:** Celo integration build v1.8.2 (37)
**Repro on device:**iPhone XS max (13.1), iphone 6+ (12.4.5)
**Repro Steps:** 
1) Launch app and sign up in the app
2) Make sure user should see backup key notification in home page 
3) Tap on backup key>Set up now
4) Observe blank circle is shown 

**Current Behavior:**  Blank circle is shown on “Your Account Key is a special  kind of password ” page when user tap on set up now button
**Attachment:** BlankCircleIssue.mp4 (Bug observed at 07 sec)

**Comment by tarikbellamine** [comment]
This is addressed.

**Comment by Lss-Ankit** [comment]
@tarikbellamine  i have verified this issue  latest build Android internal build v1.1.0 (1004294311) and Test flight build v1.1.0 (23) and found issue is fixed
**Device:** iPhone 11 (14iOS), Samsung Galaxy A70(9.0)
