### ISSUE TITLE
Secure Send address input should auto-focus on next input form when typing

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#4116]
**Frequency:** 100%
** Repro App version:** Celo integration build v1.8.2 (37)
**Repro on device:**iPhone XS max (13.1)

**Pre-condition:** Recipients should have two verified accounts with the same phone number  to initiate the send security fow. 

**Repro Steps:** 
1) Launch app and sign up in the app
2) Tap on send button
3) select contact 
4) Tap on Confirm account number 
5) Make sure user should on “Please confirm contact account page
6) Enter text on box and observe cursor should not move automatically 

**Suggestion:** Cursor should move automatically to next box once enter text is first box
**Attachment:** [Cursorshouldmove.mp4](https://drive.google.com/file/d/1gLdWErV8UOP3Nrsz96AH3MIwjYQ3HXAl/view?usp=sharing) (Bug observed at 04 sec)

**Comment by dominiquejane** [comment]
Should also replace the word "digits" with "characters"

**Comment by Pedro-vk** [comment]
Hi @Lss-Ankit, could you give me access to the video?

**Comment by Pedro-vk** [comment]
The behavior is different in Android, it's necessary a full account instead of the last digits.

**Comment by ValoraQA** [comment]
Hi @Pedro-vk we have verified this issue on latest Android internal build V1.15.0 & Testflight build V1.15.0(63) and observe the followings 
iOS:
- As per the new changes user is able to see Full account number filed on iOS so, issue got fixed.

**Android:** 
- Input cursor not auto focusing on next input when user typing. [Attachment](https://drive.google.com/file/d/1VJojvaUZUM8nYIq-kt0K8NKF-Hcv4gLZ/view?usp=sharing)
Thanks!

**Comment by Pedro-vk** [comment]
@Celoqa please, give me access to the attachment. Thanks 😊

**Comment by ValoraQA** [comment]
Sorry for the inconvenience @Pedro-vk can you please check now i have given access.

**Comment by Pedro-vk** [comment]
There was an issue pushing the code, I'll open a PR soon

**Comment by ValoraQA** [comment]
Thanks @Pedro-vk for quick looking into it.
Please let us know when you open a PR>

**Comment by Pedro-vk** [comment]
This is the PR: https://github.com/celo-org/wallet/pull/449
