### ISSUE TITLE
User is redirected to the Message app while proceeding for payment request. 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#4126]
**Frequency:** 100%
**Repro App version:** Celo integration build v1.8.2 (37)
**Does not repro:** App store build v1.8.0
**Repro on device:** iPhone XS max (13.1), iphone 6+ (12.4.5)

**Repro Steps:** 
1) Launch app and sign up in the app
2) Make sure user should have dollar request
3) Tap on send button 
4) Tap on Pay button and observe user directs to message sent box

**Current Behavior:** User is redirected to Message app while proceeding for payment request. 
**Expected Behavior:** User should pay the dollars by tapping on pay button 
**Attachment:** [Requestsendissue.mp4](https://drive.google.com/file/d/1jloGVBCSq0UiiC8oUqkQrTqw9SHv7b0u/view?usp=sharing) (Bug observed at 1:01 sec)

**Comment by tarikbellamine** [comment]
This should no longer be possible because we are encrypting phone numbers in payment requests with the application of ODIS.
