### ISSUE TITLE
 Incorrect placeholder “First Last”  is shown on “Full name” field on Account Info screen. 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#4160]
**Frequency:** 100%
** Repro App version:** Celo Integration Wallet build v1.8.2 (39)
**Repro on device:**iPhone XS max (13.1), iphone 6+ (12.4.5)

**Repro Steps:** 
1) Launch app 
2) Select the english language and navigate to the next page. 
3) Observe the Full name fields' placeholder. 

**Current Behavior:* First last placeholder is shown 
**Expected Behavior:** First Name and Last name should be shown 
**Impact** Bad user experience
**Attachment:** FullName.png 
![FullName_PlaceholderIssue](https://user-images.githubusercontent.com/55572027/85199937-0355ec00-b311-11ea-88ab-762cda120eeb.PNG)

**Comment by tarikbellamine** [comment]
This is what the new designs call for.

**Comment by Lss-Ankit** [comment]
Hi @tarikbellamine thanks for the update, but the placeholder is not looks like a user accepted, 
Can we update it to First name & Last Name instead just saying First Last. 
Please share your thiughts for the same. Thanks!

**Comment by Lss-Ankit** [comment]
Hey @tarikbellamine can you please confirm again if is it still expected,  we can close the ticket
the placeholder is not looks like a user accepted,
Can we update it to First name & Last Name instead just saying First Last.
Please share your thoughts for the same. Thanks!

**Comment by tarikbellamine** [comment]
Hi @Lss-Ankit, I can confirm that this is not a bug. Thanks!

**Comment by Lss-Ankit** [comment]
Thanks @tarikbellamine for the update!
