### ISSUE TITLE
User should not be able to press the back arrow and land on the VerificationLoading screen

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#4166]
**Frequency:** 100%
** Repro App version:** Celo Integration Wallet build v1.8.2 (39)
**Repro on device:**iPhone XS max (13.1), iphone 6+ (12.4.5),iphone 11(13.3)

**Repro Steps:** 
1) Launch the app & Select English language 
2) Enter required fields on Account Info page & tap on Next button. 
3) Accept Terms & condition page.  
4) Enter Invite code and tap on continue button. 
5) Tap on Start verify Phone number button on verify phone number screen 
6) Make sure Enter Pin screen is open. 
7) Tap on < arrow from enter PIN screen. 
8) Observe Walkthrough screen is open 

**Current Behavior:* User redirects to “+<phone number>” walkthrough screen on tapping on < arrow from Enter PIN screen
**Expected Behavior:** User should redirect to “Verify Your Phone” screen on tapping < arrow from Enter PIN screen
 **Impact** User is able to redirec verifying +<Phne Number> screen without entering PI
**Attachment:** [VerifyPhoneScreenIssue.mp4 ](https://drive.google.com/file/d/18-VqmVvF-ID3C88IdXeKXsF7WybLXUXM/view?usp=sharing) (Bug Observed at 06 sec)

**Comment by Lss-Ankit** [comment]
@tarikbellamine Verified on latest test flight Valora build v1.0.0 (6) and found that issue is still reproduced. 
Verified on : iPhone 6+ (12.4.5)

**Comment by tarikbellamine** [comment]
I believe this has been addressed.

**Comment by Lss-Ankit** [comment]
@tarikbellamine i have verified this issue latest build Android internal build v1.1.0 (1004294311) and Test flight build v1.1.0 (23) and found issue is fixed
Device: iPhone 11 (14iOS), Samsung Galaxy A70(9.0)
