### ISSUE TITLE
 User is not redirect back to "Connect Contacts" screen from "Verifying + <Phone number>" screen after tapping on < Arrow from Connect Contacts screen.

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#4178]
**Frequency:** 100%
**Repro App version:** Celo Integration Wallet build v1.8.2 (39)
**Repro on device:** Iphone 11(13.3)
**Repro Steps:** 
1) Launch the app 
2)  Navigate to Verify Phone number screen 
3) Copy & paste the Three verification code.  
4) Make sure once after Submitting the codes user navigates to Almost done and later to Connect Contacts screen
5) Tap on < arrow from Connect contact screen. 
6) Observe user stuck on "Verifying + <Phone number>" screen

**Current Behavior:**  User is not redirect back to "Connect Contacts" screen 
**Expected Behavior:**  User is should redirect back to "Connect Contacts" screen 
**Investigation:** User cannot navigate from connect contacts page to connect contacts page by tapping < arrow
 **Impact** User is blocked to navigate back to Connect Contacts screen
**Attachment:** [ IOS_VerificationFlowIssue.Mp4](https://drive.google.com/file/d/1eY70G82uOS7ZNvR1_tiwfY9w5EBSNnPj/view?usp=sharing) (Bug Observed at 06Sec)

**Comment by jmrossy** [comment]
Good catch. The Connect Contacts screen shouldn't have a back button

**Comment by Lss-Ankit** [comment]
Thanks @jmrossy for the update
