### ISSUE TITLE
validator:status command is broken in celocli version 0.0.50 

### ISSUE THREAD

**Issue by nategraf** [celo-org/celo-monorepo#4199]
### Expected Behavior

`celocli validator:status` show useful information about a validator

### Current Behavior

Throws and exception

![image](https://user-images.githubusercontent.com/5684286/85575792-b4e46e00-b5ec-11ea-9eca-5e0e474154ff.png)

**Comment by nategraf** [comment]
Possibly fixed by https://github.com/celo-org/celo-monorepo/pull/3908

**Comment by eelanagaraj** [comment]
confirmed that this has been fixed (`v1.1.0`, likely much earlier)
