### ISSUE TITLE
Submit button is not functioning on “Confirm Account Number” screen when send secure flow trigger again after tapping on edit button from sending screen

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#4226]
**Frequency:** 100%
**Repro App version:** Celo Integration Wallet build v1.8.2 (40)
**Repro on device:** iphone 11(13.3)

**Pre-condition:** 
- Make sure user B should created two account using one phone number  
- Make sure user has completed send secure flow once for this user

**Repro Steps:**
1) Launch the app and login to test account 
2)  Tap on Send button. 
3) Select user B who has two account with one number. 
4) Enter an amount and tap on Review button. 
5) tap on Edit button shown next to phone number on sending screen. 
6) Enter last 4 digit account number of User B. 
7) Tap on Submit button and observed. 

**Current Behavior:** Submit button is not functioning. 
**Expected Behavior:** Submit button should functioning. 
 **Impact:** User is not able to proceed for send secure flow again by tapping on edit button. 
**Investigation:** Submit button is function when send secure flow is trigger first time  
**Attachment:**[ EditButtonIshown&SubmitbuttonIssue.MP4](https://drive.google.com/file/d/1ws7u3V1m1diCTQWkM3wXgcKF5cwwWbSo/view?usp=sharing)(Bug observed at 43 sec)

**Comment by tarikbellamine** [comment]
I am unable to reproduce on my device (iphone 10). Can you please confirm that this is happening 100% of the time?

**Comment by Lss-Ankit** [comment]
Hi @tarikbellamine  i have verified issue again on latest test flight build v1.8.2 (40) and found that issue is repro 100%. 
Pre-condition: 
- Make sure user B should created two account using one phone number
- Make sure user has completed send secure flow once for this user
 Please found the repro steps: 
1. Launch the app and login to test account
2. Tap on Send button.
3. Select user B who has two account with one number.
4. Enter an amount and tap on Review button.
5. tap on Edit button shown next to phone number on sending screen.
6. Enter last 4 digit account number of User B.
7. Tap on Submit button and observed.

Verified on Devices: Iphone 6+ (12.4.5), Iphone XS MAX (13.1) 

Attachment: [SubmitButtonIssue.mp4](https://drive.google.com/file/d/1TB8lBp75yV_vMf38y34n_Adpu4QzlfUp/view?usp=sharing)

**Comment by tarikbellamine** [comment]
Unfortunately, I still can't reproduce. What happens if you enter an incorrect 4 digits? Do you get an error message in this case?

**Comment by Lss-Ankit** [comment]
Yes @tarikbellamine When entering incorrect 4 digits i am getting error which says "Account information does not match.." 
However Nothing happing by tapping on submit button with entering correct 4 digits.

**Comment by Lss-Ankit** [comment]
Verified with IOS Test flight Celo interation build v1.9.1 (41)  and observed issue is still reproduced
**Attachment:** [SubmitButtonIssue.mp4](https://drive.google.com/file/d/1HfwO3BDcYAONHu3fGP-p2lTLmAJqUjik/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
Verified with latest IOS test flight build v1.9.1(41) and observed that issue is still Repro
- Submit button is not functioning on “Confirm Account Number” screen when send secure flow trigger again after tapping on edit button from sending screen
- **Device Used:** iPhone 6(12.4.7)
- **Attachment:** [SubmitbuttonConfirmaccscreenIssue.MP4](https://drive.google.com/file/d/1uHToXF53X5RSPh67dW4o40aS76Cbc0Dr/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
Verified with latest iOS test flight valora v1.0.0(6) build and observed that issue is Fixed.
- **Device Used:** iPhone X (13.6)
