### ISSUE TITLE
Abrupt Pincode screen in Send flow contributes to a poor user experience

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#4227]
**Frequency:** 100%
**Repro App version:** Celo Integration Wallet build v1.8.2 (40)
**Repro on device:** iphone 11(13.3)
**Repro Steps:**
1) Launch the app and login to test account 
2) Tap on Send button and Select any contact
3) Make sure we will be navigated to Enter PIN screen
4) Tap on < arrow top left corner
5) Observe user navigated to “Send Amount” page  

**Current Behavior:** User navigating to “Send Amount” page on tapping “<” arrow
**Expected Behavior:** User should navigate to “Send with contact list” page on tapping “<” arrow
 **Impact:** User is able to send the payment without entering without Entering PIN
**Investigation:** 
Issue also repro when user proceed for payment request. 
Issue also repro when user exchange the gold.
**Attachment:** [Back_AmountScreenIssue.MOV](https://drive.google.com/file/d/1oqeVxVtZaVr4RP4NGWIQK3Or7q17NICr/view?usp=sharing) (Bug observed at 07 sec)

**Comment by jmrossy** [comment]
This is due to the PGPNP contact lookup. We can explore medium-term options (e.g. use Data Encryption Key) on how to mitigate this but no avoiding it for now. 

Having watched the video, IMO this isn't so bad. We would have asked for the pin after Send Confirmation anyway and we'll cache it for some time after first use.

**Comment by tarikbellamine** [comment]
This has been addressed.

**Comment by Lss-Ankit** [comment]
@tarikbellamine I have verified this using latest build Android internal build v1.1.0 (1004294311) and Test flight build v1.1.0 (23) and observe the following 
- For Android, User direct to Sending page when tapping on < button from Enter PIN page 
- For IOS, User redirect to home>Activity section with confirming text when user tap on < button from Enter PIN page

**Comment by tarikbellamine** [comment]
@Lss-Ankit can you please open a new issue with a new video for this? It sounds like the issue may be a little different now.

**Comment by Lss-Ankit** [comment]
Hi @tarikbellamine **FYI:** We have opened new issue in  #4891  for this & it is fixed.
