### ISSUE TITLE
Anyone SBAT open up a PR that can be merged

### ISSUE THREAD

**Issue by asaj** [celo-org/celo-monorepo#425]
### Expected Behavior

CircleCI jobs run for PRs opened by anyone

### Current Behavior

CircleCI jobs only running for PRs opened by committers

**Comment by asaj** [comment]
Looks like https://github.com/celo-org/celo-monorepo/pull/343 is having this issue

**Comment by ashishb** [comment]
Enabled "Build Forked Pull requests" at https://circleci.com/gh/celo-org/celo-monorepo/edit#advanced-settings and https://circleci.com/gh/celo-org/celo-blockchain/edit#advanced-settings

**Comment by ashishb** [comment]
https://github.com/celo-org/celo-monorepo/pull/551 failed on Circle CI since our incremental testing setup assumes all the PRs are from the same repository.
