### ISSUE TITLE
Users SBAT verify using any attestation service provider and no proxy

### ISSUE THREAD

**Issue by annakaz** [celo-org/celo-monorepo#4286]
### Expected Behavior

Users can send requests to any attestation service without using a proxy. This could be achieved by ensuring that validators run the attestation service with SSL and moving to use https for communication between the wallet and the attestation service. 

### Current Behavior

Users on Android are unable to send a reveal to some attestation services via http, as the attestation service domains are not whitelisted as safe for cleartext communication in the app. The whitelist cannot be updated dynamically. As a temporary workaround, a proxy was introduced here: https://github.com/celo-org/celo-monorepo/pull/4285

**Comment by aslawson** [comment]
All validators have been upgraded to https. Remaining work to remove proxy is captured in this epic
https://app.zenhub.com/workspaces/celo-5d94ef61d9b1e40001114c02/issues/celo-org/celo-monorepo/6097
(cc @i1skn -- I'll just move this to a task under that epic, but feel free to change or close it as is most appropriate to track on the client side)
