### ISSUE TITLE
User SBAT to faucet themselves with a proper number

### ISSUE THREAD

**Issue by ashishb** [celo-org/celo-monorepo#429]
### Expected Behavior

User SBAT to faucet themselves with a proper number. And in case of a failure, the error should be less robotic. Most people do not know what E.164 number is.

### Current Behavior

The checker is too strict and even `(` or `)` with a robotic message demanding that `E.164 number should be supplied`.

**Comment by aaronmgdr** [comment]
Improvements 

- add a country select which populates the country code
- allow numbers with and without spaces
- allow common number formating characters like `(`, `)` and `-` `+`
- in error describe what number should look like if it is not possible to accept it  (dont mention e164)

**Comment by aaronmgdr** [comment]
see also https://github.com/celo-org/celo-monorepo/issues/754

**Comment by aaronmgdr** [comment]
actual reasons this operation could fail

- not a valid number -- changed UI to be like mobile app and automatically format correctly so this wont happen via web

- twillo not initialized -- (not users fault) 
- failure sending gold or dollars (not users fault) 
- some other network issue (not users fault) 
- twillo could not send for some reason (potentially the number is not able to receive SMS, more likely some other reason)


given this what should the web interface error message say?
