### ISSUE TITLE
Exchange activity is removed when user cold launch the app while exchange activity is in progress. 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#4331]
**Frequency:** 100%
**Repro App version:** Celo Integration Wallet build v1.8.2 (40)
**Repro on device:** iphone 11(13.3), Iphone 6+ (12.4.5)

**Repro Steps:**
1. Launch the Application and Signup with test account 
2. Tap on Hamburger menu. 
3. Tap on Gold option
4. Proceed for Buy / Sell activity. 
5. Cold launch the app when exchange activity is in progress 
6. Observe. 

**Current Behavior:** Exchange activity is removed if it is in progress. 
**Expected Behavior:** Activity should not removed.
**Investigation:** Some time issue also repro while performing payment activity. 
 **Impact:** User is will lost the payment if they cold launch the app. 
**Attachment:** [GoldActivityIssue.mp4](https://drive.google.com/file/d/13TKiR-Se2gAFIez9Z5sT359IN7Bddovp/view?usp=sharing) (Bug observed at  33 sec)

**Comment by tarikbellamine** [comment]
This is expected behavior because the app was closed before the transaction was sent.

**Comment by ValoraQA** [comment]
Hi @tarikbellamine thanks for the information
