### ISSUE TITLE
[ContractKit] Add a way to set or inject the wallet in contract kit

### ISSUE THREAD

**Issue by H34D** [celo-org/celo-monorepo#4360]
### Expected Behavior

We added functionality to support multiple types of wallets in the same application like a local wallet coming from a seed phrase and a ledger wallet. It is up to the user to choose the type of wallet. When changing the wallets, like when the seed phrase changes or the user decides to use a ledger as a wallet for a specific account we need to recreate the whole contract kit because the functionality to set the wallet is in the constructor. Recreating the contract create a lot of rpc calls which is quite costly from some devices types like mobile devices. 

https://github.com/celo-org/celo-monorepo/blob/b4632d2eb40b5f6fb9cf35463b5c08ec338d418c/packages/contractkit/src/kit.ts#L104-L108

### Current Behavior

Every time i want to use a different wallet i have to recreate the whole contract kit.

**Comment by mcortesi** [comment]
I believe we discussed adding a `kit.wallet` property that can be changed by the user. Right @gastonponti ?

There's a subtle problem when working with the provider. There's a state dependency on web3 with providers (think on subscriptions which are stateful objects on web3). So; in theory changing the provider without notifying web3 can be problematic. But for wallets it think it was ok.

**Comment by gastonponti** [comment]
As Mariano said, the provider it's a little more complicate, but we are working on it.

We are changing this wallet set in the refactor to make it easier.
But for in the meanwhile, you could set the wallet from the provider.
```
(kit.web3.currentProvider as CeloProvider).wallet = differentWallet
```

**Comment by H34D** [comment]
> We are changing this wallet set in the refactor to make it easier.
> But for in the meanwhile, you could set the wallet from the provider.
> 
> ```
> (kit.web3.currentProvider as CeloProvider).wallet = differentWallet
> ```

thanks
