### ISSUE TITLE
Both “Buy” and “Sell” buttons are shown even when the user has “0 Gold”

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#4365]
**Frequency:** 100%
** Repro App version:** Celo Integration Wallet build v1.8.2 (40)
**Repro on device:** iphone 11(13.3), iphone 6(12.4.7),
**Pre-condition:** User should have sold the all gold amount after buying it once. 
**Repro Steps:**
Launch the Application and Signup with test account
Tap on the Hamburger menu.
Navigate to  to Celo Gold page
Make sure the user sells all celo gold. 
Sell total gold and make sure user has 0 Gold balance
Observe.

**Current Behavior:** Both “Buy” and “Sell” buttons are displayed even when the user has “0 Gold” Balance
**Expected Behavior:**Only “Buy” button should display when the user has “0 Gold” Balance
 **Impact:** Users should not be able to proceed for sell when they don't have Celo Gold.
**Attachment:**Buy&SellbuttonIssue.png
![Buy SellButtonIssue](https://user-images.githubusercontent.com/55572027/87159757-797dbb00-c2df-11ea-81d9-68e26c2d5358.jpg)

**Comment by gnardini** [comment]
This was fixed on https://github.com/celo-org/celo-monorepo/pull/4714

**Comment by Lss-Ankit** [comment]
Hi @gnardini , @annakaz Verified issue with latest build Test Flight build Valora app build  v1.0.0 (15),Android Valora Mainnet build v1.0.0 (16) and found the following: 

- Buy and Sell both button are not shown when user sign up with new account with 0 CUSD. 
- Only Buy button is shown when user has only cUSD. 
- Buy and Sell both button are shown when user has both CELO and cUSD. 
- Buy and Sell both button are not shown when user lost their CELO and CUSD. 

hence issue is fixed now. 
Verified devices: iPhone 7+ (13.3.1) , Google Pixel Xl (8.1)
