### ISSUE TITLE
Disable backwards navigation after wallet is successfully restored

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#4393]
**Frequency:** 100%
**Repro App version:** Android Celo internal build 1.9.1 , IOS Test flight Celo interation build v1.9.1 (41) 
**Repro on device:** Samsung Galaxy A5 (7.0) , iPhone 6 (12.4.7)
**Repro Steps:**

1. Launch the App and start the sign up flow. 
2. Make sure user on Invite Code screen 
3. Tap on “Restore Existing Wallet” button 
4. Enter Account key and tap on restore button. 
5. Make sure user is redirect to Confirm Phone number screen after some time. 
6. Tap on < back arrow from Confirm Phone Number screen. 
7. Make sure user is on “Restore Existing Wallet” screen. 
8. Tap on Restore button and observe. 

**Current Behavior:** Error “ Importing Wallet Failed” message is shown
**Expected Behavior:** User should be able to restore account. 
**Impact:** User is blocked to go Confirm Phone number screen again. 
**Attachment:** [RestoreIssue.mp4 ](https://drive.google.com/file/d/1MTy-1duRyVG0X97SwHQhIH9z5doC90r9/view?usp=sharing)(Bug Observe at 29 sec)

**Comment by Lss-Ankit** [comment]
Verified with latest IOS test flight build v1.0.0(4) and observed that issue is still Repro
- Error “ Importing Wallet Failed” message is shown when user taps on “Restore” button after navigate back to “Restore Existing Wallet” screen from “Confirm Phone Number” screen.
- **Device Used:** iPhone 11(14.0), iPhone 6(12.4.7)

**Comment by tarikbellamine** [comment]
The back button is now hidden when the user reaches the Confirm Phone Number screen.

**Comment by Lss-Ankit** [comment]
Hi @tarikbellamine  I have verified issue on Test Flight build 1.2.0(25) and Android internal build 1.2.0(1004294313) and observed that back button is not shown on confirm Phone number screen. 

However issue is still repro for Android when user taps on device back button. 
Hence reopening the ticket. 
Device: google Pixel Xl (8.1)

**Comment by Lss-Ankit** [comment]
Hi @tarikbellamine I have verified this issue on latest Android play store internal build v1.3.0(1004294316) and observe "Importing wallet failed" error message is shown when user tap on retore button after navigating back to restore existing wallet screen from confirm page 

Device: Vivo V11 pro (10)

**Comment by Lss-Ankit** [comment]
Hi @gnardini We have verified this issue on latest Android internal build V1.7.2(1004294329) &Test Flight build V1.7.2(39) and found issue is fixed.
**Device :** iPhone 6+ (12.4.5), Vivo V11 pro (12.4.5)
