### ISSUE TITLE
Redirect user to Account Key Education if they press back while on the pin screen

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#4396]
**Frequency:** 100%
**Repro App version:** Android Celo internal build 1.9.1, IOS Test flight Celo integration build v1.9.1 (41)
**Repro on device:** Samsung Galaxy A5 (7.0, iPhone 6 (12.4.7),iPhone 11(14.0)
**Repro Steps:**

1. Launch the Application and Signup with new account 
2. Tap on Set Up Now button from Your Account key In-app notification
3. Make sure user will be navigated to Your Account key page tap on Set Up Now button
4. Navigate through all 4 walk-through screens 
5. Make Sure user will be navigated to Enter PIN screen after 4th walk-through screen
6. Now tap on “<” arrow of Enter PIN screen
7. Observe

**Investigation:** User redirected back to account key page when tapping on "<" button from enter pin screen

**Current Behavior:** Account key is not shown 
**Expected Behavior:** User should navigate to “Your Account key is a special kind of password” first walk-through screen on tapping “<” arrow
**Impact:** User will confused as Account key is shown on "Account Key " screen
**Attachment:** [EnterPINscreenbackArrowIssue.Mp4](https://drive.google.com/file/d/1cuAVPM34jgXl5sv9_JztyjUIDeEBZvce/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
@annakaz Verified with latest play store  Celo Alfajores Wallet build v1.9.4 and found that issue is still reproduced. 
- Account key is not shown when the user taps on < back arrow from Enter PIN screen while user setting up account key.

**Comment by tarikbellamine** [comment]
At the moment, this is expected behavior. The user should not be able to view the account key unless they have successfully entered the pin code.

**Comment by Lss-Ankit** [comment]
Hi @tarikbellamine  yes, correct but can we redirect user to "Your Account Key" screen instead showing blank account key. 
it seems more user friendly experience. 

Please share your thought for the same. 
Thanks!

**Comment by Lss-Ankit** [comment]
Hi @tarikbellamine I have verified this issue using latest Android internal build v1.4.0(1004294317) & observed that issue is still reproduced.
   User not able to see account key even if user has successfully entered the pin code.
**Repro on devices:** Samsung Galaxy A5(7.0)

**Comment by Lss-Ankit** [comment]
Hi @tarikbellamine I have verified this issue using latest Android play store build v1.5.5 & App store build v1.5.5 & observed the issue is still reproduced.
**Observation:**
- User B able to see & store user A's account key even if he does not know PIN of user A's account.

**Investigation:** Any user can steal fund by storing account key.
**Repro on devices:** Samsung Galaxy A5(7.0), iPhone SE
**Attachment:** [AnyoneCanSaveAccountKeyWithoutPIN.mp4](https://drive.google.com/file/d/1JvgCG5ERFhD24knGNA4VfdBjVmr4OvNz/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
Hi, @nityas @tarikbellamine I have verified this issue using latest Android Internal build v1.6.0(1004294326) & Test Flight build v1.6.0(37) observed that issue is still reproduced.
**Repro on devices:** Samsung Galaxy A5(7.0) , iPhone 7 Plus (14.1)

**Comment by Lss-Ankit** [comment]
@tarikbellamine  @gnardini Verified issue on latest build Android  internal build V1.7.2(1004294329) &Test Flight build V1.7.2(39). and found the issue is still repro : 

- User is redirect to Account Key Education with blank account Key field when user taps on < arrow from Enter PIN screen. 
![BlankAccountKey](https://user-images.githubusercontent.com/55572027/103081793-af4cfc80-45fe-11eb-8dbf-b75828708871.png)

**Comment by Lss-Ankit** [comment]
@tarikbellamine verified issue using  latest Android Internal Build V1.9.1(1004294332) & Test Flight Build V1.9.1(42) and found that issue fixed as Enter PIn screen is shown when user taps on Set up now button from Account Key CTA. 

Devices : Google Pixel XL (8.1) , iPhone SE 2 (14.3)
