### ISSUE TITLE
Users SBAT to test a transaction on the wallet without losing money

### ISSUE THREAD

**Issue by medhakothari** [celo-org/celo-monorepo#44]
### Expected Behavior

There should be a way for users to test a transaction on Alfajores on the wallet, and get the money back. This would look something like "Test out a transaction.". A toast would also have to be shown, something like "Note: You may lose some money in gas fees."

The implementation would involve using the current escrow contract to send a transaction and also reclaim it instantly, showcasing both a send and a received transaction in the activity feed, like so:

in a TS function,
- create a new invite code/ temp wallet address
- use escrow's transfer fn, with the expiry seconds field set to 1 second
- reclaim the same payment using the invite code
`src/invite/saga`'s sendInvite function and `src/escrow/saga` would be a great place to see how inviting and escrowed payments work. 

### Current Behavior

Currently the user would have to send a real payment transaction, meaning they would lose Testnet money.

**Comment by nityas** [comment]
"Celo Default Recipient" added in dev envs
