### ISSUE TITLE
[Wallet] Profile picture / name 

### ISSUE THREAD

**Issue by annakaz** [celo-org/celo-monorepo#4409]
### Expected Behavior

A user can see their contacts profile pictures and names using CIP 8

Note that CIP 8 is a stretch goal for this milestone, and this would build on top of that work. 

### Current Behavior

No way for users to share profile picture/name if a user is not already in someone's contacts

**Comment by gnardini** [comment]
Tracked on https://github.com/celo-org/celo-monorepo/issues/5431
