### ISSUE TITLE
Error  " It looks like we 're having issue.." screen is shown when user taps on “MoonPay” Link 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#4428]
**Frequency:** 100%
**Repro App version:** Android Celo internal build 1.9.1, IOS Test flight Celo integration build v1.9.1 (41)
**Repro on device:** Samsung Galaxy A5 (7.0), iPhone 7 (13.5.1),iPhone 11(14.0)
**Repro Steps:**

1. Launch the Application and Sign up with test Account
2. Tap on Hamburger Menu and tap on Add and Withdraw option
3. User will be redirected to Current Balance screen tap on Add funds button
4. Enter any value in Amount field and tap on Next button
5. User will be redirected to $# Add funds page tap on MoonPay Link
6. Observe error page is shown

 

**Current Behavior:** Error page is shown after tapping in MoonPay link
**Impact:** User unable to add money into wallet
**Expected Behavior:** User should be redirected to Add money page
**Attachment:** [ErrorpageinAddFundsIssue.mp4](https://drive.google.com/file/d/1DrZANtP6avMIlHSkVSbfuL2YLWc7MCcs/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
Verified with latest IOS test flight build v1.0.0(4) and observed that issue is still Repro
- Error " It looks like we 're having issue.." screen is shown when user taps on “MoonPay” Link
- **Device Used:**  iPhone 6(12.4.7)

**Comment by tarikbellamine** [comment]
@annakaz assigning to you but feel free to close if already taken care of.

**Comment by Lss-Ankit** [comment]
- Verified issue with latest build Test flight build v1.2.0 (25), Android internal build 1.2.0(1004294313) and found that issue is fixed.

Devices used: Samsung Galaxy A70(9.0), iPhone XS max(13.5.1)
