### ISSUE TITLE
Infrastructure and client should support peering to the network within a few seconds of startup

### ISSUE THREAD

**Issue by nategraf** [celo-org/celo-monorepo#4433]
### Description

We've observed that when using a bootnode, instead of a static node list, it can take up to 30s to become peered and start to sync. We need to investigate why this process is taking so long, and make improvements to the blockchain client and/or bootnode infrastructure to ensure this process is faster the first time a user needs to find peers, and more importantly, fast when the node is started again, such that it does not impact the suer flow when the app is brought back from the background.

**Comment by tkporter** [comment]
Satisfied by #4680
