### ISSUE TITLE
SDK examples for different contexts (ie mobile/web/offline)

### ISSUE THREAD

**Issue by yorhodes** [celo-org/celo-monorepo#4447]
With lessons from #4446 

### Expected Behavior

Please describe the behavior you are expecting

### Current Behavior

What is the current behavior?

**Comment by aslawson** [comment]
closing due to duplicate https://app.zenhub.com/workspaces/devx-backlog-board-6009f3d1a7a39b001018f159/issues/celo-org/celo-monorepo/6750
