### ISSUE TITLE
Contracts SDK module as wrapper for typechain/contract abis/tx data builder

### ISSUE THREAD

**Issue by yorhodes** [celo-org/celo-monorepo#4450]
### Expected Behavior

Please describe the behavior you are expecting

### Current Behavior

What is the current behavior?

**Comment by aslawson** [comment]
@gastonponti was this fixed in  [Sdk Modularization #4790](https://github.com/celo-org/celo-monorepo/pull/4790)?
The PR says it fixes this.

**Comment by aslawson** [comment]
@aslawson to follow up with @yorhodes
