### ISSUE TITLE
“Spacing” is not shown on entering “Spaces in Name field” of Edit Profile page

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#4455]
**Frequency:** 100%
**Repro App version:** IOS Test flight Celo integration build v1.9.1 (41)
**Repro on device:** iphone 7(13.5.1), iphone 11(14.0)
**Does not Repro on device:** Samsung Galaxy A5(7.0), Google pixel 3a(11.0)
**Repro Steps:**

1. Launch the Application and Sign up with test Account
2. Tap on Hamburger Menu and tap on Settings
3. Select Edit Profile option
4. Enter some characters in name field 
5. Enter Spaces in name field 
6. Observe Text entered will not move on entering spaces

**Current Behavior:** Spaces entered are not shown and text entered is not moving
**Investigation:** space is show when user enter next letter
**Impact:** User will get confused whether he entered spaces or not
**Expected Behavior:** Text should move to left on entering spaces in name field
**Attachment:** [NamespacesIssue.mp4](https://drive.google.com/file/d/13fudql6nGGMQgnmd0M0-08R71oHEj1BT/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
@tarikbellamine I have verified this issue using latest build Android internal build v1.1.0 (1004294311) and Test flight build v1.1.0 (23) and observe issue is still repro 
**Devices:** iPhone 6+ (12.4.5), Vivo V11 pro (10)

**Comment by ValoraQA** [comment]
Hi @tarikbellamine I have verified this issue using latest  Android Internal Build V1.11.0(1004294337) & Test Flight Build V1.11.0(47) & observed that issue is fixed now. User able to see spacing name field from Edit Profile as well as while Onboarding.
**Verified on devices:** Samsung Galaxy A5(7.0), iPhone Se(13.4.1)
