### ISSUE TITLE
[ContractKit] Add synchronous access methods to WrapperCache

### ISSUE THREAD

**Issue by H34D** [celo-org/celo-monorepo#4460]
### Expected Behavior

Currently the contract kit constructor is asynchronous and i use it like this.
`const kit: ContractKit = await newKitFromWeb3(web3, wallet)`

I use this method in the initializer of my page and store the result somewhere in a cache or store. But to use the different contracts i have to load all of them individually again which is an additional async/await step every time.

So i ended up with something like this:

```
export async function loadContractKit(): Promise<ContractKitWrapper> {
    const kit: ContractKit = await newKitFromWeb3(web3, wallet)
    console.log('Contract kit loaded!')

    return {
      kit,
      wallet,
      accounts: await kit.contracts.getAccounts(),
      goldToken: await kit.contracts.getGoldToken(),
      stableToken: await kit.contracts.getStableToken(),
      election: await kit.contracts.getElection(),
      validators: await kit.contracts.getValidators(),
      lockedGold: await kit.contracts.getLockedGold()
    }
}
```

Which is not ideal. But i think this can be a functionality that contract kit can offer like:

```
export async function loadContractKit(): Promise<ContractKitWrapper> {

    const kit: ContractKit = await newKitFromWeb3(web3, wallet)
    // preload all the contracts or contracts of choice
    await kit.loadAllContracts() 
    console.log('Contract kit loaded!')

    return kit
```

When loading the contracts the results are stored as a singleton anyway so why not allow access to the object in a synchronous manner it would save the user awaits over awaits

**Comment by mcortesi** [comment]
Good feedback!

The problem when designing this was that:

1. If i make `loadAllContracts()` optional. I can eagerly load all contracts, but from typing perspective, it's the same so `kit.contracts.getAccounts()` still needs to return a Promise. (you don't know if loadAllContracts was called)

2. If i make `loadAllContracts()` part of `newKitFromWeb3()` you can then change the types, but we are forcing the user to load all the contracts. And I can imagine you having an error with one contract which you don't want to use. Or making several calls to the registry you don't need. So i didn't want to force that into users.
