### ISSUE TITLE
User is Stuck in Enter PIN page even after entering correct pin after tapping Account Key option from Menu when user was already in Your Account Key page

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#4487]
**Frequency:** 100%
**Repro App version:**  IOS Test flight Celo integration build v1.9.1 (41)
**Repro on device:** iphone 7(13.5.1), iphone 11(14.0)
**Repro Steps:**

1. Launch the Application and signup with test account
2. Tap on Hamburger Menu and tap on Account Key option
3. Make sure user will redirect to Enter Pin screen
4. Enter the valid pin
5. Make sure user redirect to Your Account key page
6. Tap on Hamburger Menu and tap on Account Key option
7. Make sure user will redirect to Enter Pin screen
8. Enter the valid PIN
9. Observe 

**Current Behavior:** User is getting stuck in Enter PIN page after tapping Account Key option from Menu when user was already in Your Account Key page
**Impact:** User is not able to set up account key
**Expected Behavior:** After entering PIN user should redirect to Your Account Key page
**Attachment:** [StuckinEnterPINscreenfromMenuIssue.mp4](https://drive.google.com/file/d/1s_tDX423hM3AH-ZeCljmDrq6E33fE6Ni/view?usp=sharing)

**Comment by tarikbellamine** [comment]
I believe this has been addressed. @Lss-Ankit can you please check and reopen if need be?

**Comment by Lss-Ankit** [comment]
@tarikbellamine i have verified this issue latest build Android internal build v1.1.0 (1004294311) and Test flight build v1.1.0 (23) and found issue is fixed
Enter pin page is not shown again when user tap on Account key button when user is on Account key page
Device: iPhone 11 (14iOS), Samsung Galaxy A70(9.0)
