### ISSUE TITLE
Valora read only services SBAT rely on very reliable full node 

### ISSUE THREAD

**Issue by annakaz** [celo-org/celo-monorepo#4488]
### Expected Behavior

Valora-related services use a private transaction node/set of nodes with uptime guarantees

### Current Behavior

The wallet relies on mainnet forno (`https://rc1-forno.celo-testnet.org`), which does not have any established uptime guarantees. Since it is used by outside developers it could experience issues due to too much traffic

The wallet relies on forno for:
- blockchain-api 
- notification service
- fetching CELO exchange rates for CELO chart, polling is part of notification service package

**Comment by annakaz** [comment]
Edited to reduce the scope to read only services

**Comment by annakaz** [comment]
There still exists a dependency when the wallet is in forno mode, but the fixes outlined above will fix the wallet when using the light client

**Comment by yorhodes** [comment]
`blockchain-api` and `notification-service` are in the `celo-org-mobile` namespace and the `tx-nodes-private` service is in the `celo-testnet-production` namespace. Thus, they are contained in different google cloud VPC and the private subnet IP addresses aren't available. 

As an alternative, I am investigating putting an external load balancer in front of the `tx-nodes-private` service with a firewall that can limit traffic to the aforementioned internal services.
