### ISSUE TITLE
How to treat QR codes in Valora

### ISSUE THREAD

**Issue by tarikbellamine** [celo-org/celo-monorepo#4490]
### Expected Behavior
- Users can tell when a scanned QR code is out of date
- Users can tell the different between a QR recipient and regular phone contact recipient

### Current Behavior
- There is no way to know if a QR code is out of date. Because QR codes have addresses encoded, users have no way of knowing if they are about to send to an outdated code
- When a transaction is done via QR code, the encoded QR data (e.g., address, user's name) is used to populated a "recent recipient" in Valora. This potentially creates a duplicate recipient that is indiscernible from a recipient populated from the user's phone contacts

**Comment by nambrot** [comment]
What does outdated mean here?

**Comment by tarikbellamine** [comment]
It means a user has verified a new address to their phone number
