### ISSUE TITLE
Review button is getting enable when user enter 0.001 CELO Amount even though user has 0 dollars while buying the CELO

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#4491]
**Frequency:** 100%
**Repro App version:**  IOS Test flight Celo integration build v1.9.1 (41)
**Repro on device:**  iphone 11(14.0)
**Precondition:** User should Buy CELO with his total amount of dollars from wallet
**Repro Steps:**

1. Launch the Application and signup with test account
2. Tap on Hamburger Menu and tap on CELO option
3. Make sure user will redirect to CELO screen
4. Tap on Buy button 
5. Make sure user redirect to Buy CELO page
6. Enter a 0.00# decimal value in Amount field
7. Tap on Review button 
8. Make sure user will redirect to Buy CELO total amount page 
9. Observe the Total amount and tap on Buy # CELO button
10. Make sure user redirect back to CELO page
11. Observe that 0.00# CELO gold bought will be added to Your CELO balance

**Current Behavior:** User able to buy gold of 0.00# amount even continuing with 0.00$ in wallet 
**Impact:** User will get confused that he is  able to Buy CELO even without having dollars in wallet
**Expected Behavior:** User should get error message that you can’t continue without dollars
**Attachment:** [Buy0.00#CELOwith0usdIssue.mp4](https://drive.google.com/file/d/1AMNKS9zzkSLIDivLy7MBBiiWIiqhizVh/view?usp=sharing)

**Comment by tarikbellamine** [comment]
I believe this has been addressed by not allowing the user to enter any values less than $0.01

**Comment by Lss-Ankit** [comment]
@tarikbellamine i have verified this issue latest build Android internal build v1.1.0 (1004294311) and Test flight build v1.1.0 (23) and found issue is fixed
Device: iPhone 11 (14iOS), Samsung Galaxy A70(9.0)
