### ISSUE TITLE
Script for checking a contracts directory corresponds to deployed bytecode

### ISSUE THREAD

**Issue by m-chrzan** [celo-org/celo-monorepo#4496]
### Expected Behavior

It should be possible to verify that a given set of Solidity sources corresponds to the currently deployed bytecodes on a Celo network. This is necessary for automated backwards compatibility checking to make sense. 

### Current Behavior

No such script.

**Comment by mrsmkl** [comment]
The contract upgrade script should do just that (after the contracts have been compiled it compares the bytecodes in the artifacts to the ones in the network).
I'll link the PR to update that script here https://github.com/celo-org/celo-monorepo/pull/4484
