### ISSUE TITLE
Validators SBAT easily begin validating using the CLI

### ISSUE THREAD

**Issue by yorhodes** [celo-org/celo-monorepo#45]
### Expected Behavior

More coupling between validator and validator group management which reduces the number of commands to get setup and the requisite understanding of on-chain architecture (validators in groups)

### Current Behavior

Entirely separate validator and validator group management in the CLI which requires numerous asymmetric commands to get setup

**Comment by asaj** [comment]
Not sure that I agree, I believe validators/groups should need to understand the underlying architecture, at least to the point of understanding that validators and validator groups are separate entities.
