### ISSUE TITLE
Devs SBAT profile + measure time from cold start to fetching balance completion

### ISSUE THREAD

**Issue by cmcewen** [celo-org/celo-monorepo#450]
### Expected Behavior

We know how long it takes till a user can see their current balance after a cold start

### Current Behavior

Not measured

**Comment by annakaz** [comment]
See https://github.com/celo-org/celo-monorepo-old/pull/4279/files for reference

**Comment by annakaz** [comment]
See logs here: https://console.cloud.google.com/logs/viewer?authuser=0&project=celo-testnet-production&minLogLevel=0&expandAll=false&timestamp=2019-08-19T18:11:23.024000000Z&customFacets=&limitCustomFacetWidth=true&interval=NO_LIMIT&scrollTimestamp=2019-08-19T02:13:44.842000000Z&resource=global&advancedFilter=resource.type%3D%22global%22%0AjsonPayload.event%3D%22COMPONENT_UNMOUNT%22
to see where about PR logs to

**Comment by annakaz** [comment]
From cold start, takes about 5 seconds if user immediately pulls down balance refresh screen. See the branch `annakaz/local-measure-fetch-time`
Note that this was taken through the local debugger so it was using a dev build of the app

**Comment by annakaz** [comment]
Closing this issue as we have a rough estimate. Opened https://github.com/celo-org/celo-monorepo/issues/662 to look into formalizing the measurement process
