### ISSUE TITLE
Devs SBAT profile celo-blockchain data usage in the wallet

### ISSUE THREAD

**Issue by asaj** [celo-org/celo-monorepo#451]
### Expected Behavior

We have a clear understanding of the costs (both in data and in time) of syncing, view calls, etc.

### Current Behavior

Back of the envelope calculations

**Comment by annakaz** [comment]
See also making view calls fast- https://github.com/celo-org/celo-monorepo/issues/928

**Comment by jeanregisser** [comment]
Moving to roadmap.
