### ISSUE TITLE
Remaining Minor Redesign Features

### ISSUE THREAD

**Issue by nityas** [celo-org/celo-monorepo#4560]
### Expected Behavior

- [ ] Home Activity should get broken up into Recent (Last 7 days), June, May, etc.” as a supplement to having removed dates from line items. Design: [Figma](https://www.figma.com/file/zt7aTQ5wuXycIwxq5oAmF9/Wallet-Refresh?node-id=2609%3A4659)
- [x] DappKit uses old design system Design: [Figma](https://www.figma.com/file/zt7aTQ5wuXycIwxq5oAmF9/Wallet-Refresh?node-id=3114%3A34886)
- [x] Error Loading Licenses Screen in iOS
- [ ] Handle long names in various places, consider capping length [Menu](https://www.figma.com/file/zt7aTQ5wuXycIwxq5oAmF9/Wallet-Refresh?node-id=986%3A4151), [Onboarding](https://www.figma.com/file/zt7aTQ5wuXycIwxq5oAmF9/Wallet-Refresh?node-id=6831%3A75942), [Settings](https://www.figma.com/file/zt7aTQ5wuXycIwxq5oAmF9/Wallet-Refresh?node-id=6831%3A76313)
- [ ] Fees should be limited to two decimal points. If user expands, the listed fees then display to three decimals. 
![image](https://user-images.githubusercontent.com/2686353/88819015-4444ea00-d174-11ea-9b18-c15e0cba6c21.png)

### Current Behavior

What is the current behavior?

**Comment by tarikbellamine** [comment]
Individual action items are addressed in broken out issues
