### ISSUE TITLE
Verification UI Experience Improvements

### ISSUE THREAD

**Issue by nityas** [celo-org/celo-monorepo#4563]
### Expected Behavior

- [x] Users should be able to enter in received text messages - restarting verification just requests more
- [x] Onboarding should check if I’m already verified before prompting. I have an account that I restored that is already verified to the number I entered in
- [x] Possible manual re-request attestation CTA (eg. button next to each import message box that requests from new issuer)
~~- [ ] change mobile's expiry definition for an attestation request to 5min and re-request new attestation on resume~~

Addressed more fully by an ongoing Verification Enhancements Feature: [figma](https://www.figma.com/file/zt7aTQ5wuXycIwxq5oAmF9/Wallet--Refresh?node-id=8047%3A238)

### Current Behavior

What is the current behavior?

**Comment by i1skn** [comment]
@nityas do you think we can remove "change mobile's expiry definition for an attestation request to 5min and re-request new attestation on resume" in light of the recent discussions?

**Comment by i1skn** [comment]
@nityas is there things left to do in this one?

**Comment by i1skn** [comment]
Closing this one as it seems to be completed
