### ISSUE TITLE
Invite Code Improvements

### ISSUE THREAD

**Issue by nityas** [celo-org/celo-monorepo#4566]
### Expected Behavior

- [ ] Add Invite code to the transaction feed item so it can be re-sent
- [x] Invites do not work due to firebase link shortener error
- [ ] Copy change to make it clear you can copy/paste the whole text message for invite codes [Design](https://www.figma.com/file/zt7aTQ5wuXycIwxq5oAmF9/Wallet-Refresh?node-id=5404%3A430)
- [x] Update invite text message to link to same play store link as the inviter is using

### Current Behavior

What is the current behavior?

**Comment by i1skn** [comment]
@nityas what domain for the short links we would like to use?

**Comment by nityas** [comment]
closing out due to komenci shipping! bye invite codes :)
