### ISSUE TITLE
Received / Sent CELO improvements

### ISSUE THREAD

**Issue by jeanregisser** [celo-org/celo-monorepo#4576]
### Expected Behavior

Received / Sent CELO activity items in the CELO feed should be consistent with exchange (Sold / Bought) items.
We shouldn't mention Celo Dollars in the drill down.

### Current Behavior

Received / Sent CELO appear in the CELO feed in an inconsistent looking way (icon for the received payment, no icon for the exchange).
Also the details screen mentions Celo Dollars.

<img src="https://user-images.githubusercontent.com/57791/88922048-d7167f00-d26f-11ea-9f28-8e9c1f1ba4ff.png" width="50%" /><img src="https://user-images.githubusercontent.com/57791/88922092-eeee0300-d26f-11ea-8ef0-688566b2e5e7.png" width="50%" />

**Comment by gnardini** [comment]
On a [recent PR](https://github.com/celo-org/celo-monorepo/pull/4646) I changed something related to this. It still says "Payment received", which I'm not sure if it's exactly what we want.

It now looks like this:

<img width="342" alt="Screen Shot 2020-08-14 at 12 04 20" src="https://user-images.githubusercontent.com/6062888/90263660-56867f80-de26-11ea-980f-691a804f3831.png">
<img width="362" alt="Screen Shot 2020-08-14 at 12 04 31" src="https://user-images.githubusercontent.com/6062888/90263669-59817000-de26-11ea-94da-bd06b6e0d63b.png">
