### ISSUE TITLE
User is redirected to Home page instead of Qr code page by tapping “<” arrow from Send page while making transaction using scanner icon

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#4588]
**Frequency:** 100%
**Repro App version:**  IOS Test flight Valora build v1.0.0 (6)
**Repro on device:** iPhone 5S (12.4.5)
**Repro Steps:**

1. Launch the Application and signup with test account
2. Tap on QR Code icon and tap on Scan option
3. Scan the User B’s QR code 
4. Make sure User will be forwarded to Send Page 
5. Tap on “<” arrow 
6. Observe User will be redirected to Home page

**Current Behavior:** User is directly redirected to home page instead Qr code page on tapping “<” from the Send page. 
**Expected Behavior:** User should be redirected to Qr code page on tapping “<” from the Send page.
**Impact:** Bad user experience as user redirect to Home screen instead QR code screen.
**Attachment:**  [“<”ArrowfromSendPagethroughQRCodeIssue.MP4](https://drive.google.com/file/d/1k4_5NqomgTP1NoFGJbSbfgayiF_3a7Ot/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
@annakaz Verified with latest valora app v1.0.0 (10) and found that issue is still reproduced. 
Devices:  Google Pixel XL (8.1), Samsung Galaxy S4 (4.4), Samsung galaxy grand prime (5.1.1)

**Comment by tarikbellamine** [comment]
This is expected behavior.

**Comment by Lss-Ankit** [comment]
Okay thanks @tarikbellamine for the updates
