### ISSUE TITLE
Implement an indepenent transaction limit for cash in/out

### ISSUE THREAD

**Issue by tarikbellamine** [celo-org/celo-monorepo#4612]
### Expected Behavior
There are individual $500 daily limits for Valora send transactions and Valora fiat cash in/out transactions.

### Current Behavior
There is one $500 daily limit that applies to both send and fiat cash in/out transactions. Send transaction limits are defined [here](https://github.com/celo-org/celo-monorepo/blob/master/packages/mobile/src/send/reducers.ts#L47) and fiat transactions are being checked against this [here](https://github.com/celo-org/celo-monorepo/blob/master/packages/mobile/src/fiatExchanges/FiatExchangeAmount.tsx#L104). We need to keep track of fiat transactions similarly to how we are doing it for send transactions.

**Comment by tarikbellamine** [comment]
@i1skn has this been resolved?

**Comment by i1skn** [comment]
I'm not sure, @nityas what would you say?

**Comment by tarikbellamine** [comment]
Closed in favor of #6981
