### ISSUE TITLE
Load all Illustration in the Brand Kit

### ISSUE THREAD

**Issue by laurencedelisle** [celo-org/celo-monorepo#4629]
Purpose: At the moment the "Illustrations" section of the "Key Imagery" tab of the Brand Kit only loads 4 images (the tenets). We have 11 images that should load now.

Illustrations Tab in Airtable: https://airtable.com/tblTaF3gZVuRZ9krb/viwuzLYM3roLQZ74f?blocks=hide

![Screen Shot 2020-08-04 at 4 11 29 PM](https://user-images.githubusercontent.com/53497147/89354237-30feb680-d66d-11ea-9fc1-6781c3dc31d7.png)

Web Page: https://celo.org/experience/brand/key-imagery#illustrations
![Screen Shot 2020-08-04 at 4 10 45 PM](https://user-images.githubusercontent.com/53497147/89354213-204e4080-d66d-11ea-92c6-bbeb95e2b21e.png)

**Comment by aaronmgdr** [comment]
The Terms and Approved rows were not checked. 

checked them and they load
