### ISSUE TITLE
Continuous loading indicator is shown when user paste received invite code on “Invite Code” screen

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#4655]
**Frequency:** 100%
**Repro App version:**  Celo Alfajores Wallet (Internal early Access) v1.9.4 (105094704) 
Does not repro on: Play store build v1.8.2.
**Repro on device:** Google Pixel XL (8.1) 
**Pre-Condition:** User should receive Invite code from friends 

**Repro Steps:**
1. Launch the Application and complete the walkthrough. 
2. Enter Full and select country and enter phone number. 
3. Tap on Next button. 
4. Create a Security PIN
5. Paste Received Invite Code. 
6. Observe 

**Current Behavior:** Continuous loading indicator is shown 
**Expected Behavior:** User should be able to sign up with Invite code. 
**Impact:** User is blocked to sign up with invite code. 
**Attachment:** [Android_InviteCodeissue.MP4 ](https://drive.google.com/file/d/1lp2Ly0hRyg05balUWjbaRlLdl7KzIEEz/view?usp=sharing)(Bug observed at 30 sec)

**Comment by Lss-Ankit** [comment]
I have verified this issue on Valora app build v1.0.0 (10) and in iOS test flight build v1.0.0 (11) and found issue is fixed

**Comment by annakaz** [comment]
@Lss-Ankit can you confirm whether you're seeing this in the latest build?

**Comment by annakaz** [comment]
Seeing invite codes failing on the most recent build as well. See https://docs.google.com/document/d/1NmEdo4lyLox_2t0efuzuiXSBhVeLLINJ-d5MnKe7ej4/edit?disco=AAAAG1oO_TI for details

**Comment by dominiquejane** [comment]
Additional details from Aug 19 onboarding session:
Users were sent an invite code, however, neither copy/pasting the entire link nor using just the passcode in the link worked. Roughly 70% of the users were unable to use the invite code.

I saw some messages on slack about the operation timing out after 2 min, which may have been the case for many of the users.

**Comment by Lss-Ankit** [comment]
Hi @annakaz I have verified Invite flow using Android Valora app build v1.0.0 (12) & IOS test flight build v1.0.0 (11) and found the following: 
- "Invite code has no funds" error message is shown when user proceed for sign up with using received invitation code. 
Note: I have sent invitation from user A who has balance and after sent invitation $0.25 also cut for User A

![InvitecodeIssue](https://user-images.githubusercontent.com/55572027/90745317-12133d80-e285-11ea-854a-75aaa213c779.PNG)

**Comment by Lss-Ankit** [comment]
Hi @annakaz , @jeanregisser i have  verified issue on latest Test Flight build Valora app build  v1.0.0 (15) , Valora Mainnet build v1.0.0 (14) and found that issue is fixed. 
- User is able to create an account using received invitation code. also got escrow payment after creating account. 
Hence closing this ticket. 
Verified devices: iPhone 7+ (13.3.1), Google Pixel Xl (8.1)
