### ISSUE TITLE
[Wallet] No error shown in CELO exchange flow if balance is not yet loaded 

### ISSUE THREAD

**Issue by annakaz** [celo-org/celo-monorepo#4658]
### Expected Behavior

If balance is not yet loaded, show error so users understand why they cannot proceed with their CELO purchase

### Current Behavior

From App Store testing: 
"We discovered one or more bugs in your app when reviewed on iPad running iOS 13.6 on Wi-Fi.

Specifically, when we attempted to purchase “Celo” via the “Cell” tab, we could not proceed after adding an amount."
![attachment Screenshot-0810-122850](https://user-images.githubusercontent.com/16907027/89816346-45263600-dafb-11ea-9734-2e5badbc8c45.png)

**Comment by annakaz** [comment]
I believe the user had 0 balance, so the "Buy" and "Sell" buttons in CELO home should have both been hidden. The issue may be that "Buy" is not being hidden when there is a 0 cUSD balance

**Comment by tarikbellamine** [comment]
Addressed by #4714
