### ISSUE TITLE
Add Fathom Analytics to Reserve Site

### ISSUE THREAD

**Issue by aaronmgdr** [celo-org/celo-monorepo#4660]
Add fathom to celoreserve.org

**Comment by AlexBHarley** [comment]
Could we also consider https://plausible.io?

**Comment by aaronmgdr** [comment]
We could. We already have a fathom account thats being used for Valoraap.com so setup would be easy

Fathom benefits
+ no cookies or other individual tracking 


I see Plausible has similar privacy / gdpr goals. 

oh it has query param source tracking. nice.

**Comment by AlexBHarley** [comment]
It's also open source which is cool. But I'm all for continuing to use what we already use.
