### ISSUE TITLE
[Wallet] CELO activity disappears after confirmed

### ISSUE THREAD

**Issue by annakaz** [celo-org/celo-monorepo#4681]
### Expected Behavior

Past CELO purchases appear in CELO activity feed after they are confirmed

### Current Behavior

Past CELO purchases appear in CELO activity feed only while confirming, but disappear once confirmed

![Screenshot_20200811-215914](https://user-images.githubusercontent.com/16907027/89976762-2f5d6180-dc1e-11ea-8cf6-55426e811d6f.png)
![Screenshot_20200811-215858](https://user-images.githubusercontent.com/16907027/89976766-32f0e880-dc1e-11ea-9321-e30cf0a7f9aa.png)

**Comment by Lss-Ankit** [comment]
@annakaz  Verified with latest build Valora Mainnet build v1.0.0 (11) and found that issue is still reproduced. 

- CELO activity disappears after confirmed 
Verified device : Google Pixel XL(8.1) | Vivo 1606 (6.0.1)

**Comment by jeanregisser** [comment]
This is now resolved on mainnet and was caused by `blockscout` not processing blocks fast enough.

See discussions started in https://celo-org.slack.com/archives/CMX4JFMQW/p1597759018123100
