### ISSUE TITLE
[Wallet] Comment request from new build to pre-comment encryption build shows cypher text

### ISSUE THREAD

**Issue by annakaz** [celo-org/celo-monorepo#4682]
### Expected Behavior

Comment unavailable is shown the same way it is handled in the transaction feed

### Current Behavior

Unreadable cypher text appears in the comment request text area if a request is sent from a build with comment encryption enabled to an older build
![IMG_6064](https://user-images.githubusercontent.com/16907027/89976975-d9d58480-dc1e-11ea-9f01-f49bbb16a905.PNG)

**Comment by tarikbellamine** [comment]
I believe this has been addressed
