### ISSUE TITLE
 [Lower end device] Amount (CELO) & subtotal fields are not shown on the “ Buy CELO” screen when the user taps button from CELO tab.

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#4701]
**Frequency:** 100%
**Repro App version:**  V1.0.0(10)
**Repro on device:** Samsung Galaxy Grand Prime(5.1.1),Samsung galaxy S4(4.4.2)
**Does not Repro:** Google Pixel XL (8.1) ,Samsung Galaxy A5(7.0)
**Repro Steps:**
1. Launch the Application and signup with test account
2. Tap on hamburger menu
3. Tap on celo
4. Tap on buy button 

**Current Behavior:** User is not able to see the Amount field & subtotal field on buy celo page 
**Expected Behavior:** Buy celo page should fit to screen when user tap on buy button 
**Investigation:** Amount and Subtotal fields are shown after tapping on Done button from Keypad. 
**Impact:** Users may get confused by seeing only the Review button. 
**Attachment:** [BuyCeloNotfitToScreen.mov](https://drive.google.com/file/d/1RPXJdlxgvmhSdPR7F0KdGXLFtzpbF5kQ/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
I have verified this issue with Valora app build v1.0.0(11) and found that issue is also repro on Add and withdraw screen

**Attachment:** [amountcelo.MOV](https://drive.google.com/file/d/18EeS1cR_0uz8p3vUm1rjZjXn4QXDOc_m/view?usp=sharing)

**Comment by tarikbellamine** [comment]
The buttons are hidden until the Geth is connected. Notice how "Connecting..." is displayed at the top of your screen

**Comment by Lss-Ankit** [comment]
@tarikbellamine Issue is repro only for low end devices can you please confirm is it still expected 
Repro on device: Samsung Galaxy Grand Prime(5.1.1),Samsung galaxy S4(4.4.2)
Does not Repro: Google Pixel XL (8.1) ,Samsung Galaxy A5(7.0)

**Comment by tarikbellamine** [comment]
Yes, lower end devices will typically take longer to connect to Geth. This is expected.

**Comment by Lss-Ankit** [comment]
Ok thanks @tarikbellamine for the confirmation.
