### ISSUE TITLE
Separating Invitations from Fees

### ISSUE THREAD

**Issue by coreycelo** [celo-org/celo-monorepo#4710]
### Expected Behavior

Invitations should be more distinct from fees positioning them a tad more like a purchase than a fee.

Review Screen
* Invitations are broken out as a top level item (rather than under Estimated Fees)

Feed
* Worth a discussion here, but proposal is to separate Payment + Invite transactions into two feed items

Drilldown
* Above would mean breaking into separate drilldowns as well
* The new "Invitation" feed item would be an obvious home for some changes going on in #4566 
* The "Payment" feed item would then reuse a typical payment drilldown design
    * This means we don't have to make changes to how Invite line items show up in the Receipt section
    * We also don't have to use a unique title, it currently displays: "Escrow Payment Sent"

Design: [Figma](https://www.figma.com/file/zt7aTQ5wuXycIwxq5oAmF9/Wallet-Refresh?node-id=7839%3A3945)

<img width="1620" alt="Screen Shot 2020-08-14 at 11 57 51 AM" src="https://user-images.githubusercontent.com/51388535/90283696-71a4bf80-de25-11ea-9b55-2047a7349b60.png">

### Current Behavior

What is the current behavior?

**Comment by tarikbellamine** [comment]
Good suggestion but I think this will no longer be relevant with feeless attestations
