### ISSUE TITLE
DApp Developers SBAT quickly setup a local celo blockchain (w/ganache)

### ISSUE THREAD

**Issue by mcortesi** [celo-org/celo-monorepo#472]
### Expected Behavior

For a developer working with celo. It needs to quickly launch a local blockchain for development. This means not only the node, but the core contracts.

In other projects, a ganache snapshot is generated and stored in the cloud for devs to consume. Also, a docker image is useful.

For example, check: https://www.npmjs.com/package/@0x/migrations

### Current Behavior

We either connect to integration or alfajores. To run tests, we do it with the e2e framework, but that's not ideal for unit tests; or to have a development chain.

**Comment by barbaraliau** [comment]
We currently have the Celo development blockchain via `yarn test:reset && yarn test:livechain` from the `contractkit` directory.
[See docs](https://docs.celo.org/developer-guide/development-chain)
