### ISSUE TITLE
Review button is not getting enabled when a user scans the QR code of another user while withdrawing CELO. 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#4732]
**Frequency:** 100%
**Repro App version:**  Valora Mainnet build v1.0.0 (11)
**Repro on device:** Google Pixel XL(8.1) , Vivo 1606 (6.0.1)  
**Test Account:** (680) 333-1978/ [Backup key.](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit#gid=0) 
**Repro Steps:**
1. Launch the Application and sign in with test account
2. Tap on the Hamburger menu. 
3. Tap on CELO option
4. Tap on Withdraw CELO 
5. Tap on the QR code icon. 
6. Scan the valid QR code. 
7. Make sure other user’s Account no is shown in Account No field. 
8. Enter an amount in the Amount (CELO) field. 
9. Observe Review button. 

**Current Behavior:** Review button is not getting enabled
**Expected Behavior:** Review button should enable 
**Investigation:** Issue does not repro when the user sends CELO by pasting Account no. of other users. 
**Impact:** Users are blocked to proceed for sending CELO using QR code. 
**Attachment:** [Android_ReviewButton_CELO.mp4](https://drive.google.com/file/d/10lriPZNWf3hzLvLgHVTl5pYU5tC4ur43/view?usp=sharing) (Bug observe at 21 sec)

**Comment by gnardini** [comment]
The format of the QR code changed recently and is a deep link instead of a json now, so the address is not read correctly, that's why the review button doesn't work :( Working on a fix.

**Comment by Lss-Ankit** [comment]
@annakaz , @gnardini Verified with Android Valora build v1.0.0 (12) and found that issue is fixed as user is able to proceed for withdraw CELO after Scanning QR code. 
Verified Device: Google Pixel XL (8.1)
