### ISSUE TITLE
[4 os specific] App get crash when user tap on “MoonPay” button from “Add funds” page 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#4734]
**Frequency:** 100%
**Repro App version:**  Valora Mainnet build v1.0.0 (11)
**Repro on device:** Samsung galaxy S4(4.4.2)
**Does not Repro:** Google Pixel XL(8.1) , Vivo 1606 (6.0.1) ,Samsung Galaxy Grand Prime(5.1.1)
**Repro Steps:**

1. Launch the Application and signup with test account
2.  Tap on Hamburger menu
3. Tap on Add & withdraw
4. Tap on Add Funds button
5. Enter celo amount & tap on Next button
6. Tap on Moonpay button & observe 

**Current Behavior:** App get crash 
**Expected Behavior:**  User should be able to proceed for to add credit card details. 
**Impact:** User get blocked to add credit card details
**Attachment:**

1. [MoonPayCrash.MOV](https://drive.google.com/file/d/1eaH4aSqKOq6Xnm2nYCUJin56MY1BW8oT/view?usp=sharing) 
2. [MoonPayCrashlogs.txt](https://drive.google.com/file/d/19KVfRdK-0KxisDH_WMoZT5sQTSLjr--B/view?usp=sharing)

**Comment by tarikbellamine** [comment]
@annakaz assigning this to you for now. maybe related to #4428?

**Comment by Lss-Ankit** [comment]
Hi @tarikbellamine @annakaz I have verified this issue using latest  Android internal build v1.2.0(1004294314) on lower end devices and observe  issue is still reproduced.
**Repro on device:** Samsung Galaxy S4(4.4.2)
**Observation:** Also in Samsung Galaxy A3(5.0.2) it is observed that when user tap on Moon Pay link then white blank screen is showing.
**Attachment:**
[MoonpayCrashlog.txt](https://github.com/celo-org/celo-monorepo/files/5399652/celo_logs-1.txt)

**Comment by Lss-Ankit** [comment]
Hi @tarikbellamine @annakaz I have verified this issue using latest Android internal build v1.2.0(1004294316) on lower end devices and observe issue is still reproduced.
**Repro on devices:** Samsung Galaxy A3(5.0.2)
**Observation:** In Samsung Galaxy A3(5.0.2) white blank screen is showing for longer time when user tap on 'Moon Pay' lin.

**Comment by tarikbellamine** [comment]
Moonpay provider link works

**Comment by ValoraQA** [comment]
Hi @tarikbellamine I have verified this issue using latest  Android Internal Build V1.11.0(1004294337) on lower end device & observed that issue is still reproduced. App crashes when user taps on Moonpay & Ramp link on Add Funds screen.
**Verified on Device:** Samsung galaxy S4(4.4.2)

**Comment by tarikbellamine** [comment]
This should be fixed by this PR: https://github.com/celo-org/wallet/pull/73

Please reopen if you are able to repro on v1.11.1

**Comment by ValoraQA** [comment]
Hey @tarikbellamine I have verified this issue using latest Android internal Build V1.11.1(1004294338) &Test Flight Build V1.11.1(48) & observed that issue is fixed now.
**Verified on devices:** Samsung galaxy S4(4.4.2)
