### ISSUE TITLE
Migrate Mobile App to the new contractkit

### ISSUE THREAD

**Issue by mcortesi** [celo-org/celo-monorepo#475]
### Expected Behavior

Use ContractKit
- [x] View functions (exchange rate, fetching balances, contract decimals)
- [ ] State changing functions

### Current Behavior

Uses WalletKit

**Comment by yerdua** [comment]
blocked by:
#671 - contractkit wrapper for `Escrow`
#1042 - contractkit wrapper for `GasPriceMinimum`
#1019 - contractkit wrapper for `Attestations`

**Comment by yerdua** [comment]
### Missing/Incomplete wrappers
- Escrow (missing: #671)
- GasPriceMinimum (missing: #1042)
- Attestations (in-progress: #1019)

### Functions from walletkit without equivalents in contractkit
- **GenesisBlockUtils** => gets the genesis block for a given network, downloading from google cloud storage
- **StaticNodeUtils** => gets the static node urls for a given network, downloading from google cloud storage
- **ContractUtils.getExchangeRate** => calls `exchange.methods.getBuyTokenAmount` and then processes the result slightly
- **ContractUtils.getGasPrice** => this calls GasPriceMinimum with the given currency and multiplies the result by 5
- **extractAttestationCodeFromMessage** => pulls an attestation code out of a message from an SMS. This looks specific to the mobile app?
- **parseFromContractDecimals** => It's part of `erc20-utils`, which are maybe useful?
- **sanitizeBase64** => body of the function is:
  `return base64String.replace(/(¿|§)/gi, '_')`
   with a comment expressing confusion about why it's necessary
- **getErc20Balance** => no equivalent exists, maybe it should?
- **awaitConfirmation** => it calls `.confirmation` on the `TxPromises` it takes as an argument

### Functions from walletkit that are Attestations contract or wrapper functions (after #1019):
- makeApproveAttestationFeeTx => attestations.approveAttestationFee
- findMatchingIssuer => attestations.findMatchingIssuer
- getActionableAttestations => attestations.getActionableAttestations
- getWalletAddress => attestations.getWalletAddress
- lookupPhoneNumbers => attesatations.lookupPhoneNumbers
- makeCompleteTx =>> attestations.complete
- makeRequestTx => attestations.request
- makeRevealTx => attestations.reveal
- makeSetAccountTx => attestations.setAccount
- validateAttestationCode => attestations.validateAttestationCode
- getDataEncryptionKey => attestations.contract.methods.getDataEncryptionKey

### Renamed functions, walletkit => contractkit
- sendTransactionAsync => sendTransaction


## Rough plan for migration after blockers are addressed:
1. Cache an instance of the contractkit in mobile
2. Move StaticNodeUtils + GenesisBlockUtils somewhere accessible to the mobile app, and use them in that new location
3. Replace all contract calls with `contractkit` contract wrapper interactions
4. Deal with all other functions with no current equivalents in `contractkit`

**Comment by jmrossy** [comment]
Adding some info from the mobile wallet retro meeting:
- There's a concern that using contract kit in with the app in zero-sync mode will cause all headers to be synced. (Unconfirmed)
- Sending transactions via contract kit won't work because the kit's utilities don't support zero-sync mode. For this we need local signing and gas-in-dollars by default transactions
- The current walletkit tx sending utility functions that the wallet uses make it easy to customize the logging. Just need to confirm contractkit's utilities can do the same

**Comment by jmrossy** [comment]
Another small issue to tackle before migrating:
Calling contract kit class methods with redux saga effects doesn't work unless the `this` context is explicitly specified like so:
```  
 const attestationsWrapper: AttestationsWrapper = yield call([
      contractKit.contracts,
      contractKit.contracts.getAttestations,
    ])
```

Before we fully migrate, we should find a more elegant way to call methods
