### ISSUE TITLE
"Failed to retrieve phone number secret" message is shown while sending payment to non Valora users. 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#4752]
**Frequency:** 100%
**Repro App version:**  Valora Mainnet build v1.0.0 (12)
**Does not repro Version:** Celo Alfajores Wallet (Internalearly Access) v1.9.4 (105094704) , Android IOS Test flight build v1.0.0 (11)
**Repro on device:**  Google Pixel XL(8.1) ,
**Account Key:** 443 390 2072/[backupKey](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit#gid=0)
**Repro Steps:**
Steps:
1. Launch the app and login with test account.
2. Tap on Send button from home screen.
3. Search contact number who does not have Valora app or not used valora yet.
4. Tap on Contact user.
5. Make sure user is on "Send" screen.
6. Enter an amount in Send screen.
7. Observe "Failed to retrieve phone number secrete" message is shown.

**Current Behavior:** "Failed to retrieve phone number secret" message is shown
**Expected Behavior:**  User should be able  to proceed to send fund for non valora users. 

**Investigation:**
- Issue also repro when user  try to verify phone number.
- Also, observe that Lookup quota screen is not shown when user proceed for phone number verification with 0 balance.

**Impact:** User is blocked to send money to non valora users. 
**Attachment:** [non valora user.mp4](https://drive.google.com/file/d/1u7OzvBJB_S8KKJ59N9SiXvp-Kf8hyx-0/view?usp=sharing) (Bug observe at 09 sec)

**Comment by tarikbellamine** [comment]
Closed by #4772

**Comment by Lss-Ankit** [comment]
- Verified issue with latest build Test flight build v1.2.0 (25), Android internal build 1.2.0(1004294313) and found that issue is fixed.

Devices used: Samsung Galaxy A70(9.0),iPhone XS max(13.5.1)
