### ISSUE TITLE
[Wallet] Failed to create wallet shown when creating a new wallet after removing account

### ISSUE THREAD

**Issue by annakaz** [celo-org/celo-monorepo#4763]
### Expected Behavior

Able to create new wallet after removing account

### Current Behavior

To reproduce: 
Go through onboarding flow, go to settings and click remove account, see app restart, click continue without invite, see "Failed to create your wallet" error banner and loading sign hang indefinitely. After killing app and trying again, see same error. After clearing app data from Android app settings, able to create new wallet

**Comment by gnardini** [comment]
I'm having trouble reproducing this, did you bump into this bug or was it Ankit? It would be really helpful to have logs to see what the problem might be.

**Comment by annakaz** [comment]
I saw this on a Pixel 2 and Ankit was able to reproduce on another Android device. Maybe Android specific? I'll track down some logs

**Comment by Lss-Ankit** [comment]
Hi @Gonza I am also not able to reproduced issue on latest build v1.0.0 (16) and previous build v1.0.0 (15) and (14). 
Verified on Device: Google pixel XL (8.1) ,Samsung Galaxy A5(7.0)
CC: @anna
