### ISSUE TITLE
Contact Mapping & Salt lookup fails during onboarding

### ISSUE THREAD

**Issue by nityas** [celo-org/celo-monorepo#4771]
### Expected Behavior

Contact Mapping should work consistently (logs sent)

### Current Behavior

Currently during onboarding, occasionally there is trouble with the

**Comment by jeanregisser** [comment]
_From @jmrossy:_
> I guess it’s a dupe of this right:
https://github.com/celo-org/celo-monorepo/issues/4764
Which seems to only happen on Android. I think we may have a bad build out there. I’ll test today with a fresh build and see if it still repros.
