### ISSUE TITLE
Bootstrap onboarding service

### ISSUE THREAD

**Issue by bowd** [celo-org/celo-monorepo#4782]
### Overview

For the fee-less attestation proposal we need to introduce a  new onboarding service that Valora will interact with as an API. This service will be responsible for gatekeeping access to the subsidy and also orchestrating meta-transaction flows in order to complete the subsidy. 

This issue is the first step in building out this service by initialising a new package in `celo-monorepo` that will hold the service and setting up the skeleton of an HTTP API according to Celo best practices.

**Comment by nategraf** [comment]
With Komenci in production, it seems that this issue should be closed. Feel free to re-open if I am wrong
