### ISSUE TITLE
Fee-less attestation flow

### ISSUE THREAD

**Issue by bowd** [celo-org/celo-monorepo#4785]
### Overview

This is the main purpose of the `Onboarding service` - running a fee-less attestation.

This flow should collect a series of signed meta-transactions constructed and execute them in a single transaction as a batch in order to complete attestations on behalf of a user's MetaTransactionWallet.

Depending on other design decisions this might also involve transferring the attestation to the user's external account.

**Comment by nategraf** [comment]
With Komenci in production, it seems that this issue should be closed. Feel free to re-open if I am wrong
