### ISSUE TITLE
Verification Prompts should not show if a user has zero balance

### ISSUE THREAD

**Issue by nityas** [celo-org/celo-monorepo#4797]
### Expected Behavior

A user should not see prompts to verify their number if they have a zero balance

### Current Behavior

- Notification shown in the home screen
- prompt to confirm number shown in send and request flows

**Comment by gnardini** [comment]
There's now also a button on the settings page to start verification we should probably hide as well:

<img width="320" alt="Screen Shot 2020-08-26 at 08 06 49" src="https://user-images.githubusercontent.com/6062888/91296578-384c4800-e773-11ea-8aa0-752d6bad9e08.png">
