### ISSUE TITLE
Valoraapp.com SEO changes part 1

### ISSUE THREAD

**Issue by aaronmgdr** [celo-org/celo-monorepo#4801]
implementing recommendations from SEO agency for Valoraapp.com

https://docs.google.com/spreadsheets/d/1oJ3qCzBXWd7cprTh6PvVNYsc3AH7OIkrtJXcLmx0TfI/edit?ts=5f501889#gid=0

**Comment by ErinHales** [comment]
Note: We should look into using Cloudinary for image optimization

**Comment by aaronmgdr** [comment]
@ErinHales  can you create a separate ticket for Cloudinary / image opt exploration?
