### ISSUE TITLE
Add About Celo Notification to first time experience

### ISSUE THREAD

**Issue by nityas** [celo-org/celo-monorepo#4807]
### Expected Behavior

[figma link](https://www.figma.com/file/zt7aTQ5wuXycIwxq5oAmF9/Wallet--Refresh?node-id=3007%3A25293) 

### Current Behavior

Intro to Celo Network does not exist

**Comment by gnardini** [comment]
@nityas A few questions :)

- I see the mock of the notification itself, but what should the "Learn More" button do?
<img width="288" alt="Screen Shot 2020-08-26 at 16 47 36" src="https://user-images.githubusercontent.com/6062888/91349566-da901e00-e7bb-11ea-92d6-318279c47640.png">

- When should this notification show up? Always after onboarding until the user interacts with it? Or should it expire at some point?
- If there are more notifications, how much priority should this notification have in terms of ordering? I assume the same as the "Learn about CELO" one?

**Comment by nityas** [comment]
not doing
