### ISSUE TITLE
Currency Display for CAD on upgrade to 1.0.0(15) inaccurate

### ISSUE THREAD

**Issue by nityas** [celo-org/celo-monorepo#4823]
### Expected Behavior

cUSD & Local Currency balance should match blockscout

### Current Behavior

 See screenshot here: https://celo-org.slack.com/archives/C013ZRXAHL1/p1598404819015100

NOTE: currently only seen once, once impacted users are known priority may be increased

**Comment by Lss-Ankit** [comment]
@nityas I have raised issue : https://github.com/celo-org/celo-monorepo/issues/4902 and it is repro for every currency hence, we can track this issue and closing ticket as per the conversion in slack: https://celo-org.slack.com/archives/CNCUN1R0D/p1598849592001300?thread_ts=1598427957.038500&cid=CNCUN1R0D. 

Thanks!
