### ISSUE TITLE
Filter Oracle metrics client-side, pilot monitoring pipeline to Grafana Cloud

### ISSUE THREAD

**Issue by rcroessmann** [celo-org/celo-monorepo#4828]
### Expected Behavior

There should be transparency around oracle client metrics by publicly available monitoring.

### Current Behavior

Currently, not oracle client data is publicly available.

**Comment by yerdua** [comment]
open questions: 
- Is there any data that should not be public?
- For the pilot of Grafana Cloud, what criteria do we use to decide whether to keep it going?
- Costs: more data is more money. How much are we willing to spend vs how much data do we need? How does this compare to existing stackdriver/gcloud dashboards?
