### ISSUE TITLE
Design doc for CP-DOTO improvements and downside risk protection

### ISSUE THREAD

**Issue by rcroessmann** [celo-org/celo-monorepo#4830]
### Expected Behavior

There should be a design doc about additional mechanism in the CP-DOTO related smart contracts that mitigate downside risk.

### Current Behavior

First ideas around additional downside protection mechanisms were discussed but never formalized.

**Comment by rcroessmann** [comment]
@albertclabs This basically is the initial step towards Mento 2.0 and I suggest we keep it around unless Mento 2.0 work is captured somewhere else already.

**Comment by albertclabs** [comment]
@rcroessmann do you feel like we should track this instead on the Economics Research board topics? Seems like some longer term research before Mento 2.0

**Comment by rcroessmann** [comment]
Yes definitely a research topic!
