### ISSUE TITLE
 “Comment Unavailable” text is shown on sent request section when user send request with adding description 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#4851]
**Frequency:** 100%
**Repro App version:**  Valora Mainnet build v1.0.0 (14), Test flight build v1.0.0 (15) 
**Does not Repro on  App version:** Test flight Valora v1.0.0(6) 
**Repro on device:** iPhone 6(12.4.7), Samsung Galaxy A5(7.0)

Pre-conditions: Make sure user has verified phone number.

**Repro Steps:**
1. Launch the Android app and sign in with a test account. 
2. Launch the iOS app and sign up. 
3. Tap on Request button
4. Select any contact
5. Enter valid amount
6. Tap on Review button
7. Tap on send button 
8. Go to home page & observe on sent notification

**Current Behavior:** Comment unavailable text is shown when user sent request adding with description 
**Expected Behavior:**  Entered description should show on sent request section
**Investigation:** Issue does not repro if user has not verified number. 
**Impact:** User not able to see entered description 
**Attachment:** [CommentUnavailable.png](https://drive.google.com/file/d/18YnB1olK5Tq4gF6itvyLcS-o59IYvAQi/view?usp=sharing)

**Comment by nityas** [comment]
Able to consistently reproduce when the requester & receiver have confirmed number, only requester sees comment unavailable

**Comment by Lss-Ankit** [comment]
Verified with latest Android internal build v1.1.0 (1004294309)& iOS test flight build v1.1.0(21) and found that issue is fixed as verified and non-verified users are able to see comment on payment request section.
