### ISSUE TITLE
Do not block enabling Review CTA in send/request flow on secure send lookup

### ISSUE THREAD

**Issue by nityas** [celo-org/celo-monorepo#4852]
### Expected Behavior

The "review" button should be enabled once a valid payment amount is input, independent of secure send completion
once cta is pressed if more time is needed to complete the secure send check, the spinner state on the button should be displayed until moving to the next screen of the send/request flow.

### Current Behavior

review button on a payment is sometimes grayed out for up to ~5s, making it unclear to the user whether changes to the amount input need to be made or the root cause of "review" not being clickable

**Comment by tarikbellamine** [comment]
I don't think this is actually a bug. This happens because we are doing a secure send check in the background and I don't see any way around that at the moment.

I am in favor of closing this.

**Comment by nityas** [comment]
@tarikbellamine Makes a lot of sense, fully agree it's not a bug but rather an enhancement. Right now this behavior is quite confusing because entering an invalid send/request amount also leads to the same disabled button result (the contrast between enabled/disabled states is also low, which is a separate problem).

Given that secure send does not determine viability of sending, rather the next state when sending, a slightly better UX could be:
- keep button enabled independent of secure send completion
- complete check (w/ spinner state on button) before moving to the next screen during flow

Thoughts on updating this issue w/ the above(or another similar) proposal?

**Comment by tarikbellamine** [comment]
I agree that would be a better experience. Originally we were expecting the time to do the check to be less than the amount of time it would take the user to enter the amount in. Can definitely see how it would be confusing if it's taking much longer than that.

I'm in favor of updating the ticket with your proposal!

**Comment by nityas** [comment]
👍 great, will update! For the record- it doesn't consistently take a long time to lookup... but I was unfortunately not able to find a reliable pre-condition for the lookup being quick/slow (if I had to guess, maybe related to whether the phone number is a contact that has been looked up or a new number).
