### ISSUE TITLE
Add Names under logos on Alliance Page

### ISSUE THREAD

**Issue by tjlahey** [celo-org/celo-monorepo#4864]
### Expected Behavior

Shows names, italicized in smaller font than the average paragraph size. 
![image](https://user-images.githubusercontent.com/3344589/91505215-e6dfae00-e883-11ea-8887-653da44c46ac.png)

### Current Behavior

What is the current behavior?
![image](https://user-images.githubusercontent.com/3344589/91383914-2ce43580-e7e2-11ea-9bf2-de691ee7b890.png)

**Comment by aaronmgdr** [comment]
@tjlahey can you add that mockup you made?
