### ISSUE TITLE
Handle large numbers better on Enter Amount Screen

### ISSUE THREAD

**Issue by coreycelo** [celo-org/celo-monorepo#4866]
### Expected Behavior

On the Send/Request Amount screen, field should handle large amount inputs better.

Design: [Figma](https://www.figma.com/file/zt7aTQ5wuXycIwxq5oAmF9/Wallet-Refresh?node-id=6500%3A0)

<img width="1081" alt="Screen Shot 2020-08-27 at 8 22 33 AM" src="https://user-images.githubusercontent.com/51388535/91462034-909c4c00-e83e-11ea-8c20-cd1c38ec345f.png">

### Current Behavior

UI breaks—text extends beyond bounds, text wraps.

![IMG_1404](https://user-images.githubusercontent.com/51388535/91462408-fdafe180-e83e-11ea-9887-713fc831dd85.png)

![IMG_1402](https://user-images.githubusercontent.com/51388535/91462397-fb4d8780-e83e-11ea-8db2-3e20cc078050.png)

![IMG_1403](https://user-images.githubusercontent.com/51388535/91462413-fe487800-e83e-11ea-9eec-8e2f1f891d5d.png)

**Comment by tarikbellamine** [comment]
Duplicate issue

**Comment by coreycelo** [comment]
Duplicate of #4960
