### ISSUE TITLE
Currency Field in QR Code should not permanently change the local currency setting

### ISSUE THREAD

**Issue by nityas** [celo-org/celo-monorepo#4869]
### Expected Behavior

localCurrency field should set the transaction amount to the local currency indicated, but outside of this transaction the user's pre-set local currency should not change

### Current Behavior

scanning a QR code in with localCurrency=PHP changes app local currency setting to PHP going forward

Impact: currently this QR/Deeplink field is only used in an isolated case, this is much more serious once the localCurrency parameter is more widely adopted

**Comment by Lss-Ankit** [comment]
Hi @nityas , i have verified issue using Test flight build v1.0.01 (17) , Android Valora Mainnet build v1.0.0 (16) and found the following: 
- Currency is change to PHP from setting when user open a valora app or scan the QR code from grameen.qa.beamandgo site. 
- Note: Issue does not repro if User B has set the PHP currency from the setting and user  A try  to send send payment via scanning QR code or number. 

Devices Used: iPhone 7+ (13.3.1) , Google pixel XL (8.1)
Attachment: [PHP_currencyIssue.mp4 ](https://drive.google.com/file/d/1VuHgMPoaXtA3UwsEykGsV7kPAd3ecF4r/view?usp=sharing)
