### ISSUE TITLE
Nothing happens when user tapping on “submit” button on confirm your contacts account page when user get back from send page 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#4876]
**Frequency:** 100%
**Repro App version:**  Valora Mainnet build v1.0.0 (16), Test flight build v1.0.0 (17) 
**Repro on device:** iPhone 6(12.4.7), Samsung Galaxy A5(7.0)
**Repro Steps:**

1. Launch the App & signi with test account
2. Tap on Send button.
3. Select user B who has two accounts with one number.
4. Enter an amount and tap on the Review button.
5. Make sure user should redirect to “Confirm your contacts account page” 
6. Tap on Confirm account number button 
7. Enter correct 4 digit & tap on submit button
8. Get back from send page 
9. Enter account number 
10. Tap on submit button & observe

 

**Investigation:** Submit button should work when user get back to ‘Please confirm your account page” again tapping on Confirm account number button 

**Current Behavior:**User not able to submit the 4 digit code by tapping on submit button  
**Expected Behavior:**  User should able to submit the 4 digit code by tapping on submit button 
**Impact:** User get blocked to submit 4 digit number and go  further once user taps on back button. 
**Attachment:** [SubmitButton.MOV](https://drive.google.com/file/d/1oGV2m-4YWSbsHRU3YawouioN69kilCkf/view?usp=sharing)

**Comment by tarikbellamine** [comment]
Closed by #4489
