### ISSUE TITLE
Send Amount screen is shown instead of “Sending” screen after scanning QR code from “Please confirm your contact’s account” screen

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#4877]
**Frequency:** 100%
**Repro App version:**  Test Flight build Valora app build  v1.0.0 (17) , Android Valora Mainnet build v1.0.0 (16)
**Does not Repro on:** Android Valora Mainnet build v1.0.0 (11)
**Repro on device:** iPhone 7+ (13.3.1), Google Pixel Xl (8.1) 
**Test Account:** 
User A : (680) 333-1978/ [Backupkey. ](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit#gid=0)
Send secure flow user B : Backup Key: (757) 699-9899. 
**Pre-condition:**
Make sure user B should have two accounts with one number to trigger a send secure flow. 
**Repro Steps:**
1. Launch the Application and sign in with user A. 
2. Tap on Send button. 
3. Enter User B number. 
4. Enter Amount on Send button. 
5. Tap on Send button. 
6. Tap on Scan QR code from “Please confirm your contact’s account” . 
7. Scan user B QR code and observe. 

**Current Behavior:** Send Amount screen is shown instead of “Sending” screen
**Expected Behavior:**  Sending screen should be shown 
**Investigation:** Issue does not repro when the user enters a 4 digit account number. 
**Impact:** User may feel frustrated that they need to enter an amount again. 
**Attachment:**[Android_QRCodeRedirectionIssue.mp4 ](https://drive.google.com/file/d/1bWXiXBOrtq6ZhY81Supv78bxvh4nGbFT/view?usp=sharing)(Bug observed at 20 sec)

**Comment by tarikbellamine** [comment]
Closed by #5090

**Comment by Lss-Ankit** [comment]
@tarikbellamine  I have verified issue on latest build Test flight build v1.2.0 (25) , Android internal build 1.2.0(1004294313) and found that issue fixed as now user is redirect to Sending screen after scanning the QR code from Please confirm your contact's account. 

**Devices used:** Google Pixel Xl (8.1) , IPhone 6+ (12.4.5)
