### ISSUE TITLE
Confirm your phone number is asked and “Matching can be done only once” error is shown  when the user taps on the “Connect” button from “Connect contacts” while signing with a verified phone number. 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#4878]
**Frequency:** 100%
**Repro App version:**  Test Flight build Valora app build  v1.0.0 (17) , Android Valora Mainnet build v1.0.0 (16)
**Repro on device:** iPhone 7+ (13.3.1), Google Pixel Xl (8.1) 
**Test Account:** [Backup Key: ](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit#gid=0)(757) 699-9899. 
Pre-condition: Users should have an account key for which they have completed the phone number verification flow. 
**Repro Steps:**
1. Launch the Application 
2. Complete the walkthrough. 
3. Tap on i have an account. 
4. Enter Full name & test phone number. 
5. Create PIN. 
6. Observe Bug1 Confirm you phone number screen is shown. 
7. Tap on the Start button. 
8. User is redirected to the Connect contact screen. 
9. Tap on “Connect” button. 
10 Observe bug2 error message. 

**Current Behavior:** Confirm your phone number is asked and “Matching can be done only once” error is shown 
**Expected Behavior:**  Confirm your phone number should not ask for a verified phone number while signing.
**Impact:** Users may get frustrated that they have verified the phone number but still phone number verification is asking while sign in. 
**Attachment:** [ConfirmPhoneNumberIssue_Signin.mp4 ](https://drive.google.com/file/d/1-5xFZ3Jh0Pal1m8aIJ22YgeAHwNSLrLd/view?usp=sharing)(bug observed at Bug #1 18 sec, Bug #2 48 sec)

**Comment by tarikbellamine** [comment]
Bug 1 has been addressed and I have opened #5099 for Bug 2.

**Comment by Lss-Ankit** [comment]
Thanks @tarikbellamine  yes bug 1 is fixed verified on latest build Test Flight build 1.2.0(25) and Android internal build 1.2.0(1004294313). 
Now, Your number is already confirmed! is shown now on Confirm phone number screen. 

Thanks for raising ticket for bug #2 #5099
