### ISSUE TITLE
Payment requests made via address are not received

### ISSUE THREAD

**Issue by tarikbellamine** [celo-org/celo-monorepo#4886]
### Expected Behavior
Payment requests work.

### Current Behavior
When making a payment request with `address` as the identifier (as opposed to phone number), requests don't appear to be received by the recipient. Appears to only happen when the requester is not verified (though unsure of this). Possibly related to #1533. 

Double checked that the address included in the request matches the recipients address.

**Comment by Lss-Ankit** [comment]
@tarikbellamine FYI, i have reopened similar issue which was filed earlier : https://github.com/celo-org/celo-monorepo/issues/1533

**Comment by tarikbellamine** [comment]
Thanks for flagging @Lss-Ankit. I will close #1533 because I believe this is actually a different issue but will update the description to reference it.

**Comment by Lss-Ankit** [comment]
okay thanks @tarikbellamine for the updates.

**Comment by nityas** [comment]
Able to reproduce with the following steps:
* clearing my main account/onboarding without verification on a new acct
* copy pasting the address (for a verified user) & requesting from them
