### ISSUE TITLE
Entered Full Name & Phone number are still shown on "i have an account"  page even when user kill and relaunch the app

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#4889]
**Frequency:** 100%
**Repro App version:**  Test Flight build Valora app build  v1.0.0 (17) , Android Valora Mainnet build v1.0.0 (16)
**Repro on device:** iPhone 7+ (13.3.1), Google Pixel Xl (8.1) 

**Repro Steps:**
1. Launch the Application 
2. Complete the walkthrough screen. 
3. Tap on create a new account. 
4. Enter Full name and Phone number. 
5. Tap on Next button. 
6. Cold launch the app 
7. Observe Entered full name & Phone number are still shown

**Current Behavior:** Entered Full Name & Phone number are still shown
**Expected Behavior:** Entered Full Name & Phone numbers should not shown after cold launching the app. 
**Investigation:** Full name & phone number is shown when user enter it while sign up and cold launch the app then navigate to sign in screen. 
**Attachment:** [Fullname&PhoneNumberIssue.mp4](https://drive.google.com/file/d/1KyzXLF0sm04vArm57NFZpwInVLoutPK2/view) (bug observe at 30 sec) :

**Comment by tarikbellamine** [comment]
This is now captured in #5040
