### ISSUE TITLE
[Web] Replace waitlist with CTAs

### ISSUE THREAD

**Issue by ErinHales** [celo-org/celo-monorepo#4923]
Update valoraapp.com
 - Remove waitlist
 - Add CTA section

Links:
 - Google Play: https://play.google.com/store/apps/details?id=co.clabs.valora
 - App Store: https://apps.apple.com/us/app/id1520414263

<img width="642" alt="Screen Shot 2020-09-01 at 12 53 01 PM" src="https://user-images.githubusercontent.com/36751902/91894247-9fc23600-ec52-11ea-8f5a-37735150be00.png">

**Comment by aaronmgdr** [comment]
Complete
