### ISSUE TITLE
Edge cases around invite code messaging 

### ISSUE THREAD

**Issue by tarikbellamine** [celo-org/celo-monorepo#4944]
### Expected Behavior
A user is able to easily view and message their invite code on a messenger of their choice after sending a successful invite transaction.

### Current Behavior
Two known edge cases:
- Non-native messenger apps (e.g., Signal) are opened but populated with blank message bodies
- Attempting to send via WhatsApp when the recipient is not a n existing user of WhatsApp returns an error

Both these edge cases result in the invite code not being viewable for the user.

Potential solution: have a fallback option when messaging fails that displays an easily copy-able invite code. Or a more holistic approach is to have somewhere in the app users can view (and potentially reclaim) sent invites.

**Comment by Lss-Ankit** [comment]
Hi @tarikbellamine FYI:  one similar bug is in open status: https://github.com/celo-org/celo-monorepo/issues/1308

**Comment by tarikbellamine** [comment]
Thank you for flagging @Lss-Ankit. I will close that issue for now as we no longer allow messaging through those channels.

**Comment by Lss-Ankit** [comment]
Okay thanks for the updates @tarikbellamine  For whats app i have tried if invited user is not in whatsApp then whatsApp gives error that user is not in whatsApp. it seems expected but when i came back to valora app, invitation fees $0.25 is cuts along with escrow payment sent. is it expected or i need to file a separate bug for the same. 
Thanks!

**Comment by tarikbellamine** [comment]
No need for a new bug, I think this will covers it.

**Comment by Lss-Ankit** [comment]
Okay @tarikbellamine thanks for the update.

**Comment by nityas** [comment]
closing out as new invite flow resolves

**Comment by Lss-Ankit** [comment]
Hi @nityas We have verified this issue on on latest Android internal build v1.6.0(1004294326) and Test Flight build v1.6.0(37) and found issue is fixed
-User is able to easily view and message their invite code on a messenger
