### ISSUE TITLE
Sending screen is not shown by tapping on the “OPEN VALORA APP” button from the “Pay With” page if the application is not running in the background. 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#4946]
**Frequency:** 100%
**Repro App version:**  Test Flight build Valora app build  v1.0.0 (17) , Android Valora Mainnet build v1.0.0 (16)
**Repro on device:** iPhone 7+ (13.3.1), Google Pixel Xl (8.1) 
**Test Account:** Backup Key: (757) 699-9899. 
**URL:** https://grameen.beamandgo.com/celo 
**Pre-conditions:** App is not running in background. 

**Repro Steps:**
1. Launch the URL and login with a test account. 
2. Navigate to the Celo page to proceed a payment. 
3. Tap on OPEN VALORA APP from Pay with page. 
4. Observe Sending screen is not shown 

**Current Behavior:** Sending screen is not shown
**Expected Behavior:**  Sending screen should show. 
**Investigation:** Issue also repro when connecting… banner is shown in the app when the user taps on OPEN VALORA APP button. 
**Impact:** User may get frustrated as they blocked to proceed for the payment 
**Attachment:** [SendingPageIssue.mp4](https://drive.google.com/file/d/1v4-pgB0_wDh7XDhYP8SbqJnWPA5nW4XL/view?usp=sharing)

**Comment by tarikbellamine** [comment]
@annakaz i think this was the deeplink issue you were mentioning this morning. assigning to you for now but maybe this belongs with @etuleu?

**Comment by annakaz** [comment]
@tarikbellamine yeah I think this is the deeplinking issue that @etuleu is looking into

**Comment by Lss-Ankit** [comment]
@etuleu Verified issue using Test flight build v1.5.1 (30) and Play store internal build 1.5.1 (1004294319) and found that issue is fixed now sending screen is shown when user taps on OPEN VALORA APP button from the pay with page if application is not running in the background.
