### ISSUE TITLE
Investigate: Plan for contractkit wrapper release process

### ISSUE THREAD

**Issue by asaj** [celo-org/celo-monorepo#4954]
We currently have no process for contractkit wrapper updates in response to contract updates. We should have one

**Comment by nambrot** [comment]
@aslawson @yorhodes feel like we should get to this one sooner than later

**Comment by aslawson** [comment]
Document process on contractkit side for how to consume releases of contracts

**Comment by yorhodes** [comment]
see https://www.notion.so/clabsco/ContractKit-release-process-48ae2b57cf004556b68986e5ffab9a00
