### ISSUE TITLE
Enter amount is overlapped on the keypad when the user enters a large amount while sending payment.

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#4960]
**Frequency:** 100%
**Repro App version:**  Android Valora Mainnet build v1.0.0 (16)
**Repro on device:** Google Pixel Xl (8.1) 
**Test Account:** Backup Key: (757) 699-9899. 
**Repro Steps:**
1. Launch the Application and sign in with test account
2. Tap on Send button. 
3. Enter a large amount. 
4. Observe. 

**Current Behavior:** Enter amount is overlapped on the keypad
**Expected Behavior:**  Amount should not overlap on keypad. 
**Investigation:** In ios, Amount is not overlapped on the keypad. 
**Attachment:** LargeAmountIssue.png 

![LargeAmountIssue](https://user-images.githubusercontent.com/55572027/92100313-45afa500-edf9-11ea-9fed-4b1648b71f84.png)

**Comment by Lss-Ankit** [comment]
Hi @tarikbellamine @gnardini I have verified this issue using latest Android Internal Build v1.4.0(1004294317) & Test Flight build v1.4.0(28) & observed that  issue is still reproduced.
**Repro on devices:** Samsung Galaxy A5(7.0) ,iPhone SE (13.5.1)
Also it is observed that in iPhone SE (13.5.1) , iPhone 7 (14.2), all entered numbers are not showing if user entered too large number.

**Comment by Lss-Ankit** [comment]
Hi @tarikbellamine @gnardini I have verified this issue using latest Android Internal Build v1.6.0(1004294325) & Test Flight build v1.6.0(36) & observed that issue is still reproduced.
**Repro on devices:** Samsung Galaxy A5(7.0) ,iPhone SE (13.5.1)
**Observation:** Also it is observed that in iPhone SE (13.5.1) , iPhone 7 (14.2), all entered numbers are not showing if user entered too large number.

**Comment by Lss-Ankit** [comment]
Hi @tarikbellamine @gnardini I have verified this issue using latest Android Internal Build v1.6.0(1004294326) & Test Flight build v1.6.0(37) & observed that issue is still reproduced.
**Repro on devices:** Samsung Galaxy A5(7.0) ,iPhone 7+ (14.1)
**Observation:** Also it is observed that in iPhone 6+ (12.4.5) , iPhone 7 (14.2), all entered numbers are not showing if user entered too large number.

**Comment by Lss-Ankit** [comment]
Hi @tarikbellamine @gnardini I have verified this issue using latest Play store Build v1.6.0 & App stoire build v1.6.0 & observed that issue is still reproduced.
**Repro on devices:** Samsung Galaxy A5(7.0) ,iPhone SE (14.2), Samsung Galaxy S4(4.4.2)
**Observation:** Also it is observed that in iPhone SE (14.2) all entered numbers are not showing if user entered too large number.

**Comment by coreycelo** [comment]
#4866 had the designs:

Design: [Figma](https://www.figma.com/file/zt7aTQ5wuXycIwxq5oAmF9/Wallet-Refresh?node-id=6500%3A0)

<img width="1081" alt="Screen Shot 2020-08-27 at 8 22 33 AM" src="https://user-images.githubusercontent.com/51388535/91462034-909c4c00-e83e-11ea-8c20-cd1c38ec345f.png">

**Comment by Lss-Ankit** [comment]
Hi @michellewong793  I have verified this issue using latest Android Internal Build V1.9.2(1004294333) & Test Flight Build V1.9.2(43) & observed that issue is still reproduced.
**Repro on devices:** Samsung Galaxy A5(7.0) ,iPhone XR (13.1.3)
**Observation:** Also it is observed that in ,iPhone XR (13.1.3) all entered numbers are not showing if user entered too large number.
