### ISSUE TITLE
Verification Error pop up is shown with “ Your current balance is not high…” description even when invited user tries to verify the phone number while on-boarding

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#4978]
**Frequency:** 100%
**Repro App version:**  Play store build v1.0.1
**Does not Repro version:** App store build v1.01, Android Valora Mainnet build v1.0.0 (16)
**Repro on device:** Google Pixel Xl (8.1) 
**Pre-condition:** User should have invited code. 
**Repro Steps:**
1. Launch the Application and complete the walkthrough  screens. 
2. Tap on create a new account and navigate to the Invite code screen. 
3. Paste the invite code. 
4. Tap on Start button
5. Observe.

**Current Behavior:** Verification Error pop up is shown 
**Expected Behavior:**  Verification error pop up should not shown for invited user as they have Invited free i.e $0.25
**Investigation:** 
- User is able to verify phone number after onboarding. 
- Issue does not repro in IOS v1.0.1. 

**Impact:** Invited user blocked to verify phone number while onboarding
**Attachment:** [Invite_0_Balanceissue.mp4](https://drive.google.com/file/d/1b46_TWs1jztfwHsQVVYp8Rxau_g6tD0I/view?usp=sharing) (Bug observe at 06 sec)

**Comment by tarikbellamine** [comment]
I believe this has been addressed.

**Comment by Lss-Ankit** [comment]
Verified with latest build Test flight build v1.2.0 (25) , Android internal build 1.2.0(1004294313) and found that issue is fixed. 

- Verification Error pop up is not shown with “ Your current balance is not high…” description when invited user tries to verify the phone number while on-boarding. 

Device used: iPhone SE (14 iOS) , samsung galaxy m40(10)
