### ISSUE TITLE
Validator UI Tests + Optimize

### ISSUE THREAD

**Issue by aaronmgdr** [celo-org/celo-monorepo#4984]
Re Write Validator UI Formatting and Calculation code so that we can run unit tests on to ensure the calculations are right. Potentially as pure functions outside of react for speed. 

Also move fetching and initial data processing to getInitialProps. So that only things that are alterable by user are re calculated on render.

**Comment by aaronmgdr** [comment]
@ErinHales  thoughts on this?

**Comment by ErinHales** [comment]
Let's do it! I was actually thinking about doing something like this after fixing the attestation score bug.
