### ISSUE TITLE
Devs SBAT Specify behavior for retroactive updates when inflationPeriod is changed

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-monorepo#499]
### Expected Behavior

Specify behavior for retroactive updates when inflationPeriod is changed -- ux implications due to drift

### Current Behavior

new inflationFactor This is computed per the present specified updatePeriod, leading to behavior where a very small updatePeriod, if applied in a scenario where the overall inflationFactor was on updated alongside the inflationParameter update, could cause this quantity to be very large.

**Comment by yorhodes** [comment]
To implement this "fairly" when the parameters are changed,  the computation/application of inflation for the prior elapsed periods should reflect the partially elapsed final inflation period before the time schedule is reset and the new parameters (period/rate) are used moving forward.

I was originally convinced that fairness meant `factor *= rate ^ ((now - factorLastUpdated) / updatePeriod)`. To do this, we needed fixed point exponentiation capabilities to implement this "fairly". Bringing in floating point approximations to fixed point exponentiation in the vm pkg in geth seemed problematic for deterministic gas costs (among other reasons cc @asaj). 

After a conversation with @mcortesi about the essence of the stability fee and inflation, he suggested that a more aligned computation would not compound the last partial inflation period. His computation pseudocode is included below for posterity.

```
periodsToApply = Math.floor((now - lastUpdated) / inflationPeriod)
perctangeOfNextPeriod = (now - lastUpdated - periodsToApply * inflationPeriod) / inflationPeriod
inflationFactor = inflactionFactor * rate^periodToApply
inflationFactor = inflactionFactor * rate * percetangeOfNextPeriod
```

Unless there are any objections, this will greatly simplify the implementation and will be the plan moving forward.

**Comment by mcortesi** [comment]
To provide some rationality around it:
First we apply the compound interest rule to the number of period that have passed:
```
inflationFactor = inflactionFactor * rate^periodToApply
```

Then, we are left with an incomplete period; let's say 40% of the period has elapsed. So the question is.. if i were to compute the inflation for 40% of a period, what would that inflation be?

To mimic what happens on a bank when you do a fixed deposit; the bank rates are stated with period=1year, and if you do a fixed deposit for a month, then compute a new interest rate which is YearlyRate/12. 

Here we should do the same...
```
incompletePeriorRate = rate * percetangeOfNextPeriod
inflationFactor = inflactionFactor * incompletePeriorRate
```
