### ISSUE TITLE
[Wallet] After upgrading to 1.1.0 app displays the enter invite code screen

### ISSUE THREAD

**Issue by jeanregisser** [celo-org/celo-monorepo#4997]
### Expected Behavior

Upgrading to 1.1.0 with an already configured account, shouldn't prompt the user to enter an invite code.

### Current Behavior

Issue was first reported by @marekolszewski in https://celo-org.slack.com/archives/CL7BVQPHB/p1599428329407100

Here are the steps to reproduce:
1. install v1.0.0
1. create new account, skip invite code
1. install v1.1.0 update
1. launch app
1. observe that the screen that opens is prompting to enter an invite code, instead of the wallet home feed with the transactions

This issue can be reproduced on iOS and Android.
It also happens when upgrading from v1.0.1 to v1.1.0

Issue does NOT reproduce when first installing v1.0.0 or v1.0.1 and restoring an existing account, and then upgrading to v1.1.0.

**Comment by jeanregisser** [comment]
I also just tested upgrading from v1.0.0 to v1.0.1 with the steps above and there was no issue.

**Comment by Lss-Ankit** [comment]
Hey @jeanregisser  I have verified this issue on both iOS & android and found the following: 
- User redirect to invite code page after upgrading v1.0.1 to v1.1.0 -Android 
- User redirect to Invite code page after upgrading to v1.0.1 to v1.1.0 - iOS. Please find the video attachment for the same.
**Note:** Open app is shown when user try to upgrade v1.0.0 to 1.1.0.
**Devices:** 
- iPhone 11 (14 beta 6)
- Samsung Galaxy A70(9.0)
**Attachment:**
- [iOS](https://drive.google.com/file/d/1wYy7MfV5Olzk5sMvt4y-vhiLGcKN9QQA/view?usp=sharing)
- [Android](https://drive.google.com/file/d/1iKuSvTDGdhqcKb3eU7wn_tKjKzvzNYh6/view?usp=sharing)

**Comment by jeanregisser** [comment]
We also need a migration for existing users on 1.0.0 / 1.0.1 to set `redeemComplete` to `true` if an account was present.

**Comment by Lss-Ankit** [comment]
I have verified this issue using Android internal build v1.1.0 (1004294309) & iOS test flight build v1.1.0(21) and found issue is fixed
**Device:** iPhone X (13.3.1), Samsung galaxy m40 (10)
