### ISSUE TITLE
[Wallet] Failed to sync after Verification Countdown + Restart

### ISSUE THREAD

**Issue by jose-compu** [celo-org/celo-monorepo#4998]
### Expected Behavior

It should continue without restarting the app (?).

### Current Behavior

Tried [Verifications] a few times, every time after the countdown I get a "Failed to sync" error with a restart button: 

`{"version":"1.0.1","buildNumber":"1004294305","apiLevel":22,"deviceId":"SC9830I","address":"0x4d1a96fa4e2ae8f9dc90ba42dd1dcf6fb20e5af5","sessionId":"","network":"mainnet"}`

https://user-images.githubusercontent.com/6062888/92254476-54549580-eea7-11ea-83a1-597478518925.png

![image](https://user-images.githubusercontent.com/30682875/92380219-0c34ad80-f109-11ea-8a71-b93ca1ec1990.png)

`========React Native Logs========
Info [2020-09-04T15:04:58.377Z] firebase/saga/Firebase initialized
Debug [2020-09-04T15:04:58.390Z] Geth@newGeth/Geth logs will be piped to /data/data/co.clabs.valora/cache/geth_logs.txt
Info [2020-09-04T15:04:58.394Z] ValoraAnalytics/Tracking event create_geth_finish with properties: {"timestamp":1599231898392,"sessionId":"88d6a9e5a88f8d4fa49727fdb303ab2b22c9642d59dfc7b6c0665bcd6313a5","userAddress":"0x4d1a96fa4e2ae8f9dc90ba42dd1dcf6fb20e5af5","celoNetwork":"mainnet"}
Info [2020-09-04T15:04:58.400Z] ValoraAnalytics/Tracking event start_geth_start with properties: {"timestamp":1599231898399,"sessionId":"88d6a9e5a88f8d4fa49727fdb303ab2b22c9642d59dfc7b6c0665bcd6313a5","userAddress":"0x4d1a96fa4e2ae8f9dc90ba42dd1dcf6fb20e5af5","celoNetwork":"mainnet"}
Debug [2020-09-04T15:04:58.408Z] FirebaseLogUploader/uploading local log file /data/data/co.clabs.valora/cache/geth_logs.txt.tmp to logs/2020-09-04/co.clabs.valora/mainnet/83f35ab69bf281bb_1599231898352_geth.txt
Debug [2020-09-04T15:04:58.420Z] FirebaseLogUploader/uploading local log file /data/data/co.clabs.valora/cache/rn_logs.txt.tmp to logs/2020-09-04/co.clabs.valora/mainnet/83f35ab69bf281bb_1599231898352_rn.txt
Info [2020-09-04T15:04:58.573Z] ValoraAnalytics/Tracking event start_geth_finish with properties: {"timestamp":1599231898572,"sessionId":"88d6a9e5a88f8d4fa49727fdb303ab2b22c9642d59dfc7b6c0665bcd6313a5","userAddress":"0x4d1a96fa4e2ae8f9dc90ba42dd1dcf6fb20e5af5","celoNetwork":"mainnet"}
Debug [2020-09-04T15:04:58.580Z] geth/saga/Geth initialized
Info [2020-09-04T15:04:58.584Z] ValoraAnalytics/Tracking event geth_init_success with properties: {"timestamp":1599231898581,"sessionId":"88d6a9e5a88f8d4fa49727fdb303ab2b22c9642d59dfc7b6c0665bcd6313a5","userAddress":"0x4d1a96fa4e2ae8f9dc90ba42dd1dcf6fb20e5af5","celoNetwork":"mainnet"}
Info [2020-09-04T15:04:58.626Z] ValoraAnalytics/Tracking event init_contractkit_geth_init_finish with properties: {"timestamp":1599231898625,"sessionId":"88d6a9e5a88f8d4fa49727fdb303ab2b22c9642d59dfc7b6c0665bcd6313a5","userAddress":"0x4d1a96fa4e2ae8f9dc90ba42dd1dcf6fb20e5af5","celoNetwork":"mainnet"}
Info [2020-09-04T15:04:58.633Z] web3/contracts@initContractKit/Initializing contractkit, forno mode: false
Info [2020-09-04T15:04:58.635Z] ValoraAnalytics/Tracking event init_contractkit_get_ipc_start with properties: {"timestamp":1599231898634,"sessionId":"88d6a9e5a88f8d4fa49727fdb303ab2b22c9642d59dfc7b6c0665bcd6313a5","userAddress":"0x4d1a96fa4e2ae8f9dc90ba42dd1dcf6fb20e5af5","celoNetwork":"mainnet"}
Debug [2020-09-04T15:04:58.642Z] web3/providers/creating IPCProvider
Debug [2020-09-04T15:04:58.645Z] web3/providers/created IPCProvider
Info [2020-09-04T15:04:58.648Z] ValoraAnalytics/Tracking event init_contractkit_get_ipc_finish with properties: {"timestamp":1599231898646,"sessionId":"88d6a9e5a88f8d4fa49727fdb303ab2b22c9642d59dfc7b6c0665bcd6313a5","userAddress":"0x4d1a96fa4e2ae8f9dc90ba42dd1dcf6fb20e5af5","celoNetwork":"mainnet"}
Info [2020-09-04T15:04:58.661Z] web3/contracts@initContractKit/Initializing wallet
Info [2020-09-04T15:04:58.666Z] ValoraAnalytics/Tracking event init_contractkit_get_wallet_start with properties: {"timestamp":1599231898663,"sessionId":"88d6a9e5a88f8d4fa49727fdb303ab2b22c9642d59dfc7b6c0665bcd6313a5","userAddress":"0x4d1a96fa4e2ae8f9dc90ba42dd1dcf6fb20e5af5","celoNetwork":"mainnet"}
Info [2020-09-04T15:04:58.674Z] ValoraAnalytics/Tracking event init_contractkit_get_wallet_finish with properties: {"timestamp":1599231898671,"sessionId":"88d6a9e5a88f8d4fa49727fdb303ab2b22c9642d59dfc7b6c0665bcd6313a5","userAddress":"0x4d1a96fa4e2ae8f9dc90ba42dd1dcf6fb20e5af5","celoNetwork":"mainnet"}
Info [2020-09-04T15:04:58.741Z] ValoraAnalytics/Tracking event init_contractkit_init_wallet_finish with properties: {"timestamp":1599231898740,"sessionId":"88d6a9e5a88f8d4fa49727fdb303ab2b22c9642d59dfc7b6c0665bcd6313a5","userAddress":"0x4d1a96fa4e2ae8f9dc90ba42dd1dcf6fb20e5af5","celoNetwork":"mainnet"}
Info [2020-09-04T15:04:58.747Z] web3/contracts@initContractKit/Initialized wallet with accounts: 0x4d1a96fa4e2ae8f9dc90ba42dd1dcf6fb20e5af5
Info [2020-09-04T15:04:58.902Z] web3/contracts@initContractKit/Initialized kit
Info [2020-09-04T15:04:58.913Z] ValoraAnalytics/Tracking event init_contractkit_finish with properties: {"timestamp":1599231898903,"sessionId":"88d6a9e5a88f8d4fa49727fdb303ab2b22c9642d59dfc7b6c0665bcd6313a5","userAddress":"0x4d1a96fa4e2ae8f9dc90ba42dd1dcf6fb20e5af5","celoNetwork":"mainnet"}
Info [2020-09-04T15:05:01.181Z] ValoraAnalytics/Tracking event drawer_navigation with properties: {"timestamp":1599231901176,"sessionId":"88d6a9e5a88f8d4fa49727fdb303ab2b22c9642d59dfc7b6c0665bcd6313a5","userAddress":"0x4d1a96fa4e2ae8f9dc90ba42dd1dcf6fb20e5af5","celoNetwork":"mainnet","navigateTo":"Help"}
Debug [2020-09-04T15:05:01.496Z] FirebaseLogUploader/uploadLogsToFirebaseStorage/Firebase logs from file 83f35ab69bf281bb_1599231898352_rn.txt uploaded successfully
Debug [2020-09-04T15:05:01.517Z] FirebaseLogUploader/uploadLogsToFirebaseStorage/Firebase logs from file 83f35ab69bf281bb_1599231898352_geth.txt uploaded successfully
Debug [2020-09-04T15:05:03.287Z] NavigationService@navigate/Dispatch SupportContact
Debug [2020-09-04T15:05:04.631Z] transactions/TransactionsList/onTxsFetched handler triggered
Debug [2020-09-04T15:05:20.890Z] transactions/TransactionsList/onTxsFetched handler triggered
Info [2020-09-04T15:05:28.687Z] geth/saga@monitorGeth :: Did not receive a block in 30000 milliseconds :: 
Debug [2020-09-04T15:05:34.624Z] transactions/TransactionsList/onTxsFetched handler triggered
Debug [2020-09-04T15:05:39.748Z] geth/saga@monitorGeth/Received new chain head 17280 produced at Thu Apr 23 2020 13:30:07 GMT-0300
Debug [2020-09-04T15:05:39.820Z] web3/saga/checkWeb3SyncProgress, Checking sync progress
Debug [2020-09-04T15:05:39.825Z] geth/saga@trackConnectionStatus/Connection status transitioned to connected = true
Info [2020-09-04T15:05:39.827Z] ValoraAnalytics/Tracking event network_connected with properties: {"timestamp":1599231939826,"sessionId":"88d6a9e5a88f8d4fa49727fdb303ab2b22c9642d59dfc7b6c0665bcd6313a5","userAddress":"0x4d1a96fa4e2ae8f9dc90ba42dd1dcf6fb20e5af5","celoNetwork":"mainnet","fornoMode":false}
Debug [2020-09-04T15:05:39.866Z] geth/saga@trackSyncStatus/Chain head has -11572472862 ms to expiration
Info [2020-09-04T15:05:39.939Z] ValoraAnalytics/Tracking event network_sync_start with properties: {"timestamp":1599231939937,"sessionId":"88d6a9e5a88f8d4fa49727fdb303ab2b22c9642d59dfc7b6c0665bcd6313a5","userAddress":"0x4d1a96fa4e2ae8f9dc90ba42dd1dcf6fb20e5af5","celoNetwork":"mainnet","currentBlock":2315520,"highestBlock":2331471,"knownStates":0,"pulledStates":0,"startingBlock":0}
Debug [2020-09-04T15:05:40.394Z] web3/saga/checkWeb3SyncProgress, Sync maybe complete, checking
Debug [2020-09-04T15:05:40.399Z] web3/utils/Getting latest block
Debug [2020-09-04T15:05:46.317Z] transactions/TransactionsList/onTxsFetched handler triggered
Debug [2020-09-04T15:05:50.581Z] web3/saga/checkWeb3SyncProgress, Sync is complete
Info [2020-09-04T15:05:50.583Z] ValoraAnalytics/Tracking event network_sync_finish with properties: {"timestamp":1599231950582,"sessionId":"88d6a9e5a88f8d4fa49727fdb303ab2b22c9642d59dfc7b6c0665bcd6313a5","userAddress":"0x4d1a96fa4e2ae8f9dc90ba42dd1dcf6fb20e5af5","celoNetwork":"mainnet","latestBlock":2331472}
Debug [2020-09-04T15:05:51.789Z] geth/saga@monitorGeth/Received new chain head 2331473 produced at Fri Sep 04 2020 12:05:06 GMT-0300
Debug [2020-09-04T15:05:51.848Z] geth/saga@trackSyncStatus/Chain head has 14154 ms to expiration
Debug [2020-09-04T15:05:58.208Z] transactions/TransactionsList/onTxsFetched handler triggered
Debug [2020-09-04T15:05:59.894Z] geth/saga@monitorGeth/Received new chain head 2331479 produced at Fri Sep 04 2020 12:05:36 GMT-0300
Debug [2020-09-04T15:06:04.438Z] Toast/Creating combined log...

========Geth Logs========
ERROR[09-04|15:04:58.416] Failed to enumerate USB devices          hub=ledger vendor=11415 failcount=1 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[09-04|15:04:58.417] Failed to enumerate USB devices          hub=trezor vendor=21324 failcount=1 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[09-04|15:04:58.418] Failed to enumerate USB devices          hub=trezor vendor=4617  failcount=1 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[09-04|15:04:58.419] Failed to enumerate USB devices          hub=ledger vendor=11415 failcount=2 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[09-04|15:04:58.421] Failed to enumerate USB devices          hub=trezor vendor=21324 failcount=2 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[09-04|15:04:58.421] Failed to enumerate USB devices          hub=trezor vendor=4617  failcount=2 err="failed to initialize libusb: libusb: unknown error [code -99]"
WARN [09-04|15:04:58.448] Found deprecated node list file /data/data/co.clabs.valora/files/.mainnet/celoandroid/static-nodes.json, please use the TOML config file instead. 
INFO [09-04|15:04:58.455] Starting peer-to-peer node               instance=celoandroid/v1.0.0-unstable/android-arm/go1.13.5
INFO [09-04|15:04:58.455] Allocated cache and file handles         database=/data/data/co.clabs.valora/files/.mainnet/celoandroid/lightestchaindata cache=16.00MiB handles=16
INFO [09-04|15:04:58.485] Writing custom genesis block 
INFO [09-04|15:04:58.497] Persisted trie from memory database      nodes=46 size=9.37KiB time=2.044678ms gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=-116.00B
INFO [09-04|15:04:58.503] HASH2                                    hash=19ea33…bd11c3
INFO [09-04|15:04:58.503] Initialised chain configuration          config="{ChainID: 42220 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 0 Engine: istanbul}"
INFO [09-04|15:04:58.504] Open roundstate db                       func=newRoundStateDB type=roundStateDB rsdb_path=
INFO [09-04|15:04:58.527] Loaded most recent local header          number=0 hash=19ea33…bd11c3 td=1 age=4mo2w23h
INFO [09-04|15:04:58.530] Checkpoint registrar is not enabled 
WARN [09-04|15:04:58.556] Light client mode is an experimental feature 
INFO [09-04|15:04:58.563] New local node record                    seq=4 id=2f25fc4a83f38f41 ip=127.0.0.1 udp=0 tcp=59622
INFO [09-04|15:04:58.564] Started P2P networking                   self="enode://4b6ba20365dcc8c49cf970e6c958b0219f143c6514e3453fee4fecc9092a617221a5c7b7af856d30c6afbf2da120c26139e82c47904cf76de472b5ff25f2c236@127.0.0.1:59622?discport=0"
INFO [09-04|15:04:58.571] IPC endpoint opened                      url=/data/data/co.clabs.valora/files/.mainnet/geth.ipc
INFO [09-04|15:04:59.220] Block synchronisation started 
ERROR[09-04|15:04:59.423] Failed to enumerate USB devices          hub=ledger vendor=11415 failcount=3 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[09-04|15:04:59.424] Failed to enumerate USB devices          hub=trezor vendor=21324 failcount=3 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[09-04|15:04:59.425] Failed to enumerate USB devices          hub=trezor vendor=4617  failcount=3 err="failed to initialize libusb: libusb: unknown error [code -99]"
INFO [09-04|15:05:03.210] Mapped network port                      proto=tcp extport=59622 intport=59622 interface="UPNP IGDv1-IP1"
INFO [09-04|15:05:39.718] Imported new block headers               count=134 elapsed=33.344s number=2315520 hash=516406…663a53 age=22h9m58s
INFO [09-04|15:05:39.969] Upgrading chain index                    type=bloombits    percentage=0
INFO [09-04|15:05:40.373] Imported new block headers               count=2   elapsed=403.137ms number=2331472 hash=c05d64…541825
INFO [09-04|15:05:47.998] Upgrading chain index                    type=bloombits    percentage=1
INFO [09-04|15:05:50.395] Disconnecting from static or trusted peer id=87b69ac8c9434bd4 conn=staticdial static=ExplicitStaticPurpose trusted= reason="useless peer" remoteRequested=false err="useless peer"
INFO [09-04|15:05:51.763] Imported new block headers               count=6   elapsed=1.173s    number=2331478 hash=adfd10…487b40
INFO [09-04|15:05:52.764] Imported new block headers               count=0   elapsed=967.590ms number=2331478 hash=adfd10…487b40 ignored=6
INFO [09-04|15:05:52.772] Disconnecting from static or trusted peer id=edead527638e5adb conn=staticdial static=ExplicitStaticPurpose trusted= reason="useless peer" remoteRequested=false err="useless peer"
INFO [09-04|15:05:53.719] Imported new block headers               count=0   elapsed=945.709ms number=2331478 hash=adfd10…487b40 ignored=6
INFO [09-04|15:05:53.728] Disconnecting from static or trusted peer id=36dc4a88f449c720 conn=staticdial static=ExplicitStaticPurpose trusted= reason="useless peer" remoteRequested=false err="useless peer"
INFO [09-04|15:05:54.494] Imported new block headers               count=0   elapsed=762.908ms number=2331477 hash=1771b6…858714 ignored=5
INFO [09-04|15:05:54.503] Disconnecting from static or trusted peer id=87b69ac8c9434bd4 conn=staticdial static=ExplicitStaticPurpose trusted= reason="useless peer" remoteRequested=false err="useless peer"
INFO [09-04|15:05:55.505] Imported new block headers               count=0   elapsed=1.001s    number=2331478 hash=adfd10…487b40 ignored=6
INFO [09-04|15:05:56.004] Upgrading chain index                    type=bloombits    percentage=1
INFO [09-04|15:05:56.351] Imported new block headers               count=0   elapsed=839.477ms number=2331477 hash=1771b6…858714 ignored=5
INFO [09-04|15:05:56.356] Disconnecting from static or trusted peer id=36dc4a88f449c720 conn=staticdial static=ExplicitStaticPurpose trusted= reason="useless peer" remoteRequested=false err="useless peer"
INFO [09-04|15:05:56.365] Disconnecting from static or trusted peer id=42ba0aa81a8f4dfa conn=staticdial static=ExplicitStaticPurpose trusted= reason="useless peer" remoteRequested=false err="useless peer"
INFO [09-04|15:05:57.248] Imported new block headers               count=0   elapsed=881.408ms number=2331477 hash=1771b6…858714 ignored=5
INFO [09-04|15:05:57.891] Imported new block headers               count=0   elapsed=632.049ms number=2331476 hash=78a58d…9aea31 ignored=4
INFO [09-04|15:05:57.895] Disconnecting from static or trusted peer id=01c092500489752b conn=staticdial static=ExplicitStaticPurpose trusted= reason="useless peer" remoteRequested=false err="useless peer"
INFO [09-04|15:05:57.896] Disconnecting from static or trusted peer id=1279c461707c8ef9 conn=staticdial static=ExplicitStaticPurpose trusted= reason="useless peer" remoteRequested=false err="useless peer"
INFO [09-04|15:05:57.898] Disconnecting from static or trusted peer id=42ba0aa81a8f4dfa conn=staticdial static=ExplicitStaticPurpose trusted= reason="useless peer" remoteRequested=false err="useless peer"
INFO [09-04|15:05:58.694] Imported new block headers               count=0   elapsed=792.938ms number=2331477 hash=1771b6…858714 ignored=5
ERROR[09-04|15:05:58.700] Failed to unregister sync peer           peer=1279c461707c8ef91bd56003c1dba178ca03335b753b41a9b0503ce2212692d4 err="peer is not registered"
INFO [09-04|15:05:58.700] Disconnecting from static or trusted peer id=1279c461707c8ef9 conn=staticdial static=ExplicitStaticPurpose trusted= reason="useless peer" remoteRequested=false err="useless peer"
WARN [09-04|15:05:58.701] Unable to request etherbase from peer    id=1279c461707c8ef9 conn=staticdial err="shutting down"
INFO [09-04|15:05:58.706] Disconnecting from static or trusted peer id=edead527638e5adb conn=staticdial static=ExplicitStaticPurpose trusted= reason="useless peer" remoteRequested=false err="useless peer"
WARN [09-04|15:05:58.898] Unable to request etherbase from peer    id=42ba0aa81a8f4dfa conn=staticdial err="shutting down"
INFO [09-04|15:05:59.353] Imported new block headers               count=0   elapsed=650.512ms number=2331476 hash=78a58d…9aea31 ignored=4
INFO [09-04|15:05:59.361] Disconnecting from static or trusted peer id=a21715b607d4cf35 conn=staticdial static=ExplicitStaticPurpose trusted= reason="useless peer" remoteRequested=false err="useless peer"
INFO [09-04|15:05:59.361] Disconnecting from static or trusted peer id=01c092500489752b conn=staticdial static=ExplicitStaticPurpose trusted= reason="useless peer" remoteRequested=false err="useless peer"
WARN [09-04|15:05:59.702] Unable to request etherbase from peer    id=1279c461707c8ef9 conn=staticdial err="shutting down"
INFO [09-04|15:05:59.877] Imported new block headers               count=3   elapsed=515.594ms number=2331481 hash=2046a9…505f06
INFO [09-04|15:06:00.578] Imported new block headers               count=1   elapsed=693.725ms number=2331482 hash=b17688…d10f43 ignored=3
INFO [09-04|15:06:00.584] Disconnecting from static or trusted peer id=a21715b607d4cf35 conn=staticdial static=ExplicitStaticPurpose trusted= reason="useless peer" remoteRequested=false err="useless peer"
WARN [09-04|15:06:00.902] Unable to request etherbase from peer    id=42ba0aa81a8f4dfa conn=staticdial err="shutting down"
WARN [09-04|15:06:01.586] Unable to request etherbase from peer    id=a21715b607d4cf35 conn=staticdial err="shutting down"
INFO [09-04|15:06:01.627] Imported new block headers               count=1   elapsed=200.103ms number=2331483 hash=c51163…1e0435
WARN [09-04|15:06:01.704] Unable to request etherbase from peer    id=1279c461707c8ef9 conn=staticdial err="write tcp 192.168.0.8:52239->34.83.23.77:30303: use of closed network connection"
WARN [09-04|15:06:03.587] Unable to request etherbase from peer    id=a21715b607d4cf35 conn=staticdial err="shutting down"
INFO [09-04|15:06:04.042] Upgrading chain index                    type=bloombits    percentage=1
INFO [09-04|15:06:04.080] Imported new block headers               count=1   elapsed=235.809ms number=2331484 hash=a35650…6e7683
`

### Notes

Reported by @gnardini 

Link to support: https://groups.google.com/a/clabs.co/g/support/c/rHxxfFuIcwk/m/KkLtyYBCCgAJ

**Comment by i1skn** [comment]
@gnardini is the app otherwise working fine (sending funds, etc.)?

**Comment by gnardini** [comment]
This was a while back and it hasn't happened since, might have been fixed by something else or maybe it was just a connection issue. I didn't test other features since I was going through this just to test verifications with different carriers if it ever happens again I will make sure to test other stuff too.

**Comment by i1skn** [comment]
Ok, I'm closing this one then, re-open if it occurs again.
