### ISSUE TITLE
[Wallet] Data Pasted from Clipboard when loading app

### ISSUE THREAD

**Issue by jose-compu** [celo-org/celo-monorepo#4999]
### Expected Behavior

Do not paste anything from external apps. Is this maybe a hack to get some network environment values from the Browser?

### Current Behavior

It was noticed on iOS beta 14.0 that whenever the Valora app is started it copies the last value from the clipboard. Kind of alarming from the security point of view, screenshot attached. 

{"version":"1.0.1","buildNumber":"17","apiLevel":-1,"deviceId":"iPhone12,3","address":"0x07f329fbf15a7107c03c7993e60f97880e2fbaed","sessionId":"","network":"mainnet"}

![image](https://user-images.githubusercontent.com/30682875/92383136-11482b80-f10e-11ea-8756-eef618a0364d.png)

### Notes

Support threads: 

https://groups.google.com/a/clabs.co/g/support/c/3O_KvorKFQo
https://groups.google.com/a/clabs.co/g/support/c/vm4izaEZF-U

**Comment by tarikbellamine** [comment]
Included in #4835
