### ISSUE TITLE
“Not enough CELO…” message is shown when the user Buy/Sell with the whole available amount. 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#5004]
**Frequency:** 100%
**Repro App version:**  Test Flight build Valora app build  v1.1.0 (18) & v1.0.1 (17) 
**Does not repro version:** Play store build v1.1.0 
**Repro on device:** iPhone 7+ (13.3.1)
**Does not repro devices:** Google Pixel XL  (8.1) 

**Test Account:** Backup Key: (757) 699-9899. 
**Repro Steps:**
1. Launch the Application and sign in with test account
2. Tap on the hamburger menu. 
3. Tap on CELO option. 
4. Tap on BUY button. 
5. Tap on Switch to USD. 
5. Make user has available balance i.e 0.10. 
6. Enter amount 0.10 and observe. 

**Current Behavior:** “Not enough CELO…” message is shown
**Expected Behavior:**  Users should be able to Buy and Sell with available balance. 
**Investigation:** Issue also repro when user sending cUSD
**Impact:** User is not able to Buy / Sell with the whole available balance. 
**Attachment:** [Buy&SellIssue.mp4 ](https://drive.google.com/file/d/1EP8G3Tu3-OQOIq0rxeAiFpLhVqo7lOt9/view?usp=sharing)(Bug observe at 10 sec)

**Comment by tarikbellamine** [comment]
Maybe this is because of the transaction fees involved? If so, might be helpful to have a more descriptive error message

**Comment by ValoraQA** [comment]
Hi @gnardini I have verified this issue using latest Test Flight Build V1.11.1(48) & Android Internal Build V1.11.1(1004294339) & observed that issue is still reproduced.
**Verified on Devices:** Samsung Galaxy A5(7.0), iPhone SE (14.2)

**Comment by ValoraQA** [comment]
Hi @gnardini We have verified this issue on latest android internal build V1.15.2 & Testflight build V1.15.2 and found issue is fixed so, we are closing this ticket.
Devices: iPhone 6+ (12.4.5) , Vivo V11 pro (10)
