### ISSUE TITLE
Devs SBAT create governance proposal to upgrade changed contracts

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-monorepo#501]
### Expected Behavior

Detect changes, deploy new contracts, create a governance proposal that repoints proxies at new contracts.  

### Current Behavior

Governance now owns Proxy contracts, so `yarn run upgrade` no longer works to upgrade contract changes on specified network. (The script at `packages/protocol/scripts/truffle/upgrade.ts` is outdated, as it assumes the `MultiSig` contract is deployed. However, we don't deploy it anymore, so the script breaks.)

**Comment by yorhodes** [comment]
2 options:
1. use hotfixes
2. use governance proposals

Analysis:
- hotfixes have fewer timing dependencies compared to governance proposal phases
- hotfixes might seem centrally unilateral from an optics perspective

Concrete steps:
1. migrate functionality from protocol upgrade script to contractkit for constructing proxy logic update transaction
2. add functionality to contractkit Governance wrapper for <encoding/hashing> transaction and submitting <proposal/hotfix>
3. add validator commands to CLI for interacting with governance <hotfix/proposals>
4. migrate functionality from protocol upgrade script to <celotool> for detecting changes between network bytecode and local bytecode and performing upgrade via CLI/contractkit

**Comment by yorhodes** [comment]
closing due to #2142 being merged
