### ISSUE TITLE
[Wallet] Valora sometimes crashes after hitting review to send payment in Android (1.1.0)

### ISSUE THREAD

**Issue by annakaz** [celo-org/celo-monorepo#5010]
### Expected Behavior

User able to send payment without app crashing

### Current Behavior

For at least one user, after restoring from backup key, the app crashes when sending to users who are in their contact list. This was not happening before restoring from backup key. This does not occur when sending to an address, or when sending to a phone number that is not in their contact list

See issue report here: https://groups.google.com/a/clabs.co/g/support/c/vZEkwSC_vu8

Video included in logs

**Comment by tarikbellamine** [comment]
Fixed by #5012
