### ISSUE TITLE
Phone number verification CTA is shown when the user spent all cUSD after receiving it. 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#5018]
**Frequency:** 100%
**Repro App version:**  Test Flight build Valora app build  v1.1.0 (20) , Android Valora Mainnet build v1.1.0 (1004294308)
**Repro on device:** iPhone 7+ (13.3.1), Google Pixel Xl (8.1) 
**Test Account:** Backup Key: (757) 699-9899. 
**Repro Steps:**
1. Launch the Application and sign in with test account
2. Make sure the user has balance and phone number CTA is shown. 
3. Spent cUSD by sending another member or Buy CELO. 
4. Make sure users have 0 cUSd balance now. 
5. Observe. 

**Current Behavior:** Phone number verification CTA is shown
**Expected Behavior:**  Phone number verification CTA should disappeared 
**Investigation:** 
CTA is not shown when users sign up with 0 balance.
“Your balance is not high enough...” is shown when the user taps on CTA. 
**Impact:** Users are able to see CTA with 0 balance. 
**Attachment:** [CTA_Phonenumber.mp4](https://drive.google.com/file/d/1l0LNnKx1fuWqUGIrsZ0u3jaIGcfx5u3c/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
@jeanregisser @i1skn i have verified issue again on latest build Android internal build v1.1.0 (1004294309)& iOS test flight build v1.1.0(21) and found that following: 
- Continuous loading indicator is shown when user taps on tap on phone number CTA when user has 0 Balance. 

Attachment: [Continuous indicator issue.mp4](https://drive.google.com/file/d/1Qf-pNTT6CFzCiHkT2YkYgr8V947ry8ku/view?usp=sharing)

**Comment by tarikbellamine** [comment]
@i1skn not sure if this has been addressed yet so assigning to you

**Comment by Lss-Ankit** [comment]
Hi @tarikbellamine I have verified this issue using latest Android internal build v1.3.0(1004294316) & Test Flight build v1.3.0(27) and found issue is fixed
**Repro on devices:** iPhone 6+(12.4.5), Vivo V11 pro (10)
