### ISSUE TITLE
Add copy to the bottom of add/withdraw screen indicating that there are additional withdraw options

### ISSUE THREAD

**Issue by nityas** [celo-org/celo-monorepo#5021]
### Expected Behavior

Add footnote to Add/Withdraw screen with the following info:
EN: “For more ways to add and withdraw funds, visit [How to fund your account]”
ES: "Para obtener más formas de agregar y retirar fondos, visite [Cómo depositar fondos en cuenta]"

The link points to valorrapp.com/fund-wallet.

Design: [Figma](https://www.figma.com/file/zt7aTQ5wuXycIwxq5oAmF9/Wallet-Refresh?node-id=3571%3A3793)

![Cash In and Out Landing](https://user-images.githubusercontent.com/51388535/92633601-db2eb700-f287-11ea-8b33-b867bcb67528.png)

### Current Behavior

What is the current behavior?

**Comment by coreycelo** [comment]
Added design.

**Comment by gnardini** [comment]
Is there a spanish version of https://valoraapp.com/fund-wallet or is English the only one? Just to know if I use the same link in both languages or a different one.

**Comment by nityas** [comment]
same link right now unfortunately -- no spanish version yet :/
