### ISSUE TITLE
Continuous loading indicator is shown when the user taps on the Review button from the Request screen if the user has 0 balance. 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#5072]
**Frequency:** 100%
**Repro App version:**  Test Flight build Valora app build  v1.1.0 (21) , Android Valora Mainnet build v1.1.0 (1004294309)
**Repro on device:** iPhone 7+ (13.3.1), Google Pixel Xl (8.1) 

Pre-condition: user should have 0 balance. 
**Repro Steps:**
1. Launch the Application and sign up with a test account. 
2. Tap on the Request button. 
3. Tap on search fields and search any user. 
4. Tap on Searched user. 
5 Enter an amount and tap on the review button. 
6. Observe. 

**Current Behavior:**  Continuous loading indicator is shown 
**Expected Behavior:**  User should be able to request to any user with 0 balance. 
**Investigation:** Your balance is low to complete this process message is shown when user taps on contact user from request screen if balance is 0. 
**Impact:** user is blocked to send payment request with 0 balance. 

**Attachment:**[RequestWith0Balance.mp4 ](https://drive.google.com/file/d/1uyrqh4H-cNx4wkLzyfukxft2sGii2l-I/view?usp=sharing)(Bug observed at 13 sec)

**Comment by Lss-Ankit** [comment]
Hi @tarikbellamine I have verified this issue using latest Android internal build v1.3.0(1004294316) & Test Flight build v1.3.0(27) and observed issue is still repro.
**Repro on devices:** iPhone 6+(12.4.5), Vivo V11 pro (10)

**Comment by ValoraQA** [comment]
Hi @tarikbellamine  I have verified this issue using latest Test Flight Build V1.11.1(48) & Android Internal Build V1.11.1(1004294339) & observed that issue is still reproduced.
**Verified on Devices:** Samsung Galaxy A5(7.0), iPhone SE (14.2)

**Comment by ValoraQA** [comment]
Hi @tarikbellamine we have verified this issue on latest android internal build V1.15.2 & Testflight build V1.15.2 and found issue is fixed.
- User should able to proceed to request even if user has 0 balance 
**Devices:** iPhone 6 + (12.4.5), Vivo V11 pro (10).
