### ISSUE TITLE
 “Importing wallet failed” error message is shown when user sign in with account key after “Reset Valora” app

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#5077]
**Frequency:** 100%
**Repro App version:**  Android Valora Mainnet build v1.1.0 (1004294309)
**Does not repro on App version**  Test Flight build Valora app build  v1.1.0 (21) 
**Repro on device:** Samsung Galaxy A70(9.0)
**Test Account:** Backup Key:(650) 777-7647. 
**Repro Steps:**

1. Launch the Application and sign in with a test account 
2. Go to setting page 
3. Reset valora
4. Walk through tutorials 
5. Tap on i have an account 
6. Enter same phone number 
7. Paste account key 
8. Tap on restore button 
9. Observe 

**Current Behavior:** Importing wallet failed error message is shown when user sign in with account key after reset valora 
**Expected Behavior:**  User should able to login by using account key 
**Investigation**:
1.  User is able to sign in with account after reinstall the app 
2. Users are able  to create an account after resetting the Valora app. 

**Impact:** User get blocked to login after reset Valora app. 
**Attachment:** [ImportingWalletFailed.mp4](https://drive.google.com/file/d/13kA5wRJGgv1uw0ilSzZsyZGsc5kPMiGB/view?usp=sharing) (Bug observed at 37 sec)

**Comment by tarikbellamine** [comment]
This should be fixed by #5062. Please monitor and reopen if still an issue in newest build.

**Comment by Lss-Ankit** [comment]
@tarikbellamine We have verified this issue using Android Valora Mainnet build v1.1.0 (1004294311) and found issue fixed 
"User is able to signin using account key after reset valora app" 
**Device:** Samsung Galaxy A70(9.0)
