### ISSUE TITLE
SDK SNBAT conditionally import packages

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-monorepo#508]
### Expected Behavior

Nice solution for different environments

### Current Behavior

React Native does not support conditional imports, so we have to find a workaround for this
https://github.com/react-native-community/discussions-and-proposals/issues/120

**Comment by timmoreton** [comment]
@cmcewen @mcortesi @ashishb do we still need to do this?

**Comment by mcortesi** [comment]
No
