### ISSUE TITLE
Devs SBAT use signing code with proper dependencies declared located in the SDK

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-monorepo#509]
### Expected Behavior

Signing code has dependencies declared, proper imports, works everywhere it is used

### Current Behavior

node_modules imports, no underscore dependency declared, multiple copies of signing-utils

**Comment by timmoreton** [comment]
@mcortesi @ashishb is this still a problem?

**Comment by mcortesi** [comment]
Not sure what this is. But since we are doing everything brand new I would close it
