### ISSUE TITLE
Users SBAT delegate voting and validating rights via a CLI

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-monorepo#511]
### Expected Behavior

We support these features via CLI

### Current Behavior

Rewards delegation is implemented under `bonds` command, voting and validating should go elsewhere

**Comment by diminator** [comment]
I can take this

**Comment by diminator** [comment]
Currently rewards delegation is under `celocli lockedgold:rewards -d`. Is that where it should be (ie not under `bonds`)? @timmoreton

**Comment by diminator** [comment]
I'm assuming that for vote delegation the command 
`celocli validatorgroup:vote` requires a `--delegate,-d` flag?

Or is this refering to `LockedGold.delegateRole`?
