### ISSUE TITLE
Users SNBAT see deprecation warnings when using CLI

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-monorepo#512]
### Expected Behavior

Suppressed output

### Current Behavior

![Screen Shot 2019-07-08 at 12 16 06 PM](https://user-images.githubusercontent.com/3020995/60836359-60957380-a17a-11e9-8f86-97618417ce8f.png)

**Comment by yorhodes** [comment]
![image](https://user-images.githubusercontent.com/3020995/64584375-138c7400-d35a-11e9-9dc4-58db116fd4ed.png)
No longer getting this behavior so I am closing.
