### ISSUE TITLE
 Update Clipboard for iOS 14

### ISSUE THREAD

**Issue by gnardini** [celo-org/celo-monorepo#5120]
iOS 14 brought a new API for the clipboard which we need to implement

### Expected Behavior

A notification shouldn't appear every second on iOS 14+ when on a screen with an input where we can paste.

### Current Behavior

A notification appears every second.

**Comment by Lss-Ankit** [comment]
Hi @tarikbellamine i have verified task using Test flight build v1.2.0 (24) and found the following:
Device: iPhone 11 (14iOS)

Test scenarios:

Verify user is able to paste the copied text in valora app
verify "Valora pasted from ###" message should show when user any copied text 
Verify notification should appear only once after pasting 

Please let me know if any thing else i need to verify for this task.
Thanks !
