### ISSUE TITLE
celocli should be tagged upon every release and README code references should point to tagged src

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-monorepo#514]
### Expected Behavior

Code references in README:
https://github.com/celo-org/celo-monorepo/blob/<tag>/src/commands/bonds/rewards.ts

### Current Behavior

Code references in README:
https://github.com/celo-org/celo-monorepo/tree/master/src/commands/bonds/rewards.ts

**Comment by timmoreton** [comment]
@mcortesi @ashishb do we still need to do this?

**Comment by mcortesi** [comment]
@timmoreton we need to tag each npm package version in the github repo.
This is hard to do with our current publish & PR merge strategies.

How do we deploy today?

 1. Start a branch
 2. run `yarn publish` (this updates package.json and can also create a git tag)
 3. send pr (& hope it's the first one to be merged)
 4. squash and merge (& loss any git history/tag)

So, we need a better process for publishing packages, and be able to use git tags

What can we do?

cc @ashishb @jmrossy
