### ISSUE TITLE
Users SBAT prefix identifiers for use in the Attestations contract

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-monorepo#515]
### Expected Behavior

We want to use the Attestations contract mostly independent of phone numbers. Therefore, ideally the identifier base for hashing/encryption would be prefixed with `tel:`

### Current Behavior

We currently just use the phone number itself as the base for the hash and encryption.

**Comment by nambrot** [comment]
@nityas @jmrossy Can you remind us again why we punted this? It was something about the contact list, right?

**Comment by jmrossy** [comment]
@nambrot Just cause it was wrapped up in the conversion to scrypt which was punted. We could do this if we need it.

**Comment by jmrossy** [comment]
Was done as part of PGPNP
