### ISSUE TITLE
“Skip for now” button is shown instead on “Resume” & “I already received three codes” buttons on Confirm page when user tap on < button from Confirm Code pasting page 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#5166]
**Frequency:** 100%
**Repro App version:**  Android Valora Mainnet build v1.1.0 (1004294311), Test Flight build Valora app build  v1.1.0 (223) 
**Repro on device:** iPhone 11 (14 iOS), Pixel 3a (11)
**Repro Steps:**

1. Launch the Application and sign in with a test account 
2. Make sure user should able to see the “Receive payments directly to your phone number” notification in home page 
3. Tap on confirm Now button 
4. Tap on start button 
5. Make sure user should receive 3 code
6. Tap on < button on confirm pasting code page 
7. Observe skip for now button is shown 

**Investigation:** Resume & i already received three codes buttons is shown when user go back and and again tap on confirm button 

**Current Behavior:** “Skip for now” button is shown when user tap on < button from Confirm code roasting page 
**Expected Behavior:** Resume & i already received three codes buttons should show when user tap on < button from confirm pasting code page 

**Attachment:** [ResumeButtons.mp4](https://drive.google.com/file/d/1exYXcJcR2V0zdPdrEilBUUImtLBveCAY/view?usp=sharing) (Bug observed at 1:48 )

**Comment by Lss-Ankit** [comment]
Hi @i1skn I have verified this issue using latest Android internal build v1.5.5(1004294323) & Test Flight Build v1.5.5(34) & observed that:-

-  Start button is displaying instead of Resume button when user interrupts phone number confirmation while timer is going on.
**Repro on Devices:** Samsung Galaxy A5(7.0), iPhone SE (13.5.1)
**Attachment:**  [ResumeButtonIsNotDisplaying.mp4](https://drive.google.com/file/d/1S_MmRVRSiGcC2_ihbMC7GXj7Jnt6OdTO/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
Hi @i1skn I have verified this issue using Play store  build v1.5.5 & App store build v1.5.5& observed that issue is still reproduced.

**Repro on Devices:** Samsung Galaxy A5(7.0), iPhone SE (13.5.1)

**Comment by Lss-Ankit** [comment]
Hi @i1skn I have verified this issue using latest Android internal build v1.6.0(1004294325) & Test Flight Build v1.6.0(36) & observed that issue is still reproduced.
**Repro on Devices:** Samsung Galaxy A5(7.0), iPhone SE (13.5.1)

**Comment by i1skn** [comment]
I can not reproduce it on 1.6.0 on Android. When I press back icon on top - I see the screen with `Resume` button. Is there anything else I should be doing in additional to general onboard flow?

**Comment by Lss-Ankit** [comment]
'Hi @i1skn I have verified this issue using latest Android internal build v1.6.0(1004294325) & Test Flight Build v1.6.0(36) & observed that "Start" button displayed instead of "Resume" when user interrupts phone number confirmation. Please refer attachment. 
Repro on Devices: Samsung Galaxy A5(7.0), iPhone SE (13.5.1)
Attachment: [ResumeButtonNOtDisplaying.mp4 ](https://drive.google.com/file/d/1rQjhiJhPgv-AeWrifPo29Zd3n8L58AOo/view?usp=sharing)

**Comment by i1skn** [comment]
Oh, I got it, so the original `5. Make sure user should receive 3 code` is not present in this scenario. 
This is expected then, but @nityas can you confirm that this behaviour is alright? When user cancels before hitting enter codes screen?

**Comment by Lss-Ankit** [comment]
Hi @i1skn I have verified this issue & observed following observations.
**Observations:**
- If we interrupt confirmation while timer is going on then we able to see "Start" button instead of Resume.
- If we interrupt confirmation on paste 3 verification page then we able to see "Resume" button.
Let me know is first point expected??

**Comment by nityas** [comment]
Just weighing in-- if user has already received/requested codes and goes back to the screen, we would expect to see "Resume"; if they have not requested any codes yet, seeing "start" or "resume" would be acceptable (a slight preference for resume showing if they have ever been to the timer screen but either functionality is OK)

**Comment by Lss-Ankit** [comment]
Hi @nityas Thanx for giving more information about this ticket. So, we are closing this ticket.
