### ISSUE TITLE
Comment field on Blockchain should have a size limit

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-monorepo#521]
### Expected Behavior

Comment size should be limited on blockchain to avoid potential abuse. Starting with say 1024 bytes would be a safe bet. And we can increase it later if required.

### Current Behavior

Comment sizes are not limited, for example, https://github.com/celo-org/celo-monorepo/blob/master/packages/protocol/contracts/stability/StableToken.sol#L136

**Comment by galihmelon** [comment]
Hello, I'd like to contribute on this issue. Would this be fixed by changing the type of comment from `string` to `bytes1024` in  https://github.com/celo-org/celo-monorepo/blob/master/packages/protocol/contracts/stability/StableToken.sol file?
