### ISSUE TITLE
Docs should have its own analytics

### ISSUE THREAD

**Issue by aaronmgdr** [celo-org/celo-monorepo#5215]
Right now docs.celo.org and celo.org share the same google analytics tracking ID. I think we should create a separate tracking ID for docs as combining them makes the data muddy. for instance / on both is as far as i can tell not differentiated. the home page for both websites are counted together. Also things like average page load time get get distorted.

**Comment by AlexBHarley** [comment]
Closing, context [here](https://celo-org.slack.com/archives/C01V5UXJ6RY/p1625676793054400)
