### ISSUE TITLE
Upgrade React Native and remove iOS 14 patch

### ISSUE THREAD

**Issue by tarikbellamine** [celo-org/celo-monorepo#5248]
### Expected Behavior
We are using the latest React Native package. Lots of cool new features like "pressables". Latest version has a fix for iOS 14 so the patch we've applied `react-native+0.62.2.patch` is no longer needed.

### Current Behavior
Using a slightly outdated version of React Native.

**Comment by tarikbellamine** [comment]
#5967 upgrades RN so all that should remain is removing the iOS 14 patch and testing

**Comment by jeanregisser** [comment]
Fixed by #5967
