### ISSUE TITLE
Leading 0 is automatically added to some international phone numbers + update Google phone lib package

### ISSUE THREAD

**Issue by tarikbellamine** [celo-org/celo-monorepo#5260]
### Expected Behavior
We should either keep the package from auto-completing with a 0 or let the user know that it's not something to worry about. It is probably also worthwhile to update the google-lib package to the latest release.

### Current Behavior
Appears that the package adds a 0 prefix to some international numbers when it shouldn't. Appears to largely be a display issue because the user still correctly receives the verification texts and is able to redeem from escrow.

https://celo-org.slack.com/archives/C018VLA3YAK/p1601038063011900
https://celo-org.slack.com/archives/CL7BVQPHB/p1601660582120600

**Comment by jeanregisser** [comment]
We got another report for Russian numbers.
Example with the following number: `+79991234567`
The user selects "Russia" in the countries list and then enters `9991234567`
This ends up automatically formatting the number as `+7 8 (999) 123-45-67` in the phone number input.

Problem is we concatenate both the phone country code and the `NATIONAL` formatting, which works for US (or some other countries) but is incorrect and confusing for others like reported.

https://github.com/celo-org/celo-monorepo/blob/66cdc5a6bd34cd0957e968d599e223cccaf6496e/packages/react-components/components/PhoneNumberWithFlag.tsx#L27

Note that during input we should probably accept the `NATIONAL` form like we do today, but we should find a way to avoid the surprising experience where the auto formatting adds extra digits which are only relevant nationally.

And for display we should probably always use the `INTERNATIONAL` format everywhere to avoid confusion.
Though we must also consider contacts which are only entered in `NATIONAL` form ;)

See playground with google's `libphonenumber`:
https://runkit.com/embed/vqxg9mqvuu9n

**Comment by tarikbellamine** [comment]
@jeanregisser i believe i've captured the display issue with this [existing ticket](https://github.com/celo-org/celo-monorepo/issues/5261)

**Comment by Lss-Ankit** [comment]
I have verified this issue using latest Android internal build V1.7.2(1004294329) & Test Flight build V1.7.2(39) & observed following:

- If we enter US number & change country code from US to India then automatically 0 comes before whole number & next button enables
- But now if we change country code from India to US then automatically 0 not removed & also Next button shown disable
**Verified on devices:** Samsung Galaxy A5(7.0), iPhone 8(14.2)
**Attachment:** [Automatically0Added.mp4](https://drive.google.com/file/d/1pJ9QgNRyY_0QS3ieF-R3Ae8GGBiMQ25J/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
I have verified this issue using latest Android internal build V1.7.2(1004294329) & Test Flight build V1.7.2(39) & observed some more following observations:

- If we enter Argentina number number & tap on Next button then automatically 9 comes at start of number when user taps on Next button on Account info screen.
- Also same issue observed that for South Africa 0 comes automatically at start of number.

**Comment by Lss-Ankit** [comment]
I have verified this issue using Android Internal Build V1.9.1(1004294332) & Test Flight Build V1.9.1(42) & observed following:
**Observation:** 
- It is observed that phone number changes automatically while login with Germany number when user taps on X button on keyboard.
Attachment: [NumberChnagesAutomaticallyForGermany.mp4](https://drive.google.com/file/d/1RAVhHNrXbGi8FhtB7aB25ZjDLXGuq6KM/view?usp=sharing)
**Verified on devices:** Samsung Galaxy A5(7.0)
