### ISSUE TITLE
Blank fields is shown on First & second Confirm code fields when user go back and return to confirm page. 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#5267]
**Frequency:** 100%
**Repro App version:**  Test Flight build Valora app build  v1.2.0 (25), Android internal build Android internal build 1.2.0(1004294313) 
**Repro on device:** iPhone 11 (14 iOS), Samsung Galaxy A70(9.0)
**Repro Steps:**
1.Launch the Application 
2.Signin with test account
3.Make sure sure should able to see Receive payments directly to your phone number notification
4.Tap on Confirm button 
5.Tap on start button
6.Make sure user should get 3 codes
7.Copy paste first & Second codes 
8.Tap on Resend 1 code button
9.Make sure confirm page should open after resending code
10.Observe First & second code fields 

**Investigation:** Posted code is shown on First & second field when user paste the code for first time 

**Current Behavior:** Blank fields is shown on First & second Confirm code fields when user go back and open confirm

**Expected Behavior:** Pasted code should show on respective code fields when user go back and open confirm page

**Attachment:** [BlankFields.PNG](https://drive.google.com/file/d/1gCVc6LHo9WfX0iPR9n-ERR6xmoRlCs1l/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
Hi @gnardini we have verified issue with latest Android play store internal build v1.3.0(1004294316) & Test Flight build v1.3.0(27) and found that issue is still repro.

- Blank fields is shown on First & second Confirm code fields when user go back and return to confirm page.
Device used: Google Pixel XL (8.1) , iPhone SE 2 (13.5)

**Comment by ValoraQA** [comment]
Hi @i1skn  I have verified this issue using latest Test Flight Build V1.11.1(48) & Android Internal Build V1.11.1(1004294339) & observed that issue is fixed now. Both field displayed with pasted code when user get back to Confirm page.
Verified on Devices: Samsung Galaxy A5(7.0), iPhone SE (14.2)
**Attachment:** [BothFiledDisplayedWithCode.mp4](https://drive.google.com/file/d/1tGTh-KSOFhoM-9v07RguPrOQjdEBQZfC/view?usp=sharing)

**Comment by ValoraQA** [comment]
HI @jeanregisser @gnardini We have verified this issues on latest app store build 1.11.1 and observed the following.
- Blank fields is shown on confirm code fields when user skip the verification flow after pasting codes & get back to confirm page by tapping on confirm button on in-app verification.
**Frequency:** 70%
Repro steps:
- Go through on-boarding flow 
- Paste 2 codes [Verification error is show for sometimes after pasting codes]
- Skip the flow
- Tap on confirm now button on in-App notification
- Tap on "Resume" button
- Observed fields is shown blank
[Attachment:](https://drive.google.com/file/d/1FQwZ-5VLyhyU_XOrWTFVk_mhdhDlcSPi/view?usp=sharing)

Can you please let us know we need to open new issues for this.
