### ISSUE TITLE
Exchange amounts should not be represented in scientific notation

### ISSUE THREAD

**Issue by tarikbellamine** [celo-org/celo-monorepo#5271]
### Expected Behavior
Amounts are not represented in scientific notation.

### Current Behavior
Amounts are sometimes represented in scientific notation when there are many decimals. This results in an "invalid number value" error.

https://sentry.io/organizations/celo/issues/1936609246/?project=1250733

**Comment by gnardini** [comment]
I can't reproduce this and on Sentry there appears to be only 1 user. Wondering if it's really a P1 given the low number of affected users.

**Comment by jeanregisser** [comment]
Small note, we also usually need to limit to 18 decimals when passing to a smart contract.
