### ISSUE TITLE
Hitting "Back" on the PIN flow does not gracefully cancel the transaction

### ISSUE THREAD

**Issue by nityas** [celo-org/celo-monorepo#5276]
### Expected Behavior

Backing out of the PIN flow should cancel the current transaction (instead of proceeding with the transaction and then showing a tx failure)

### Current Behavior

cancelling from the pin navigates to the same screen as success, then shows a failed transaction (noticed in verification)

**Comment by tarikbellamine** [comment]
@nityas this feels more like a P2 or P3 to me. Given the impact is on the UX rather than incorrect functionality, I'd reduce prioritization on this because we've already got a very crowded 1.3 bug list and Milestone 7 is shaping up to be very busy.

What do you think?
