### ISSUE TITLE
Receipt of a CELO transfer should display a push notification

### ISSUE THREAD

**Issue by nityas** [celo-org/celo-monorepo#5278]
### Expected Behavior

Push notification should be shown for any CELO receipt

### Current Behavior

no push notification

**Comment by Lss-Ankit** [comment]
Hi @nityas I have verified this issue using using Test Flight build 1.2.0(25) and Android internal build Android internal build 1.2.0(1004294313) and not able to repro 
- Push notification is shown to UserA when UserB send celo to UserA
**push Notification in iOS:**
- Received celo is not shown on push notification 
**push Notification in Android:**
-  Received celo is shown on push notification 

**Attachment:** [PushNotification.PNG](https://drive.google.com/file/d/12WuhvKJwuSKjMc4HvINqwe4t-tTM9LsQ/view?usp=sharing)

**Comment by jeanregisser** [comment]
I'm successfully receiving push notifications for received CELO transfers here too with Valora 1.2 on iOS. Closing this.
