### ISSUE TITLE
Push notifications should be displayed in the receiving user's local currency

### ISSUE THREAD

**Issue by nityas** [celo-org/celo-monorepo#5280]
### Expected Behavior

received transactions should be denominated in PHP/MXN/etc

### Current Behavior

received transactions are denominated in Celo Dollars

**Comment by Lss-Ankit** [comment]
FYI @nityas  we already have similar issue #2725 and #2153

**Comment by nityas** [comment]
Amazing, thanks! closing out @Lss-Ankit
