### ISSUE TITLE
New QR Code Designs

### ISSUE THREAD

**Issue by nityas** [celo-org/celo-monorepo#5281]
### Expected Behavior

New Feature (cc @coreycelo could you add)
Deeplinking (vlra.app shortlinks):
* when sharing QR code, a shortlink should redirect the user to
-> if app not installed: play/app store
-> if app installed: app w/ pre-filled recipient (same as QR code deeplink)

### Current Behavior

n/a

**Comment by coreycelo** [comment]
Is this distinct from #4567?

**Comment by nityas** [comment]
oops, great catch, closing.
