### ISSUE TITLE
Back arrow of Pin screen not working after initiating verification through the in-app notification

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#5289]
**Frequency:** 100%
**Repro App version:**  Test Flight build 1.2.0(25), Android internal build 1.2.0(1004294313)
Does not Repro App version:   Test Flight build 1.1.0(23)
**Repro on device:** iPhone 11 (14 iOS), Google Pixel xl2
**Test Account:** Backup Key: 4704658594
**Precondition:** 
User should have atleast of 0.02Usd in the wallet.
User should try to confirm Phone number from the in-app notification screen 3-4 times.
**Repro Steps:**

1. Launch the Application 
2. Signin with test account
3. Tap on Confirm now button from Phone number verification in-app notification screen
4. User will be redirected to Enter Pin screen tap on “<” arrow 
5. Observe user is stuck in Enter Pin screen.

**Current Behavior:** User not redirecting to home page when user tap on Back button on enter pin page from Confirm phone number In-app notification > Confirm button
**Expected Behavior:** User should be redirected back to Home screen by tapping on < arrow from Enter Pin screen.
**Attachment:** [StuckinEnterPinscreenwhileConfirmPhonenumber.Mp4](https://drive.google.com/file/d/1cGxN5xLF2SXKQ6YdxskneKZL59KgYFGu/view?usp=sharing)

**Comment by gnardini** [comment]
Fixed by #6002

**Comment by Lss-Ankit** [comment]
@gnardini  Verified issue with Android  internal build V1.7.2(1004294329) &Test Flight build V1.7.2(39) and found that issue is fixed 

- User is redirected to Home screen by tapping on Back < arrow from Enter PIN screen when user taps on Confirm now button from in app notification 

Devices: iPhone SE 2 (14.2) , Google Pixel Xl (8.1)
