### ISSUE TITLE
Sent to Ethereum wallet and it doesn't show up

### ISSUE THREAD

**Issue by bamaemail** [celo-org/celo-monorepo#5305]
My destination wallet support said this:

"In your Ballet App, you can only add ERC20 coins manually. You may have seen Celo or CGLD in the search list because this coin may have been previously 
an ERC20 coin that has now migrated to its mainnet. Another thing to note is that ERC20 coins are not unique. Some ERC20 coins share the same ticker. 
With this, before adding the coin manually and making a deposit, you have to confirm the contract address of the ERC20 coin and add the coin according 
to the correct contract address. Hope this clarifies. As mentioned previously, you can recover your Celo coins by decrypting the private key of your 
Ballet wallet on https://www.balletcrypto.org and you can import your Celo coins to a wallet/platform that can support Celo. After successfully decrypting 
the wallet, you will see the ETH address on the left side and you will see the corresponding ETH Private Key WIF Compressed/Private Key (Hex) on the right side.
For you to recover your Celo coin, you can copy the Private Key WIF Compressed/Private Key (Hex) of your ETH wallet and use this and import your Celo coin 
from your Ballet wallet to another wallet that supports Celo."

I have decrytped, and I have the private key, but coinbase won't allow be to import the private key so I can send it back to my coinbase wallet.

Can you help?
Thank you

**Comment by bamaemail** [comment]
Token: Celo
Amount: 1046.32
To: 0x896C724357Fba8D6E9F53F3A280719ff3B6aBdCc
Hash: 0xcbd6879ba27c099cc770408b20cb0f731110a0815dcd2dd1ef51662bfa63843c
Date: 10/6/2020

**Comment by dominiquejane** [comment]
@bamaemail We have instructions for recovering your funds from an ETH wallet in this doc [here](https://docs.celo.org/celo-holder-guide/eth-recovery).

**Comment by bamaemail** [comment]
This ask for a 24 word recovery phrase I only have the private keys. How does that work. Thank you

Sent from bob@bama.email

Monday, October 12, 2020, 3:09 PM -0500 from notifications@github.com  <notifications@github.com>:

**Comment by dominiquejane** [comment]
@bamaemail If you already have your private key, then I think you should be able to skip the first two steps ("Prepare your recovery phrases" and "Recover your Ethereum address on Celo") and go straight to the next steps.

**Comment by bamaemail** [comment]
Thank you for trying to help, but I have no idea on how to do any of that. Is there something you can send me so I can enter my private key and get my celo back.

Sent from bob@bama.email

Monday, October 12, 2020, 7:01 PM -0500 from notifications@github.com  <notifications@github.com>:

**Comment by dominiquejane** [comment]
@bamaemail Unfortunately, we don't have a user interface for this. I can walk you through the process but it's a bit lengthy. Answer these questions so I can help you get started:
Do you have a computer and if so, what is your computer's operating system?
Have you ever used the terminal or command line interface before?

**Comment by bamaemail** [comment]
bob@bama.email
Microsoft Windows 10 Home
No

Thank you for helping me

Sent from bob@bama.email

Monday, October 12, 2020, 8:13 PM -0500 from notifications@github.com  <notifications@github.com>:

**Comment by dominiquejane** [comment]
@bamaemail I have sent you an email with instructions. We'll continue our discussion there.

Closing this issue.
