### ISSUE TITLE
Developers SBAT use a generic slashing interface on BondedDeposits

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-monorepo#532]
### Expected Behavior

Validator stakes should be confiscated under slashing conditions

Design proposal [here](https://docs.google.com/document/d/1f79e1Kiz3BbeTKdCvZLzf9bE6kPl7JPqc001ZsMZ5LA/edit#heading=h.vclsg6twr41l).

### Current Behavior

No slashing

**Comment by asaj** [comment]
Dupe
