### ISSUE TITLE
cLabs engineers SBAT reference a process for testnet governance proposals

### ISSUE THREAD

**Issue by nambrot** [celo-org/celo-monorepo#5344]
### Expected Behavior

There is a well defined process/run book that mirrors stakeholders on Mainnet so that no single person is single point of failure.

### Current Behavior

No process/runbook

**Comment by aslawson** [comment]
Can use this to start
https://docs.google.com/document/d/15x0mlMysHzaeG1Vtwy2iy7-2QoVujua86S_dvJ2_-1o/edit#heading=h.2jnnmdp12t18

**Comment by nambrot** [comment]
Thanks @aslawson!

**Comment by nambrot** [comment]
Updated @aslawson 's document
