### ISSUE TITLE
[Valora] UX Improvements for Re-request

### ISSUE THREAD

**Issue by aslawson** [celo-org/celo-monorepo#5373]
Discussions for improvements TBD

**Comment by aslawson** [comment]
@i1skn Do you know if the first issue is already complete here?

RE: issue "Better re-requesting attestation UX" -- this is assuming that user failures during this request phase are significant. Updates in handling transactions and komenci have been pushed in the latest version showing that drop off during this phase due to error, cancelation, and app close is low (8% drop between `verification_request_all_attestation_start` and `verification_request_all_attestation_complete` from test users)

[data visual here](https://metabase.celo-networks-dev.org/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJxdWVyeSIsInF1ZXJ5Ijp7InNvdXJjZS10YWJsZSI6MjAyLCJhZ2dyZWdhdGlvbiI6W1sic3VtIixbImZpZWxkLWlkIiwyMDE5XV0sWyJzdW0iLFsiZmllbGQtaWQiLDIwMjBdXSxbInN1bSIsWyJmaWVsZC1pZCIsMjAxN11dLFsic3VtIixbImZpZWxkLWlkIiwyMDE1XV0sWyJzdW0iLFsiZmllbGQtaWQiLDIwMTZdXSxbInN1bSIsWyJmaWVsZC1pZCIsMjAyMV1dXSwiYnJlYWtvdXQiOltbImZpZWxkLWlkIiwyMDE4XV0sImZpbHRlciI6WyJhbmQiLFsiPSIsWyJmaWVsZC1pZCIsMjAyNF0sIjEuMy4wIl1dfSwiZGF0YWJhc2UiOjEwfSwiZGlzcGxheSI6ImJhciIsInZpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnsiZ3JhcGguZGltZW5zaW9ucyI6WyJzdGVwIl0sImdyYXBoLm1ldHJpY3MiOlsic3VtIiwic3VtXzIiLCJzdW1fMyIsInN1bV80Iiwic3VtXzUiLCJzdW1fNiJdLCJzdGFja2FibGUuc3RhY2tfdHlwZSI6Im5vcm1hbGl6ZWQiLCJzZXJpZXNfc2V0dGluZ3MiOnsic3VtXzIiOnsidGl0bGUiOiJTa2lwcGVkIn0sInN1bV80Ijp7InRpdGxlIjoiQXBwIENsb3NlZCJ9LCJza2lwcGVkIjp7ImNvbG9yIjoiIzUwOUVFMyJ9LCJhcHBfY2xvc2VkIjp7ImNvbG9yIjoiI0E5ODlDNSJ9LCJzdW1fNiI6eyJ0aXRsZSI6IlRpbWVvdXQifSwic3VtXzMiOnsidGl0bGUiOiJDYW5jZWwifSwiY2FuY2VsIjp7ImNvbG9yIjoiI0Y5RDQ1QyJ9LCJ0aW1lb3V0Ijp7ImNvbG9yIjoiI0YyQTg2RiJ9LCJzdW0iOnsidGl0bGUiOiJTdWNjZXNzIn0sInN1bV81Ijp7InRpdGxlIjoiRXJyb3IifX0sInN0YWNrYWJsZS5zdGFja19kaXNwbGF5IjoiYmFyIiwiZ3JhcGguc2hvd192YWx1ZXMiOnRydWUsImdyYXBoLnlfYXhpcy5hdXRvX3NwbGl0IjpmYWxzZX0sIm9yaWdpbmFsX2NhcmRfaWQiOjI4MX0=)

@nityas what are your thoughts on the priority of this item. we had it at P1 commit, but didn't do it with lack of certainty around the data and its necessity. I would say in general, its a nice optimization for the user experience, but its necessity is still unclear until we have REAL user data on the latest versions of Valora.

**Comment by i1skn** [comment]
I'm not sure I understand correctly what is exactly the first issue here?

**Comment by aslawson** [comment]
@i1skn "Notification to confirm number should change to “resume verification” if the process has already started"
^ is there any place that we still have "start verification" listed instead? I'm assuming this is referring to the scrollable cards at the top of the home screen.

**Comment by i1skn** [comment]
What you've suggested in Slack make sense for me, so to move it to the Milestone 8 and label it with `P2`.
