### ISSUE TITLE
Standardize geth logging verbosity & redeploy if needed

### ISSUE THREAD

**Issue by tkporter** [celo-org/celo-monorepo#5376]
* Decide upon a default verbosity for all geth nodes
* Redeploy/reconfigure all geth nodes to use this default verbosity
* Look at log lines / minute being sent to SD and identify any high verbosity services. Consider reducing verbosity for problem resources.

**Comment by trianglesphere** [comment]
Standardized on verbosity 2. Upgraded tests & .env files
