### ISSUE TITLE
Developers SBAT use *Contract as opposed to Truffle.Contract<*Instance> type in tests

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-monorepo#540]
### Expected Behavior

We use the `*Contract` types generated by typechain everywhere in our tests

### Current Behavior

We use the `Truffle.Contract<*Instance>` type instead

**Comment by jeamick** [comment]
Hello @timmoreton ,

Could you please give details about which test are you talking about ?
I would be interested to look a bit at this issue if possible.

Thanks
JM

**Comment by timmoreton** [comment]
@jeamick Hey! @asaj can give you some more context

**Comment by jeamick** [comment]
hey @timmoreton  and @asaj ,
By a quick research I found some examples of what you are describing in this part of the repository:

https://github.com/celo-org/celo-monorepo/tree/master/packages/protocol

are you talking about this ?

By the way is there a reason why it was like this ?
Convenience?

Thanks
JM

**Comment by asaj** [comment]
Happy to provide more context!

This is really just a readability issue, and not a functional difference. Typechain creates contract specific types for us, so we might as well use them, but the types should be functionally the same, just with a more readable name.
