### ISSUE TITLE
ContractKit Wrapper Updates for Release 1

### ISSUE THREAD

**Issue by ewilz** [celo-org/celo-monorepo#5408]
As new changes to the Celo Core Contracts are being deployed to all the testnets + Mainnet, the contractKit wrappers need to be updated to be able to use these changes.

- [x] New `Exchange` functions
- [x] `Attestations` transferring
- [x] `Governance getVoteRecord` new signature

**Comment by jmrossy** [comment]
@emaG3m Can you add some details here? I was about to open an issue for the Exchange wrapper being out of date with @tkporter's latest changes in #4580 but I guess this covers that?

**Comment by nambrot** [comment]
@jmrossy This epic should indeed cover that. There are also some `Attestations` changes that we should add to the wrappers
