### ISSUE TITLE
Reinstate estimated exchange rate UI interaction

### ISSUE THREAD

**Issue by nityas** [celo-org/celo-monorepo#5414]
[not a 1.3 blocker]

### Expected Behavior

prior to redesign, exchange rates were presented as an estimate due to expected shifts; this functionality should be reinstated

### Current Behavior

dropped as of redesign

**Comment by calrobertlee** [comment]
[Figma Link](https://www.figma.com/file/zt7aTQ5wuXycIwxq5oAmF9/Wallet-Refresh?node-id=9368%3A695) of design iterations for this issue.  4 different version
