### ISSUE TITLE
Push notifications for payment requests are not received

### ISSUE THREAD

**Issue by jeanregisser** [celo-org/celo-monorepo#5416]
### Expected Behavior

Push notifications for cUSD payments requests should be visible in the Notification Center of the device when the app is closed.

### Current Behavior

Push notifications for cUSD payments requests  aren't received (app closed) on iOS (didn't check Android).
This was tried on Valora 1.2 on iOS.

**Comment by nityas** [comment]
closing as a duplicate of https://github.com/celo-org/celo-monorepo/issues/1339
