### ISSUE TITLE
Implement Cash Out and add more Cash In/Out Providers

### ISSUE THREAD

**Issue by jeanregisser** [celo-org/celo-monorepo#5424]
### What's important about this? 

Users should have an easy way of getting value into and out of Valora. Valora currently only supports Cash In with Moonpay and has no Cash Out providers. This epic includes the work required to Cash Out, which will involve sending a cUSD transaction to the Cash Out provider. It also includes adding additional providers (Simplex, and Flexa and Wyre if they are ready) once the integrations are ready. 

### Definition of done

**Cash out flow:** The wallet supports Cash Out with cUSD using a provider's Webview. This will involve sending a cUSD transaction to the Cash Out provider. It is unclear exactly what this flow (need design) will be - whether it will require leaving the webview to approve a transaction - more detail to come from Simplex. 

**New providers:** As new providers like Simplex (expected by October 31) and others are added, their webview is added to the Cash In/Out screen. Just adding them in the same way Moonpay is displayed - no additional changes to this flow. 

Out of scope: working with providers to support integration (that work falls under DevEx this milestone), labeling transactions from providers in the transaction feed, local currency support in the Cash In/Out flow, cUSD/CELO automatic conversions if only CELO available

Open question: is CELO Cash Out support needed, or can it be cUSD only? 

Blocker for GA: we need at least 1 Cash-In provider for cUSD and 1 Cash-Out provider for cUSD

**Comment by annakaz** [comment]
### What's important about this? 

Users should have an easy way of getting value into and out of Valora. Valora currently only supports Cash In with Moonpay and has no Cash Out providers. This epic includes the work required to Cash Out, which will involve sending a cUSD transaction to the Cash Out provider. It also includes adding additional providers (Simplex, and Flexa and Wyre if they are ready) once the integrations are ready. 

### Definition of done

**Cash out flow:** The wallet supports Cash Out with cUSD using a provider's Webview. This will involve sending a cUSD transaction to the Cash Out provider. It is unclear exactly what this flow will be - whether it will require leaving the webview to approve a transaction - more detail to come from Simplex. 

**New providers:** As new providers like Simplex (expected by October 31) and others are added, their webview is added to the Cash In/Out screen. Just adding them in the same way Moonpay is displayed - no additional changes to this flow. 

Out of scope: working with providers to support integration (that work falls under DevEx this milestone), labeling transactions from providers in the transaction feed, local currency support in the Cash In/Out flow, cUSD/CELO automatic conversions if only CELO available

Open question: is CELO Cash Out support needed, or can it be cUSD only?

**Comment by annakaz** [comment]
Update: while the wallet team was under the impression that Simplex would support Cash Out by October 31, it seems the original agreement was that they would support Cash In by October 31. It's unclear what the timeline for Simplex to offer Cash Out is or whether this would be ready in time to be integrated into Valora for GA. 

cc @nityas
