### ISSUE TITLE
Improve CELO Cash In experience

### ISSUE THREAD

**Issue by jeanregisser** [celo-org/celo-monorepo#5425]
### What's important about this? 

Users cashing in with CELO have been confused as they do not receive a notification or see their cUSD balance update. This epic improves the experience of cashing in with CELO. 

### Definition of done

Users receive notifications when they receive CELO, and CELO balance is listed in drawer when it is greater than zero.

**Comment by annakaz** [comment]
CP-DOTO changes moved to https://github.com/celo-org/celo-monorepo/issues/5444

**Comment by jeanregisser** [comment]
Taking this given, I've done part of this for PH changes in #5444

**Comment by jeanregisser** [comment]
Push notification issue is when the TX is a native CELO TX which doesn't call the ERC20 smart contract.

See discussion in https://celo-org.slack.com/archives/C01A2839V7G/p1603990253003300

**Comment by annakaz** [comment]
Depends on https://github.com/celo-org/blockscout/issues/172
