### ISSUE TITLE
Integration support for feeless attestation

### ISSUE THREAD

**Issue by jeanregisser** [celo-org/celo-monorepo#5426]
### What's important about this?

Feeless attestation is a blocker for GA. We want to be sure the integration with the wallet is optimal.

### Definition of "done"

Feeless attestation is integrated and fully functional.

### What's involved in doing this work?

- Help review PR related to feeless attestation
- Give input when needed
- Help write unit/e2e tests needed
- Thorough test of each delivered PR related to feeless attestation 

### Open questions

- ?

**Comment by gnardini** [comment]
The work on this is done for now :)
