### ISSUE TITLE
Reduce celocli size

### ISSUE THREAD

**Issue by barbaraliau** [celo-org/celo-monorepo#5439]
### Expected Behavior

Should be able to install celocli on AWS `t2.micro` instance (free trial), or other similarly specced VMs

### Current Behavior

VM crashes during celocli installation. RAM might be the issue. 
`yarn` process halts and then the VM is unreachable by ssh until reboot

**Comment by barbaraliau** [comment]
**Proposed Solution**

* Determine minimum spec requirements goal for celocli
* Reduce dependencies
* Cut new release

**Open Questions**
* What dependencies can be cut?
* Does this depend on ContractKit modularization (I'm guessing yes)?
* What is a reasonable spec requirement?
* Should we include this in M7 CLI epic?

**Comment by medhakothari** [comment]
Yah I think this should definitely be addressed for the cli, thanks for making the issue! 

How much would the contractkit modularization solve this? From what I see on the [modularization PR](https://github.com/celo-org/celo-monorepo/pull/4790), seems like the cli would need access to most of the new proposed packages, such as extenders, communication, wallet libraries, etc, so not sure how much bundle size would be reduced from that front. 
@gastonponti do you have more information here?

**Comment by gastonponti** [comment]
@medhak1 you are right. It basically uses all the packages, so unless we decide to for example, remove the HSM wallet as a possibility, probably this PR won't impact on the cli size

**Comment by gastonponti** [comment]
For example, if we could think more of the things required to be use in these kind of instances, and maybe make a light-cli, with just the basics, and supporting only one wallet.

**Comment by martinvol** [comment]
I personally experienced this but it'd be great that someone else confirms it too.

**Comment by barbaraliau** [comment]
I think a celocli-lite version would be great. It would solve a lot of the
bundle size issues.

**Comment by aslawson** [comment]
Closed related ticket: [Improve celocli install time #579](https://app.zenhub.com/workspaces/devx-backlog-board-6009f3d1a7a39b001018f159/issues/celo-org/celo-labs/579)

**Comment by aaronmgdr** [comment]
#6193 should go a long way to fixing this as
