### ISSUE TITLE
[Protocol Economics] Economics design for another fiat-pegged stable asset

### ISSUE THREAD

**Issue by yerdua** [celo-org/celo-monorepo#5443]
### What's important about this?

We ultimately want to be able to support multiple stable assets, that can be added via governance. Currently, there are aspects of the protocol and economics that assume only one stable token. In preparation for adding more stable assets, we need a better understanding of what the economics should look like, and the work involved in doing this.

### Definition of done

There is a design doc detailing what the economics should look like. 
Note: this is an exploratory epic and should be timeboxed to at most 2 weeks.

**Comment by clrblmt** [comment]
Open questions to be addressed:
- What happens we have different "interest" rates on these assets? Will this cause stability issues?
- How do we implement it?

**Comment by clrblmt** [comment]
Based on recent discussions with cLabs go to market team we should plan to add >1 additional stable asset (suggestion is 3 tbc)
Anticipated assets (subject to change and gov proposals) cBRL, cEUR, cCFA, or cPHP

**Comment by nvtaveras** [comment]
A lot of exploratory work around this was done in M7 so I'm closing in favour of #6162
