### ISSUE TITLE
CLI Bugfixes and Release

### ISSUE THREAD

**Issue by barbaraliau** [celo-org/celo-monorepo#5504]
**Output**
Close >= 5 issues. Minor release 0.0.59

**Comment by barbaraliau** [comment]
Maybe issue #3994 and #3998? #5439

**Comment by medhakothari** [comment]
Removed #3994 and #3998 because they seem a bit dated

**Comment by YazzyYaz** [comment]
Worked on this on Friday: https://github.com/celo-org/celo-monorepo/issues/5713
Will test the solution this week, was having compiling issues before.
