### ISSUE TITLE
Celo: <Bought CELO using COINBASE PRO and TRANSFER to NANO S Ledger under ETHER account

### ISSUE THREAD

**Issue by knowblockchain** [celo-org/celo-monorepo#5576]
*Bought CELO CGLD on 10/16/2020 a total of 202.46 units CELO (mainnet) to the Ledger ETH account. I used COINBASE account and TRANSFER to NANO S Ledger to my ETHER account. Of course, I realized later that the transfer did not happen. After contacted LEDGER they recommend me to reach out CELO and say HELP... . What is/are the possible solutions for this issue?*
thanks

**Comment by barbaraliau** [comment]
Please see this guide: https://docs.celo.org/celo-owner-guide/eth-recovery

**Comment by knowblockchain** [comment]
Thanks Barbara.
I am going to try to recover my CELO's this weekend.
If i have any issues who and how i can get in touch with?
________________________________
