### ISSUE TITLE
celocli 0.0.59 is broken

### ISSUE THREAD

**Issue by haferman** [celo-org/celo-monorepo#5577]
### Expected Behavior
I expect
```celocli account:claim-account ./validator1_metadata.json --address $CELO_VALIDATOR_GROUP_RG_ADDRESS --from $CELO_VALIDATOR_SIGNER_ADDRESS```
to return without an error.

I expect 
```celocli releasegold:authorize --contract $CELO_VALIDATOR_RG_ADDRESS --role attestation --signature 0x$CELO_ATTESTATION_SIGNER_SIGNATURE --signer $CELO_ATTESTATION_SIGNER_ADDRESS```
to return without an error.

### Current Behavior

`celocli account:claim-account ./validator1_metadata.json --address $CELO_VALIDATOR_GROUP_RG_ADDRESS --from $CELO_VALIDATOR_SIGNER_ADDRESS`
produces
`Read Metadata from ./validator1_metadata.json... Error: TypeError: signatureUtils_1.hashMessage is not a function
    TypeError: signatureUtils_1.hashMessage is not a function`

`celocli releasegold:authorize --contract $CELO_VALIDATOR_RG_ADDRESS --role attestation --signature 0x$CELO_ATTESTATION_SIGNER_SIGNATURE --signer $CELO_ATTESTATION_SIGNER_ADDRESS`
produces
` Error: Unable to parse signature`

**Comment by haferman** [comment]
Downgrading to celocli 0.0.58 is a workaround for now.

**Comment by barbaraliau** [comment]
@haferman thanks for opening this. Can you provide us with some additional network information? Is this on a local or hosted node? Are you on Alfajores, Baklava, or mainnet?

**Comment by haferman** [comment]
@barbaraliau I experienced the problem with `celocli account:claim-account` on both baklava and mainnet on full nodes that I am running with the CELO 1.1.0 image using
`docker run --name celo-accounts -it --restart unless-stopped -p 127.0.0.1:8545:8545 -v $PWD:/root/.celo $CELO_IMAGE --verbosity 3 --networkid $NETWORK_ID --syncmode full --rpc --rpcaddr 0.0.0.0 --rpcapi eth,net,web3,debug,admin,personal --baklava --allow-insecure-unlock --nousb --gcmode=archive`

(and without the `--baklava` flag on mainnet.

The issue with `celocli releasegold:authorize` was reported by two other people on Discord who were running on baklava and one was attempting to connect to the Baklava forno.

**Comment by medhakothari** [comment]
Hi @haferman! I've identified the issue and will be publishing a fix to it shortly. Thank you for flagging this and creating the issue 🙌
