### ISSUE TITLE
Continuous  loading indicator is shown when user try to restore existing account which having low balance. 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#5578]
**Frequency:** 100%
**Repro App version:** Android play store internal build v1.3.0(1004294316) & Test Flight build v1.3.0(27)
Does not repro version : Android internal build 1.2.0(1004294314), Test flight build v1.2.0 (26)
**Repro on devices:** Google Pixel XL (8.1) , iPhone SE 2 (13.5) , Samsung Galaxy M30s(9.0)
Account Key: 443 390 2072/ [Back up key.](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit#gid=0&range=B5) 
**Repro Steps:** 
1. Launch the app and go through the walkthrough. 
2. Tap on i have an account button. 
3. Enter name & number 
4. Set up PIN
5. Enter an existing account which is having $0 dollars.
6. Tap on restore button. 
7. Observe

**Current Behavior:**  Continuous  loading indicator is shown

**Expected Behavior:** User  should be able to restore an account. 
**Impact:** User is get frustrated by seeing continuous loading indicators. 
**Investigation:** Issue does not repro when user has enough balance which shows in app. i.e $0.01 
**Attachment:** [SigninIssue.mp4](https://drive.google.com/file/d/1scdf1ExZ6aKAHJDSs-20rEmPPnkt5kCZ/view?usp=sharing)[issue observed after 17 sec] 

## Mitigations:
* display the low balance
* give them access to the address (do not fetch pepper, etc if there are insufficient funds)

**Comment by gnardini** [comment]
Hi @Lss-Ankit, I verified this with an account with $0 and the popup did show up. The account used has a small amount of cUSD (0.00532, see here: https://explorer.celo.org/address/0x6826d0e96eb1727efee245e23dbcd1d557e2a196) which is why the popup doesn't show up.

This is still something we should fix, just mentioning this for context.

**Comment by Lss-Ankit** [comment]
Hi @gnardini  Thanks for the update. 
I have verified issue again and yes you are correct, i am getting Balance $0.00 pop-window  for 0 balance account. 
Issue is repro only for an account which has lower cUSD. 
Sorry for the inconvenience, Actually in app I am able to see only $0.00 as balance hence I thought it is 0 balance issue. 
I have updated the title and description of an issue. 
Thanks!

**Comment by gnardini** [comment]
@Lss-Ankit Can you please check if this is still happening? I think it shouldn't since the latest changes to the verification flow.

**Comment by Lss-Ankit** [comment]
Hi @gnardini We have verified this issue with latest Android internal build v1.6.0(1004294326)  and Test Flight build v1.6.0(37) and found issue is fixed So, we are closing this ticket.

**Device:** Google pixel 2 (11), iPhone 6+ (12.4.5)
