### ISSUE TITLE
CICO improvments

### ISSUE THREAD

**Issue by cmcewen** [celo-org/celo-monorepo#5635]
### Expected Behavior

- Users see CELO/cUSD in local currency
- fetch rates from providers to show before webview
- choose your provider/see rates
- withdraw - warn if the address has zero balance
- withdraw flow should have cUSD/green buttons
- filter by your geography/asset

**Comment by tarikbellamine** [comment]
These suggestions have either have been addressed, been split out into individual issues, or will be addressed in the CICO redesign.
