### ISSUE TITLE
“$” symbol does not fit to the screen when the user tries to reclaim the amount on the ‘Reclaim Payment’ page.

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#5639]
**Frequency:** 100%
**Repro on build version:** Android internal build v1.3.0(1004294316)
**Repro on devices:** Samsung Galaxy A5(7.0) , Samsung Galaxy A3(5.0.2)
**Does not Repro:**  iPhone XS max (13.5.1),Samsung Galaxy M 40s(10.0)
**Account Key:** (680)3331978
**Pre-condition:** User should send money to non verified user and wait for 24 hrs. to get Reclaim invitation in In-app notification.

**Repro Steps:**
1. Launch the application and login with verified account details.
2. Send money to non verified user B through the invite option.
3. User B should not accept an invitation for 24 hrs.
4. Now user A will get “Invited with  $# and Reclaim option”.
5. Tap on the Reclaim button.
6. Observed that the “$” symbol (below the user profile picture & name section)does not fit to screen properly.

**Current Behavior:** “$” this symbol does not fit to screen properly.
**Expected Behavior:** “$” symbol should be corrected on the Reclaim Payment page.
**Attachment:** [$SymbolNotFitToScreen.png](https://drive.google.com/file/d/1jmmEUeLsrffeh1ogxVSvmlmV2Qwc1Nd7/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
Hi, I have verified this issue using latest Android Internal build v1.4.0(1004294317) & Test Flight build v1.4.0(28) & observed that issue is still reproduced.
**Repro on devices:** Samsung Galaxy A5(7.0), iPhone SE(13.5.1)

**Comment by Lss-Ankit** [comment]
Hi, I have verified this issue using latest Android Internal build v1.5.5(1004294323)  &  Test Flight build v1.5.5(34) observed that issue is still reproduced.
**Repro on devices:** Samsung Galaxy A5(7.0) , iPhone SE (13.5.1)

**Comment by Lss-Ankit** [comment]
Hi, I have verified this issue using latest Android Play store build v1.5.5 & App store build v1.5.5(34) observed that issue is still reproduced.
**Repro on devices:** Samsung Galaxy A5(7.0) , iPhone SE (13.5.1)

**Comment by Lss-Ankit** [comment]
Hi, I have verified this issue using latest Android Internal build v1.6.0(1004294326) & Test Flight build v1.6.0(37) observed that issue is still reproduced.
**Repro on devices:** Samsung Galaxy A5(7.0) , iPhone 7 Plus (14.1)

**Comment by Lss-Ankit** [comment]
Hi @nityas @jeanregisser  we have verified this issue using latest app store build 1.6.0 & play store build 1.6.0  observed that issue is still reproduced.
**Repro on devices:** Samsung Galaxy A5(7.0) , iPhone 7 Plus (14.1)

**Comment by Lss-Ankit** [comment]
Hi @nityas @jeanregisser I have verified this issue using latest Android internal build V1.7.2(1004294329) observed that user not able to see dollar amount screen. Let me know is it expected?
**Repro on devices:**  LGK7i (6.0)
**Attachment:**  [ReclaimPaymentPageUI.jpg](https://drive.google.com/file/d/1_zjRr8HhvVIf8FA8MzJrVOP0B5xLVtIQ/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
Hi @nityas @jeanregisser I have verified this issue using latest Android internal build V1.8.0(1004294330) & Test Flight Build V1.8.0(40) & observed following.
**Verified on devices:** LGK7i (6.0), iPad Air 1(12.4.6)
**Observations:** 
- In  LGK7i (6.0) it is observed that user not able to see dollar amount screen. Let me know is it expected?
**Attachment:** [ReclaimPaymentPageUI.jpg](https://drive.google.com/file/d/1_zjRr8HhvVIf8FA8MzJrVOP0B5xLVtIQ/view?usp=sharing)
- Also in iPad Air 1(12.4.6) it is observed that $ symbol does not fit to screen.

**Comment by Lss-Ankit** [comment]
Hi @nityas @jeanregisser I have verified this issue using latest Android Internal Build V1.9.2(1004294333) & Test Flight Build V1.9.2(43) & observed following:

- In Samsung Galaxy A5(7.0) it is observed that user not able to see dollar amount screen. Let me know is it expected?

- Also in iPhone XR(13.1.3)  it is observed that $ symbol does not fit to screen.
**Verified on Devices:** Samsung Galaxy A5(7.0),  iPhone XR(13.1.3)

**Comment by gnardini** [comment]
This will be fixed by https://github.com/celo-org/celo-monorepo/pull/6457

**Comment by ValoraQA** [comment]
Hi @gnardini I have verified this issue using latest  Android Internal Build V1.11.0(1004294337) & Test Flight Build V1.11.0(47) & observed that issue is fixed now.
**Verified on Devices:** Samsung Galaxy A5(7.0), iPhone XR(14.4)
