### ISSUE TITLE
Determine how to aggregate chain data and translate into cUSD Rewards

### ISSUE THREAD

**Issue by ewilz** [celo-org/celo-monorepo#5640]
Collect data for only verified addresses on their cUSD balances over a one month period. Will probably use time-weighted average or mean. Then use this data to calculate monthly rewards.

Questions:

1. How do we pull attestation data? (events)
2. How do we pull balance data?
3. How do we calculate average/mean?
4. How do we calculate time-weighted balance into a rewards amount? (6%/ 12)?
5. What does output file look like? I think noting the time-weighted balance as well as reward amount are both valuable figures to maintain.

**Comment by ewilz** [comment]
Collect data for only verified addresses on their cUSD balances over a one month period. Will probably use time-weighted average.

Open questions:
- Collect balance every nth block. How often do we note balance?
- What does output file look like? I think noting the time-weighted balance as well as reward amount are both valuable figures to maintain.

**Comment by nambrot** [comment]
@ewilz Shouldn't this still be open?

**Comment by ewilz** [comment]
Answers:

1. Events
2. Events
3. Time-weighted average by block ((balance1 * nBlocks1) + (balance2 * nBlocks2) / totalNumberOfBlocks)
4. totalAnnualPercentage / n reward periods
5. Output files:
  rewards.json {
   [address: string] : rewardAmount
   }
  rewardsCalculationState.json {
    attestationCompletions: AttestationCompletions
    averageBalances: Balances
    balancesByBlock: BalancesByBlockState
    startedBlockBalanceTracking: boolean
    blockNumberToStartTracking: number
    blockNumberToFinishTracking: number
    rewardPercentage: number
  }
