### ISSUE TITLE
celocli users can include metadata in their transactions with a flag

### ISSUE THREAD

**Issue by martinvol** [celo-org/celo-monorepo#5641]
### Expected Behavior

The cli should have a flag to include metadata in tx, at least the ones triggered by `exchange` and `transfer`.

### Current Behavior

No metadata can be added.

**Comment by martinvol** [comment]
Some apps, like Hummingbot, relly on the cli to make exchanges. It'd be great they could be able to tag those as sent from the bot, so we could analyze how efficiently trading bots are reacting.

**Comment by aslawson** [comment]
Chatted with to @martinvol  and @MarkusBerlin, and this is blocking some key liquidity initiatives.

**Comment by barbaraliau** [comment]
> The cli should have a flag to include metadata in tx, at least the ones triggered by exchange and transfer

Need more information on what this means. Verify this means sending extra data in tx

**Comment by medhakothari** [comment]
Marking as blocked until we get more information: 
Looking at it now, wondering what this exactly entails. Are they trying to add metadata on chain, using something like `transferWithComment` as we currently have been? If so:

- For transfer , can’t the users using the CLI with the `--comment` flag to achieve this?
- And for exchange, how would we do this without making changes at the protocol level (e.g. emitting a new type of event on chain)?

**Comment by gastonponti** [comment]
This requires contract changes.
Talked with @martinvol and he agrees to close it
