### ISSUE TITLE
Determine what changes need to be made in uniswap's merkle distributor scripts and contract

### ISSUE THREAD

**Issue by ewilz** [celo-org/celo-monorepo#5642]
- This is an initial spike, though as implementation is carried out, more changes may be brought to light.
- Ideally no changes need to be made to the smart contract.
- The scripts involve taking a json of addresses mapped to balances (in our case rewards) and converting that into a merkle tree. Not included in this repo is the scripts to scrape chain data. Those will need to be written from scratch.

**Comment by nambrot** [comment]
@asaj Determined no work to be done
