### ISSUE TITLE
Non-core-contracts should be verifiable

### ISSUE THREAD

**Issue by nambrot** [celo-org/celo-monorepo#5667]
### Expected Behavior

I should be able to easily tell whether non-Celo Core, but audited contracts like `ReleaseGold` or `MetaTransactionWallet` correspond to the audit commit

### Current Behavior

I can't tell

**Comment by nambrot** [comment]
This is for the most part already one in Valora, so kicking it out of the milestone https://github.com/celo-org/celo-monorepo/blob/master/packages/komencikit/src/verifyWallet.ts

**Comment by aslawson** [comment]
@nambrot this seems like its still needed for ReleaseGold Contract, correct?

**Comment by nambrot** [comment]
I'd say this is still valuable, but afaik no one specifically is asking for it. IMO, this would be more valuable for all the MultiSigs that have been recently deployed. Though maybe more primarily to do in Blockscout than via code tooling

**Comment by yorhodes** [comment]
might get this for free with https://github.com/celo-org/celo-monorepo/issues/7439
I read sourcify identifies duplicate bytecode for "factory" contracts
