### ISSUE TITLE
Escrow V2

### ISSUE THREAD

**Issue by nambrot** [celo-org/celo-monorepo#5671]
### Expected Behavior

Additional protections:
- Time-lock
- better attestation heuristic assessment
- optional payment codes

### Current Behavior

What is the current behavior?

Relevant thread: https://celo-org.slack.com/archives/CP5V8KF51/p1601910740112800

**Comment by clrblmt** [comment]
Following this release to we anticipate additional work to further secure the escrow?

**Comment by nambrot** [comment]
Since we don't have specific requirements or designs, I would assume we won't know until someone works on this
