### ISSUE TITLE
Contracts developer environment should be closer to celo-blockchain

### ISSUE THREAD

**Issue by nambrot** [celo-org/celo-monorepo#5695]
### Expected Behavior

- Make Ganache closer and easier to use
- OR look into hardhat
- OR look into celo-blockchain

### Current Behavior

ganache is very different from celo-blockchain, making integration testing hard. Additionally. ganache is hard to use

**Comment by nambrot** [comment]
There is a foundation grant applicant to look into this

**Comment by AlexBHarley** [comment]
@nambrot is this ticket something you'd feel happy with the Contracts circle owning? If so we can remove from the Applications circle backlog.
