### ISSUE TITLE
User is able to take a screenshot & be able to save the user's account key when the user taps on  ‘Account key’ from Hamburger Menu.

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#5707]
**Frequency:** 100%
**Repro on build version:** Android internal build v1.3.0(1004294316) 
**Repro on devices:** Samsung Galaxy Note 5(7.0) 
Testing Account: (680)9898865  / Back up Key: https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit#gid=0

**Pre-condition:** Users should have set an Account key after login with a new account.
**Repro Steps:**
1. Launch the application & login with New/Existing account.
2. Go to the Account key section & set account key.
3. Again tap on the Account key section from Hamburger Menu.
4. Now the user should be on the ‘Your Account Key’ page with the generated account key.
5. Try to take screenshots using respective mobile devices.
6. Observed that,
**Current Behaviour:** Any other user is able to take a screenshot and be able to save it.
**Expected Behaviour:** Other users should not be able to take screenshots.
**Investigation:** For IOS, it is expected and confirmed with jean as for iOS it is not possible. 
**Impact:** Other User can sign in and funds can be stolen by any random user.
**Attachment:**  [UserShouldNotAbleToTakeScreenshot.mp4](https://drive.google.com/file/d/1MowFuAAQsExx-e84a5VBHJxTSztNm4kB/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
Hi @nityas I have verfified this issue using latest Android internal build v1.5.5(1004294323) & Test Flight build v1.5.5.(34) & found that issue is still reproduced.
**Repro on devices:** Samsung Galaxy Note 5(7.0)

**Comment by nityas** [comment]
downgrading to P2-- just because we've noticed that this is not the case on initial saving of key(so this would be an additional copy) and we are looking to build a v2 of this feature

**Comment by Lss-Ankit** [comment]
Hi @nityas I have verified this issue using latest Android internal build v1.5.5(1004294323) & Test Flight build v1.5.5.(34) & found below observations.
**Repro on devices:** Samsung Galaxy Note 5(7.0), iPhone SE (13.5.1)
**Observation:** 

**For Android:**  
- User is not able to take screenshot while setting up Account key but able to take screenshot after setup is done.

**Comment by Lss-Ankit** [comment]
Hi, @nityas  I have verified this issue using latest Android Internal build v1.6.0(1004294326) & observed that issue is still reproduced.
**Repro on devices:** Samsung Galaxy A5(7.0) 
**Observation:**

**For Android:**
User is not able to take screenshot while setting up Account key but able to take screenshot after setup is done.
