### ISSUE TITLE
User must supply absolute path in governance:propose cmd

### ISSUE THREAD

**Issue by alecps** [celo-org/celo-monorepo#5713]
### Expected Behavior

`governance:propose` should accept a relative path to the `proposal.json` file.

### Current Behavior

The user must pass an absolute path to the `proposal.json` file.

**Comment by YazzyYaz** [comment]
@alecps I have a fix for it but I'd like to be able to test the change. Any sample `proposal.json` you can point me to? Or the full command would be nice cause I don't have 100 Alfajores CELO coin to test submitting a governance proposal.

**Comment by YazzyYaz** [comment]
PR for this ticket: https://github.com/celo-org/celo-monorepo/pull/5798

Can be tested as follows:
```sh
$ ./cli/bin/run governance:propose --jsonTransactions proposal.json --deposit 100000000000000000000 --from 0xD30d08E9C0ad3D158953C062b6ee8ca53B706d2d --descriptionURL https://gist.github.com/yorhodes/46430eacb8ed2f73f7bf79bef9d58a33 --node https://alfajores-forno.celo-testnet.org

(node:10828) ExperimentalWarning: The fs.promises API is experimental
Running Checks:
   ✔  Account has at least 100 CELO
   ✔  Deposit is greater than or equal to governance proposal minDeposit

Sending Transaction: proposeTx... !
    Error: unknown account
```

with proposal.json inside the packages dir.

Now, say I move the proposal.json inside the `bin` directory.

```sh
$ ./run governance:propose --jsonTransactions proposal.json --deposit 100000000000000000000 --from 0xD30d08E9C0ad3D158953C062b6ee8ca53B706d2d --descriptionURL https://gist.github.com/yorhodes/46430eacb8ed2f73f7bf79bef9d58a33 --node https://alfajores-forno.celo-testnet.org

(node:11123) ExperimentalWarning: The fs.promises API is experimental
Running Checks:
   ✔  Account has at least 100 CELO
   ✔  Deposit is greater than or equal to governance proposal minDeposit

Sending Transaction: proposeTx... !
    Error: unknown account
```

In both cases, the path of the proposal.json is relative and the full path isn't specified or needed.

**Comment by alecps** [comment]
Closing this as I can't seem to reproduce the error. I'll assume I just had the file in the wrong place 🤦‍♂️
