### ISSUE TITLE
payment received in-app notification is shown on Enter PIN screen again when user has launch the app after putting app in background

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#5726]
**Frequency:** 100%
**Repro on build version:** App store build V1.3 
**Repro on devices:** iPhone 6 (12.4.5) 
Testing Account: (680)9898865  / Back up Key: https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit#gid=0

**Pre-condition:** Users should ope the app from back ground when user received dollars.
**Repro Steps:**

1. Launch the application & login with New/Existing account.
2. Send dollars from UserA to UserB
3. Make sure User should receive dollar
4. Enable Require PIN on App Open toggle button 
5. Keep app background for 30 secs
6. Open the app from background 
7. Observe payment received blue banner is shown

**Current Behaviour:**  payment received blue banner is shown when user is on enter pin page after opening app from background .
**Expected Behaviour:**  payment received blue banner should not  show
**Impact:** USer get confuse that he received another payment.
**Attachment:**  [ReceivedPaymetBlueaner.MP4](https://drive.google.com/file/d/1a4L23NgyNde8MykLMfDnUJDz-Cstcudp/view?usp=sharing)

**Comment by ValoraQA** [comment]
Hi  I have verified this issue using latest Test Flight Build V1.11.1(48) & Android Internal Build V1.11.1(1004294339) & observed that issue is fixed now. User not able to see blue In-App notification again on Enter PIN screen after keeping app in background.
**Verified on Devices:** iPhone 6 (12.4.7), iPhone SE (14.2)
