### ISSUE TITLE
Pixel Phones are unable to attach logs

### ISSUE THREAD

**Issue by dominiquejane** [celo-org/celo-monorepo#5730]
### Expected Behavior
Logs should be attached to the email when sent via _Menu > Help > Contact_

### Current Behavior
Logs are not attached.
All cLabbers (Rene, Will, Denisse) who experienced this were using Pixel phones

**Comment by nategraf** [comment]
Confirming on Pixel 4. I get a "Could not attach file" toast as it opens GMail.
