### ISSUE TITLE
[Wallet] Back button in "Confirm Phone Number" doesn't function as expected

### ISSUE THREAD

**Issue by calrobertlee** [celo-org/celo-monorepo#5738]
### Expected Behavior

Note: Issue is only relevant to new users that have not confirmed their phone number yet.  

When the user clicks "Confirm Phone Number" in Settings, they are brought to a PIN screen to enter in their pin code.  The expected behavior is to allow the user to click the back carrot in the top bar without the requirement to enter a pin code.

### Current Behavior

It does not allow the above behavior, the screen flashes briefly and remains on the pin screen.  The back carrot is essentially broken and does not function as expected.

**Comment by Lss-Ankit** [comment]
@jeanregisser  While doing regression testing on Test flight build v1.4.0 (28) and Android play store (internal build) v1.4.0 (1004294317) , also observed same issue. 

- Continuous loading indicator is shown when user taps on < back button from Confirm screen (Enter Three code screen).

Devices: Google Pixel XL (8.1) , iPhone XR (13.2.2)
