### ISSUE TITLE
Blank screen is shown  when the user taps on the Simplex option from the Add and Withdraw section.

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#5743]
**Frequency:** 100%
**Repro on build version:** Test flight build v1.4.0 (28)
**Does not repro version** Android play store (internal build) v1.4.0 (1004294317)
**Repro on devices:** iPhone 6+ (12.4) , iPhone XR (13.2.2) 
Testing Account:  (806) 459-1666/ [Backup Key](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit#gid=0)

**Repro Steps:**
1. Launch the application & login with a test account.
2. Tap on Hamburger Menu. 
3. Tap on Add and Withdraw option. 
4. Tap on Add Funds options. 
5. Tap on Simplex provider. 
6. Copy valora cUSD address and observed. 

**Current Behaviour:**  Blank screen is shown  
**Expected Behaviour:**  cUSD and other currency field should be displayed. 
**Investigation:** Sometimes in Android we are getting an error screen with something wrong message. 
**Impact:** Users are blocked from buying cUSD. 
**Attachment:**  [IOS_Simplex.mp4](https://drive.google.com/file/d/1a7rIrqpCehNTfoEhQLotLBzXVQZdNCpP/view?usp=sharing) [Bug observed at 09 sec]

**Comment by jeanregisser** [comment]
Here's how it shows for me:

In Valora:
<Img src="https://user-images.githubusercontent.com/57791/98381431-27a92f80-204a-11eb-8fa2-c6ec77710213.png" width="50%" />

In Safari:
<Img src="https://user-images.githubusercontent.com/57791/98381581-5cb58200-204a-11eb-92fb-6a8c910f661f.png" width="50%" />

**Comment by aaronmgdr** [comment]
😨

**Comment by ValoraQA** [comment]
We have verified this issue on latest Android Internal build V:1.22.1 and observed that issue is fixed

Verified on device : OnePlus 7t(11.0)
Attachment : [simplex_issue.mp4](https://drive.google.com/file/d/1BWrQNdh8nidjjLfgUy43AC0vklvfZ9aB/view?usp=sharing)
