### ISSUE TITLE
ContractKit Should refresh contract address and clear caches

### ISSUE THREAD

**Issue by mcortesi** [celo-org/celo-monorepo#575]
### Expected Behavior

A smart contract address can change due Governance. So, we shouldn't rely forever on contract address. Instead we should refresh them, revoke contract cache and wrappers, and invalidate current instances

+ contractkit should at minimum recognize if ABI is incorrect and fail gracefully

### Current Behavior

nothing is done

**Comment by aslawson** [comment]
@mcortesi super old ticket, but do you remember the context on this? where are we relying on direct contract addresses rather than proxy addresses?

And how does "refreshing" happen?

**Comment by mcortesi** [comment]
@aslawson  Context is:

* We have registry mapping that maps `Name -> contractAddress`
* Those mapping might change (via gov proposal we choose a new proxy / contract)
* ContractKit mantains an in memory cache of the mapping, so in the case the contract changes, you won't notice it.

It's arguable something that won't happen any time soon, but contractKit can be part of a long running process that needs to be able to detect this changes, and somehow fail accordingly.

There's a subcase, which is proxy address didn't change, but implementation changed, and maybe the ABI (contract interface). Here also contractKit should be able to detect and fail accordingly.

To give you an example, imagine the attestation contract changes, then all attestation service would fail with weird errors, it would be nice if they fails because they've notice the ABI has changed (contract version)

**Comment by aaronmgdr** [comment]
@mcortesi I just came across this. Im thinking a solution could be to store a timestamp when the cache was created and either purge or check if its needs to be updated if accessed after X time (like an hour?)

**Comment by aaronmgdr** [comment]
Theres actually three "caches" in the js code the Address Registry , the Web3 Contracts Cache and then Wrapper Cache. All three would need to be reset.
