### ISSUE TITLE
Celo Core Contracts should not be impacted by EIp1884 gas changes

### ISSUE THREAD

**Issue by nambrot** [celo-org/celo-monorepo#5753]
### Expected Behavior

Celo Core Contracts should continue to work as expected if EIP1884 changes are made.

See:
- https://forum.openzeppelin.com/t/openzeppelin-upgradeable-contracts-affected-by-istanbul-hardfork/1616
- https://github.com/celo-org/celo-blockchain/pull/939
- https://medium.com/authereum/istanbul-gas-reprice-breaks-contract-interactions-4236fdddb5e0

### Current Behavior

Unclear

**Comment by aslawson** [comment]
@pranaymohan Do you have a sense of how high priority is this? Would it be more painful to do this later if we wait?

**Comment by pranaymohan** [comment]
I believe we did not include this in the current hard fork to give more time to investigate whether it would break any contracts. The timeline which this would be useful to get done is before the next hard fork, which will be ~6 months after the first one, i.e. November 2021.

**Comment by trianglesphere** [comment]
FYI: In the berlin HF they increased gas prices again, but added [EIP-2930: Optional access lists](https://eips.ethereum.org/EIPS/eip-2930) to defray costs when the access list can be computed ahead of time.
