### ISSUE TITLE
describe deletion of replicastate folder in docs

### ISSUE THREAD

**Issue by k0kk0k** [celo-org/celo-monorepo#5763]
https://docs.celo.org/validator-guide/node-upgrades#geth-flags lacks this description from @trianglesphere about deleting `replicastate` folder which he gave in discord.

What will happen if the node is started with `--istanbul.replica` and restarted? What will happen if the folder is removed and the node is restarted?

https://discord.com/channels/600834479145353243/638489933740376068/774365316548919346

Joshua | cLabs 11/06/2020
Ok. So this isn't the most intuitive behavior, but that's how it's built. What's going on is that nodes that mine save if they are validators or replicas and that overrides the command line (so say you have a validator that you hotswap out and it gets restarted it stays offline rather than mining). That warn just means that it was able to load the replica state and should be removed.
If you want to clear out the replica state persistence, delete the `replicastate` folder in the data dir.

**Comment by trianglesphere** [comment]
@k0kk0k I made PR to try to clarify these questions. I've had my head in this for a while, so LMK if something's not clear or I left something out.

https://github.com/celo-org/celo-monorepo/pull/5821
