### ISSUE TITLE
Android randomly resets Redux state

### ISSUE THREAD

**Issue by jeanregisser** [celo-org/celo-monorepo#5792]
### Expected Behavior
App state should never reset without direct user action.

### Current Behavior

This was reported by @marekolszewski 
> Valora account reset unexpectedly...

Disk space doesn't seem to be the issue. The user had 70% of free disk space.

Deleting the app and reinstalling it fixes the issue.

We don't have logs yet.

**Comment by Lss-Ankit** [comment]
Hi @jeanregisser i have verified issue on Android play store (internal build) v1.4.0 (1004294317) and found the following: 
Devices used : Samsung Galaxy m40 (10) 
- User is able to restore account after reset valora from setting screen. 
- User is able to restore account after clearing app data from device setting. 

Can you please let me know is it device specific issue or specific steps to repro the issue ?

**Comment by jeanregisser** [comment]
I have been able to reproduce this randomly on an Android emulator. I unfortunately don't have the logs though.

I was relaunching/killing the app many times, and after around 40 attempts, I got this problem. Basically the persisted Redux state got reset and I couldn't restore my account anymore because the key was already in the geth keystore.

This seems to indicate there's some kind of race condition/corruption with the Redux state persistence mechanism.

**Comment by i1skn** [comment]
Just to clarify here:
1. User installs Valora, create an account after successful onboarding
2. User gets randomly logged out from the account at some point they launch the app? At this point geth actually still has the account in it, but in redux we do not know about that?

**Comment by jeanregisser** [comment]
Yes exactly!

**Comment by tarikbellamine** [comment]
Split out the inability to restore from Account Key into a separate issue (#6235). This issue now solely relates to the random account resets that appear to be happening only on Android.

**Comment by gnardini** [comment]
This should have been fixed by https://github.com/celo-org/celo-monorepo/pull/6273 I'll just keep open for a bit to monitor and make sure it is actually fixed before closing.

**Comment by tarikbellamine** [comment]
I'm going to close this for now to represent the progress we've made. We can reopen if we encounter this issue again
