### ISSUE TITLE
Nothing happens when the user taps on “Cancel” from Withdraw CELO screen opened via deeplink

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#5802]
**Frequency:** 100%
**Repro on build version:** Test Flight build v1.5.0 (29)
**Repro on devices:** iPhone XR (13.2.2) , iPhone 11 (14.0)
Testing Account: (806) 459-1666 / [Backup Key](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit#gid=0)
**Pre-condition:** launch the deeplink celo://wallet/pay?address=0xd13eee43e38f65fe3839bef6297928b43de38a02&amount=.1&token=CELO 
**Repro Steps:**
1. Launch the application & login with a test account.
2. Copy the given link and paste to Safari browser. 
3. Tap on Open button from "Open this page to valora" pop up
4. Make sure the Withdraw CELO screen is open.
5. Tap on the Cancel button and observe. 

**Current Behaviour:**  Nothing happens when the user taps on “Cancel”
**Expected Behaviour:** Users should redirect to the Feed screen. 
**Impact:** Cancel button functionality is broken 
**Attachment:**  [IOS_Cencel_button.mp4](https://drive.google.com/file/d/16ZoMztxSQs6rj35AAI28TK8s0lJNUzeN/view?usp=sharing)(Bug Observed at 10 sec)

**Comment by ValoraQA** [comment]
Hi @gnardini We have verified the above issue on latest iOS testflight build V:1.20.4 and Latest Android Internal build V:1.20.4 and observed the following things :

- [x] Cancel / X button is seen on review page (dependent on device font size)

- [x] Clicking on cancel button redirects user to CELO carousels if user has not gone through the screens

- [x] If user has gone through screens then it should redirects user to CELO landing page

Attachments : [Cancel_android.mp4](https://drive.google.com/file/d/1bPv0NVeut3KVrnpU93tGOnnAHCRvgtbE/view?usp=sharing), [X_iOS.mp4](https://drive.google.com/file/d/1bU5C1EUXTOK_rpNUuqQCs7fl9ldE2ZXC/view?usp=sharing)

Note : In attachment CELO carousel wont be seen as we had already gone through it.

**Verified on Devices :** iPhone 6+(12.5.4), OnePlus 7T(11.0)

**CC:** @jeanregisser
