### ISSUE TITLE
"Open this page to valora" pop up is not shown when the user copy & paste the given deep link into the mweb browsers.

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#5804]
**Frequency:** 100%
**Repro on build version:** Play store (internal build) v1.4.0 (1004294317) 
**Does not repro version** Test Flight build v1.5.0 (29)
**Repro Devices** Google Pixel XL (8.1), Samsung Galaxy M41 (10.0) 
**Does not repro Devices:** iPhone XR (13.2.2) , iPhone 11 (14.0)

**Pre-condition:**  launch the deeplink celo://wallet/pay?address=0xd13eee43e38f65fe3839bef6297928b43de38a02&amount=.1&token=CELO 

**Repro Steps:**
1. Launch the application & login with a test account.
2. Copy the given link and paste to any android Mweb browser. 
3. Observe  

**Current Behaviour:**  "Open this page to valora" pop up is not shown
**Expected Behaviour:**  "Open this page to valora" pop up is should shown
**Impact:** User is blocked to use deep links on Android. 
**Attachment:** [Android_Deeplink.mp4](https://drive.google.com/file/d/1k-t61-7COAgvZMSmmBNxe2lc3Ou9KVLY/view?usp=sharing) (Bug Observed at 12 sec)

**Comment by jeanregisser** [comment]
This is expected behavior in Chrome Android.
See https://stackoverflow.com/a/37089686/158525

**Comment by Lss-Ankit** [comment]
Okay thanks for the updates @jeanregisser 
Is there any way to use deep links on Android

**Comment by Lss-Ankit** [comment]
Hi @jeanregisser Any update on this? Is there any possible way to check deeplink in Android?

**Comment by jeanregisser** [comment]
Writing a note/document with deeplinks, or sending yourself an email with deeplinks should allow you to click them.

**Comment by Lss-Ankit** [comment]
Hi @jeanregisser thanks for the update!
- Still we are not redirected to app when pasting the deeplinks in browser. Tried with below steps.
1) User not able to redirect to app when tapping on link in mail.
2)  "Open this page to valora" pop up is not shown when the user copy & paste the deep link into the mweb browser
[Attachment:](https://drive.google.com/file/d/12viPKo_VTz90lXYea1uNY-O6iato9WfW/view?usp=sharing)

**Comment by jeanregisser** [comment]
Ok here's a test web page you can use: https://codepen.io/jeanregisser/pen/abBzMRo

**Comment by Lss-Ankit** [comment]
Hi @jeanregisser thank you so much for your help Now, we are able to perform Deeplinks using web page in Android,
 Can you please let us know that So each deeplink we can use code pen for Android.
