### ISSUE TITLE
Account Key still referenced as "Backup Key" in blue banner

### ISSUE THREAD

**Issue by nityas** [celo-org/celo-monorepo#5805]
### Expected Behavior

Account Key should be used everywhere

### Current Behavior

Account Key still referenced as Backup Key in some places

**Comment by Lss-Ankit** [comment]
Hi @nityas We have verified this issue on latest build  latest Android  internal build V1.7.2(1004294329) &Test Flight build V1.7.2(39) and observe the following.
- "Setup your account key" is shown along with "Setup now" button when user open the app after a long time if user not setup account key 

**Device:** Samsung Galaxy S4(4.4.2), Samsung Galaxy A5(7.0)
