### ISSUE TITLE
Importing Contacts when they have been previously connected does not allow proceeding

### ISSUE THREAD

**Issue by nityas** [celo-org/celo-monorepo#5812]
### Expected Behavior

After connecting contacts, should be able to progress

### Current Behavior

Currently no way to proceed beyond screen https://celo-org.slack.com/archives/C018VLA3YAK/p1605111265027400

**Comment by Lss-Ankit** [comment]
FYI, we have similar ticket for the importing contact issue : https://github.com/celo-org/celo-monorepo/issues/4878 & https://github.com/celo-org/celo-monorepo/issues/5099
