### ISSUE TITLE
Reclaim payment hangs indefinitely

### ISSUE THREAD

**Issue by annakaz** [celo-org/celo-monorepo#5822]
### Expected Behavior

Can reclaim payment, or at least see an error if it doesn't work 

### Current Behavior

![File](https://user-images.githubusercontent.com/16907027/98861842-c9e66000-241a-11eb-8740-bb04fb31a57d.jpg)

Trying to reclaim an escrow payment hangs indefinitely

This escrow payment was sent from a version prior to 1.5 and the attempt to reclaim was in 1.5.1

**Comment by annakaz** [comment]
Related to https://github.com/celo-org/celo-monorepo/issues/5274

**Comment by annakaz** [comment]
Was not able to reproduce on a local build

**Comment by dominiquejane** [comment]
[Denisse's logs - dec 14](https://github.com/celo-org/celo-monorepo/files/5690968/celo_logs.20.txt)
"Got stuck after fee is calculated when reclaiming finds in escrow"

![](https://clabs.zendesk.com/attachments/token/jy9XP9LskfhawTP8WtFHzFig0/?name=Screenshot_20201214-105853.png)
