### ISSUE TITLE
Verification will sometimes, after prefilling all 3 codes, error out & require a retry

### ISSUE THREAD

**Issue by nityas** [celo-org/celo-monorepo#5834]
### Expected Behavior

when all 3 codes are prefilled they should be processed

### Current Behavior
After all 3 codes read, see the following modal
![image](https://user-images.githubusercontent.com/2686353/98902373-b3132e00-2459-11eb-8b92-c0be6aec54b4.png)

**Comment by tarikbellamine** [comment]
This is a duplicate of #5832
