### ISSUE TITLE
 “404 | This page could not be found” mweb page is open when user taps on Valoraapp.com/Support link from “Funding valora” pop up. 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#5840]
Frequency:** 100%
**Repro on build version:** v1.5.1 (30) and Play store internal build 1.5.1 (1004294319)
**Repro on devices:** Google Pixel XL (8.1) , iPhone SE 2 (14.1) 
Testing Account: (806) 459-1666 / (Backup Key)[https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit#gid=0]

**Repro Steps:**
1. Launch the application & login with a test account.
2. Tap on Hamburger Menu. 
3. Tap on Add and Withdraw option. 
4. Tap on Add Funds option
5. Tap on ? besides Select a digital currency 
6. Tap on Valoraapp.com/support link from Funding Valora popup 
7. Observed

**Current Behavior:**  “404 | This page could not be found” 
**Expected Behavior:**  Valoraapp.com/Support page should open. 
**Investigation:** Issue also repro from Cash out screen 
**Impact:** Users will not get the more information about the funding on Valora. 
**Attachment:**  [https://drive.google.com/file/d/1wF2x0HKB6JMNC_tFJKztlacy4kHheqbF/view?usp=sharing](Bug observed at  05 sec)

**Comment by jeanregisser** [comment]
The site should be up soon!

**Comment by Lss-Ankit** [comment]
Hi @jeanregisser i have verified this issue on latest Test flight build v1.5.5 (34) and Android internal build 1.5.5(1004294323) and found issue is still repro 
**Devices:** iPhone 6+ (12.4.5), Google Pixel XL (8.1)

**Comment by Pedro-vk** [comment]
@jeanregisser @Lss-Ankit I think that was fixed. It is working fine on dev version on Android

**Comment by tarikbellamine** [comment]
This has been addressed.

**Comment by ValoraQA** [comment]
Hi @tarikbellamine we have checked the above issue and observed that it is fixed.
Checked on Device : OnePlus 7t (11.0)
Attachment : [supportlink.mp4](https://drive.google.com/file/d/1xPnAOOOZBiqK3SCUluuZp5Eoa4i_V-Yj/view?usp=sharing)
