### ISSUE TITLE
“Failure sending payment” error message is displayed when the user sends an invitation from the “send” screen.

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#5842]
**Frequency:** 100%
**Repro on build version:** v1.5.1 (30) and Play store internal build 1.5.1 (1004294319)
**Repro on devices:** Google Pixel XL (8.1) , iPhone SE 2 (14.1), Samsung Galaxy A5(7.0),iPhone SE (13.5.1)
**Testing Account:** (680)2635981
**Repro Steps:**
1. Launch the application & login with a test account.
2. Open the home screen & tap on the Send button.
3. Tap on the search bar & enter any unverified number.
4. Now on the Send page Enter amount & click on Review button.
5. Tap on the Send button.
6. Now “Invite a Friend” popup displaying with Cancel  & Invite button.
7. Tap on invite option & Observed that
**Current Behavior:**  “Failure sending payment” error message is displayed.
**Expected Behavior:**  Users should invite another user and respective share options should be displayed.
**Impact:** Users get blocked to send invitations to other users.
**Attachment:**  [InvitationError.mp4](https://drive.google.com/file/d/13DgM6ZENkqGCfh5TA_wiNDE_srkyWAkl/view?usp=sharing)

**Comment by jeanregisser** [comment]
This should be fixed in 1.5.2 and above.

**Comment by Lss-Ankit** [comment]
@jeanregisser Verified issue on latest test flight build v1.5.5 (34) and Android play store internal build v1.5.5 (1004294323) and found that issue is fixed. 
Devices used : Google Pixel XL (8.1) and iPhone SE 2 (14.1)
