### ISSUE TITLE
[Protocol Economics] Cap on cUSD CP-DOTO tank size

### ISSUE THREAD

**Issue by yerdua** [celo-org/celo-monorepo#5849]
### Expected Behavior

As a safeguard against oracle manipulation or other issues related to an incorrect cUSD/CELO exchange rate, there should be a cap on the cUSD tank size. The rationale is that if other safeguards fail, the impact is limited

### Current Behavior

There is no cap.

### Definition of Done

- We have a design doc detailing why the cap is necessary and how we come up with a value for it 
- Cap is implemented and live on mainnet.

**Comment by albertclabs** [comment]
@martinvol does this need to be done for cEUR as well? Does doing this for cUSD also apply the same restrictions to cEUR or they are set separately?

**Comment by tkporter** [comment]
@albertclabs they are deployed as different contracts on-chain but are the same code, so the change would easily apply to both cUSD and cEUR (& any future stabletokens)
