### ISSUE TITLE
[Philippines] “Not found” page is open when user taps on BeamAndGo option from Spend screen

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#5864]
Frequency:** 100%
**Repro on build version:**  v1.5.2 (31) and Play store internal build 1.5.2 (1004294320)
**Repro on devices:** Google Pixel XL (8.1) , iPhone SE 2 (14.1) 
Testing Account: (806) 459-1666 / [Backup Key](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit#gid=0)

**Repro Steps:**
1. Launch the application & Sign up with Philippines number 
2. Tap on Hamburger Menu. 
3. Tap on Add and Withdraw option. 
4. Tap on Spend option 
5. Tap on BeamAndGo option 
6. Observe 

**Current Behaviour:** “Not found” page open
**Expected Behaviour:**  Valoraapp.beamandgo.com page should open. 
**Investigation:** Issue does not repro for Merchant Map
**Impact:** Users is blocked use beamandgo site. 
**Attachment:**  [BeamAndgoIssue](https://drive.google.com/file/d/1MSUhwtgtSeLgR0U-uOIjtJZ8IxCVd95z/view?usp=sharing)

**Comment by jeanregisser** [comment]
Thanks, the https://valora.beamandgo.com site will be available soon!

**Comment by nityas** [comment]
B&G Page should now be up :) closing this out

**Comment by Lss-Ankit** [comment]
Hi @nityas I have verified this issue using latest App store build v1.5.5 & Play store build v1.5.5 & observed that issue is fixed now & user redirect to Beam and GO page(Valoraapp.beamandgo.com).
**Devices:** Samsung Galaxy A5(7.0) & iPhone SE (13.5.1)
