### ISSUE TITLE
Restructure and publish Contracts Release Process docs

### ISSUE THREAD

**Issue by nambrot** [celo-org/celo-monorepo#5865]
### Expected Behavior

Docs are well structured

### Current Behavior

We added things one-by-one and that has become monolithic

**Comment by aslawson** [comment]
should fix tooling bugs before updating docs

**Comment by kevjue** [comment]
Split up the documents by stakeholder.

**Comment by yorhodes** [comment]
Also document newly added features and idiosyncrasies. Linked library addresses among others.
