### ISSUE TITLE
Attestations should return a batch of account addresses and attestation stats

### ISSUE THREAD

**Issue by nambrot** [celo-org/celo-monorepo#5869]
Query Goals:

1. Given an identifier (phone number), look up accounts (entry in `Account.sol`) that have attestations for the identifier
2. Given an identifier and account, lookup attestation stats (completed/total)
3. Given a list of identifiers, lookup accounts that have attestations and their stats
4. Given an account, lookup DEK and walletAddress
5. Given an identifier and account, has the account revoked for this identifier

Non-goal:
6. Given a list of identifiers, lookup walletAddresses that have attestations and their stats

Questionable:
7. Given a list of accounts, lookup DEK and walletAddress

Spec:

1. `Attestations#lookupAccountsForIdentifier` and `AttestationsWrapper#lookupAccountsForIdentifier`
2. `Attestations#getAttestationStats` and `AttestationsWrapper#getAttestationStat`
3. `Attestations#batchLookupAttestationStats` (new) and `AttestationsWrapper#batchLookupAttestationStats` (new)
4. `Accounts#getWalletAddress`/`Accounts#getDataEncryptionKey`
5. `Attestations#isRevokedFor(identifier, account)` and `AttestationsWrapper#isRevokedFor(identifier,account)`
6. (deprecated) `Attestations#batchGetAttestationStats` and `AttestationsWrapper#lookupIdentifiers`
7. `Accounts#batchGetWalletAddress`/`Accounts#batchGetDataEncryptionKey`

### Expected Behavior

- Deprecate `Attestations#batchGetAttestationStats` (currently used by `AttestationsWrapper#lookupIdentifiers `)
- Add `Attestations#lookupIdentifiers` which does the same as the old batchGetAttestationStats, but returns the accountAddress instead of the walletAddress
- Add a `Accounts#lookupAccounts` which takes as input an array of accountAddresses, and returns walletAddresses and DEKs for them
- Have `AttestationsWrapper#lookupIdentifiers` move to `Attestations#lookupIdentifiers`

Open Question:
- [ ] Is it preferable to break backwards compatibility for `AttestationsWrapper#lookupIdentifiers` or rename it?
- [ ] Does this get impacted by inflight CIP10 work?

### Current Behavior

`batchGetAttestationStats` returns walletAddresses, but there is no equivalent function for account addresses

**Comment by tarikbellamine** [comment]
From a Valora perspective, these query goals look right to me.

I think `Given a list of accounts, lookup DEK and walletAddress` should be considered a need. If we lookup an `identifier` and there are several `accounts` associated with it, our next step is to lookup the `wallet` associated with each `account` so that we can ask the user to help us disambiguate via Secure Send. Having a batched method would be more efficient for this.

My only additional thought is we don't really ever need a batched lookup for `DEKs` in Valora so it might make sense to remove that as an output.

**Comment by nambrot** [comment]
Should standardize on `get` instead of `lookup`

**Comment by nambrot** [comment]
Chatted with @tarikbellamine on this one. General read is that this is a good direction and could be done in the "near future", he will bring it up with product folks on the wallet

**Comment by tarikbellamine** [comment]
On the open question of `Is it preferable to break backwards compatibility for AttestationsWrapper#lookupIdentifiers or rename it?` the strong preference would be not to break backwards compatibility. Perhaps we can leave a note on the method that it is deprecated and will be deleted in the next version release (v3). I think we want to move towards standardizing on `get` so we probably want to name this new method with that convention.

**Comment by nambrot** [comment]
Chatted with Valora team and they said they could implement this in the short-term
