### ISSUE TITLE
Accounts.sol should allow walletAddresses to indicate the accountAddress

### ISSUE THREAD

**Issue by nambrot** [celo-org/celo-monorepo#5874]
Historically, users only needed to lookup walletAddress from an accountAddress for transfers.

Data encryption keys are registered by accountAddresses.

That means that currently, there is no easy way for a receiver of a transfer to determine the DEK of the sender if the walletAddress is different from the accountAddress.

We have two options:
1. 2 way mapping between `account.walletAddress` and `accountAddress`
2. backwards compatible migration from `walletAddress` to `authorizedBy` mapping such that `signerToAccount` allows account address lookup

option 1 requires 2 storage writes and we can't retroactively populate this mapping

option 2 solution
- create a new role `LegacyWalletAddress` which when authorized writes to CIP10 storage 
- ensure `AccountWalletAddressSet` is emitted
- modify `getWalletAddress` to lookup CIP10 mapping first and fallback to legacy struct storage location

Accounts with legacy wallet addresses can use new CIP10 authorization to allow `signerToAccount` to compute the reverse mapping from wallet address to account address

**Comment by kevjue** [comment]
This should be done as part of the CIP-10 implementation work.

**Comment by AlexBHarley** [comment]
This contracts piece of this is done with CIP10 merged. To gain adoption we simply need to introduce a role in ContractKit `celo.org/core/account` that allows specifying the account address for a given wallet address, then begin registering them (likely in Valora).

To make our concept of walletAddresses more flexible and allow multiple to be registered, we'd need to modify places marked with `legacySigner` in `Accounts.sol` to now also write/read from the walletAddress property.

**Comment by nambrot** [comment]
Is it that simple? Don't we need a method to write to the legacy struct location as well?

**Comment by AlexBHarley** [comment]
So there's two separate things here,

- Accounts can indicate `accountAddress` ✅   done with CIP10
- Accounts can indicate multiple `walletAddresses` ❌  we need to modify the methods to write these structs yes.

**Comment by yorhodes** [comment]
we need either
1. 2 way mapping between `account.walletAddress` and `accountAddress`
2. backwards compatible migration from `walletAddress` to `authorizedBy` mapping such that `signerToAccount` allows account address lookup

option 1 requires 2 storage writes and we can't retroactively populate this mapping

option 2 solution
- create a new role `LegacyWalletAddress` which when authorized writes to CIP10 storage 
- ensure `AccountWalletAddressSet` is emitted
- modify `getWalletAddress` to lookup CIP10 mapping first and fallback to legacy struct storage location

Accounts with legacy wallet addresses can use new CIP10 authorization to allow `signerToAccount` to compute the reverse mapping from wallet address to account address
