### ISSUE TITLE
Devs SBAT build monorepo according to SETUP.md with no errors

### ISSUE THREAD

**Issue by eelanagaraj** [celo-org/celo-monorepo#5910]
### Expected Behavior

Running `yarn && yarn build --ignore docs` should build a fresh clone of the monorepo without errors. 

### Current Behavior

Described [here](https://discord.com/channels/600834479145353243/774302385555243008/776592781153402930); the `packages/base` is not built before other packages which require it, causing the build to fail. We need to fix this or else update `SETUP.md` so that it's clear how to build the monorepo.

**Comment by barbaraliau** [comment]
Couldn't repro. Closing for now.
