### ISSUE TITLE
 “Please provide a valid Celo address” error message is displayed when the user taps on the Continue button after pasting the cUSD address.

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#5922]
**Frequency:** 100%
**Repro on build version:** Android internal build v1.5.5(1004294323) , Test Flight build v1.5.5(34)
**Repro on devices:** Samsung Galaxy A5(7.0), iPhone SE(13.5.1),Vivo V11 pro (10) ,iPhone 6+ (12.4.5)
**Testing Account:**  / Backup Key: 7576998999
broom guard vital vendor suspect bike output identify three essay moral nominee popular tail crime stomach inquiry first burden settle pond degree pulse mushroom

**Repro Steps:**
1. Launch the application and login with a test account.
2. Tap on the Hamburger menu and select Add and Withdraw option.
3. Click on Add funds option.
4. Now select the Celo Dollar(cUSD) option in “Select a digital currency” field & Debit card or bank account option in “Pay with” field.
5. Tap on the Next button & copy the cUSD address by tapping & holding on address.
6. Now paste the address in the “Celo Dollar address” field and tap on Next button.
7. Observed that, 
**Current Behavior:** “Please provide a valid Celo address”  error message is displayed after pasting the cUSD address.
**Expected Behavior:**  Users should redirect to the  “Order Summary" page.
**Investigation:**  Users are able to redirect to the “Order Summary” page if a user enters a cUSD address by removing spaces between addresses.
**Impact:** User might be confused in the cUSD address even if the user has entered the correct one.
**Attachment:**  [cUSDAddressWithBlankSpaceNotAccepting.mp4](https://drive.google.com/file/d/1czOyaDsV4s8sY0VwEi_-458SO1oQzqqr/view?usp=sharing)(issue observed at 00.31 sec)

**Comment by nityas** [comment]
@Lss-Ankit any chance this pasted with spaces? Would you be able to check and see if this still reproduces & reopen if so- we believe this was fixed and I can no longer repro :)

**Comment by Lss-Ankit** [comment]
Hi @nityas There is no chance to paste it with spaces.
- We have verified this issue with latest Android internal build v1.6.0(1004294326)  and Test Flight build v1.6.0(37) and found issue is fixed 
**Thanks for fixing this issue.**
