### ISSUE TITLE
Users SBAT know who they voted for

### ISSUE THREAD

**Issue by nambrot** [celo-org/celo-monorepo#595]
### Expected Behavior

There should be a call function that tells you who you voted for

### Current Behavior

You can't tell from the smart contract who you voted for

**Comment by nicholasguo** [comment]
Do we really want this? I'm aware that one property of voting schemes is that you shouldn't be able to fetch who you voted for. I may be wrong here.

**Comment by asaj** [comment]
I assume you're referring to `Validators.sol`?

**Comment by nambrot** [comment]
Yes. 

@nicholasguo You can figure out who anyone voted for by looking at the transaction log, so I don't think this is a concern here.

**Comment by mrsmkl** [comment]
It looks like the `voters` mapping is public, so solidity has already generated a getter for it.

**Comment by diminator** [comment]
What's the status here?
> It looks like the voters mapping is public, so solidity has already generated a getter for it.

Does this solve the issue?
