### ISSUE TITLE
DAppkit should leave feeCurrency field empty when using CELO as the fee currency

### ISSUE THREAD

**Issue by critesjosh** [celo-org/celo-monorepo#5956]
### Expected Behavior

DAppkit should leave the `feeCurrency` field of a transaction empty (`0x`) when CELO is the intended fee currency.

### Current Behavior

Dappkit populates the `feeCurrency` with the CELO ERC20 contract address. [Discord reference message](https://discord.com/channels/600834479145353243/697229940067663912/781248026143359006)

https://github.com/celo-org/celo-monorepo/blob/486a02ec7741d649e441726bde6c8e770526ee7f/packages/dappkit/src/index.ts#L110

**Comment by critesjosh** [comment]
The line referenced above may need to be changed to `undefined` or `null` rather than `0x0`

**Comment by aslawson** [comment]
Does this mean users currently cannot pay gas in CELO through dappkit? This feels like a high priority bug, easy fix.

**Comment by critesjosh** [comment]
Yes, trying to pay gas fees in CELO with dappkit doesn't work right now. I tried implementing a fix a couple of weeks ago, but it was more complicated than I thought so I didn't complete it.

**Comment by barbaraliau** [comment]
DappKit is a little outdated, and maybe updating it will solve the other errors and then we can debug

**Comment by critesjosh** [comment]
lastperson on discord is running into problems with this https://discord.com/channels/600834479145353243/697230027992858714/806272374462218241

**Comment by medhakothari** [comment]
Update: Spent time yesterday looking into the discord issue mentioned above, but wasn't able to repro. Will continue doing that today and post any updates

**Comment by critesjosh** [comment]
@medhak1 did you try it on alfajores and mainnet? I think it might work on mainnet but not alfajores.

**Comment by aslawson** [comment]
@medhak1 I added https://app.zenhub.com/workspaces/devx-backlog-board-6009f3d1a7a39b001018f159/issues/celo-org/celo-monorepo/7307 to track adding minimal unit tests you mentioned were needed to feel confident with the fix
