### ISSUE TITLE
App get crash while opening after install 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#5958]
**Frequency:** 100%
**Repro on build version:** Android  v1.6(1001148596)
**Does not repro version** play store build  v1.5.5
**Repro devices** Samsung Galaxy A5(7.0),Vivo V11 pro (10),Galaxy J5 Prime(8.0.0), K7i(LG-X230I)(6.0)
**Repro Steps:**

1. Download the apk file V1.6
2. Open the app & observe ,

**Investigation:** we are tried on this device ( Samsung Galaxy A5(7.0))but not able  to installed this APK (app-mainnet-x86_64-release.apk,app-mainnet-x86-release.apk)

**Current Behavior:**  App get crash while opening after install 
**Expected Behavior:**  User should able to open the app after install 
**Impact:** USer gets blocked to open the app 
**Attachment:**  [CrashV1.6.mp4](https://drive.google.com/file/d/1JwCcys6SOzIlsm2pR9PuBGsBtc8dmsoI/view?usp=sharing)

**Comment by jeanregisser** [comment]
Caused by the segment library update, only in release builds:

```
java.lang.AssertionError: Could not create instance of com.segment.analytics.p.
                         E  java.lang.NoSuchMethodException: <init> [interface java.util.Map]
                         E      at com.segment.analytics.u.a()
                         E      at com.segment.analytics.u.a()
                         E      at com.segment.analytics.u.a()
                         E      at com.segment.analytics.w.h.e()
                         E      at com.segment.analytics.v.a.a.a.a()
                         E      at com.segment.analytics.i.a()
                         E      at com.segment.analytics.i$j$a.a()
                         E      at com.segment.analytics.l.a()
                         E      at com.segment.analytics.i.a()
                         E      at com.segment.analytics.i$j.a()
                         E      at com.segment.analytics.a.a()
                         E      at com.segment.analytics.a$a.run()
                         E      at android.os.Handler.handleCallback(Handler.java:739)
                         E      at android.os.Handler.dispatchMessage(Handler.java:95)
                         E      at android.os.Looper.loop(Looper.java:148)
                         E      at android.app.ActivityThread.main(ActivityThread.java:5417)
                         E      at java.lang.reflect.Method.invoke(Native Method)
                         E      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                         E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by Lss-Ankit** [comment]
@jeanregisser We have verified this issue on latest Android internal build v1.6.0(1004294325) and found issue is fixed so we are closing this ticket
