### ISSUE TITLE
App get crash when user tap on “X”(Close) button on scan page

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#5964]
**Frequency:** 80%
**Repro on build version:** Android  v1.6
**Does not repro version** APp store build  v1.5.5
** repro devices** Samsung Galaxy A5(7.0),Vivo V11 pro (10)
**Does not repro on Devices:* iPhone 6+ (12.4.5)
**Repro Steps:**

1. install the app & login with test account
2. Tap on scanner icon on home page 
3. Tap on X button on scan page 
4. continue same process for 4-5 times
5. Observe app get crash 

**Current Behavior:**  App get crash when user tapping on X button scan page 
**Expected Behavior:**  User should able to close the scan page 
**Impact:** USer gets blocked to close the scan page 
**Attachment:** 
[scannercrash.mp4](https://drive.google.com/file/d/1pzpNym5kBXCk4PPEDgOvZOmWwUGlMicM/view?usp=sharing )
[celo_logs (1).txt](https://drive.google.com/file/d/1RX63_Ctqqj48CtcfDJR5kP4SlXVZjH6V/view?usp=sharing )

**Comment by ValoraQA** [comment]
Hi @nityas I have verified this issue using latest  Android Internal Build V1.11.1(1004294338) & observed that issue is fixed now. Hence closing this ticket.
**Verified on Devices:** Samsung Galaxy A5(7.0),Vivo V11 pro (10.0)
