### ISSUE TITLE
Account Key accessible without PIN

### ISSUE THREAD

**Issue by dominiquejane** [celo-org/celo-monorepo#5985]
### Expected Behavior
App should require PIN when accessing Account Key from the Menu.

### Current Behavior
Tapping Account Key in the Menu, and then pressing the back button, takes you straight to the Account Key screen without having to enter in a PIN

Reproduced in Android 1.5.5 and iOS 1.6.0
[Logs](https://groups.google.com/a/clabs.co/g/support/c/H_Fp77ESmsg)

**Comment by gnardini** [comment]
Fixed by #6002
