### ISSUE TITLE
App get crash when user trying to enter phone number on Account Info screen using lower internet connection

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#5989]
**Frequency:** 100%
**Repro on build version:** V1.6.0(1004294326)
**Repro on devices:** Samsung Galaxy A5(7.0)
**Does not repro devices** Realme 6i(10.)
**Testing Account:**  / Backup Key: 6803331978
**Pre-condition:** Users should use applications on lower internet connection.
**Repro Steps:**
1. Launch the application & go through walkthrough screens.
2. Tap on Get Started button
3. Now tap on the ‘Create new account’ option.
4. Tap on the ‘Accept’ button on the Terms and conditions page.
5. Now tap on the Phone Number field & try to enter the phone number.
6. Observed that,
**Current Behavior:**  The app crashes when the user tries to enter a phone number.
**Expected Behavior:**  Users should redirect to the Create PIN screen when the user enters their phone number.
**Impact:** User gets blocked from the login app.
**Attachment:**  [PhoneNumberCrash.mp4](https://drive.google.com/file/d/1-qjkegsl6UBSh52_9dOCkWRwmrGe-cQv/view?usp=sharing) [Issue observed at 0.54 sec]
**Crashlog**: [celo_logs.txt](https://drive.google.com/file/d/1SnflzcJ3qt_CFdbdazuLVexUL6Z43Tof/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
Hi @annakaz We have performed BVT testing on Androd build V1.5 & IOS Test flight build V1.6  and observed the followings 

**For V1.5 build**
- App get crash when user try to enter phone number on signup flow in V1.5 build 
**Repro on device:** Google pixel 2 (11)  [Crashlogs:](https://drive.google.com/file/d/1pY-_GpAq2rKFAxGIEm9UPVA-CXQBQW_9/view?usp=sharing) 
**Issue does not repro on device:** Samsung Galaxy A5(7.0), Samsung Galaxy S8 (9) 
- Also, We have not observed any crash on iOS in V1.5 build. 

**For V1.6 build**
- App get crash when user try to enter phone number on signup flow in V1.6 by using 3G network 
Repro on Device: iPhone 6+(12.4.5), Samsung Galaxy A5(7.0),
- Note: Crash does not observed when we are performing BVT testing on v1.6 using 4G / Solid wifi connection. 

- While performing regression testing we have found crash on scan page https://github.com/celo-org/celo-monorepo/issues/5964

**Comment by etuleu** [comment]
My guess is that this is the geth issue not being able to connect in 30 seconds and then crashing the app on purpose. So I don't think it is related to the place you were in the app at the time necessarily, but still worth looking into it more. Ankit will test 1.7 which has forno mode on where this crash should not happen.

**Comment by Lss-Ankit** [comment]
Hey @etuleu I have verified this issue on latest Android internal Build V1.7.2(1004294329) & observed that issue is fixed now.
**Verified on devices:** Samsung Galaxy A5(7.0)
**Observation:** It is observed that loading indicator displayed for while when user taps on Phone number field.
**Attachment:** [LoadingIndicatorForWhile.mp4](https://drive.google.com/file/d/1JeVuO-uxOxODuS0DLV1eUPVPE2vPQFZD/view?usp=sharing)

**Comment by jeanregisser** [comment]
Thanks! Closing this then!
