### ISSUE TITLE
Continuous loading indicator is shown when a user proceeds for payment after navigating back from Enter PIN screen by tapping on < arrow.

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#5991]
**Frequency:** 100%
**Repro on build version:**  v1.6.0(1004294326)  and Test Flight build v1.6.0(37)
**Repro on devices:** iPhone SE 2 (14.2) , Google Pixel Xl (8.1) 
Testing Account:  515 444 0200/ [Backup Key](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit#gid=0)

**Repro Steps:**
1. Launch the application & login with a test account.
2. Tap on Send button. 
3. Tap on any contact user. 
4. Enter an amount tap on review button. 
5. Tap on Send button. 
6. Make sure the Enter PIN screen is shown. 
7. Tap on < Arrow from Enter PIN screen 
8. Tap on Send button again and observe. 

**Current Behavior:**  Continuous loading indicator is shown
**Expected Behavior:**  User should be able to do payment 

**Impact:** User is blocked to payment when navigate back from Enter PIN screen 

**Investigation:** Issue does not repro after kill and relaunch the app 

**Attachment:**  BackbuttonIssue.mp4 (https://drive.google.com/file/d/13qSIRTJGkHhEzLx7fhHFlSQPtbmV-Khu/view?usp=sharing) (Bug Observe at  10 sec )

**Comment by ValoraQA** [comment]
Hi  I have verified this issue using latest Test Flight Build V1.11.1(48) & Android Internal Build V1.11.1(1004294339) & observed that issue is still reproduced.
**Verified on Devices:** Samsung Galaxy A5(7.0), iPhone SE (14.2)

**Comment by ValoraQA** [comment]
Hi I have verified this issue using latest Appstore build V1.15.2 & Android Internal Build V1.15.2 and found issue is fixed so, closing this ticket.
**Verified on Devices:** iPhone 6+(12.4.5), Vivo v11 pro (10)
