### ISSUE TITLE
"Setting” button displayed instead of “Set”button if the user tries to set birthdate on a simplex page.

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#6006]
**Frequency:** 100%
**Repro on build version:** V1.5.5
**Repro on devices:** Realme 6i(10.0)
**Does not repro devices**	Samsung Galaxy A21(10.0),Samsung Galaxy S8 (9), Google pixel 2(11)
Testing Account:  / Backup Key: 680331978
gather secret proof essence text sunny inform zone second luxury evidence raccoon expire link thrive spy female spread fame symptom grass consider arena region 
**Repro Steps:**
1. Launch the application & login with a test account.
2. Go to the Add and Withdraw section & tap on Add Funds option.
3. Select Cello Dollar from Digital Currency & select Debit or credit card option from Pay With section.
4. Tap on the Next button.
5. Paste cUSD address & tap on Continue button.
6. Now tap on to the Date of birth section on the Order Summary page.
7. Observed that,
**Current Behavior:**  Setting button is displayed instead of Set on Calender.
**Expected Behavior:**  Set page should display on the calendar window.
**Impact:** Bad user experience.
**Attachment:**  [SetButtonShouldDisplay.jpg](https://drive.google.com/file/d/1GnIdfrQYUaPc0i7IDDZ300TcltMmxqty/view?usp=sharing)

**Comment by gnardini** [comment]
Unfortunately, there's nothing we can do with this since this is Simplex's code and we can't modify it.

Closing it since there's no action for us to take :/

**Comment by ValoraQA** [comment]
Hey @gnardini we have verified this issue in latest Android Internal build V:1.23.0 and observed that Simplex Site UI is changed
**Refer attachment :** [Simplex_newUI.mp4](https://drive.google.com/file/d/1X9dUankp-E17Z2L01KZh7QwBgnCkFViX/view?usp=sharing)
**Checked on Device :** OnePlus 7t(11.0)
