### ISSUE TITLE
Users SNBAT use autoCorrect when restoring their wallet

### ISSUE THREAD

**Issue by drklee3** [celo-org/celo-monorepo#602]
### Expected Behavior

autoCorrect should not be usable / show up when inputting a user's backup key.

### Current Behavior

autoCorrect works in certain the backup key is saved entirely in autocomplete options after manually typing it in once (using SwiftKey keyboard).  autoCorrect still shows [despite having the prop disabled](https://github.com/celo-org/celo-monorepo/blob/master/packages/mobile/src/import/ImportWallet.tsx#L168).

Using `keyboardType="visible-password"` does hide the auto complete options, but it does not work with multiline. (Backup key will be input in a single line)

![restore_autocorrect](https://user-images.githubusercontent.com/22536567/63188175-94837480-c015-11e9-8429-09f127520952.gif)

**Comment by jeanregisser** [comment]
See recent discussion https://celo-org.slack.com/archives/CD03BK79B/p1599751215015400
