### ISSUE TITLE
Define performance, reliability and usage metrics

### ISSUE THREAD

**Issue by carterqw2** [celo-org/celo-monorepo#6033]
**Acceptance Criteria**

- [ ] Document in notion describing performance, reliability and usage metrics we want to monitor for blockscout.

**Comment by jbsibille** [comment]
https://docs.google.com/spreadsheets/d/1HYdr9L2JCDgHvuCrpzUce-LMTxzclltG5LO638qTuUQ/edit#gid=447598208
