### ISSUE TITLE
Make available API log-based metrics in Metabase

### ISSUE THREAD

**Issue by carterqw2** [celo-org/celo-monorepo#6035]
**Acceptance Criteria**
- [ ] API log-based metrics are available in Metabase

**Comment by yourbuddyconner** [comment]
This task is blocked pending the `Phase 0`, of the Metrics Migration.

Generally it will consist of logs flowing to Loki and either being exported to BigQuery for batch reporting via metabase OR queried directly for real-time reporting via Grafana.
