### ISSUE TITLE
Blockscout Metrics

### ISSUE THREAD

**Issue by carterqw2** [celo-org/celo-monorepo#6037]
### **What's important about this?**
We have defined metrics that define health of the service and we collect minimally necessary information about how users interact with it.

### **What is "done"?**
There is a document defining what metrics we feel right to have for blockscout.
There is a way to know who and how uses the web UI.
We have understanding how and who uses API.
*There is a dashboard that allows to see how metrics we chose to monitor change.*

**Comment by jbsibille** [comment]
What's the concept of a user here?
* [JB] Ask Brynly what we need to do in terms of disclaimer if we gather data
* on the client side: Cookie/user agent
* API: we could introduce api keys. If no api key, rate limit. 
* TODO: JB to checkout: https://console.cloud.google.com/monitoring/dashboards/custom/c3873b1b-b597-40fa-a3f1-2450cbfb5dff?authuser=0&project=celo-testnet-production&timeDomain=1w
* Other TODO: https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%20resource.labels.cluster_name%3D%22mainnet%22%20resource.labels.namespace_name%3D%22default%22%20resource.labels.container_name%3D%22nginx-ingress-controller%22%20httpRequest.status%3E%3D500;timeRange=PT3H?authuser=0&project=celo-testnet-production

**Comment by jbsibille** [comment]
https://docs.google.com/spreadsheets/d/1HYdr9L2JCDgHvuCrpzUce-LMTxzclltG5LO638qTuUQ/edit?usp=drive_web&ouid=104172066676422061805
