### ISSUE TITLE
Design doc for disbursement tool

### ISSUE THREAD

**Issue by carterqw2** [celo-org/celo-monorepo#6043]
**Acceptance Criteria**

- [ ] Actionable design doc ready for implementation.

**Comment by jbsibille** [comment]
https://www.figma.com/file/ivOJJk6f6v3NJtsILeRsdL/Disbursement-Tool-v0.1

**Comment by jbsibille** [comment]
Write down user stories as well.

**Comment by jbsibille** [comment]
How to decide who is admin? 
* For Grameen: was done via cloud provider UI. Could do the same thing for now.
* If open externally: we'll need to build our own UI.

**Comment by carterqw2** [comment]
https://docs.google.com/document/d/1rgjcjEHncEYv5NVkLt4-ICeD2oPxD9dmCIGIo1toQ1I/edit
