### ISSUE TITLE
CIP32 (ASv1 Attestation Incentives)

### ISSUE THREAD

**Issue by alecps** [celo-org/celo-monorepo#6052]
https://github.com/celo-org/celo-proposals/blob/d1b7059b150360976d2df7838ac1ae26098f3627/CIPs/cip-0032.md

**Comment by nambrot** [comment]
Should we break this down? It's feels quite large for a single ticket?

**Comment by alecps** [comment]
@codyborn Is there a way we could split this ticket up into more manageable pieces?

**Comment by yorhodes** [comment]
@codyborn whats the status of this? seems like a high value workstream

**Comment by yorhodes** [comment]
https://github.com/celo-org/celo-proposals/blob/d1b7059b150360976d2df7838ac1ae26098f3627/CIPs/cip-0032.md

**Comment by alecps** [comment]
This may be rendered irrelevant by ASv2, but we should keep it mind when discussing the token curated registry portion of the design

**Comment by alecps** [comment]
Related: https://app.zenhub.com/workspaces/identity-backlog-board-60e61301c3dc55000e540b61/issues/celo-org/celo-monorepo/8921
