### ISSUE TITLE
Global + per-validator verifications dashboard improvements

### ISSUE THREAD

**Issue by alecps** [celo-org/celo-monorepo#6057]

**Comment by alecps** [comment]
(possibly more info from /status endpoints, responses to questions, clarification of cancel/app closed/etc, histogram of attempt counts broken down by user abandonment/cancelation method to differentiate and filter out test users)

**Comment by codyborn** [comment]
> histogram of attempt counts broken down by user abandonment/cancelation method to differentiate and filter out test users

https://github.com/celo-org/clabs-pipeline/pull/34
