### ISSUE TITLE
Attestation Service Observability

### ISSUE THREAD

**Issue by alecps** [celo-org/celo-monorepo#6059]
Catch-all for ASv1 observability

**Comment by codyborn** [comment]
I haven't heard any recent requests for Foundation dashboard. Probably not high-pri.

Opt-in metrics are important only if we need more data than we can currently get from AS. My feeling is that we have enough data to diagnose current issues.

AS focused dashboard for E2E troubleshooting would be nice, but I haven't been asked by Valora support to dig into a case recently so the burden hasn't been high.
