### ISSUE TITLE
Dig through AS logs

### ISSUE THREAD

**Issue by alecps** [celo-org/celo-monorepo#6060]
Support @dominiquejane with incoming verification issues

**Comment by aslawson** [comment]
@timmoreton was this intended to be an extension of the ticket we had in the verification bubble to help customer support review the reported logs. or is this something different specific to the attestation service itself?

**Comment by timmoreton** [comment]
Timebox for any log investigation needed for folks who report verification issues via support

**Comment by aslawson** [comment]
Perfect, that's how I had interpreted it and had added in the description
