### ISSUE TITLE
Investigate what on-chain events (if any) CAP needs alerting for and how to set-up that alerting 

### ISSUE THREAD

**Issue by alecps** [celo-org/celo-monorepo#6068]

**Comment by yorhodes** [comment]
Short team solution is to use metabase pulses to a slack channel for medium severity "real-time" alerting and daily/weekly/monthly summaries. `rc1_eksportisto_11` now exports all core contract events to metabase.
Opened https://github.com/celo-org/celo-monorepo/issues/6556.

Long term solution is to develop a more robust, lower latency alerting pipeline and runbook for on-call engineers to respond to and communicate about high severity on-chain events.
Opened https://github.com/celo-org/celo-monorepo/issues/6557.
