### ISSUE TITLE
Escrow Contract v2 Design Doc

### ISSUE THREAD

**Issue by alecps** [celo-org/celo-monorepo#6083]

**Comment by yorhodes** [comment]
Likely most straightforward implementation: make `Escrow` contract use `AttestationCallProxy`

**Comment by kevjue** [comment]
cc'ing @nambrot @aslawson for additional context.

**Comment by nambrot** [comment]
For anyone on this thread, I'm inclined to reduce the estimate on this to fairly small (0.5?). IMO it seems pretty clear that 

1) Escrow V2 would just reuse the AttestationCallProxy
2) make payment codes optional
3) add an optional expiry

Is there much more design work we are expecting here? I chatted to tariq and this high-level description made sense to him and he'll bring it up with wallet product

**Comment by aslawson** [comment]
@nambrot 

> Escrow V2 would just reuse the AttestationCallProxy

Does this cause complications in other dapps wanting to use the Escrow contract? They will also be required to initialize a AttestationCallProxy?

What did we settle on for the AttestationCallProxy Verification heuristic? Is it hardcoded or set by the client on contract initialization?

**Comment by nambrot** [comment]
The Escrow becomes slightly harder to use, but from an accessibility standpoint it should mostly stay the same.

The heuristic is hardcoded in the hub (https://github.com/celo-org/celo-monorepo/pull/7363/files#diff-85496e4c5be21586d86c366e664937c7d14ecd3054ac10eb621a20adcd7a218eR53), but the client could choose to deploy a different hub if they wanted to (though Valora would need to lookup via that hub as well then)

**Comment by nambrot** [comment]
So currently, to use the escrow you'd do the following:

Create an escrow:
- call `transfer` with all the parameters

Determine if an escrow exists:
- derive payment code from ODIS pepper and check for existence via it

Withdraw:
- call `withdraw` from the account that has attestations


In an EscrowV2 world with the new attestation proxy, usage would look as follows (any usage would likely want to reuse the `IdentityProxyHub` instance that cLabs will be using, so we need to expose a way to access the contract address easily)

Create an escrow:
- Call `getIdentityProxy` on the `IdentityProxyHub` with the `identifier` to get the address of the proxy eligible to withdraw
- Call `deposit`/`transfer` on `EscrowV2` to transfer value

Determine if an escrow exists:
- Call `getIdentityProxy` on any known `IdentityProxyHub` to fetch the proxy address
- Determine if any payment on EscrowV2 is available to withdraw for the proxy address

Withdraw:
- Call `getIdentityProxy` on the `IdentityProxyHub` with the `identifier` to get the address of the proxy eligible to withdraw
- Call `makeCall` on the proxy with `EscrowV2#withdraw` being the destination to transfer the funds

@m-chrzan @kevjue Lmk if that is incorrect

**Comment by asaj** [comment]
Why use an `IdentityProxy` as part of this? It seems like that adds an unnecessary contract deployment into the withdrawal flow.

**Comment by nambrot** [comment]
It mostly made sense from a modularity standpoint, but you are right that it is not as gas efficient. The alternative would be to hardcode a particular heuristic into the Escrow contract/parameterize the Escrow contract with the heuristic, or were you thinking of something else?
