### ISSUE TITLE
Investigate: Transaction Metadata Standards

### ISSUE THREAD

**Issue by alecps** [celo-org/celo-monorepo#6111]
### Expected Behavior

Investigate a solution on top of CIP8

From Slack:
```
Merging all the convos related to transaction metadata:
First started with exploring it to deprecate transferWithComment
Then #eng-wallet brought up the need for better metadata
Then @josh is asking for merchant tx processing
The common factor is to start investigating with 6111, however it will likely grow beyond as truly moving transaction metadata will require:
Making CIP8 more accessible (as for example cash-in providers need to write to their storage)
tx metadata has to be passed through QR code and wallet interfaces (dappkit/walletconnect)
Valora has to migrate it’s various use cases (plaintext, odis metadata)
It has to be documented of course
```

### Current Behavior

Transaction metadata is more often than not stashed into the transfer comment of `transferWithComment`. That has the following downsides:
- It makes transfers cost 30% more gas 
- It's limited in expressiveness

**Comment by nambrot** [comment]
@aslawson I'd move this up to a P2?

**Comment by isabellewei** [comment]
There has been discussion about extending CIP8 to allow accounts to set their profile privacy as public (ie. anyone can view it), which would be great for CICO providers

**Comment by isabellewei** [comment]
For escrow payments, I haven't given this idea extensive thought, but I think CIP8 could be used to associate the invite information to the temp address used for the payment

**Comment by yorhodes** [comment]
closing in favor of https://github.com/celo-org/celo-monorepo/issues/8162 on applications board
