### ISSUE TITLE
Roll-out AS Release 1.2.0

### ISSUE THREAD

**Issue by alecps** [celo-org/celo-monorepo#6112]
Publish latest version following Release Process:
https://docs.celo.org/community/release-process/attestation-service

**Comment by timmoreton** [comment]
See https://docs.celo.org/community/release-process/attestation-service

- [x] Set up, fund, KYC MessageBird account (Amy funded)
- [x] Deploy a pre-release build to a baklava validator (Tim can help)
- [x] Once it looks happy, cut the build and deploy it to alfajores and set up MB
   - [x] configure to randomize between Telekom and others
   - [x] add credentials to `.env.mnemonic.alfajores`
   - [x] need to update celotool and helm chart to pass through additional params
   - [x] `bin/celotooljs.sh deploy upgrade attestation-service -e alfajores` (`--verbose` will help if you hit issues)
   - [x] check status pages: `https://alfajores-attestation-service.celo-testnet.org/0/status`
   - [x] before check in do `yarn run keys:encrypt` (may overwrite extra stuff) 
- [ ] Run the e2e tests from branch `verification-e2e-tests`:
   - [ ] `yarn test:e2e:ios -t e2e/src/RedeemInviteAndVerify.spec.js`
   - [x] according to @gnardini this is not working anymore
- [x] will want to deploy an attestation bot in alfajores too  -- see baklava for example

**Comment by aslawson** [comment]
@AlexBHarley any remaining work on this?
