### ISSUE TITLE
Account key words missing after setting up account key

### ISSUE THREAD

**Issue by dominiquejane** [celo-org/celo-monorepo#6127]
### Expected Behavior
After setting up account key, the user is taken to their account key screen

### Current Behavior
Account key screen has no account key

![image](https://user-images.githubusercontent.com/14333164/101387171-513cbd00-387b-11eb-9ba6-06dc21460b61.png)

**Comment by tarikbellamine** [comment]
My guess is this is related to skipping the pincode screen or the account otherwise failing to unlock, which results in the mnemonic not being accessible.

**Comment by dominiquejane** [comment]
Closing because it's being addressed in PR #6002

**Comment by dominiquejane** [comment]
Going to let PR #6002 close this instead

**Comment by Lss-Ankit** [comment]
added comment and reopened https://github.com/celo-org/celo-monorepo/issues/4396 as this is duplicate of it
