### ISSUE TITLE
Setup Docusaurus configuration and remove unnecessary files

### ISSUE THREAD

**Issue by barbaraliau** [celo-org/celo-monorepo#6159]

**Comment by AlexBHarley** [comment]
I setup Docusaurus v2.0 for a side project recently and it's now a fully fledged static site generator. That means by default it renders a website at `/`, docs at `/docs` and a blog at `/blog`.

Quick tip to get _just_ a documentation build setup (which is what I think we want given our docs lie at docs.celo.org). 

- Delete `src/pages/index.js` but leave the `src/pages` folder
- Set base URL to `/`
