### ISSUE TITLE
User SBAT tap words in their account key when resetting their account.

### ISSUE THREAD

**Issue by dominiquejane** [celo-org/celo-monorepo#6173]
### Expected Behavior
User SBAT tap words in their account key when resetting their account.

### Current Behavior
The entire screen is blank except for the words "What's the first word of your Account Key"

This was reported by a user and the support agent was able to reproduce this bug after a few attempts to reset their account.

Possibly related to #6127 

[Sentry Report](https://sentry.io/organizations/celo/issues/2017790699/?end=2020-12-08T22%3A48%3A01&project=1250733&query=is%3Aunresolved&start=2020-12-08T22%3A09%3A42)

[Logs from support center agent](https://groups.google.com/a/clabs.co/d/msgid/support/3026D7F3-CD72-4B1B-90F0-6FB8EFB90F21%40icloud.com)

[Logs from user](https://groups.google.com/a/clabs.co/d/msgid/support/CAPQx-bFmQN16kXFsrsCK_oaSsz1KQUZ%2B%3D9uEvU6HTyX%2BLySrwg%40mail.gmail.com)

[Video](https://slack-files.com/T01EJ9REZPH-F01GUC3QCCR-68aaf19d89)

![Screen Shot 2020-12-09 at 12 43 12 PM](https://user-images.githubusercontent.com/14333164/101679105-1b830a00-3a1c-11eb-93df-d84af84efb26.png)

**Comment by tarikbellamine** [comment]
After seeing the video for this, I believe there is a high probability that this is caused by #6127

**Comment by dominiquejane** [comment]
Closing because it's being addressed in PR #6002

**Comment by dominiquejane** [comment]
Going to let PR #6002 close this
