### ISSUE TITLE
Reduce the # of libraries that the SDK uses to reduce bundle size 

### ISSUE THREAD

**Issue by barbaraliau** [celo-org/celo-monorepo#6190]

**Comment by aslawson** [comment]
closing is this is a generalization of the specific work specified by 
[Break up Utils Package](https://app.zenhub.com/workspace/o/celo-org/celo-monorepo/issues/6189)
[remove moment dependency from contractkit
](https://app.zenhub.com/workspaces/devx-backlog-board-6009f3d1a7a39b001018f159/issues/celo-org/celo-monorepo/7357)
[nodegyp dependency is removed](https://app.zenhub.com/workspaces/devx-backlog-board-6009f3d1a7a39b001018f159/issues/celo-org/celo-monorepo/6191)
