### ISSUE TITLE
Set up automatic releases for all 15 sdk packages 

### ISSUE THREAD

**Issue by barbaraliau** [celo-org/celo-monorepo#6195]
does not include CLI

**Comment by aslawson** [comment]
@medhak1 
there was a duplicate
https://app.zenhub.com/workspaces/devx-backlog-board-6009f3d1a7a39b001018f159/issues/celo-org/celo-monorepo/3992

posting here in case there was anything relevant

**Comment by barbaraliau** [comment]
Came across this PR https://github.com/celo-org/celo-monorepo/pull/5744. Not sure how relevant it still is. @medhak1

**Comment by medhakothari** [comment]
Yah it doesn't fully work with the new package split but that what I'm aiming to refactor to finish off this issue! @barbaraliau 

update: started creating a script to automate the process a bit more, testing it on the release today!
