### ISSUE TITLE
Attestation Service: Migration management

### ISSUE THREAD

**Issue by joe-bowman** [celo-org/celo-monorepo#6207]
### Expected Behavior

If the database is unmigrated, the attestation service should fail to start.

### Current Behavior

If the attestation service is run against an unmigrated database, it doesn't error until an attestation is attempted. 

### Suggestion
Maintain a 'database version' field, and check this is appropriate on startup.
Alternatively, attempt to run the migration action on startup.

**Comment by aslawson** [comment]
This could be a nice-to-have improvement for attestation setup, but doesn't feel its super high priority right now. We don't see this causing many issues and if it did, Validators have caught the issue quickly and recovered.

I am going to close for now as "won't do," but we can revisit if this seems to be a persistent error with attestation service operators.
