### ISSUE TITLE
New Storage Variables should be initializable as part of the release process

### ISSUE THREAD

**Issue by nambrot** [celo-org/celo-monorepo#6232]
### Expected Behavior

As a PR author, I should have an easy way to specifying that I want the new storage variable to be initialized

Technically, constitution threshold setting similarly could fall under this purview, however it is unlikely that a function needs to be protected in the same tx, and thus again a concurrent proposal could be used.

### Current Behavior

When making a logic contract change that requires a new storage variable, the release process cannot express that it needs to be initialized. For changes that can gracefully handle an empty variable, this is not necessary as a concurrent proposal is possible.

**Comment by yorhodes** [comment]
Contract changes for release 3 were modified to maintain the invariant of not requiring a new storage variable to have a value initialized atomically during a governance upgrade (see #4747, #6287). This is in contrast with new storage and implementation pairs that require initialization (ie for `Registry` address: see #5604). This invariant allows voters to separate concerns of implementation logic from parameterization for core contracts, and mitigates potential for catastrophe on core contracts during upgrades.
