### ISSUE TITLE
ODIS - Add unit tests for Common library

### ISSUE THREAD

**Issue by codyborn** [celo-org/celo-monorepo#6254]
Currently to test the phone-number-privacy-common package, we have to publish it and consume it in the signer/combiner tests. We should have some unit tests to validate it prior to publishing.

**Comment by codyborn** [comment]
Bumping up the priority since this is a blocker for other high priority items.

**Comment by emilhotkowski** [comment]
What do we want to test in common package?
So far I see that whole **input-validation** file is full of useful code that should be tested. Anything else?
@alecps @codyborn

**Comment by emilhotkowski** [comment]
This is what so far I've got.
https://imgur.com/y9QhFJZ
