### ISSUE TITLE
getBlockRandomness SBAT succeed on pending block even after addRandomness is called

### ISSUE THREAD

**Issue by kevjue** [celo-org/celo-monorepo#6258]
### Expected Behavior

A node should be able to call `getBlockRandomness` of the previous epoch's last block on the Random.sol smart contract on a pending epoch last block even after `addRandomness` is called.

NOTE:  This is a subtle and low priority bug and not currently affecting us.  In fact, adding a comment describing this subtle bug in the `getBlockRandomness` and the `addRandomness` is probably sufficient.

### Current Behavior

`addRandomness` will delete the randomness of the previous block's last block when it's called on a pending block (https://github.com/celo-org/celo-monorepo/blob/master/packages/protocol/contracts/identity/Random.sol#L121).  That means that if `getBlockRandomness` is called again on that pending block, an exception will be thrown (https://github.com/celo-org/celo-monorepo/blob/master/packages/protocol/contracts/identity/Random.sol#L184).

This is related to this issue:  https://github.com/celo-org/celo-blockchain/issues/999

**Comment by nambrot** [comment]
@kevjue Can you maybe expand on what the bug here is? IMO the contract works as expected, and the call should be made with historical state trie?
