### ISSUE TITLE
Licenses screen doesn't load

### ISSUE THREAD

**Issue by jmrossy** [celo-org/celo-monorepo#626]
### Expected Behavior

Loads license list.

### Current Behavior

Just sits on spinner (tested on prod build)

**Comment by emberian** [comment]
still doesn’t load for me in iOS 1.5.1

**Comment by emberian** [comment]
![22620FBD-81A9-49B9-B68E-D8C925D0FE69](https://user-images.githubusercontent.com/704250/67991585-ed1ae480-fbf6-11e9-8951-3521f2a49af9.png)

**Comment by jmrossy** [comment]
@cmr yes known issue for iOS. Thanks for the heads up, I'll reopen this now
