### ISSUE TITLE
Update CICO radio button component with new design

### ISSUE THREAD

**Issue by dominiquejane** [celo-org/celo-monorepo#6270]
New designs available on [Figma](https://www.figma.com/file/zt7aTQ5wuXycIwxq5oAmF9/Wallet-Refresh?node-id=3005%3A42941)
If link doesn't work, it's in Wallet Refresh > Pages: Design Kit > Frame labelled "UI Controls"

![Screen Shot 2020-12-16 at 11 38 18 AM](https://user-images.githubusercontent.com/14333164/102391624-33660b00-3f93-11eb-8ac6-6e4f87fd8bde.png)

**Comment by michellewong793** [comment]
which screens do we need this changed on specifically?

**Comment by gnardini** [comment]
Isn't this how it looks right now? Is this an old issue or are there any changes needed?

**Comment by gnardini** [comment]
@michellewong793 
The screen that uses this can be accessed by the `And and Withdraw` item on the side drawer and tapping on `Add Funds`:

<img width="365" alt="Screen Shot 2021-01-14 at 18 36 03" src="https://user-images.githubusercontent.com/6062888/104652083-5cafaf00-5697-11eb-8562-0be45cb427ed.png">
