### ISSUE TITLE
Consider not persisting exchange rate history

### ISSUE THREAD

**Issue by gnardini** [celo-org/celo-monorepo#6284]
### Expected Behavior

Exchange rate history is not persisted in the Redux state. See if it's cached at the Firebase lib layer.

### Current Behavior

We have a bug in our code where the exchange rate history gets stored multiple times in our redux state.

Quoting from this issue: https://github.com/celo-org/celo-monorepo/pull/6273
> On one of my tests, I noticed that the size of the Redux store was getting bigger and bigger. Upon closer inspection, it was the history we use for the CELO/cUSD exchange rate that was growing at a rate of ~100kb sometimes when restarting the app. [...]
There are more details on what is failing on that PR, but unlimited growth of the persisted Redux state is definitely concerning.

One comment by @jeanregisser was:
> Interesting, it looks like we can even go as far as not persisting the exchange rate history in Redux, as I think it's already cached at the firebase lib layer.

**Comment by tarikbellamine** [comment]
Upping priority to P1 because we have reason to believe this is bloating redux state to the point that it's triggering app crashes
