### ISSUE TITLE
[Wallet] e2e test fails if the Send button is spinning

### ISSUE THREAD

**Issue by etuleu** [celo-org/celo-monorepo#6296]
### Expected Behavior

e2e test passes successfully the Send screen

### Current Behavior

It fails because the button is still spinning probably because geth is still connecting.

<img width="1680" alt="Screen Shot 2020-12-18 at 10 01 33 AM" src="https://user-images.githubusercontent.com/674143/102645984-2d4d6700-4118-11eb-9356-f8e40a9c971b.png">

**Comment by gnardini** [comment]
Some more context, these are the error logs when this error happens:

```
[Fri Dec 18 2020 16:08:45.203]  INFO     identity/privateHashing@fetchPhoneHashPrivate :: Unknown error :: Unknown Client Error 404 in http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:384371:44
step@http://localhos
[Fri Dec 18 2020 16:08:45.206]  INFO     identity/contactMapping@fetchAddressesAndValidateSaga :: Error fetching addresses :: saltFetchFailure in fetchPhoneHashPrivate$@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:456206:
[Fri Dec 18 2020 16:08:45.209]  DEBUG    redux/saga@logger/{"type":"ALERT/SHOW","alertType":"error","displayMethod":0,"message":"Failed to retrieve phone number secret","dismissAfter":5000,"buttonMessage":null,"action":null,"title":null,"underlyingError":"saltFetchFailure"}
```

And the red error banner pops up with the message `Failed to retrieve phone number secret`

**Comment by gnardini** [comment]
This was an ODIS failure that has already been resolved, closing.
