### ISSUE TITLE
Celo: <wallet not received Celsius >

### ISSUE THREAD

**Issue by Thomashadley89** [celo-org/celo-monorepo#6345]
*Describe your issue here.*
I have recently got myself a celsius wallet on my android phone and deposited xrp and tether fine.
I bought some Celsius this morning from my coinbase wallet and transferred it to the wallet, the confirmation code is here https://explorer.celo.org/address/0x57e83da4e9c0d1a9f3643aec62b04c5c21a86477/transactions

but no celsius in my wallet as of 18:36.  I am a uk resident, would this be why? 

### Environment
* Elixir Version: 1.9.0
* Erlang Version: 22
* BlockScout Version: 330e57bb88472a655cb1b67d70131d8ecef56e49

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36`

### Steps to reproduce ... no idea!

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour. celsius depoosited in my celsius app  

*Tell us what should happen.*

### Actual Behaviour  - no celsius in my wallet
![Screenshot_20201223_182833_network celsius wallet](https://user-images.githubusercontent.com/76533764/103027590-11015e00-454e-11eb-953b-b1fd755a8675.jpg)

*Tell us what happens instead.*

**Comment by dominiquejane** [comment]
@Thomashadley89 
Hi, Coinbase does not support Celsius. Did you mistakenly buy CGLD or CELO?
You may be able to recover your CELO if you have the private key for your celsius wallet.
If you would like some help in this matter I can walk you through some steps that may be able to help you recover your funds.

**Comment by Thomashadley89** [comment]
Hi

Thanks for your reply and yes that's right I did mistake it for celo.

I do have my private key, so I take it I need to ggo to a wallet that
supports celo or cgld and then could get my funds back?

Tom

**Comment by dominiquejane** [comment]
@Thomashadley89 
Yes, you can use the [instructions](https://docs.celo.org/celo-owner-guide/eth-recovery) here to do so.
Let me know if it works!
