### ISSUE TITLE
Valora is unable to load in debug mode

### ISSUE THREAD

**Issue by tarikbellamine** [celo-org/celo-monorepo#6346]
### Expected Behavior
Valora should be able to run in debug mode.

### Current Behavior
Valora shows a blank white screen when put into debug mode. Suspect it has something to do with TurboModules and PR #5967.

More context: https://celo-org.slack.com/archives/CL7BVQPHB/p1608686939496200

**Comment by jeanregisser** [comment]
This has been fixed.
