### ISSUE TITLE
Can't read LockedGold contract info from blockscout

### ISSUE THREAD

**Issue by critesjosh** [celo-org/celo-monorepo#6348]
### Expected Behavior

I should be able to look up info about the LockedGold contract via Blockscout, [here](https://explorer.celo.org/address/0x6cc083aed9e3ebe302a6336dbc7c921c9f03349e/read_contract).

### Current Behavior

All I see is `error`.

![image](https://user-images.githubusercontent.com/18372439/103040571-da254b00-4541-11eb-9b37-374a33369555.png)

**Comment by AlexBHarley** [comment]
@carterqw2 I'm still having issues with this. I now get a link to the implementation when I'm on /read-proxy

**Comment by carterqw2** [comment]
The problem is that the new implementation contract (https://explorer.celo.org/address/0xc683d91656ED9024ADDD7a40A181398E0258283F/transactions) is not verified, that's why Blockscout can't get the ABI and render the form.

**Comment by AlexBHarley** [comment]
Who do we need to ping for that?

**Comment by carterqw2** [comment]
I think @yorhodes was checking what's possible there
