### ISSUE TITLE
Add and Withdraw Screen: Update subtitles 

### ISSUE THREAD

**Issue by coreycelo** [celo-org/celo-monorepo#6351]
### Expected Behavior

Subtitles on Add and Withdraw Landing screen should be as follows:

**Add Funds**
"Fund your Valora account"

**Cash Out**
"Send funds to an exchange or another account"

<img width="386" alt="Screen Shot 2020-12-23 at 3 30 23 PM" src="https://user-images.githubusercontent.com/51388535/103044034-dbe81200-4533-11eb-9a9f-43d4a0fa2902.png">

### Current Behavior

**Add Funds**
"Purchase cUSD or CELO" 

**Cash Out**
"Exchange cUSD or CELO for another currency"

**Comment by michellewong793** [comment]
on it!

**Comment by michellewong793** [comment]
https://github.com/celo-org/celo-monorepo/pull/6424 addresses this issue
