### ISSUE TITLE
Order summary section is not fit to screen on “connecting to simplex for purchase” page 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#6354]
**Frequency:** 100%
**Repro on build version:**  V1.7.2(39)
**Repro on devices:** iPhone 6+(12.4.5)
**Does not repro devices** Samsung Galaxy A5(7.0), iPhone XR (14.2)
**Testing Account:  / Backup Key:** 
515 444 0200
library huge cram diet document mimic pink trade invest arm catalog feature ocean muscle either try include canoe awful just brief proof idea figure
**Pre-condition:** User should run the application in the background.
**Repro Steps:**

- Launch the application & login with a test account.
- Tap on hamburger menu> ADd and withdraw 
- Tap on add funds button
- select Celo dollar & Debit card or bank account 
- Copy paste the account address
- Tap on continue button
- Observed Order summary is not fit to the screen

,
**Current Behavior:** Order summary section is not fit to screen 
**Expected Behavior:**  Order summary section should fit to screen.
**Impact:**  Bad user experience / UI
**Attachment:**  [OrderSummary.mp4](https://drive.google.com/file/d/1ji7Hy4Y46I8QO3m26lk63Gt8htmkrE5P/view?usp=sharing)

**Comment by tarikbellamine** [comment]
This is a Simplex issue that we unfortunately can't control.

**Comment by ValoraQA** [comment]
Hey @tarikbellamine we have verified this issue in latest Android Internal build V:1.23.0 and observed that Simplex Site UI is changed
Refer attachment : [Simplex_newUI.mp4](https://drive.google.com/file/d/1X9dUankp-E17Z2L01KZh7QwBgnCkFViX/view?usp=sharing)
Checked on Device : OnePlus 7t(11.0)
