### ISSUE TITLE
App get crash when user try to enable ‘Data Saver Toggle’ again after restarting app automatically from ‘Restart To Switch’ option from setting

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#6356]
**Frequency:** 100%
**Repro on build version:** Android Internal Build V1.7.2(1004294329)
**Does not repro version** Play Store Build V1.6.0
**Repro on devices:** Samsung Galaxy A5(7.0)
**Does not repro devices** Galaxy J5 Prime(8.0), LG K7i(6.0)
Testing Account:  / Backup Key: (680) 333-1978
gather secret proof essence text sunny inform zone second luxury evidence raccoon expire link thrive spy female spread fame symptom grass consider arena region 
**Pre-condition:** User should have performed Data saver toggle on & off action once before & app should restart automatically.
**Repro Steps:**
1. Launch the application and login with a test account.
2. Go to settings & disable ‘Data Saver Toggle’ & app should start automatically.
3. Now the user is on the Home screen .
4. Again go to setting & try to disable ‘Data Saver Toggle’.
5. Observed that,
**Current Behavior:**  App get crash when user taps on ‘Enable Data Saver’ toggle
**Expected Behavior:**  User should able to turn ON & OFF Data Saver toggle
**Impact:** User get blocked to proceed further
**Attachment:**  [CrashWhenUserTapsOnDataSaverToggle.mp4](https://drive.google.com/file/d/1ZX7hb0kJZzZrrsjgnXa2oqRTlF7SeGAW/view?usp=sharing)

**Comment by jeanregisser** [comment]
@Lss-Ankit could you provide the logs?

**Comment by Lss-Ankit** [comment]
hi @jeanregisser I have verified this issue with low network issue & here are logs:
[celo_logs .txt](https://drive.google.com/file/d/1PH32DxTpUPKubinT_TYv1baJUsCWubbU/view?usp=sharing)

**Comment by ValoraQA** [comment]
Hey @jeanregisser I have verified this issue using  latest Android internal build V1.15.1 and Test Flight 1.15.1 & observed that issue is fixed now.
**Verified On Devices:** Samsung Galaxy A5(7.0),  Samsung Galaxy Note 5(7.0)
