### ISSUE TITLE
‘Your current balance is not high enough to complete the verification process’ error message displayed on ‘Phone Number’ screen.

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#6358]
**Frequency:** 100%
**Repro on build version:** Android Internal Build V1.7.2(1004294329)
**Repro on devices:** Samsung Galaxy S4(4.4.2)
**Does not repro devices** Samsung Galaxy A5(7.0)
Testing Account:  / Backup Key: 7155002148
**Pre-condition:** User should open application on lower end devices.
**Repro Steps:**
1. Launch the application & go through welcome screens.
2. Tap on the ‘Create New Account’ button & fill all the details.
3. Tap on the Next button & create PIN.
4. Now the user should be on the ;Phone Number’ screen.
5. Observed that,
**Current Behavior:**  ‘Your current balance is not high enough to complete the verification process’ error message is displayed with skip for now button.
**Expected Behavior:**  User should be able to confirm phone number without any fund required message.
**Impact:** User not able to complete verification flow when the user does not have an amount in account.
**Attachment:**  [FundRequiredMessageShouldNotDisplay.jpg](https://drive.google.com/file/d/1H9HxnMQCbyL9f5_cNgD-hOLJO_M8x_Q7/view?usp=sharing)

**Comment by i1skn** [comment]
@Lss-Ankit can you please attach logs?

**Comment by Lss-Ankit** [comment]
Hi @i1skn Here are logs:
[celo_logs_1.txt](https://drive.google.com/file/d/1fYhxtcPjLC8QVnQl-JhMJYmkp58c_Dp9/view?usp=sharing)

**Comment by i1skn** [comment]
Ok, I see the following error: `Error occured while fetching verification state :: KomenciDown in KomenciDown`. Closing this one as this is expected behaviour when Komenci is down. Also in the upcoming releases we would add retry logic, when Komenci is down.

**Comment by Lss-Ankit** [comment]
Thanx @i1skn for update. We will verify this ticket in next upcoming build.

**Comment by Lss-Ankit** [comment]
Hi @i1skn 
FYI: We observed following observations

- It is observed that this message displayed if user login with fresh account with strong network connection.
**Verified on devices:** Samsung Galaxy S4(4.4.2)

- Also it is observed that same message display if we tap on start button after turning off network connection on Phone Number  Confirmation screen.
**Verified on devices:** Samsung Galaxy A5(7.0) , ,iPhone 6+ (12.4.5)
Let me know needful.
