### ISSUE TITLE
cEUR support for contractkit

### ISSUE THREAD

**Issue by medhakothari** [celo-org/celo-monorepo#6365]
### Expected Behavior

Once cEUR is deployed, the cli and the contractkit will need to be updated. See the proposal [here](https://github.com/celo-org/celo-proposals/pull/124/files#diff-5bfc24539524546f5862a63ebc12d72bf00226660eaabdadc757b575da497f43R74
). 

Detailed breakdown of changes:

- [x] Add cEUR to the appropriate enums/functions/variables here: [https://github.com/celo-org/celo-monorepo/blob/master/packages/sdk/base/src/currencies.ts](https://github.com/celo-org/celo-monorepo/blob/master/packages/sdk/base/src/currencies.ts)

- [x] Set up new wrappers for ExchangeEUR and StableTokenEUR:
    - Following the discussion here [https://celo-org.slack.com/archives/C014SRL4URY/p1613486582377400](https://celo-org.slack.com/archives/C014SRL4URY/p1613486582377400), the current plan is to:
        - Pull core logic from ExchangeWrapper into a new class, `BaseExchangeWrapper` (WIP name), which is intended to serve as a superclass of ExchangeWrapper and a new wrapper, ExchangeEURWrapper. There are some functions with dollar-specific names, like `sellDollar`, `buyDollar`, `quoteUsdSell`, `quoteUsdBuy`, `getUsdExchangeRate`. The plan is to generalize those names in `BaseExchangeWrapper` to work for all stables, like `sellStable`, or `quoteStableBuy`, etc (WIP names). Then, to preserve backward compatibility, ExchangeWrapper would keep the dollar-specific functions that serve as aliases of the generalized functions.
        - Very similar setup for StableTokenEUR— create a new class `BaseStableTokenWrapper` (WIP name) to serve as a superclass with all the meaty logic, and then have `StableTokenWrapper` (for cUSD) and `StableTokenEURWrapper` (for cEUR) as subclasses.
        - Adapt any existing tests for the wrappers for to cover the cEUR case if appropriate, eg [https://github.com/celo-org/celo-monorepo/blob/master/packages/sdk/contractkit/src/wrappers/Exchange.test.ts](https://github.com/celo-org/celo-monorepo/blob/master/packages/sdk/contractkit/src/wrappers/Exchange.test.ts)
- [x] (Optional) Add a function for reporting specifically for cEUR [https://github.com/celo-org/celo-monorepo/blob/master/packages/sdk/contractkit/src/wrappers/SortedOracles.ts#L184](https://github.com/celo-org/celo-monorepo/blob/master/packages/sdk/contractkit/src/wrappers/SortedOracles.ts#L184)
- [x] Add ExchangeEUR & StableTokenEUR to the list of contracts (which are used for lookup in the Registry)
    - [https://github.com/celo-org/celo-monorepo/blob/master/packages/sdk/contractkit/src/base.ts#L1](https://github.com/celo-org/celo-monorepo/blob/master/packages/sdk/contractkit/src/base.ts#L1)
- [x] Add StableTokenEUR to `CeloToken`:
    - [https://github.com/celo-org/celo-monorepo/blob/master/packages/sdk/contractkit/src/base.ts#L31](https://github.com/celo-org/celo-monorepo/blob/master/packages/sdk/contractkit/src/base.ts#L31)
- [x] Add ExchangeEUR & StableTokenEUR to `WrapperFactories`
    - [https://github.com/celo-org/celo-monorepo/blob/master/packages/sdk/contractkit/src/contract-cache.ts#L25](https://github.com/celo-org/celo-monorepo/blob/master/packages/sdk/contractkit/src/contract-cache.ts#L25)
- [x] Add ExchangeEUR & StableTokenEUR to `WrapperCacheMap` and `WrapperCache`
    - WrapperCacheMap [https://github.com/celo-org/celo-monorepo/blob/master/packages/sdk/contractkit/src/contract-cache.ts#L55](https://github.com/celo-org/celo-monorepo/blob/master/packages/sdk/contractkit/src/contract-cache.ts#L55)
    - WrapperCache [https://github.com/celo-org/celo-monorepo/blob/master/packages/sdk/contractkit/src/contract-cache.ts#L87](https://github.com/celo-org/celo-monorepo/blob/master/packages/sdk/contractkit/src/contract-cache.ts#L87) (ie `getStableTokenEUR`
- [x] Add ExchangeEUR & StableTokenEUR's config to `NetworkConfig`, `getNetworkConfig`, and `getHumanReadableNetworkConfig`
    - NetworkConfig [https://github.com/celo-org/celo-monorepo/blob/master/packages/sdk/contractkit/src/kit.ts#L55](https://github.com/celo-org/celo-monorepo/blob/master/packages/sdk/contractkit/src/kit.ts#L55)
    - getNetworkConfig [https://github.com/celo-org/celo-monorepo/blob/master/packages/sdk/contractkit/src/kit.ts#L120](https://github.com/celo-org/celo-monorepo/blob/master/packages/sdk/contractkit/src/kit.ts#L120)
    - getHumanReadableNetworkConfig [https://github.com/celo-org/celo-monorepo/blob/master/packages/sdk/contractkit/src/kit.ts#L171](https://github.com/celo-org/celo-monorepo/blob/master/packages/sdk/contractkit/src/kit.ts#L171)
- [x] Add `cEUR` to `AccountBalance` and `getTotalBalance`
    - AccountBalance [https://github.com/celo-org/celo-monorepo/blob/master/packages/sdk/contractkit/src/kit.ts#L70](https://github.com/celo-org/celo-monorepo/blob/master/packages/sdk/contractkit/src/kit.ts#L70)
    - getTotalBalance [https://github.com/celo-org/celo-monorepo/blob/master/packages/sdk/contractkit/src/kit.ts#L98](https://github.com/celo-org/celo-monorepo/blob/master/packages/sdk/contractkit/src/kit.ts#L98)
- [x] Add cEUR to comment on setting fee currency
    - [https://github.com/celo-org/celo-monorepo/blob/master/packages/sdk/contractkit/src/kit.ts#L221](https://github.com/celo-org/celo-monorepo/blob/master/packages/sdk/contractkit/src/kit.ts#L221)
- [x] Add ExchangeEUR & StableTokenEUR to `ContractFactories` and `Web3ContractCache`
    - ContractFactories [https://github.com/celo-org/celo-monorepo/blob/master/packages/sdk/contractkit/src/web3-contract-cache.ts#L33](https://github.com/celo-org/celo-monorepo/blob/master/packages/sdk/contractkit/src/web3-contract-cache.ts#L33)
    - Web3ContractCache [https://github.com/celo-org/celo-monorepo/blob/master/packages/sdk/contractkit/src/web3-contract-cache.ts#L72](https://github.com/celo-org/celo-monorepo/blob/master/packages/sdk/contractkit/src/web3-contract-cache.ts#L72)

Old:
**Contractkit: registry, wrappers (exchange and stabletoken), add it in balances. Gas payment is handled via the whitelist as token that can afford gas. Here we have two implementation choices. A) duplicate cusd wrapper. B) something generic for multiple new tokens of the future (if we know that a new stable is in a near future, we should think abut spending a little more time on this)

**Comment by asaj** [comment]
It looks like #6792 was closed, @martinvol are you sure this epic covers contractkit support?

**Comment by martinvol** [comment]
Looking at the labels I assumed it did, is that not the case @aslawson?

**Comment by asaj** [comment]
Per @nvtaveras the cEUR oracle work depends on this

**Comment by asaj** [comment]
Scratch that ^ there is apparently a workaround
