### ISSUE TITLE
Celo: <Issue Title>

### ISSUE THREAD

**Issue by anouar32** [celo-org/celo-monorepo#6400]
*Describe your issue here.*
Hello, I transferred some Celo to my wallet 22 days ago, and up to now I didn't receive them. 
The URL of the transaction is : https://explorer.celo.org/tx/0xfe5e48d11a617b998bc57b48d905804af54ce4672aa70c30612c904776ea4880/token_transfers 

Thank you.
Anouar.

### Environment
* Elixir Version: 1.9.0
* Erlang Version: 22
* BlockScout Version: 330e57bb88472a655cb1b67d70131d8ecef56e49

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Safari/605.1.15`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by dominiquejane** [comment]
Hi @anouar32, I came across your issue and wanted to see if I can help in any way.
What is the current status of your issue?
