### ISSUE TITLE
Go over the Certora Report and identify any bugs

### ISSUE THREAD

**Issue by nambrot** [celo-org/celo-monorepo#6410]
### Expected Behavior

Please describe the behavior you are expecting

### Current Behavior

What is the current behavior?

**Comment by yorhodes** [comment]
see https://docs.google.com/document/d/1SwVK0ImHj5KqSqIsNlj2CYowxKiGk_2lbyyGBLBknqI/edit#

**Comment by yorhodes** [comment]
opened https://github.com/celo-org/celo-monorepo/issues/6943

**Comment by yorhodes** [comment]
opened https://github.com/celo-org/celo-monorepo/issues/6945

**Comment by yorhodes** [comment]
opened https://github.com/celo-org/celo-monorepo/issues/6946

**Comment by yorhodes** [comment]
opened https://github.com/celo-org/celo-monorepo/issues/6947

**Comment by yorhodes** [comment]
opened https://github.com/celo-org/celo-monorepo/issues/6948
