### ISSUE TITLE
DowntimeSlasherV2 should have a constitution set

### ISSUE THREAD

**Issue by nambrot** [celo-org/celo-monorepo#6411]
Requires a governance proposal

### Expected Behavior

Please describe the behavior you are expecting

### Current Behavior

What is the current behavior?

**Comment by nambrot** [comment]
@aslawson Moved this ahead as this seems kind of critical?

**Comment by aslawson** [comment]
Ya -- this seems pretty critical. Is this contract already deployed? If so, it'll have to be a governance proposal to update.

**Comment by nambrot** [comment]
Yeah this was done as part of release 1

**Comment by yorhodes** [comment]
@Tjudice good candidate
