### ISSUE TITLE
$100 for retreving celo from zrx wallet

### ISSUE THREAD

**Issue by jclaver1** [celo-org/celo-monorepo#6429]
### Expected Behavior

Please describe the behavior you are expecting

### Current Behavior

What is the current behavior?

**Comment by jclaver1** [comment]
Need help getting celo back to coinbase from zrx address it was sent to by mistake.

**Comment by jclaver1** [comment]
Is this even possible using myetherwallet or any other application?

**Comment by dominiquejane** [comment]
@jclaver1 
Hi, what's the status on this issue?
It may be possible to retrieve your funds if you have the private key for the zrx address.
