### ISSUE TITLE
Update wording in docs to clarify CELO implements the ERC-20 standard, but is not an ERC-20 token on Ethereum

### ISSUE THREAD

**Issue by barbaraliau** [celo-org/celo-monorepo#6436]
### Expected Behavior

It's clear that CELO follows the ERC-20 standard but is not an ERC-20 token on the Ethereum blockchain

### Current Behavior

Language is not as clear.

Current paragraph:
https://docs.celo.org/overview#background-and-key-concepts

```
ERC-20 is a standard interface for implementing cryptocurrencies or tokens as contracts, rather than via account balances. In Celo, CELO has a duality as both the native currency and is also an ERC-20 token on the Celo blockchain.
```

**Comment by critesjosh** [comment]
could link to this page wherever ERC20 is referenced https://docs.celo.org/developer-guide/celo-for-eth-devs

**Comment by barbaraliau** [comment]
I like that idea a lot
