### ISSUE TITLE
BlockchainParameters should be considered a Celo Core Contract

### ISSUE THREAD

**Issue by nambrot** [celo-org/celo-monorepo#6464]
### Expected Behavior

It should be checked for compatability

### Current Behavior

It is not

**Comment by deepakhb2** [comment]
@nambrot The BlockchainParameers is already included in CoreContracts constant in build.ts under scripts. Is this already fixed and but not checked for compatibility?

**Comment by nambrot** [comment]
Yeah, I think that's why I filed the ticket. I don't fully remember why again. Not checking for compatability in https://github.com/celo-org/celo-monorepo/pull/4747/files was the reason I think

**Comment by deepakhb2** [comment]
Thank you @nambrot. I am not sure, how to check the compatibility. Please share more details on this or direct me to some documentation that helps. I will work on this issue. Thank you in advance.

**Comment by yorhodes** [comment]
from @nambrot 
> the contract shows up in the version report, its in the list of core contracts in registry-utils, and registered in the registry

closing due to already being compatibility checked

**Comment by nambrot** [comment]
@deepakhb2 If you are looking for another easy issue, I recommend you to take a look at https://github.com/celo-org/celo-monorepo/issues/6467

**Comment by deepakhb2** [comment]
Thank you @nambrot I will work on that issue.
