### ISSUE TITLE
Protocol Migrations should only transfer ownership once

### ISSUE THREAD

**Issue by mcortesi** [celo-org/celo-monorepo#647]
### Expected Behavior

It seems each time we deploy a contract a couple of transferOwnerships happens

 * we transfer ownership for Proxy to `accounts[0]`
 * on initialize some (but not all) contract implementation transfer ownership to the `msg.sender`
 * on governance migration we transfer ownership for both to the governance contract.

It seems that we do duplicated work here. Probably the Proxy ownership transfer doesn't make sense since `accounts[0]` is probably already the owner. We need to check this and remove the step is possible

Comes from: https://github.com/celo-org/celo-monorepo/pull/644#discussion_r315840254

**Comment by mcortesi** [comment]
@asaj do you know about this?

**Comment by aslawson** [comment]
This feels pretty low priority now since we've already deployed our core contracts. @nambrot would any newly deployed contracts by clabs also use this migration path?

**Comment by nambrot** [comment]
I think this would apply to future upgrades and deploys, but I agree this feels very low priority
