### ISSUE TITLE
Mainnet should have consistent randomness retention window

### ISSUE THREAD

**Issue by nambrot** [celo-org/celo-monorepo#6484]
### Expected Behavior

randomness should be available

### Current Behavior

If proposal 15 passes, the effective attestation validity will still be 1 hour, since randomness will not be available beyond

**Comment by aslawson** [comment]
Requires governance proposal to set `randomnessBlockRetentionWindow` to the same value as `attestationExpiryBlocks`

"The greatest risk would be that clients look on-chain for actionable attestations, and seeing a request that is more than 1 hour, but less than 1 day, old will try to select issuers. I am worries the client would get stuck in this state until the next day."
