### ISSUE TITLE
Add Defi Pulse Link to celo.org footer

### ISSUE THREAD

**Issue by aaronmgdr** [celo-org/celo-monorepo#6490]
### Expected Behavior

add a link to defi pulse (https://defipulse.com/ ) to the social section of the footer on celo.org 

design => https://www.figma.com/file/E7HhqLi5TrFwcCpKriqEu4/Celo-Website-5.0?node-id=51%3A46
slack request https://celo-org.slack.com/archives/CABQPRW0Z/p1607086315359000
### Current Behavior

no link

**Comment by njokuScript** [comment]
@aaronmboyd can i work on this?

**Comment by aaronmboyd** [comment]
@Khay-EMMA Different Aaron =P, I think you're asking for @aaronmgdr

**Comment by aaronmgdr** [comment]
this has been implemented https://github.com/celo-org/website/commit/d89fc245f0eec8c4f901736c92beae6416f5ed56
