### ISSUE TITLE
Should know whether CELO minting ahead of schedule is problematic

### ISSUE THREAD

**Issue by nambrot** [celo-org/celo-monorepo#6517]
### Expected Behavior

It should be easily knowable whether CELO minting is problematic given current projections. If it is, there should be explicit decision making process that recommends a particular change (or no change) to the parameters influencing the minting 

### Current Behavior

By this point, the original schedule of CELO issuance expected to mint around 9M CELO. However, in fact, ~15M CELO have been minted. It is possible that this accelerated pace of CELO minting is problematic.

**Reason for need:**  We're unsure of the economic impact of extra minting and could be diluting the most vulnerable and our retail users in excess.

**Comment by bowd** [comment]
- current voting yield → getTargetVotingYieldParameters()?
- the amount of CELO voting → getTotalLockedGold() - getNonvotingLockedGold()?
- the amount minted to the reserve in the last epoch to collateralize validator payments
- and the latest amounts minted to the community fund and carbon offsetting fund.

**Comment by albertclabs** [comment]
Output of this work should be some kind of recommendation on whether we should tweak any of the contract parameters to affect CELO distribution. Should we be affecting behavior like more staking or voting?

A side benefit of this could be a shared understanding on this team of how the system functions.

**Comment by ghost** [comment]
Explanation and analysis of the issue: https://docs.google.com/document/d/1G_EH4U0qmI277z55QcBry245_QMKzJ3WQGvfMCgiQJM/edit
