### ISSUE TITLE
Investigate push notifications not arriving

### ISSUE THREAD

**Issue by gnardini** [celo-org/celo-monorepo#6533]
Push notifications are intermittently not arriving. I sent 10 on a row and received only 4, sometimes I receive more and sometimes less. I've tested with CELO transfers, but the same might happen with cUSD.

This issue involves investigating and fixing the issue

**Comment by Lss-Ankit** [comment]
Hi @gnardini we have verified this issue on Android internal build V1.8.0 & testflight build V1.8.0 and observed the followings and also we have added below scenarios in our adhoc test plan.
 
**Push notification for sending cUSD:**

 **iOS:**

- Only 4 push notifications is shown to user A when userB  sending cUSD 10times in a row.

**Android:**
- Only 4 push notifications is shown to user A when user B sending cUSD 10times in a row.

**Push notification for Transferring CELO:**
**iOS:**

- Only 4 push notifications is shown to user A when user B Transfer CELO 10times in a row.

**Android:**
- Only 2 push notifications is shown to user A when user B Transfer CELO 8-10 times in a row.

Can you please let us know if we want to test anything else

Thanks!
