### ISSUE TITLE
User phone numbers and country should be input automatically

### ISSUE THREAD

**Issue by cmcewen** [celo-org/celo-monorepo#654]
### Expected Behavior

read both the country and phone number automatically, present both as a placeholder so the user can edit if incorrect.

If there are multiple phone numbers detected, present the default modal with options to prompt the user to select the correct one.

We use the Android hint picker so people don't have to type as much
https://developers.google.com/identity/sms-retriever/request (though apparently there are some bugs https://github.com/googlesamples/android-credentials/issues/27)

### Current Behavior

Everyone has to type

**Comment by martinvol** [comment]
To autocomplete phone number (not fully sure this includes country code), the app should have `PermissionsAndroid.PERMISSIONS.READ_PHONE_STATE`, the system displays this request as "make and manage phone calls". Is this acceptable? @nityas 

Alternative option to complete only country code will be using an API to get the phone's public IP, then use a geoIP library and then convert that to a phone country code.

Example of API to get IP: https://github.com/sindresorhus/ipify
Example of library to map IP to country: https://github.com/bluesmoon/node-geoip

**Comment by jmrossy** [comment]
My feeling is that heavy permissions is not worth the feature.
Are we 100% sure there's no way to get it without that permission? I think I saw an app do it once but can't remember if that was iOS or Android?

**Comment by cmcewen** [comment]
@martinvol the link above in the issue description has the API to do it without permission - creating a hint request (https://developers.google.com/identity/sms-retriever/request)

**Comment by martinvol** [comment]
Thanks @cmcewen, my bad.

I didn't find anything implementing that in React Native so I'm now bridging the Java example to RN.

**Comment by jmrossy** [comment]
@martinvol FYI we have already forked the SMS retriever RN package so you can make your changes to our fork :)
