### ISSUE TITLE
Setup metabase pulses for summaries and informational alerting

### ISSUE THREAD

**Issue by yorhodes** [celo-org/celo-monorepo#6556]
### Expected Behavior

[Metabase pulse](https://www.metabase.com/docs/latest/users-guide/10-pulses.html) which posts to Slack channel (#eng-alerts-cap-informational or #eng-alerts-cap ).

### Current Behavior

No notifications from metabase or on-chain events.

**Comment by aslawson** [comment]
@yorhodes let me know if you feel this should be higher priority. i saw you suggested both short and long term solution for this. i'll put this higher up on our p3s for now
