### ISSUE TITLE
ASv1 integration docs

### ISSUE THREAD

**Issue by aslawson** [celo-org/celo-monorepo#6561]
Todos: 
- [x] #6753
- [x] #6578

### Expected Behavior

External developers and integrating partners should be able to access and create phone number mappings. Onchain identity requires a pepper from ODIS, so developers need access to this service.

- Create documentation on how to access phone number mappings (via ODIS + onchain requests)
- Create documentation on how to create phone number mappings

Exploration of more seamless dev solutions:
- Use Valora (& WalletConnect) to provide phone number mappings to application
- Abstract verification logic out of Valora (like Komenci) -- needed for other wallets or for dapp users who don't want to have multiple wallets

### Current Behavior

Other developers currently can read Valora created mappings by calling ODIS (for the pepper) and making the onchain request, but it is unclear on how to do so. Creating mappings is complex and there are no clear standards on how to do so.

**Comment by codyborn** [comment]
We've created this guide here for how to read identity mapping with ODIS: https://docs.celo.org/developer-guide/contractkit/odis

It'd be useful to know if devs are getting tripped up with this guide or if it's too difficult to find.

**Comment by aslawson** [comment]
RE: the existing guide only has ODIS pepper access. This ticket should encapsulate read/write of phone number mappings (inclusive of ODIS). I've updated the title to be clearer

**Comment by alecps** [comment]
Closing this Epic as it now wraps a single underlying ticket
