### ISSUE TITLE
Core Contracts should be tested against unintentional delegatecall/selfdestruct

### ISSUE THREAD

**Issue by nambrot** [celo-org/celo-monorepo#6569]
### Expected Behavior

Write script/tests that check that implementation contracts don’t have unintentional delegatecalls or self-destructs

Might be solved with #6433 

### Current Behavior

No contracts has them, but we also have no checks

**Comment by yorhodes** [comment]
This is checked by the openzeppelin-upgrades tool https://docs.openzeppelin.com/upgrades-plugins/1.x/faq#what-does-it-mean-for-a-contract-to-be-upgrade-safe

**Comment by yorhodes** [comment]
Because we do not expect the `DELEGATECALL` to be used anywhere outside of our `Proxy` contract, we can accomplish this by simply filtering on the `DELEGATECALL` and `SELFDESTRUCT` opcodes in the compiled bytecode for all of our non-proxy contracts.

This is far easier than achieving #6433.
