### ISSUE TITLE
Implement a process to ensure logic contracts can be initialized

### ISSUE THREAD

**Issue by m-chrzan** [celo-org/celo-monorepo#6577]
Currently, the logic contract of a proxied contract could be "hijacked" by anyone. In most cases this isn't dangerous, but there are specific situations (e.g. when a `selfdestruct` is reachable) where this could pose problems. To avoid any headaches around this, the Celo smart contracts should have a mechanism for automatically locking the logic contract on deployment.

One proposal for achieving this:

* To the `Initializable` contract, add a constructor that sets `initialized` to 1, thus blocking proper initialization.
* Since unit tests use contracts unproxied, this constructor could take an additional boolean argument `testingDeployment` that, when set to `true`, would skip the above step.

**Comment by nambrot** [comment]
@yorhodes @aslawson Moved this one up as well. None of our CoreContracts should be vulnerable, but it should be good practice?

**Comment by aslawson** [comment]
IIUC - this feels like an generalized approach for #6544 . Can this solution be applied for ReleaseGold contract deployments as well?

**Comment by nambrot** [comment]
I'd interpret this ticket as solving it for the Celo Core Contracts, and #6544 to solve it for releaseGold contracts. I think the solution is going to be similar, but still different enough to track differently IMO
