### ISSUE TITLE
[EPIC] Metrics Migration Phase 2: Migrate Alerts Service-by-Service

### ISSUE THREAD

**Issue by yourbuddyconner** [celo-org/celo-monorepo#6589]
In the new architecture, Alerts that rely on data collected via Prometheus will be managed by Grafana Cloud’s hosted version of [Prometheus Alertmanager](https://prometheus.io/docs/alerting/latest/alertmanager/). Alerts can be defined using PromQL (aka normal Prometheus queries) and be uploaded to Grafana Cloud via a CLI interface called cortex-tool. Details for the process are included in the Grafana Cloud documentation [here](https://grafana.com/docs/grafana-cloud/alerts/alerts-rules/).

Alerts for the entire suite of applications and services will live in the same place, as defined in Phase 0, making management and organization of alerts simple.

See https://www.notion.so/clabsco/Monitoring-migration-to-Grafana-Cloud-4447de76415b43ccacdbb32fbdb7a40b.

**Comment by lvpeschke** [comment]
Pending Identity dashboards & alerts migration.
