### ISSUE TITLE
[EPIC] Metrics Migration Phase 3: Sunset Stackdriver Monitoring

### ISSUE THREAD

**Issue by yourbuddyconner** [celo-org/celo-monorepo#6590]
As all the alerts for a particular cluster are migrated, we can begin updating Prometheus servers and stop the flow of metrics to Stackdriver Monitoring.

See https://www.notion.so/clabsco/Monitoring-migration-to-Grafana-Cloud-4447de76415b43ccacdbb32fbdb7a40b.

**Comment by lvpeschke** [comment]
**Impact: 9**
  [See the discussion](https://action.parabol.co/meet/cad5rClzP2/estimate/1) in 2022-03 project scoring with ICE

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by lvpeschke** [comment]
**Confidence: 9**
  [See the discussion](https://action.parabol.co/meet/cad5rClzP2/estimate/2) in 2022-03 project scoring with ICE

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by lvpeschke** [comment]
**Ease: 9**
  [See the discussion](https://action.parabol.co/meet/cad5rClzP2/estimate/3) in 2022-03 project scoring with ICE

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
