### ISSUE TITLE
Create a section in the cLabs Infrastructure Repository for alerts to live

### ISSUE THREAD

**Issue by yourbuddyconner** [celo-org/celo-monorepo#6591]
Create a section in the cLabs Infrastructure Repository for alerts to live, delimited by Circle/Service. 

Repo: https://github.com/celo-org/infrastructure

Ideas: 
```
/alerts
  /web-services
  /blockchain
...
```

**Comment by lvpeschke** [comment]
Alert configuration remains technology dependant.

For Grafana Cloud Alertmanager alerts, the folders now exist: terraform-modules/grafana-cloud/files/alertmanager/alerts. They are currently keyed by service.
