### ISSUE TITLE
Wire up automation to the Infrastructure Repository’s CI

### ISSUE THREAD

**Issue by yourbuddyconner** [celo-org/celo-monorepo#6593]
Call the automation created as part of #6592 to the Infrastructure Repository’s CI, such that changes to alerting rules are automatically deployed upon merging. 

CI Options: 
- CircleCI 
- Github Actions (I like this one)

**Comment by lvpeschke** [comment]
This is in place: https://github.com/celo-org/infrastructure/blob/master/.github/workflows/workflow.yaml
