### ISSUE TITLE
Author Instructions that teams can use to migrate their Stackdriver Monitoring Alerts to Prometheus Alertmanager

### ISSUE THREAD

**Issue by yourbuddyconner** [celo-org/celo-monorepo#6594]
Author Instructions that teams can use to migrate their Stackdriver Monitoring Alerts to Prometheus Alertmanager. 

High-Level: 
- Identify what metrics are being used in your Stackdriver Monitoring Alert 
- Locate the corresponding time series in Prometheus using Grafana Cloud
  - Should probably mention labels here 
  - Don't try to teach the reader how to use Prometheus, link to Prometheus docs when explanation is required.
- Use the query to write an alert, save it in the appropriate group corresponding to the circle that owns the alert 
- Explain how CI automation works 
- Explain how to verify the alert was installed 
- Explain how to manually trigger the alert

The documentation should live in notion, in the Operational Circle tree here: https://www.notion.so/clabsco/Operational-Circle-ef2a7ce9f28b45fe8e14b185c7c2ff79

**Comment by yourbuddyconner** [comment]
Link to living doc: https://www.notion.so/clabsco/Prometheus-Metrics-at-cLabs-c37bb43c5dc2407e91b3c53806769702

**Comment by lvpeschke** [comment]
Follow-up living doc: https://www.notion.so/clabsco/Prometheus-on-Grafana-and-off-Stackdriver-bf4283297f1b4bc789fb433afd71ac16
