### ISSUE TITLE
Upgrade Prometheus Instances (via celotool)

### ISSUE THREAD

**Issue by yourbuddyconner** [celo-org/celo-monorepo#6597]
Upgrade Prometheus Instances (via celotool), modifying their remote_write configuration to direct Metrics to Grafana Cloud. 

Specifically, this will involve updating the Prometheus Helm Chart [here](https://github.com/celo-org/celo-monorepo/blob/master/packages/helm-charts/prometheus-stackdriver/templates/configmap.yaml) and adding a `remote_write` stanza as described in the Prometheus docs [here](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write).

**Comment by lvpeschke** [comment]
Added by @jcortejoso in #7303.
