### ISSUE TITLE
Configure Prometheus Alertmanager to route alerts to Slack and VictorOps

### ISSUE THREAD

**Issue by yourbuddyconner** [celo-org/celo-monorepo#6598]
Configure Prometheus Alertmanager to route alerts to Slack and VictorOps, to achieve parity with Stackdriver Monitoring. 

The configuration process involves taking flat config files and uploading them to the remote AlertManager instance via `cortextool`, this process is described in the Grafana Cloud docs [here](https://grafana.com/docs/grafana-cloud/alerts/alerts-rules/#upload-alertmanager-configuration-to-your-grafana-cloud-alerts-instance). 

This configuration file should live in the [cLabs Infrastructure repository](https://github.com/celo-org/infrastructure).

**Comment by lvpeschke** [comment]
Progress in https://github.com/celo-org/infrastructure/pull/35, https://github.com/celo-org/infrastructure/pull/61, https://github.com/celo-org/infrastructure/pull/61: configuration exists and has been tested for blockchain and data services.

The Alertmanager config can be inspected through the Grafana Cloud UI or by following https://alertmanager-us-central1.grafana.net/instances?redirect=/alertmanager/.

**Comment by lvpeschke** [comment]
Refinement of scope:

The Alertmanager routes should cover:

- [x] All currently set-up VictorOps destinations -- reuse of the routing_key concept

- [x] All Slack channel integrations set up from within VictorOps -- necessity to choose
    1. using a [Slack app][slack-app]: the "Grafana Alertmanager" one that's already set up with 1 webhook per channel
    2. using the [legacy webhooks][legacy] with channel override
    - see https://prometheus.io/docs/alerting/latest/configuration/#slack_config 
    - concise context: https://community.atlassian.com/t5/Jira-Software-questions/Slack-incoming-webhook-will-be-deprecated-and-not-recommended-to/qaq-p/1826161
    - secrets should be stored in GCP Secret Manager

- [ ] all the channels defined in Stackdriver need to be supported https://console.cloud.google.com/monitoring/alerting/notifications?project=celo-testnet-production

[legacy]: https://api.slack.com/legacy/custom-integrations
[slack-app]: https://api.slack.com/slack-apps
