### ISSUE TITLE
Migrate Data Services Circle Alerts

### ISSUE THREAD

**Issue by yourbuddyconner** [celo-org/celo-monorepo#6600]
Follow process as described in #6599 for the Web Services Circle.

**Comment by lvpeschke** [comment]
All data services alert of interest are now coming from Grafana for Blockscout and aws for Stokado.
There are no more GCP alerts that cannot be disabled or deleted altogether.
All dashboards, graphs, and data sources needed to troubleshoot the alerts are available in Grafana for Blockscout and aws for Stokado.
