### ISSUE TITLE
Expand Formal Verification (certora) - Investigate

### ISSUE THREAD

**Issue by aslawson** [celo-org/celo-monorepo#6621]
Writing our own specs (write tests/constraints of contracts)
Expand coverage to more contracts

**Comment by yorhodes** [comment]
workshop 2

SMEs internally who join Certora sync meetings and focus on this

**Comment by nambrot** [comment]
@yorhodes As per our conversation, you might want to advocate for increasing the priority of this one

**Comment by yorhodes** [comment]
https://docs.google.com/document/d/1KbloG3GNCR9baEuPWS8T3-S9sarpJfj9kVgZg0YrR-U/edit?usp=sharing
