### ISSUE TITLE
Celo: Lost Crypto

### ISSUE THREAD

**Issue by sanram54** [celo-org/celo-monorepo#6624]
#*Describe your issue here.*
trying to send crypto to a different wallet and cant find it any where https://etherscan.io/address/0x20cdF832A12870C623ED501E9FA45Fc24453107d
### Environment
* Elixir Version: 1.9.0
* Erlang Version: 22
* BlockScout Version: 3c418b3df3bb4d38abff295c13fc60c529a59487

* User Agent: `Mozilla/5.0 (Linux; Android 9; SM-G950U Build/PPR1.180610.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/88.0.4324.93 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by medhakothari** [comment]
Hi @sanram54! Could you give us more details? For example, what network was this on (e.g. mainnet, alfajores)? Where were you sending the transaction from? Were you sending cUSD or CELO? Can you confrim that the money left the first wallet? Any more information here would be super helpful!

**Comment by aslawson** [comment]
@sanram54 -- I'm closing this ticket due to inactivity. Please reopen and let us know if this is a still a problem.
