### ISSUE TITLE
 Blank screen displayed when user taps on “Earn Rewards” option from Hamburger Menu

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#6625]
**Frequency:** 100%
**Repro on build version:** Android Internal Build V1.9.0(1004294331), Test Flight Build V1.9.0(41)
**Repro on devices:** Samsung Galaxy A5(7.0), iPhone 6+(12.4.5), Google Pixel XL (8.1), iPhone SE 2(14.3)
Testing Account:  432 568 9221 / [Backup Key](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit#gid=0&range=B65)
 **Repro Steps:**
1. Launch the application & login with a test account.
2. Tap on Hamburger Menu.
3. Tap on the “Earn Rewards” option near the user profile picture.
**Current Behavior:**  Blank screen displayed when the user taps on it.
**Expected Behavior:**  Related Earn Rewards details screen should be displayed when user taps on it.
**Impact:** User not able to proceed to Earn Rewards.
**Attachment:**  [BlankScreenWhenUserTapsOnEarnRewards.mp4](https://drive.google.com/file/d/1B5Qdnv_r1wCjH8cTb57nFe2ZBb3_D-ed/view?usp=sharing)

**Comment by gnardini** [comment]
@Lss-Ankit 
Thanks for reporting, this was because the mainnet server didn't have the texts loaded. The screen should show properly now without need for an update, can you check again on 1.9 please?

**Comment by Lss-Ankit** [comment]
Hey @gnardini I have verified this issue using Android Internal Build V1.9.0(1004294331) & Test Flight Build V1.9.0(41) & observed that issue is fixed now & user able to redirect to  "CELO Earn Rewards program" screen.
**Verified on Devices:** Samsung Galaxy A5(7.0), iPhone XR(13.1.3)
