### ISSUE TITLE
Ledger-related flags no longer available in autocomplete since v1.0.x

### ISSUE THREAD

**Issue by amani1104** [celo-org/celo-monorepo#6630]
### Expected Behavior

Ledger-related flag `--useLedger` and option `--ledgerAddresses=x` are available in autocomplete to improve workflow, as was the case in earlier versions.  

### Current Behavior

Although the flags do still work, these have been removed from autocomplete since v1.0.x and are also not described in respective help-files.

**Comment by aslawson** [comment]
@amani1104 does this work for other flags? was not even aware this way even a feature we originally offered, but seems nice to have :)

**Comment by amani1104** [comment]
@aslawson I believe autocomplete only worked for the Ledger-related flags. This was a feature of the autocomplete plugin until v1 of celocli, but somehow it got removed after that.

**Comment by aslawson** [comment]
@amani1104 We won't have the bandwidth to dig into this in the near term, so I'm going to close for now. But this seems like a good ticket to open up to the community via gitcoin
