### ISSUE TITLE
8-digit attestation code

### ISSUE THREAD

**Issue by ole-nov** [celo-org/celo-monorepo#6631]
### Expected Behavior

The existing long alphanumeric string is replaced with8-digit characters in the SMS sent to users during the verification process

Designs: [Figma](https://www.figma.com/file/zt7aTQ5wuXycIwxq5oAmF9/Wallet-Refresh?node-id=11635%3A1396)
- Updated input field designs 
- Updated copy
- Removal of iOS-specific verification screen
- Removal of "Typing?..." toast message
- Not shown: Virtual keyboard updates 
    - Display numpad instead of keyboard
    - Autosuggest (?)

![Screen Shot 2021-02-16 at 1.33.23 PM.png](https://images.zenhubusercontent.com/5fa30bfd4afb7771fa773153/673e0ecf-9720-44de-9ab0-924cbe2e9b05)

### Current Behavior

Long randomly generated alphanumeric string of symbols.

**Comment by ole-nov** [comment]
- UX is going to be changed
         virtual keyboard
         remote FF
- iOS autofill issue

**Comment by coreycelo** [comment]
Designs added to issue
