### ISSUE TITLE
 Nothing happens when the user taps on the “Simplex” option from Add Funds screen.  

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#6633]
**Frequency:** 100%
**Repro on build version:** Android Internal Build V1.9.0(1004294331) & Test Flight Build V1.9.0(41)
**Repro on devices:** Samsung Galaxy A5(7.0), iPhone XR(13.1.3)
Testing Account:  680-333-1978/ [Backup Key](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit#gid=0&range=B7)
**Pre-condition:** User should login with Verified Phone Number.
 **Repro Steps:**
1. Launch the application & login with a test account.
2. Tap on the Hamburger menu.
3. Now tap on Earn Rewards option beside Profile picture.
4. Now tap on the “Add cUSD” option on the CELO Rewards Program page.
5. Now select “Celo dollar” from “Select a digital currency” option & “Debit card or bank account” from “Pay with” option.
6. Now the user should be on the Add Funds screen.
7. Now tap on the Simplex option.
8. Observed that,
**Current Behavior:**  Nothing happens when the user taps on the Simplex option.
**Expected Behavior:**  Simplex related information page should be displayed.
**Impact:** User not able to proceed to “Earn Rewards”.
**Attachment:**  [NothingHappensWhenTapsOnSimplex.mp4](https://drive.google.com/file/d/11Mjmmd74ZISFGlvUQRofEQogVNUuOlSD/view?usp=sharing)

**Comment by gnardini** [comment]
Fixed in https://github.com/celo-org/celo-monorepo/pull/6623 the fix will be available on 1.9.1

**Comment by Lss-Ankit** [comment]
Hi @gnardini I have verified this issue using Android Internal Build V1.9.1(1004294332) & Test Flight Build V1.9.1(42) & observed that issue us fixed now.
**Verified on devices:** iPhone XR(13.1.3), Samsung Galaxy A5(7.0)
