### ISSUE TITLE
Deploy cEUR activation governance proposal on Mainnet

### ISSUE THREAD

**Issue by yerdua** [celo-org/celo-monorepo#6644]
This governance proposal should include:

1. Set cEUR as a fee/gas currency
2. Set stableTokenEUR as reserveExchangeSpender
3. Unfreeze `stableTokenEUR` and `exchangeEUR`
4. Set parameters for exchangeEUR (if any)

**Comment by martinvol** [comment]
Proposal is ready to be submmited when we're ready: `https://github.com/celo-org/celo-proposals/blob/master/CGPs/0024/mainnet.json

**Comment by martinvol** [comment]
Proposal is ready here: https://github.com/celo-org/celo-proposals/blob/master/CGPs/0024/mainnet.json
Docs are here: https://github.com/celo-org/celo-proposals/blob/master/CGPs/0024.md

**Comment by albertclabs** [comment]
Executed Thursday Apr 22. Closing this one out.
