### ISSUE TITLE
cEUR cashflow analysis

### ISSUE THREAD

**Issue by yerdua** [celo-org/celo-monorepo#6645]
Add cEUR to tooling that analyzes if the reserve is bleeding money.

**Comment by martinvol** [comment]
The cashflow dashboard is working with multicurrency now https://metabase.celo-networks-dev.org/dashboard/42?past_days_relative_to_now=7&exclude_this_address=0x4132F04EaCfdE9E2b707667A13CB69DbC5BABb68&quotation_currency=USD&exchange_contract=Exchange

The only work remaining to close the issues in this epis are reviews to merge the code in.
