### ISSUE TITLE
CELO <> tBTC on-chain exchange

### ISSUE THREAD

**Issue by yerdua** [celo-org/celo-monorepo#6649]
Pairs to support

- [ ]  CELO/tBTC - required
- [ ]  CELO/cKEEP

TBC if https://koroswap.com will support

**Comment by clrblmt** [comment]
Aggregated into one issue: [tBTC Ecosystem Support ](https://app.zenhub.com/workspaces/platform-economics---backlog-board-600a9f7399b43a001348ae1b/issues/celo-org/celo-monorepo/6652)
