### ISSUE TITLE
Celo-tBTC in Metamask

### ISSUE THREAD

**Issue by yerdua** [celo-org/celo-monorepo#6653]

**Comment by cla-bel** [comment]
[DSRV Labs ](https://github.com/dsrvlabs)providing support for cKEEP and tBTC - 16 week project starting Feb 1 2021. 

First working version expected on Mainnet Feb 28 2021.

**Comment by cla-bel** [comment]
Duplicate - captured in issue #6652 ([tBTC Wallet Support](https://app.zenhub.com/workspaces/platform-economics---backlog-board-600a9f7399b43a001348ae1b/issues/celo-org/celo-monorepo/6652))

**Comment by cla-bel** [comment]
https://app.zenhub.com/workspaces/platform-economics---backlog-board-600a9f7399b43a001348ae1b/issues/celo-org/celo-monorepo/6652

**Comment by clrblmt** [comment]
Duplicate: https://app.zenhub.com/workspaces/platform-economics---backlog-board-600a9f7399b43a001348ae1b/issues/celo-org/celo-monorepo/6652
