### ISSUE TITLE
CELO/EUR oracles deployed on Baklava

### ISSUE THREAD

**Issue by yerdua** [celo-org/celo-monorepo#6658]
### Expected Behavior

There are oracles deployed on Baklava that are reporting the CELO/EUR price to SortedOracles on Baklava. The addresses for these must have been included in the #6845 governance proposal

This also includes dashboards, alert updates, runbook

### Current Behavior

Oracles not yet allowlisted or deployed.

**Comment by bowd** [comment]
I've ran the deployment and scaled down the stateful sets on both clusters so when the GCPs pass we can just scale up and start reporting.
