### ISSUE TITLE
CELO/EUR oracles deployed on Mainnet

### ISSUE THREAD

**Issue by yerdua** [celo-org/celo-monorepo#6659]
### Expected Behavior

There are oracles deployed on Baklava that are reporting the CELO/EUR price to SortedOracles on Mainnet.
This includes:
- generating new private keys + identities (or deciding to use those of the existing CELO/USD oracles)
- doing a governance proposal to add those to the allowlist for reporting CELO/EUR to SortedOracles
- deploying oracle instances running as those allowlisted identities

### Current Behavior

Oracles not yet allowlisted or deployed.

**Comment by martinvol** [comment]
Done!
