### ISSUE TITLE
[Wallet] Emulator runs out of memory on e2e on circle ci

### ISSUE THREAD

**Issue by etuleu** [celo-org/celo-monorepo#6669]
### Expected Behavior

App should run on emulator without throwing OOM.

### Current Behavior

What is the current behavior?

App fails to start on emulator because it reaches the 16MB max heap allocation.

> 01-14 05:46:35.636  3702  3766 I Detox   : Detox thread starting (com.wix.detox.manager)
01-14 05:46:35.640  3702  3766 I DetoxManager: DetoxServerUrl: ws://localhost:49648
01-14 05:46:35.640  3702  3766 I DetoxManager: DetoxSessionId: dc54b52d-8230-810d-c0ea-70bfd3a7cc68
01-14 05:46:42.133  3702  3713 I elo.mobile.tes: Background concurrent copying GC freed 1999(123KB) AllocSpace objects, 0(0B) LOS objects, 38% free, 9866KB/15MB, paused 6.072ms total 317.652ms
01-14 05:46:47.433  3702  3764 I elo.mobile.tes: WaitForGcToComplete blocked Alloc on None for 5.207ms
01-14 05:46:47.433  3702  3764 I elo.mobile.tes: Starting a blocking GC Alloc
01-14 05:46:47.433  3702  3764 I elo.mobile.tes: Starting a blocking GC Alloc
01-14 05:46:47.439  3702  3762 I elo.mobile.tes: Waiting for a blocking GC Alloc
01-14 05:46:47.446  3702  3764 I elo.mobile.tes: Alloc young concurrent copying GC freed 2184(138KB) AllocSpace objects, 0(0B) LOS objects, 2% free, 15MB/15MB, paused 4.032ms total 12.604ms
01-14 05:46:47.446  3702  3762 I elo.mobile.tes: WaitForGcToComplete blocked Alloc on HeapTrim for 7.923ms
01-14 05:46:47.447  3702  3762 I elo.mobile.tes: Starting a blocking GC Alloc
01-14 05:46:47.675  3702  3713 I elo.mobile.tes: Clamp target GC heap from 21MB to 16MB
01-14 05:46:47.904  3702  3762 I elo.mobile.tes: Starting a blocking GC Alloc
01-14 05:46:47.905  3702  3762 I elo.mobile.tes: Starting a blocking GC Alloc
01-14 05:46:47.918  3702  3762 I elo.mobile.tes: Alloc young concurrent copying GC freed 997(70KB) AllocSpace objects, 0(0B) LOS objects, 2% free, 15MB/16MB, paused 1.621ms total 13.679ms
01-14 05:46:48.151  3702  3762 I elo.mobile.tes: Waiting for a blocking GC Alloc
01-14 05:46:48.154  3702  3702 I elo.mobile.tes: Waiting for a blocking GC Alloc
01-14 05:46:48.166  3702  3713 I elo.mobile.tes: Clamp target GC heap from 21MB to 16MB
01-14 05:46:48.166  3702  3713 I elo.mobile.tes: Background concurrent copying GC freed 772(54KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 15MB/16MB, paused 18.771ms total 85.997ms
01-14 05:46:48.166  3702  3762 I elo.mobile.tes: WaitForGcToComplete blocked Alloc on HeapTrim for 15.793ms
01-14 05:46:48.167  3702  3762 I elo.mobile.tes: Starting a blocking GC Alloc
01-14 05:46:48.167  3702  3702 I elo.mobile.tes: WaitForGcToComplete blocked Alloc on HeapTrim for 13.210ms
01-14 05:46:48.167  3702  3702 I elo.mobile.tes: Starting a blocking GC Alloc
01-14 05:46:48.252  3702  3762 I elo.mobile.tes: Waiting for a blocking GC Alloc
01-14 05:46:48.259  3702  3713 I elo.mobile.tes: Clamp target GC heap from 21MB to 16MB
01-14 05:46:48.259  3702  3762 I elo.mobile.tes: WaitForGcToComplete blocked Alloc on HeapTrim for 7.203ms
01-14 05:46:48.259  3702  3762 I elo.mobile.tes: Starting a blocking GC Alloc
01-14 05:46:48.260  3702  3762 I chatty  : uid=10105(org.celo.mobile.test) .0.2.2:8081/... identical 1 line
01-14 05:46:48.260  3702  3762 I elo.mobile.tes: Starting a blocking GC Alloc
01-14 05:46:48.270  3702  3762 I elo.mobile.tes: Alloc young concurrent copying GC freed 0(0B) AllocSpace objects, 0(0B) LOS objects, 0% free, 15MB/16MB, paused 1.612ms total 10.192ms
01-14 05:46:48.274  3702  3762 I elo.mobile.tes: Starting a blocking GC Alloc
01-14 05:46:48.296  3702  3762 I elo.mobile.tes: Clamp target GC heap from 21MB to 16MB
01-14 05:46:48.296  3702  3762 I elo.mobile.tes: Alloc concurrent copying GC freed 153(4376B) AllocSpace objects, 0(0B) LOS objects, 0% free, 15MB/16MB, paused 1.624ms total 21.351ms
01-14 05:46:48.297  3702  3762 I elo.mobile.tes: Forcing collection of SoftReferences for 8208B allocation
01-14 05:46:48.297  3702  3713 I elo.mobile.tes: WaitForGcToComplete blocked Background on HeapTrim for 21.428ms
01-14 05:46:48.297  3702  3762 I elo.mobile.tes: Starting a blocking GC Alloc
01-14 05:46:48.338  3702  3762 I elo.mobile.tes: Clamp target GC heap from 21MB to 16MB
01-14 05:46:48.339  3702  3762 I elo.mobile.tes: Alloc concurrent copying GC freed 401(14KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 15MB/16MB, paused 15.983ms total 41.222ms
01-14 05:46:48.350  3702  3762 I elo.mobile.tes: Waiting for a blocking GC Alloc
01-14 05:46:48.359  3702  3762 I elo.mobile.tes: WaitForGcToComplete blocked Alloc on HeapTrim for 8.874ms
01-14 05:46:48.359  3702  3762 I elo.mobile.tes: Starting a blocking GC Alloc
01-14 05:46:48.360  3702  3762 I elo.mobile.tes: Starting a blocking GC Alloc
01-14 05:46:48.372  3702  3762 I elo.mobile.tes: Clamp target GC heap from 21MB to 16MB
01-14 05:46:48.372  3702  3762 I elo.mobile.tes: Alloc concurrent copying GC freed 80(2200B) AllocSpace objects, 0(0B) LOS objects, 0% free, 15MB/16MB, paused 1.609ms total 12.114ms
01-14 05:46:48.373  3702  3762 I elo.mobile.tes: Starting a blocking GC Alloc
01-14 05:46:48.380  3702  3762 I elo.mobile.tes: Alloc young concurrent copying GC freed 0(0B) AllocSpace objects, 0(0B) LOS objects, 0% free, 15MB/16MB, paused 1.651ms total 6.820ms
01-14 05:46:48.380  3702  3762 I elo.mobile.tes: Starting a blocking GC Alloc
01-14 05:46:48.400  3702  3762 I elo.mobile.tes: Clamp target GC heap from 21MB to 16MB
01-14 05:46:48.400  3702  3762 I elo.mobile.tes: Alloc concurrent copying GC freed 6(144B) AllocSpace objects, 0(0B) LOS objects, 0% free, 15MB/16MB, paused 1.609ms total 19.396ms
01-14 05:46:48.400  3702  3762 I elo.mobile.tes: Forcing collection of SoftReferences for 8208B allocation
01-14 05:46:48.400  3702  3762 I elo.mobile.tes: Starting a blocking GC Alloc
01-14 05:46:48.419  3702  3762 I elo.mobile.tes: Clamp target GC heap from 21MB to 16MB
01-14 05:46:48.419  3702  3762 I elo.mobile.tes: Alloc concurrent copying GC freed 6(256B) AllocSpace objects, 0(0B) LOS objects, 0% free, 15MB/16MB, paused 1.629ms total 17.814ms
01-14 05:46:48.419  3702  3713 I elo.mobile.tes: WaitForGcToComplete blocked Background on HeapTrim for 46.344ms
01-14 05:46:48.420  3702  3762 W elo.mobile.tes: Throwing OutOfMemoryError "Failed to allocate a 8208 byte allocation with 4112 free bytes and 4112B until OOM, target footprint 16777216, growth limit 16777216" (VmSize 4104924 kB)
01-14 05:46:48.420  3702  3762 I elo.mobile.tes: Waiting for a blocking GC Alloc
01-14 05:46:48.428  3702  3762 I elo.mobile.tes: WaitForGcToComplete blocked Alloc on HeapTrim for 7.894ms
01-14 05:46:48.428  3702  3762 I elo.mobile.tes: Starting a blocking GC Alloc
01-14 05:46:48.429  3702  3762 I elo.mobile.tes: Starting a blocking GC Alloc
01-14 05:46:48.441  3702  3762 I elo.mobile.tes: Alloc concurrent copying GC freed 3962(13MB) AllocSpace objects, 0(0B) LOS objects, 49% free, 2555KB/5111KB, paused 1.607ms total 12.055ms
--------- beginning of crash
01-14 05:46:48.528  3702  3762 E AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
01-14 05:46:48.528  3702  3762 E AndroidRuntime: Process: org.celo.mobile.test, PID: 3702
01-14 05:46:48.528  3702  3762 E AndroidRuntime: java.lang.OutOfMemoryError: Failed to allocate a 8208 byte allocation with 4112 free bytes and 4112B until OOM, target footprint 16777216, growth limit 16777216
01-14 05:46:48.528  3702  3762 E AndroidRuntime: 	at okio.Segment.<init>(Segment.java:63)
01-14 05:46:48.528  3702  3762 E AndroidRuntime: 	at okio.SegmentPool.take(SegmentPool.java:48)
01-14 05:46:48.528  3702  3762 E AndroidRuntime: 	at okio.Buffer.writableSegment(Buffer.java:1301)
01-14 05:46:48.528  3702  3762 E AndroidRuntime: 	at okio.Okio$2.read(Okio.java:138)
01-14 05:46:48.528  3702  3762 E AndroidRuntime: 	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
01-14 05:46:48.528  3702  3762 E AndroidRuntime: 	at okio.RealBufferedSource.read(RealBufferedSource.java:51)
01-14 05:46:48.528  3702  3762 E AndroidRuntime: 	at okhttp3.internal.http1.Http1Codec$AbstractSource.read(Http1Codec.java:363)
01-14 05:46:48.528  3702  3762 E AndroidRuntime: 	at okhttp3.internal.http1.Http1Codec$ChunkedSource.read(Http1Codec.java:453)
01-14 05:46:48.528  3702  3762 E AndroidRuntime: 	at okio.RealBufferedSource.read(RealBufferedSource.java:51)
01-14 05:46:48.528  3702  3762 E AndroidRuntime: 	at com.facebook.react.devsupport.MultipartStreamReader.readAllParts(MultipartStreamReader.java:136)
01-14 05:46:48.528  3702  3762 E AndroidRuntime: 	at com.facebook.react.devsupport.BundleDownloader.processMultipartResponse(BundleDownloader.java:184)
01-14 05:46:48.528  3702  3762 E AndroidRuntime: 	at com.facebook.react.devsupport.BundleDownloader.access$100(BundleDownloader.java:34)
01-14 05:46:48.528  3702  3762 E AndroidRuntime: 	at com.facebook.react.devsupport.BundleDownloader$1.onResponse(BundleDownloader.java:150)
01-14 05:46:48.528  3702  3762 E AndroidRuntime: 	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
01-14 05:46:48.528  3702  3762 E AndroidRuntime: 	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
01-14 05:46:48.528  3702  3762 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
01-14 05:46:48.528  3702  3762 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
01-14 05:46:48.528  3702  3762 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919)
01-14 05:46:48.533  3702  3762 I Process : Sending signal. PID: 3702 SIG: 9

**Comment by etuleu** [comment]
This is fixed by running the app in release mode.

I believe there is still a flaky test related to deep links which I can look into today.

**Comment by etuleu** [comment]
We can still upgrade the RAM of the emulator. I can test that to see if it still helps in release mode or if it speeds up things.

**Comment by jeanregisser** [comment]
Fixed
