### ISSUE TITLE
Release 3 on Alfajores

### ISSUE THREAD

**Issue by aslawson** [celo-org/celo-monorepo#6677]

**Comment by nambrot** [comment]
Note that deploys need to include https://github.com/celo-org/celo-monorepo/pull/6937

**Comment by martinvol** [comment]
The StableTokenEUR initialization parameters should be changed from:
`"StableTokenEUR": ["Celo Euro", "cEUR", 18, "0x000000000000000000000000000000000000ce10", "1000000000000000000000000", "47304000", ["0xD533Ca259b330c7A88f74E000a3FaEa2d63B7972", "0x989e1a3B344A43911e02cCC609D469fbc15AB1F1"], ["2000000000000000000000000", "6000000000000000000000000"], "ExchangeEUR"],`

to:

`"StableTokenEUR": ["Celo Euro", "cEUR", 18, "0x000000000000000000000000000000000000ce10", "1000000000000000000000000", "47304000", ["0xAA963FC97281d9632d96700aB62A4D1340F9a28a", "0x489324b266DFb125CC791B91Bc68F307cE3f6691"], ["2000000000000000000000000", "6000000000000000000000000"], "ExchangeEUR"],`

where `0xAA963FC97281d9632d96700aB62A4D1340F9a28a ` is the community fund in Alfajores and `0x489324b266DFb125CC791B91Bc68F307cE3f6691` is a test wallet we control.

**Comment by nambrot** [comment]
Env-test pass as expected
