### ISSUE TITLE
Reporting script for monitoring multiple addresses

### ISSUE THREAD

**Issue by carterqw2** [celo-org/celo-monorepo#6697]
**Acceptance Criteria**

There is a CLI application that:
 - accepts the following parameters:
   - path to the file with the list of addresses in the `0x...` format
   - start date (in the `YYYY-MM-DD` format)
   - end date (in the `YYYY-MM-DD` format)
   - optional path to the output file
 - validates the format of addresses on the list
 - using Blockscout (or Blockchain API) gathers the following statistics for the given list of addresses in the given date range:
   - the total amount (in cUSD) received by all the addresses
   - the average amount (in cUSD) received by all the addresses
   - the average fee amount (in cUSD) charged on transfers to the addresses
   - the average amount of time (in seconds) for a transfer to the addresses
- outputs the result in CSV format if the output path is defined, otherwise, prints out the result

**Comment by aaronmboyd** [comment]
@carterqw2 Made adjustments we discussed, including block times.

Moved repo to live under celo-org/simple-address-statistics.

**Comment by aaronmboyd** [comment]
@carterqw2 Please review and close if appropriate.
