### ISSUE TITLE
Account Recovery Key improvements

### ISSUE THREAD

**Issue by ole-nov** [celo-org/celo-monorepo#6698]
### Expected Behavior

TBA

Notion doc: https://www.notion.so/clabsco/Account-Key-Recovery-Exploration-62e4078a9950418abb7f2868d5b7373c
Google doc: https://docs.google.com/document/d/1X2E5ore11XMNgFnA92ow-NARTOY2osWZIiDekJxAE_8/edit

### Current Behavior

Atm account key consists of 24 randomly chosen English words. The assumption is that this approach is bad for a couple of reasons, among the main of them are:

- Only English words are available atm, which is a problem for the users who don't speak English (a presumably big chunk of our potential customers);
- Users don't choose the words themselves, they are selected randomly by the algorithm, which means it is harder for the end-user to memorize their account key.

**Comment by nategraf** [comment]
I am going to close this Epic in favor of https://github.com/celo-org/celo-monorepo/issues/7240, which contains more detail on the approach we are planning to take.
