### ISSUE TITLE
Wallet Users SBAT talk to the network via bootnodes 

### ISSUE THREAD

**Issue by ashishb** [celo-org/celo-monorepo#67]
### Expected Behavior

Should be able to use a bootnode to discover full nodes

### Current Behavior

What RNGeth calls bootnodes are actually static nodes, and thus we can't pass our actual bootnode to RNGeth right now

**Comment by ashishb** [comment]
Passing via RNGeth is trivial as long as we know that Geth supports boot nodes.

https://github.com/celo-org/geth/blob/73c1d86b519c72722a924664304e6573cbcf77fa/mobile/geth.go#L147 - set
this to true and build a geth. Discovery works on the mobile client as confirmed in the logs.

The goal will be to make this parameter configurable via react-native-geth.

**Comment by ashishb** [comment]
Plan of action

1. https://github.com/celo-org/celo-blockchain/blob/73c1d86b519c72722a924664304e6573cbcf77fa/mobile/geth.go#L147 - change this to be configurable. Similar to how `config.SyncMode` is.

2. Pass it via `react-native-geth`. Again similar to `syncmode` https://github.com/celo-org/react-native-geth/search?utf8=%E2%9C%93&q=syncmode&type=

3. Configure it in the mobile app. https://github.com/celo-org/celo-monorepo/blob/c6adcb24962cdeb52201ca4a429b08e8039f92f5/packages/mobile/src/geth/geth.ts#L61

**Comment by timmoreton** [comment]
@tkporter Please check in with @cmcewen as he has some plans for changes to react-native-geth
