### ISSUE TITLE
More intelligent CI recognition of relevant contract tests

### ISSUE THREAD

**Issue by yorhodes** [celo-org/celo-monorepo#6714]
### Expected Behavior

Only related tests run

ie if migrationsConfig changes, all tests run

if signatures library changes, all downstream dependencies run

### Current Behavior

All tests always run

**Comment by nambrot** [comment]
Feels like a good idea, but IMO we are not quite bottlenecked by this kind of testing yet, and it seems still worth the safety to just run all right now?

**Comment by m-chrzan** [comment]
Agreed with Nam's comment above. The effort:benefit ratio of doing this correctly seems too high.
