### ISSUE TITLE
ODIS E2E tests to run in CI 

### ISSUE THREAD

**Issue by codyborn** [celo-org/celo-monorepo#6717]
As an ODIS developer, I should be able to easily identify E2E issues before production deployment

E2E tests will provide us better protection against regression going forward. Need to investigate how best to run this since it will require a deployment.

**Comment by codyborn** [comment]
E2E tests will provide us better protection against regression going forward. Need to investigate how best to run this since it will require a deployment.

**Comment by alecps** [comment]
- Promotion process
- e2e running locally

**Comment by alecps** [comment]
Output of this ticket should be a design doc + tickets specifying the approach and changes needed

**Comment by codyborn** [comment]
This was the latest on this front
https://docs.google.com/document/d/115uDd1_RLyDTIZ91Fku7_xG0uW9USWpOYHF-Epta990/edit

**Comment by alecps** [comment]
Out of date. Integration tests added in #9161
