### ISSUE TITLE
ODIS abuse monitoring

### ISSUE THREAD

**Issue by codyborn** [celo-org/celo-monorepo#6724]
Alerting on rate of ODIS usage over time (compared to expected Valora usage).
Start with simple alert if we see more requests than expected over a day or week period. 
Another potential alert is on the max number of requests from a single address. If a single address requests thousands of ODIS signatures, it's likely unexpected and abusive. 

Update: Output of this ticket should be a written investigation into abuse monitoring approaches. Additional tickets may be created to implement these approaches depending on their complexity

**Comment by codyborn** [comment]
I think this is a larger item since we'll need to get data into BigQuery/Metabase to build thorough charts. Last milestone I tried to cover this in StackDriver and reached the limits of what it's capable of:

https://console.cloud.google.com/monitoring/dashboards/custom/2873fde9-f0d9-4961-9563-68677dacebd8?project=celo-pgpnp-mainnet&timeDomain=1w

![image.png](https://images.zenhubusercontent.com/5f8782182bc44530856af91b/58303f27-98ef-4f05-bb23-5eb72637a912)

**Comment by alecps** [comment]
This should be reviewed in the context of the 'Attacks on ODIS' discussion
