### ISSUE TITLE
Attestation Service Opt-in Metrics using Prometheus

### ISSUE THREAD

**Issue by codyborn** [celo-org/celo-monorepo#6727]
Use the common opt-in pipeline that Conner has created to get better visibility into the 3rd party AS. 

1. Sync with Conner to get an understanding of the pipeline readiness
2. Use Prometheus endpoints to collect metrics
3. Build dashboards from these metrics

**Comment by nambrot** [comment]
I'd love for us to get to this, especially since it sounds like on the cLabs side we are making progress on Grafana

**Comment by alecps** [comment]
De-prioritizing in favor of ASv2
