### ISSUE TITLE
Long term solution for pinning versions in CLI

### ISSUE THREAD

**Issue by aslawson** [celo-org/celo-monorepo#6736]
`shrinkwrap` seems more like a short term solution. see 
[Slack thread](https://celo-org.slack.com/archives/C014SRL4URY/p1611609949077800)

- short term solution adds a couple steps to process and it a bit hacky (verifies with commit hash)
- Investigate if we should have a better solution

**Comment by barbaraliau** [comment]
Still need to add checks to verify libraries with every update
