### ISSUE TITLE
Allow CLI plugins

### ISSUE THREAD

**Issue by aslawson** [celo-org/celo-monorepo#6738]
Related PR: https://github.com/celo-org/celo-monorepo/pull/5973

TODOs:
- [x] get it mergeable again (current merge conflicts)
- [x] if decision is to go forward with this -> add a warning label with using this
- [x] reach out to infosec for further thoughts on this

**Comment by barbaraliau** [comment]
* Would also need to include warning on CLI if this is merged
* Could mitigate risk by recommending plugins, hosting them on our npm, need process for reviewing

**Comment by eelanagaraj** [comment]
Current status: 
- implemented a prerun hook in our CLI which will check if either of the install commands (`plugins:install` or `plugins:link`) is called and if so, require the user to explicitly say Y/N to letting install proceed. Current warning message: `Installing a 3rd party plugin can be *dangerous*! Are you sure you trust this plugin and want to install it? (y/n)`
- added logic for only allowing packages in `@celo/` NPM scope (i.e. published by `celo` organization) to be installed.

Depending on the result of the meeting with the security circle tomorrow, we can decide:
1) if it makes sense to use one or both of the checks above (explicit consent, only `@celo` scope)
2) if yes to the consent message, what warning message we want to display.
3) if we want to close this PR for now and reimplement once we can also add signing, verifying, and whitelisting as one bundled feature

**Comment by eelanagaraj** [comment]
Waiting for review + decision on whether we want to keep the prompt confirming user consent, and if so, what we want the message to be.

We could also add checking for the `@clabs/*` NPM scope (once we reserve this scope) and suggest that future plugins, (e.g. merkle-distributor) are published under this scope, while `@celo/*` is used for "core" plugin functionality. Thoughts on this? @barbaraliau @aslawson @medhak1 

After that, I'd say it's ready to merge, considering that we got the security circle's sign-off on the most restrictive version of this.

**Comment by aslawson** [comment]
@eelanagaraj I think we should keep the warning, since you did all the work, and we will hopefully be able to lift the restriction in the future.

Copy looks good as is. Can we also update the docs as part of this ticket to say:
```
Plugins
Currently, celocli only supports installing plugins within the @celo/* and @clabs/* scopes. Installing a 3rd party plugin can be *dangerous*! Please always be sure that you trust the plugin provider.
```

**Comment by eelanagaraj** [comment]
@aslawson Sounds good! I changed the order of the checks though (break fast if the scope doesn't match, then ask to confirm installation) as I hope that'll be less confusing for people and it won't feel like it's breaking despite them giving consent. Does that sound ok to you? I updated the docs per your suggestion, here's what this will look like on the docs ([forked repo page on gitbook](https://app.gitbook.com/@eela/s/forked-monorepo-come-on/command-line-interface/introduction/~/settings/integrations).

**Comment by eelanagaraj** [comment]
also, wondering if @ewilz's cusd rewards plugin is a good candidate for the inaugural plugin published by the @clabs org on NPM? (realize that this is over a month after your earlier comment @ewilz but in case it's still relevant/would be useful, happy to give you more context or see if that works out, even though this is separate from your point about making it easier to build on the base command!) cc @aslawson

**Comment by aslawson** [comment]
@eelanagaraj docs looks good 👍. can they also be added to README so they appear in the NPM documentation as well?

**Comment by eelanagaraj** [comment]
@aslawson good idea, added basically the same message to the CLI `README`. (I didn't add instructions for calling the actual `plugins` command, feel like it's maybe best to advertise the warning but not necessarily encourage people to use it too much right now since there's not much that can be installed at the moment, but what do you think? Also feel happy to tweak the formatting, message, etc. doc nits are very welcome!)

**Comment by aslawson** [comment]
Sounds good. Thanks @eelanagaraj

**Comment by eelanagaraj** [comment]
If you have a second to review/approve @aslawson, would love to get it merged :) otherwise I can ping DevX as well!

**Comment by ewilz** [comment]
> also, wondering if @ewilz's cusd rewards plugin is a good candidate for the inaugural plugin published by the @clabs org on NPM? (realize that this is over a month after your earlier comment @ewilz but in case it's still relevant/would be useful, happy to give you more context or see if that works out, even though this is separate from your point about making it easier to build on the base command!) cc @aslawson

Just seeing this. Would be happy to test this out with you guys with the rewards cli. I've been busy and would welcome support on getting this setup with my existing CLI 😅

**Comment by eelanagaraj** [comment]
@ewilz for sure! I was testing the plugin functionality using your CLI as is (following how Nam tested it earlier), so I think all we would need to do is publish it under our NPM scope. (In the future we can look at making the base command more extensible and whatnot). I'll look into it + get back to you 😄
