### ISSUE TITLE
[Attestation Service] Investigate 10DLC requirements -- issue guidance

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-monorepo#6744]
### Expected Behavior

Providers can send SMS to all US phones on all networks

### Current Behavior

* Verizon is introducing something which seems to have triggered additional KYC reqs for Nexmo. Risk is misconfigured providers that are set up but always fail
* Twilio seems unaffected? https://support.twilio.com/hc/en-us/articles/360008372654-Commercial-Long-Code-SMS-MMS-Product-and-Fee-Structure-Changes-on-Verizon

**Comment by eelanagaraj** [comment]
Public guidance is located [here](https://www.notion.so/clabsco/10DLC-Guidance-6f23dcff502f45b4afae02254c629c61)
