### ISSUE TITLE
Upgrade DappKit and Tutorials to use current expo client and reactnative versions

### ISSUE THREAD

**Issue by aslawson** [celo-org/celo-monorepo#6751]
- [x] https://github.com/celo-org/celo-monorepo/tree/master/packages/sdk/dappkit
- [x] https://github.com/critesjosh/celo-dappkit
- [x] https://github.com/critesjosh/hello_contract-truffle
- [ ] https://github.com/critesjosh/savings-circle-demo
- [x] https://github.com/critesjosh/helloCelo

**Comment by critesjosh** [comment]
I updated dependencies for the repos that may be blocking anything else, so I removed the blocker tags
