### ISSUE TITLE
Extend analysis from single order book to set of order books

### ISSUE THREAD

**Issue by sissnad** [celo-org/celo-monorepo#6763]
This is a subtask of [Analysis of bucket sizes prior to cEUR deployment #6179](https://app.zenhub.com/workspaces/platform-economics---sprint-board-5f89a1e34ce1b6001230771d/issues/celo-org/celo-monorepo/6179)

**Comment by pedro-clabs** [comment]
Keeping it open for cleaning up the analysis notebooks.
