### ISSUE TITLE
Daily scrape of on-chain balances to Eksportisto

### ISSUE THREAD

**Issue by ewilz** [celo-org/celo-monorepo#6764]
### Expected Behavior

Have access to balances for a given date

### Current Behavior

Data is in raw state, needs to be tranformed

**Comment by jbsibille** [comment]
https://celo-org.slack.com/archives/C01B3RG4B50/p1611704893004700

**Comment by jbsibille** [comment]
https://www.notion.so/clabsco/Reward-users-for-holding-a-cUSD-balance-5d5f102e7a9c4886b889d689324a16bf
