### ISSUE TITLE
Research: Reward users for inviting others

### ISSUE THREAD

**Issue by ewilz** [celo-org/celo-monorepo#6767]
### Expected Behavior
Research how to determine that a user invited another user onto the platform. (valora in this case?)
**Eligibility**
- Sender address must be verified
- Sender address must invite someone else via phone number by sending them at least XX cUSD (tbd if minimum amount)
- Receiver phone number must not be already on the Celo platofrm
- Receiver must confirm phone number

https://www.notion.so/clabsco/CELO-rewards-9d31cf64f82f4f1e9a3894fdc6672924?p=e85e2a0afe8847a198ee4fcadc8ff762

### Current Behavior

What is the current behavior?

**Comment by ewilz** [comment]
Design Doc: 
https://docs.google.com/document/d/1FgglpekEgRiEC1rOdJWMg88uRDV9N41pwwCezCbJyyY/edit?usp=sharing

**Comment by jbsibille** [comment]
@carterqw2 posted suggested plan for feedback here: https://celo-org.slack.com/archives/CP5V8KF51/p1614118046078800?thread_ts=1613510571.197600&cid=CP5V8KF51
