### ISSUE TITLE
Devs SBAT see design doc to access historical gold/dollar exchange rate data

### ISSUE THREAD

**Issue by cmcewen** [celo-org/celo-monorepo#677]
### Expected Behavior

The wallet can access historical gold/dollar exchange rate data from the Exchange

### Current Behavior

Only fetch current rate

**Comment by annakaz** [comment]
Reopened because this is about gold/dollar exchange rate not currency exchange rate

**Comment by annakaz** [comment]
Design doc: https://docs.google.com/document/d/1XTezvn0cbplJI5cXAT1RIXihxg9BBhBSsuv3HNb8ejM/edit?usp=sharing

**Comment by annakaz** [comment]
Design doc completed here: https://docs.google.com/document/d/1XTezvn0cbplJI5cXAT1RIXihxg9BBhBSsuv3HNb8ejM/edit#
