### ISSUE TITLE
CELO native transfer push notification

### ISSUE THREAD

**Issue by ole-nov** [celo-org/celo-monorepo#6776]
### Expected Behavior

"As a user I expect to get push notification when I received CELO transfer to my account."

### Current Behavior

What is the current behavior?

**Comment by ole-nov** [comment]
@jeanregisser , in another issue @gnardini commented that this issue is already part of the https://github.com/celo-org/celo-monorepo/issues/6533

**Comment by jeanregisser** [comment]
Yes as discussed on Slack, we want to keep these 2 issues separate.
