### ISSUE TITLE
Initialization data should use named parameters akin to migrationsConfig

### ISSUE THREAD

**Issue by yorhodes** [celo-org/celo-monorepo#6777]
### Expected Behavior

`releaseData/initializationData/releaseXXX.json` looks like 

```json
{
  "registryID_X": {
    "X_initializeParam1Name": "param1Value",
    "X_initializeParam2Name": "param2Value"
  },
  "registryID_Y": {
    "Y_initializeParam1Name": "param1Value",
    "Y_initializeParam2Name": "param2Value"
}
```

### Current Behavior

Hard to understand how array maps to params

**Comment by yorhodes** [comment]
it might even be nice if the migrations *read from* the initialization data for reproducing prod after releases 1-N

**Comment by yorhodes** [comment]
related https://github.com/celo-org/celo-monorepo/pull/6780

**Comment by nambrot** [comment]
@yorhodes Where would you put this in terms of priority?
