### ISSUE TITLE
CLI Tests should be able to be run internally 

### ISSUE THREAD

**Issue by medhakothari** [celo-org/celo-monorepo#6778]
### Expected Behavior

`yarn run tests` in `packages/cli` should run all the unit tests. 

### Current Behavior

`FAIL  src/commands/account/register.test.ts
  Test suite failed to run
    TypeError: Cannot redefine property: configDescriptor
        at Function.defineProperty (<anonymous>)
      at Object.<anonymous> (../../node_modules/usb/usb.js:48:8)
      at Object.<anonymous> (../../node_modules/@ledgerhq/hw-transport-node-hid/src/listenDevices.js:6:1)
      at Object.<anonymous> (../../node_modules/@ledgerhq/hw-transport-node-hid/src/TransportNodeHid.js:14:1)`

**Comment by medhakothari** [comment]
Update: no updates on this issue at the moment

**Comment by eelanagaraj** [comment]
Looks like it may be related to [this issue](https://github.com/LedgerHQ/ledgerjs/issues/197) with jest/ledger. Possible issue: jest is trying to re-import an already imported module (`@ledgerhq/hw-transport-node-hid`) which causes all suites after the first file's tests are run.

Running 
```
yarn jest src/commands/account/
yarn jest src/commands/governance/
yarn jest src/commands/lockedgold/
yarn jest src/commands/releasegold/
yarn jest src/commands/reserve/
yarn jest src/commands/validator/
yarn jest src/commands/validatorgroup/
```
causes all tests to run. Note it seems like there are a lot of failing tests on master right now; CI looks like it's working, but 22 of 50 tests are flakey, which is something we should probably look into as well, but maybe separate from this.

Confirmed that it has to do specifically with this import in `packages/cli/src/base.ts`: `import TransportNodeHid from '@ledgerhq/hw-transport-node-hid'`

**Comment by eelanagaraj** [comment]
Also re: CI -- looks like 22 of 50 tests are flakey, which is something we should probably look into as well.

**Comment by eelanagaraj** [comment]
Minimal bug repro here: https://github.com/eelanagaraj/jest-ledger-debug
Submitted an issue with ledger here: https://github.com/LedgerHQ/ledgerjs/issues/572 to see if they have any additional thoughts on this/can take a look before we add a weird/hacky fix for this

**Comment by aslawson** [comment]
no response from ledger team -- lets just implement the workaround previously explored.

**Comment by aslawson** [comment]
This is now running internally, but failing locally in different ways

**Comment by eelanagaraj** [comment]
@aslawson just to clarify (unless something else changed on master) -- [this PR](https://github.com/celo-org/celo-monorepo/pull/7959) fixes it locally (so it runs) but certain tests fail locally but not on CI. (On master, tests were still not running locally last I checked). We can go ahead and merge that PR as a first step and then individual code owners can look into the tests failing locally, wdyt?
