### ISSUE TITLE
Baklava AS dashboard for Foundation Voting

### ISSUE THREAD

**Issue by codyborn** [celo-org/celo-monorepo#6783]

**Comment by codyborn** [comment]
It'd be helpful for the Foundation to have a granular view on Baklava AS nodes. Currently [Baklava AS Score](https://celo.org/validators/explore/baklava) is used but it can't be used to select a custom look back window. 
Create a simple Metabase dashboard for getting AS score (completion/requested) for a custom look back window.

**Comment by alecps** [comment]
@eelanagaraj do you know if this is still relevant?

**Comment by eelanagaraj** [comment]
I don't think so -- foundation voting should be based on Mainnet voting (though not sure about this for new validators). Will close for now as it's very low priority in any case, and we can reopen if need be
