### ISSUE TITLE
[CLI] rewards:show gives `Error: invalid BigNumber string`

### ISSUE THREAD

**Issue by oneeman** [celo-org/celo-monorepo#6787]
### Expected Behavior

No error

### Current Behavior

```
❯ celocli rewards:show --voter 0x01b2b83fdf26afc3ca7062c35bc68c8dde56db04 --estimate
Running Checks:
   ✔  0x01b2b83fdf26afc3ca7062c35bc68c8dde56db04 is a registered Account
Calculating rewards... !
    Error: invalid BigNumber string (argument="value", value="01b2b83fdf26afc3ca7062c35bc68c8dde56db04", code=INVALID_ARGUMENT, version=bignumber/5.0.13)
    Code: INVALID_ARGUMENT
```

Tested with celo cli v1.0.3.

I looked into this and it is due to https://github.com/celo-org/celo-monorepo/blob/4e0231e6fb411118479b2d4084159ed1caabdcb8/packages/sdk/contractkit/src/wrappers/Election.ts#L514, which strips the `0x`.  If you replace it with `normalizeAddressWith0x()` then it works.

However, there is a further problem that I noticed while investigating this.  Sometimes, when running this command in the CLI from the monorepo, it will simply halt in the middle of execution, giving neither an error nor the result.  Here is an example:

```
❯ node   ./bin/run rewards:show --voter 0x01b2b83fdf26afc3ca7062c35bc68c8dde56db04 --estimate
Running Checks:
   ✔  0x01b2b83fdf26afc3ca7062c35bc68c8dde56db04 is a registered Account
Calculating rewards... ⡿
❯
```
[with the program halting with no further output, whereas it should give a result such as "No rewards" or something else]

@gastonponti and I looked into this briefly, and suspect it has to do with web3 requests timing out, which we experimented with by initializing web3 using `HttpProvider` with different `timeout` values in the options.  We managed to reproduce this halting behavior happen by using timeouts that are long enough to get past the node synced check (which fails with an error if it times out) but to give a timeout on a later request.  However, even setting the timeout to a huge value like 1000000 ms, I still see the CLI halt like that without an error or result, which doesn't make sense.  Note that I've only observed this running the CLI from the monorepo directory, not running it from the global npm installation of the CLI.  Still, it is quite concerning since the program is halting having neither given an error nor finished executing its normal code path.

Additionally, @gastonponti suggested also looking into why it is that the address is being converted in web3's internals into a BigNumber during the method call.

**Comment by aslawson** [comment]
We should investigate if this is the way we want to fix this. ^

**Comment by jmrossy** [comment]
Just tacking this on here, hope folks don't mind:

The `examples` text for the command is incorrect:
https://github.com/celo-org/celo-monorepo/blob/c328556e39b4e89321c290e73a2b3eccb2bcdf8d/packages/cli/src/commands/rewards/show.ts#L41

Not a huge deal, would make sense to fix when we fix this bug.

More broadly, the current approach for providing this info requires querying state history from the full nodes, which are expensive queries. Would be good to investigate other ways to get this information. One thought that comes to mind is making the contract's `EpochRewardsDistributedToVoters` events contain more info, but that's just a first thought may not work for all cases.

**Comment by aslawson** [comment]
Additional report #6787
