### ISSUE TITLE
Scope Required Work to Support cEUR in CLI

### ISSUE THREAD

**Issue by aslawson** [celo-org/celo-monorepo#6790]
Should consider doing so in a generalized way that would set us up to support additional future stable tokens.

Cli: transfer, exchange, flag for gas in ceur (should be straight forward)

Related to issue #7100

**Comment by aslawson** [comment]
@asaj do you have a sense in timeline of when cli/faucet changes need to be delivered?

**Comment by eelanagaraj** [comment]
Would this involve producing a design doc for a general procedure for adding new stable tokens to CLI/Faucet[/Rosetta]? Or is the output of this one a list of tasks that need to be done per category?

**Comment by barbaraliau** [comment]
Possible to have ContractKit request data from the node - gas estimation in other tokens cc @gastonponti 
Check if nodes have versions. Can refactor CK. Node generate gas estimation.

**Comment by barbaraliau** [comment]
todo: split issue
sync with protocol economics - CK work

**Comment by eelanagaraj** [comment]
split up --> related issue https://app.zenhub.com/workspaces/devx-sprint-board-5fd7e7014356ff000e7a5b19/issues/celo-org/celo-monorepo/7100
