### ISSUE TITLE
Scope Required Work to Support cEUR in Ledger

### ISSUE THREAD

**Issue by aslawson** [celo-org/celo-monorepo#6791]
Should consider generalizing approach to set Ledger up to support future stabletokens.

Ledger: generate de data file for the contracts in every chain

From Asa: "ledger app should be very easy but with perhaps high latency." we won't be able to submit for approval until we have the contract address from the contract release (~March 1), but should have it ready to plug in the address then.

**Comment by aslawson** [comment]
@asaj do you have a sense of the timeline in which this ledger work needs to be delivered?

**Comment by kobigurk-clabs** [comment]
I think https://app.zenhub.com/workspaces/celo-5d94ef61d9b1e40001114c02/issues/celo-org/celo-labs/848 covers this issue. Let me know what you think!

**Comment by martinvol** [comment]
Thanks Kobi, with that I'd consider the scoping done!
