### ISSUE TITLE
cEUR support for Ledger

### ISSUE THREAD

**Issue by aslawson** [celo-org/celo-monorepo#6794]
Ledger: generate de data file for the contracts in every chain

**Comment by albertclabs** [comment]
Depends on CR3
Needed for the Foundation's funds management.

**Comment by asaj** [comment]
Specifically it's blocked on having a contract address for cEUR

**Comment by martinvol** [comment]
This involves updating the blobs [here](https://github.com/celo-org/celo-blockchain/blob/master/accounts/usbwallet/ledger/tokens_data.go) and [here](https://github.com/celo-org/celo-monorepo/blob/25b662b4eb926ae1d97d29ac72ae4bbbfcefe1ea/packages/sdk/wallets/wallet-ledger/src/data.ts).

**Comment by martinvol** [comment]
I opened a PR with the new json and now I'm waiting on the signature
