### ISSUE TITLE
cEUR support for Faucet

### ISSUE THREAD

**Issue by aslawson** [celo-org/celo-monorepo#6795]
**Faucet: add ceur (?)**

From scoping (issue #7100)

Here are the smaller sub-tasks that I think will need to be necessary for adding cEUR to the faucet (happy to move this discussion to slack as well, but wanted this documented on this ticket as well!):

_celotool changes (use cases: large transfers of cUSD/CELO/cEUR on alfajores)_
- [coordinate with protocol economics] on how much cEUR to initially provide validator-0 @martinvol 
- modify the celotool script to allow for cEUR transfers and test this out (should be straightforward to add the additional arg)

_web faucet changes (use cases: devs using web interface to request 5 CELO/10 cUSD/10? cEUR)_
- [web team] -> update the text on the faucet (very tiny change)
- [coordinate with protocol economics] initialize web faucet address (`0x22579ca45ee22e2e16ddf72d955d6cf4c767b0ef`) with a large amount of cEUR @martinvol 
- redeploy `faucetRequestProcessor` firebase function (adding transfer command for cEUR should be mostly straightforward (steps enumerated below), testing may be slightly trickier. It should be possible to test this out with the firebase emulator, but double check this)
1. modify `buildHandleFaucet`
2. extend `CeloAdapter`; (possible option to modify `transferDollars` --> `transferStable`? May be overkill/not actually make future additions easier, already quite easy)
3. test `faucetRequestProcessor` in firebase emulator if possible, or by deploying to staging? (second would be more complicated)
4. deploy `faucetRequestProcessor` under a new name on firebase? --> can test, coordinate with web for testing this on staging once cEUR is on alfajores
5. either redeploy previous function (same name) or coordinate with web to use newly deployed function once website mods are ok and faucet should start allowing for cEUR fauceting

_alerting_
- set up a devX alert on GCP tracking cEUR (should take very little time, copy cUSD alert)

(- there's an additional script: `packages/faucet/scripts/transfer-funds.ts` and it's unclear where/what service is using this, as I believe the faucet runs using the firebase function described above.)

**Comment by martinvol** [comment]
Shall I go ahead and send the balance we have in the pre-mint address to the faucet address?
What is this address?

**Comment by eelanagaraj** [comment]
@martinvol Faucet address: `0x22579ca45ee22e2e16ddf72d955d6cf4c767b0ef`

We haven't started work on this yet, but you can go ahead and transfer if you want! Otherwise happy to reach out once we've started!

**Comment by martinvol** [comment]
Just made a transfer: https://alfajores-blockscout.celo-testnet.org/tx/0xf527654fb9bff9952e0af1fd2c368b7954dc219bf5ad9c257289ee0070c4b50f

**Comment by eelanagaraj** [comment]
This took much longer than expected; getting testing set up and ready for the firebase changes ended up being much more involved than expected. (Using the firebase emulator wasn't really possible; the email/login req for requests to work made it non trivial to trigger the function programmatically and not through the web UI or by manually entering data into the staging faucet). The e2e governance tests for the celotool continue to pose an issue even though these pass locally; likely known flakey test behavior but may still be tricky to merge this. Also took a bit longer as I took the time to make (slightly) more expansive changes to celotool fauceting in particular.

Updates/remaining TODOs here: 
- celotool updates ready to go, waiting on PR review (+ CI for e2e governance tests..passing locally but this may take a little while)
- faucet firebase updates should also be ready to go, testing now works, but cannot deploy to staging until SDK version 1.1.1 is published (makes sense to wait for this as this offers more flexibility when it comes to stabletoken transfers in the future)
- want to also take some time to update the faucet docs on notion about the architecture as hopefully this will save some debugging time in the future if anything comes up

Probably 1 more day of work on this with the above things (once unblocked),

**Comment by eelanagaraj** [comment]
Update: deployed + added docs about testing/deploying in the future that should make the process much faster!

**Comment by martinvol** [comment]
Amazing!
