### ISSUE TITLE
Dev SBAT to turn Geth sync on/off

### ISSUE THREAD

**Issue by ashishb** [celo-org/celo-monorepo#68]
### Expected Behavior

Dev SBAT to turn Geth sync on/off
For example, turn sync on when the app is foregrounded and off when the app is backgrounded. Or sync less eagerly on cellular than unmetered Wi-Fi.

### Current Behavior

Geth sync runs while the app is running. In ad-hoc testing, @jmrossy found that the app uses ~1MB per minute due to syncing while running.

**Comment by ashishb** [comment]
1. Add measurements to figure out network usage - "background/foreground", "network type (cellular/wifi)". Most network usage, as of now, is due to Geth.
2. Add ability to turn sync on/off. I tried this 6 months back, saw crashes, and never got a chance to revisit this.
3. Add rules to turn sync on/off. Eg. battery below 20%, turn sync off. The User is on cellular, turn sync off. App backgrounded, turn sync off. User in data saver mode, turn sync off. This layer is decoupled and configurable from the previous layer allowing us to change these decisions over time.

**Comment by nityas** [comment]
@annakaz will this capability be taken care of as part of #1171 ?

**Comment by jeanregisser** [comment]
Data Saver mode takes care of this.
