### ISSUE TITLE
Metadata functionality should be migrated to CIP8

### ISSUE THREAD

**Issue by nambrot** [celo-org/celo-monorepo#6809]
### Expected Behavior

CIP8 is likely the better place for this kind of functionality as the tooling makes them more accessible there

### Current Behavior

Current metadata applications such as attestation service URL registration and identity claims (keybase, DNS, name, account) are harder to manage

**Comment by alecps** [comment]
Though this is now quite old, I'm leaving it open so that we remember to discuss this when thinking about the storage component of ASv2
