### ISSUE TITLE
Set cEUR bucket sizes for Contracts Release 3

### ISSUE THREAD

**Issue by yerdua** [celo-org/celo-monorepo#6817]
Based on the analysis done in #6760, set the initial bucket sizes for cEUR. This parameter can be adjusted after the contracts release 3 deployment, as a part of the cEUR activation proposal.

This issue is done when a "good enough" value is included in the commit that will be used for contracts release 3.

**Comment by asaj** [comment]
It sounds like this parameter can be adjusted after the contracts release 3 deployment as part of the cEUR activation proposal, because even though the cEUR Mento will be deployed, it will be impossible to use due to no oracle reports.
