### ISSUE TITLE
Devs SBAT deploy cEUR to a network

### ISSUE THREAD

**Issue by martinvol** [celo-org/celo-monorepo#6820]
### Expected Behavior

The tooling for deploying a testnet SBAT:
- Fund oracles address
- Deploy oracles reporting (alternatively, reporting just once and having the reports with long expiring time)
- Pass a governance proposal with:
  - enabling a oracles (see above)
  - allowing cEUR as gastoken
  - adding exchangeEUR to the exchangeSpender addresses

After this, testing transfers and exchanges of cEUR.

### Current Behavior

Everything is manual.

**Comment by aslawson** [comment]
@martinvol anything specific for the CAP backlog here? if its governance support, I can make a separate ticket to reflect that

**Comment by nambrot** [comment]
Removing the CAP label. If there is specific work necessary from CAP, please file a specific ticket, such as #6695

**Comment by bowd** [comment]
See parent epic: https://app.zenhub.com/workspaces/platform-economics---backlog-board-600a9f7399b43a001348ae1b/issues/celo-org/celo-monorepo/6162
