### ISSUE TITLE
ODIS common package release process - investigate

### ISSUE THREAD

**Issue by alecps** [celo-org/celo-monorepo#6821]
### Expected Behavior

There should be a well defined and streamlined process for testing and publishing the ODIS common package

### Current Behavior

Currently the ODIS common package must be published before its effects on the signer and combiner can be fully tested. There should be a way to ensure (before publishing) that an update to the common package will not cause tests for the signer or combiner to start failing. In addition to solving this technical problem, this ticket also includes documenting the new release process in the ODIS runbook

**Comment by nambrot** [comment]
Is this more like a P3?

**Comment by alecps** [comment]
Output of this ticket should be a design doc + tickets specifying the approach and changes needed

**Comment by emilhotkowski** [comment]
I believe this should fix it https://github.com/celo-org/celo-monorepo/pull/8268

**Comment by emilhotkowski** [comment]
@codyborn @alecps does this require any more work?

**Comment by codyborn** [comment]
@emilhotkowski this definitely solves the part of the problem of detecting breaking changes early. The second part is to automate the release process of the NPM package. I think your Github Actions approach can be used to do this if we embed NPM credentials in an env file. For now this could be triggered manually, but we might want to automatically run the release process whenever there's a version change detected.

**Comment by emilhotkowski** [comment]
Hmm do when if we were to change from a version 1.1.3-dev to 1.1.4 and pushed IT to the master we would like to have extra workflow (to automated stg release) which looks for this change and using NPM token publishes changed packages, something like that ?

**Comment by emilhotkowski** [comment]
@codyborn I believe that once we have release process in place that people agree upon and try to adapt, we could think about general approach to the NPM publishing for whole monorepo.
