### ISSUE TITLE
User should be able to change their PIN within the app

### ISSUE THREAD

**Issue by ole-nov** [celo-org/celo-monorepo#6828]
Design: https://www.figma.com/file/zt7aTQ5wuXycIwxq5oAmF9/Wallet--Refresh?node-id=3114%3A34886

Expected behavior:
 Users can go to Valora's app setting and change their PIN.

- [x] Add the "Change PIN" button to the Settings screen under the section "Security and Data" that will open the change pin screen.

- [x] Create "Change PIN" screen that should have one of four states:
- enter the existing PIN;
- create new PIN;
- confirm new PIN;
- error message if PINs don't match;

- [x] Implement logic needed to update the pin with the new one;

- [x] confirmation message on the settings screen that the new PIN is added and saved;

- [x] Add analytics events. Please find events to be implemented in this doc: https://docs.google.com/spreadsheets/d/1rnSj4fjCNE1Z0Qxjn_cpBe_AFKQgS4RlKo2NLuYAahs/edit#gid=0

**Comment by ole-nov** [comment]
Design: https://www.figma.com/file/zt7aTQ5wuXycIwxq5oAmF9/Wallet--Refresh?node-id=3114%3A34886

**Comment by michellewong793** [comment]
could we do a little more detailed scoping here? Like break it down into tickets together

**Comment by michellewong793** [comment]
just a quick update, we have the change pin feature working so far but there is UI work needed to be done to finish this task

**Comment by jeanregisser** [comment]
Done in https://github.com/celo-org/wallet/pull/221
