### ISSUE TITLE
Update Code examples to use `.env` variables for account management

### ISSUE THREAD

**Issue by critesjosh** [celo-org/celo-monorepo#6834]
### Expected Behavior

The code examples should use an `.env` file and [dotenv](https://www.npmjs.com/package/dotenv) to import account information. Consider that for projects that use Truffle, we could update to use the [`hdwallet-provider` package](https://github.com/trufflesuite/truffle/tree/develop/packages/hdwallet-provider) and the Celo derivation path to use mnemonics instead of private keys.

### Current Behavior

Account management is currently done using a JS script and stored in a file called `.secret`. Private keys are in plain text. This is low risk because it is on the testnet and for code examples only, but we want to stick to best practices in all examples.

**Comment by aslawson** [comment]
@critesjosh this seems related to tutorials. what's the best way to move it to dev rel's board?

**Comment by critesjosh** [comment]
@aslawson I will add it there, thanks for flagging.
