### ISSUE TITLE
Deploy CGP for cEUR oracle activation on Baklava

### ISSUE THREAD

**Issue by martinvol** [celo-org/celo-monorepo#6845]
The goal of this governance proposal is to allow oracles to start reporting the CELO/EUR rate, while preventing activation of ExchangeCEUR. The proposal needs to contain these things:

- Freeze ExchangeCEUR
- Freeze StableTokenCEUR (TODO: determine if this is necessary or desirable)
- Add oracle addresses to the SortedOracle whitelist for cEUR

Note: This should be basically the same as the CGP in #6167 on a private testnet. If we learned of any adjustments/changes needed there, those should be incorporated in this CGP.

**Comment by bowd** [comment]
```
baklava-celoeur-oracle0 -> 0xC7D2B97d104f71a4E1E773A99886ca7ad8a5CCF8
baklava-celoeur-oracle1 -> 0x70E4F7Bc64d878091cFB8eDF30C3968095178216
baklava-celoeur-oracle2 -> 0x042aC21b9CDA6171881135884DE16CF6aCa78375
baklava-celoeur-oracle3 -> 0xc496d108C6781Fbc9967E48873Eac2eA14ca119a
baklava-celoeur-oracle4 -> 0x54050b55eD9f78Ef143B5182E8C767A101DFe9CC
baklava-celoeur-oracle5 -> 0x39862a96a28800A1f626D86f20900085705D1156
baklava-celoeur-oracle6 -> 0xbbD2b821C7F376cB4D22b317530706D43688495e
baklava-celoeur-oracle7 -> 0x4Ab2B594f08403b6324Cb0B172e332d8a08f1d5a
baklava-celoeur-oracle8 -> 0x21d66472604A931211379A32710D26AFA203D190
baklava-celoeur-oracle9 -> 0xECF4192Db52696CD08cB909e700b1F5962aa6fA2
```

**Comment by martinvol** [comment]
Already passed!
