### ISSUE TITLE
Attestation Service Standards Doc

### ISSUE THREAD

**Issue by codyborn** [celo-org/celo-monorepo#6864]
https://discord.com/channels/600834479145353243/654086275900375041/805875109687853076
We should provide some documentation of standards for AS operators when interfacing with all three SMS providers. For example, MessageBird requires a name to be specified as the sender. This should be standardized to provide a common experience for Celo users.

**Comment by codyborn** [comment]
Starting point: https://www.notion.so/clabsco/SMS-Provider-Validator-Support-Template-e168d45219e844e8a826c1ccefb5a06a

**Comment by codyborn** [comment]
Setting as P1 due to small amount of work (Amy already started) and the asks we're getting from validators.

**Comment by aslawson** [comment]
https://www.notion.so/clabsco/SMS-Provider-Validator-Support-Template-e168d45219e844e8a826c1ccefb5a06a#797033879adf469d9cbe1ee56b1d0e61

Believe we have most of this complete here. But there is still work to get validators to set up their brand by the 10dlc deadline (between april 1 - june 1)
https://support.twilio.com/hc/en-us/articles/1260800720410-What-is-A2P-10DLC-

```
As of April 1, 2021, you can begin registering in Twilio’s Trust Hub. 
You will have until June 1, 2021 to complete registration.
```

I'll create a separate ticket for tracking.

**Comment by aslawson** [comment]
[Get all Attestation Services with Twilio to Set up 10DLC brand/campaign](https://app.zenhub.com/workspaces/cap-backlog-board-600598462807be0011921c65/issues/celo-org/celo-monorepo/7370)
