### ISSUE TITLE
make-release script should accept a private key 

### ISSUE THREAD

**Issue by alecps** [celo-org/celo-monorepo#6868]
### Expected Behavior

It should be straightforward to figure out how to provide a private key to the make-release script so that it can deploy the contracts. The script should either accept a private key as input or have clear documentation explaining how to provide the private key to the script

### Current Behavior

make-release looks for the private key on the node it is connected to. If you are using forno or port-forwarding to a mainnet validator then no accounts are unlocked. This means that mainnet proposers must start up a light node with an unlocked and funded account in order to run the script. The docs don't currently explain this.

**Comment by nambrot** [comment]
I'll probably can do this as part of the docs re-haul I've been meaning to do
