### ISSUE TITLE
Update CoinMarketCap API Endpoints to report cEUR

### ISSUE THREAD

**Issue by clrblmt** [celo-org/celo-monorepo#6877]
[Ideal API Endpoint Samples](https://docs.google.com/document/d/1S4urpzUnO2t7DmS_1dc4EL4tgnnbTObPYXvDeBnukCg/edit)

Existing endpoints:

- https://thecelo.com/api/v0.1.js?method=ex_totalcoins 
- https://thecelo.com/api/v0.1.js?method=ex_cusd_circulating (circulating supply refers to the # of coins that are circulating in the market and in the general public's hands)
- https://thecelo.com/api/v0.1.js?method=ex_summary
- https://thecelo.com/api/v0.1.js?method=ex_assets
- https://thecelo.com/api/v0.1.js?method=ex_ticker
- https://thecelo.com/api/v0.1.js?method=ex_orderbook
- https://thecelo.com/api/v0.1.js?method=ex_celocusd

**Comment by albertclabs** [comment]
Above endpoints are operational and CoinMarketCap listing has been submitted. Currently CMC listing in "untracked" status until we get more exchange adoption.

**Comment by martinvol** [comment]
Amazing @albertclabs!


Thanks Bi23 for the update!
