### ISSUE TITLE
ODIS log shipping to Stackdriver( / Grafana)

### ISSUE THREAD

**Issue by kevjue** [celo-org/celo-monorepo#6884]
### Expected Behavior

AKS deployed ODIS signer logs should be shipped to GCP Stackdriver service.

### Current Behavior

Those logs are being sent to Azure log analytics.

### Miscellaneous

So this [PR](https://github.com/celo-org/celo-monorepo/pull/5934), which does the same thing for Komenci.

**Comment by alecps** [comment]
This should be reviewed in the context of migrating to grafana

**Comment by alecps** [comment]
closing in favor of https://app.zenhub.com/workspaces/identity-backlog-board-60e61301c3dc55000e540b61/issues/celo-org/celo-monorepo/9118
