### ISSUE TITLE
Confirm cEUR bucket size parameters for cEUR activation

### ISSUE THREAD

**Issue by yerdua** [celo-org/celo-monorepo#6901]
An initial value for cEUR bucket sizes is included in Contracts Release 3. However, because cEUR Mento is impossible to use before there are oracle reports, we have another chance to adjust this value based on further analysis.

This issue is done when:
- We have decided on a final value for this parameter. 
- If that final value is different than the initial value set in #6817, the new value is included in the cEUR activation governance proposal

**Comment by yerdua** [comment]
The work remaining:
- run analysis with newer data
- take into account any new listings
- assess if we can make the bucket sizes

**Comment by yerdua** [comment]
Confirmed: we're sticking with the bucket size set in CR3. 
Remaining work: remove the placeholder from the activation proposal

**Comment by albertclabs** [comment]
@pedro-clabs to check if buckets are removed from the activation proposal
