### ISSUE TITLE
[WalletConnect] investigate Web3Modal

### ISSUE THREAD

**Issue by AlexBHarley** [celo-org/celo-monorepo#6903]
Output of this task is verifying whether it fits our assumptions and could integrate with our WC abstraction.

**Comment by aslawson** [comment]
@AlexBHarley to document -- should not use web3modal

**Comment by aslawson** [comment]
@AlexBHarley feels like we can close this one as well?

**Comment by AlexBHarley** [comment]
Yup not much more to say, for the foreseeable future we won't have much to do with Web3Modal. 

CIP35 will make Celo compatible with any wallets supported by Web3Modal, so we get that out of the box.

We'll be maintaining [use-contractkit](https://github.com/celo-tools/use-contractkit) as a more developer focused alternative.
