### ISSUE TITLE
[WalletConnect] implement accept/revoke transaction screen

### ISSUE THREAD

**Issue by AlexBHarley** [celo-org/celo-monorepo#6908]
Pending a lot of design decisions but for a first pass we'll be wanting to show basic transaction data.

- show raw transactions
- show decoded transaction
- investigate showing rich transaction data
    - potentially verified by CIP8
    - potentially special cased in client side code
    - another solution

**Comment by aslawson** [comment]
Ticket capturing the "investigate rich transaction data":
https://app.zenhub.com/workspaces/cap-backlog-board-600598462807be0011921c65/issues/celo-org/celo-monorepo/7461

Though seems we can include at least core contract transaction decoding as a first ticket item.
