### ISSUE TITLE
Deploy contracts to a private testnet for cEUR (without oracles)

### ISSUE THREAD

**Issue by martinvol** [celo-org/celo-monorepo#6917]
The tesnet should be mimicking the post-contracts-release-3 state, this in fact are the migrations in this branch: https://github.com/celo-org/celo-monorepo/blob/release/celo-core-contracts/

But with some modifications:
1. Remove fee currency in `09_1_stableToken_EUR.ts`
2. Remove oracles and reports in `09_1_stableToken_EUR.ts`
3. Remove exchange spender in `10_1_exchange_EUR.ts`
4. Governance should be speeded up to allow a quick governance process. 
5. in `migrationsConfig.js` the pre-mint address should be an account that can be used (as later it should test that cant exchange cEUR for CELO before first oracle report)

**Comment by bowd** [comment]
See parent epic: https://app.zenhub.com/workspaces/platform-economics---backlog-board-600a9f7399b43a001348ae1b/issues/celo-org/celo-monorepo/6162
