### ISSUE TITLE
Deploy and pass cEUR governance proposals on private testnet for cEUR (without oracles)

### ISSUE THREAD

**Issue by martinvol** [celo-org/celo-monorepo#6918]
There should be two proposals:

1st, Oracles activation and freeze:
1. Enable oracle address (this accounts should be funded and under control so they can report)
2. Should include a long oracle expiration for cEUR and a minimum report of 1. So a dummy oracle can be enough for testing.
3. Freeze `stableTokenEUR` and `exchangeEUR`

After this proposal was passed, it should be safe to report a CELO/EUR price. 

2nd, Oracles activation and freeze:
1. Everything that was removed from the migrations not included in the 1st proposal on this issue, see #6917
2. Unfreezing `stableTokenEUR` and `exchangeEUR`

Please note that the oracles included in this proposal needs to be available to use and funded for them to be able to report.

**Comment by bowd** [comment]
See parent epic: https://app.zenhub.com/workspaces/platform-economics---backlog-board-600a9f7399b43a001348ae1b/issues/celo-org/celo-monorepo/6162
