### ISSUE TITLE
Test cEUR on a private testnet (without oracles)

### ISSUE THREAD

**Issue by martinvol** [celo-org/celo-monorepo#6919]
Testing should involve the folowing:

1. Bare minimum script to allow one report (before this report, it should be tested that cEUR is not redeemable for CELO)
2. Test exchanges and transfers of cEUR (this is blocked by contract kit changes)
3. Check that cEUR can be used as gas/fee currency
4. Check that the right amounts are minted and burned on every exchange

**Comment by bowd** [comment]
See parent epic: https://app.zenhub.com/workspaces/platform-economics---backlog-board-600a9f7399b43a001348ae1b/issues/celo-org/celo-monorepo/6162
