### ISSUE TITLE
Deploy and pass CGP for cEUR activation (staging)

### ISSUE THREAD

**Issue by martinvol** [celo-org/celo-monorepo#6922]
The purpose of this governance proposal is to activate cEUR. It assumes that oracles for CELO/EUR are deployed and operational.

The proposal should include:
- Unfreeze any contracts frozen in #6167
- Add cEUR to the reserve (reserve.addToken)
- Allow ExchangeCEUR to be a reserve exchange spender
- Update any cEUR parameters that we've learned should be different than the initial values set for CR3 deployment
- set cEUR as gas currency

**Comment by bowd** [comment]
```
oracle-CELOEUR-0 -> 0x4D169C0Ec17D3dEcB250701Aa64e966bE98a696B
oracle-CELOEUR-1 -> 0x034217fB0C08dec29a6beA99e75aAC39baf7459A
oracle-CELOEUR-2 -> 0xD20f803a1489849031725479Df27741c3326eD15
oracle-CELOEUR-3 -> 0x26412103865Be3F80152EA10E61E6294ed0e0DC9
oracle-CELOEUR-4 -> 0x7Ba21D1f769Ae9feCF58dEfB5bD08905Bd3B707B
```

**Comment by martinvol** [comment]
Already passed!
