### ISSUE TITLE
Deploy contracts for cEUR (private testnet, with oracles)

### ISSUE THREAD

**Issue by yerdua** [celo-org/celo-monorepo#6939]
The testnet should be mimicking the post-contracts-release-3 state, this in fact are the migrations in this branch: https://github.com/celo-org/celo-monorepo/blob/release/celo-core-contracts/

But with some modifications:
1. Remove fee currency in 09_1_stableToken_EUR.ts
2. Remove oracles and reports in 09_1_stableToken_EUR.ts
3. Remove exchange spender in 10_1_exchange_EUR.ts
4. Governance should be speeded up to allow a quick governance process.
5. in migrationsConfig.js the pre-mint address should be an account that can be used (as later it should test that cant exchange cEUR for CELO before first oracle report)

**Comment by asaj** [comment]
Closing as this will be done as part of CR3 testing
