### ISSUE TITLE
Deploy CGP for cEUR activation on Baklava

### ISSUE THREAD

**Issue by yerdua** [celo-org/celo-monorepo#6940]
The purpose of this governance proposal is to activate cEUR. It assumes that oracles for CELO/EUR are deployed and operational.

The proposal should include:

Unfreeze any contracts frozen in oracle activation CGP
Add cEUR to the reserve (reserve.addToken)
Allow ExchangeCEUR to be a reserve exchange spender
Update any cEUR parameters that we've learned should be different than the initial values set for CR3 deployment
set cEUR as gas currency

**Comment by martinvol** [comment]
Deployed and env test passed:
```
λ › yarn baklava-test --verbose
yarn run v1.17.3
$ CELO_ENV=baklava CELO_PROVIDER=http://localhost:8545 jest --runInBand --verbose
PASS  src/monorepoRun.ts (56.74 s)
  Run tests in context of monorepo
    Transfer Test
      ✓ transfer cEUR (13637 ms)
    Exchange Test
      ✓ exchange cEUR for CELO (29782 ms)
Test Suites: 1 passed, 1 total
Tests:       2 passed, 2 total
Snapshots:   0 total
Time:        56.795 s
Ran all test suites.
```
