### ISSUE TITLE
Changing unlockingPeriod doesn't apply to existing or relocked pending withdrawals 

### ISSUE THREAD

**Issue by yorhodes** [celo-org/celo-monorepo#6943]
### Expected Behavior

Relocked and existing pending withdrawals are effected by `unlockingPeriod` changes, or inverse behavior should be explicitly acknowledged and documented.

### Current Behavior

`unlockingPeriod` only applies to new pending withdrawals

**Comment by m-chrzan** [comment]
Is that really the case? The timestamp stored for pending withdrawals is the time it becomes available, i.e. it statically depends on time when `unlock` was called and the `unlockingPeriod` at that moment. Even if `unlockingPeriod` changes, the timestamp doesn't.
