### ISSUE TITLE
Governance allows for empty proposals

### ISSUE THREAD

**Issue by yorhodes** [celo-org/celo-monorepo#6946]
### Expected Behavior

- Proposals with no transactions revert on `propose`

### Current Behavior

- Proposals with no transactions can live through the governance lifecycle

**Comment by timmoreton** [comment]
I seem to remember wanting "indicative votes" to be able to done through governance -- Cc @asaj  ?

**Comment by m-chrzan** [comment]
These are useful for "offchain policy" changes (e.g. recent proposals about the Reserve mandate).
