### ISSUE TITLE
Governance vote accepts non-zero values which function as none instead of abstain

### ISSUE THREAD

**Issue by yorhodes** [celo-org/celo-monorepo#6948]
### Expected Behavior

Either `value>Abstain` should imply `value=Abstain` or revert

### Current Behavior

Governance `vote` reverts on `uint8 value=None` but not `uint8 value>Abstain`

**Comment by deepakhb2** [comment]
@yorhodes How value > Abstain work? It should be either == or != comparison right?
Also, this checking should be added after after this line in [Governance.sol](https://github.com/celo-org/celo-monorepo/blob/master/packages/protocol/contracts/governance/Governance.sol#L632) file right?

**Comment by nambrot** [comment]
I think @yorhodes 's point is that the input to the function is really just a vote (since the enum bounds isn't getting checked at run time), so a value of greater than Abstain is 1) not defined but also 2) does not revert. I think the check location makes sense

**Comment by yorhodes** [comment]
yeah I think value>Abstain should revert on that line too

**Comment by yorhodes** [comment]
compiler enforces this already, thanks @deepakhb2 !
