### ISSUE TITLE
 [ ContractKit] Investigate Changes needed to support optional 3 extra transaction fields

### ISSUE THREAD

**Issue by aslawson** [celo-org/celo-monorepo#6949]
Investigate developer experience.
Probably most work is done on the blockchain side to handle optional 3 tx fields
(?) CAP - fees: set default currency. affects ContractKit.

Deliverable:
* Touch points to tools so they don't break

**Comment by barbaraliau** [comment]
ToDO: Break up into separate issues

**Comment by aslawson** [comment]
Eskportiso tracking here
https://app.zenhub.com/workspaces/cap-backlog-board-600598462807be0011921c65/issues/celo-org/celo-monorepo/7078

Kliento investigated by @oneeman

**Comment by aslawson** [comment]
Separate issues:
CLI: https://app.zenhub.com/workspaces/devx-backlog-board-6009f3d1a7a39b001018f159/issues/celo-org/celo-monorepo/7079

Rosetta: https://app.zenhub.com/workspaces/devx-backlog-board-6009f3d1a7a39b001018f159/issues/celo-org/rosetta/141
