### ISSUE TITLE
WalletConnect Valora Designs V0

### ISSUE THREAD

**Issue by aslawson** [celo-org/celo-monorepo#6971]
Likely can reuse the QR scanner and much of the designs for transaction confirmation with dapp/valora integrations

https://www.notion.so/clabsco/Valora-x-WalletConnect-Design-7f8b2357257a4062af772dfd899a98c9

**Comment by aslawson** [comment]
@coreycelo hopefully I'm using the P&D board correctly 😬
can you add links to the designs you had?

**Comment by coreycelo** [comment]
Current Dapp Integration screens:
[Figma](https://www.figma.com/file/zt7aTQ5wuXycIwxq5oAmF9/Wallet-Refresh?node-id=7424%3A468)

A few todos to get to based on last week's convo.

**Comment by AlexBHarley** [comment]
@coreycelo can I get access to that file?
