### ISSUE TITLE
New Notification copy on CELO Transfers + New Home Feed Education Card

### ISSUE THREAD

**Issue by nityas** [celo-org/celo-monorepo#6978]
### Expected Behavior

New push notification copy should read

Title: CELO deposit received
Body: “You just received __ CELO! Tap to learn how you can earn, save, and spend in Valora”
Redirect to: CELO tab

New home card notification card should read:

Title: With Valora you can save, spend or send to your friends.
CTA1: Learn More
CTA2: Dismiss
Redirect to: firebase-controlled text screen(or webview)

learn more page copy:
https://docs.google.com/document/d/1GYSiFKtwMguQxZtoZvOgJfdI7XyX--gFwdm5pmSY4T8/edit?ts=601b43e1#heading=h.v1xq2l9tqekl (still to be fully finalized)

### Current Behavior

Doesn't exist :)

**Comment by gnardini** [comment]
Open PR to detect the language automatically on valoraapp.com:
https://github.com/clabs-co/valora-website/pull/49

**Comment by gnardini** [comment]
The PR was merged and is live, everything on this issue should be done now :)
