### ISSUE TITLE
Setup per service routing keys

### ISSUE THREAD

**Issue by alecps** [celo-org/celo-monorepo#7014]
Switch on-call alerts over to service specific routing keys to handle situations where a given service is under maintenance or needs a different person on call

**Comment by nambrot** [comment]
@alecps Where would you put this in terms of priority?

**Comment by aslawson** [comment]
@alecps we seem to be in a good spot now, do you think this is still a priority?

**Comment by alecps** [comment]
@aslawson @nambrot  I think p3 makes sense for now. I'll bring this up for discussion during the ops sync
