### ISSUE TITLE
Tune ODIS alerts and dashboards

### ISSUE THREAD

**Issue by alecps** [celo-org/celo-monorepo#7015]
ODIS operations are still in need of continued adjustment as we respond to alerts and discover imperfections in our metrics/dashboards. This ticket should allocate some dedicated time to address these issues when they arise. Specific responsibilities include reviewing aggregation settings on alerts/dashboards, reviewing alert thresholds, adding dashboard documentation to runbook, and improving the description blurbs provided in alerts.

**Comment by nambrot** [comment]
@aslawson Moved this pretty high up in this milestone, hope you dont mind

**Comment by codyborn** [comment]
Changes
- Fixed latency reporting issue on two charts (previously rates were >200M for some reason) 
  1. [Latency by API](https://console.cloud.google.com/monitoring/metrics-explorer?pageState=%7B%22xyChart%22:%7B%22constantLines%22:%5B%5D,%22dataSets%22:%5B%7B%22plotType%22:%22LINE%22,%22timeSeriesFilter%22:%7B%22aggregations%22:%5B%7B%22alignmentPeriod%22:%2260s%22,%22crossSeriesReducer%22:%22REDUCE_MEAN%22,%22groupByFields%22:%5B%22resource.label.%5C%22function_name%5C%22%22%5D,%22perSeriesAligner%22:%22ALIGN_PERCENTILE_99%22%7D%5D,%22apiSource%22:%22DEFAULT_CLOUD%22,%22crossSeriesReducer%22:%22REDUCE_MEAN%22,%22filter%22:%22metric.type%3D%5C%22cloudfunctions.googleapis.com%2Ffunction%2Fexecution_times%5C%22%20resource.type%3D%5C%22cloud_function%5C%22%20resource.label.%5C%22function_name%5C%22!%3D%5C%22odisMonitorScheduleFunction%5C%22%20resource.label.%5C%22function_name%5C%22!%3D%5C%22status%5C%22%22,%22groupByFields%22:%5B%22resource.label.%5C%22function_name%5C%22%22%5D,%22minAlignmentPeriod%22:%2260s%22,%22perSeriesAligner%22:%22ALIGN_PERCENTILE_99%22,%22unitOverride%22:%22ns%22%7D%7D%5D,%22options%22:%7B%22mode%22:%22COLOR%22%7D,%22timeshiftDuration%22:%220s%22,%22y1Axis%22:%7B%22label%22:%22y1Axis%22,%22scale%22:%22LINEAR%22%7D%7D%7D&project=celo-pgpnp-mainnet) 
  2. [Latency by Signer](https://console.cloud.google.com/monitoring/metrics-explorer?pageState=%7B%22xyChart%22:%7B%22dataSets%22:%5B%7B%22timeSeriesFilter%22:%7B%22filter%22:%22metric.type%3D%5C%22logging.googleapis.com%2Fuser%2Fodis-signer-latency%5C%22%20resource.type%3D%5C%22cloud_function%5C%22%20metric.label.%5C%22signer%5C%22!%3D%5C%22handleGetBlindedMessageSig%20latency%5C%22%22,%22minAlignmentPeriod%22:%2260s%22,%22aggregations%22:%5B%7B%22perSeriesAligner%22:%22ALIGN_DELTA%22,%22crossSeriesReducer%22:%22REDUCE_MEAN%22,%22groupByFields%22:%5B%22metric.label.%5C%22signer%5C%22%22%5D%7D,%7B%22crossSeriesReducer%22:%22REDUCE_NONE%22%7D%5D%7D,%22targetAxis%22:%22Y1%22,%22plotType%22:%22LINE%22%7D%5D,%22options%22:%7B%22mode%22:%22COLOR%22%7D,%22constantLines%22:%5B%5D,%22timeshiftDuration%22:%220s%22,%22y1Axis%22:%7B%22label%22:%22y1Axis%22,%22scale%22:%22LINEAR%22%7D%7D,%22isAutoRefresh%22:true,%22timeSelection%22:%7B%22timeRange%22:%221m%22%7D%7D&project=celo-pgpnp-mainnet)
- Separate Latency errors from other errors
- Increase alerting severity on [non-latency errors](https://console.cloud.google.com/monitoring/alerting/policies/12395213547291590031?project=celo-pgpnp-mainnet)
- Standardized alerting titles/messages with links
- Added histograms for query count + quota
