### ISSUE TITLE
Run attestation-bot on Mainnet

### ISSUE THREAD

**Issue by nambrot** [celo-org/celo-monorepo#7020]
### Expected Behavior

Artificial attestations by cLabs on Mainnet to detect issues

### Current Behavior

No artificial attestations by cLabs on Mainnet

**Comment by nambrot** [comment]
@aslawson @codyborn Curious to get your take on this one, this seems like an easy win

**Comment by codyborn** [comment]
This can also be used to detect gaming of AS metrics since we'll have a good ground truth from cLab's side. Only concern is cost (.15 cUSD per run). Do you know how frequently this runs?

**Comment by codyborn** [comment]
Conflicts with #7083

**Comment by aslawson** [comment]
what do we gain from this? mainnet has real traffic and will likely grow with Valora

**Comment by nambrot** [comment]
We would get a baseline of whether attestation services are really down with higher confidence. I.e. if the attestation bot is not completing an attestation for a particular issuer, we have quite high confidence that they are "down" and that we should reach out to them. It also gives us a baseline to compare Valora as a client

@codyborn frequency is configurable. Given cLabs' infrastructure expenditures, I'm personally not too concerned about costs and this can also be funded with a community fund slice too.

**Comment by alecps** [comment]
Closing this in favor of ASv2. It is now also quite out of date
