### ISSUE TITLE
“Payment Received” same push notification displayed twice even user B sent money for only a single time.

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#7021]
**Frequency:** 100%
**Repro on build version:** Android Internal Build V1.10.0(1004294335), Test Flight Build V1.10.0(45)
**Does not repro version** Android Internal Build V1.9.2(1004294334), Test Flight Build V1.9.2(44)
**Repro on devices:** Samsung Galaxy A5(7.0), iPhone XR(14.2),  iPhone 6+ (12.4.5)
**Testing Account:**    For iOS: [(680) 333 1978](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit#gid=0&range=B9)
			  For Android: [(715) 575 8688](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit#gid=0&range=B12)
**Pre-condition:** User B’s phone number should be verified.
  **Repro Steps:**
1. Launch the application & login with a test account.
2. Go to the Home screen & tap on the “Send” button.
3. Search for verified user B’s phone number & send amount.
4. Now open the notification tray of user B.
5. Observed that, 
**Current Behavior:**  Payment Received push notification displayed twice.
**Expected Behavior:**  Notification should be displayed only for one time.
**Investigation:** Also we have observed the same issue when user  receive money by scanning QR code.
**Impact:** User might be confused that he received money from another user.
**Attachment:**  [PushNotificationShownTwice.mp4](https://drive.google.com/file/d/1Kx9PvhEigSn9tSC2yhrTqzq5YQGQgnBI/view?usp=sharing)

**Comment by ValoraQA** [comment]
Hi @jeanregisser & @isabellewei We have verified this issue on latest Play store build V1.10.1 & App store build 1.10.1 observe that issue is still repro.

- “Payment Received” same push notification displayed twice even user B sent money for only a single time".

**Comment by ValoraQA** [comment]
Hi @jeanregisser & @isabellewei We have verified this issue using latest Android Internal Build V1.11.1(1004294338) & Test Flight Build V1.11.1(48) & observed that issue is fixed now. User able to see only one push notification after receiving money.
**Verified on Devices:** Samsung Galaxy A5(7.0), iPhone XR(14.2), iPhone 6+ (12.4.5)

**Comment by ValoraQA** [comment]
Hey  @jeanregisser & @isabellewei We have verified this issue using latest Android Internal Build V1.12.1(1004294341) & Test Flight Build V1.12.1(50) & observed following:

- In latest build user get twice notification even when User A sent money for single time. Hence, reopening this issue.
**Verified on Devices:** Samsung Galaxy A5(7.0), iPhone SE(13.4.1)
**Attachment:** [PushNotificationStillShownTwice.png](https://drive.google.com/file/d/1BJXKIeDUKm0Wq5e2TVAkIl6Pz-tm3ShT/view?usp=sharing)

**Comment by gnardini** [comment]
This should be fixed now, thanks for the error report!

**Comment by ValoraQA** [comment]
Hi @gnardini We have verified this issue on latest builds Android internal build V1.15.1 & Testflight build V1.15.1(64) and found issue is fixed.
Device: iPhone 6+ (12.4.5), Vivo v11 pro (10)
