### ISSUE TITLE
Attestation Service won't start until Full Node is synced

### ISSUE THREAD

**Issue by codyborn** [celo-org/celo-monorepo#7050]
### Expected Behavior

If the AS full-node isn't synced, the AS should start and continue to wait until the full-node is ready. Once it's ready, it should complete the startup process automatically.

### Current Behavior

If the AS full-node isn't synced, the AS fails to start altogether.

**Comment by eelanagaraj** [comment]
with the upcoming 1.4.0 release, this should be resolved (unless the service cannot connect to the light node + all backup nodes) cc @codyborn , feel free to reopen if that doesn't cover this!
