### ISSUE TITLE
Expose GET & POST endpoints for Nexmo callback

### ISSUE THREAD

**Issue by codyborn** [celo-org/celo-monorepo#7055]
Nexmo callback defaults to GET (can be updated in the portal); however, we only enable POST. As a result, we don't get/log the callback status for Nexmo calls.

Expose both endpoints for Nexmo callback.
https://github.com/celo-org/celo-monorepo/blob/d07b9267115255d03174a218d31dee8d29b473b1/packages/attestation-service/src/index.ts#L84

**Comment by codyborn** [comment]
Not high priority. I think Nexmo is our least preferred provider.

**Comment by alecps** [comment]
@eelanagaraj is this safe to de-prioritize?
