### ISSUE TITLE
Scope implementation details for an identity proxy contract to enable identity-based calls

### ISSUE THREAD

**Issue by nategraf** [celo-org/celo-monorepo#7057]
In order to support the use of phone numbers as a factor in smart contract recovery, a contract will need to be written to act as a proxy for any address considered "verified" for an identifier (i.e. phone number). This will allow using the address of the identity proxy for identity-based authentication.

At the core of this identity proxy would be a predicate that determines whether a given address is "verified" to be the owner of the a given identifier. Verification should consider the number of completed attestations, similarly to the [Escrow contract](https://github.com/celo-org/celo-monorepo/blob/0a42abd821fe165182db57d19cd989acf9cce9d3/packages/protocol/contracts/identity/Escrow.sol#L164-L174), but also consider the number of failed verification attempts from the same address, and the number of other addresses with attestations on that identifier.

Note that the primary application for this proxy today will be phone number based identity, but it would be useful for this proxy to be forwards-compatible with other forms of attested identity.

**Comment by nambrot** [comment]
@nategraf Would you mind more specifically specifying the predicate for your specific circumstance?

@aslawson I wonder if this fits well with #5671, as this is pretty much just a generalization

cc @yorhodes @codyborn

**Comment by aslawson** [comment]
my understanding is that account recover needs an onchain contract to perform the logic of whether an account show be considered verified. @nategraf can you describe why it is needed and more details of the predicate eg:
- we can set the fraction of complete attempts to the same value we are using in the heuristic for valora now, but it was arbitrarily selected...by me
- "number of other addresses with attestations on that identifier"-- what are we looking for here?

@nambrot does seem related to #5671. I think #5671 could adopt this later.

**Comment by aslawson** [comment]
Architecture - https://www.notion.so/clabsco/Smart-Contracts-dc7a569130dd49679c39e45cbab6b46f

3 different recovery routes with identify proxy being one:
the idea is that on creation, this identify proxy is part of the guardian multisig. if a user lost access to their account, they would create a new MTW with the same phone number verified to that. through the NEW MTW, they would then call the OLD identify proxy which will check that the NEW MTW is indeed verified to the same identifier. If this is true, then it can call approve `recoverWallet` action via the guardian multisig

**Comment by nategraf** [comment]
## Requirements

In the proposed architecture, the Identity Proxy is used to effectively allow use of an address in authorization as a proxy for an identity, defined as the verified owner of an attestation identifier. It must:
* Define criteria for whether of not a given address is the "verified owner" of an attestation identifier.
* Act as an honest proxy for a given identity with respect to the contract that authorizes it:
  * In the case of one-proxy-per-identity, this is trivially true if only verified owners of that identity can use it to make outbound calls.
  * In the case of a global Identity proxy, it must be the case that a given contract receives a call from the Identity Proxy if and only if the initiator was the verified owner of the specific identity it authorized. (e.g. If a MultiSig specifies the global Identity Proxy contract as a signer to proxy for identity `0xdeadbeef`, the verified owner of `0x0badd00d`, or for that matter any other party, should not be able to initiate a call to the MultiSig to sign a transaction)
* Must work as a signer in existing contracts, such as the MultiSig contract, or MetaTransactionWallet.  (e.g. it may require transactions from the authorizing party, but it must not rely on any functions existing on the authorizing contract)
* Must support the issuing a `recoverWallet` transaction against a MTW, through a MultiSig, without prior knowledge of the `newSigner` address argument. (Ideally, it would simply support arbitrary transactions that meat authorization criteria)

## Verification heuristic

Identity in the Celo protocol is based on attestations, and as such does not have concrete definitions of "verified" at the core protocol layer. Defining this is up to the application in question based on the security and usability tradeoff appropriate.

In the case of account recovery, the heuristic needs to be compatible with Valora such that an account with three successful attestations and a small number of failures (e.g. 0, or 1 or 2 caused by SMS delivery issues) against a given identifier will be able to pass verification.

### Attacks on the verification heuristic

Checking only that a fixed number of completed attestations is not sufficient.  As an example, if three attestations are required to be considered verified, any three malicious attesters (i.e. validator) can obtain a verified account. One way to do this is to request `n` attestations, where `n` is the total number of registered attesters, which guarantees exactly one attestation will be assigned to each attester. Each attestation assigned to a malicious node can be completed without communication to the true account holder. Extending this attack, any one attester can obtain a verified account by running three rounds of the attack. (Note that this attack costs at most $15 and 25 seconds to execute)

Adding the requirement that a given account have a certain ratio of complete to incomplete attestations may not be enough because the an attacker an attempt to verify any number of accounts with a number of requests such that the ratio of those that will fail may be under the requirement (e.g. requesting 10 attestations and hoping 3 will fall on the 5 malicious nodes). (I haven't yet gotten the math worked out on this one 😅 )

**Comment by nambrot** [comment]
First attempt at a spec:

General interface for an AttestationCallProxy

```
interface AttestationCallProxy {
  function registerIdentifier() // saves in storage identifier => msg.sender
  function revokeIdentifier()  // revokes identifier
  function callForIdentifier(bytes32 identifier, address destination, uint256 value, bytes calldata data)
}
```

First instance:
`AttestationCallProxyV1`

Contract is not upgradable, and thus no owner neccessary

Invariants that should be checked in V1:
- [ ] Has the `destination` called `registerIdentifier` for `identifier` before
- [ ] Minimum number of completions > 3
- [ ] Completion percentage Y > 50%
- [ ] Other accounts on the identifier do not have have a higher number of completed attestations than msg.sender

Usage:
- The MultiSig in question would make a `registerIdentifier` transaction to the proxy with identifier `I`
- The MultiSig would then add the address of the proxy as a signer on the multisig
- The proxy would let `callForIdentifier` succeed for accounts that pass the invariants

Questions:
- What to do in the case where the account that is being recovered is the target identifier in question? 
- By extension, this will mean that another account will have more attestations? Also which key/account is getting the attestations? Will it be the new wallet address? 
- I'm not sure that at the contract level we support wallet addresses being registered accounts on `Accounts.sol` right now. Would it just be another MTW? If so, does the old one still become the canonical one?
- Ideally, we'd increase the requirement for attestations for these kind of situations, but that would mean that at the client/komenci level, we'd need to support a higher level of attestations. 
- Once the recovery is complete, what to do with the "new" MTW? Just revoke? Modify transfer to allow attestations to be merged? I guess this in general raises an interesting question whether one should be allowed to "retry" an attestation?

Outstanding to spec:
- [x] How does an account specify the identifier => proxy mapping? CIP10 maybe? A global directory seems preferential to deploying a specific contracts/factorying it? Just store on the proxy itself?
- [x] Should it be proxied to allow for implementation upgrades?
  - I tend towards no, consumers could always update themselves to a different proxy?
- [x] Who should own the contract, cLabs or governance?
- [x] How is the contract "discovered"?

**Comment by nategraf** [comment]
I have a hard time imagining how this interface would be used exactly or if it's complete. One major question I've always run into when thinking this though is: Because the MultiSig will simply encode the address of the proxy, we will need to restrict to what addresses a given identifier can call, otherwise user A on the proxy could call the MultiSig for user B. I don't see support for this clearly in this interface.

## Cost analysis for attacks on verification heuristic

I mentioned above that there is an attack where an adversary with control over a small number of  attesters (i.e. validators) can create a large number of accounts and attempt to verify each of them by requesting a small number of attestations and hoping the request are assigned to the corrupted attesters.

In this attack, consider any single account. Given `n` total attesters, `f` of whom are compromised, the adversary will request `a` attestations in the hope that at least `r` of them are assigned to the compromised nodes. (Those that are will succeed, the rest of the requests will fail). Assuming that  a success ratio of 50% is imposed. In  this case, the attacker will request no more than `2r` attestations on any given account. (They could request more, but it would raise the minimum number that need to succeed and would overall reduce their chances of success.)

Assuming the adversary requests all attestations in a single batch, such that selecting issuers is done via selection without replacement, the following equation describes the chance that at least `r` of the `a` requests will be assigned to a compromised validator. Considering 6 requests, 3 of which must be assigned to 5 faulty validators out of 90, the chance of success on each attempt is roughly 0.162%. An attacker would need to create roughly 425 accounts to have a 50% at success. Success must be worth around $185 for the first attempt to be economically rational under these conditions.

![equation 1](https://user-images.githubusercontent.com/5684286/117855965-e46d8a80-b23f-11eb-93f9-01f397195401.png)

```python
lambda a, r, f, n: sum(comb(f, i) * comb(n - f, a - i) / comb(n, a) for i in range(r, a+1))
```

A slightly better approach is to request attestations one at a time, which allows selection of issuers by sampling with replacement.  Considering the same 6 requests, 3 of which must be assigned to 5 faulty validators out of 90, the chance of success on each attempt is roughly 0.302%. An attacker would need to create roughly 225 accounts to have a 50% at success. Success must be worth around $100 for the first attempt to economically rational under these conditions.

![equation 2](http://www.sciweavers.org/tex2img.php?eq=%5Csum_%7Bi%3Dr%7D%5Ea%7Ba%20%5Cchoose%20i%7D%5Cleft%28%5Cfrac%7Bf%7D%7Bn%7D%5Cright%29%5Ei%5Cleft%281-%5Cfrac%7Bf%7D%7Bn%7D%5Cright%29%5E%7Ba-i%7D&bc=White&fc=Black&im=jpg&fs=12&ff=arev&edit=0[/img])

```python
lambda a, r, f, n: sum(((f / n)**i) * (((n - f) / n)**(a - i)) * comb(a, i) for i in range(r, a+1))
```

Based on this analysis, I feel relatively comfortable using 3 completed attestations and a 50% success rate on a given account to guard an account as one of 2 or more factors. (It's probably less costly to execute a SIM-swapping attack than corrupting and coordinating validators and executing the attack on-chain.) We should work on monitoring that could detect this kind of attack though. In this case I do not think we should condition that `msg.sender` be the account with attestations for an identifier.

An alternative to using this per-account success rate would be to use a _global_ success rate for an identifier. This would enable a much higher margin of security, even with much lower completion rates (e.g. 5%). The primary downside is that the account would then be vulnerable to denial-of-service by anyone who simply requests a bunch of attestations against the identifier they wish to attack..

A slightly more advanced version of this heuristic would use a sort of time-window completion rate. For example, in order to assess whether an account is verified consider the completion on that account _and_ any other accounts that requested attestations against the same identifier in the 24 hours preceding the most recent completed attestation. This effectively rate limit the speed at which an attacker can attempt to take over an account while also making DoS attacks require a persistent adversary rather than a one-time cost. Other extensions certainly also exist and we can decide how far to explore these. 

Note: In all of this discussion it's very important that attestations cannot be merged between two account through transfers. If this ever changes, the security will need to be reconsidered, probably with a global completion rate.

## Questions

> What to do in the case where the account that is being recovered is the target identifier in question?

If I understand the question correctly, that is actually the primary flow that we expect. A user will specify their own phone number (identifier) during onboarding, and during recover will verify their phone number against a new account (MTW). We are not currently considering phone-number based social recovery, although this same contract could certainly facilitate that!

> By extension, this will mean that another account will have more attestations?

I don't think it matters if another account has more. It's ok to have two verified accounts on the same identifier, and we expect this will happen. (Both would be considered "canonical", in reference to the next question)

> Ideally, we'd increase the requirement for attestations for these kind of situations, but that would mean that at the client/komenci level, we'd need to support a higher level of attestations.

We should certainly consider it. We can discuss what security benefit that would have (hopefully the equations above should provide some guidance) . My currently opinion is that by default we should use the "standard" 3 attestations. We may consider raising the threshold if the global failure rate on an identifier is too low (i.e. the identifier is being attacked) but I would consider other options first.

> Once the recovery is complete, what to do with the "new" MTW? Just revoke? Modify transfer to allow attestations to be merged?

My first reaction would have been to allow merging attestations, but after some more thought, that would make the attack mentioned above far more viable. I think we should simply revoke the attestations on the MTW created for recovery.

**Comment by nambrot** [comment]
> I have a hard time imagining how this interface would be used exactly or if it's complete. One major question I've always run into when thinking this though is: Because the MultiSig will simply encode the address of the proxy, we will need to restrict to what addresses a given identifier can call, otherwise user A on the proxy could call the MultiSig for user B. I don't see support for this clearly in this interface.

Very fair, I amended the spec to be more clear in the usage of the proxy. I.e. the proxy will be storing the mapping of identifier to addresses. There is a small question as to whether CIP10 could facilitate this as well.

Great analysis of attack costs, it does highlight to me that there is no straightforward answer for assessing the canonical owner of an identifier, and it is dependent on so many factors. Not sure how feasible in the short-term, but I think we need more sophisticated off-chain analysis (as well as access to such analysis by other parties such as wallet devs), to increase our confidence in the security of the attestations protocol. I think age of attestations, relative trustworthiness of validators, use of sms providers etc. all should go into a heuristic. (cc @codyborn @aslawson )

Coming back to the issue at hand, we are of course much more limited at what we can express on-chain. That being said, it seems to me that the heuristic as specified works for you?

**Comment by nategraf** [comment]
Yes, I think the heuristic of at least 3 completed attestations and a completion rate of 50% will work. I would also consider a limit on the total number of accounts that have requested attestations on an identifier, but would lean against implementing it due to DoS concerns.

In parallel to this work being rolled out, we should invest in monitoring that can identify attack patterns on-chain such that if it ever where to occur the user in question can be notified, and we could potentially use Governance to slash any malicious validators. We can continue that work elsewhere.

**Comment by codyborn** [comment]
Thanks for the thorough analysis @nategraf! Using your sample w/ replacement formula and holding `a`,` r`, and `f` constant at the values in your example, I've plotted out the likelihood of success vs the number of total attestation services elected (`n`):
![image](https://user-images.githubusercontent.com/11261382/108787885-9348d700-752b-11eb-8be3-1ed398bd74c8.png)
**Note the log-scale on the y-axis**

This helps us figure out what the absolute minimum number of attestation services we should have elected to consider results to be valid. Any attestation service count less than 60 (.95%) seems too risky.

Regarding monitoring, it may be difficult to detect this type of abuse in the case that the attacker only attempts once per phone number, and only completes the 3 if they get at least 3 of their nodes selected. One idea to help with detection could be to add a link to the SMS message to allow a user to flag that they didn't initiate the request. Something like "Didn't initiate this request? Go here to protect your account". Though adding links might lower the likelihood of SMS delivery. @aslawson might know.

**Comment by nambrot** [comment]
I would close this ticket to start implementation in #7164, any concerns?
