### ISSUE TITLE
Alerting When Attestation Service Misses X attestations in a Row

### ISSUE THREAD

**Issue by aslawson** [celo-org/celo-monorepo#7061]
Discord Bot and/or internal oncall alerts when an attestation service has been [10] attestations in a row.

This can help catch issues where their service may be set up properly but they have issues with their provider accounts (eg no balance).

**Comment by codyborn** [comment]
Created some slack bot alerts using Metabase:

1. Issuers that have failed their past 10 requests (checked hourly)
https://metabase.celo-networks-dev.org/question/332/notebook 
2. Recent errors that indicate an issuer is having billing failures from Twilio or Nexmo (checked daily)
https://metabase.celo-networks-dev.org/question/331/notebook
3. Issuers with non-compliant endpoints (checked daily)
https://metabase.celo-networks-dev.org/question/333/notebook

These three alerts will post a message to #eng-alerts-cap-informational.

**Comment by aslawson** [comment]
@codyborn is there an easy way to also post these first two in the discord node-operators #mainnet-alerts? but maybe having them both only daily?

**Comment by codyborn** [comment]
@aslawson Not directly from Metabase, but it looks like we can "chain" them together:
https://discourse.metabase.com/t/discord-alert/4492

**Comment by codyborn** [comment]
We'll need a Discord server admin to help set this up.

**Comment by aslawson** [comment]
ok -- probably lower priority now that we have internal alerts. but i'll keep it in the backlog for future.

**Comment by codyborn** [comment]
Sounds good, thanks!

**Comment by alecps** [comment]
@eelanagaraj making a note here for us to discuss this

**Comment by eelanagaraj** [comment]
@alecps 👍  I think this can also be bundled into the "self-help" service to some extent -- i.e. some way for validators to get alerts themselves. (and both should be deprioritized vs. ASv2)
