### ISSUE TITLE
Automatically select new issuers upon reveal failure

### ISSUE THREAD

**Issue by codyborn** [celo-org/celo-monorepo#7062]
### Expected Behavior

If an issuer is down and the reveal step fails, Valora should auto-retry with a new issuer until the Komenci limit is reached.

### Current Behavior

When an issuer is returning an error, the user must reinitiate the flow in order to select new issuers.
https://github.com/celo-org/celo-monorepo/blob/master/packages/mobile/src/identity/feelessVerification.ts#L331

**Comment by nambrot** [comment]
What does `down` mean in this case?

**Comment by codyborn** [comment]
Down would be unrecoverable errors (SMS provider billing quota outage) or once a certain threshold of retryable attempts have been reached.

**Comment by gnardini** [comment]
This was implemented on the Verification refactoring: https://app.zenhub.com/workspaces/wallet-backlog-board-60092d006a84e3001d0d5936/issues/celo-org/wallet/116
