### ISSUE TITLE
JavaScript native keystore

### ISSUE THREAD

**Issue by aslawson** [celo-org/celo-monorepo#7063]
Quick Implementation: I see this as basically a state management and persistence library that wraps the LocalWallet functionality already in ContractKit, ideally providing support for each environment we want to run it in. LocalWallet keeps the private key in memory and has support for all operations (sign, decrypt, computeSharedSecret, etc) that we're currently thinking about. In an effort to move away from Geth signing data and controlling keys we just need more people to use this LocalWallet safely.

Could also explore `KeystoreManager` - Basically an API for getting (and decrypting) the private key in a way all the consumers can implement.

Use Cases

- CLI - I see an API like celocli unlock 0x... (which prompts for password), celocli lock 0x... and all other operations (e.g. sending tx's via celocli send cUSD 10 --from 0x) would simply call into the .celocli keystore file if it exists. As Amy mentioned much nicer than including the --privateKey flag
- Valora - is able to skip touching Geth and use this keystore instead for all key. This would mean when Valora is running the light client, all it does it send signed transactions to it and read state from it. Right now when using Forno the flow is 1. Ask Geth to sign transaction 2. Get back signed transaction 3. Send to Forno.
- Attestation Service - Right now validators need to run a separate full node with their attestation signer key unlocked in order to sign the message (attestation proof). it would be a security risk to make the request directly to a validator, but if we had a local storage for the private key, they could make the request to the validator proxy (and thus eliminate the need of running an additional full node and reduced many of our downtime issues due to node problems)here the encrypted storage might be the attestation service database or even a raw file on the VM.

Thoughts on Clef:

- It doesn't have wide adoption
- Bundling a second binary into Valora (Geth is the first) might cause more size bloat.

**Comment by AlexBHarley** [comment]
Seems like the ideal scenario here is something Valora can use (ReactNative compatible), the browser can use (LocalStorage / IndexedDB compatibility) and something the CLI can use (file system access).

#### Where does Metamask store private keys?

Metamask uses a library called [LocalForage](https://github.com/localForage/localForage), that acts as a thin wrapper around LocalStorage and IndexedDB. AFAICT metamask simply stores private keys with that, encrypted with a password / pin.

**Comment by aslawson** [comment]
Added old description for posterity
* Makes CIP8 very unusable
* Getting it into CLI; don’t have to worry about browser capability, reads from file from file
* Extend wallet interface
* ~ 1d work
* Wallet channel cannot access what they need to
    * RPC with geth node with native node — some keys kept in plan text (file system store); use contract kit and hook up to this store; contract kit uses this in memory wallet (DEK)
    * Do run a geth client and some things (Signing Key) native bridge
* Would Validators like js keystore — filesystem and local store interface 
* Where does Metamask store private key?
* `.celo` file
