### ISSUE TITLE
Plan what needs to be done for cEUR contractkit support

### ISSUE THREAD

**Issue by yerdua** [celo-org/celo-monorepo#7065]
### Expected Behavior

We know what changes need to be made for contractkit support for cEUR

### Current Behavior

What is the current behavior?

**Comment by tkporter** [comment]
Updated these issues with more info:

* cEUR support for contractkit https://app.zenhub.com/workspaces/platform-economics---backlog-board-600a9f7399b43a001348ae1b/issues/celo-org/celo-monorepo/6365
* cEUR support for CLI https://app.zenhub.com/workspaces/platform-economics---backlog-board-600a9f7399b43a001348ae1b/issues/celo-org/celo-monorepo/6793
* cEUR faucet support - celotool & standalone faucet https://app.zenhub.com/workspaces/platform-economics---backlog-board-600a9f7399b43a001348ae1b/issues/celo-org/celo-monorepo/7150
* cEUR DappKit support https://app.zenhub.com/workspaces/platform-economics---sprint-board-5f89a1e34ce1b6001230771d/issues/celo-org/celo-monorepo/7151
