### ISSUE TITLE
CLI Docs should point to correct source files

### ISSUE THREAD

**Issue by mcortesi** [celo-org/celo-monorepo#707]
### Expected Behavior

Docs should point to the `ts` version

### Current Behavior

We have `cli/lib/src`, 
```
_See code: [packages/cli/lib/src/commands/account/new.js](https://github.com/celo-org/celo-monorepo/tree/master/packages/cli/lib/src/commands/account/new.js)_
```

What is the current behavior?

**Comment by yorhodes** [comment]
Currently this is generated quite hackily using [our fork](https://github.com/celo-org/dev-cli) of oclif. 

I am not entirely sure but I think using [patch-package ](https://github.com/ds300/patch-package) might be a better alternative.
