### ISSUE TITLE
Catch src import issues on pre-commit hook

### ISSUE THREAD

**Issue by bowd** [celo-org/celo-monorepo#7077]
### Expected Behavior

Sometimes the IDE can trick you and auto-import a `@celo` dependency from the `src` folder instead of the `lib` folder.
For example, in ContractKit we had this in a file:
```typescript
import { isValidAddress } from '@celo/utils/src/address'
```

Nothing in CI complains about this, but it continues to reference `src` after it's published to NPM which causes a runtime error as the `src` folder isn't published to NPM. See #7073 

This can cause sizeable disruption when it comes to the NPM publish cycle. But it's easy to catch earlier, potentially in a pre-commit hook by looking at `.ts` files for `/@celo.*src/` this regexp, or something of that nature.

### Current Behavior

Everything works until you try to use the package from NPM :(

**Comment by aslawson** [comment]
Before publishing to contractkit/cli to NPM, we should check they do not have `src` dependencies
