### ISSUE TITLE
Investigate Changes needed for Ekportisto to support optional 3 extra transaction fields

### ISSUE THREAD

**Issue by aslawson** [celo-org/celo-monorepo#7078]
Blockchain is investigating making Celo's 3 extra transaction fields optional. We should have a sense of how much work needs to be done and the touchpoints for ensuring Ekportisto doesn't break for transactions not including these fields.

**Comment by yorhodes** [comment]
Eksportisto does not index these 3 transaction fields anywhere
The only potential friction point is when [tracing internal transfers](https://github.com/celo-org/eksportisto/blob/4143d418c5d9b72bcdb819908fdc91b91cfb6c68/monitor/main.go#L241), but this work is delegated to [kliento's debug module](https://github.com/celo-org/kliento/blob/9bd2e6982f1be9ef59a6ef4118fa432f32c9cfa4/client/debug/tracer.go#L266)
