### ISSUE TITLE
[Attestation Service] Don't send SMS to voip numbers

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-monorepo#7083]
### Expected Behavior

* Attestation Service providers should expose a call to get phone number type from that service - e.g [Twilio lookup number](https://www.twilio.com/docs/lookup/api#phone-number-type-values) or return unsupported.

* New  attestation requests should use this service, if available, from a configured provider, to see if the number to send an attestation to is a VOIP number.   If no such service is available (e.g. configured provider doesn't support this), then fallback to determine type via libphonenumber (see below).

* Add a metric to record how many server-side lookup calls are made and how many numbers of each type are seen.

* Add a config option to control whether the SMS is actually blocked in the case of VOIP numbers.  Initially, we should not block, since it's unclear how broadly the lookup APIs respond with correct info across many countries and carriers.

* If so, a blocked request should return a response and status that Valora can identify. This should be surfaced to the user rather than trying new issuers.

### Current Behavior

We record the type of the number according to libphonenumber in metrics e.g.

```
attestation_requests_number_type{country="RU",type="mobile"} 1 attestation_requests_number_type{country="US",type="fixed_line_or_mobile"} 3  
```

While it is tough to currently aggregate metrics across validators, I have never seen a type of `voip`, suggesting blocking VOIP calls might have little effect on real user verifications.

**Comment by nambrot** [comment]
Lookups cost money as far as I know and as a Google Voice user myself, I find services blocking my number very frustrating. Additionally we should better understand the false-negative rate as well. What is the benefit of doing this?
