### ISSUE TITLE
Pending transaction 

### ISSUE THREAD

**Issue by aaash91** [celo-org/celo-monorepo#7086]
### Expected Behavior
Quick deposit of CELO from Coinbase to COInlist 
Please describe the behavior you are expecting

### Current Behavior

What is the current behavior?
The transaction of CELO has been pending for over 3 hours, I sent 21 CELO so this isn't a small deal,

**Comment by aslawson** [comment]
closing duplicate https://app.zenhub.com/workspaces/devx-backlog-board-6009f3d1a7a39b001018f159/issues/celo-org/celo-monorepo/7085
