### ISSUE TITLE
[cli, contractkit] releasegold:show, account:show broken when no signer set   

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-monorepo#7091]
### Expected Behavior

`celocli releasegold:show` and `celocli account:show` complete successfully and lists contract address under vote,validator,attestation signer when account not registered, or no matching signer registered.
 
[getAccountSummary](https://github.com/celo-org/celo-monorepo/blob/master/packages/sdk/contractkit/src/wrappers/Accounts.ts#L131) also now fails in these settings -- what changed?

### Current Behavior

* Hits requires on https://github.com/celo-org/celo-monorepo/blob/master/packages/protocol/contracts/common/Accounts.sol#L405
* `    Error: Your request got reverted with the following reason string: Unknown account`

**Comment by medhakothari** [comment]
I believe #7098 & #7092  both close this issue
