### ISSUE TITLE
 App get crash when user try to upload profile picture from take photo section

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#7093]
**Frequency:** 100%
**Repro on build version:** Test Flight Build V1.10.1(46)
**Does not Repro on build version:** Android Internal Build V1.10.1(1004294336
**Repro on build version:** iPhone 6+ (12.4.5)
**Does not Repro on devices:** iPhone XR(14.2), Samsung Galaxy A5(7.0), iPhone SE 2(14.2), iPhone XS max (13.3.1), iPhone 6(12.4)
  **Repro Steps:**

1. Launch the application & go to Create Account screen.
2. Tap on Add photo icon.
3. Select Take photo section
4. Tap on photo button
5. Observed ,

**Current Behavior:** App get crash when try to upload profile picture.
**Expected Behavior:**  User should able to upload profile picture through Take photo option.
**Observation:** App get crash when user try to upload profile picture from settings> edit profile
**Impact:** User get blocked to upload profile picture .
**Attachment:**  [CrashonAddphoto.mp4](https://drive.google.com/file/d/1boWnMwLqpy9Y8Pu8DDxPOcUaWlkH4DyW/view?usp=sharing)
[Crashlogs](https://drive.google.com/file/d/1uZW1KkAI43a-MGvasDphEz9beFKA-Bg1/view?usp=sharing)

**Comment by ValoraQA** [comment]
Hi @jeanregisser & @isabellewei We have verified this issue on latest  app store build V1.10.1 and observe that issue is still repro.
- App get crash user try to upload profile picture from take photo section
[LogsonTakePhoto](https://drive.google.com/file/d/1iXtFrPKwTq6ICJt3S644hTTmpKKyURqG/view?usp=sharing)

**Comment by ValoraQA** [comment]
Hi @jeanregisser & @isabellewei We have verified this issue on Testflight build V1.11.1(48) and observe that issue is fixed so, we are closing this ticket.
**Device:-** iPhone 6+ (12.4.5)
