### ISSUE TITLE
Scope Required Work to Support cEUR in Faucet

### ISSUE THREAD

**Issue by eelanagaraj** [celo-org/celo-monorepo#7100]
Should consider doing so in a generalized way that would set us up to support additional future stable tokens.

Related to issue: #6790

Faucet
- celotool changes
- web tool -> update text ==> "Each request adds 10 cUSD, 10 cEUR, and 5 CELO."
- firebase -> what does the request currently look like? changes necessary here to also add the cEUR transfer?
- initial balance for `0x22579ca45ee22e2e16ddf72d955d6cf4c767b0ef`
- alerting for web faucet balance (balance of `0x22579ca45ee22e2e16ddf72d955d6cf4c767b0ef`)

**Comment by eelanagaraj** [comment]
Here are the smaller sub-tasks that I think will need to be necessary for adding cEUR to the faucet (happy to move this discussion to slack as well, but wanted this documented on this ticket as well!):

_celotool changes (use cases: large transfers of cUSD/CELO/cEUR on alfajores)_
- [coordinate with protocol economics] on how much cEUR to initially provide validator-0 @martinvol 
- modify the celotool script to allow for cEUR transfers and test this out (should be straightforward to add the additional arg)

_web faucet changes (use cases: devs using web interface to request 5 CELO/10 cUSD/10? cEUR)_
- [web team] -> update the text on the faucet (very tiny change)
- [coordinate with protocol economics] initialize web faucet address (`0x22579ca45ee22e2e16ddf72d955d6cf4c767b0ef`) with a large amount of cEUR @martinvol 
- redeploy `faucetRequestProcessor` firebase function (adding transfer command for cEUR should be mostly straightforward (steps enumerated below), testing may be slightly trickier. It should be possible to test this out with the firebase emulator, but double check this)
1. modify `buildHandleFaucet`
2. extend `CeloAdapter`; (possible option to modify `transferDollars` --> `transferStable`? May be overkill/not actually make future additions easier, already quite easy)
3. test `faucetRequestProcessor` in firebase emulator if possible, or by deploying to staging? (second would be more complicated)
4. deploy `faucetRequestProcessor` under a new name on firebase? --> can test, coordinate with web for testing this on staging once cEUR is on alfajores
5. either redeploy previous function (same name) or coordinate with web to use newly deployed function once website mods are ok and faucet should start allowing for cEUR fauceting

Question here -- do we by default want users to receive funds of all currencies in the future? Or do we want users to be able to specify which tokens they want to receive?

- set up a devX alert on GCP tracking cEUR (should take very little time, copy cUSD alert)
(- there's an additional script: `packages/faucet/scripts/transfer-funds.ts` and it's unclear where/what service is using this, as I believe the faucet runs using the firebase function described above.)
@timmoreton  -- does this look about right to you esp. regarding the firebase functions?

(for visibility @aslawson @yerdua)

**Comment by martinvol** [comment]
For future reference I wanted to point out this is one relevant line where the minting amounts are defaulted: https://github.com/celo-org/celo-monorepo/blob/master/packages/celotool/src/lib/migration-utils.ts#L68

**Comment by eelanagaraj** [comment]
updated issue #6795 with scoping details from above.

From devX discussion -- for now, faucet should default to sending some of each currency (i.e. no specifying options or creating new endpoints, etc. for now)
