### ISSUE TITLE
Phone number verification process is asking again even when user provide verified phone number to login

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#7114]
**Frequency:** 100%
**Repro on build version:** Test flight build 1.10.1(46) , Android Internal Build V 1.10.1(1004294336)
**Repro on devices:** iPhone XR(14.2), iPhone SE (14.2), Vivo V11 pro (10)
**Testing Account:**   (515 444 0200)/ [Backup Key](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit#gid=0&range=B5)   
**Pre-condition:** User should need to provide already verified phone number in the past.
  **Repro Steps:**

1. Launch the application 
2. Go through login flow 
3. Paste account key & tgap on restore button
4. Enter verified number & observe 

**Current Behavior:** User should need to verify phone number everytime .
**Expected Behavior:** User should able to login with verified phone number.
**Impact:** Bad user experience & USer should verify number everytime.

**Attachment:**  [VerifiedPhoneNumber.mp4](https://drive.google.com/file/d/1PLyB90u5YoBIW1I497gx9hW6N8p0l6eZ/view?usp=sharing)

**Comment by ValoraQA** [comment]
Hi @jeanregisser & @isabellewei We have verified this issue on latest Play store build V1.10.1 & app store build V1.10.1 and observe that issue is still repro.
- "Phone number verification process is asking again even when user provide verified phone number to login".

**Comment by ValoraQA** [comment]
Hi  I have verified this issue using latest Test Flight Build V1.11.1(48) & Android Internal Build V1.11.1(1004294339) & observed following.
**Observations:**

- "Your Phone number Already Confirmed with Continue button" displayed when user tap on < arrow on paste 3 attestation codes when user restore verified phone number's account.
**Attachment:** [PhoneNumberConfimation.mp4](https://drive.google.com/file/d/1EoNdzXxwkGGFl3NUvO6gehVACZmEvqf6/view?usp=sharing)
Verified on Devices: Samsung Galaxy A5(7.0), iPhone SE (14.2)

**Comment by ValoraQA** [comment]
Hi @jeanregisser We have verified this issue on latest builds Android internal build V1.15.1 & Testflight build V1.150.1(64) and found issue if fixed so we are closing this ticket.
"User should able to login with already verified phone number" 
**Devices:** Vivo v11 pro (10), iPhone 6+ (12.4.5)
