### ISSUE TITLE
 Account number get truncated  on send page when user A try to send amount to request userB.

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#7118]
**Frequency:** 100%
**Repro on build version:** Android Internal Build V 1.10.1(1004294336), Testflight build 1.10.1(46) Play Store & app store builds V1.9.2
**Repro on devices:** Samsung Galaxy A5(7.0), iPhone XR(14.2), Iphone 6+(12.4.5), Vivo V11 pro (10)
**Testing Account:**  [Backup Key](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit#gid=0&range=B5)  
**Pre- condition:** User should receive any amount request.
  **Repro Steps:**

1.  Launch the application & login with a test account.
2. Make sure user should receive any mount request
3. Tap on send button
4. Observe account key,

**Current Behavior:**  Account number gets truncated on sending page.
**Expected Behavior:**  “User should able to see full account number on sending page.
**Impact:** User get blocked to see full account number.
**Attachment:**  [AccountKey.jpeg](https://drive.google.com/file/d/16ELFk1M0wqhmidwsyfgrqgF8f_PVFE11/view?usp=sharing)

**Comment by ValoraQA** [comment]
Hi @jeanregisser & @isabellewei We have verified this issue on latest Play store build V1.10.1 & app store build V1.10.1 and found issue is fixed so, we are closing this ticket.
