### ISSUE TITLE
Validators SBAT know that they need to be synced before they can send transactions

### ISSUE THREAD

**Issue by asaj** [celo-org/celo-monorepo#714]
### Expected Behavior

~- [ ] Documentation tells you what the easy to understand log message that celo-blockchain outputs when a node is synced~

- [x] CLI checks whether synced before sending tx

### Current Behavior

Documentation does not specify this

**Comment by yerdua** [comment]
As far as I can tell, there's no special log message that indicates that the node has synced. The only difference I see between a message _during_ syncing to one after it has caught up is that messages during syncing have an age associated with the chain segment:

While actively syncing:
```
INFO [09-09|13:41:17.022] Imported new chain segment               blocks=24  txs=0   mgas=0.000  elapsed=2.693s    mgasps=0.000 number=410972 hash=1a347b…88a0a4 age=13m21s    cache=2.51mB
```

synced, probably?
```
INFO [09-09|13:41:24.030] Imported new chain segment               blocks=2   txs=0   mgas=0.000  elapsed=68.509ms  mgasps=0.000 number=411122 hash=31a4ed…c69da3 cache=2.48mB

INFO [09-09|13:41:20.291] Imported new chain segment               blocks=148 txs=0   mgas=0.000  elapsed=3.253s    mgasps=0.000 number=411120 hash=19407c…2301e9 cache=2.48mB
```

**Comment by yerdua** [comment]
After running with a more verbose log level (4, rather than 3), I see this message that perhaps is the one we're looking for:
```
DEBUG[09-09|15:00:27.047] Synchronisation terminated               elapsed=13.7623173s
```

It originates here: https://github.com/celo-org/celo-blockchain/blob/master/eth/downloader/downloader.go#L454

@asaj - is this the message to call out in the documentation?
