### ISSUE TITLE
Specify Nexmo callback dynamically to POST-JSON (for v1.3.0)

### ISSUE THREAD

**Issue by codyborn** [celo-org/celo-monorepo#7140]
Nexmo callback requires the operator to specify `POST-JSON` in the Nexmo admin portal. See if it's possible to automatically specify this callback type when we initially setup the callback in the Attestation Service.

**Comment by alecps** [comment]
@eelanagaraj do you know if this is still relevant?

**Comment by eelanagaraj** [comment]
@alecps hmm not positive, though I think it's not high priority (and probably not worth any effort with ASv2 coming up soon) since nexmo is generally pretty bad anyways and there are instructions for how to configure this properly (one-time setup)

Closing and we can always reopen
