### ISSUE TITLE
Audit Support for savingscelo

### ISSUE THREAD

**Issue by nambrot** [celo-org/celo-monorepo#7143]
CAP team should support https://github.com/zviadm/savingscelo by @zviadm

**Comment by zviadm** [comment]
@yorhodes @m-chrzan let me know if there is anything that you might need from me. Most of the stuff should be self explanatory from the Readme in the project. There is also annotated output of "slither" run: https://github.com/zviadm/savingscelo/blob/main/audit/slither.out.md addressing benign issues that the tool points out.

**Comment by yorhodes** [comment]
WIP at https://www.notion.so/clabsco/SavingsCELO-Review-2e11988b7bdc4cf6a4488ba507a7f5c1

**Comment by zviadm** [comment]
> WIP at https://www.notion.so/clabsco/SavingsCELO-Review-2e11988b7bdc4cf6a4488ba507a7f5c1

I don't seem to have access to that notion document unfortunately. (it is restricted to cLabs only)

**Comment by yorhodes** [comment]
gave @zviadm a PDF export via discord

**Comment by zviadm** [comment]
@yorhodes what would be next steps here? is there anything else to wait on other than this round of comments?

My plan is to launch SavingsCELO by end of April latest. So I am happy to take in as much review/feedback i can before that but do plan on just launching it by end of April to avoid delaying it indefinitely.
