### ISSUE TITLE
Document the Account.sol abstraction better

### ISSUE THREAD

**Issue by nambrot** [celo-org/celo-monorepo#7144]
### Expected Behavior

- Account abstraction is well documented
- There is a coherent roadmap/guidance how use cases/applications should think about the abstraction

### Current Behavior

`Accounts.sol` is an account abstraction on top of Ethereum's account model that features some additional features such as:
- Authorizing other keys
- Indicating wallet addresses

However, the abstraction is 1) not well documented and 2) not very consistent. 1) is obvious, but for 2) we are not providing enough guidance how this abstraction impacts use cases like:

- Dapp interaction: I.e. should users interact with the wallet address or account address?
- Recovery: Related to dapp interaction, if its tied to the wallet address, then recovery as specced currently cannot recover funds on dapps
- User display: Currently wallet addresses are displayed which makes sense since a lot of exchanges won't lookup wallet address if you gave them the account address. However, wallet addresses can become "stale" and/or be inconsistent if dapps interact with the account address instead
- wallet interfaces: dappkit and walletconnect likely also do not know the difference, how would this possibly change the API (dappkit right now conveys the wallet address?)

**Comment by aslawson** [comment]
@aslawson add separate ticket to investigate standardizing this

**Comment by codyborn** [comment]
New item that spawned from this investigation: https://app.zenhub.com/workspaces/cap-backlog-board-600598462807be0011921c65/issues/celo-org/celo-monorepo/7381

**Comment by codyborn** [comment]
[Added external docs for the MTW](https://github.com/celo-org/celo-monorepo/pull/7421).

Wrote down our design for exposing MTW to 3rd party Dapp developers:
https://www.notion.so/clabsco/ERC20-Funds-Recovery-4cf76134fb6f406c9c25ab38408699ff#2db28237aa5a4744ba7d7e574c6f709a

**Comment by codyborn** [comment]
Created a new ticket to track the ERC20 recovery design work: #7426
