### ISSUE TITLE
cEUR faucet support - celotool & standalone faucet

### ISSUE THREAD

**Issue by tkporter** [celo-org/celo-monorepo#7150]
### Expected Behavior

Standalone Faucet

- Modify the faucet to also send some cEUR
    - [https://github.com/celo-org/celo-monorepo/blob/master/packages/faucet/src/database-helper.ts](https://github.com/celo-org/celo-monorepo/blob/master/packages/faucet/src/database-helper.ts)

Celotool faucet

- Modify the celotool faucet command to also send cEUR
    - [https://github.com/celo-org/celo-monorepo/blob/master/packages/celotool/src/cmds/account/faucet.ts#L45](https://github.com/celo-org/celo-monorepo/blob/master/packages/celotool/src/cmds/account/faucet.ts#L45)

### Current Behavior

Only works for cUSD

**Comment by albertclabs** [comment]
This has been more scoped out by DevX team in this ticket: (https://app.zenhub.com/workspaces/devx-sprint-board-5fd7e7014356ff000e7a5b19/issues/celo-org/celo-monorepo/6795)

**Comment by martinvol** [comment]
Seems like everything is done!
