### ISSUE TITLE
cEUR support in DappKit

### ISSUE THREAD

**Issue by tkporter** [celo-org/celo-monorepo#7151]
### Expected Behavior

- Add cEUR to `FeeCurrency` enum and `getFeeCurrencyContractAddress`:
    - FeeCurrency [https://github.com/celo-org/celo-monorepo/blob/master/packages/sdk/dappkit/src/index.ts#L97](https://github.com/celo-org/celo-monorepo/blob/master/packages/sdk/dappkit/src/index.ts#L97)
    - getFeeCurrencyContractAddress [https://github.com/celo-org/celo-monorepo/blob/master/packages/sdk/dappkit/src/index.ts#L102](https://github.com/celo-org/celo-monorepo/blob/master/packages/sdk/dappkit/src/index.ts#L102)

### Current Behavior

No support for cEUR in DappKit

**Comment by aslawson** [comment]
@tkporter is protocol economics planning to do this?

**Comment by aslawson** [comment]
we are deprecating dappkit - 
WalletConnect should work with all tokens, so I think this can close (cc @AlexBHarley to confirm)
