### ISSUE TITLE
[investigate] Contract changes required to allow enabling stable assets with just governance proposal and oracles

### ISSUE THREAD

**Issue by martinvol** [celo-org/celo-monorepo#7153]
### Expected Behavior

A new stable asset can be created just with a governance proposal and the deployment of oracles.

### Current Behavior

Now it requires:
1) Contracts to be released with the audit cycle (like stableTokenEUR and exchangeEUR)
2) One governance proposal to activate the oracles and freezing
3) A second governance proposal to unfreeze + enable.

**Comment by aslawson** [comment]
@martinvol is this work that's needed for be done by CAP? if not, I'd like to remove the CAP label so we are only tracking CAP work on our backlog.

If you feel CAP needs support, we can create a separate ticket with the specific ask from the CAP circle and link to this one.

**Comment by aslawson** [comment]
@aslawson find out how urgent based on timeline for releasing more stable assets

**Comment by martinvol** [comment]
I think the output of this should be economics makes a lists of things that need to be changed in both contracts and tooling, and then we open new issues and assign as we see fit.
