### ISSUE TITLE
cCAD (Canadian Dollar) stable asset on Celo 

### ISSUE THREAD

**Issue by clrblmt** [celo-org/celo-monorepo#7154]
Explore potential opportunity to drive adoption with Canadian students by helping them save (and thus pay off their debts) through merchant rebates. There is an opportunity to reduce fees and improve the user experience using crypto vs. the current system. The main benefit would allow to access their rebates immediately vs. have to wait months if not years. 

This work would be part of the additional stable assets initiative.

**Comment by albertclabs** [comment]
Will not support for now. Payd to run their own pilot.
