### ISSUE TITLE
[cli] Check 'to' address is not a ReleaseGold contract for transfer:euro

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-monorepo#7157]
### Expected Behavior

Can't send cEUR via cli to a ReleaseGold contract.

### Current Behavior

Could send cEUR funds to a ReleaseGold contract then never be able to retrieve it (without upgrading the contract, a painful and risky operation that involves a multisig).

**Comment by aslawson** [comment]
@timmoreton @gastonponti  should this be the case for all stabletokens? i looks like this can happen with cUSD now?

**Comment by aaronmgdr** [comment]
looks liek yorks PR addressed this

**Comment by aaronmgdr** [comment]
looks liek yorks PR addressed this
