### ISSUE TITLE
Add /get_attestations monitoring to metadata-crawler

### ISSUE THREAD

**Issue by codyborn** [celo-org/celo-monorepo#7159]
`/get_attestations` being available is required for the 8-digit code feature to work. Some AS operators may mistakenly block this endpoint behind a firewall. Add a rule to check this in the metadata-crawler to monitor for 404's going forward.

**Comment by alecps** [comment]
Just investigate this for now

**Comment by alecps** [comment]
@eelanagaraj do you know if this is still relevant?

**Comment by eelanagaraj** [comment]
@alecps it could be nice but not necessarily worth the effort at this point IMO. We would see validators failing with low attestation completion rates. For new validators, this is documented as a route that needs to be publicly exposed. I'll close it for now and we can always reopen if this becomes an issue in the future.
