### ISSUE TITLE
[crash>Scanner code] App get crash when user try to scan the other user QR code on send, request & scanner pages

### ISSUE THREAD

**Issue by ValoraQA** [celo-org/celo-monorepo#7163]
**Frequency:** 100%
**Repro on build version:** App store build V1.10.1 
**Does not repro version** Test flight build V1.10.1(46), Playstore build V1.10.1
**Repro on device:** iPhone 6+ (12.4.5)
**Does not Repro on devices:** Samsung A21S(10)(SM A217F)(10), iphone SE 2 (14.4), iPhone XR (13.3.1),
**Testing Account:**  [Backup Key](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit#gid=0&range=B5) 

   **Repro Steps:**

1. Launch the application & login with a test account
2. Try to scan the other user QR code 
3. Observe

**Current Behavior:**  App get crash while try to scan other user QR code.
**Expected Behavior:**  User should able to scan other user QR code.

**Impact:** User get blocked to scan other user QR code.
**Attachment:**  [CrashonScanner.mp4](https://drive.google.com/file/d/1nuoxaILHgkpFiGBOL7Q06CJ9saqwXG3g/view?usp=sharing)
[Crashlogs](https://drive.google.com/file/d/1HJolglmWWk5GsbheSz94ILnnlgIAiOpd/view?usp=sharing)

**Comment by jeanregisser** [comment]
Interesting, App Store build v1.10.1 (46) and Test Flight build v1.10.1 (46) are the same binary.

You're saying this crash happens on App Store build but not on the TestFlight one, right @Celoqa?

**Comment by ValoraQA** [comment]
Hi @jeanregisser thanks for responding.
When we have performed testing on Testflight build 1.10.1 (46) on that time not observed any crash on scanner page.
But, Today again we have cross verified the same issue now able to observe crash on both testflight V1.10.1(46) & App store build V1.10.1

**Comment by ValoraQA** [comment]
Hi @jeanregisser "App get crash also when user try to scan other user QR code on send secure" flow.

**Comment by jeanregisser** [comment]
Decreasing severity to P1.

From @gnardini:
> I just checked on appstoreconnect and less than 1% of our iOS users are on iOS 12 if I red that correctly. I think it's safe not to treat this as a blocker

**Comment by ValoraQA** [comment]
Hi @jeanregisser We have verified this issue on testflight build 1.11.1(48) and found issue is fixed so, we are closing this issue.
- User is able to scan the other user QR code 
**Device:** iPhone 6+ (12.4.5)
