### ISSUE TITLE
[First name> Swipe]iOS: User not able to swipe entered name on first name field from Create account page

### ISSUE THREAD

**Issue by ValoraQA** [celo-org/celo-monorepo#7166]
**Frequency:** 100%
**Repro on build version:** App store build V1.10.1,  Test flight build V1.10.1(46), 
**Does not repro version** Playstore build V1.10.1
**Repro on device:** iPhone 6+ (12.4.5), iPhone 5s(12.5.1)
**Does not Repro on devices:** Samsung A21S(10)(SM A217F)(10),
   **Repro Steps:**

1. Launch the application 
2. Go to Create account page
3. Enter long text on name field
4. Try to swipe 
5. Observe 

**Current Behavior:**  USer not able to swipe the enter text on name filed .
**Expected Behavior:** User should able to swipe entered text .
**Observations:** User should able to swipe the text on android 
**Impact:** User get blocked to see full text.
**Attachment:**  [SwipeNameText.mp4](https://drive.google.com/file/d/1pvYx2GY1YpTBZyH4PEkJp71uazhoEQYw/view?usp=sharing)

**Comment by jeanregisser** [comment]
This is the standard behavior of iOS input field.
You can't swipe left or right, what you can do is hold the cursor and then move it to reach the part you want.

**Comment by ValoraQA** [comment]
Thanks @jeanregisser for confirmation.
