### ISSUE TITLE
Understand accuracy of libphonenumber for VOIP classification

### ISSUE THREAD

**Issue by codyborn** [celo-org/celo-monorepo#7177]
If this library is not accurate, we should investigate VOIP usage by looking at paid calls to SMS providers (ex. [Twilio Lookup](https://www.twilio.com/docs/lookup/api#phone-number-type-values)). Do some digging to determine the false-positive/false-negative rates for this library.

https://github.com/google/libphonenumber/

**Comment by nambrot** [comment]
We should also investigate how problematic VoIP numbers actually are

**Comment by codyborn** [comment]
I wrote a quick script to measure the difference in classification between libphonenumber and Twilio Lookup for a set of 517 phone numbers that my attestation service recently served.

https://docs.google.com/spreadsheets/d/1htTPRzPErpSyEBLdfjRU-oNrauVkuxG19FVf4ir9m6E/edit?usp=sharing

All were either `mobile` or `unknown`. Twilio Lookup had much better coverage compared to libphonenumber. Twilio had classifications for 396 more phone numbers than libphonenumber did. Given that we're looking into this for sybil resistance, I don't think libphonenumber has enough coverage to be useful.

**Comment by codyborn** [comment]
```
import { readFileSync } from 'fs'
import parsePhoneNumber, { PhoneNumber } from 'libphonenumber-js'

const accountSid = "<ACCOUNTSID>";
const authToken = "<AUTHTOKEN>";
const client = require('twilio')(accountSid, authToken);

async function comparePNTypes() {
  var lines = readFileSync('/Users/codyborn/Documents/TwilioLogs.csv','utf8')
  .split('\n')

  for(var line of lines) {
    var phoneNumber = line.split(',')[1]
    
    const phoneNumberParsed = parsePhoneNumber(phoneNumber)
    if (phoneNumberParsed && phoneNumberParsed.isValid()) {
      // Note: `.getType()` requires `/max` metadata: see below for an explanation.
      var twilioType = await getTwilioType(phoneNumber)
      console.log(phoneNumber + ", " + phoneNumberParsed.getType() + ", " + twilioType)
    }
    else {
      console.error("Invalid phone number: " + phoneNumber)
    }
  }
}

async function getTwilioType(phoneNumber: string) {
  var lookup = await client.lookups.v1.phoneNumbers(phoneNumber)
        .fetch({type: ['carrier']});
  return lookup.carrier.type
}

comparePNTypes()
```
