### ISSUE TITLE
CI should actually execute a contract upgrade proposal

### ISSUE THREAD

**Issue by nambrot** [celo-org/celo-monorepo#7186]
### Expected Behavior

CI should actually move the proposal through govnernance on ganache and execute the proposal

### Current Behavior

CI only runs make-release/verify-release which doesn't actually test that the proposal txs will not revert

**Comment by yorhodes** [comment]
cc @deepakhb2 
this could be one you can work on, though we might have to sync about the details

**Comment by deepakhb2** [comment]
@yorhodes Please more details on this issue when you get sometime. Thank you.

**Comment by yorhodes** [comment]
https://github.com/celo-org/celo-monorepo/pull/8200 creates `celocli governance:test-proposal`

we could use this in combination with a dev network where ownership hasn't been transferred from `accounts[0]` to `Governance` to avoid having to shepherd proposals through governance pipeline
