### ISSUE TITLE
“Account Number” alignment is not proper when the user taps on  Hamburger Menu from the Home screen.

### ISSUE THREAD

**Issue by ValoraQA** [celo-org/celo-monorepo#7187]
**Frequency:** 100%
**Repro on build version:** Play store build V1.10.1
**Does not repro version** App store build V1.10.1
**Repro on devices:** Samsung Galaxy A21s(10.0),Samsung Galaxy M31(10.0)
**Does not repro devices** Vivo V11 pro (10.0) 
**Repro Steps:**
1. Launch the application & login without phone  number.
2. Go to the home screen & tap on “Hamburger Menu” & scroll down.
3. Observed that,
**Current Behavior:**  Account number alignment not proper.
**Expected Behavior:**  Account number alignment should be proper.
**Impact:** Bad user experience.
**Attachment:**  [AccountNumberAllignmentNotProper.png](https://drive.google.com/file/d/1thkf2rCTYjJpWpa2UQuACy4Qp0JFsQ1E/view?usp=sharing)

**Comment by ValoraQA** [comment]
Hi  I have verified this issue using latest  Android Internal Build V1.11.1(1004294339) & observed that issue is still reproduced.
**Verified on Devices:** Samsung Galaxy A21s(10.0)
**Does Not Repro on Devices:** Samsung Galaxy M31(10.0)

**Comment by MuckT** [comment]
Closed by [Valora-inc/wallet #861](https://github.com/valora-inc/wallet/pull/861).

**Comment by ValoraQA** [comment]
Hey @MuckT,  We have verified this issue using latest Android Internal Build V1.20.4 & observed that issue is fixed and "Account number" is properly aligned in Hamburger menu.

**Devices:** Samsung Galaxy A31 (10.0), Redmi Note 8(10), Samsung Galaxy J5 Prime (8.0)
**Attachments:** 
[Account Number Aligned.jpg](https://drive.google.com/file/d/1MKYfNsZRCXUcWYCkzHeQNTiIgAFIda4A/view?usp=sharing) 
Thanks..!!
