### ISSUE TITLE
cLabbers and External Devs SBAT to Integrate a Mobile App with DappKit Easily

### ISSUE THREAD

**Issue by aslawson** [celo-org/celo-monorepo#7198]
### Expected Behavior

Clear step by step instructions on how to initialize mobile application and integrate with dappkit (eg. following the steps of @barbaraliau's tech talk) the next step of pulling in Dappkit should be just as straightforward.

Requires removing expo dependency.

Should be as easy as removing expo line:
https://github.com/expo/expo/blob/master/packages/expo-linking/src/ExpoLinking.ts

### Current Behavior

There are currently version issues that make it difficult to get up and running with dappkit.

**Comment by eelanagaraj** [comment]
@AlexBHarley already updated the expo dependency + pointed to the existing Expo docs, closing this for now
