### ISSUE TITLE
[ ContractKit] I Changes needed to support optional 3 extra transaction fields

### ISSUE THREAD

**Issue by aslawson** [celo-org/celo-monorepo#7199]
Implement #6949

https://www.notion.so/clabsco/Explore-tool-changes-due-to-ethereum-format-transactions-75fb18b535664885a1da07df7169122b

**Comment by aslawson** [comment]
Work is being done on blockchain including tests @oneeman?

**Comment by oneeman** [comment]
Yes, https://github.com/celo-org/celo-blockchain/issues/1387 which includes e2e tests.  I also created https://github.com/celo-org/celo-blockchain/issues/1388 as a catchall for any needed monorepo changes besides adding e2e tests.  @gastonponti, with his knowledge of contractkit has offered to provide support if needed.  So I think this issue can be closed in favor of those two.
