### ISSUE TITLE
Integration test for adding a new StableToken via governance

### ISSUE THREAD

**Issue by asaj** [celo-org/celo-monorepo#7224]
### Expected Behavior

There is an integration test for adding a new StableToken via governance.

### Current Behavior

No such test.

**Reason for need:** Need standardized tests to run on our next StableToken #3.

**Comment by martinvol** [comment]
Important to note that this should also test that that the following order of proposal execution are supported:

1. CR3
2. cEUR oracle activation
3. cEUR activation

and

1.  cEUR oracle activation
2. CR3
3. cEUR activation

**Comment by albertclabs** [comment]
Should be done before stablecoin #3, but not as pertinent now.

**Comment by albertclabs** [comment]
It looks like nobody is working on this and it's not very important for the time being. Removing from the sprint for now. If you see this story in the future check with Audrey or Albert before starting it.
