### ISSUE TITLE
Playbook for adding new StableTokens 

### ISSUE THREAD

**Issue by asaj** [celo-org/celo-monorepo#7228]
### Expected Behavior

There is a clear playbook for adding new StableTokens, e.g. cEUR

### Current Behavior

No such playbook

**Comment by yerdua** [comment]
This involves writing a checklist of things that need to happen for deploying a new stable token.

**Comment by albertclabs** [comment]
Moving this into "in review" as there is a more functional version (Medium style) here: https://docs.google.com/document/d/17MYBLmcKqSTLpWfJMvcmeofs6Qt9xjFDj7lKWD-ji68/edit?usp=sharing

And also a more technical documentation PR by Volpe here: https://github.com/celo-org/celo-monorepo/pull/7506/files#
