### ISSUE TITLE
Minimum viable solution for "key-less" Valora account recovery

### ISSUE THREAD

**Issue by nategraf** [celo-org/celo-monorepo#7245]
### Summary

We aim to deploy a minimum viable product for a Valora experience without the account mnemonic to some, and eventually all, Valora users. Viability of any recovery solution must include both a high degree of security and reliability. With this in mind, the proposed MVP will include a 2 of 3 scheme including a local institution, phone number verification, and a passphrase.

### Detail

https://www.notion.so/clabsco/LIP-Supported-Recovery-Overview-1fb53ef2eaea456a8101395dc8e38b9a

**Comment by arthurgousset** [comment]
@alecps - Closed (deprioritised)
