### ISSUE TITLE
Design ODIS rate limiting structures suitable for secure password hashing

### ISSUE THREAD

**Issue by nategraf** [celo-org/celo-monorepo#7249]

**Comment by nategraf** [comment]
Design for domain-restricted API is now in review https://github.com/celo-org/celo-proposals/blob/master/CIPs/cip-0040.md

**Comment by alecps** [comment]
Design Doc: https://www.notion.so/clabsco/ODIS-RateLimit-Structures-3719039d08db4ffc9e55a0257e4c7468
PR: https://github.com/celo-org/celo-proposals/pull/285
