### ISSUE TITLE
Nifty Wallet Support

### ISSUE THREAD

**Issue by aslawson** [celo-org/celo-monorepo#7268]
Support Celo integration for Nifty wallet

**Comment by barbaraliau** [comment]
web3 version 0.20. Not up to date.
Not sure if we can do this because of incompatibility
Cost benefit between developing CK 

who will upgrade versions?

**Comment by AlexBHarley** [comment]
@gastonponti @aslawson are we good to close this?

They are compatible now that Donut has landed, all you need to do is add a custom RPC. Maybe we can ask them to add Celo as a default network? 

They already have Ethereum, Ethereum Classic, POA, xDai, Rinkeby, Ropsten etc. @gastonponti could you reach out?

**Comment by aslawson** [comment]
Closed as there were compatibility issues with libraries and we now have metamask support which is sufficient for power x-chain users
