### ISSUE TITLE
ODIS combiner should retry on connection failure

### ISSUE THREAD

**Issue by codyborn** [celo-org/celo-monorepo#7280]
Observed `CELO_ODIS_ERR_09 SIG_ERR Failed to request signature from signer` in the logs. This resulted from a connection failure:
[Logs](https://console.cloud.google.com/logs/viewer?interval=CUSTOM&dateRangeStart=2021-02-25T14:53:14.000Z&dateRangeEnd=2021-02-25T14:57:10.000Z&project=celo-pgpnp-mainnet&minLogLevel=0&expandAll=false&timestamp=2021-02-26T00:54:15.396000000Z&customFacets=&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22cloud_function%22%20resource.labels.function_name%3D%22getBlindedMessageSig%22%20&scrollTimestamp=2021-02-25T14:57:09.606000000Z)

The alerts correctly fired however it would be great if the service gracefully handled this with retry logic with exponential back-off.

Relevant code can be found here: https://github.com/celo-org/celo-monorepo/blob/1f7aa084a9f66ff0264a372cfdcb6d9bc7924642/packages/phone-number-privacy/combiner/src/signing/get-threshold-signature.ts#L304

**Comment by alecps** [comment]
This could be easily knocked out either as a drive by in CIP40 work and/or as an ODIS onboarding ticket

**Comment by arthurgousset** [comment]
Sprint planning: 
- On Alec's backlog (to not lose track of it)
- Basically want to look at the code
- Doesn't seem super high priority
- Eela - this is a problem in the existing ODIS logic
- Eela - perhaps get back to this after the merge (more nice to have)
- Alec agrees 
- This could be in the after merge bucket
- P0 before merge
- P1 after merge, before deploy
- We'll keep **P3** as "after deploy"
