### ISSUE TITLE
[Docs] Update DappKit documentation

### ISSUE THREAD

**Issue by barbaraliau** [celo-org/celo-monorepo#7281]
Verify and update documentation as necessary to make sure the following topics are clear:

- [x] What is DappKit?
- [x] When to use DappKit vs `useContractKit`?
- [x] When should I not use DappKit?
- [x] Send a transaction from my app to Valora using DappKit
- [x] Using DappKit on Alfajores vs Mainnet
- [x] What are known issues on DappKit?
- [x] DappKit compatibility (Android and iOS versions)
- [x] DappKit no longer has Expo (dependent on #5956. might pull this item out of this issue)

**Comment by chews** [comment]
hey good human, I am embarking on an attempt to use this. Should I hold off till code settles?

**Comment by eelanagaraj** [comment]
hey @chews sorry we missed this earlier! There is already some updated documentation on DappKit (+ a new release with some improved web-app compatibility). Feel free to reach out on [the Celo discord](https://discord.com/channels/600834479145353243/600839784700837926) (if you're not already there) as it may be easier to get a better sense of what issues/challenges currently exist with dappkit and whether it makes sense for your use case (or `useContractKit` or something else entirely) :)

**Comment by barbaraliau** [comment]
I think this was closed by #7385

**Comment by barbaraliau** [comment]
@aslawson @barbaraliau break this issue up again
