### ISSUE TITLE
Wallet exchange text cursor moves to incorrect spot when empty

### ISSUE THREAD

**Issue by tkporter** [celo-org/celo-monorepo#730]
### Expected Behavior

Text cursor is always in the center when there is no input

### Current Behavior

Found on a Pixel 3, API 28, target Android 9.0 (Google APIs)

Specific steps to reproduce (there are other ways to get this behavior by mixing up the order of these steps too):

1. Go to the exchange tab, tap exchange
2. Enter a number into the cUSD field (for example, 5)
3. Tap the button with the arrows to switch to exchanging cGLD into cUSD
4. Delete the number in the textbox. The cursor now appears here whenever the textbox is empty (for both cUSD and cGLD):

<img width="308" alt="Screen Shot 2019-08-27 at 10 24 00 AM" src="https://user-images.githubusercontent.com/20362969/63794045-ec439a80-c8b5-11e9-9457-9f747e09987b.png">

**Comment by Lss-Ankit** [comment]
Verified with Android build 1.5.1 and observed the same issue on Google Pixel XL (8.1), Moto z play (7.0), Google Pixel XL 2 (9.0)
**Does not repro:** Redmi Note 7 Pro (9.0), Samsung Galaxy A5 (6.0.1), Samsung Galaxy J7 Prime (6.0.1), Galaxy J7 Pro (8.0.1). 
Attachment: Android_CursorIssue_Exchangetab
![Android_CursorIssue_Exchangetab](https://user-images.githubusercontent.com/55572027/68738597-b9838580-060c-11ea-8293-34046f6ae2b6.png)

**Comment by annakaz** [comment]
No longer relevant after redesign

**Comment by Lss-Ankit** [comment]
Verified with latest IOS test flight build v1.9.1(41) and observed that issue is Fixed
**Device Used:** iPhone 6(12.4.7)
