### ISSUE TITLE
Transaction and balance amounts are black/dark in multiple places

### ISSUE THREAD

**Issue by coreycelo** [celo-org/celo-monorepo#7304]
### Expected Behavior

Text for amounts (transactions and balances) should not be a distinct color from the rest of the line.

### Current Behavior

Amount appears in black (dark) instead of matching the gray of the rest of the line. This happens in a few places including: 
* Transaction Feed - the comment of a CELO exchange
* Enter Amount screen - the available balance in the top bar

![IMG_0866](https://user-images.githubusercontent.com/51388535/109545714-10210700-7a7e-11eb-87b3-b3e313e6717c.jpeg)

**Comment by jeanregisser** [comment]
Adding another screenshot where the same problem is visible: 
<img src="https://user-images.githubusercontent.com/57791/112518923-2b8be300-8d9a-11eb-8b33-cd5063fe452a.png" width="50%" />

**Comment by michellewong793** [comment]
picking this up as a second task for myself, looking into this ~
