### ISSUE TITLE
Celo: <Issue Title>

### ISSUE THREAD

**Issue by joegtllc** [celo-org/celo-monorepo#7312]
My celo how can I send back to coinbase?

### Environment
* Elixir Version: 1.9.0
* Erlang Version: 22
* BlockScout Version: d09fdbfd87d54ba1a80de57ea48c5c7e6f4f61f8

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 13_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.2 Mobile/15E148 Safari/604.1`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by lynapham** [comment]
Did you ever got this resolved? I’m having the same issue

**Comment by joegtllc** [comment]
Nope they stole from me

**Comment by lynapham** [comment]
Hi. I found a solution and here’s how I got my celo back into my coinbase. Visit https://docs.celo.org/celo-owner-guide/eth-recovery. It’ll tell you how to retrieve it/find urs. Input the recovery code (account key) of the wallet that u sent it to, not the one u sent it FROM. That’s how I got mine. Lmk if you have any questions!

**Comment by joegtllc** [comment]
Thank you will try this out ! Appreciate you
