### ISSUE TITLE
Create a dashboard of completion rate based on Valora version

### ISSUE THREAD

**Issue by codyborn** [celo-org/celo-monorepo#7317]
We recently saw a spike in incompletion rate driven entirely by an unreleased Valora version. It took a significant amount of time to narrow this down. We should create a dashboard showing attestation completion rate based on Valora version to help us with this type of investigation in the future.

**Comment by alecps** [comment]
@eelanagaraj do you know if this is still relevant?

**Comment by eelanagaraj** [comment]
Something similar exists [here](https://metabase.celo-networks-dev.org/question/439?date=past7days~) -- note: it's the verification rate and not the attestation completion rate, but I think that's fine
