### ISSUE TITLE
Attestation Service should be operational in the event of a full-node outage

### ISSUE THREAD

**Issue by codyborn** [celo-org/celo-monorepo#7343]
### Expected Behavior

A full-node outage should not prevent the AS from being operation. There should be a fallback mechanism to a secondary full-node or Forno instance. This may require moving the signing key outside of the full-node management.

### Current Behavior

If the full-node goes down on an attestation service node, the service can no longer sign/submit txs.

**Comment by eelanagaraj** [comment]
cc @codyborn @arthurgousset 
1.4.0 should have closed this, feel free to reopen if there's something else required!
