### ISSUE TITLE
Expose AS public parameters (ex. SMS_PROVIDERS_RANDOMIZED)

### ISSUE THREAD

**Issue by codyborn** [celo-org/celo-monorepo#7351]
### Expected Behavior

It should be possible to get the current public config settings. This will help us collect the SMS_PROVIDERS_RANDOMIZED status so that we can do a proper comparison of SMS Providers. 

### Current Behavior

No way to collect settings such as SMS_PROVIDERS_RANDOMIZED.

**Comment by alecps** [comment]
Will need to cut new AS release
