### ISSUE TITLE
remove moment dependency from contractkit

### ISSUE THREAD

**Issue by aslawson** [celo-org/celo-monorepo#7357]
moment accounts for 12% of bundle size
https://bundlephobia.com/result?p=@celo/contractkit@1.0.2
and is only used in one tiny line [here](https://github.com/celo-org/celo-monorepo/blob/fdf0d8b4a8ed27a47273b24a3875a896ed6e2a2c/packages/sdk/contractkit/src/wrappers/BaseWrapper.ts#L129)

**Comment by aaronmgdr** [comment]
Happy To Help with this
