### ISSUE TITLE
Measure and track AS completion by Carrier x Provider x Country x Verify

### ISSUE THREAD

**Issue by codyborn** [celo-org/celo-monorepo#7367]

**Comment by eelanagaraj** [comment]
TODO: walkthrough session with @codyborn to get a sense of how the metabase dashboards currently work cc @arthurgousset

**Comment by eelanagaraj** [comment]
Next steps for the ticket, from AS data landscape walkthrough cc @arthurgousset 
- make sure necessary fields are accessible in BigQuery, i.e. that metadata crawler is updated + being piped into BigQuery
- potentially add fields to an existing model, or likely create a new model with the necessary data
 - may need to join completion rate (attestation_state_with_user_data issuer JOIN ON  attestation_service_check address or signer? unclear double check this)
 - figure out how we want to visualize this data/table -- add this to the Mainnet Attestations dashboard, potentially add later to the Mainnet Attestations - Validator Dashboards (public-facing)

(Potential later TODO): alerting based on a specific failure rate for a carrier/provider/country; currently can add an alert based on a specific question (i.e. if anything shows up for a given query, then send an alert at some frequency)
