### ISSUE TITLE
Coordinate Twilio Customer Service Investigation into Differences between "Verify Service" vs "Messaging Service" 

### ISSUE THREAD

**Issue by codyborn** [celo-org/celo-monorepo#7368]
### Context 

- [Slack thread](https://celo-org.slack.com/archives/CJXJ1EV0D/p1633483120485200) regarding _Verify vs Messaging_ **performance** and _impact assessment_.

**Comment by 0xarthurxyz** [comment]
### Additional context:

**Rationale for difference between Verify and Messaging service performance**: 

> Twilio say there is no **legal** or other reasons that they know of that would cause VerifyAPIs to perform worst than a MessageAPI with US phone number, including in China.

**Usefulness of customer support**

We probably won't receive useful support for **Twilio Customer Service** unless we connect with Eng/Product.

Next step: 

- [x] Stop communication with Twilio (close ticket)

**Cost of implementing split between Verify vs Messaging service**

> Having a redirect to a specific provider by country is already implemented. We provided recommended configs [here](https://forum.celo.org/t/messagebird-to-your-attestation-service/1136). I don't imagine adding logic to support a split among Twilio VerifyAPI + MessageBird should be too complicated.

Next step: 

- [x] Implement logic "[Attestation Service: Switch between Verify and Messaging Service by Country # 8755](https://app.zenhub.com/workspaces/identity-sprint-board-61015de9a849530010b49fc6/issues/celo-org/celo-monorepo/8755)"

**Comment by 0xarthurxyz** [comment]
**Update**: Closed Twilio ticket (via email) because we de-prioritised the investigation through Twilio Customer Support.

**Comment by 0xarthurxyz** [comment]
Closing this ticket because:

- [x] communications with Twilio are put on hold. 
- [x] @eelanagaraj is implementing the changes to adjust the Verify vs Messaging settings in the Attestation Service.
