### ISSUE TITLE
Implement identity heuristic for the IdentityProxy smart contract

### ISSUE THREAD

**Issue by kevjue** [celo-org/celo-monorepo#7396]
### Expected Behavior

The identity proxy should be able to check authorization of a msg.address w.r.t. an identity using a heuistic

### Current Behavior

It's not implemented.

**Comment by yorhodes** [comment]
duped with https://app.zenhub.com/workspaces/cap-backlog-board-600598462807be0011921c65/issues/celo-org/celo-monorepo/7399
