### ISSUE TITLE
Instrument Blockchain-API with performance metrics

### ISSUE THREAD

**Issue by yourbuddyconner** [celo-org/celo-monorepo#7402]
Blockchain API:
- RPM (Counter w/ labels for `request_verb` and `endpoint`)
- Response time (Histogram)
- Response codes (Counter w/ label for `response_code`)
- Number of “unknown” transaction types (Gauge _(?)_)

Repo: https://github.com/celo-org/wallet/tree/main/packages/blockchain-api

Recommended course of Action: 
- Instrument Blockchain-API using the Node.js Client Library for Prometheus. 
  Example here: https://github.com/siimon/prom-client/blob/master/example/server.js

**Comment by yourbuddyconner** [comment]
Talked with @gnardini about this and we came up with a couple more metrics. We also decided that we'd already identified the most important status metric for this service as being the RPM on a per-endpoint/response-code basis. 

- `query_exchange_rate_duration` - (Histogram) a measure of the execution duration of the `queryExchangeRate` method
- `pipeline_duration` - (Histogram) a measure of the execution duration of the entire pipeline which is executed for each request, this might overlap with the RPM metrics. 
- `get_raw_token_transactions_duration` - (Histogram) a measure of the execution duration of the `getRawTokenTransactions` method which fetches data from blockscout.

**Comment by yourbuddyconner** [comment]
Some examples of the queries/graphs we can make: 

![Screen Shot 2021-03-17 at 4.53.43 PM.png](https://images.zenhubusercontent.com/5dfd466e8574c815907b5c94/6acb7e08-0ece-4235-948b-692a1b59dca7)
![Screen Shot 2021-03-17 at 4.50.14 PM.png](https://images.zenhubusercontent.com/5dfd466e8574c815907b5c94/d3ae94cd-51ed-4be2-957e-826f61ea75b3)

**Comment by yourbuddyconner** [comment]
PR for this ticket is here: https://github.com/celo-org/wallet/pull/115

cc @gnardini and @carterqw2 for review.

**Comment by carterqw2** [comment]
Agree with the metrics, let's do it.

**Comment by yourbuddyconner** [comment]
PR Closed
