### ISSUE TITLE
Instrument Notifications Service with performance metrics

### ISSUE THREAD

**Issue by yourbuddyconner** [celo-org/celo-monorepo#7403]
Package Repo: https://github.com/celo-org/wallet/tree/main/packages/notification-service

Notifications Service: 
- Number of notifications sent (Counter)
- Blocks that haven't been processed (Gauge)

Recommended course of Action: 
- Instrument Notifications Service using the Node.js Client Library for Prometheus. 
  Example here: https://github.com/siimon/prom-client/blob/master/example/server.js

**Comment by yourbuddyconner** [comment]
Talked to @gnardini about this, he had a bunch of good ideas on places to instrument metrics: 
- `notification_latency` - (Histogram) a measure of the difference between the time the notification was sent and the timestamp on the transfer event that is being notified on
- `block_delay` - (Gauge) a measure of the difference between `lastBlockHeight` and `currentBlockHeight` each time the Notifications Service polls Blockscout
- `pending_requests` - (Gauge) a measure of the size of `pendingRequestsRef`, the array that stores _all_ of the pending requests in Firebase

- `latest_token_transfers_duration` - (Histogram) a measurement of the execution duration of `getLatestTokenTransfers`, a proxy for how long it takes Blockscout to return the data
- `handle_exchange_query_duration` - (Histogram) a measurement of the execution duration of `handleExchangeQuery`, a proxy for how long it takes to retrieve external exchange rates

I think the first three are invaluable and should be implemented right away, and the latter two should be implemented right now iff I can find a quick and easy way to measure method execution duration in node.

**Comment by jbsibille** [comment]
@yourbuddyconner which one of the 3 above would capture the situation when some old blocks are returned to the notification service because they are still being indexed but some more recent ones are returned?

**Comment by carterqw2** [comment]
@yourbuddyconner good metrics, let's implement those.

**Comment by gnardini** [comment]
> @yourbuddyconner which one of the 3 above would capture the situation when some old blocks are returned to the notification service because they are still being indexed but some more recent ones are returned?

I believe that would be `block_delay` and `notification_latency` to an extent. It doesn't cover order specifically but it does show us how long it takes until a block is indexed and processed by the notification service.

**Comment by yourbuddyconner** [comment]
PR For Review, cc @gnardini: https://github.com/celo-org/wallet/pull/160
