### ISSUE TITLE
Instrument Blockscout API server with performance metrics 

### ISSUE THREAD

**Issue by yourbuddyconner** [celo-org/celo-monorepo#7404]
Blockscout API: 
- RPM (Counter w/ labels for `request_verb` and `endpoint`)
- Response time (Histogram)
- Response codes (Counter w/ label for `response_code`)
- DB response times (Gauge or Histogram)

Recommended Course of Action:
- Extend [existing](https://github.com/celo-org/blockscout/tree/master/apps/block_scout_web/lib/block_scout_web/prometheus) Prometheus instrumentation, adding above-mentioned custom metrics. 

Relevant Links: 
- Prometheus Phoenix: https://github.com/deadtrickster/prometheus-phoenix
- Prometheus.ex: https://github.com/deadtrickster/prometheus.ex
- Prometheus Plugs: https://github.com/deadtrickster/prometheus-plugs

**Comment by lvpeschke** [comment]
See celo-org/data-services#36 instead.
