### ISSUE TITLE
New stablecoin launch playbook v1

### ISSUE THREAD

**Issue by albertclabs** [celo-org/celo-monorepo#7414]
### Expected Behavior
This is a v1 doc that anyone external to cLabs could read and understand the scope of both on and off chain activities, and governance procedures that are needed to happen to launch a new fiat pegged stablecoin on Celo. The audience for this is community members of Celo that is somewhat familiar with governance. It is intended to enable the community to launch their own stablecoins and community coins in the future. It may be posted to Medium or Github for public consumption.

This should feed into a better v2 internal playbook with greater technical depth that we can build on as we launch the next stablecoin.

### Current Behavior
Currently, cLabs deploys new currencies based on tribal knowledge and the community is informed of upcoming stablecoins through the CGP/CIP processes. The community is only involved through governance proceedings and 3rd party app integrations.

**Comment by martinvol** [comment]
Are we ready to close this? the only sub item is already closed
