### ISSUE TITLE
Dapp developers should easily be able to get the verification status of an address/phone-number

### ISSUE THREAD

**Issue by codyborn** [celo-org/celo-monorepo#7427]
Certain dapps like ImpactMarket would like to check the verification status and uniqueness of a phone number for one of their users. This can help with simple fraud prevention if a user is creating multiple accounts with the same phone number or claiming to own a number that is not truly verified. Today the Dapp developer will have to process events to see the address->PN identifier relationship since the only mapping that's stored on chain is from PN Identifier->Address. 

This work can be broken into two components:
1. DappKit/WalletConnect to return the phone number identifier for a Valora wallet. This allows easy lookup of verification status for an account.
2. Attestation Service to verify that the pepper originates from ODIS. This is important to ensure uniqueness of a phone number. It  can be that a user uses the same PN but constructs peppers on their own to make it appear as many unique identifiers.

**Comment by arthurgousset** [comment]
Pointing to the associated feature request in Github Discussions: [Feature Request: Return whether a phone number is verified #9296
](https://github.com/celo-org/celo-monorepo/discussions/9296)
