### ISSUE TITLE
Attestation Service should verify that the pepper originates from ODIS

### ISSUE THREAD

**Issue by codyborn** [celo-org/celo-monorepo#7429]
Certain dapps like ImpactMarket would like to check the verification status and uniqueness of a phone number for one of their users. This can help with simple fraud prevention if a user is creating multiple accounts with the same phone number or claiming to own a number that is not truly verified. Today the Dapp developer will have to process events to see the address->PN identifier relationship since the only mapping that's stored on chain is from PN Identifier->Address.

Attestation Service should verify that the pepper originates from ODIS. This is important to ensure uniqueness of a phone number. It can be that a user uses the same PN but constructs peppers on their own to make it appear as many unique identifiers.

Attestation Service should receive the PN, pepper, and signed blinded message to be able to verify the origin. If this check fails, AS should fail with a new type of error. This change is not backwards compatible so will need to be rolled out in parts.

**Comment by aslawson** [comment]
May be required for cUSD invite rewards.

**Comment by nategraf** [comment]
We should keep in mind that in the future with blinded matchmaking and ARKE, we expect that users will not use ODIS to derive a pepper. Rolling this out now may mean rolling out an exception to this rule later. One way around this would be to use the attestation metadata being included to provide for phone-number type, to include an indicator of whether or not ODIS was used to derive an identifier.

**Comment by emilhotkowski** [comment]
@nategraf I've tried to consider your way of veryfing but as far as I understand we would use some metadata given in a request to recognize pepper type? We can never trust a user input. If we want to have some verification method we would need to do it internally, like for example 10 minutes cache on a REDIS with recently generated peppers or some other thing that we have control over. 

@codyborn
I see two possible solutions for this requirement _"Attestation Service should verify that the pepper originates from ODIS."_:
- Either we have some cryptography way of doing it (I am not sure how we could trust this verification if everything is coming from a user)
- Or we have some extra  mechanism in ODIS to verify if this pepper was recently generated. We could make this mechanism internal and cache could be short living.

**Comment by nategraf** [comment]
> Either we have some cryptography way of doing it (I am not sure how we could trust this verification if everything is coming from a user)

ODIS is a verifiable OPRF, so if the user forwards the signature they received from ODIS to the attestation service, the attestation service can verify it is a signature over the phone number against the ODIS public key.

> Or we have some extra mechanism in ODIS to verify if this pepper was recently generated. We could make this mechanism internal and cache could be short living.

ODIS does not know what pepper values it generates. (This is a key feature of the system)

**Comment by emilhotkowski** [comment]
Thanks a lot guys, it is clearer to me how it works. 

So far, from what I've seen in the code of attestation service, I would imagine that this verification should happen before we create new attestation on a request. Specifically _attestation-service/src/requestHandlers/attestation.ts_ in function _doAttestation()_ we have a place where we create a new attestation and before creating it we could verify if this request was generated with a help of ODIS. Does it make sense ? @codyborn 

I'd also appreciate some help on how can I verify it. Do we have some cryptography library? I know that ODIS' public key will be provided via a configuration but the logic itself is foreign to me.

**Comment by codyborn** [comment]
Yes, adding it to the request validation logic in `doAttestation()` makes sense. 

For verification, we have a library that can help with this:
https://github.com/celo-org/celo-monorepo/blob/b16a2d472a7cf24858f9d8b33a7185c8b81a261a/packages/sdk/identity/src/odis/phone-number-identifier.ts#L135
You would create a new `WasmBlsBlindingClient` passing in the well-known `odisPubKey` which is unique for each environment (alfajores, mainnet).

**Comment by emilhotkowski** [comment]
@codyborn 
I've made a few attempts but I cannot get one thing. I believe I am putting wrong data in this function 
```
export async function getPhoneNumberIdentifierFromSignature(
  e164Number: string,  // Here I put phoneNumber for the request
  base64BlindedSignature: string, // what here?? this.key.identifier, ends up with "Must call blind before unblinding" error
  blsBlindingClient: BlsBlindingClient  // Client with ODIS_PUBLIC_KEY
):
```
Any idea where can I find blinded signature or do I have to somewhat generate it based on pepper I was provided in the request?

**Comment by codyborn** [comment]
The blinded signature is returned from the ODIS client. Here's an example in the tests:
https://github.com/celo-org/celo-monorepo/blob/d33672fb0b7bcff67651abfbbabe845412e7ccf1/packages/sdk/identity/src/odis/phone-number-identifier.test.ts#L115

**Comment by emilhotkowski** [comment]
It looks like service context requires us to provide 
```
 authSigner,
 serviceContext,
```
Where service context is
```
export interface ServiceContext {
  odisUrl: string // Oblivious Decentralized Identifier Service Url
  odisPubKey: string
}
```
To my understanding we never wanted to call ODIS in this case? but "getBlindedPhoneNumberSignature" [calls ODIS](https://github.com/celo-org/celo-monorepo/blob/d33672fb0b7bcff67651abfbbabe845412e7ccf1/packages/sdk/identity/src/odis/phone-number-identifier.ts#L123) and without this function we cannot verify pepper.

**Comment by codyborn** [comment]
Ah, so the user will have already called `getBlindedPhoneNumberSignature` at this point. The user will need to pass the result of this to the Attestation Service so that it can verify it.

**Comment by eelanagaraj** [comment]
Hey @codyborn! Was chatting with @emilhotkowski about this and want to check my understanding. For the use case we are imagining, a Dapp would have only the PN Identifier + Address, but not the user's phone number? What we are trying to mitigate is Dapps/users that are trying to create a bunch of different PN Identifiers by repeatedly requesting attestations for the same phone number but with different `identifier` values in each request, and to do this, from now on we will check that the passed in `identifier` uses a pepper from ODIS. Is that correct?

Out of my crypto-depth here, but is it possible to verify if a blinded identifier originated from ODIS without also knowing the phone number (i.e. verify the signature on the blinded identifier)? If so, would it be possible/preferable to expose this sybil-resistant check as a separate endpoint of the attestation service/ODIS altogether, which would then be backwards compatible? That is, a user can create a bunch of different attestations if they would like, but a Dapp like ImpactMarket could then send a request to the AS/ODIS to check if a blindedIdentifier provided by a user uses a pepper from ODIS? If so, this could be a backwards compatible way of providing this sybil-resistant check without requiring unique attestations.

**Comment by codyborn** [comment]
Hey @eelanagaraj!
> and to do this, from now on we will check that the passed in identifier uses a pepper from ODIS. Is that correct?

Yes, exactly. The Attestation Service would check prior to providing its signature, so that down-stream no app or individual would need to.

Unfortunately, you cannot derive the original ODIS provided pepper from the on-chain identifier. We're using a SHA3 hash of the (phone number + pepper) to derive the on-chain identifier:
https://github.com/celo-org/celo-monorepo/blob/b552c608d0db20d15389fdfc443e9535f6cb3f65/packages/sdk/base/src/phoneNumbers.ts#L14

**Comment by emilhotkowski** [comment]
@codyborn to my understanding and a little conversation with Eela, I figured that what comes in AttestationRequest comes from a wallet (ie Valora). Some anything that I add to the body of AttestationRequest is out of my/our control. Giving it a new **required** field would break the existing contract. Adding _blindedPhoneNumberSignature_ as an optional field in the request's body is IMO the best option. 

I'll proceed coding with this assumption, until told otherwise :)

**Comment by eelanagaraj** [comment]
From my understanding the DApps would be accessing the user’s already-attested on-chain identifier (as opposed to verifying phone numbers directly). The DApps want to have security that the attested identifier is unique to the phone number, but from what I understood from @codyborn's earlier response, it can only know this if 1) all attestations produced by the AS require that the pepper originates from ODIS or 2) the AS stores this information about a subset of attestations (i.e. some "tag" is stored in the AS about a particular PN Identifier that can then be retrieved by a DApp -- but this feels a bit messier).

If this is correct, if a DApp doesn't include the `blindedPhoneNumberSignature`, then the verification should fail; that is, it should not be possible to verify a phone number with a pepper not derived from ODIS. Or am I missing something here?
@codyborn @emilhotkowski

**Comment by codyborn** [comment]
> 1) all attestations produced by the AS require that the pepper originates from ODIS

This is the planned solution. We can roll it out in phases. Once all Valora users are on the upgraded version, we can make the field mandatory. 

> If this is correct, if a DApp doesn't include the blindedPhoneNumberSignature, then the verification should fail; that is, it should not be possible to verify a phone number with a pepper not derived from ODIS. Or am I missing something here?

If we go with the first approach, the Dapp just needs to know that the user is verified. The Attestation Service is the one who checks the `blindedPhoneNumberSignature`.

**Comment by isabellewei** [comment]
The client (ex. Valora) will provide the Attestation Service with the _unblinded_ phone number signature. Using this, the plaintext phone number, and the ODIS public key, the Attestation Service can verify that the signature was signed by ODIS
