### ISSUE TITLE
Develop shared process docs with OpenZeppelin for retainer audits 

### ISSUE THREAD

**Issue by yorhodes** [celo-org/celo-monorepo#7440]
### Expected Behavior

Defined roadmap, roles, and responsibilities for members of the OpenZeppelin and cLabs team to ensure a smooth audit cycle

### Current Behavior

No shared docs or process

**Comment by kevjue** [comment]
Here's the shared Clabs-OZ processs doc:

https://docs.google.com/document/d/14tb18jieQV2d3cFceE4-SRq-2vZBVQpVzwj9O8yQ0Zg/edit

**Comment by yorhodes** [comment]
closed with updates to above linked google doc
