### ISSUE TITLE
Fix DappKit `Example: Exchanging cUSD and Locking CELO`

### ISSUE THREAD

**Issue by eelanagaraj** [celo-org/celo-monorepo#7444]
`Example: Exchanging cUSD and Locking CELO` currently doesn't compile/work. Fix these docs so that the example is actually runnable.

Combine this with the reorganization of the `README` vs. `usage.md` docs.

**Comment by aslawson** [comment]
@eelanagaraj I cannot find `Exchanging cUSD and Locking CELO` in the docs. where is it?

**Comment by aslawson** [comment]
Also did you already do the  "reorganization of the README"

**Comment by eelanagaraj** [comment]
Merged Ponti's PR that fixed this into my reorg PR [here](https://github.com/celo-org/celo-monorepo/pull/7385), a review on that will close! cc @aslawson
