### ISSUE TITLE
Add Local CICO options in Brazil to the Add/Withdraw Flow

### ISSUE THREAD

**Issue by nityas** [celo-org/celo-monorepo#7449]
### Expected Behavior
Users in Brazil have 2 local CICO options (not integrated in Valora) that should be listed to users in that country
- Bitfy: CICO for cUSD/BRL via Bitfy app [LIVE] - https://bitfy.app/
- FlowBTC: exchange in Brazil working to get cUSD and CELO listed by the beginning of April 2021 [WIP, Co-Marketing campaign is live] - https://www.flowbtc.com.br/ (should be https://www.flowbtc.com.br/celo.html but not live yet)

### Current Behavior
Users in Brazil only see global options in the CICO flow
---
More details on the campaign: https://docs.google.com/document/d/1tu1V6PijKIfSJ3gZUY6Ic-mwcvMxBdSeT2ZUBXFUcx0/edit?usp=sharing

**Comment by tarikbellamine** [comment]
Closed by: https://github.com/celo-org/wallet/pull/132#event-4473067382
