### ISSUE TITLE
Cleanup deprecated oracles deployment on RC1

### ISSUE THREAD

**Issue by bowd** [celo-org/celo-monorepo#7451]
### Overview

Because we needed to make significant changes to the deployment structure of oracles for multi-currency, upgrading the existing CELOUSD oracles was not an option, instead we created a new deployment and temporarily scaled down the stateful set associated with the old deployment. 

This issues relates to tearing down the old deployments and associated azure identities. Which can be done by switching to an older version of `celo-monorerpo` (before https://github.com/celo-org/celo-monorepo/pull/7028 was merged) and running `celotool deploy destroy ...` 

The reason this was not done straight away was so that we can still quickly scale-up the previous deployment if any issues were to surface with the new on.

**Comment by nvtaveras** [comment]
Did this by checking out to https://github.com/celo-org/celo-monorepo/commit/295b554993c66dcf9e1d3d4d3fd9cfa3c7ddb510
