### ISSUE TITLE
Upgrade combiner DB to HA tier

### ISSUE THREAD

**Issue by alecps** [celo-org/celo-monorepo#7456]

**Comment by codyborn** [comment]
- Ensure that upgrading the DB tier does not incur any downtime (on Staging)
- Upgrade both staging and mainnet

**Comment by codyborn** [comment]
Upgrade incurs some downtime of a couple minutes. Temporarily swapped Alfajores DB during upgrade to limit user facing errors.

https://celo-org.slack.com/archives/CP5V8KF51/p1616555864116500
