### ISSUE TITLE
Add monitoring and alerting to combiner DB

### ISSUE THREAD

**Issue by alecps** [celo-org/celo-monorepo#7460]
Metrics already exist, just have to setup alerts when limits are hit

**Comment by codyborn** [comment]
- Added Monitoring for both [Mainnet](https://console.cloud.google.com/monitoring/dashboards/builder/2873fde9-f0d9-4961-9563-68677dacebd8?authuser=0&project=celo-pgpnp-mainnet&dashboardBuilderState=%257B%2522editModeEnabled%2522:false%257D&timeDomain=1m) and [Alfajores](https://console.cloud.google.com/monitoring/dashboards/builder/886dd3f4-8656-418b-a4a7-8ba846ddc479?project=celo-phone-number-privacy&dashboardBuilderState=%257B%2522editModeEnabled%2522:false%257D&timeDomain=1m)
- Added alerting for both
