### ISSUE TITLE
Wallets Transaction Confidence

### ISSUE THREAD

**Issue by nambrot** [celo-org/celo-monorepo#7461]
### Expected Behavior

We should have a roadmap for what the next step in tx signing we want to do. This ticket should only reflect investigative work. Opportunities could include:

- Clarify about accessing verified contract ABIs
- Provide attestations to Contract Addresses/ABIs
- Connect transaction to existing identities such as DNS (or twitter)

### Current Behavior

- Dappkit only shows the destination address and tx data which is very opaque
- Ledger app only supports GoldToken/StableToken tx data decoding
- WalletConnect likely inherits from dappkit

**Comment by aslawson** [comment]
Interactions with Core contracts = ABIs + Valora
3rd part contracts needs to investigate identity

**Comment by codyborn** [comment]
ABI verification is one of the most important pieces in the short-term. Currently community is using https://github.com/ethereum/sourcify for this.
