### ISSUE TITLE
core contract release process should include step to verify PRs to be audited with author

### ISSUE THREAD

**Issue by kevjue** [celo-org/celo-monorepo#7470]
### Expected Behavior

All PRs that are assigned to be audited should be verified by the PR author (unless the author is external).

E.g. for Release 4, this [PR](https://github.com/celo-org/celo-monorepo/pull/7254) was initially designated to be audited.  But @alecps later mentioned that it was going to be reverted.

### Current Behavior

PRs designated to be audited are not verified by the PR author.

**Comment by yorhodes** [comment]
closed with updates to https://www.notion.so/clabsco/Release-Process-9876c6c0773249d687c6c2413e7bab76
