### ISSUE TITLE
Update GoldToken symbol constant to CELO

### ISSUE THREAD

**Issue by yorhodes** [celo-org/celo-monorepo#7471]
### Expected Behavior

- `GoldToken.symbol() === CELO`
- CGP outlining contract change (currently coupled to release setImplementation() due to constants being compile time artifacts)
- Forum post describing motivation and announcing to any stakeholders that this may be changed

### Current Behavior

`GoldToken.symbol() === cGLD`

**Comment by aslawson** [comment]
@yorhodes what are the implications of this change?

**Comment by yorhodes** [comment]
@asaj can chime in as he suggested this but mostly to rid ourselves of this `cGLD` bytecode
stakeholders like exchanges which are familiar with ERC20 but not celo should be able to consume this ticker programatically

**Comment by m-chrzan** [comment]
What should `name` be changed to? Currently it's "Celo Gold", imagine we want to change that as well. What is the official "full name" of the asset? "CELO", "Celo", "Celo Native Asset"?
