### ISSUE TITLE
celocli network:parameters support cEUR

### ISSUE THREAD

**Issue by martinvol** [celo-org/celo-monorepo#7473]

**Comment by aslawson** [comment]
@gastonponti do you have context on this one?

**Comment by barbaraliau** [comment]
Setting default network parameter

**Comment by eelanagaraj** [comment]
looks like this is already done but was taken out as part of @tkporter's refactor, or am I missing something else that needs to be done? @martinvol 

Running this on commit `25b662b4e` (right before Trevor's PR), seems like `ExchangeEUR` and `StableTokenEUR` appear in `network:params`. Also [`network:contracts`](https://app.zenhub.com/workspaces/devx-sprint-board-5fd7e7014356ff000e7a5b19/issues/celo-org/celo-monorepo/7472) seems to be in a similar situation

**Comment by gastonponti** [comment]
Oh, sorry @eelanagaraj. I have a PR for this.

**Comment by eelanagaraj** [comment]
@gastonponti all good! but just curious, it seems like it's already done in the older version of master (commit `25b662b4e`)? Or is there additional stuff we added to the `network:params` command anyways?
