### ISSUE TITLE
Investigate dappkit issues with iOS -- celo-dappkit (trufflebox)

### ISSUE THREAD

**Issue by aslawson** [celo-org/celo-monorepo#7481]
https://celo-org.slack.com/archives/C014SRL4URY/p1615916591004600

https://github.com/critesjosh/celo-dappkit

Timeboxed to 2 dev days

**Comment by barbaraliau** [comment]
Related to issues with Expo framework. Works with Android, can't get started on iOS. Possible to do with versions, but could be more errors in DappKit or the tutorial itself.

**Comment by barbaraliau** [comment]
Note: Setting up iOS is time-consuming
