### ISSUE TITLE
Extract Documentation from Monorepo

### ISSUE THREAD

**Issue by aslawson** [celo-org/celo-monorepo#7488]
Pull documentation into its own repo

**Comment by cmcewen** [comment]
So far I haven't done much but open lots of tabs - hoping to get a little further this week

**Comment by aslawson** [comment]
2 pieces left is:
- moving all documents over
- makes sure autogenerated docs is set up and works

**Comment by AlexBHarley** [comment]
https://github.com/celo-org/docs
