### ISSUE TITLE
[WalletConnect] Re-add Alex's changes: Use walletconnect for all Valora integrations in use-contractkit

### ISSUE THREAD

**Issue by aslawson** [celo-org/celo-monorepo#7490]
First step toward deprecating dappkit

Changes were made but need to be reapplied on top of Ian's PR merge

**Comment by AlexBHarley** [comment]
Currently the list in the modal looks like

- WalletConnect
- Metamask
- Ledger
- Valora
- Private Key

My suggestion would be to do

- Valora (using WalletConnect, not DappKit. Bit sneaky but just to promote Valora)
- WalletConnect (for other WalletConnect compatible wallets)
- Ledger
- Metamask

Remove the private key option when NODE_ENV=production.

**Comment by barbaraliau** [comment]
Blocked by WalletConnect landing in Valora

**Comment by barbaraliau** [comment]
When you click Valora, use WalletConnect. instead of current DappKit connection

**Comment by barbaraliau** [comment]
Prerequisites: Run Valora on phone locally for testing
Code: Replace logo etc.

**Comment by aslawson** [comment]
@barbaraliau -- one piece to add is that on desktop web browser, it should look like the standard walletconnect experience with a QR code. But in a mobile web browser it should deep link.

**Comment by AlexBHarley** [comment]
This is basically done. I pushed some code and it's live on https://use-contractkit.vercel.app and released as `@celo-tools/use-contractkit` `v1.0.0-beta.12`. I'll wait for the Valora integration with WC to go live though before closing this. I want to verify the deeplinking works on Android too.
