### ISSUE TITLE
Create use-contractkit library for react native

### ISSUE THREAD

**Issue by aslawson** [celo-org/celo-monorepo#7491]
Exploration. What do we want to do?
Output: Design doc (draft is fine)

**Comment by medhakothari** [comment]
So Alex and I chatted about this, and we have come to the conclusion that this library might not make sense to use. 
However, I do want others' thoughts, so will discuss at next Monday's DevX meeting or async on slack. 

[Notes and my thoughts here](https://www.notion.so/clabsco/use-contractkit-library-for-react-native-42e76ab071d24d6298197c566c9c39b0)

**Comment by aslawson** [comment]
Hey @medhak1 the notion is private so I cannot view. I also chatted with Alex and had some thoughts here if we decide to not provide an opinionated modal:

1. Valora couldn't be a "top-level" option. This means deeplinking to Valora would be difficult. -- This could be addressed by creating a wallet connect endpoint that prompts users to select their wallet.
2. There wouldn't be an extensible modal standard that other wallets could promote dapp developers to add their wallets as "top-level" options (less important, but maybe there would be dapps that would want to do this)
3. Alex made a great document/tutorial on how to implement WalletConnect. Wondering if this still provides any additional ease to just have a plug-and-play library? (i'm not sure how complex the code is here)
4. We should have a doc page to consolidate the Dapp-to-Wallet integration that directs them to:  web developers --> use-contractkti, mobile developers --> <library or just wallet connect docs>
