### ISSUE TITLE
Documentation for Using Original Metamask

### ISSUE THREAD

**Issue by aslawson** [celo-org/celo-monorepo#7518]
Work wit @prestwich & @oneeman to generate documentation for how to use metamask with Celo post donut hardfork, and how to integrate in dapps (should not be the norm, but an advance feature)

Documentation Page that contains at least the following info:

- [x] a warning that Original Metamask compatibility is not natively supported by Metamask and that only sophisticated users should use it
- [x] a standard snippet for adding the Celo network to metamask using their custom network API
- [x] how devs select an appropriate gas price parameter
- [x] the derivation path mismatch and why these funds will not immediately show up in other Celo wallets
- [x] that the UI may show ETH logo when it means Celo
- [x] the contract addresses for cUSD and cEUR and how to add them as custom tokens in metamask (can be done programatically right after adding the network)

Guide for "how do you use Metamask as a user"
Don't send funds to wrong addresses

**Comment by prestwich** [comment]
[equivalent page for BSC](https://docs.binance.org/smart-chain/wallet/metamask.html)

**Comment by prestwich** [comment]
here's a screenshot of a BSC setup. As you can see. there's no logo, but it accurately shows the BSC symbol

![Screen Shot 2021-04-15 at 11.24.28.png](https://images.zenhubusercontent.com/5fa1bd4191c6226145eba90b/785ab6ad-f453-4b6b-9605-714dd5c2103d)

**Comment by prestwich** [comment]
[Custom network API documentation](https://docs.metamask.io/guide/rpc-api.html#other-rpc-methods)

**Comment by oneeman** [comment]
This is how I added a custom RPC method to web3:
```
    web3.extend({methods: [{name: 'getBLS', call: 'istanbul_getValidatorsBLSPublicKeys', params: 1, inputFormatter: [web3.utils.numberToHex]}]})
```

Could be similarly done for gas price (`eth_gasPrice`)

**Comment by prestwich** [comment]
Some notes from 4/15/2021 meeting:

Focus on dapp developers rather than users. Now that an api for this exists, we should not prioritize manual action

educate on these three things to build a celo-forward web dapp using metamask/walletconnect/etc:
1. explicit gas price selection
    - snippet for estimating gas price in ethers (James)
    - snippet for estimating gas price in web3
2. adding the network 
    - snippet using metamask's `wallet_addEthereumChain`
3. link to add cUSD asset to the wallet
    - snippet using `wallet_watchAsset`
4. encourage devs to disable the app when on the wrong network

**Comment by medhakothari** [comment]
[My notes ](https://www.notion.so/clabsco/Documentation-for-Using-Metamask-w-Celo-b871aefaa721407bbea864d76c64dbd0)from the same meeting above!

**Comment by barbaraliau** [comment]
@medhak1 how is this progress? do you need any additional resources to complete before the next milestone?

**Comment by medhakothari** [comment]
Guide finished here: https://www.notion.so/clabsco/Draft-Using-MetaMask-with-Celo-b81e2907633e4157923dc959ce086052

Will be made into a PR that is published on May 18th, right before Donut is enabled on mainnet.
