### ISSUE TITLE
Modify release process for the 1 week prior scoping and release management effort for the OZ audit

### ISSUE THREAD

**Issue by kevjue** [celo-org/celo-monorepo#7528]
This will involve initial communication with OZ for the audit round.  Also will need to start making public the changes made for that audit/release round.

Per the contract with OZ:

```
In order to use the booked time, we will need the commit hash 1 week before the
starting date and to define the scope and sign the WO in advance before the audit
starts.
```

**Comment by yorhodes** [comment]
fixed in updates to https://www.notion.so/clabsco/Release-Process-9876c6c0773249d687c6c2413e7bab76

**Comment by yorhodes** [comment]
closed with updates to https://www.notion.so/clabsco/Release-Process-9876c6c0773249d687c6c2413e7bab76
