### ISSUE TITLE
Update dappkit+walletconnect & Valora to have separate deeplink pathways for alfajores

### ISSUE THREAD

**Issue by aslawson** [celo-org/celo-monorepo#7530]
handover to wallet team
----
currently developers cannot have both alfajores and mainnet valora versions installed and use the dappkit for deeplinking for both. workaround is to only have the alfajores wallet installed during development, but many developers instead have just done testing on mainnet rather than bother the hassle (cheap to do now but may not always be the case). overall, this is a confusing developer experience and should be an easy fix by creating unique deeplink urls for the separate versions.

https://celo-org.slack.com/archives/CL7BVQPHB/p1616448441062200

- [ ] Valora changes
Pathway is currently hardcoded
https://github.com/celo-org/wallet/blob/6e8df4e23fd07d8f6470f67f67f0f3d87aced3d3/packages/mobile/ios/celo/Info.plist#L32
https://github.com/celo-org/wallet/blob/6e8df4e23fd07d8f6470f67f67f0f3d87aced3d3/packages/mobile/android/app/src/main/AndroidManifest.xml#L25

we should update this to be configurable in the .env files

- [ ] dappkit
https://github.com/celo-org/celo-monorepo/blob/8e9da539cf39440d6dde177d3db315540c163ff1/packages/sdk/utils/src/dappkit.ts#L4

- [ ] walletconnect

--
we should keep mainnet pathway the same so we do not break production use cases for our developers. The change to the wallet will break for development use cases where the developer ONLY has alfajores installed and has not updated dappkit/walletconnect, but this should be ok as long as we have timed the latest version of dappkit/walletconnect to account for it.

**Comment by vibern0** [comment]
Hi,
where can I find more about this?
Was this solved?
