### ISSUE TITLE
Attestation Service can produce PN-type claims

### ISSUE THREAD

**Issue by codyborn** [celo-org/celo-monorepo#7537]

**Comment by codyborn** [comment]
- Add calls to get PN type
- Let validator community know about increased costs
- Issue claim to be consumable by Valora
  - Claim should contain:
    - PN type
    - PN Identifier
    - Issuer
    - Issuer signature
    - Block number or epoch

**Comment by codyborn** [comment]
Swapping this work with @alecps

**Comment by alecps** [comment]
Update: This work now just involves reviewing and merging the existing Spruce PR https://github.com/celo-org/celo-monorepo/pull/8690 
@alecps will use this work as an opportunity to on-board onto the AS
