### ISSUE TITLE
Valora can manage / log PN-type claims

### ISSUE THREAD

**Issue by codyborn** [celo-org/celo-monorepo#7539]
Valora can receive and manage a PN-type claim. 

Claim will be received from attestation service endpoint. Claim will need to be stored by Valora in a public location using CIP-8. Claim will need to be given to Komenci for Celo Rewards.

**Comment by codyborn** [comment]
Swapping this work with @alecps

**Comment by alecps** [comment]
Relevant PR https://github.com/valora-inc/wallet/pull/879

**Comment by alecps** [comment]
Update: The scope of this ticket was reduced to simply logging the phone number type credential in Valora so that voip usage can be monitored. Based on the results of that monitoring we can determine how to prioritize actually storing the credential.
