### ISSUE TITLE
[WalletConnect] DApps should be able to submit multiple transactions at once

### ISSUE THREAD

**Issue by AlexBHarley** [celo-org/celo-monorepo#7551]
This should already be supported by the WalletConnect protocol. We just need to handle an array of actions in Valora that the user accepts in succession.

----
handover to wallet team

**Comment by aslawson** [comment]
closing since we decided it would only handle one transaction at a time

**Comment by AlexBHarley** [comment]
@aslawson this was around a DApp sending multiple TXs, then the user having to approve each one. What we want is the following flow

- DApp sends 2 TXs
- User approves both
- DApp continues

We don't want

- DApp sends a TX
- User approves
- DApp sends another TX
- User Approves

This makes it extremely clunky to interact with DApps. The user will still only be able to see one action at a time.

**Comment by aslawson** [comment]
Gotcha -- What do other wallets do? Or does wallet connect suggest any best practices here? I'm not finding much in the documentation.
I was under the impression most wallets perform the latter example ^  but it was up to the dapp developer to wrap everything into a single transaction (which we should encourage).

I definitely agree if the standard is to send them one at a time, the experience becomes clunkier with mobile apps.

**Comment by aslawson** [comment]
This also now seems related to the discussion on accessing offchain data, no? How do they access multiple contact's photos/names at once?

**Comment by AlexBHarley** [comment]
The best example is the transferAndCall route. We `approve` some contract to take tokens from us, then do the action (e.g. Uniswap). Here we can't do a single TX I believe, but we should be able to approve these two actions in succession on Valora without having to wait for the first TX to be mined.

 Re. accessing off chain data, imagine a dApp wants to read a users encrypted profile picture. To do this it

- Requests the shared secret (1st request to Valora)
- Computes the storage path and requests file
- Decrypts key (2nd request to Valora) and then decrypts profile picture. 

Currently this would look like 2 confirmable requests, if we wanted to request a users name as well, 4 requests. To display the names and pictures of all their friends, 4 * N requests. So maybe here we would want to not prompt on Valora for `decrypt` and `computeSharedSecret` calls? We'd put the onus on users to connect to DApps they trust.

We could also go the route of a `celo_offchainRead`, Valora would handle the above steps and just transmit back decrypted data. Not sure if this would work for binary payloads like pictures though, so maybe not worth thinking about.

**Comment by aslawson** [comment]
Gotcha -- so transferAndCall use cases are really the only onchain cases that couldn't be wrapped by another call function since it requires two block transactions right now.

Is this more a decision for your current implementation work on this or is this additional work to support multiple transaction prompts which we can have anyone else take on?

**Comment by aslawson** [comment]
Pretty sure this works already
