### ISSUE TITLE
Analysis of redundancy needed for oracles

### ISSUE THREAD

**Issue by albertclabs** [celo-org/celo-monorepo#7555]
**Definition of done:**
- Design doc written and circulated for review
- Optimal number of oracles and segregated cloud regions identified
- Options on path to decentralized operation covered
- Create relevant new stories for development, deployment, testing, documentation
- Signoffs needed from: Asa and 1 economist
- Presentation to Platform economics team with feedback

**Expected Behavior**
Come up with a design on how to ensure fallback reliability of oracles in case of server failures or outages. This model should identify an optimal N+x number of oracles to run what a likely path to non-cLabs operation of such oracles may look like

**Current Behavior**
No fallback plan for reliable oracle operations

**Reason for need:**  This is needed as a stepping stone to oracle decentralization and to build trust in our oracle infra. We will not get to independently run oracles without this work.

**Comment by tkporter** [comment]
Doc to pull from: https://docs.google.com/document/d/19rJ5BNE-mxttMmNYyndYVZRMT-aOMHI3sMbXeNWhnCM/edit

**Comment by nvtaveras** [comment]
Did a write up on the current state of things (from the doc linked by Trevor) as well as some of the remaining open questions before moving forward with this task:

https://docs.google.com/document/d/1kKhQtuEkmj8uFUQMy_RX8P6jPO1t5jOV7Kv4SbikGsw/edit

**Comment by albertclabs** [comment]
Removed from sprint while oracles initiative is being scoped. This story may still be used in our implementation. To check back if this is still applicable.
