### ISSUE TITLE
Celo: <Issue Title>

### ISSUE THREAD

**Issue by Dovagedys** [celo-org/celo-monorepo#7613]
*Describe your issue here.*
Hi,The money has not been transferred to my account because I made the wrong transfer. I have been waiting for 8 days. Please help. Blok Number : 5877016 / 188.10 USDC :(
### Environment
* Elixir Version: 1.9.0
* Erlang Version: 22
* BlockScout Version: 84ce46d650ca2c38079c50706f155cc313ee1bd0

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by Dovagedys** [comment]
I wanted to know my binance account as celo from coinlist, but I accidentally converted it to CUSD in the coinlist and tried to put it in my CELO wallet on Binance, but I have been waiting for more than 10 days!

**Comment by lynapham** [comment]
Hi I’m having the same issue. Just wanted to know, did you ever get it resolved??

**Comment by Dovagedys** [comment]
Unfortunately they didn't even return :/

**Comment by lynapham** [comment]
Have you contacted binance?

**Comment by Dovagedys** [comment]
No, does it work?

**Comment by lynapham** [comment]
Either your celo got lost or delayed. I had an issue with transferring it to trust wallet Bc they don’t support celo so there’s how I was able to get it back. Visit https://docs.celo.org/celo-owner-guide/eth-recovery. It’ll tell you how to retrieve it/find urs. Input the recovery code of the wallet that u sent it to, not the one u sent it FROM. That’s how I got mine. Lmk if you have any questions!

**Comment by lynapham** [comment]
My celo basically got sent into the actual CELO web instead and I just retrieved it there back into my coinbase

**Comment by Dovagedys** [comment]
I did not understand how to do this process, where do I write the codes
