### ISSUE TITLE
https dependencies no longer work with npm 7 in CI

### ISSUE THREAD

**Issue by daffl** [celo-org/celo-monorepo#7629]
### Expected Behavior

The expected behaviour is that all modules of the official latest version of the Celo SDK are published to npm and not pulled from third party dependencies and external URLs like GitHub. Using non-npm dependencies has always led to many issues that are hard to debug and predict in all the projects I worked on so far.

### Current Behavior

A breaking change introduced in npm 7 (see https://github.com/npm/cli/issues/2610) causes all `https` dependencies to be re-written as `git+ssh` in the `package-lock.json`. This breaks in many environment (e.g. most CI environments like GitHub actions) with a permission denied error trying to install Celos non-npm dependencies:

![Screen Shot 2021-04-06 at 2 20 53 PM](https://user-images.githubusercontent.com/338316/113780504-27d65580-96e4-11eb-8c6a-ab9d865b93d6.png)

This is related to my previous PR https://github.com/celo-org/celo-monorepo/pull/6474 but the ideal solution is to really not use any external non-npm dependencies like that at all.

**Comment by aslawson** [comment]
bummer -- it looks like npm has labeled it as a `bug` so hopefully will get fixed.

agree that we should probably not depend on github urls. this will require us investigating and understanding why those are not published npm packages. but wonder if this workaround will help in the shorterm or if adding some generic `username` would tricker a password prompt 
https://github.com/npm/cli/issues/2610#issuecomment-795189708

**Comment by daffl** [comment]
We downgraded to npm 6 for now. I figured I bring it up as an issue here since I know from my experience that these kinds of dependencies will probably keep causing random problems like this - and even more tricky might create weird version conflicts when the main project uses the actually published packages (e.g. https://github.com/celo-org/celo-monorepo/blob/master/packages/sdk/utils/package.json#L34 has caused us some headaches before).

I did a quick `package.json` scan and it looks like there are only three dependencies in the SDK that would need to be changed, all in the same `@celo/utils` package:

- https://github.com/celo-org/celo-monorepo/blob/master/packages/sdk/utils/package.json#L23
- https://github.com/celo-org/celo-monorepo/blob/master/packages/sdk/utils/package.json#L34
- https://github.com/celo-org/celo-monorepo/blob/master/packages/sdk/utils/package.json#L35

**Comment by aslawson** [comment]
Thanks @daffl!

**Comment by daffl** [comment]
Any update on this? This keeps causing CI and deployment issues for us every time someone forgets to switch to the right (old) Node version when working on any codebase depending on the Celo SDK. I'd love to help but there isn't much that can be done without publishing rights and the reasoning why these dependencies link to a commit instead of the published version.

**Comment by aslawson** [comment]
Hey @daffl -- We are in the final stretches of upgrading everything to Node 12 so that will at least get you off a <10 version
https://github.com/celo-org/celo-monorepo/issues/7084

Node 14 ganache issue is still pending merging ganache changes by our grantee. We are currently at the stage of internally reviewing the changes for this -- I'll check on the the expected timeline for review and whether we should prioritized internal work to make the changes to support node 14 with ganache.

**Comment by daffl** [comment]
The problem for this specific issue is npm 7 (which comes with newer Node versions by default). Other than Ganache for testing we don't have any problems running the SDK on Node 14.

**Comment by aslawson** [comment]
@daffl could this be a solution for the CI issues?
https://github.com/celo-org/celo-monorepo/issues/7852

**Comment by daffl** [comment]
Well I mean then you'd see that it breaks but the solution is what I mentioned above to only use actual published versions from npm and not arbitrary URLs as dependencies.
