### ISSUE TITLE
More intelligent gas price configuration for contractkit

### ISSUE THREAD

**Issue by asaj** [celo-org/celo-monorepo#7630]
### Expected Behavior

The increased load we saw last Thursday gave the Celo network a taste of what high congestion can do to gas prices. Transaction pricing relies on the gas price market to work efficiently; users decide how quickly they want their transaction included, and how much they're willing to pay for that.

However, bad things can happen if the market isn't working effectively, particularly under high load. If everyone were to, for example, always bid the same gas price (e.g. 5x the gas price minimum), this market mechanism would effectively disappear, and users would bid up gas prices to infinity.

Contractkit should support more intelligent gas pricing so that dapp developers can choose more sophisticated gas pricing schemes.

### Current Behavior

Always a multiple of the current gas price minimum

**Comment by barbaraliau** [comment]
Related:
https://github.com/celo-org/celo-monorepo/blob/master/packages/sdk/contractkit/src/kit.ts#L86
https://github.com/celo-org/celo-monorepo/blob/master/packages/sdk/contractkit/src/kit.ts#L225

**Comment by barbaraliau** [comment]
Initial investigation timeboxed to 1 dev day
