### ISSUE TITLE
Contract calls should forward revert reason

### ISSUE THREAD

**Issue by asaj** [celo-org/celo-monorepo#7633]
### Expected Behavior
E.g. in ExternalCall the transaction should revert with the actual reason for debugging purposes

**Comment by yorhodes** [comment]
hey @asaj can you add more context with an example transaction or contract where this happens?
is this core or MTW?

**Comment by yorhodes** [comment]
maybe a good bounty cc @aslawson

**Comment by aslawson** [comment]
could be -- I think I need more clarity from @asaj on where this is happening as well.
