### ISSUE TITLE
yarn build fails

### ISSUE THREAD

**Issue by piersy** [celo-org/celo-monorepo#7660]
### Expected Behavior

It should pass.

### Current Behavior

It currently fails with errors relating to gtibook.

We use `yarn build --ignore docs` to get around this currently.

**Comment by alexreyes** [comment]
I have this problem too. I tried building the Celo test wallet app a couple of days ago and had yarn fail a couple of times so I ended up not continuing.

Would be helpful to put the instructions for getting around it in various places in the documentation. I'd make that PR now, but I'm focusing on my hackathon project at the moment 😄
