### ISSUE TITLE
Wallet backup flow should show social backup options

### ISSUE THREAD

**Issue by drklee3** [celo-org/celo-monorepo#768]
### Expected Behavior

Backup flow provides social backup option along side existing ones:

* Copy to Clipboard
* Write Down
* Send parts of the backup phrase to friends

### Current Behavior

Backup flow only allows the user to write down their backup phrase before the quiz and a copy to clipboard button.

**Comment by annakaz** [comment]
See https://github.com/celo-org/celo-monorepo/pull/965

**Comment by annakaz** [comment]
Seel also https://docs.google.com/document/d/1_Qh9TFV9oNihIzDAgHdJ8PV1l5DRxe6GAkpxZZXxdJg/edit
