### ISSUE TITLE
Evaluate performance impact of multiple Signer replicas

### ISSUE THREAD

**Issue by codyborn** [celo-org/celo-monorepo#7683]
Increase Signer replica per pod and use load tests to measure performance impact

If we do use multiple replicas, make sure that our signer dashboards display them properly.

**Comment by codyborn** [comment]
Sync with @nambrot to see if he found anything from the previous investigation

**Comment by codyborn** [comment]
<Placeholder for Emil>

**Comment by emilhotkowski** [comment]
"Increase Signer replica per **pod**" we want to have multiple signer containers per pod? If so do we want to expose extra service or maybe put some nginx as a third container to do load balancing on the pod itself?

**Comment by emilhotkowski** [comment]
Could we pick some important metrics for me to check?
I would like to run load test from my machine as a baseline but I am not sure which metrics are important from GCP board.

**Comment by codyborn** [comment]
Good question. I've been measuring the following:
Duration (min) | Peak load (RPS) | Combiner instance count (peak) | Error Rate (peak) | Combiner Latency 50% | Combiner Latency 95% | Combiner Latency 99%

I just shared a spreadsheet w/ you that has the previous measurements for comparison.

**Comment by emilhotkowski** [comment]
I've seen this excel, but I have a problem with mapping what there is on GCP dashboard to excel metrics.

**Comment by codyborn** [comment]
Followed up over Slack

**Comment by emilhotkowski** [comment]
Baseline is measured. I will measure again after this PR https://github.com/celo-org/celo-monorepo/pull/8343

**Comment by emilhotkowski** [comment]
Should I investigate what needs to be changed for it to work? Increasing number of replicas generated some errors (probably resource race condition) @codyborn

**Comment by codyborn** [comment]
Yes, please. I'd try locally using `yarn start` or `yarn start:docker` and see if you can repro it.

**Comment by emilhotkowski** [comment]
Probably I still have the same problem with .env decryption since I have some errors while running `yarn start:docker`

>rror: getaddrinfo ENOTFOUND http://localhost\n    at GetAddrInfoReqWrap.onlookup [as oncomplete (dns.js:66:26)(dns.js:66:26)

**Comment by alecps** [comment]
closing this as it's become outdated
