### ISSUE TITLE
Investigate ODIS Signer timeouts 

### ISSUE THREAD

**Issue by alecps** [celo-org/celo-monorepo#7687]
During the CB earn firefighting we saw evidence that the signer timeouts we added weren't working correctly
- Figure out how to test the signer timeouts
- Test the signer timeouts
- If timeouts aren't working, fix them or create a new ticket to do so if it's complicated

Observations from CB earn:
- Express level "backup" timeout is triggering even when the signers return 200, which suggests the process doesn't terminate until well after the response is sent
- We saw some latencies reported above the limit set by the inner-level timeout

**Comment by codyborn** [comment]
Run it locally with an added sleep statement to reproduce this and confirm

**Comment by codyborn** [comment]
We should confirm this is still happening in the logs before further investigation. We've made a decent number of changes that may have fixed this.

**Comment by codyborn** [comment]
Not high priority now since things have been running smoothly. Will re-open if we observe this during the improved load testing.
