### ISSUE TITLE
[Bounty]  celocli governance:show timeUntilStages should be hidden until proposal is dequeued

### ISSUE THREAD

**Issue by asaj** [celo-org/celo-monorepo#7688]
### Issue Title
[Bounty]  celocli governance:show timeUntilStages should be hidden until proposal is dequeued

### Challenge Description

The celocli is a command line tool used to interact with the Celo network. For many governance voters, it is the main tool used for proposing, reviewing, and voting on governance proposals.

The governance:show command provide details of a proposal -- eg. stage in the proposal lifecycle, how many votes it has, ect. Progressing through stages is dependent on timers (started when removing proposal from the queue) and passing criteria (eg. enough approvals or votes). You can learn more about the governance phases [here](url).

Onchain timeUntilStages are inaccurate until proposals are dequeued. Displaying them in the celocli tooling confuses Celo holders and approvers. We should hide this field from the governance:show tool until 

```
timeUntilStages: 
  referendum: past
  execution: 6 days, 21 hours, 7 minutes, 44 seconds
  expiration: 1 week, 2 days, 21 hours, 7 minutes, 44 seconds
```

### Submission Requirements

governance:show should not display the timeUntilStages until the proposal has been removed from the queue.

### Prerequisites

What prerequisite knowledge does this bounty require? What specific topics does someone need to know about before they can start work? Is there setup required before they can begin work? If so, what do they need to do?

### Time Expectation

Given someone has the expected prerequisites and knowledge, what is the expected time investment?

### Category

_Front End, Back end, Design, Documentation or Other_

### Project Type

- *Traditional - One contributor, one person paid*
- *Contest - Multiple people can contribute, one person is paid*
- *Cooperative - multiple people can contribute, multiple people are paid*

### Permissions

- *Approval Required: Bounty hunters should be approved before starting work*
- *Permissionless: No approval required*

### Experience Lever

Beginner, Intermediate or Advanced

### Bounty Type

Bug, Feature, Improvement, Security, Documentation, Design, Code Review, Other

### Expiration

When does this bounty expire? (if applicable)

### Resources

Link any relevant resources (e.g. specific documentation, source code that may be useful)

**Comment by aslawson** [comment]
i think we had agreed to just hide the timings until items were dequeued
