### ISSUE TITLE
Wallet recovery flow should have a social recovery option

### ISSUE THREAD

**Issue by drklee3** [celo-org/celo-monorepo#770]
### Expected Behavior

Wallet recovery flow should have social recovery options.  Related: #768 

### Current Behavior

Wallet only provides user input backup key recovery.

**Comment by annakaz** [comment]
See https://github.com/celo-org/celo-monorepo/pull/965

**Comment by annakaz** [comment]
See also https://docs.google.com/document/d/1_Qh9TFV9oNihIzDAgHdJ8PV1l5DRxe6GAkpxZZXxdJg/edit
