### ISSUE TITLE
Investigate Sourcify as Source for Public ABIs and Contract Verification

### ISSUE THREAD

**Issue by aslawson** [celo-org/celo-monorepo#7700]
- Sourcify client should always compile and verify against the bytecode. Should confirm availability and UX for Celo as a standard.

**Comment by nambrot** [comment]
Can this ticket be closed? I think at this point we are pretty far down the Sourcify route, and as far as I can tell it does work for our requirements? cc @yorhodes @kevjue

**Comment by yorhodes** [comment]
in the long term, sourcify is definitely the right tool for the job
the same team developing the solc compiler develops sourcify
I have reached out on their gitter and am in talks with community members dealing with related issues (see poofcash)

> FabijanC @FabijanC 00:53
> Hey guys, any updates on library linking support? I see this PR has been languishing for a while ethereum/sourcify#105. Anything I can do to help out? Sincerely, a happy customer.
> 
> @yorhodes
> Good research work! We also remembered this PR yesterday while referring to @BriungRi 's issue. 
> Ever since this PR, some people have left the Sourcify team (the author of the PR), and some have joined, so that might at least partly explain why some issues/PRs have lost their initial traction. But now we definitely plan to see if anything from this PR can be used to improve the library linking support.

created https://github.com/celo-org/celo-monorepo/issues/7855 to track this specific requirement
