### ISSUE TITLE
Investigate Feasibility and Confidence methods for Contract Interactions

### ISSUE THREAD

**Issue by aslawson** [celo-org/celo-monorepo#7702]
Output should be an understanding of whether these are things we could do from a technical standpoint. This will inform the Wallet Transaction Confidence initiative.

Existing confidence methods:

- Contract Verification -- contracts deployed match what's been uploaded publicly (eg. Sourcify)
- Reputation of the contract deployer
- Social confidence (X of your friends have interacted with this contract/dapp)
- Auditor signatures -- reputation (eg. trusted third party like cLabs has reviewed the contract/dapp)
- Any are solutions with formal verification? (confirming sendTransaction() actually does what it claims to do)?

**Comment by yorhodes** [comment]
cc @aslawson is this identity or contracts component? any more context to provide would be great

**Comment by aslawson** [comment]
@yorhodes yup this is to have establish a method with which to map contract deployers/dapp developers to forms of identity.

eg. its very unlikely a Valora user would read a contract to understand what its doing. So even if it's been verified on Sourcify, it doesn't give the user much reassurance. Other forms of confidence could come from 

- Reputation of the contract deployer
- Social confidence (X of your friends have interacted with this contract/dapp)
- Auditor reputation (trusted third party like cLabs has reviewed the contract/dapp)

This ticket captures that first item. But I think there's a bit of investigative/design work involved here for what is possible and what would be the best solutions for transaction confidence. Will need a eng to partner on this outlining this as an initiative.

**Comment by aslawson** [comment]
To answer your question, I think it's a bit of both. It's leveraging identity to instill confidence in users interacting with a contract. It will likely include offchain storage (so overall this epic would really touch on all our components)

I'm going to rename Investigate Contract Identity Standards --> Investigate Feasibility and Confidence methods for Contract Interactions

Output being an understanding of whether these are things we could do from a technical standpoint. While I continue to work with wallet stakeholders to understand what is the most valuable.
