### ISSUE TITLE
CeloTxObject has insufficient type for `call`

### ISSUE THREAD

**Issue by zviadm** [celo-org/celo-monorepo#7705]
CeloTxObject is missing some parameters:
* call method needs to accept: 'blockNumber':
https://web3js.readthedocs.io/en/v1.2.11/web3-eth-contract.html#methods-mymethod-call
https://github.com/celo-org/celo-monorepo/blob/4f6c48f196e3e523407306da760a96d62474c1f9/packages/sdk/connect/src/types.ts#L16

This is pretty important to be able to query things at specific block numbers.

**Comment by zviadm** [comment]
cc: @gastonponti

**Comment by gastonponti** [comment]
@zviadm agree

@aslawson @barbaraliau we should take this in count for the next sprint
