### ISSUE TITLE
Celo: <Issue Title>

### ISSUE THREAD

**Issue by ishtark1970** [celo-org/celo-monorepo#7708]
I transferred CELO and never received them. Below you can find a copy of my transaction
0xe7c3a7d1d17f21eae3873a0f143d0a8cbb5819650c2a50ce443ba0b1d38a64ab

0xe7c3a7d1d17f21eae3873a0f143d0a8cbb5819650c2a50ce443ba0b1d38a64ab
0xA203bbF51A5bC4a8A82F8e145D01D0333471D411 → 0xd489c5f58D3dFb16569c93AC21EF27b44C173721
Token Transfer
Success
2 days ago (April-17-2021 06:14:22 AM +-4 UTC)
Block Number
6215617
Block Confirmations
39,490
Nonce
5618
TX Fee
0.0000105 CELO
Fee Recipient
None
Gateway Fee
0
Transaction Speed
2.1 seconds

**Comment by ishtark1970** [comment]
I never received my tokens

**Comment by lynapham** [comment]
I’m having the same issue. Did you ever get it??

**Comment by lynapham** [comment]
Hi. I found a solution and here’s how I got my celo back into my coinbase. Visit https://docs.celo.org/celo-owner-guide/eth-recovery. It’ll tell you how to retrieve it/find urs. Input the recovery code of the wallet that u sent it to, not the one u sent it FROM. That’s how I got mine. Lmk if you have any questions!
