### ISSUE TITLE
Investigate transaction metadata readiness

### ISSUE THREAD

**Issue by codyborn** [celo-org/celo-monorepo#7740]
Sync with @AlexBHarley to understand current state of transaction metadata. If it's ready for prod use, we can use it to signal the Finclusive ID of a user during a cUSD transfer to the Finclusive wallet. If it's not ready, we'll likely create a new API that Valora can call to pass this information out of band.

**Comment by carterqw2** [comment]
Checked with Alex, it won't be ready for prod use for sure. We either have to rely on tx comments or create a new API indeed.
