### ISSUE TITLE
Finclusive CICO Integration Investigation

### ISSUE THREAD

**Issue by codyborn** [celo-org/celo-monorepo#7745]
Set of investigation work to set up the Finclusive integration for CICO.

1. Interface between Finclusive and cLabs (specific details for each API call)
2. Transaction Metadata readiness (start with simple API solution if not ready)
3. Blockchain team’s sign-off that Finclusive can use Forno for tx submission
4. Web Svc team’s sign-off that Finclusive can use Blockscout API for balance monitoring
5. Investigate Valora integration
6. Support Finclusive with adding cUSD liquidity

**Comment by tarikbellamine** [comment]
Closed in favor of: https://github.com/celo-org/wallet/issues/645
