### ISSUE TITLE
[Bounty] Disallow zero value locked celo operations

### ISSUE THREAD

**Issue by yorhodes** [celo-org/celo-monorepo#7758]
### Expected Behavior

`GoldWithdrawn`, `GoldLocked`, `GoldRelocked`, `GoldUnlocked` should not emit when value is 0 (and corresponding operations should be prevented)

`AccountsSlashed`?

### Current Behavior

Locked Celo operations are used to trace internal celo transfers by indexers, which leads to a false positive when value is 0

Discovered by coinbase in rosetta operation
See fix: https://github.com/celo-org/rosetta/pull/160

**Comment by covendev** [comment]
Would be interested in working on this and made the changes suggested in the PR linked above. wanted to know the test cases to be followed and any other contributor guidelines to be followed as this is my first contribution to this repo. Thanks!

**Comment by covendev** [comment]
cc @yorhodes @alecps @aslawson , I have made the changes and linked the PR, but the test was failing for lint step any hints on how to resolve and if any additional changes to be made apart from PR

**Comment by hbandura** [comment]
> cc @yorhodes @alecps @aslawson , I have made the changes and linked the PR, but the test was failing for lint step any hints on how to resolve and if any additional changes to be made apart from PR

The Rosetta PR build fails because the code is not formatted properly
