### ISSUE TITLE
Granda Mento Activation

### ISSUE THREAD

**Issue by tkporter** [celo-org/celo-monorepo#7776]
Activating Granda Mento

**Comment by albertclabs** [comment]
@tkporter should we add some extra work items here for the coming sprint?
- Tracking deployment to testnet? (can be in the implementation epic instead?)
- Setting up testnet multisig and making sure participants can use it
- Deployming mainnet multisig
- Submitting CGP for voting

CC: @yerdua

**Comment by martinvol** [comment]
Activated on Mainnet!
