### ISSUE TITLE
Onboarding Throughput

### ISSUE THREAD

**Issue by aslawson** [celo-org/celo-monorepo#7779]
https://github.com/celo-org/celo-monorepo/commit/0a0dcbde601a828891b320201f56334f34199b51

Onboarding (including verifications with 3 attestations) is very expensive (cost ~1M gas) resulting in a low throughput for onboarding.

There a few known optimizations which can collectively ~double our throughput (which will have greater impact as we scale our block gas limits)
```
Now - 5.8/block = 1.16/sec (69.6/min)
EIP-1167 - 8.3/block = 1.66/sec (99.6/min)
+Pooled Proxy - 9.3/block = 1.86/sec (111.6/min)
+Optimized Proxy & ASV2 - 14.1/block = 2.82/sec (169.2/min)
```

**Comment by alecps** [comment]
out of date
