### ISSUE TITLE
Users SBAT read better docs to understand proof of stake protocol

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-monorepo#780]
### Expected Behavior

Update date documentation to include:
- [ ] Proof of stake explanation
- [ ] Proof of stake numbers
- [ ] Proof of stake terms in glossary

### Current Behavior

No documentation exists.

**Comment by diminator** [comment]
closed by #1800

**Comment by nategraf** [comment]
Fixed by https://github.com/celo-org/celo-monorepo/pull/2022
