### ISSUE TITLE
Add events when user successfully(or not) adds funds to their account

### ISSUE THREAD

**Issue by ole-nov** [celo-org/celo-monorepo#7840]
**Why is this important?**
Atm we don't have visibility of the conversion rate of our payment providers and can't do data-driven decisions about which of them provide better experience for the users

**What is done?**
One of the following events should be triggered when a user comes to the app from the cash in provider:
`cico_add_funds_success` // when user successfully added funds to their account
`cico_add_funds_error` // when the user wasn't able to add funds (not sure if it is possible to track it at all)

Next parameters should be added to this event on top of default parameters defined in [this issue](https://app.zenhub.com/workspaces/wallet-backlog-board-60092d006a84e3001d0d5936/issues/celo-org/wallet/305):
```
provider:
fiatCurrency
coinType:
dollarAmount:
errorType:
paymentMethod
```

**What is involved in doing this work?**

**Comment by tarikbellamine** [comment]
Closed in favor on #360
