### ISSUE TITLE
HOGLers SBAT see more locked gold info including rewards via CLI

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-monorepo#786]
Voters in validator elections should be able to understand the history of their epoch rewards. Currently, there is no way to do so, other than examining their locked gold info before and after the last block of an epoch. This can get muddled if the user made a transaction in that block that would affect this information, e.g. activating additional votes.

We should have a command, e.g. `rewards:show` that will print out the history of rewards for a particular address. This information can be gleaned from the events emitted in block finalization.

Validator/group payments should be relatively straightforward to figure out from the events, rewards to voters may require a bit more work.

**Comment by diminator** [comment]
I can take this if there's a bit more explanation
