### ISSUE TITLE
Micro-dapps

### ISSUE THREAD

**Issue by aslawson** [celo-org/celo-monorepo#7861]
A suite of microdapps that demonstrate how to do key functionality in the Celo ecosystem. Will demonstrate how to do each action via popular wallets (leveraging use-contractkit wallet model) and directly onchain.

This will serve as both reference to dapp/wallet developers, as well as highlight where we are lacking standardized/accessible solutions.

Ideally, these dapp could be collated into a storybook-like user interface (versel) that enables developers to engage with each example and be directed to the codebase.

- [ ] transactions
- [ ] mento exchange
- [ ] individual phone number read/write
- [ ] access contacts
- [ ] escrow
- [ ] staking
- [ ] voting
- [ ] metadata read/write (eg. profile pictures, phone number type detection)

**Comment by bejarano-tech** [comment]
Hi Amy, i want to work on this issue, can you tell me how to start, please?

**Comment by barbaraliau** [comment]
Hi @bejarano-tech! We're going to be breaking this up into multiple smaller issues; when that happens it'll be easier to get started. Was there one you were more interested in working on? We'll probably be having one person lead this, but they may like some assistance.

**Comment by bejarano-tech** [comment]
Hi @barbaraliau, thanks for your response. I would like to collaborate with transactions :)
