### ISSUE TITLE
Investigate operational complexity of running DRAND software with ODIS operators 

### ISSUE THREAD

**Issue by alecps** [celo-org/celo-monorepo#7868]
Background
There has been[ some discussion ](https://www.notion.so/clabsco/Randomness-Beacon-Discussion-May-6th-and-10th-a2b80154d5634bfe9657adbf2c2d7694) around using ODIS as a randomness beacon. One way to do this would be to somehow incorporate the existing DRAND software into ODIS.

Output
Determine how we might add DRAND to ODIS and roughly how much work it would be. Investigate the pros and cons of this approach and its overall feasibility.

**Comment by codyborn** [comment]
TODO after we hear back from @kobigurk on feasibility of using DRAND beacon on Celo. If we can use DRAND natively, then we can avoid needing to perform this investigation in the first place.

**Comment by codyborn** [comment]
It seems unlikely that this is an option at this point. We will revisit after having more conversations w/ DRAND.
