### ISSUE TITLE
Sync with crypto team to add DEK signing/blinding to ODIS requests

### ISSUE THREAD

**Issue by alecps** [celo-org/celo-monorepo#7879]
See https://www.notion.so/clabsco/ODIS-Replay-Handling-dc41b91e61fc4aff97e05679f65153b2

**Comment by alecps** [comment]
Synced with Kobi and added this ticket to track implementation support work on the crypto team side https://app.zenhub.com/workspaces/celo-5d94ef61d9b1e40001114c02/issues/celo-org/celo-monorepo/7950

**Comment by aslawson** [comment]
Related:
#7950

#7957
