### ISSUE TITLE
Node operators SBAT reference troubleshooting guide

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-monorepo#788]

**Comment by clrblmt** [comment]
[Developer & Validator FAQ](https://docs.google.com/document/d/1l3hqhVBvw7PHNAtQ6vOfXDTEs-95lJ82Ne1J_XT0-Q0/edit?usp=sharing)

**Comment by clrblmt** [comment]
Posted on Celo Forum: https://forum.celo.org/t/setting-up-a-validator-faq
