### ISSUE TITLE
Issues with payments greater than $1000 in the disbursement tool

### ISSUE THREAD

**Issue by carterqw2** [celo-org/celo-monorepo#7883]
**Description**
There is an error when people try sending amounts greater than $1k (1,000 cUSD value) in the Disbursement Tool.

```
Invalid BigNumber string (argument="value", value="3e+21", code=INVALID_ARGUMENT, version=bignumber/5.0.14)
```

The user was able to add the amounts manually but encountered the same error when submitting through the UI.

**Comment by eruizgar91** [comment]
This is fixed here https://github.com/celo-org/celo-multisend/tree/dissendi
