### ISSUE TITLE
Deploy T&C page for invite rewards

### ISSUE THREAD

**Issue by jbsibille** [celo-org/celo-monorepo#7898]
This page will be linked to from the app, but no where else.
It should be hosted on valoraapp.com
It will be available in several languages. The default language for people opening the page should be their phone's language. 

Current EN draft is here: https://docs.google.com/document/d/1NHD6EJM9sygFSqK2yR-mecVh3TroL3KSvkWE6KkM2Ss/edit# 

For inspiration, this is a previous T&C Page we did for the previous celo rewards program: https://website-staging-dot-celo-testnet.wl.r.appspot.com/celo-rewards-terms-and-conditions

We'd love to keep the same layout

In app-experience: https://www.figma.com/file/DL6Huw867n1EZOVPJ2kNmp/Invite-Rewards-(Updated)?node-id=1%3A55 (these T&C will live on the screen that says “Terms and Conditions”)

Design: https://valoraapp.com/terms 
Goal: 300,000 installs on Valora, want to make some clusters with users, not trying to be flashy but use as a test. This page is meant to be terms & conditions page.

**Comment by laurencedelisle** [comment]
Moved here: https://app.zenhub.com/workspaces/webfront-600f094ea5c674000fbcffd0/issues/clabs-co/valora-website/103
