### ISSUE TITLE
Deploy T&C for Save

### ISSUE THREAD

**Issue by jbsibille** [celo-org/celo-monorepo#7899]
Current draft: https://docs.google.com/document/d/1UUOz2-naZ8664sspQWP3AzEcWN3LaFpcT5eKNWkdWPo/edit# (pending legal review and translations)

SHould be hosted on celo.org

It will be available from the app (the celo save details page), cf designs here: https://www.figma.com/file/31HUGhIHLXEm1qwVpHV1QR/CELO-Rewards?node-id=1442%3A0

The language should be the language of the phone

**Comment by laurencedelisle** [comment]
Moved here: https://app.zenhub.com/workspaces/webfront-600f094ea5c674000fbcffd0/issues/celo-org/website/195
