### ISSUE TITLE
Generic Attestations Contract Changes

### ISSUE THREAD

**Issue by alecps** [celo-org/celo-monorepo#7911]
The Attestations contract currently stores attestations in a format that is specific to on-chain identifiers. That is, the data of the Attestations contract is keyed by indentifier and assumes that attestations can only map identifiers to accounts. 

A Generic Attestation protocol should support attestations for non-identity based claims. While these claims can be stored off-chain, **we need an on-chain record of the selected issuers for a given attestation that is generic**

**Comment by alecps** [comment]
The Attestations contract currently stores attestations in a format that is specific to on-chain identifiers. That is, the data of the Attestations contract is keyed by indentifier and assumes that attestations can only map identifiers to accounts. 

A Generic Attestation protocol should support attestations for non-identity based claims. While these claims can be stored off-chain, **we need an on-chain record of the selected issuers for a given attestation that is generic**

**Comment by codyborn** [comment]
WIP
https://www.notion.so/clabsco/Trusted-Issuer-Attestations-Protocol-f6aa3f9debde498d8f5f4376a5f7e2bd

**Comment by 0xarthurxyz** [comment]
@alecps Closing this ticket because it's partially included in the work of the ASv2 MVP (#8588) and can be re-opened in the future if necessary.
