### ISSUE TITLE
Investigate enabling Account -> Attestations lookup 

### ISSUE THREAD

**Issue by alecps** [celo-org/celo-monorepo#7913]
As we rethink the way that attestations are stored on-chain, we should consider the potential benefits of indexing attestations by account to enable Account -> Identifier lookup and other use cases

**Comment by nambrot** [comment]
Discussed offline, but it would be useful if this can be assessed in the context of the greater proposal, as a claim could always be passed in to lookup the attestations? I.e. what is the use case here?

**Comment by codyborn** [comment]
I was thinking more about this yesterday. Assuming all identifiers are obfuscated with ODIS, the reverse mapping doesn't do you much good. A client can keep track of the identifiers they are aware of (contacts) and create an off-chain reverse lookup mapping. The on-chain reverse lookup is convenient, but the chain state cost probably doesn't justify it.

For Sybil resistance cases, we can assume the user will pass relevant information in real time (ex. identifier) to the verifier.

**Comment by alecps** [comment]
Agreed. Also, now that I know a bit more about CIP8 it's clearer to me that would be the correct place to store a list of attestations for a given account
