### ISSUE TITLE
Generic Attestations

### ISSUE THREAD

**Issue by alecps** [celo-org/celo-monorepo#7914]
This epic encapsulates all work related to generalizing the attestation protocol to support adding new kinds of attestations (i.e. Phone-Number type, discord handle, social media accounts, preferred payment currency etc). See brainstorming doc here.
https://www.notion.so/clabsco/Generic-Attestations-Brainstorming-f6aa3f9debde498d8f5f4376a5f7e2bd

This is an extension of the work started in the epic https://app.zenhub.com/workspaces/cap-backlog-board-600598462807be0011921c65/issues/celo-org/celo-monorepo/7540

**Comment by 0xarthurxyz** [comment]
Closing this epic (having closed and reviewed the tickets in it) because the work is very similar to the ASv2 smart contract design and this epic can be re-opened in the future if necessary.
