### ISSUE TITLE
Node 10 Deprecation

### ISSUE THREAD

**Issue by codyborn** [celo-org/celo-monorepo#7930]
https://nodejs.org/en/about/releases/

Node 10 is reaching end of life and should be replaced by the current LTS version (v14).

We need to update the Attestation Service and ODIS dockerfiles to change the base image to a newer version of Node. Example:
https://github.com/celo-org/celo-monorepo/blob/master/dockerfiles/attestation-service/Dockerfile#L1

**Comment by codyborn** [comment]
Let Prasanna Gautam (prasanna@anchorlabs.com on Slack) know when this has been updated.

**Comment by alecps** [comment]
We should probably upgrade to node 12 rather than node 14 as that is what the rest of the monorepo has recently been upgraded to.

**Comment by alecps** [comment]
Versions bumped in this PR https://github.com/celo-org/celo-monorepo/pull/7955

Remaining work is to 
(1) determine whether we need to push this change out to prod immediately
(2) If so, coordinate releasing a new version of ODIS and AS
