### ISSUE TITLE
Review the Factory's feeToSetter TimeLock contract deployment

### ISSUE THREAD

**Issue by kevjue** [celo-org/celo-monorepo#7935]
Ubeswap's factory deployment's `feeToSetter` state variable is set to a [timelock smart contract](https://repo.sourcify.dev/contracts/full_match/42220/0x1BDB37DAA42E37bFCa4C5536AcF93b1173588981/sources/).

I looked at the code, and from an initial review it looks ok.   However, there probably should be a more thorough review and some consideration of how thorough.

This state variable will be able to set which address gets the 5 basis point fee.  Note that this fee doesn't affect any of the liquidity deposited to the  liquidity pool.

**Comment by nambrot** [comment]
@kevjue what urgency would you give this?
