### ISSUE TITLE
Metamask instructions should programmatically link a user's wallet

### ISSUE THREAD

**Issue by codyborn** [celo-org/celo-monorepo#7948]
https://docs.celo.org/getting-started/wallets/using-metamask-with-celo/programmatic-setup

We should setup a simple celo.org site that users can leverage to create the custom network and add the tokens. We can link the user to this site as an option instead of manual setup.

**Comment by aslawson** [comment]
Dev Rel -- TODO find Prestwich's URL

**Comment by aslawson** [comment]
https://prestwich.github.io/celo-metamask-page/

**Comment by aslawson** [comment]
closing in favor of https://app.zenhub.com/workspaces/identity-sprint-board-61015de9a849530010b49fc6/issues/celo-org/celo-monorepo/8542
