### ISSUE TITLE
Merge InitializableV2 and Initializable and adopt across core contracts

### ISSUE THREAD

**Issue by yorhodes** [celo-org/celo-monorepo#7962]
### Expected Behavior

All core contracts inherit from `Initializable` with implementation constructor

### Current Behavior

Some contracts inherit from `Initializable` and some from `InitializableV2`

**Comment by nambrot** [comment]
Are you saying we should do this as part of the audit 5 response?

**Comment by yorhodes** [comment]
Yes, I think we should avoid any further complications from Initv2
