### ISSUE TITLE
Add local signing support for Attestation Service

### ISSUE THREAD

**Issue by aslawson** [celo-org/celo-monorepo#7971]
This change would allow validators to sign attestation requests and point requests to their validator proxy rather than running a separate full node. The validator proxy would more likely be up to date (and validators are incentivized to ensure they are consistently synced)

Discord alerts indicate that nearly all unhealthy attestation cases are due to `Node is not synced`  or `Node is not up to date`

And if sorting issuers by counts of unhealthy cases, top offenders are all the top in the `Missed Attestations` table. we can assume with high probability that full node syncing is a large piece of attestation service failures and thus SMS delivery failures.

This may also cause slower SMS deliveries as requesters wait for full node sync.

**Comment by eelanagaraj** [comment]
Remaining time: deploying + testing to Alfajores (after changes to node fallback, which is captured in a separate ticket)
