### ISSUE TITLE
Complete Scoping of Attestation Protocol Redesign to Support New Identity Types

### ISSUE THREAD

**Issue by aslawson** [celo-org/celo-monorepo#7973]
Complete [Attestation protocol design proposal](https://www.notion.so/clabsco/Trusted-Issuer-Attestations-Protocol-f6aa3f9debde498d8f5f4376a5f7e2bd) to include changes needed to the contract and the downstream impacts to Komenci/Valora.

This work may or may not be needed for sybil resistance work with VOIP detection (dependent on whether we need backfill support for already mapped numbers) #7536 .

This work is blocking decisions around whether to batch attestation contract changes with #7872

**Comment by codyborn** [comment]
Setting a higher priority (P2) due to the fact that it's blocking the other Attestation.sol contract changes

**Comment by codyborn** [comment]
Per this [Slack thread](https://celo-org.slack.com/archives/C022H5JUFNZ/p1621545717000100) the additional Attestations.sol changes aren't critical so lowering the priority of this.

**Comment by 0xarthurxyz** [comment]
Closing this ticket because we implicitly worked on scoping the redesign during the NYC offsite (#9059) and the current prioritisation of the "**ASv2 MVP**" (#8588).
