### ISSUE TITLE
[L02] Extraneous Events

### ISSUE THREAD

**Issue by yorhodes** [celo-org/celo-monorepo#7988]
Many functions in the `Accounts` contract complete successfully and emit extraneous events when there is no operation to be performed. For example, it’s possible to [authorize a signer](https://github.com/celo-org/celo-monorepo/blob/f64b4c5b5228ecbf41e3e7cfdbb8c0e9a983eea2/packages/protocol/contracts/common/Accounts.sol#L273) that already exists or [remove a signer](https://github.com/celo-org/celo-monorepo/blob/f64b4c5b5228ecbf41e3e7cfdbb8c0e9a983eea2/packages/protocol/contracts/common/Accounts.sol#L559) that doesn’t exist. In such cases, the emitted event will not correspond to any executed action, which may intefere with offline processing. Consider validating that the contract state has changed before emitting events.

**Comment by AlexBHarley** [comment]
We've decided to mark this as "won't-fix". 

1. Extraneous events should be considered no-ops from the perspective of indexing the chain
2. The current behaviour is consistent with the other setters (e.g.`setName`, `setMetadataURL`, etc) in our `Accounts.sol` contract
3. Calls to authorise signers remain idempotent which is a desirable and correct
