### ISSUE TITLE
[N04] Simplify identity heuristic calculation

### ISSUE THREAD

**Issue by yorhodes** [celo-org/celo-monorepo#7998]
The passesIdentityHeuristic function of the IdentityProxyHub contract evaluates multiple independent conditions, including a compound condition, and then evaluates whether or not they are all satisfied. For simplicity, consider returning immediately when any of the conditions fail. This would make the function easier to reason about, and would also increase efficiency.

**Comment by nategraf** [comment]
Created PR to address this comment https://github.com/celo-org/celo-monorepo/pull/8016

I considered splitting out the rules into multiple functions, but decided that it would not greatly improve readability. I've added some more comments to mark each of the three rule checks both in the doc string and in the function body. 

Additionally, I've added a note on why we choose not to return early on a rule failure: To avoid extra conditional checks and (mildly) optimize for the passing case, at the expense of the failing case. This was suggested in the following PR comment https://github.com/celo-org/celo-monorepo/pull/7363#discussion_r614428367
