### ISSUE TITLE
Publish CELOBTC pricing in Alfajores oracle

### ISSUE THREAD

**Issue by albertclabs** [celo-org/celo-monorepo#8000]
### Expected Behavior

- New CELO/BTC price feed is published on Alfajores
- Contract is verified
- Public and devs are aware of how to interact with this feed. Short post to Discord?

### Current Behavior

CELO/BTC price not supported in our Oracles. Us and the greater ecosystem cannot calculate what the Bitcoin price is and are unable to unlock advanced use cases of Bitcoin-like products.

Impact: Dapps like Moola will be able to price BTC and enable greater functionality for Celo users such as lending/borrowing of wrapped BTC.

Open questions:
- Additional cost to Oracles?
- Can we bundle this with implicit pairs work?

**Comment by nvtaveras** [comment]
Done, CELO/BTC oracles are now up on Alfajores and reporting. Here's a short write up on the oracle specs, including an example gist on how to interact with the oracles through contractkit:

https://docs.google.com/document/d/1XhRpomBhUSVFfsC3THxWVsLXsJ7MVkRKWJU9sFt7LbI/edit
