### ISSUE TITLE
Investigate making cLabs (komenci) relay service more generic for account recovery

### ISSUE THREAD

**Issue by kevjue** [celo-org/celo-monorepo#8002]
1) Make the komenci relayers be able handle all txns (not just attestation ones).  This looks to be really easy.
2) See how to modify the relay service to be able to handle different payers that reimburse txn fees.  Right now, it's not really clear on whether Valora will pay for it or another source (e.g. the MTW itself).

**Comment by kevjue** [comment]
TBH, I'm actually not sure if the CAP team is the right one?  E.g. does it own Komenci/Relayers?

**Comment by yorhodes** [comment]
cc @dave-carroll7 for intern project
