### ISSUE TITLE
Document Error Codes from Attestation Services for Clients

### ISSUE THREAD

**Issue by aslawson** [celo-org/celo-monorepo#8022]
We should document error codes and possible causes/suggests of what clients might want to do in response.

Eg. currently Valora requests a new issuer when it receives'Delivery attempts exceeded', 422. Other errors such as 401: "Invalid signature" are more unclear to the Valora team and will likely be so for other clients.

**Comment by alecps** [comment]
https://github.com/celo-org/celo-monorepo/blob/ed029419d75b52b04cfce65658ac669530af68a9/packages/attestation-service/README.md
