### ISSUE TITLE
Contract source code verification in retrospect

### ISSUE THREAD

**Issue by ghost** [celo-org/celo-monorepo#8025]
### Expected Behavior

- We should be able to verify contracts in retrospect, after they got deployed or automatically verify contracts upon deployment
- Example contract that I couldn't get verified even with looking deeper into it is ExchangeEURProxy.sol: https://explorer.celo.org/address/0xe383394b913d7302c49f794c7d3243c429d53d1d/transactions

### Current Behavior
- It's very hard or impossible to rebuild the metadata locally for an exact match with the deployed bytecode on-chain as truffle hashes absolute filepaths into the bytecode
- If you're not the original migrator of a contract, and don't know the exact folder structure of the migrator, and they used truffle to generate the artefacts (so the absolute file paths are embedded in the metadata and hashed into the bytecode), and they haven't verified it themselves - there is no way to compile it yourself such that your locally build metadata matches the deployed bytecode on-chain

**Comment by ghost** [comment]
Related: https://github.com/ethereum/sourcify/issues/27 and https://github.com/ethereum/sourcify/issues/24

**Comment by ghost** [comment]
Related: https://github.com/trufflesuite/truffle-compile/issues/77

**Comment by aaronmboyd** [comment]
Note this is _mostly_ a Truffle-specific issue. If the original migrator used hardhat or even generates metadata manually this is not a problem.

I realise now the old issue 77 under `truffle-compile` is a deprecated repository and no longer maintained. The new version is `trufflesuite/truffle` and there is a replacement issue covering the same thing: https://github.com/trufflesuite/truffle/issues/1621, but it is definitely stale.

More importantly, there is a larger conversation going on with the Solidity compiler related to removing absolute paths for many reasons, including non-deterministic swarm hashes in compiled bytecode: https://github.com/ethereum/solidity/issues/11410

**Comment by yorhodes** [comment]
We can resolve this by migrating our internal release tooling to Hardhat but it is difficult to prioritize https://github.com/celo-org/celo-monorepo/issues/8118

**Comment by aaronmboyd** [comment]
@yorhodes This has been resolved by truffle team, no need to migrate to hardhat - https://github.com/trufflesuite/truffle/issues/4119

It looks like with this merge: https://github.com/trufflesuite/truffle/pull/4137 the project root will be noted as `project://` instead of the entire absolute file path on the machine you build/migrate with.

@carterqw2 This will simplify the Blockscout verification explainer documentation significantly. We should both update the default truffle version for all Celo contracts going forward to utilise this fix.

**Comment by yorhodes** [comment]
unfortunately many of the deployed core contracts will forever be associated with this absolute path metadata unless they are upgraded
definitely great to hear that future deployments do not have to suffer from this limitation

**Comment by carterqw2** [comment]
That's nice, thanks for the update @aaronmboyd!
