### ISSUE TITLE
Implement ODIS API for domain-restricted queries

### ISSUE THREAD

**Issue by nategraf** [celo-org/celo-monorepo#8045]

**Comment by nategraf** [comment]
Once the design is reviewed, we will need to implement the API and basic rate limiting functions for the domain-restricted OPRF https://github.com/celo-org/celo-monorepo/issues/7249

**Comment by alecps** [comment]
Will close in favor of epic https://app.zenhub.com/workspaces/identity-backlog-board-60e61301c3dc55000e540b61/issues/celo-org/celo-monorepo/8622
