### ISSUE TITLE
Update use-contract Kit Modal with Link to Metamask Docs

### ISSUE THREAD

**Issue by aslawson** [celo-org/celo-monorepo#8063]
Designs https://www.figma.com/file/U1Xd3uOPGFfcZnYeLMhx0o/Connect-Wallet-Modal-for-dApps?node-id=1%3A3

![Screen Shot 2021-06-23 at 4.01.25 PM.png](https://images.zenhubusercontent.com/5f88e3cee9099f064e26aa70/2bd9f916-168a-4ce5-bd19-3627869f0257)

![Screen Shot 2021-06-23 at 4.03.25 PM.png](https://images.zenhubusercontent.com/5f88e3cee9099f064e26aa70/0e459974-7c15-48fe-b6e1-dd3e0c7914e2)

**Comment by AlexBHarley** [comment]
https://celo-org.slack.com/archives/C0134SBQTQR/p1622823239009600
