### ISSUE TITLE
Celo Minting: Formalizing and summarizing community feedback

### ISSUE THREAD

**Issue by yerdua** [celo-org/celo-monorepo#8074]
DOD:
- Forum post is enhanced with some narrative and framing
- Legal has reviewed forum post about inflation/minting
- Governance forum post created about inflation/minting topic
- Cross post to Discord / Reddit about the discussion to drive participation
- At least 1 week of feedback from and discussion with community
- Summary of discussion and feedback either in this ticket, our economics channel, or a lengthier doc 

Reference: [Forum post draft ](https://docs.google.com/document/d/1Rrs_iAr_421vtLRqSiB7fhs4gKKMh-aSptmuBRXnL7A/edit?usp=sharing)

**Comment by ghost** [comment]
Community discussion summary: https://docs.google.com/document/d/1AWjhW8sGYeGI-ktgy79C6smS2rRxCFxNnYfqKsw4lMc/edit?usp=sharing
