### ISSUE TITLE
[Attestation Service] Improve SMS Coverage and SMS Providers

### ISSUE THREAD

**Issue by codyborn** [celo-org/celo-monorepo#8080]
## Context

This epic serves to coordinate our efforts (among others): 

- to improve our **SMS country coverage** for the `phone number` verification flow
- to coordinate investigations into country-level **success rates**

## Previous Epics

Previous **epics** relating to "_SMS Coverage and SMS Providers_":

- [[Attestation Service] Measure and Improve SMS Carrier Success Rate#7369](https://app.zenhub.com/workspaces/identity-backlog-board-60e61301c3dc55000e540b61/issues/celo-org/celo-monorepo/7369)

## Housekeeping

@arthurgousset: Check if I can close

- [x] [Switch to Verify API for SMS Providers#7947](https://github.com/celo-org/celo-monorepo/issues/7947#issuecomment-939023080) 
- [x] [Investigate design for wallet support for Verify API#8081](https://github.com/celo-org/celo-monorepo/issues/8081#issuecomment-939033860)

**Comment by 0xarthurxyz** [comment]
@codyborn: I'm repurposing this **Epic** to coordinate our SMS country coverage efforts and investigations. Please ping me if this is not ok (i.e. I'm breaking something).

**Comment by 0xarthurxyz** [comment]
Added tickets documenting @eelanagaraj's work on: 

- feature: **local signing** (via keystores)
- feature: **fallback node** support
