### ISSUE TITLE
Investigate design for wallet support for Verify API

### ISSUE THREAD

**Issue by codyborn** [celo-org/celo-monorepo#8081]

**Comment by codyborn** [comment]
See #7947 for details.

**Comment by codyborn** [comment]
Only needed for Nexmo since we found workarounds for Twilio + MB. Will measure results of Twilio + MB first and prioritize this accordingly.

**Comment by 0xarthurxyz** [comment]
@codyborn: With the `Attestation Service 1.3.1` release we support the Twilio VerifyAPI.

- [x] Can we close this ticket (?) with the view that:

1. we're monitoring the Twilio impact and this is only needed for Nexmo (as you [mentioned above](https://github.com/celo-org/celo-monorepo/issues/8081#issuecomment-886264753)) 

> Only needed for Nexmo since we found workarounds for Twilio + MB. Will measure results of Twilio + MB first and prioritize this accordingly.

2. we can create new tickets for the Nexmo Verify APIs as and when needed.
