### ISSUE TITLE
Catch up on existing payments work

### ISSUE THREAD

**Issue by AlexBHarley** [celo-org/celo-monorepo#8092]
A little bit of an open ended ticket but I just want to make sure this work is captured. 

- Read through all the [offchain storage](https://www.notion.so/clabsco/Off-Chain-Storage-ef29ec7756304e5caceb1298f29a9695) documents
- Take a look at the [payments integration proposal](https://www.notion.so/clabsco/Payments-Integration-Proposal-aadd8b6afe7a4f71a32e55fe10eccdb0) and the deprecated option
- Join the slack [#eng-transaction-metadata](https://celo-org.slack.com/archives/C021YPA3H98)

**Comment by medhakothari** [comment]
Was able to start taking a look! can continue to do so this week
