### ISSUE TITLE
ContracKit LocallySigned Setup SN fetch every single block

### ISSUE THREAD

**Issue by mcortesi** [celo-org/celo-monorepo#810]
### Expected Behavior

By looking at https://github.com/MetaMask/web3-provider-engine/blob/master/index.js
it seems that the ProviderEngine we use for locally signed transaction is constantly polling for new blocks, and getting the full block, thus totally suboptimal when we are using a ultralight client; since we'll get every block.

We should investigate why this behaviour and if this can be avoided. I don't know why ProviderEngine does this.

**Comment by mcortesi** [comment]
@asaj fyi

**Comment by ashishb** [comment]
@mcortesi We are planning to use Http provider for the hosted node setup. Afaik, web3 will not maintain an ongoing connection and blocks won't be auto-fetched in that case. Is this issue still a concern for that case?

**Comment by mcortesi** [comment]
I think is important to get done; so i wouldn't close it. But we can deprioritize it for now

**Comment by mcortesi** [comment]
Either way doesn't look that complex to do
