### ISSUE TITLE
Define the list of metrics we want to track

### ISSUE THREAD

**Issue by bowd** [celo-org/celo-monorepo#8111]
### Overview

As part of the "change and observer" action plan for Celo inflation, we need to ensure that we have access to all the metrics we need to make informed decisions on the state of the network.

During our initial exploration we've used [this script ](https://github.com/celo-org/economics-scripts/blob/main/celo-minting-data-scraper/scrape.ts#L36-L58) as a quick way to access the relevant data. We will use this as a starting point to define the list of metrics we want to track and have access to in metabase going forward.

| Column | Type | Description | Status |
| -------- | ----- | ----------- | ----------------- |
| epoch | int | The epoch number | Can be derived |  
| timestamp | int | Timestamp of the epoch | Can be derived |
| validatorRewards | bigint | Validator rewards distributed in that epoch | [Can be extracted from events](https://github.com/celo-org/eksportisto/blob/master/monitor/main.go#L402-L405) |
| voterRewards | bigint | Voter rewards distributed in that epoch | [Can be extracted from events](https://github.com/celo-org/eksportisto/blob/master/monitor/main.go#L402-L405) |
| communityFund | bigint | Community Fund rewards distributed in that epoch | [Can be extracted from events](https://github.com/celo-org/eksportisto/blob/master/monitor/main.go#L402-L405) |
| carbonOffsetFund | bigint | Carbon Offset Fund rewards distributed in that epoch | [Can be extracted from events](https://github.com/celo-org/eksportisto/blob/master/monitor/main.go#L402-L405) |
| reserveCeloBalance | bigint | Celo balance of the reserve  | [Available](https://github.com/celo-org/eksportisto/blob/master/monitor/reserve.go#L42) |
| totalLockedCelo | bigint| Amount of locked celo | [Available](https://github.com/celo-org/eksportisto/blob/master/monitor/lockedGold.go#L37) |
| totalNonvotingLockedCelo | bigint| Amount of non-voting locked celo | [Available](https://github.com/celo-org/eksportisto/blob/master/monitor/lockedGold.go#L29) |
| totalVotingLockedCelo | bigint | Amount of voting locked celo | `totalLockedCelo - totalNonvotingLockedCelo` |
| voitngCeloFraction | bigint | Fraction of celo voating |  `totalVotingLockedCelo / (totalCeloSupply - reserveCeloBalance)` | 
| totalCeloSupply | bigint | Total amount of minted celo | [Available](https://github.com/celo-org/eksportisto/blob/master/monitor/celoToken.go#L47) |
| targetTotalCeloSupply | bigint | Target minted celo according to schedule | [Available](https://github.com/celo-org/eksportisto/blob/master/monitor/epochRewards.go#L31) | 
| targetVotingYieldTarget | int | TargetVotingYield parameter | Not available |
| targetVotingYieldMax | int |  TargetVotingYield parameter  | Not available |
| targetVotingYieldAdjustmentFactor | int | TargetVotingYield parameter | Not available |
| rewardsMultiplier | int | Multipler that scales epoch rewards | [Available](https://github.com/celo-org/eksportisto/blob/master/monitor/epochRewards.go#L52) |
| rewardsMultiplierOverspend | int | Overspend adjustment factor | Not available |
| rewardsMultiplierUnderspend | int | Underspend adjustment factor | Not available |
| rewardsMultiplierMax | int | Max rewards multiplier value | Not available |

**Comment by ghost** [comment]
@bowd nice table. votingGoldFraction is adjusted for the reserve CELO balance, so it's: votingCeloFractionFraction = totalVotingLockedCelo/ totalCeloSupply - reserveCeloBalance. I changed that at some point in the script. Other than calculating it, the metric is also available from the EpochRewards contract as `ctx.epochRewards.methods.getVotingGoldFraction()`

**Comment by ghost** [comment]
Also thought about which variables are fixed. I think targetVotingYieldMax, rewardsMultiplierOverspend, rewardsMultiplierUnderspend, rewardsMultiplierMax are fixed. Would it make sense to reduce the data set ? Monitoring the fix parameters does not make a lot of sense, only if we would like to draw the maximum lines for some parameters in the metabase dashboard. We could discuss about that, otherwise I see no value right now in pulling them. @bowd

**Comment by ghost** [comment]
I take my last comment on variables with a fixed value back. Might be helpful for future analysis on the topic, I guess it doesn't come at a high cost to pull them with.

**Comment by bowd** [comment]
> Other than calculating it, the metric is also available from the EpochRewards contract as `ctx.epochRewards.methods.getVotingGoldFraction()`

We need to figure out a trade-off here. The way things work with `eksportisto` as far as I uncovered implies that it's not feasible to run data collection from the beginning of the chain anymore. This means that if we do change the schema to include this value as a _view call_ to that function, we will only have it from the point where we deployed the new version of eksportisto. But if we instead derive this value from metrics eksportisto has already been reporting, we can add this at the "SQL view" level. The problem with this approach is that we're re-implementing logic from the contract in the analytics layer, but I think the chance of that calculation changing is pretty small.

 > I take my last comment on variables with a fixed value back. Might be helpful for future analysis on the topic, I guess it doesn't come at a high cost to pull them with.

I also think having the values exposed is useful, and here we fall into the same trap as before, where we can't really re-run the logic on the full chain, but I think we can fake it by coalescing with the know historical value when computing the views, and because the historical value is static we can get away with that pretty easily.

--- 

On a meta note, we started this task from the general point of view of "let's make an exhaustive list of what to track", but after diving deeper into the specifics of our current data pipeline some limitations reared their ugly head. But from the looks of it I think we can get away with deploying eksportisto onto the existing schema (i.e. as an upgrade) and start tracking the additional columns only from the upgrade block onwards in the BigQuery collection, and then when we [implement the view](https://app.zenhub.com/workspaces/platform-economics---sprint-board-5f89a1e34ce1b6001230771d/issues/celo-org/celo-monorepo/8114) we can use some SQL magic to either backfill with static values, or derive metrics when possible.

**Comment by ghost** [comment]
> The way things work with eksportisto as far as I uncovered implies that it's not feasible to run data collection from the beginning of the chain anymore. 
>but I think we can fake it by coalescing with the know historical value when computing the views, and because the historical value is static we can get away with that pretty easily.
>and then when we implement the view we can use some SQL magic to either backfill with static values, or derive metrics when possible.

Doing some SQL magic sounds good to fill in the values. I guess that's also not a problem for changing values, as we could combine it with the data from the archive node scraper when computing the views? When we plug the historical data into BigQuery and combine that with the eksportisto real-timeish updates.

**Comment by bowd** [comment]
> Doing some SQL magic sounds good to fill in the values. I guess that's also not a problem for changing values, as we could combine it with the data from the archive node scraper when computing the views? When we plug the historical data into BigQuery and combine that with the eksportisto real-timeish updates.

Not sure I fully follow. We won't really be plugging historical data into BigQuery. Eksportisto is the only one that writes into BigQuery, so after we update eksportisto our giant BigQuery table will have some new columns with the values that we're currently not tracking and we will start seeing data in those columns only for blocks from the time of the upgrade onwards. 

But the way things work in my understanding is that we have these "sql views" which expose a virtual table derived from the contents of the giant, semi-unstructured BigQuery table. So these views are essentially a way of restructuring the unstructured data in the giant BigQuery table. And at this layer I imagine we do something like grouping the "rewardsMultiplierMax" by block to extract the row that has that value from the unstructed BigQuery table, but if we can't find a value we can default to what we know was the historical value, because if was fixed. But all future values will result from eksportisto actually inserting rows in the BigQuery table, so any change of these "historically-fixed" values will be picked up.

But we're not relying at any point on the script or the data exported by the script. I hope that makes sense.

**Comment by ghost** [comment]
>Not sure I fully follow. We won't really be plugging historical data into BigQuery.

Oh I thought we could do that. 

> But we're not relying at any point on the script or the data exported by the script. I hope that makes sense.

But wouldn't it make sense to rely on the historical data exported by the script? IIUC, we could create a new BigQuery table which contains the historical data from the script. Then we could combine what we need in a view and we wouldn't need to care about the historical stuff in eksportisto data. But maybe I'm not understanding the whole pipeline well enough
