### ISSUE TITLE
Create a celo inflation metabase dashboard

### ISSUE THREAD

**Issue by bowd** [celo-org/celo-monorepo#8115]
Setup a Celo Inflation dashboard to visualize the data from the view(s) we have defined in the linked issue.

**Comment by ghost** [comment]
A cool chart that's not in the celo minting issue notebook so far would be one which tracks relative annualized inflation = annualized relative daily supply expansion. Either annualized or daily, I think annualized would be more comparable. I think that would be annualized((totalCeloSupply_(t) - totalCeloSupply_(t-1)) / totalCeloSupply(t-1))

**Comment by ghost** [comment]
Dashboard is here: https://metabase.celo-networks-dev.org/dashboard/71
