### ISSUE TITLE
[use-contractkit] Investigate adding Celo, cUSD, cEUR tokens to MetaMask with use-contractkit

### ISSUE THREAD

**Issue by aslawson** [celo-org/celo-monorepo#8126]
not sure if metamask exposes API, so may not work

**Comment by aslawson** [comment]
@critesjosh do you know if this is still an issue? i cannot actually remember what the concern was here, but maybe you've had some experience with users regarding this?

**Comment by critesjosh** [comment]
i haven't seen people having trouble. Maybe the issue was created as a feature request for use-contractkit, like to make it easy for dapp devs to add these buttons to their site?

**Comment by aslawson** [comment]
I see, so on selecting metamask, it would not only try to connect to metamask, but automate adding the Celo network if the user does not have that set up yet.

**Comment by critesjosh** [comment]
Yea, adding the celo network and potentially adding buttons to add tokens. I recently wrote a post that shows how to code the "add network" and "add token" buttons, not sure if this is helpful but here it is. https://docs.celo.org/blog/code-metamask

**Comment by nicolasbrugneaux** [comment]
Kinda got excited and stole this from @Bijan-Massoumi :pray:

**Comment by ChuckYampa** [comment]
Hello,
I tried sending BNB from Valora wallet to Metamask wallet since Metamask accepts BNB. Transfer successful, but funds were never received on Metamask. Any idea how can I regain access to BNB that is lost?
