### ISSUE TITLE
Developers SBAT DAppKit without Expo

### ISSUE THREAD

**Issue by nambrot** [celo-org/celo-monorepo#813]
### Expected Behavior

We should not prescribe the use of Expo to external developers

### Current Behavior

DAppKit is currently tied to Expo for 
1) opening and listening to deeplinks
2) contact functionality

**Comment by aslawson** [comment]
@eelanagaraj this looks like you accomplished this with https://github.com/celo-org/celo-monorepo/pull/7328/files?

Do we consider this close with that?
