### ISSUE TITLE
Celo:I made a heat transaction to a wallet and mark as approved and sent and I never arrive at the coinlist wallet I need help to solve it please

### ISSUE THREAD

**Issue by emmanuel868** [celo-org/celo-monorepo#8133]
*Describe your issue here.*

### Environment
* Elixir Version: 1.11.4
* Erlang Version: 23
* BlockScout Version: d334a72ffc31ee415908a27c74bc0a0ffa21a681

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by xutso** [comment]
Same problem, same time (6/19/21 12:30-45). can someone help us?
