### ISSUE TITLE
Pls solve 

### ISSUE THREAD

**Issue by albalush1** [celo-org/celo-monorepo#8134]
*Describe your issue here.*
Dear support team

 Good morning and have a nice day to you

I have problems i mistake withdrawal can u cancelled and returned my mony

I withdrawal from coinlist celo CUSD to celo bainace

this is my transactions ID
0x12a0380ed055715278673d75f4ab2ef11e6c2c3e922d78c5787397dc691a0252

plz cancelled 

Thanks regards
### Environment
* Elixir Version: 1.11.4
* Erlang Version: 23
* BlockScout Version: d334a72ffc31ee415908a27c74bc0a0ffa21a681

* User Agent: `Mozilla/5.0 (Linux; Android 10; MAR-LX1A Build/HUAWEIMAR-L21MEB; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/91.0.4472.114 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by albalush1** [comment]
Yes is stale and you didn't know how to fix it, lazy support team and they don't reply early this problem will complete one year

**Comment by karlb** [comment]
Confirmed transactions cannot be canceled.
