### ISSUE TITLE
Rehearse a key re-sharing (internal, no partner signers)

### ISSUE THREAD

**Issue by alecps** [celo-org/celo-monorepo#8148]
We should have confidence in our ability to perform a key re-sharing in the case that a signer's share is compromised. 

This ticket is for
1. Knowledge transfer from crypto -> identity teams
2. Performing a mock re-sharing with an unused set of BLS key shares 
3. Adding new tickets to this epic if additional work is needed to perform the re-sharing. 

Tickets will likely need to be created for: 
- Implementing / extending re-sharing smart contract
- Improving / writing re-sharing documentation 
- CLI improvements
- Determining how to coordinate transition to new key shares while minimizing downtime

**Comment by codyborn** [comment]
Should be done before ODIS is used for account recovery
