### ISSUE TITLE
Review operational security guidelines with partner signers

### ISSUE THREAD

**Issue by alecps** [celo-org/celo-monorepo#8149]
We should revisit the list of key management and operational security guidelines that we agreed to with partner signers and make sure that nothing should be added or clarified. 

We should also check in with each signer in some way to remind them of these guidelines and alert them of any new ODIS use cases.

**Comment by nategraf** [comment]
Quick thought: In order for resharing to be secure, we need to highlight a requirement for secure key erasure (i.e. the ability to delete a key and know that it's really destroyed.) IIUC, cloud provider key vault solutions all include this.

**Comment by codyborn** [comment]
@nategraf They do, but only for keys generated in the HSM. Unfortunately cloud HSMs do not support BLS keys and last that I heard they don't plan to add it.
