### ISSUE TITLE
Explore alternatives to currently proposed pOPRF construction for ODIS

### ISSUE THREAD

**Issue by nategraf** [celo-org/celo-monorepo#8156]
### Description

As part of an effort to enable secure password hashing for use in Account Recovery, we are working to implement a pOPRF in ODIS. Currently we have a candidate which seems to satisfy our needs, but has some drawbacks. Current proposal is available here: https://www.notion.so/clabsco/pOPRF-Cryptography-Proposal-493f1099460940f8a5d7dee4c78b4442

Drawbacks of the current proposal include:

* It requires a bilinear paring to compute the pOPRF output.
* It requires the client to run a number of operations in the target group, which is computationally expensive.
* Its output is only verifiable through an interactive protocol.
* Verification requires an additional request to the service, which must consume quota, halving the effective rate limit for verifying clients.

#### Goal

Our goal is to explore alternative constructions that can remove some or all of these trade-offs, or to reach a decision that we will not likely find such a scheme.

Related https://github.com/celo-org/celo-monorepo/issues/8157

**Comment by arthurgousset** [comment]
@alecps - Closed
