### ISSUE TITLE
Granda Mento exchange proposal template CIP

### ISSUE THREAD

**Issue by tkporter** [celo-org/celo-monorepo#8158]
This involves drafting a CIP that outlines suggested steps an exchanger takes prior to proposing the exchange.

Should include:
* Template for a forum post to share with the community
* Recommended information shared
* Who talk to & where
* How to get consensus on approval

Reason for need: We need a way for Granda Mento proposers to present their case to governance and the multisig in a unified manner. A lot of feedback was given by the community on what proposers should include (e.g. price they got their CELO at, reason they need it, etc., identity of requestor or requesting org) which will be helpful in determining if a swap is made in good faith for constructive (non-trading or arbitrage) purposes.

**Comment by albertclabs** [comment]
Some comments received, awaiting signoff from yaz

**Comment by tkporter** [comment]
Satisfied by: https://github.com/celo-org/celo-proposals/pull/272
