### ISSUE TITLE
Baklava faucet requires valid Keybase account

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-monorepo#816]
Details in https://docs.google.com/document/d/13I9wQfSriiQOWMZKb5YRkrdclZ4SowEoz3YusOSCtsU/edit#heading=h.w63hdoxbfy4o

- [ ] Faucet accepts a form submission which includes a required URL to metadata
- [ ] Pulls the metadata from that URL and verifies the keybase claim 

- [ ] Optionally -- Handles the case where someone sets the URL to be `https://gist.github.com/timmoreton/01e54471eb159ec4c399d6ce2cd08a81` whereas they really meant `https://gist.githubusercontent.com/timmoreton/01e54471eb159ec4c399d6ce2cd08a81/raw/master/`
- [ ] Further checks that the keybase user in the verified claim: "A Keybase account must have >= 2 external accounts verified (phone number, Twitter, GitHub with at least 1 repo, HN with at least 1 karma, Reddit with at least 1 karma) at least a month before the stake off starts i.e. before October 1st 2019"
- [ ] Faucet only allows a Keybase username to be fauceted once  
- [ ] Faucet is a reserve spender -- hence there is no faucet account -- but we will still need single-threading here!
- [ ] Configured in the migrations as a Reserve spender
- [ ]  Makes transfers using Reseve's `transferGold(address to, uint256 value) external returns (bool)` method

- [ ] Records the metadata URL and the keybase name as fields in the Firebase DB (so we can check not refauceted)

- [ ] Prints clear error messages so the user can know what's wrong

**Comment by clrblmt** [comment]
Faucet killed.
