### ISSUE TITLE
[Payments] Abort/cancellation flow

### ISSUE THREAD

**Issue by AlexBHarley** [celo-org/celo-monorepo#8175]

**Comment by aslawson** [comment]
Remaining work is checking the balance before trying to make the transaction to abort early

**Comment by aslawson** [comment]
The only remaining improvement would be pre-check balance > then requested amount.

Adding this would provide earlier check and save gas costs, but also introduce dependency of contractkit.

This could be done in the wallet. Valora may already have logic for checking balance.
