### ISSUE TITLE
[Payments] CLI Documentation

### ISSUE THREAD

**Issue by AlexBHarley** [celo-org/celo-monorepo#8177]
Should document:
- [ ] How to run the SDK CLI e2e
- [ ] How clients should implement the flow in their (yes, this is a bit redundant with the cli, but more accessible and will allow more details for each call and edge case explanation)

**Comment by aslawson** [comment]
TODO @aslawson : Make another ticket for developer documentation (those looking to make contributions to the payments SDK)
