### ISSUE TITLE
Investigate more generic ContractKit contracts abstraction

### ISSUE THREAD

**Issue by yorhodes** [celo-org/celo-monorepo#8180]
- remove web3 dependency from contract abstraction in web3 to allow for injectable providers (ethers?)

**Comment by nambrot** [comment]
Relevant ticket #8061

**Comment by yorhodes** [comment]
explore how blocked this is on providers @nambrot

**Comment by kevjue** [comment]
@nambrot - Is this ticket a dup of https://github.com/celo-org/celo-monorepo/issues/8061?

Or rather, if the long term plan is to deprecate ContractKit, then this ticket seems unnecessary.
