### ISSUE TITLE
Rehearse DKG ceremony (internal, no partner signers)

### ISSUE THREAD

**Issue by alecps** [celo-org/celo-monorepo#8186]
This ticket is for 
1. DKG knowledge transfer from crypto -> identity teams 
2. Performing a mock DKG ceremony 
3. Adding new tickets to this epic if additional work is needed to prepare the DKG setup for creating a new production ODIS key. 

Tickets will likely need to be created for: 
- Improving DKG documentation 
- Adding CLI commands
- Managing secure storage of key shares after they are created 

Existing DKG documentation: https://hackmd.io/_ZZqfPG0Qeiodgx9fy8hXQ#Docker
DKG setup repo: https://github.com/celo-org/celo-threshold-bls-rs/tree/master/crates/dkg-cli

**Comment by codyborn** [comment]
The existing DKG CLI is no longer compatible with Celo network (post Donut hardfork). There are a slew of dependencies that need to be upgraded to make the necessary changes to DKG-CLI. @kobigurk is taking a look at the dependency upgrade.
