### ISSUE TITLE
Determine target date for ODIS DKG ceremony

### ISSUE THREAD

**Issue by alecps** [celo-org/celo-monorepo#8187]

**Comment by ankushswar1** [comment]
We now have 3 signers interested in onboarding (Spruce, Keyko, and Figment), so the main blockers are internally rehearsing the DKG/resharing, and building any tooling necessary afterwards. 

To partners, we've been suggesting a timeline of late September/early or mid-October for the DKG. Internally, we have a **target deadline of the week of 9/29 (last week of Sept).**
