### ISSUE TITLE
Light access to celo core smart contracts

### ISSUE THREAD

**Issue by piersy** [celo-org/celo-monorepo#8206]
The blockchain team requires:
- To be able to obtain the source and build different versions of the celo core smart contracts
- in the lightest way possible (*)

(*) What do we mean with lightest, and why?

- Installing the dependencies takes an unnecessarily long time (7m) this
because dependencies for all 37 packages in celo-monorepo are installed.
- The resultant celo-monorepo folder contains so many files that it breaks
gopls (the go language server) and interferes with lots of other tooling if
placed under the celo-blockchain directory.
- The size of celo-monorepo after installing dependencies is
2169 MiB and the size of the protocol package is 112 MiB. So the protocol
package has roughly 5% of the dependencies of the whole celo-monrepo. So if we
could just download those dependencies we could expect the time to install
dependencies to be 5% of 7m which is 21s.

**Comment by martinvol** [comment]
How does this play out with the connect package? https://github.com/celo-org/celo-monorepo/tree/master/packages/sdk/connect

**Comment by martinvol** [comment]
@piersy 
Does the package [@celo/connect](https://github.com/celo-org/celo-monorepo/tree/master/packages/sdk/connect) include what you need?

**Comment by piersy** [comment]
Hi @martinvol I don't believe so.

As far as I can see it doesn't:
* Contain the source for celo core smart contracts
* Provide a way to compile the celo core smart contracts

However I am not an expert in js/ts so maybe I am mistaken?

**Comment by arthurgousset** [comment]
Closing the loop here (for future reference). 
Hope this release helps: 
- https://github.com/celo-org/celo-monorepo/discussions/10311

**Comment by aaronmgdr** [comment]
this is being handled by #10297 which will pubish  json abis and sol files as packages via a github action
