### ISSUE TITLE
Release AS 1.3.0 on Alfajores

### ISSUE THREAD

**Issue by codyborn** [celo-org/celo-monorepo#8226]
Contains following changes
- local signer 
- Verify API

**Comment by alecps** [comment]
TODO: split into 2 tickets. Maybe Eela can take 1.3.1

**Comment by eelanagaraj** [comment]
Once the two PRs above are merged to master, here are the release steps (combined from deployment + release guides):

- push a commit updating AS version on master to 1.3.0
- create a release branch (named as above)
- deploy to alfajores (part 1; as before, no changes to deployment)
- tests against alfajores (part 1; e2e verification tests -- look into how this works with Valora now though)
        --> manual testing for Verify API track
        --> manual testing for keystore changes
            - test for backwards compatibility
- deploy to alfajores (part 2; with modified deployment -- new env vars + helm chart modifications required)
- tests against alfajores (part 2; e2e verification tests)
        --> manual testing for keystore changes
            - test that behavior is the same as before
- docker tags (attestation-service-alfajores, attestation-service-baklava) + publishing release on Git, sign docker image -- figure out developer key stuff (look into if this something we still do + where these keys are actually registered on celo.org?)
- (communication of the baklava release date — is this still exactly 1 week after?)
