### ISSUE TITLE
Add Attestation Service dev environment file

### ISSUE THREAD

**Issue by codyborn** [celo-org/celo-monorepo#8231]
- Add `.env.clabs` to secrets store based on the [.env.development](https://github.com/celo-org/celo-monorepo/blob/master/packages/attestation-service/config/.env.development) base
- Add this new file to .gitignore so it's not accidentally added.

**Comment by alecps** [comment]
@eelanagaraj adding a note to ask you about this

**Comment by eelanagaraj** [comment]
@alecps this ticket is still relevant as long as we still need to maintain the ASv1, more context: it's really annoying currently to manually look up all of the API keys needed to get the ASv1 running locally, but these access tokens shouldn't be published.
