### ISSUE TITLE
Account Recovery Roadmap

### ISSUE THREAD

**Issue by codyborn** [celo-org/celo-monorepo#8232]
The account recovery work has many moving parts and dependencies. By listing all dependencies and their timelines we can get a better picture on when the items need to be started and the expected timeline for the overall project. The deliverable from this work should be a roadmap in Zenhub with sub-tasks shown as issues or epics.

**Comment by nategraf** [comment]
Created a timeline ready for review in ZenHub https://app.zenhub.com/workspaces/celo-5d94ef61d9b1e40001114c02/issues/celo-org/celo-monorepo/7244
