### ISSUE TITLE
Take inventory of general data needs for the economics team

### ISSUE THREAD

**Issue by bowd** [celo-org/celo-monorepo#8237]
As part of the ongoing effort to improve our data, we should have a clear sense of what is important to us. 
The output of this task would be a public data taxonomy that differentiates between real-time and historical data needs.
It will be shared with the data circle as they start ramping up more general cLabs wide data solutions.

**Comment by albertclabs** [comment]
Covered by ticket https://app.zenhub.com/workspaces/platform-economics---backlog-board-600a9f7399b43a001348ae1b/issues/celo-org/eksportisto/73

Will take inventory of dashboards for eksportisto migration
