### ISSUE TITLE
Develop cryptographic libraries for pOPRF functionality

### ISSUE THREAD

**Issue by nategraf** [celo-org/celo-monorepo#8250]
Following on from https://github.com/celo-org/celo-labs/issues/779, we want to finalize a design for pOPRF cryptographic functionality, implement it, and have the implementation reviewed for security. This supports the work to provide secure password hashing for use in account recovery https://github.com/celo-org/celo-monorepo/issues/7252

**Comment by arthurgousset** [comment]
@alecps - Closed
