### ISSUE TITLE
[Payments] Schema validation

### ISSUE THREAD

**Issue by AlexBHarley** [celo-org/celo-monorepo#8262]
Every step of the Celo Payments Protocol has strict data validation requirements.

We should use a tool such as [io-ts](https://github.com/gcanti/io-ts) (though preferably something more lightweight) that can handle this in an elegant way for us.

We never want to be sending or receiving invalid properties/status codes in our requests and this is the way to handle it all.

**Comment by aslawson** [comment]
Remaining schema validation for KYC data
