### ISSUE TITLE
Automate testnet governance proposal shepherding in CD

### ISSUE THREAD

**Issue by yorhodes** [celo-org/celo-monorepo#8266]
build upon output work from https://github.com/celo-org/celo-monorepo/issues/7108

- automatically approve, vote, execute an input proposal based on environment parameterization

**Comment by aslawson** [comment]
@yorhodes how are the governance proposals being specified in CD? is this just for the contract release governance proposal?

**Comment by yorhodes** [comment]
ideally this works for any type of proposal
just enter a JSON and it proposes, approves,.votes, executes automatically

**Comment by aslawson** [comment]
this would be cool. are there any security concerns though allowing automatic approval in our testnets?

and risk of testnets being out of sync if something in mainnet does not get passed?

**Comment by yorhodes** [comment]
timeboxed alerting if made public
