### ISSUE TITLE
@celo/utils needs to include country data file

### ISSUE THREAD

**Issue by jmrossy** [celo-org/celo-monorepo#8269]
There’s a problem with the latest published @celo/utils package since the use of country-data was changed to reduce the size.  

The countries.ts file imports the country.json file from ../data but the data folder isn’t included in what gets published to npm (see files section of package.json)
So when something tries to bundle utils package the bundler (e.g. webpack) will throw an error.

Also the dependencies are mixed up. The @types should be in the devDependencies section and country-data should be removed since we only use its types now.

**Comment by BriungRi** [comment]
+1. Having issues all the time when packages are depending on @celo/utils

**Comment by BriungRi** [comment]
@jmrossy A temporary workaround if you are using `yarn`:

Add this to your `package.json`

```
  "resolutions": {
    "@celo/utils": "1.2.1"
  }

```

**Comment by aslawson** [comment]
@jmrossy I don't recall, was this resolved? Updating priority since there seems to be a short term workaround, but will pull it near term backlog

**Comment by jmrossy** [comment]
@aslawson I don't know if it was resolved, I haven't tested new contract kit versions since I opened this. But it's definitely high pri if it hasn't
