### ISSUE TITLE
Investigate ethereumjs-vm monorepo compatibility

### ISSUE THREAD

**Issue by aslawson** [celo-org/celo-monorepo#8271]
Shardlabs has rebuilt Celo compatible ganache, but ganache upstream depends on a forked version of ethereumjs-vm. ethereumjs-vm has moved to a monorepo and its unclear whether it is compatible with ganache (or hardhat) and how much effort it would take to make it work.

We'd like to keep up to date on all upstream dependencies (including ethereumjs-vm) for security, maintainability and functionality.

**Comment by yorhodes** [comment]
**what is necessary for hardhat-network users to work with a celo-contracts chain?**
@nambrot ethereumjs-vm v5 (in monorepo) is a requirement for hardhat-network compatibility
maybe shardlabs can continue this work but urgency might be preventative

**Comment by kevjue** [comment]
Ganache-core is using ethereumjs-vm v4.2: https://github.com/trufflesuite/ganache-core/blob/master/package.json#L46
ethereumjs-vm v.4.2:  https://github.com/ethereumjs/ethereumjs-monorepo/releases/tag/%40ethereumjs%2Fvm%404.2.0

hardhat-network is using @ethereumjs/vm v^5.5.2: https://github.com/nomiclabs/hardhat/blob/master/packages/hardhat-core/package.json#L98
@ethereumjs/vm v5.5.2: https://github.com/ethereumjs/ethereumjs-monorepo/releases/tag/%40ethereumjs%2Fvm%405.5.2
