### ISSUE TITLE
[e2e-tests] Add Registry Proxy in genesis

### ISSUE THREAD

**Issue by 37ng** [celo-org/celo-monorepo#8276]
### Expected Behavior
Registry Proxy sits in genesis block for e2e tests, since we want to add a check in `gocelo` startup.

### Current Behavior
Registry Proxy is not in genesis, so adding that check would fail the e2e tests:
- [ ] governance
- [ ] slashing
- [ ] transfer
- [ ] validator-order

Related to [PR](https://github.com/celo-org/celo-blockchain/pull/1573)

**Comment by mcortesi** [comment]
Are you sure it's not added? 

This code adds the registry proxy to the genesis block https://github.com/celo-org/celo-monorepo/blob/8e21a5d970c69917deda5f587e07276273cfb19f/packages/celotool/src/lib/generate_utils.ts#L421-L437

So it should be there, unless it's broken.
