### ISSUE TITLE
[Payments] Verify transactions on chain

### ISSUE THREAD

**Issue by AlexBHarley** [celo-org/celo-monorepo#8277]
Given a PSP has,

- a transaction hash
- a reference ID ​

How can they verify the transaction was correct? They need to do some transaction decoding to verify everything matches up.

We should implement this in our reference server (@celo/payments-server) so that they can have an idea of how to do it.

**Comment by aslawson** [comment]
Don't need to prioritize this until we have others interested in the API/server implementation
