### ISSUE TITLE
[use-contractkit] investigate methods for opening WalletConnect deep links on action 

### ISSUE THREAD

**Issue by AlexBHarley** [celo-org/celo-monorepo#8288]
When we're using a WalletConnect compatible wallet that leverages deep links (Desktop Dapp <> Desktop Wallet or Mobile Dapp <> Mobile Wallet), we want to redirect the user to the application when they try perform an action (like signing a transaction).

Currently we only deep link when establishing the connection.

https://celo-org.slack.com/archives/C014SRL4URY/p1636740416052900?thread_ts=1636722997.050900&cid=C014SRL4URY

**Comment by aslawson** [comment]
Recent conversation about auto redirect from Valora:
https://celo-org.slack.com/archives/C014SRL4URY/p1636740416052900?thread_ts=1636722997.050900&cid=C014SRL4URY
