### ISSUE TITLE
Investigate supporting forno or other third party node service provider as a fallback CELO_PROVIDER in the Attestation Service

### ISSUE THREAD

**Issue by eelanagaraj** [celo-org/celo-monorepo#8305]
Ideally include this as an add-on to local signing (#7971) that would help reduce errors due to the full node syncing.

Additionally add/fix docs to support/encourage ultralight clients (instead of full nodes).

**Comment by aslawson** [comment]
I think it might be useful to look at this ticket as just enabling fallback CELO_PROVIDER nodes in general. so they could list a third party provider, another full node of theirs, and maybe forno as last resort.

if it's easy enough, an ordered list of providers could be nice. But if it adds more effort, not necessary

**Comment by eelanagaraj** [comment]
Totally -- looking into that as well; have a preliminary solution [PR](https://github.com/celo-org/celo-monorepo/pull/8311) that does this for just a single backup, but currently looking into doing this in a slightly different way that would make it a bit easier to add multiple fallback nodes. I do think that we should keep in mind that each additional provider will bring diminishing returns (+ additional costs for checking which one is up to date + added complexity, etc.)
