### ISSUE TITLE
Create product spec / roadmap document for dapp dev environment

### ISSUE THREAD

**Issue by kevjue** [celo-org/celo-monorepo#8307]
Ticket to document understand stakeholders, problem statement, and what we plan (and not) plan on solving.

**Comment by yorhodes** [comment]
do stakeholders like hardhat because of hardhat-network specifically? this has broad implications across our dev offerings

**Comment by yorhodes** [comment]
what work is necessary to achieve ganache + precompiles + tx support in hardhat-network?
