### ISSUE TITLE
ODIS Combiner Node Version Bug

### ISSUE THREAD

**Issue by codyborn** [celo-org/celo-monorepo#8315]
Build uses node version > 10, but GCP Cloud function only accepts node 10. We've been manually changing this line before deployment which is not a sustainable fix.

Builds
```
  "engines": {
    "node": ">=10"
  }
```

Deploys
```
  "engines": {
    "node": "10"
  }
```

**Comment by emilhotkowski** [comment]
According to this https://cloud.google.com/appengine/docs/standard/nodejs/runtime#node.js-14, we can't do match since 

> The engines.node property is optional, but if present, the value **must be compatible** with the Node.js version specified in your app.yaml file.

I would consider upgrading node.js version in Combiner (I believe this our service). 
@codyborn @alecps
