### ISSUE TITLE
[L06] No checks in setMaxApprovalExchangeRateChange

### ISSUE THREAD

**Issue by yorhodes** [celo-org/celo-monorepo#8321]
Within the function setMaxApprovalExchangeRateChange, there are no checks on acceptable values for maxApprovalExchangeRateChange.
In the proposal approval process, the rateChange variable represents a percentage difference between the proposed exchange rate and the current exchange rate. Then, the rateChange must be less than the maxApprovalExchangeRateChange. If maxApprovalExchangeRateChange is too low, it is highly likely that proposal approvals will revert.
Consider setting a lower bound for maxApprovalExchangeRateChange within setMaxApprovalExchangeRateChange to prevent excessive reversions during the proposal approval process.

**Comment by tkporter** [comment]
After discussion, decided to be a `wontfix`. While the value of `maxApprovalExchangeRateChange` is critical to not be too low, we believe Governance is capable of picking a reasonable value, and hardcoding a minimum doesn't help much. For example, a hardcoded minimum of 1% doesn't do a whole lot, and a higher value of 10% would paralyze the flexibility Governance has in restricting proposals easily.
