### ISSUE TITLE
[L05] Be careful of noncompliant ERC20s

### ISSUE THREAD

**Issue by yorhodes** [celo-org/celo-monorepo#8325]
Within the GrandaMento contract, there are uses of the ERC20 transfer function on line 324 and line 354. There is also an instance of the transferFrom function on line 235. These instances are within requires and will revert if the call to transfer does not return true.
Although all current stable tokens, as well as the native asset CELO, do return true on a successful transfer, it is a common pattern within DeFi that some tokens do not return true. Thus, GrandaMento will not work for these tokens.
Additionally, any non-standard tokens which charge fees on transfer may not be accounted correctly, due to not checking the contract&#8217;s balance post-transfer.
Consider checking for ERC20 compliance before allowing a token to be used with GrandaMento. Additionally, consider modifying the logic in GrandaMento to account for tokens which may charge fees by checking the change in the GrandaMento contract&#8217;s balance before and after transfer.

**Comment by m-chrzan** [comment]
It is presumed that the only ERC-20 tokens that will be allowed in Granda Mento are core Celo stable tokens that are based on StableToken.sol and approved by Governance. There's no general way to determine ERC-20 compliance on-chain, this needs to be done by humans off-chain and approved via a Governance vote.
