### ISSUE TITLE
[L02] Exchanger cancellations can be front-run

### ISSUE THREAD

**Issue by yorhodes** [celo-org/celo-monorepo#8328]
When a proposal is created in GrandaMento.sol, it can only be cancelled before it is approved by the approver role by calling the cancelExchangeProposal function. However this process can be front-run by the approver role, who can approve the proposal and prevent the user from cancelling it.
Consider informing exchangers that this is possible. Consider giving proposals a grace period in which the exchangers can cancel them before the approver can approve them.

**Comment by tkporter** [comment]
After brief discussion, we believe informing exchangers this is possible is sufficient, and that implementing the grace period is not worth it. The approver is generally a trusted role, so realistically this is unlikely to happen, and governance can always change the approver & cancel the exchange proposal if this does occur. Exchangers are also expected to be very confident in their exchange by the time they create the proposal on-chain, so cancellations are unlikely.
