### ISSUE TITLE
ODIS signer fallback mechanism when Azure FrontDoor has degraded service

### ISSUE THREAD

**Issue by codyborn** [celo-org/celo-monorepo#8341]
The Azure Frontdoor service recently had degraded service that significantly impacted the ODIS service, as described in this incident report.  The FrontDoor service is used for DOS protection and SSL termination. However, in the event of a FD downtime, there should be a fallback. E.g. perhaps the combiner can directly communicate with the signer clusters.

**Comment by arthurgousset** [comment]
Closing this ticket because the only two tickets in it are closed. Can always re-open if necessary.
