### ISSUE TITLE
Users SBAT reference initial CP-DOTO parameters

### ISSUE THREAD

**Issue by asaj** [celo-org/celo-monorepo#835]
### Expected Behavior

Stability protocol parameters are finalized

### Current Behavior

Not finalized

**Comment by rcroessmann** [comment]
Settled on the following parameters for now based on our CP-DOTO analysis. 
    spread: 5 / 1000,
    reserveFraction: 1 / 100,
    updateFrequency: 5 * 60, // 5 minutes
