### ISSUE TITLE
Account Recovery documentation to support broader identity features

### ISSUE THREAD

**Issue by ankushswar1** [celo-org/celo-monorepo#8356]
- Investigate how to reframe ODIS documentation to support broader identity features
- Smart contract architecture

**Comment by nategraf** [comment]
Superseded by the following tickets:
* https://github.com/celo-org/celo-monorepo/issues/8668
* https://github.com/celo-org/celo-monorepo/issues/8656
* https://github.com/celo-org/celo-monorepo/issues/8670
* https://github.com/celo-org/celo-monorepo/issues/8671
