### ISSUE TITLE
Simplify Attestation Service deployment helm chart 

### ISSUE THREAD

**Issue by eelanagaraj** [celo-org/celo-monorepo#8460]
Currently, the helm chart's geth containers are deployed in the pre-donut fashion, but we no longer need to initialize geth, don't need to pass in a genesis file, should pass in the network flag (`--alfajores` or `--baklava`) instead of using `--networkid` and don't need to pass in staticnodes. Leaving this in is not dangerous but caused an issue when deploying and the genesis file that it relies on was incorrect (which happens from time to time); cleaning this up will also make it easier to understand and also debug issues with deployment.

**Comment by codyborn** [comment]
Will be closed in preference of the local signing support feature which removes the need for this.

**Comment by eelanagaraj** [comment]
Reopening since we realized a component of the AS helm charts are still affected by this
