### ISSUE TITLE
Investigate improving speed of attestation service dashboards

### ISSUE THREAD

**Issue by eelanagaraj** [celo-org/celo-monorepo#8484]
Currently, all of our clabs-pipeline models are views (i.e. a saved query that is then re-run), the reasons being:
- this is the default of dbt
- we would have to build in some mechanism for refreshing the data if these were tables (i.e. running a CRON job or something to recreate these tables, or look into dbt cloud)
This may explain why so many of our AS metabase dashboards + GCP queries are slow to load (even for reasonably basic queries, and some dashboards currently take 30+ seconds).

Goals of this ticket:
- Investigate the tradeoffs of switching to tables (at least for some of the "base" views that a lot of views are built off of):
   - what are estimated costs in GCP of writing tables, running queries on views vs. tables?
   - how much of a speedup (if at all) do tables actually provide in our metabase dashboards?
   - what are possible solutions to the data-refreshing issue?
   - how much time/effort would this roughly take to implement any changes?
- Decision: is it worthwhile to pursue this further?

**Comment by codyborn** [comment]
Follow up with @carterqw2 to see if there are any BigQuery cost drivers for the priority of this. Maybe part of a larger data refactoring effort.

**Comment by codyborn** [comment]
@nategraf - We should evaluate which data sources should be views vs tables based on frequency of access and cost to compute.
