### ISSUE TITLE
Investigate wallet needs for keyless/social recovery and a generalizable social guardian service

### ISSUE THREAD

**Issue by ankushswar1** [celo-org/celo-monorepo#8489]
**Since this is no longer on Valora's near-term roadmap, we should scope if any other wallets are interested in a social recovery feature.**

To make keyless recovery widely available, we should consider how cLabs or Valora might operate a social guardian service to verify a user's identity (via email confirmation, knowledge-based authentication, etc.) for users that don't have another obvious choice for a social guardian.

**Comment by nategraf** [comment]
Assigning myself for the work of refactoring and expanding existing designs for social guardian support

**Comment by nategraf** [comment]
After bringing documentation and discussion to the Wallet Council it is unclear what shared infrastructure or support from cLabs will be utilized by wallets if available. Next steps are to schedule 1:1 syncs with wallet teams to discuss needs for Account Recovery. Another potential step is to set aside time at a Wallet Council to do a collective brainstorming session.
