### ISSUE TITLE
[Payments] Proof of number verification on server side

### ISSUE THREAD

**Issue by AlexBHarley** [celo-org/celo-monorepo#8519]
Now that we've cut the scope of this project to only include phone numbers in the KYC data, we need a way on the server side to verify the `from` address of a transfer is mapped to the phone number provided in the KYC data. 

- [ ] Get Identifier from ODIS https://docs.celo.org/developer-guide/contractkit/odis
- [ ] Check onchain for existence of phone number mapping in attestation service

**Comment by nicolasbrugneaux** [comment]
note to self: https://docs.celo.org/developer-guide/contractkit/odis - use this to find out info about the phone number
