### ISSUE TITLE
Gas Repricing EIP Adoption

### ISSUE THREAD

**Issue by aslawson** [celo-org/celo-monorepo#8538]
Required for upcoming hardfork. Ideally, understand the contract changes needed by end of sprint.

https://celo-org.slack.com/archives/CP5V8KF51/p1628693424048700

**Comment by yorhodes** [comment]
discuss on governance call

**Comment by yorhodes** [comment]
check optics contracts? cc @pranaymohan

**Comment by yorhodes** [comment]
https://celo-org.slack.com/archives/C01KT8JKQ67/p1630517485030100?thread_ts=1630517311.029800&cid=C01KT8JKQ67
