### ISSUE TITLE
ASv2 MVP 🤝

### ISSUE THREAD

**Issue by codyborn** [celo-org/celo-monorepo#8588]
This epic encompasses all of the necessary steps for implementing an MVP (alpha-version) of a trusted issuer model attestation service (ASv2) for A/B testing against the existing Attestation Service (ASv1). 

As we decide that any of the listed tickets are out of scope for this epic, we should move those tickets out of this epic and into the parent ASv2 epic

**Comment by 0xarthurxyz** [comment]
Assigning myself for visibility on Zenhub board.

**Comment by alecps** [comment]
Closing in favor of https://github.com/celo-org/celo-monorepo/issues/9730
