### ISSUE TITLE
Technical design of off-chain client for generalized cLabs Attestation Service (ASv2)

### ISSUE THREAD

**Issue by aslawson** [celo-org/celo-monorepo#8591]
See discussion from [Offsite Wednesday](https://www.notion.so/clabsco/NYC-Offsite-Nov-2021-7ceaa4f764324a62a46c67a19b70818b#acc07f038c6742ff814aa8567553aa33). This should include the challenge/request model used by clients requesting attestations and issuers of those attestations.

**Comment by eelanagaraj** [comment]
sync with Trustworks on this to understand timing/priority

**Comment by eelanagaraj** [comment]
[Link to design doc draft](https://www.notion.so/clabsco/Off-chain-Client-ASv2-722dd23a5e17482791c1c7b00cce30d3)
