### ISSUE TITLE
Produce simple "Data Docs" with available fields and data source for newcomers.

### ISSUE THREAD

**Issue by ag-clabs** [celo-org/celo-monorepo#8597]
The goal of this ticket is to start creating simple documentation for identity data.
Learn from the data documentation the Data Services team produced for the Blockscout API.

**Comment by arthurgousset** [comment]
Investigate existing data: 
- [ ] Document data types in relevant tables
- [ ] Document data source (i.e. where is the original data from)

Future work ideas:
- [ ] Create code snippets ("query templates") that can be leveraged in future investigations

**Comment by 0xarthurxyz** [comment]
Closing this ticket, because an interim documentation was created in Data Studio. Might move it in the future.
