### ISSUE TITLE
Create Colab Notebook and update KRs for Program Review

### ISSUE THREAD

**Issue by ag-clabs** [celo-org/celo-monorepo#8600]
The goal of this ticket is to: 

- have a simple way to view the current status for all KRs
- update some KRs manually (e.g. wallets that use identity features)

**Comment by arthurgousset** [comment]
#### Colab Notebook: [Key Results (Program Review)](https://colab.research.google.com/drive/1l1BSmjVOPgjPZPZlE7NClqh3O9IRKl30#scrollTo=ShwwM-SbAh08)

**Comment by arthurgousset** [comment]
- [ ] replicate all queries in Google Colab
- [ ] learn to manipulate pandas data frames to calculate the relevant metrics we're looking for (e.g. completion rate is % of true vs false on a given date)
- [ ] Provide written context so it is easy to understand where the relevant outputs are

**Comment by 0xarthurxyz** [comment]
Closing this ticket in favour of prioritising general ID dashboard (#8659) and because Notion with links to Metabase queries works quite well right now.
