### ISSUE TITLE
Expose ODIS API v2 signer endpoints

### ISSUE THREAD

**Issue by alecps** [celo-org/celo-monorepo#8638]
Handlers can just return a "not-implemented" error for now

Endpoint are exposed in server.ts

**Comment by emilhotkowski** [comment]
@alecps should we put these three endpoints under **/domain** path?

**Comment by alecps** [comment]
@emilhotkowski Yea like that. We could then do 
**/domain/disable**
**/domain/sign**
**/domain/status**
