### ISSUE TITLE
implement /getDomainRestrictedSignature handler

### ISSUE THREAD

**Issue by alecps** [celo-org/celo-monorepo#8643]

**Comment by emilhotkowski** [comment]
@alecps Could you provide more info about this part? I could do it and add e2e tests to signer.

EDIT: BTW should we remove existing signing method once we change combiner ?

**Comment by alecps** [comment]
@emilhotkowski This will basically be filling in the body of the handler function once the versioning scheme, types and other components are in place. It should be relatively straightforward at that point. I think it makes sense to wait on this for now. I also think (from experience) that e2e testing should be it's own ticket / PR since it's often more involved than the actual implementation. We'll also want to test e2e via the identity sdk, so this should be done after that ticket as well
