### ISSUE TITLE
 Investigate migrating AS dashboards to blockscout data

### ISSUE THREAD

**Issue by eelanagaraj** [celo-org/celo-monorepo#8655]
This may be the preferred long-term solution regarding our data landscape anyways. While waiting for potential fixes in the eksportisto 14 data (+ deployment, etc. which will take several weeks minimum) before migrating (#8617), it may be prudent to investigate this as well.

Questions/todos:
- Is this desirable, and is this the direction we are going in (re: consolidating data sources)? -> consult with the Data Services team on this
- How feasible is this, what changes would need to be made?

Output is either of:
- Ticket(s) with steps required to switch to blockscout data
- OR decision to not use blockscout data for now (+ reason why)

**Comment by eelanagaraj** [comment]
Timeline on blockscout data prep is unclear, and since eks14 data works after sept 14th, we can deprioritize this until blockscout data is in BigQuery and in a usable state.

**Comment by 0xarthurxyz** [comment]
I had a conversation with Matt (PM Data Services) about the Blockscout vs Eksportisto discussion. 

Here are a few take-aways: 

1. the Data Services ("DS") team is running a few **off-sites** in the next week to discuss service ownership and pros/cons of Blockscout among other things

2. to help frame the DS team's thinking around pros/cons, it would help if we could provide **context** on our experience of working with data for the attestation service dashboards along the following metrics: 
- [ ] Quantity (do we have enough eksportisto data points, if not which data fields are missing, where are the most `null` values...)
- [ ] Quality (do we have good enough eksportiso data to answer our questions, if not what are we missing to spin our dashboards in a meaningful way)
- [ ] Operations (how easy is it to work with eskportisto data: do we have to join tables too often, are our SQL queries cumbersome, is it easy to understand the data fields and tables?...)
3. Matt would like to take a look at our **dashboards** 
- [x] Thanks for sharing these @eelanagaraj 🙏

**Comment by arthurgousset** [comment]
Updating this ticket because Data Services have prioritised migrating all data to Blockscout, including attestations data. 

Closing the ticket because this is not an "investigation"/exploration anymore.
