### ISSUE TITLE
(Step 1) Clean up Notion Docs for Wallet Council

### ISSUE THREAD

**Issue by codyborn** [celo-org/celo-monorepo#8668]
This ticket specifically addresses the "cleaning up" and "documenting" of our research for the **wallet council**.

The goal is to share the Notion doc with the wallet council and get feedback on what else might need to be clarified before making it "public facing" (through the [blogpost](https://app.zenhub.com/workspace/o/celo-org/celo-monorepo/issues/8656)).

**Comment by nategraf** [comment]
Done. Deliverables for the Wallet Council are available here: https://github.com/celo-org/celo-proposals/issues/288#issuecomment-926984338
