### ISSUE TITLE
(Step 4) Run a Celo tech talk on Account recovery

### ISSUE THREAD

**Issue by 0xarthurxyz** [celo-org/celo-monorepo#8671]
# Context

Run a very casual 1:1 tech talk moderated by Arthur with Victor. 
High-level mostly talking about the **why** and high-level **how** of account recovery:

- What does Account recovery solve?
- What did we implement and why? 
- What did we not implement yet but have design docs on?

@nategraf's Notion doc: "[Account Recovery Tech Talk Outline](https://www.notion.so/clabsco/Account-Recovery-Tech-Talk-Outline-f670a3157e5a42b6913a4b12b1041e31)"

# House keeping

- [ ] @arthurgousset to coordinate with Brandy (or whoever is running the tech talks)
- [x] @nategraf and @arthurgousset to sync on the content of the call and prep how we moderate and run it

**Comment by 0xarthurxyz** [comment]
Happy to help organise the tech talk with Judy (or whoever owns them)

**Comment by 0xarthurxyz** [comment]
Added a link to your notes @nategraf: "[Account Recovery Tech Talk Outline](https://www.notion.so/clabsco/Account-Recovery-Tech-Talk-Outline-f670a3157e5a42b6913a4b12b1041e31)"

**Comment by arthurgousset** [comment]
Deprioritised
