### ISSUE TITLE
Create a script to add a new stable token to a network

### ISSUE THREAD

**Issue by martinvol** [celo-org/celo-monorepo#8676]
We need to create a script that does the following:

For Stable Token:
1. Deploy a new StableToken.sol contract
2. Deploy a Proxy contract, and set the implementation with the contract deployed in (1)
3. initialize the contract with a .json file with the argument (this includes pre-mint addresses), etc.
4. Transfer ownership to GovernanceProxy
5. Set StableTokenX (where X can be for example BRL) in the registry.

For Exchange:  Same as Exchange, with detail that a parameter for the initializer function should be the address of the proxy deployed in (1).

It should generate a governance proposal in .json format ready to be proposed.

Ideally, this contract should be able to verify an existing governance proposal as well.

**Comment by yorhodes** [comment]
This can reuse much of the automated core contracts release tooling. Specifically [`deployCoreContract`](https://github.com/celo-org/celo-monorepo/blob/8f2241e1de42b28ad02c1edcc35a25f3d2a5e7d9/packages/protocol/scripts/truffle/make-release.ts#L145-L146) should be useful but it's not immediately reusable without some abstraction away from the `versionedReport` context.

**Comment by yorhodes** [comment]
The [`make-release-3-changes` script](https://github.com/celo-org/celo-monorepo/blob/master/packages/protocol/scripts/make-release-3-changes.ts) introduced in #7267 performs the exchange initialization parameter change. Please reach out if you need help using either of these already battle-tested paths.

**Comment by martinvol** [comment]
For security reasons, we decided to create new contracts for cREAL and use the existing tooling that we use for contract releases.
