### ISSUE TITLE
App SN reset on poor connectivity

### ISSUE THREAD

**Issue by martinvol** [celo-org/celo-monorepo#87]
### Expected Behavior

App shows error message.

### Current Behavior

The app resets when I try to recover from back-up phrase when I used the connection I have in my house. TBF, the connection is kinda weird and media works well on my computer but not my phone when I scroll some apps and I haven't found out why yet.

Unfortunately, I haven't been able to reproduce this anywhere than my house.

Send the emails to support from test phone 4.

**Comment by annakaz** [comment]
Use Android emulator to simulate slow internet

**Comment by annakaz** [comment]
Steps to reproduce: turn wifi on and off, cause chaos in phone, killing app and moving around

**Comment by nityas** [comment]
Addressed by low connectivity mode #1171 , closing
