### ISSUE TITLE
Implement Domain versioning scheme

### ISSUE THREAD

**Issue by alecps** [celo-org/celo-monorepo#8702]
- Refactor common and signer packages to allow for versioned Domains of various types. 
- Consider using strategy pattern https://refactoring.guru/design-patterns/strategy

**Comment by emilhotkowski** [comment]
@alecps Can we be more specific of what is the goal? What we want to have in common and signer. We already have some code for domains in Common. In signers I would imagine we want change "get-quota" functionality?

**Comment by alecps** [comment]
@emilhotkowski Just documenting what we discussed earlier. We don't want to change the get-quota functionality, but rather add code to the getDomainRestrictedSignature handler (or more likely to a helper method that the handler will use) that determines whether a given domain is of a supported type, casts the domain to that type, checks the version number, and determines which helper functions (i.e. checkSequentialDelay) to use to handle the request based on the domain type and version. This will also require re-organizing / renaming the helper functions so that it's easy to add new versions of them. It should build off of the work in https://github.com/celo-org/celo-monorepo/pull/8705
