### ISSUE TITLE
Consider shifting approver approval to veto by default

### ISSUE THREAD

**Issue by yorhodes** [celo-org/celo-monorepo#8736]
### Expected Behavior

Approvers are only required to act on proposals which they believe are dangerous

### Current Behavior

Coordination work necessary to contact approvers about proposals is very centralized

**Comment by m-chrzan** [comment]
Consider the risks of this (are approvers actively monitoring for proposals that weren't reported to them? potentially this risk would decrease with #8734).

**Comment by martinvol** [comment]
This issue will be closed as referendum and approval stages go in parallel: https://github.com/celo-org/celo-monorepo/issues/8734
