### ISSUE TITLE
Investigate priority of supporting China phone onboarding

### ISSUE THREAD

**Issue by codyborn** [celo-org/celo-monorepo#8741]
Supporting China will pose a unique set of challenges due to crypto regulations. Work with founders and CeloDance to understand priority of market and desired features for supporting onboarding users reliably.

@arthurgousset: Update: Following chat with @albertomartin, China SMS support is not top of list compared to other priorities.

**Comment by 0xarthurxyz** [comment]
Scheduled to talk about this with @albertomartin this week.

**Comment by 0xarthurxyz** [comment]
Closing this ticket due to update below (copied in description). 

Update: Following chat with @albertomartin, China SMS support is not top of list compared to other priorities.
