### ISSUE TITLE
Understand blockers for Valora to use trusted issuer model

### ISSUE THREAD

**Issue by codyborn** [celo-org/celo-monorepo#8744]
Valora expressed concern about using a trusted issuer for phone number verification due to Celo rewards governance. Understand if this is a hard blocker or something that we can work with.

**Comment by 0xarthurxyz** [comment]
Added this to the following epic "[[Attestation Service] Trusted Issuer Model#8762](https://app.zenhub.com/workspaces/identity-backlog-board-60e61301c3dc55000e540b61/issues/celo-org/celo-monorepo/8762)"

**Comment by codyborn** [comment]
Chatted with Silas and Aleksey. Before investing here, we'd like to first understand the user drop-off vs onboarding time. For example, if a majority of the users drop off after 5 second, then we may need an alternative approach to solving the onboarding friction.
