### ISSUE TITLE
[Attestation Service] Explore Trusted Issuer Model

### ISSUE THREAD

**Issue by 0xarthurxyz** [celo-org/celo-monorepo#8762]
## Context

- [[2-pager] Trusted Social Identity Attestations
](https://www.notion.so/clabsco/2-pager-Trusted-Social-Identity-Attestations-56247072712f4cd2b77fa8106f4a1cba)
- [ID Product Review, 23 Sep 2021](https://www.notion.so/clabsco/ID-Product-Review-23-Sep-2021-2557116a077443308ff290e94c113cff)

## Housekeeping

- [x] @arthurgousset: Synthesise tensions and takeaways from product review
- [x] @eelanagaraj + @arthurgousset: Spec out tickets to reflect next steps

**Comment by eelanagaraj** [comment]
Closing this in favor of the sub-epics that have been moved out; "exploration" is done, and we are moving forward with the ASv2+ concepts that came out of the NY Offsite
