### ISSUE TITLE
[Wallets] Explore "funny" verification UI in wallets (Valora)

### ISSUE THREAD

**Issue by 0xarthurxyz** [celo-org/celo-monorepo#8765]
Closed this ticket in favour of this Github Discussions topic: 
- https://github.com/celo-org/celo-monorepo/discussions/9306

### Assumptions 

1. "_Decentralised phone number verifications are **slow**_", because (among other reasons):

  a. Generating **on-chain randomness** takes time
  b. Sending SMS message through the **Attestation Service** takes time

2. "_Users expect fast phone number verifications_", because 

  a. attention spans are short 
  b. phone number verifications are "usually" fast (when requesting OTP from Amazon, Google, etc for 2FA)

### What can we do?

We can:

1. improve the **verification speed** (i.e. effort at _protocol level_), or
2. increase user **patience and understanding** (i.e. effort at _wallet level_)

## Idea

_Design wallet UIs that entertain users and visualise what "magic" is happening in the background_. 

e.g. 

- "While user waits for text messages, Valora displays message saying "Cooking up some magic in the background"
- "generating randomness on chain so you don't really on centralised services"
- "connecting you to decentralised validators"
- "validators are sending you a message"

or gamify process

- Google internet error [dinosaur game](https://trex-runner.com/) 

**Hypotheses**:

- Users might be more patient if they are educated/entertained about the process

**Comment by arthurgousset** [comment]
Closing this ticket in favour of this Github Discussions topic: [Feature Request: Present educational/entertaining UI in wallets during decentralised phone number verification (Valora) #9306
](https://github.com/celo-org/celo-monorepo/discussions/9306)
