### ISSUE TITLE
Define AS success metric and data needs for "success" definition

### ISSUE THREAD

**Issue by 0xarthurxyz** [celo-org/celo-monorepo#8767]
## Context

The current definition of "_success_" for the Attestation Service is ambiguous.

**Definition**: "_did the service deliver the text messages [in a reasonable amount of time]_"

For example: 

1. "_completing an attestation_", is different than
2. "_successfully delivering an SMS message_", which is different from a 
3. "_user successfully verifying their phone number_". 

_Source: [Slack thread](https://celo-org.slack.com/archives/CJXJ1EV0D/p1633556295008300?thread_ts=1633483120.485200&cid=CJXJ1EV0D)_

> -  if we just look at SMS sent/delivery messages: the attestation service could receive + log that the SMS was delivered, but we don’t have external confirmation that the SMS was indeed delivered. Failures here -- i.e. error messages returned -- should probably be seen as a reliable condition for failure, but “Sent”/“Delivered” messages may not be reliable conditions for success
Current 
> - if we just look at verification completion: a completed flow guarantees that messages were delivered, but an incomplete flow does not guarantee messages were not delivered.
> - (it seems really hard to isolate possible user error, with the AS/SMS providers functioning properly)

## Potential Next steps

**Define success metric and data needs for "success" definition**

- [ ] Define success at ID level
- [ ] Identify data needs to compute success metric 
- [ ] Identify data owners (stakeholders owners like wallets, Twilio etc) we need to partner with to compute the metric

## Additional thoughts
- break down success by country --> what are the driving factors per country (for countries that have particularly bad success rates) that are leading to delivery failures? would these effects likely be present in ASv2 as well as ASv1?
- what is the success rate when removing countries that seem to experience regional delivery outages?

**Comment by alecps** [comment]
@eelanagaraj Is it safe to close this?

**Comment by eelanagaraj** [comment]
Closing for now in favor of ASv2 work; we can revisit and make this more specific in the future if needed.
