### ISSUE TITLE
[Attestation Service] Investigate root cause of "slow" AS

### ISSUE THREAD

**Issue by 0xarthurxyz** [celo-org/celo-monorepo#8770]
### Context 

**Current assumption**: "_Decentralised phone number verifications are **slow**_", because (among other reasons):

  a. Generating **on-chain randomness** takes time
  b. Sending SMS message through the **Attestation Service** takes time

**Additional resources**: @eelanagaraj also compiled assumed problems with the Attestation Service on this [Jamboard "ASv2 Requirements Gathering](https://jamboard.google.com/d/19NBWrbb-EMZ5ArpA6EJ7Ug8JK5QngI_0PlPc0_M9uKs/viewer?f=1)"

### Potential Next Steps

- [ ] Investigate which "components" of the verification flow contribute to the **~2 minute waiting time** for SMS messages 

Example questions:

- _Do we wait 15 seconds for on-chain randomness 3 times (for each validator) or once?_ 
- _Does the Attestation Service itself contribute a lot of time and if so how?_ (just curious, so we can estimate if a trusted issuer model would address this)

### Impact

This will **help us to define testable hypotheses** that we want to validate with some of our products/solutions (among others) the **trusted issuer model** ("[[Attestation Service] Trusted Issuer Model#876](https://app.zenhub.com/workspaces/identity-backlog-board-60e61301c3dc55000e540b61/issues/celo-org/celo-monorepo/8762)2")

**Comment by 0xarthurxyz** [comment]
☝️ Hi @eelanagaraj, I created this ticket as discussed during our 1:1 today 💬
I've linked your [jamboard](https://jamboard.google.com/d/19NBWrbb-EMZ5ArpA6EJ7Ug8JK5QngI_0PlPc0_M9uKs/viewer?f=0) and a bit of context to explain our reasoning. Please feel free to edit or complement the description with any other meaningful context or questions.

**Comment by codyborn** [comment]
@eelanagaraj does this investigation cover this ticket?
https://celo-org.slack.com/archives/CJXJ1EV0D/p1634578501197000

**Comment by eelanagaraj** [comment]
@codyborn I think mostly! May still be useful to take time to evaluate the implications are for the ASv2 + create additional tix for the current speedups, wdyt?

**Comment by codyborn** [comment]
Sounds good @eelanagaraj! I'm syncing with @aleksey-nov to get a sense of priority within Valora. If they're equally interested in speed-up, we can create some tickets for speed-ups.
