### ISSUE TITLE
Attestation Service support alternative sender names

### ISSUE THREAD

**Issue by codyborn** [celo-org/celo-monorepo#8791]
Currently the attestation service sends a generic message to the user "Your Celo verification code is...". Wallets would like to have the ability to customize the sender (ex. "Your Valora verification code is..."). To achieve this, it requires Celo validators to create a support ticket and respond to the following questions:
> In order to evaluate if we can activate the custom friendly name feature on your account, could you please confirm what's your use case for custom friendly name? Also, please confirm that you have controls and validation in place on the text field used for the service name. This is necessary to ensure that the feature is used appropriately.

My response: 
> We participate in a decentralized phone number verification service. The service is generic and not tied to any particular application which is why we need the ability for the caller to specify their own app name. These applications are mostly blockchain wallets which run on the Celo network.

It also requires a new feature be added to the Attestation service and API to expose the ability to pass in a custom sender name.

**Comment by codyborn** [comment]
See this thread for more context
https://celo-org.slack.com/archives/C018VLA3YAK/p1633375735133000

**Comment by eelanagaraj** [comment]
@codyborn is this something we can still decide not to do? I agree with you on "Celo" being more generic + wonder if it's potentially an attack vector to fully support custom names (i.e. custom name set to some sketchy link that the user then clicks when they receive the SMS)

**Comment by alecps** [comment]
Closing this in favor of ASv2
