### ISSUE TITLE
Investigate whether we need a database lock for faucet account

### ISSUE THREAD

**Issue by eelanagaraj** [celo-org/celo-monorepo#8799]
Currently, there is logic in `packages/faucet/src/database-helper.ts` (`doWithAccount`, `tryLockAccountWithRetries`) that requires "locking" the faucet account before trying any faucet transactions. If another process has already obtained the lock, then the requesting process retries until the lock is freed and it can obtain it, or else fails.

We have observed an error where some event "locked" the account but never unlocked it, causing all future attempts to fail with a `NoFreeAccountErr`.

This ticket should look at:
- is the locking logic necessary at all? -- as long as firebase is locked down to requests from our website and the ReCAPTCHA is enabled, we shouldn't need this additional DoS protection
- If locking is not necessary, it is adding complexity + possible points of failure (like the error seen), we should refactor out the locking + redeploy
- if we do need to keep the locking, we should understand if/where an error was thrown that caused the errant lock, and implement a timeout on the lock (i.e. 5min) in the event it isn't given up to prevent deadlock

**Comment by aslawson** [comment]
@eelanagaraj what is the impact of this? how often does it happen? how difficult is recovery?

**Comment by eelanagaraj** [comment]
Hey @aslawson! This caused the faucet to go down a few weeks ago: [slack thread](https://celo-org.slack.com/archives/C9RSRC8KS/p1634502792153600). How often: this seems like the first time it's happened, but no idea what the root cause was (unclear: was it an attack? was it a request failing in an unexpected way that caused it to block every request afterwards?). It was a pretty bad bug in that it fully blocked all faucet requests, but the manual fix seemed to work. We also don't have alerting for failing faucet requests (only alerting for faucet balance), so we unfortunately won't know if this isn't working until people start complaining about it :-/
