### ISSUE TITLE
Build a lightweight Phone Number lookup client

### ISSUE THREAD

**Issue by codyborn** [celo-org/celo-monorepo#8830]
[Querying on-chain identifiers with ODIS](https://docs.celo.org/developer-guide/contractkit/odis)

Users of [Celo Wallet](https://github.com/celo-tools/celo-web-wallet) should be able to send funds to a friend easily with only a phone number. Similar to Valora, a user could enter a wallet address or phone number and have it resolved/validated to an address.

The solution should also cover error handling (ex. out of quota) and show errors to user.

The client should be as small as possible with a minimum security footprint to meet the needs of Celo Wallet.

This library can be used in the future to lookup generic types of identifier attestations.

**Comment by arthurgousset** [comment]
Similar to what @critesjosh is working on here https://github.com/critesjosh/register-number

**Comment by eelanagaraj** [comment]
Hey @alecps not sure if there's more context on this ticket, but if it's a wrapper around the ODIS calls, this could also be helpful for simplifying integration for Kaala and others? (Unless this is actually an API endpoint or something we would need to keep up and running as a way of bypassing ODIS + BLS libraries?)

**Comment by codyborn** [comment]
Just for some more context:
Motivated by Rossy's requirements to have as small of a size requirement as possible (no OOF Size). One option is as @0xarthurxyz mentioned to leverage @critesjosh's API, which doesn't need any BLS blinding but does have some privacy risks since users will be sending their phone number in plaintext.
The second option is as @eelanagaraj mentioned to slim down the library and make the BLS Blinding more concise. The BLS blinding requires 2 dependencies - crypto which is 142B and blind-threshold-bls-wasm which is 1.8MB. The biggest culprit is the wasm file which is 1.1 MB. If I gzip it I can get it down to 215 KB. 
`gzip -9 < src/blind_threshold_bls_bg.wasm | wc -c`
