### ISSUE TITLE
Add QR Code Scanning for Merchant Payment

### ISSUE THREAD

**Issue by aslawson** [celo-org/celo-monorepo#8837]
- [ ] QR code scan should recognize this is a merchant payment code.
- [ ] Checks for phone number verification
- [ ] If no phone number verified, redirect to phone number verification flow
- [ ] If verified, direct to the payments screen

**Comment by dckesler** [comment]
Need copy for the "verification needed" message

**Comment by dckesler** [comment]
Put this work behind a feature flag
