### ISSUE TITLE
[on-call] look into discrepancy between validator AS dashboards

### ISSUE THREAD

**Issue by eelanagaraj** [celo-org/celo-monorepo#8851]
Big discrepancy in validator AS completion rates for AnyblockAnalytics in the dashboards linked below:

- https://thecelo.com/groupDetail/0x69cd274C6AcBc08F664eD7B2D54aaB6615BC1d70
- https://celo.org/validators/explore
- https://rc1-blockscout.celo-testnet.org/address/0x66Be809e9ba5A6F57625b32506916db49a75D360/celo
- https://metabase.celo-networks-dev.org/public/dashboard/b0a27650-1d62-4645-81d7-26ff7546ff0d?date_filter=past4weeks~&validator_address=0x8C1Bf342693772A04bB223EA949f915ebf72521A
- https://cauldron.pretoriaresearchlab.io/attestations; Validator: AnyblockAnalytics; Attestation URL: https://attestation.celo.anyblock.tools

Outputs:
- [x] understand what's causing the differences
- [x] determine which dashboard(s) are closest to ground truth
- [ ] understand implication re: foundation votes, reach out to them if necessary
- [ ] communicate findings to Anyblock + other validators via discord/email

**Comment by eelanagaraj** [comment]
- Differences likely caused by a bug in the blockscout indexer's counter, will be investigated by Data Services [in this ticket](https://app.zenhub.com/workspaces/data-services-backlog-5fb2a73661b16000112ee756/issues/celo-org/data-services/75)
- Raw blockscout logs confirm eksportisto data (i.e. AS metabase dashboards, thecelo)

With this in mind, seems even more important that the foundation voting's AS completion component is not based on https://celo.org/validators/explore until the blockscout bug is fixed cc @codyborn @arthurgousset

**Comment by 0xarthurxyz** [comment]
Thanks for the detailed overview 💯 🙌 
I don't fully understand how the "foundation voting" program works. 

I.e. is it programmatic or does someone from the Foundation look at the dashboard (https://celo.org/validators/explore) to make manual adjustments to the voting program. 

If someone is manually doing this, we could simply suggest they use the Metabase dashboard instead like you said.

**Comment by eelanagaraj** [comment]
Followed up with foundation folks but do so again to make sure that the need for this change is understood

**Comment by eelanagaraj** [comment]
set a recurring reminder to keep any eye + check-in on foundation voting when it happens for the next cohort
