### ISSUE TITLE
[BOUNTY]: <Bounty Title> Transaction issue on my celo wallet 

### ISSUE THREAD

**Issue by Airamlo** [celo-org/celo-monorepo#8853]
### Challenge Description

i had tranaction on metamask walet and transfer 80 USDT on Celo but my walet didint support this feature and i didint received the crypto 

### Submission Requirements

What constitutes a valid/good submission to win the bounty? Would you like a demo included in the submission (Strongly Recommended)? What will help you determine whether a submission passed a threshold of acceptable quality? Please include any relevant code contribution guidelines/standards, etc. Is there any criteria?

How will we ultimately decide the winner/winners from all valid submissions? Typically clean successful PR merge? First valid submission received? Best submission meeting some criteria by the deadline? 

We review the submissions as early as possible (sometimes immediately upon submission) to ensure prompt winner announcement and payout.

### Prerequisites

What prerequisite knowledge does this bounty require? What specific topics does someone need to know about before they can start work? Is there setup required before they can begin work? If so, what do they need to do?

### Time Expectation
 2 days ago | October-24-2021 03:41:19 PM +3.5 UTC | Confirmed within 4.5 seconds

### Category

_Front End, Back end, Design, Documentation or Other_

### Project Type

- *Traditional - One contributor, one person paid*
- *Contest - Multiple people can contribute, one person is paid*
- *Cooperative - multiple people can contribute, multiple people are paid*

### Permissions

- *Approval Required: Bounty hunters should be approved before starting work*
- *Permissionless: No approval required*

### Experience Lever

Beginner, Intermediate or Advanced

### Bounty Type

Bug, Feature, Improvement, Security, Documentation, Design, Code Review, Other

### Expiration

When does this bounty expire? (if applicable)

### Resources

Link any relevant resources (e.g. specific documentation, source code that may be useful)

**Comment by critesjosh** [comment]
If you need support please reach out on discord. You can join discord at https://chat.celo.org
