### ISSUE TITLE
ODIS Quota Improvements

### ISSUE THREAD

**Issue by codyborn** [celo-org/celo-monorepo#8865]
@nategraf found that ODIS quota calculation is really easy to generate and should be made harder.

https://www.notion.so/clabsco/Attacks-on-ODIS-88a2f254d11a4c96b882df199502aa2e#3b441ec11e9744418df39cbc4c2cc580

- Track quota for both account and EOA
- Base quota off fees paid
- Remove quota for unverified users? (estimate impact on good users)

**Comment by arthurgousset** [comment]
@alecps - Closing this ticket in favour of new ODIS rate limiting ticket @eelanagaraj will create
- #9703
