### ISSUE TITLE
ODIS: Base quota off fees paid (investigation)

### ISSUE THREAD

**Issue by codyborn** [celo-org/celo-monorepo#8873]
See [Notion doc](https://www.notion.so/clabsco/Attacks-on-ODIS-88a2f254d11a4c96b882df199502aa2e#3b441ec11e9744418df39cbc4c2cc580) for more details.

Investigate potential designs and trade-offs. How do signers reliably track fees paid over time? Should we estimate the cost in USD?

**Comment by alecps** [comment]
Closing in favor of https://www.notion.so/clabsco/ODIS-Rate-Limit-v2-2d3e7bcf01cf4fd19f00b1542ae862b9
