### ISSUE TITLE
Track quota against identifier

### ISSUE THREAD

**Issue by codyborn** [celo-org/celo-monorepo#8875]
See [Transferring attestations to abuse the verification bonus](https://www.notion.so/clabsco/Attacks-on-ODIS-88a2f254d11a4c96b882df199502aa2e#7f37ca9de23647b8974a1f7ca9483fa4) section for more details.

**Comment by arthurgousset** [comment]
@codyborn Is this possibly a duplicate of #8872 ? cc @alecps

**Comment by alecps** [comment]
Not a duplicate of #8872 but closely related
