### ISSUE TITLE
Watch product review recording and slides

### ISSUE THREAD

**Issue by ag-clabs** [celo-org/celo-monorepo#8913]
# References

- [Recording](https://drive.google.com/file/d/1Bkb6x7bjjYWM-8R6Z8mHbPSztiEMUTdy/view)
- [Slides](https://docs.google.com/presentation/d/16xyfKppER-tlXJbLj6xB7EWS5sDZr5DygPw3dB_Ed2k/edit#slide=id.p)

**Comment by 0xarthurxyz** [comment]
Closing this ticket because I watched the recording back today.
