### ISSUE TITLE
[Payments] Payment SDK User Documentation

### ISSUE THREAD

**Issue by nicolasbrugneaux** [celo-org/celo-monorepo#8918]
Documentation for how to use the payments SDK

**Comment by aslawson** [comment]
@nicolasbrugneaux I forget what was the remaining work on this?

I remember we wanted documentation for two groups:
- users of payments sdk
- developers of sdk

Is there anything remaining here?

**Comment by nicolasbrugneaux** [comment]
I'm not entirely sure anymore, the CLI is documented and there's a readme to collaborate, so that clears the developers of the sdk. But there's no documentation for the end users of the sdk
