### ISSUE TITLE
Add margins and background color to Tab Bar 

### ISSUE THREAD

**Issue by coreycelo** [celo-org/celo-monorepo#894]
### Expected Behavior

<img width="1103" alt="tab_spacing" src="https://user-images.githubusercontent.com/51388535/64573135-0ef69a00-d31f-11e9-9412-bfc6e2a67102.png">

Tab Bar pulls the margins (pink) in from the rest of the UI—this is currently 16px. Tabs split remaining space equally and icons/labels are centered vertically/horizontally within the tab.

We've also added a slightly darker bg color (#FAFCFF).

[Figma link](https://www.figma.com/file/E3kgMuySj6gDboO3HdU9cixK/Wallet-3.0?node-id=986%3A4151)

### Current Behavior

Tab bar has white bg and no margins.

**Comment by annakaz** [comment]
Closing out outdated issues
