### ISSUE TITLE
Use new WalletConnect V1 Wrapper in use-contractkit

### ISSUE THREAD

**Issue by aslawson** [celo-org/celo-monorepo#8963]

**Comment by nicolasbrugneaux** [comment]
As @aslawson  suggested, for the short term, let's hard code the wallet id <-> version  mapping

**Comment by dckesler** [comment]
Amy to follow up with Celo Dance on which version of WC they use

**Comment by aslawson** [comment]
Hard code to use v1:
Valora ✅
Celo Terminal ✅
Celo Dance ❓ ( @aslawson to find out)
Celo Wallet ❓ ( @nicolasbrugneaux to check with @jmrossy )
