### ISSUE TITLE
[Tracking] Celo Camp 4: Demo Day

### ISSUE THREAD

**Issue by ag-clabs** [celo-org/celo-monorepo#8979]
# Context

ID specific **action items** relating to celo camp demo day
See notes [here](https://www.notion.so/clabsco/Celo-Camp-Demo-Day-a8b2cad62c4d446f89b200a523f3f2b6)

Todo 
- [x] #8975
- [x] https://github.com/celo-org/celo-monorepo/issues/9221
- [x] https://github.com/celo-org/celo-monorepo/issues/9226

**Comment by 0xarthurxyz** [comment]
Closing this because all todos are complete
