### ISSUE TITLE
Users SBAT scan QR codes faster

### ISSUE THREAD

**Issue by cmcewen** [celo-org/celo-monorepo#898]
### Expected Behavior

QR codes scan fast

### Current Behavior

Slower than other apps

**Comment by annakaz** [comment]
In the Philippines pilot we noticed that the Celo QR code had a finer grained grid than other app's QR codes. Not sure if this is because of the library we're using or because we are encoding more information than other apps

**Comment by rohit-dua** [comment]
Related #1131
