### ISSUE TITLE
Multiple keccak256

### ISSUE THREAD

**Issue by aaronmgdr** [celo-org/celo-monorepo#8986]
### Expected Behavior
One Import to Rule them ALL

### Current Behavior

I See `keccak256` imported from many different libraries this seems inefficient. in the utils package alone three separate packages are used for keccack256. 

It looks like the plurality come from `ethereumjs-util`

###  examples from around monorepo

packages/sdk/identity/src/offchain/utils.ts
`import { keccak256 } from 'ethereumjs-util'`

 packages/sdk/utils/src/bls.ts
`const keccak256 = require('keccak256')` 

packages/sdk/wallets/wallet-base/src/signing-utils.ts
```
import { account as Account, bytes as Bytes, hash as Hash, RLP } from 'eth-lib'

export function getHashFromEncoded(rlpEncode: string): string {
  return Hash.keccak256(rlpEncode)
}

```
packages/sdk/contractkit/src/wrappers/Accounts.ts
`import { keccak256 } from 'web3-utils'`

![Screen Shot 2021-11-17 at 3 52 47 PM](https://user-images.githubusercontent.com/3814795/142300790-94e4407a-5d0c-434c-841c-4314ad90fc29.png)

**Comment by aslawson** [comment]
@aaronmgdr did you mean to assign to me. is this something you are working on or want to be included in Application's backlog?
