### ISSUE TITLE
[M02] Incorrect token initialization data

### ISSUE THREAD

**Issue by cylon56** [celo-org/celo-monorepo#8999]
### Incorrect token initialization data

In [PR #8831](https://github.com/celo-org/celo-monorepo/pull/8831), the `migrationsConfig.js` file is updated to include initialization data for the deployment of the `StableTokenBRL`. 

This initialization data is [incorrectly set](https://github.com/celo-org/celo-monorepo/pull/8831/files#) to be a copy of the `StableTokenEUR` initialization data. Specifically the `tokenName` and `tokenSymbol` are set incorrectly to `Celo Euro` and `cEUR`.

This incorrect token initialization will not affect the inner logic and accounting of the token itself. However, this mislabelling can cause errors in indexing this token in exchanges, and will likely confuse users which can greatly affect its utility and adoption.

Consider updating the `migrationsConfig.js` to have appropriate `tokenName` and `tokenSymbol` set specific to the `StableTokenBRL`. 

_Part of the OpenZeppelin Release 6 Audit: @georgercarder @clarkhenry_

**Comment by martinvol** [comment]
As a clarification, wanted to point out that file is only used for testing proposals and not for mainnet (not even testnets).
