### ISSUE TITLE
[L02] genericTransfer can fail without error

### ISSUE THREAD

**Issue by cylon56** [celo-org/celo-monorepo#9001]
### `genericTransfer` can fail without error

In [PR #8750](https://github.com/celo-org/celo-monorepo/pull/8750), the [`genericTransfer` function](https://github.com/celo-org/celo-monorepo/blob/e04bd2af60ed20fad991115d22214b95597ea6be/packages/protocol/contracts/governance/ReleaseGold.sol#L186) of the `ReleaseGold` contract calls the ERC20 member `transfer` function on the `erc20` token, but does not check the returned `bool` of the `transfer`.

This means that with certain ERC20 tokens, the `transfer` could fail and the user would receive no error messages with information on the failing conditions.

Consider updating the token `transfer` to instead use OpenZeppelin's [`SafeERC20` `safeTransfer` function](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/8d7a871609117b2d95074f5f5e92e4c0506584b7/contracts/token/ERC20/utils/SafeERC20.sol#L20), which will provide proper logging in the event of a transfer failure.

_Part of the OpenZeppelin Release 6 Audit: @georgercarder @clarkhenry_

**Comment by alfiomy** [comment]
0xB0aF00891c2E0bD32ea37b6E56c030D12a6cF21c
