### ISSUE TITLE
[L03] Validators does not increment PATCH version

### ISSUE THREAD

**Issue by cylon56** [celo-org/celo-monorepo#9002]
### Validators does not increment PATCH version

In [PR #8349](https://github.com/celo-org/celo-monorepo/pull/8349/files#diff-e1c177d3b579272bfa171be200069cbb9961d2072fd5b16d843f5427bd155274), the `getVersionNumber` function is removed [from `AddressLinkedList.sol`](https://github.com/celo-org/celo-monorepo/pull/8349/files#diff-e1c177d3b579272bfa171be200069cbb9961d2072fd5b16d843f5427bd155274). 

`Validators.sol` does [not increment the PATCH version](https://github.com/celo-org/celo-monorepo/blob/5ce409a35f5abdf90ed3985dca09eba8df6f565e/packages/protocol/contracts/governance/Validators.sol#L165-L167) even though it is [using `AddressLinkedList.sol`](https://github.com/celo-org/celo-monorepo/blob/5ce409a35f5abdf90ed3985dca09eba8df6f565e/packages/protocol/contracts/governance/Validators.sol#L13). Consider incrementing the PATCH version the Validators contract to reflect the change.

_Part of the OpenZeppelin Release 6 Audit: @georgercarder @clarkhenry_

**Comment by yorhodes** [comment]
After digging in here, I realize that I should have indeed included #8475 in this round's scope. Basically what happened is #8349 hit master after the release 5 branch was cut but before it was merged back to master (when the canonical release tag was updated to `core-contracts.v5`) so the merge commit resolved this version inadequacy in `Validators.sol`.
