### ISSUE TITLE
[N01] addStorageRoot can add duplicate URLs

### ISSUE THREAD

**Issue by cylon56** [celo-org/celo-monorepo#9003]
### `addStorageRoot` can add duplicate `url`'s

In [PR #8360](https://github.com/celo-org/celo-monorepo/pull/8360), the [`addStorageRoot` function](http://github.com/celo-org/celo-monorepo/blob/c1f72b8918d8d6f1da2d988afd410bbd0ebad96a/packages/protocol/contracts/common/Accounts.sol#L250) of the `Accounts` contract adds `url`'s to an `offchainStorageRoots` array for the `msg.sender`'s `account`.

This function does not check whether the `url` already exists in the array so there can be duplicate entries added.

This does not pose a security risk. However, it can result in unnecessary gas expenditure. Furthermore the resulting redundant data returned by the [`getOffchainStorageRoots` function](http://github.com/celo-org/celo-monorepo/blob/c1f72b8918d8d6f1da2d988afd410bbd0ebad96a/packages/protocol/contracts/common/Accounts.sol#L279) can confuse offchain clients and add computational complexity to the processing of this data.

Consider using OpenZeppelin's [`EnumerableMap`](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v4.3.3/contracts/utils/structs/EnumerableMap.sol) as a more practical solution than an array. 

_Part of the OpenZeppelin Release 6 Audit: @georgercarder @clarkhenry_

**Comment by yorhodes** [comment]
These duplicates can be checked for on the client side easily, both as a check before adding a duplicate or as a filter on the returned storage roots. To avoid complicating and inflating the cost of the storage root logic, we will not make a change to address this at this time.
