### ISSUE TITLE
Migrate attestation service data tables from eksportisto 14 -> newest eksportisto

### ISSUE THREAD

**Issue by eelanagaraj** [celo-org/celo-monorepo#9051]
Should be only minor changes, but migrating to the newest version would be best as this is expected to be more reliable and has alerting/monitoring set up (where eks14 does not).

Possible that this is super fast and requires only minimal modifications to the tables. Added some buffer in case there are discrepancies between the old and new versions that need to be investigated.

cc @tobikuhlmann

EDIT: eksportisto 14 has unexpectedly stopped receiving data so moving this ticket up in terms of priority.

TODOs:
- [x] migrate views to use eksportisto data instead of eksportisto_14 data
- [x] data checks to make sure we are deduplicating appropriately and no unexpected, unaccounted for rows/values in or not in the new tables
- [x] potentially simplify or stop using the mixed "frozen data" from before as this should no longer be necessary
- [ ] (optional) consider creating a set of "mini-views" for better metabase performance (i.e. limiting base tables to most recent 2 months and going from there)

**Comment by 0xarthurxyz** [comment]
cc @pedro-clabs (for visibility).
For context, Pedro shut down eks11 today and is officially maintaining “eksportisto with no version” (until it’s owned by the data services team and/or completely deprecated in favour of blockscout in the future).
