### ISSUE TITLE
Ingest Oracle prod metrics in Grafana Cloud

### ISSUE THREAD

**Issue by lvpeschke** [celo-org/celo-monorepo#9055]
All metrics required for monitoring (dashboard, alerting, troubleshooting) should be available in the clabs instance of Grafana. See https://github.com/celo-org/celo-oracle-old/issues/320 for history.
See https://www.notion.so/clabsco/Prometheus-on-Grafana-and-off-Stackdriver-bf4283297f1b4bc789fb433afd71ac16.

Attention: the metrics should be reviewed before ingestion in light of https://github.com/celo-org/data-services/issues/50.

How? By adding a `remote_write` stanza to the Prometheus config: https://github.com/celo-org/celo-monorepo/blob/6296ca4fda942da108ce95b298047b04e8dd3bb7/packages/helm-charts/prometheus-stackdriver/templates/configmap.yaml#L31-L41

**See https://github.com/celo-org/celo-monorepo/issues/9100 for more deployment details.**

**Comment by lvpeschke** [comment]
Blocker: deprecated k8s version in use (1.17)

**Comment by jcortejoso** [comment]
Updated the oracle's clusters in `mainnet-oracles-westus2` and `mainnet-oracles-westeurope` (production clusters).
