### ISSUE TITLE
Clean up Azure access

### ISSUE THREAD

**Issue by codyborn** [celo-org/celo-monorepo#9060]
Remove folks who have left the company - especially those in the PIM approver set

**Comment by codyborn** [comment]
Proposed list for removal
- Alex Harley
- c
- carlinho?
- carlos rienzi?
- charles_redlion?
- cmcewen
- conner
- deepak
- dluke_redlion?
- emil.hotkowski
- emily
- erin?
- jason.rudianto
- jonch
- judy
- kevin
- rossy
- silas

**Comment by BenAtClabs** [comment]
Added Yorke to the list, 20 users deleted.
