### ISSUE TITLE
[ASv2] Protocol Design

### ISSUE THREAD

**Issue by isabellewei** [celo-org/celo-monorepo#9064]
new smart contract registry, design found in [notes](https://www.notion.so/clabsco/NYC-Offsite-Nov-2021-7ceaa4f764324a62a46c67a19b70818b#3124cb1710064ef19fab5aab607e8c0d)

- [ ] Modular verification pattern ?
- [ ] Attestation struct claim + reading
- [ ] Revocability -> add small section justifying punting
- [ ] Final review and link to other doc  (or, alternatively, add claims/identifiers work here)

**Comment by arthurgousset** [comment]
Notes from conversation: 
- @alecps would like to do more reading ahead of a convo
- then consider asking Spruce for advice in chat (around Friday)
