### ISSUE TITLE
Ingest ODIS metrics in Grafana Cloud

### ISSUE THREAD

**Issue by lvpeschke** [celo-org/celo-monorepo#9100]
## Overview

All metrics required for monitoring (dashboard, alerting, troubleshooting) should be available in the clabs instance of Grafana.
See https://www.notion.so/clabsco/Prometheus-on-Grafana-and-off-Stackdriver-bf4283297f1b4bc789fb433afd71ac16.

### Details

- [x] (1) Prometheus metrics from the ODIS Signer clusters (example: [the ones used for this dashboard](https://console.cloud.google.com/monitoring/dashboards/builder/7d9c15f3-fcd5-45b5-b4c9-117d432fb518?project=celo-pgpnp-mainnet&timeDomain=1h&dashboardBuilderState=%257B%2522editModeEnabled%2522:false%257D))
- [X] (2) Logs from the ODIS Signer clusters
- [X] (3) Google Cloud Monitoring data (metrics, log-based metrics) from the ODIS combiner
- ~~[ ] (4) GCP Cloudfunctions logs, TBD if relevant, see also https://github.com/celo-org/data-services/issues/70 [not a hard requirement, no dashboards or alerts depend on it]~~ (Update: This requirement has been split into it's own ticket here https://app.zenhub.com/workspaces/identity-backlog-board-60e61301c3dc55000e540b61/issues/celo-org/celo-monorepo/9378) 

Once steps 1-3 are complete, identity team will work on recreating + codifying dashboards / alerts as captured in this ticket https://app.zenhub.com/workspaces/identity-backlog-board-60e61301c3dc55000e540b61/issues/celo-org/celo-monorepo/9523  

### How?

1. Deploy the Prometheus Helm chart using celotool in the clusters:

```bash
ENV=<fill in>  # alfajores, baklava, rc1
CONTEXT=<find the context>  # see the .env files for valid ones
INIT_OR_UPGRADE= <fill in>  # initial if no prometheus is deployed, upgrade if there is one (check with: helm list -n prometheus)
# --deployGrafana adds a local Grafana instance to the cluster which can make it easier to inspect metrics locally and troubleshoot forwarding issues
celotool deploy ${INIT_OR_UPGRADE:?} prometheus -e {ENV:?} --context ${CONTEXT:?} --deployGrafana --verbose --helmdryrun
```

When inspecting the diff (or the preview), make sure that the prometheus-server-conf ConfigMap has a `remote_write` stanza with the Grafana Cloud credentials from the .env.mnemonic files

NOTE: this change will initially preserve the export to stackdriver. There is a flag `--disableStackdriver` defaulting to `false` which controls this setting. Have a look at the output of the dry-run to assert whether the stackdriver sidecar is included and whether that reflects what you expect.

2. Deploy the Promtail Helm chart using celotool in the clusters:

```bash
ENV=<fill in>  # alfajores, baklava, rc1
CONTEXT=<find the context>  # see the .env files for valid ones
INIT_OR_UPGRADE= <fill in>  # initial if no prometheus is deployed, upgrade if there is one (check with: helm list -n prometheus)
celotool deploy  ${INIT_OR_UPGRADE:?} promtail -e {ENV:?} --context ${CONTEXT:?} --verbose --helmdryrun
```

3. Connect the relevant projects through a Grafana datasources: https://grafana.com/docs/grafana/latest/datasources/google-cloud-monitoring/.

**Comment by jcortejoso** [comment]
For upgrading prometheus and promtail with celotool we probably will need to also upgrade Kubernetes clusters to 1.20.

**Comment by lvpeschke** [comment]
Alfajores clusters upgraded to k8s v1.21 (see https://github.com/celo-org/infrastructure/issues/156) and new prometheus-stackdriver release deployed.

Metrics are going to
- Grafana Cloud: https://clabs.grafana.net/goto/mThfX5lnk?orgId=1 (examples)
- Google Cloud monitoring: https://console.cloud.google.com/monitoring/dashboards/builder/3a138c25-d9c4-4166-8ef0-8b3ebed75d77?project=celo-phone-number-privacy&dashboardBuilderState=%257B%2522editModeEnabled%2522:false%257D&timeDomain=1h (dashboards are updating)

**Comment by lvpeschke** [comment]
Alfajores and Mainnet logs are also enabled on Grafana Cloud: https://clabs.grafana.net/goto/kV9M9clnz?orgId=1.

Missing staging.

**Comment by lvpeschke** [comment]
Staging logs enabled. One thing that might need further work is that the cluster name is not automatically exported as a log label and unlike in GCP, Azure doesn't put it into the node names.

EDIT: log label for cluster_name was added in https://github.com/celo-org/celo-monorepo/pull/9551.

**Comment by lvpeschke** [comment]
Mainnet metrics enabled.

**Comment by lvpeschke** [comment]
All logs (staging, alfajores, mainnet) redeployed to include the cluster_name label.
