### ISSUE TITLE
[celo-monorepo] Upgrade to a newer version of node.

### ISSUE THREAD

**Issue by dckesler** [celo-org/celo-monorepo#9103]
Currently the mono-repo is officially on node 12 which reaches end of life in April 2022. We should upgrade everything to a newer node version. This includes package.jsons, nvmrcs, node related packages, ci pipelines, and anything else that could be broken after upgrading

**Comment by istx25** [comment]
I'll start looking into this!

**Comment by aaronmgdr** [comment]
replaced with #9519
