### ISSUE TITLE
ODIS Logs and Metrics to Grafana

### ISSUE THREAD

**Issue by codyborn** [celo-org/celo-monorepo#9118]
https://app.zenhub.com/workspaces/identity-backlog-board-60e61301c3dc55000e540b61/issues/celo-org/celo-monorepo/9100

**Comment by alecps** [comment]
We should also migrate the Signer logs, which are currently stuck in Azure

**Comment by alecps** [comment]
Closing in favor of https://app.zenhub.com/workspaces/identity-backlog-board-60e61301c3dc55000e540b61/issues/celo-org/celo-monorepo/9100

**Comment by arthurgousset** [comment]
@alecps - Closing this because work is complete
