### ISSUE TITLE
Look into MessageBird routing and update our 10DLC guidance if necessary.

### ISSUE THREAD

**Issue by eelanagaraj** [celo-org/celo-monorepo#9142]
There is some indication that MB's internal SMS routing based on phone numbers is not at all intelligent. A validator on Discord reported receiving strange 10DLC registration warning messages despite having purchased a US toll-free number. It seems like MB cannot properly select to use the toll-free number since there is another US phone number present.

Possible advice (short-term) is to remove the US phone number and only have a US toll-free number (to serve the US) and Canadian number (to serve Canada + global traffic). Even still, we should better understand if MB is routing in this assumed way ^, or if it triggers errors by sending with an incorrect number (i.e. tries to send to Canada via both the US and Canadian numbers, though the first will be blocked).

[Relevant Discord link](https://discord.com/channels/600834479145353243/882328092608172072/921473159574716448).

TODOs:
- [ ] small data investigation: can we gain insight into whether MB is routing intelligently?
- [x] update guidance for 10DLC if necessary, communicate this with validators

**Comment by eelanagaraj** [comment]
Looked into this + checked out MB's docs on this and the old thread.

Should be addressed by:
- docs changes & config change in PR #9363
- added some guidance to the MessageBird section of our Notion docs on this (which is now linked in the AS docs)
- posted on Discord asking Validators to double check their configs
- added a note to our on-call runbooks for how to look out for these messages; use this info going forwards to get better information about our MB guidance and make sure new validators are set up properly

cc @0xarthurxyz for visibility

**Comment by arthurgousset** [comment]
Thank you @eelanagaraj 🙏
