### ISSUE TITLE
cREAL Forever Pending Transactions (on Alfajores)

### ISSUE THREAD

**Issue by phelipebf** [celo-org/celo-monorepo#9149]
### Expected Behavior

Using the code below for transactions with CELO, cUSD and cEUR everything works fine.

```
let token = await contractkit.contracts.getStableToken('cUSD');

await token
        .transfer(to, amount)
        .send({ from, gasPrice, feeCurrency: token.address });
```

### Current Behavior

However using same code with cREAL, transactions are [pending forever](https://alfajores-blockscout.celo-testnet.org/tx/0x8024ec126ff428ba63a05fff8591880ec6802d1753ceb7640372f238c4f27b89). 

```
let token = await contractkit.contracts.getStableToken('cREAL');

await token
        .transfer(to, amount)
        .send({ from, gasPrice, feeCurrency: token.address });
```

Looks like `gasPrice` and `feeCurrency` parameters combined are causing the problem.

If use `gasPrice` alone or `feeCurrency` alone [this works](https://alfajores-blockscout.celo-testnet.org/tx/0xb7d2c99516ec1b6b44cb3d46860a20f482314c8619e888b541b0fa297b0e8993).

**Comment by martinvol** [comment]
Thanks for flagging! 

I am investigating why this is happening, although I think worth noting that I am not aware of this issue happening on mainnet.

Can you share the value of `gasPrice` you're using? It could be that it's simply too low.

**Comment by martinvol** [comment]
Actyally, could you try to multiply `gasPrice` by 7? Because cREAL is roughly worth 7 times less than cUSD/cEUR.

Let me know how that goes.

**Comment by ericnakagawa** [comment]
@phelipebf Were you able to get your cREAL tx processing?

**Comment by phelipebf** [comment]
After some adjustments of fee calcs and tests directly on the mainnet (tsc), we were able to make it work. Thanks!
