### ISSUE TITLE
Users SNBAT to see a blank screen when long pressing the send tab '+'

### ISSUE THREAD

**Issue by jeanregisser** [celo-org/celo-monorepo#919]
### Expected Behavior

Long pressing the send tab ('+') doesn't do anything special.

### Current Behavior

Long pressing the send tab ('+') displays a blank screen:

![image](https://user-images.githubusercontent.com/57791/64679663-770ec280-d47c-11e9-9856-154a0856ccaa.png)

**Comment by jmrossy** [comment]
Dupe of #466
