### ISSUE TITLE
Investigate removing Reserve.addToken oracle check

### ISSUE THREAD

**Issue by martinvol** [celo-org/celo-monorepo#9195]
In order to add StableTokens in one proposal, it should be possible to add call Reserve.addToken before an oracle was ever sent.

If it is possible, then code written for https://github.com/celo-org/celo-monorepo/issues/7315 should be discarded and not merged.

Worth checking investigate also how the blockchain will behave in case there's a pre-mint and the pre-mint address wants to execute a transfer before the oracles are turned on.

**Comment by m-chrzan** [comment]
Some research so far:

The oracle check in `addToken` was originally added in [this PR](https://github.com/celo-org/celo-monorepo-old/pull/3417). The related issue is [here](https://github.com/celo-org/celo-monorepo-old/issues/3416), so it sounds like the change was necessary at the time for contract migrations to work with celo-blockchain. I'm having a hard time understanding why that particular check would have been necessary at the time and whether or not it's still necessary now or if it's safe to remove.

Not everyone has access to that repo, so copying some of the details from the issue:

> Currently failing when sending gold to the reserve since the medianator is not registered.
> Solution:
> * getAddressFor used by geth, getAddressForOrDie used by SCs
> * Medianator deployed before reserve
> * Exchange rate added for dollars before dollars added to reserve
> * Check non-null exchange rate when adding token to the reserve

Note: the medianator was part of a prior implementation of oracles that has since been replaced with SortedOracles. "Gold" refers to CELO.

**Comment by m-chrzan** [comment]
These are the only uses of `isToken` and `getTokens` in the monorepo contracts:

```
$ ag "(isToken|getTokens)" contracts/
contracts/stability/interfaces/IReserve.sol
12:  function getTokens() external view returns (address[] memory);

contracts/stability/Reserve.sol
36:  mapping(address => bool) public isToken;
83:    require(isToken[token], "token addr was never registered");
227:    require(!isToken[token], "token addr already registered");
228:    isToken[token] = true;
250:    isToken[token] = false;
442:  function getTokens() external view returns (address[] memory) {
```
And in the celo-blockchain repo:
```
$ ag "(\bisToken\b|\bgetTokens\b)"
signer/fourbyte/4byte.go
14980:"19f37361": "isToken(address)",
21481:"2570e31e": "getTokens(uint256,address)",
25464:"2c512d6e": "getTokens(address,uint256)",
39611:"450efe21": "getTokens(address)",
42051:"494cfc6c": "getTokens(uint256,uint256)",
46625:"5127ad4c": "getTokens(address,uint256,uint256,uint256,uint256)",
57777:"64d414bf": "getTokens(uint256,uint256,uint256)",
97492:"aa6ca808": "getTokens()",
108957:"be571e8f": "getTokens(address,bytes32,uint256)",
121403:"d3c9cc26": "getTokens(uint256)",
137047:"eee94805": "getTokens(uint256,uint256,bool)",
137092:"eefa597b": "isToken()",

signer/fourbyte/4byte.json
14931:"19f37361": "isToken(address)",
21432:"2570e31e": "getTokens(uint256,address)",
25415:"2c512d6e": "getTokens(address,uint256)",
39562:"450efe21": "getTokens(address)",
42002:"494cfc6c": "getTokens(uint256,uint256)",
46576:"5127ad4c": "getTokens(address,uint256,uint256,uint256,uint256)",
57728:"64d414bf": "getTokens(uint256,uint256,uint256)",
97443:"aa6ca808": "getTokens()",
108908:"be571e8f": "getTokens(address,bytes32,uint256)",
121354:"d3c9cc26": "getTokens(uint256)",
136998:"eee94805": "getTokens(uint256,uint256,bool)",
137043:"eefa597b": "isToken()",

mycelo/contract/gen_abis.go
16437:      "name": "isToken",
17083:      "name": "getTokens",
```
In other words, the state protected by this check is not used for anything useful.

**Comment by martinvol** [comment]
Martin did this and was included in the audit for CR7 (that merged CR7 and what we called CR8)
