### ISSUE TITLE
Mento exchange quotes are inverted when called using the contract kit 

### ISSUE THREAD

**Issue by Jesse-Sawa** [celo-org/celo-monorepo#9211]
### Expected Behavior

Fetching quote stable buy using the contract kit i.e. 

```
    const kit = newKit(CELO_RPC);
    kit.defaultAccount = publicKey;
    kit.addAccount(privateKey);
    const mentoExchange: ExchangeWrapper = await kit.contracts.getExchange(
        StableToken.cUSD,
    );
    mentoExchange.quoteStableBuy(convertToWei(stableAmount))

```
should return the amount of celo a user would need to exchange to receive the `stableAmount` of stable token.

### Current Behavior

`quoteStableBuy` returns the value `quoteGoldBuy` should return (the amount of stable token a user would need to exchange to receive the buyAmount of CELO. And Vice versa.

version: "@celo/contractkit": "^1.3.3",

**Comment by aaronmgdr** [comment]
Since @martinvol is removing this code from thee repo im closing
