### ISSUE TITLE
[ASv2 MVP] Meet with release engineering team re: infra design

### ISSUE THREAD

**Issue by eelanagaraj** [celo-org/celo-monorepo#9222]
Check-in with the release/devOps team on:
- overview of current roadmap -- anything that is missing here?
- best practices for service design
- anything we should know about infra + service setup or things we should consider?
- how should we continue working together during the infra design + implementation phase?
  - (is there any way we can help you develop the release team's best practices + advising process?)

**Comment by lvpeschke** [comment]
Initial thoughts:

- need for a clear transition plan from v1 to v2

- excellent opportunity to start creating a production readiness checklist, which would cover at least the following (some references: https://sre.google/sre-book/service-best-practices/, https://www.opslevel.com/blog/production-readiness-in-depth/)
  - SLI / SLO / SLA
  - testing: unit, integration, e2e, performance/load/stress, chaos
  - desired CI/CD pipeline (build strategy, testing strategy, stages, deployment)
  - monitoring: metrics + logs + traces, dashboards, alerts
  - incident management: runbooks, risk assessment, mitigation strategies (eg: graceful degradation), escalation path
  - security: secrets, static/dynamic analysis, dependencies
  - capacity planning: resource needs, growth expectation, provisioning strategy (compute, storage, networking, misc)
  - documentation

- would be good to have more eyes on the infra review depending on what components make it into the design

**Comment by lvpeschke** [comment]
Meeting notes: https://www.notion.so/clabsco/ASv2-ID-DevOps-Release-dcb76801f82e400fb8a42b8157493c3f
