### ISSUE TITLE
[Feature Request] Revocable phone number mappings

### ISSUE THREAD

**Issue by 0xarthurxyz** [celo-org/celo-monorepo#9274]
Closing this ticket in favour of a Github Discussion topic (to collect feedback and votes before prioritising). Can always re-open ticket when necessary: 

- #9299

**Comment by arthurgousset** [comment]
Closing this ticket in favour of this Github Discussion entry #9299 (to collect feedback and votes before prioritising). Can always re-open ticket when necessary.
