### ISSUE TITLE
[Feature Request] Balance privacy

### ISSUE THREAD

**Issue by 0xarthurxyz** [celo-org/celo-monorepo#9277]
Closed this ticket in favour of the discussion topic:
- https://github.com/celo-org/celo-monorepo/discussions/9293

### User story

If solved, I cannot see a user's Celo balance (tokens) because I know their phone number.

**Comment by arthurgousset** [comment]
Closing this ticket in favour of the discussion topic here: [Feature Request: Balance privacy for accounts with a phone number mapping #9293](https://github.com/celo-org/celo-monorepo/discussions/9293)
