### ISSUE TITLE
[Feature Request] Selective disclosure

### ISSUE THREAD

**Issue by 0xarthurxyz** [celo-org/celo-monorepo#9278]
Closed this ticket in favour of the Discussion topic here:

- https://github.com/celo-org/celo-monorepo/discussions/9294

**Comment by arthurgousset** [comment]
Closing this ticket in favour of the Discussion topic here: [Feature Request: Read-only disclosure of private balances ("selective disclosure") #9294](https://github.com/celo-org/celo-monorepo/discussions/9294)
