### ISSUE TITLE
[Feature Request] Pass identity data through WalletConnect

### ISSUE THREAD

**Issue by 0xarthurxyz** [celo-org/celo-monorepo#9279]
Closed this ticket in favour of this Github Discussion topic: 

- https://github.com/celo-org/celo-monorepo/discussions/9305 

This clears up our backlog until this becomes a priority.

**Comment by arthurgousset** [comment]
Closing this ticket in favour of this Github Discussion topic: [Feature Request: Pass identity data through WalletConnect #9305](https://github.com/celo-org/celo-monorepo/discussions/9305). This clears up our backlog until this becomes a priority.
