### ISSUE TITLE
Link on withdraw funds screen goes to wrong place

### ISSUE THREAD

**Issue by lukasawagner** [celo-org/celo-monorepo#9301]
![File (6).jpg](https://images.zenhubusercontent.com/614a1c3f0fad65061c33b5a9/494755c6-bbc5-484d-a4c8-ef4db2a34616)

The link on this screen goes to the wrong place, we want it to go to this page: https://support.valoraapp.com/hc/en-us/categories/360006359592

**Comment by asharma13524** [comment]
@lukasawagner do you know where this code lives? I could not find it in this repo (celo-monorepo) upon a cursory glance.
