### ISSUE TITLE
Devs SBAT see mobile logs in Stackdriver and be alerted when they are not flowing

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-monorepo#932]
-[] Make sure mobile logs are uploaded to firebase cloud storage
- [] check permissions on cloud storage and make sure logs are private to Celo Labs
- [] check data flow job is correctly exporting to SD logging
- [] create log-based alerts on count of entries, and add dashboard view and alert in integration for count=0
- [] copy-policies to all other environments

**Comment by jcortejoso** [comment]
I can help with this issue.

**Comment by jcortejoso** [comment]
Regarding the point `[ ] check data flow job is correctly exporting to SD logging`:
After checking with @rohit-dua  some of the Stackdriver documentation I have not seen a clean way. Maybe would be possible to create an Apache Beam project with Dataflow as runner and in the code read the logs from cloudstorage and log directly to StackDriver, but does not seems very clean and also would affect the format. 
AFAIK and I think I have understood, logs should be directly saved in Stackdriver using [@google-cloud/logging](https://www.npmjs.com/package/@google-cloud/logging) or [GoogleCloudPlatform/stackdriver-errors-js](https://github.com/GoogleCloudPlatform/stackdriver-errors-js), and from there logs can be exported easily to cloud storage. Once you have the logs on Stackdriver we can create the alerts, dashboards, and so on.

**Comment by rohit-dua** [comment]
Fixed the script to stream logs into SD. PR:https://github.com/celo-org/celo-monorepo/pull/1055

Added [metric](https://console.cloud.google.com/logs/viewer?advancedFilter=resource.type%3D%22global%22%0AjsonPayload.bundleId%3D(%22org.celo.mobile.staging%22%20OR%20%22org.celo.mobile.integration%22%20OR%20%22org.celo.mobile.debug%22%20OR%20%22org.celo.mobile.pilot%22%20OR%20%22org.celo.mobile.alfajores%22)&project=celo-testnet&organizationId=54829595577&resource=dataflow_step%2Fjob_id%2F2019-09-19_06_37_36-16811382895122532808&minLogLevel=0&expandAll=false&timestamp=2019-09-19T16:13:58.804000000Z&customFacets=&limitCustomFacetWidth=true&dateRangeStart=2019-09-19T15:13:59.055Z&dateRangeEnd=2019-09-19T16:13:59.055Z&interval=PT1H&scrollTimestamp=2019-09-19T16:13:58.494000000Z) for all envs 

Created new data flow and deleted the old ones.https://console.cloud.google.com/dataflow?organizationId=54829595577&project=celo-testnet

Added alerts for more than 10 errors/minute and less than 1 log entry in 23.5 hours
https://app.google.stackdriver.com/policies?project=celo-testnet&f.search=client

The dashboards could not be updated as there is a limit of 25 charts per dashboard(which is filled)
