### ISSUE TITLE
Investigate status of missing metabase alerts for attestation service on-call

### ISSUE THREAD

**Issue by eelanagaraj** [celo-org/celo-monorepo#9352]
We are missing attestation service alerts in the informational alerts Slack channel.

This ticket should:
- check on the status of the metabase/Slack integration bug fix
- if it looks like the fix won't happen for a while, set up a Slack alert to remind on-call person to check the dashboards once a shift

**Comment by alecps** [comment]
duplicate of https://app.zenhub.com/workspaces/identity-backlog-board-60e61301c3dc55000e540b61/issues/celo-org/celo-monorepo/9353
