### ISSUE TITLE
ASv2 🤝 

### ISSUE THREAD

**Issue by alecps** [celo-org/celo-monorepo#9374]
ASv2 - Trusted Issuer Attestation Service

**Comment by eelanagaraj** [comment]
@alecps do we need this in addition to the MVP ticket #8588 ? Could we instead just change the MVP -> ASv2, since we probably won't have as concrete of a delivered MVP without the off-chain client?

**Comment by alecps** [comment]
closing in favor of https://github.com/celo-org/celo-monorepo/issues/9730
