### ISSUE TITLE
[ASv2] Get ecosystem feedback on design doc

### ISSUE THREAD

**Issue by eelanagaraj** [celo-org/celo-monorepo#9381]
- Share design doc publicly (in stages) to ecosystem partners
- Schedule 1:1 meetings with stakeholders
  - get feedback on ASv2
  - use this as a basis for broader dApp needs research
- make necessary updates to design doc

TODO
- [x] link form (non-anonymous) to the design doc for broader public feedback

**Comment by arthurgousset** [comment]
Next steps: 

- [x] https://github.com/celo-org/celo-monorepo/issues/9416
  - summarise feedback received so far ("themes", "patterns")
  - make clear action items after summary
