### ISSUE TITLE
Recreate + Codify ODIS Signer dashboards and alerts in Grafana

### ISSUE THREAD

**Issue by alecps** [celo-org/celo-monorepo#9523]
- @alecps to determine which dashboards and alerts should be migrated (some may no longer be needed) and any other adjustments that should be made in migration
- @noisypigeon to codify and recreate dashboards and alerts (use opportunity for ODIS onboarding)

**Comment by alecps** [comment]
Restricting scope to just Signer monitoring and breaking combiner monitoring into its own ticket

**Comment by istx25** [comment]
I am making progress on this.
