### ISSUE TITLE
Escrow Payments are not showing up correctly

### ISSUE THREAD

**Issue by nityas** [celo-org/celo-monorepo#953]
### Expected Behavior

A user should only be prompted to resend or redeem if the person they invited has not verified

### Current Behavior

Even if an Escrowed payment is sent, the option to redeem it (in some cases for only $.05, in some cases for the full amount even though per bug reporter, the payment had been successfully redeemed)

**Comment by annakaz** [comment]
@nityas can you clarify the Current Behavior? I think your sentence got cut off

**Comment by nityas** [comment]
@annakaz good catch - edited the original description

**Comment by annakaz** [comment]
I am blocked on this as`celotooljs` is broken so I cannot send invites, and the wallet cannot send transactions
