### ISSUE TITLE
Add CLI commands for removing attestation signers

### ISSUE THREAD

**Issue by eelanagaraj** [celo-org/celo-monorepo#9535]
This should make it possible for validators to opt-out of running an attestation service, even after they have registered attestation signer keys. (Extension of [this work](https://github.com/celo-org/celo-monorepo/pull/2230)).

Work includes:
- tests
- possible CK changes

**Comment by alecps** [comment]
Closing in favor of https://app.zenhub.com/workspaces/identity-backlog-board-60e61301c3dc55000e540b61/issues/celo-org/celo-monorepo/6397
