### ISSUE TITLE
Developers SBAT display stability fee in transaction feed

### ISSUE THREAD

**Issue by nityas** [celo-org/celo-monorepo#954]
### Expected Behavior

Adding a new transaction item to the Activity Feed for Stability Fee, which has become "Network Fee". 

If the amount is less than 0.001 in US/local currency, show ‘< 0.001’ in the feed and the exact amount to ~6 decimal places in the drilldown (rounded UP). Otherwise, show fee rounded UP to nearest .001.

<img width="919" alt="Screen Shot 2019-09-19 at 4 19 56 PM" src="https://user-images.githubusercontent.com/51388535/65287825-6a800f00-daf9-11e9-8f33-831bfe03ce92.png">

[Figma link](https://www.figma.com/file/kZEv4xA3cBNxnTykjneqz1/Exchange-Confirmation-Network-Fee-Fee-Dialog?node-id=0%3A1)

### Current Behavior

does not exist

**Comment by coreycelo** [comment]
Added designs.

**Comment by annakaz** [comment]
Hey @nityas any update on whether this is a priority for the upcoming sprint?

**Comment by annakaz** [comment]
Note that for this feature to be live, the notification service must track the network fee- see https://github.com/celo-org/celo-monorepo/issues/1144
