### ISSUE TITLE
Wallet users SBAT see tobin tax on exchanges

### ISSUE THREAD

**Issue by nityas** [celo-org/celo-monorepo#955]
### Expected Behavior

* Update Exchange Confirmation Screen
  * "Fee" is now split into "Exchange Fee" and "Security Fee"
  * Add More Info buttons for each
* Add Exchange Fee dialog (new)

<img width="1977" alt="Screen Shot 2019-09-19 at 4 06 52 PM" src="https://user-images.githubusercontent.com/51388535/65287316-9dc19e80-daf7-11e9-9bca-57d85399425e.png">

[Figma Link](https://www.figma.com/file/kZEv4xA3cBNxnTykjneqz1/Exchange-Confirmation-Network-Fee-Fee-Dialog?node-id=0%3A1)

### Current Behavior

Exchange Fee dialog doesn't exist. Security Fee dialog exists, but isn't linked. Exchange Confirmation screen doesn't include Exchange Fee. 

<img width="1970" alt="Screen Shot 2019-09-19 at 4 07 15 PM" src="https://user-images.githubusercontent.com/51388535/65287510-5b4c9180-daf8-11e9-8a20-01a0703caa6b.png">

**Comment by coreycelo** [comment]
Added designs.

**Comment by Pedro-vk** [comment]
@coreycelo can you provide the new image for Fee exchange information view?
![image](https://user-images.githubusercontent.com/1885747/66121071-9bbe0c00-e5dc-11e9-896b-5547bed31689.png)

**Comment by coreycelo** [comment]
@Pedro-vk Yep, available here: [Figma Link](https://www.figma.com/file/kZEv4xA3cBNxnTykjneqz1/Exchange-Confirmation-Network-Fee-Fee-Dialog?node-id=0%3A1)
