### ISSUE TITLE
Some protocol tests that incorrectly use `assertRevert` instead of `assertRevertWithReason`

### ISSUE THREAD

**Issue by eelanagaraj** [celo-org/celo-monorepo#9557]
Go through and fix all tests that do this and ensure that the tests pass afterwards.

TODOs:
- check that all uses of `assertRevert` are not using the optional `errorMessage` param as the _expected revert reason_; if so, change `assertRevert` -> `assertRevertWithReason`
  - Examples:
    - `packages/protocol/test/governance/validators/downtimeslasher.ts` numerous, including L241
    - `packages/protocol/test/common/accounts.ts` L722
-  ensure that all protocol tests pass

**Comment by covendev** [comment]
@eelanagaraj ,  I would be interested to work on this  but wanted to get more clarity before proceeding, does optional errorMessage in the above mentioned lines point to this particular line - 'startBlock and endBlock must be in the same epoch' in packages/protocol/test/governance/validators/downtimeslasher.ts L241 and 'Cannot re-authorize address or locked gold account for another account' in packages/protocol/test/common/accounts.ts L725 but not exactly the errorMessage keyword itself?

**Comment by eelanagaraj** [comment]
Hey @Rnamita great to hear that! for those two examples, those are currently passed in as the `errorMessage` optional arg for `assertRevert`, but these look like they are the expected revert reason. In this case, we should be using the `assertRevertWithReason` function instead of `assertRevert`, as this will actually check that the test reverts with the correct revert reason.

For this ticket, I'd recommend the following steps:
- find uses of `assertRevert` that also include an `errorMessage` (i.e. some string passed in) for a given contract
- try to get the tests running for that contract locally (i.e. via `quicktest`, you can check out the `README` in the protocol folder for some tips on getting this set up)
- double check if the usage in the test looks like it's checking against a revert message in the contract; if so, change `assertRevert` -> `assertRevertWithReason`
- run the tests again and make sure they still pass

Hope this helps! Let me know if you have other questions :)
