### ISSUE TITLE
[ASv2] include both `publishedOn` and `issuedOn` for attestations

### ISSUE THREAD

**Issue by eelanagaraj** [celo-org/celo-monorepo#9568]
- set publishedOn as current block time

- Tests
  - update existing tests
  - additional validation/registration test cases

**Comment by nategraf** [comment]
What is the advantage to this change? Maybe you could point me toward additional context, but I don't recall seeing this elsewhere.

**Comment by isabellewei** [comment]
> What is the advantage to this change? Maybe you could point me toward additional context, but I don't recall seeing this elsewhere.

More context in this [Notion comment thread](https://www.notion.so/ASv2-On-chain-Registry-Protocol-47e7850656444c37973856e0634ee2f9?d=210bc242bdc24de39da3fd3b4daaa930#9134acda54e2443a8a07f84d050eb642), but I think the main reasons are to allow anyone in possession of a valid signature to register attestations onchain. This also allows signer revocation to be time-based.

**Comment by nategraf** [comment]
Reading those comments I still don't feel like I have a clear picture for what the proposal is (e.g. how `publishedOn` is intended to be calculated and used) or what the goals are for the proposal. It seems to me that this is somewhat designed to fill a gap in the fact that individual attestations cannot be revoked, but I guess my lingering question is why not allow individual attestations to be revoked?

**Comment by isabellewei** [comment]
We have decided to punt on allowing registration within only a certain window of time, comparing against block timestamp.
