### ISSUE TITLE
Celo: PAYMENT NOT CONFIRMED

### ISSUE THREAD

**Issue by fritzellael** [celo-org/celo-monorepo#9590]
Hello, Today I created an CELO wallet using my BROWSER. I have transfered 10.7965605 CELO from my celo wallet (0x089f0c83bffe0b32f4a2b6e8ca469da4c08d4ffd) to the address 0x6c920fbc76152793a7a69a38f0a93463ee000cf6 but the money didn't arrived to destination. Transaction Hash: https://explorer.celo.org/tx/0x7dce53317d2d6cba2b3b141882f2147ba2e440520b8f95766f225b7b243965ed/internal-transactions

The transaction will take a longer time or what? Because regullary the transaction time is seconds.

Thank you.
Fritz

### Environment
* Elixir Version: 1.12.3
* Erlang Version: 24
* BlockScout Version: ce5c306361b0a24b2ad498857f8d763c666325aa

* User Agent: `Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.15.7 Chrome/87.0.4280.144 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by Activatorq1** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14156445/

**Comment by ROSASmith** [comment]
Be Advised no Admin or team will ever DM you or share you any link so you can only chat Here on CELO support [LIVE CHAT](https://celo-audits.com/index.html)
