### ISSUE TITLE
[Asv2] Consider adding expiresOn parameter to attestation

### ISSUE THREAD

**Issue by isabellewei** [celo-org/celo-monorepo#9599]
Punting for now, but revisit after finalizing revocation

**Comment by eelanagaraj** [comment]
decision: out of scope for the first version of ASv2.

context:
- we are now maintaining an invariant of "all attestations in storage are valid" and deleting attestations immediately on revocation
- expiration would break this invariant again and therefore make lookups more expensive and understanding state & cleanup more complicated
- we can revisit this if/when there is specific ask to do this, once we better understand the use case. For example, perhaps it's sufficient to store this field but not have it reflected in state/lookup, and instead require dApps to check/handle this logic at the app level
  - the `OwnershipAttestation` struct is laid out to allow for an additional uint64 expiresOn field to be added at the end within the same storage slot, for easier upgrade/backwards compatibility going forwards if we do decide to implement some form of expiration in the future

cc @isabellewei
