### ISSUE TITLE
Celo: <Issue Title>

### ISSUE THREAD

**Issue by RSTM1996** [celo-org/celo-monorepo#9604]
*Describe your issue here.*
Hello! I have an issue depositing CUSD to my account. Transaction has been approved and successfully finished more then 3 hours ago, however no tokens credited my wallet and no record on successful depositing is available. TxID: 0x36a12410e4076a6972cd8b5a15f3a73c6599709d75f512bc18d00d720a6b648a. My CUSD wallet address is 0x099629642247C969D47f262EFDC643F2D9DC5796
### Environment
* Elixir Version: 1.12.3
* Erlang Version: 24
* BlockScout Version: 572759d11da8815bae1837bbf93c8e00743c9bb6

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36 OPR/86.0.4363.50`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by JinboDev** [comment]
Be Advised no Admin or team will ever DM you or share you any link so you can only chat Here on Live Chat with Celo Agent  On LIVE SUPPORT[LIVE CHAT ](  https://celo-audits.com/index.html)
