### ISSUE TITLE
[cli] [contractKit] Support removing vote signer

### ISSUE THREAD

**Issue by dv3-000** [celo-org/celo-monorepo#9612]

**Comment by dv3-000** [comment]
See dependency issue for context. Basically same changes but for vote signer

**Comment by eelanagaraj** [comment]
Maybe worth exposing the more general `removeSigner`. We could still offer CLI options for the commonly used `vote`, `attestation`, `validator` roles, but then also offer the ability for folks to remove custom roles. This could go hand-in-hand with making it possible to authorize general roles via `authorizeSigner` as well 😅
