### ISSUE TITLE
코인 오배송

### ISSUE THREAD

**Issue by kangjh34** [celo-org/celo-monorepo#9616]
안녕하세요 업비트에서 실수로 이 거래소에 넘기게 되었는데 잘못 보낸 것이여가지고 혹시 복구를 할 수 있나 문의 해봤습니다.

**Comment by kjsman** [comment]
1. **접근하는 그 누구에게도 본인의 비밀키를 알려주지 마세요!**
2. 이곳은 CELO 블록체인을 개발하기 위한 소스코드 관리 웹사이트이고, 지금 글을 올리신 곳은 어떤 내용을 개발할지 논의하는 공간입니다. 거래소가 아닙니다.
3. 어떤 상황이신지 보다 상세히 말씀을 해주시면 도움을 드릴 수 있는지 확인은 해보겠습니다. 어디에서 어디로 어떤 코인을 보내셨나요?
    * 참고로, 저는 CELO 블록체인의 개발이나 해당 재단과 어떤 관련도 없는 일반인입니다.
