### ISSUE TITLE
De-dupe MoneyAmount and CurrencyDisplay components

### ISSUE THREAD

**Issue by jmrossy** [celo-org/celo-monorepo#962]
https://github.com/celo-org/celo-monorepo/blob/master/packages/mobile/src/components/CurrencyDisplay.tsx#L17

https://github.com/celo-org/celo-monorepo/blob/master/packages/react-components/components/MoneyAmount.tsx#L13

**Comment by jeanregisser** [comment]
Fixed in #3032
