### ISSUE TITLE
Users SBAT use invite code from partial invite text

### ISSUE THREAD

**Issue by annakaz** [celo-org/celo-monorepo#97]
### Expected Behavior

Some phones cut off texts at 160 (?) characters which leads to an invite text that does not contain the full message, but does contain the full invite code (see image below). Users SBAT copy this partial message into the redeem invite screen. 

### Current Behavior

Invitation texts that are cut off fail. Users must select the code from within the message to redeem it. Usually users can paste the full text in and the app identifies the invite code, but this does not work with partial texts. 

Example of partial text:
![Photo on 7-23-19 at 4 23 PM](https://user-images.githubusercontent.com/16907027/61695501-2de89f00-ad66-11e9-80a9-fce6c20dcf18.jpg)

**Comment by sallyjyl** [comment]
Seems to work for me, after copying up to "...You can install the C". As long as the full invite code is contained in the message you copied, it should work.  Are you still able to reproduce this?
