### ISSUE TITLE
ODIS rate limit contract + signer quota implementation

### ISSUE THREAD

**Issue by arthurgousset** [celo-org/celo-monorepo#9703]
- Simple on-chain store for total ODIS value per account
  - add CK accessors for this contract
  - tests for ODIS on-chain & contractkit
- Update new ODIS Signer endpoint to query the on-chain contract to calculate quota
  - integration tests for ODIS signers

**Comment by arthurgousset** [comment]
@eelanagaraj during sprint planning:
- Smart contract (3 functions) and tests are done 🥳 
- getting functions exposed through CK
- hopefully get this done fairly soon so capacity in same sprint

@alecps: 
- Only signer endpoints in this scope
- combiner endpoint will have own ticket

**Comment by alecps** [comment]
See design in https://www.notion.so/clabsco/ODIS-Rate-Limit-v2-2d3e7bcf01cf4fd19f00b1542ae862b9

**Comment by alecps** [comment]
https://github.com/celo-org/celo-monorepo/pull/9710

**Comment by arthurgousset** [comment]
Sprint planning notes: 

- Some form of release notes for the smart contract component so it can be looked at separately from the CIP40 branch
