### ISSUE TITLE
Draft Core-Contracts 8 release notes.

### ISSUE THREAD

**Issue by arthurgousset** [celo-org/celo-monorepo#9724]
Draft release notes for [Core Contracts Release 8](https://github.com/celo-org/celo-monorepo/releases/tag/core-contracts.v8.pre-audit) (pre-release). In particular the following sections:

- [x] "Key updates in this release" (blurb with description of changes)
- [x] "Specific Version Updates" (table with contract versions)

You can use [Core Contracts Release 7](https://github.com/celo-org/celo-monorepo/releases/tag/core-contracts.v7.post-audit) as a template.

I (@0xarthurxyz) will add the Hacken.io audit report to the "Audits" section when it's published in the next days.

**Comment by arthurgousset** [comment]
@alecps ticked off the todos above and moved this into the Q/A Review column.

**Comment by arthurgousset** [comment]
During sprint planning: 

- We Eela's feedback and link ODIS docs

**Comment by alecps** [comment]
https://github.com/celo-org/celo-monorepo/releases/tag/core-contracts.v8.pre-audit
