### ISSUE TITLE
ODIS 2.0.0 Monitoring/Alerting

### ISSUE THREAD

**Issue by eelanagaraj** [celo-org/celo-monorepo#9728]
Catch-all ticket for updating metrics post-merge 

- [x] promote alerts from slack to page
- [x] delete old signer alerts
- [x] setup grafana alert from synthetic uptime check 
- [x] put up signer dashboard PR
  - [x] merge
- [x] put up combiner dashboard PR
  - [x] merge

**Comment by arthurgousset** [comment]
Sprint planning: 
- Alec - just to make sure we have alerts/graphs set up in Grafana
- Eela estimated high "don't have background on Grafana, would just need to onboard"
