### ISSUE TITLE
ODIS 2.0.0 Code Review

### ISSUE THREAD

**Issue by alecps** [celo-org/celo-monorepo#9729]
For those assigned, please budget 2 -3 days to do a thorough review of #9693

**Comment by arthurgousset** [comment]
Sprint planning: 
- Alec - could be good to timebox this review per person
- Eela - really like the idea of timeboxing, could pay attention to special parts but review the whole PR
- We'll also ask for a review from Victor
- Costing will include making small changes from comments
- 8 dev days in total across team
