### ISSUE TITLE
[Tracker] ODIS 2.0.0 code cleanup

### ISSUE THREAD

**Issue by alecps** [celo-org/celo-monorepo#9736]
Catch-all ticket for thorough (preliminary) code review of #9693 and any miscellaneous work that comes out of it. Will include cleaning up TODO statements, making new tickets when necessary, and identifying gaps in testing. 

Note that this ticket is separate from #9729, which will happen later 

- [x] @alecps break up the list of todos below

**Comment by arthurgousset** [comment]
During spring planning: 

- Catch all ticket for small todos that are difficult to estimate. 
- We'll try to address being better at scoping in the remaining time of this sprint planning. We'll break this into separate tickets.
- There are multiples scattered todos in the code that can't be addressed immediately to avoid going down a rabbit hole.

**Comment by alecps** [comment]
https://github.com/celo-org/celo-monorepo/pull/9782

**Comment by alecps** [comment]
See TODO list in #8645
