### ISSUE TITLE
Fix CI build for Cip40

### ISSUE THREAD

**Issue by alecps** [celo-org/celo-monorepo#9760]
- fixing install-dependencies (currently blocking all other CI tests)
- fixing `migration-override.json --upto` numbers in:
  - `packages/cli/package.json`
  - `packages/sdk/identity/package.json`
  - `packages/sdk/transactions-uri/package.json`
- Adding releaseData for OdisPayments for whichever release corresponds to the version on OdisCip40 (may be different than the "actual" release, but whatever is needed to get the `protocol-test-release` CI tests working for this branch, even though this will probably be changed when merging to `master` later)

**Comment by arthurgousset** [comment]
During spring planning: 

- SDK tests fail but pass on PR branch (some flakiness with tests)
