### ISSUE TITLE
Add unit tests for thresholdState services

### ISSUE THREAD

**Issue by alecps** [celo-org/celo-monorepo#9792]
The combiner implements a thresholdState service for both the pnp and domains use cases. Some of this functionality is tested in the relevant quota or signature integration tests, but we should have more thorough unit tests that check/specify the functionality of the findThresholdDomainState and findCombinerQuotaState methods when different combinations of signer responses are provided. These tests should exist in separate files from the integration tests.

**Comment by arthurgousset** [comment]
Sprint planning: 
- Writing tests for thresholdState service

**Comment by arthurgousset** [comment]
Sprint planning: 
- PR under review
- Addressing PR comments from Alec
