### ISSUE TITLE
Audit db wrapper code + error handling

### ISSUE THREAD

**Issue by alecps** [celo-org/celo-monorepo#9795]
The Signer DB code needs to be thoroughly reviewed before we launch ODIS 2.0.0. In particular, we've seen that some tests may be flakey due to a potential hanging DB operation. The output of this ticket is a PR with any fixes/improvements to this part of the codebase, with the goal of identifying and fixing the source of this flakiness. 

Additionally, this PR should employ the [meter](https://github.com/celo-org/celo-monorepo/blob/79c6bdbe530cf872de6a63d0567a407172298cc6/packages/phone-number-privacy/signer/src/common/web3/contracts.ts#L23) helper function in any DB operations where it is not already being used, and should probably be taken by the same person who takes #9796

**Comment by arthurgousset** [comment]
Sprint planning:
- Currently in review
- [ ] Eela -  Take some stuff out of PR that is adding complex edge cases
- Alec - Minor refactor (could be its own ticket)
- We're estimating remaining dev days

**Comment by isabellewei** [comment]
fixed in #9846
