### ISSUE TITLE
ensure meter(...) helper function is used everywhere in Signer

### ISSUE THREAD

**Issue by alecps** [celo-org/celo-monorepo#9796]
The [meter](https://github.com/celo-org/celo-monorepo/blob/79c6bdbe530cf872de6a63d0567a407172298cc6/packages/phone-number-privacy/signer/src/common/web3/contracts.ts#L23) helper function is currently being used in many places but not everywhere in the signer. For consistency, we should use this function instead of the more verbose metering code that is currently used in places such as https://github.com/celo-org/celo-monorepo/blob/79c6bdbe530cf872de6a63d0567a407172298cc6/packages/phone-number-privacy/signer/src/common/database/wrappers/domainState.ts#L61

It will probably make sense to batch this work with #9795 as much of the old metering code is used in db wrapper functions

**Comment by arthurgousset** [comment]
Sprint planning: 
- No changes left, part of same PR

**Comment by isabellewei** [comment]
fixed in #9846
