### ISSUE TITLE
yarn postinstall step is run twice and too early the first time

### ISSUE THREAD

**Issue by jeanregisser** [celo-org/celo-monorepo#98]
### Expected Behavior

When running `yarn install`, our`postinstall` step should run only once after all our dependencies postinstall step.

### Current Behavior

When running `yarn install`, our `postinstall` step is being run twice and makes it unnecessarily long. Also it's being run too early the first time.

I discovered this while we investigated an error when running `yarn install` on the newly open-sourced repo.

@jmrossy submitted [a PR to fix the initial error](https://github.com/celo-org/celo-monorepo/pull/50).

I commented with the following:
> However to me it hides the underlying problem of `postinstall-postinstall` triggering too early and operating while yarn still executes other packages postinstall in the `yarn install` sequence. So it's possible this problem will appear again in the future if timing changes.
Another small drawback is it takes a couple more seconds to run due to concurrency being limited to 1.
> I'll open an issue to discuss possibly removing `postinstall-postinstall` to have a better long term fix.

From what I gathered, `postinstall-postinstall` was added because https://github.com/ds300/patch-package recommends using it to workaround `yarn remove <package>` not running `postinstall` and [leaving fresh unpackaged modules](https://github.com/ds300/patch-package#why-use-postinstall-postinstall-with-yarn).

I feel that use case is not a big problem, however, `yarn install` executing `postinstall` twice and also too early the first time (and causing the race condition error we saw) is a bigger problem.

One simple option I see is removing `postinstall-postinstall` which is causing this unintended side effect and burden on all developers.
For the case where a developer runs `yarn remove <package>`, the developer will have to remember to run `yarn` or `yarn postinstall` so `patch-package` can do its job on the fresh unpackaged modules.
Though I'd would prefer an automated way, this operation would only be needed seldomly.
Also we should probably open an issue with [yarn](https://github.com/yarnpkg/yarn) so the `postinstall-postinstall` workaround is not needed anymore in the future (I searched for an existing issue but didn't find one).

@jmrossy also suggested wrapping our `postinstall` script to detect when it's run too early. But might not be worth the added complexity.

What do you think?

**Comment by cmcewen** [comment]
I agree with your assessment that yarn remove is a pretty rare use case, and it's an easy fix to just run yarn again there. The much more common case is installing, so I would be in favor of removing it and just adding a note to the README. Also sounds like a good idea to open an issue
