### ISSUE TITLE
Determine why ODIS request signing does not use SignatureUtils and if we should switch

### ISSUE THREAD

**Issue by alecps** [celo-org/celo-monorepo#9803]

**Comment by arthurgousset** [comment]
Sprint planning: 
- Eela highlighted this
- More of an investigation ticket
- Alec put this into Spring backlog
- Cody wrote some of this code a while ago
- Chat through this with Victor

**Comment by arthurgousset** [comment]
Sprint planning: 
- Alec - Asking victor today
