### ISSUE TITLE
Audit request / response types

### ISSUE THREAD

**Issue by alecps** [celo-org/celo-monorepo#9804]
- [ ] Consider improving PNP req/res types for new (non-legacy) PNP endpoints https://github.com/celo-org/celo-monorepo/blob/79c6bdbe530cf872de6a63d0567a407172298cc6/packages/phone-number-privacy/common/src/interfaces/requests.ts#L32
- [ ] Investigate alias of GetBlindedMessageSig that is defined in @celo/identity sdk
- [ ] investigate disable domain response types which are missing `status`
- [ ] Also look into #9812 
- [ ] Check that pnp request/responses are backwards compatible (see https://github.com/celo-org/celo-monorepo/blob/3f09e7624dfe34e0a28936da6e3c2414393cbf58/packages/phone-number-privacy/common/src/interfaces/responses.ts#L38)

**Comment by arthurgousset** [comment]
Sprint planning: 
- Eela - various things related to request/response types

**Comment by arthurgousset** [comment]
Sprint planning: 
- Eela - Splitting request types is a little more involved. Alec/Eela agreed to do minimal changes short-term (timebox to end of week 1.5 dev days). This includes the db changes. 
- Alec - Wait to end of the week for review. `disabled` endpoint query about outstanding work. Eela already did that.
