### ISSUE TITLE
audit ODIS bunyan logging

### ISSUE THREAD

**Issue by alecps** [celo-org/celo-monorepo#9808]
Ensure we are using Bunyan structured logging correctly everywhere in the ODIS codebase. There's a chance that we aren't using the built-in error message handling correctly or that our logs are sometimes split into two separate lines when they shouldn't be. The output of this ticket should be a PR and a sense of confidence that we are using logging best practices consistently. 

Some things to double check (audit not limited to these):
- `session.logger.level('text', object)` -- this format does not seem to format objects properly (converts them to string) as we are mixing "object" & text logging, while something like `session.logger.level({message: 'text', objectName: object})`
  - eyeball check & fix places where object logging output doesn't look like it's formatted properly (i.e. looks like a JSON string in the unit test logs)
- standardize error logging format (and double check that this outputs messages and error stacktraces properly)
- audit logging levels -- are there places where we are logging errors when we should be logging warnings/info statements instead?

**Comment by arthurgousset** [comment]
Sprint planning: 
- This is also like the sketchy import ticket

**Comment by alecps** [comment]
Bumped the estimate for this after looking through some more complicated sections of logging and discussing with Eela
