### ISSUE TITLE
Investigate whether domainState is ever provided on failure in domain/sign endpoint

### ISSUE THREAD

**Issue by alecps** [celo-org/celo-monorepo#9812]
See TODO comment: https://github.com/celo-org/celo-monorepo/blob/79c6bdbe530cf872de6a63d0567a407172298cc6/packages/phone-number-privacy/combiner/src/domain/endpoints/sign/io.ts#L88

**Comment by alecps** [comment]
related to #9804

**Comment by arthurgousset** [comment]
Sprint planning: 
- Alec - some overlap with strict object matching
