### ISSUE TITLE
Standardize naming conventions throughout ODIS codebase

### ISSUE THREAD

**Issue by alecps** [celo-org/celo-monorepo#9813]
We are currently inconsistent about how we name files in the ODIS codebase. For example, some files are named using camelCase while others are named using kebab-case (https://github.com/celo-org/celo-monorepo/blob/c7d70baf00b359d13bcf1dd32b1a64393986f1d6/packages/phone-number-privacy/combiner/src/common/crypto-clients/crypto-client.ts#L5). It's likely there are other inconsistencies too, which we should address. The output of this ticket should be a PR that corrects any naming convention inconsistencies in the ODIS codebase.

**Comment by arthurgousset** [comment]
Sprint planning: 
- Could be nice to combine with file import ticket
