### ISSUE TITLE
Implement monitoring for client-side signature unblinding errors returned from the combiner (domain)

### ISSUE THREAD

**Issue by alecps** [celo-org/celo-monorepo#9817]
Continuation of the work in #9717.

Since we won't be able to check for verification errors server-side (for `DOMAIN_SIGN` requests), the goal of this ticket is to enable some kind of check such that we don't have to wait for wallets to reach out to us in frustration because unblinding started failing on the client-side.

Possible solutions to explore:
- upgrading the monitoring function to periodically query the combiner for signatures for some known example domain and unblind the response. If the unblinding throws an error, this should result in some kind of alert that there may be something wrong with a signer's key version or something else
- tracking repeated requests in the combiner (detailed more in #9717)

**Comment by arthurgousset** [comment]
Sprint planning: 
- We can do way later

**Comment by alecps** [comment]
finished by monitor check
