### ISSUE TITLE
Determine if we need a different error code for nonce failures

### ISSUE THREAD

**Issue by alecps** [celo-org/celo-monorepo#9818]
Right now, authentication failures and nonce failures have the same error status code. Determine if it would be useful to have different error codes for each scenario and what they should be

**Comment by arthurgousset** [comment]
Sprint planning: 
- Came out of PR discussion with Eela
- Relating to 401 error used for two errors
- Consider having two status codes
- Alternatively have different error messages (same status code)
- Eela - would be nice for logging after merge, before deployment

Todo: 
- [ ] Check if we have different error messages

**Comment by arthurgousset** [comment]
Sprint planning: 
- Alec - nonces related to domain requests for account recovery. Conflicting error codes.
- Izzy - Mostly like an investigation ticket. Good for consistent logging.
