### ISSUE TITLE
Add pnp "fail-open" monitoring to combiner

### ISSUE THREAD

**Issue by alecps** [celo-org/celo-monorepo#9836]
Ensure we have monitoring in the combiner for fail-open logic since we don't have visibility into prometheus metrics for partner signers. The combiner monitoring should be based intelligently off of the warning messages returned by signers

https://github.com/celo-org/celo-monorepo/blob/f53dae76000d8d86f31149805e341d93a248c64d/packages/phone-number-privacy/signer/src/pnp/endpoints/sign/action.ts#L66

**Comment by arthurgousset** [comment]
Sprint planning: 
- another small ticket, output from recent PR
- can't see if a signer fails open if it's run by a 3rd party
- Eela - Does this include updating things on the dashboard side of things?
- Alec - Only logging atm, combiner doesn't have prometheus metrics atm

**Comment by arthurgousset** [comment]
Sprint planning: 
- Alec - Got a PR up (responded to Eela's comments), hasn't added unit tests yet. Probably done by tomorrow
- Izzy - Thought we're not doing unit tests for logging.
- Alec - Pretty crucial to log whether combiner fails open

**Comment by arthurgousset** [comment]
Sprint check-in: 
- Alec responded to feedback
- Wants to add logic to test logging
- Probably timebox this into an afternoon and close after that

**Comment by arthurgousset** [comment]
Sprint planning: 

- Alec merged this "ended up being a huge PR"
- Added a test suite to test all the logs in the combiner
- Became verbose because tests needed to spell out the logs
- Good news "logs work"
