### ISSUE TITLE
How to get the amount of Locked (staked) CELO from the REST API?

### ISSUE THREAD

**Issue by kopeboy** [celo-org/celo-monorepo#9840]
I see no method at https://explorer.celo.org/api-docs for getting the amount of CELO I locked, I can only see the liquid balance and rewards. Basically once I lock it's like I loose track of my funds.

**Comment by marekolszewski** [comment]
Hi @kopeboy. Locked CELO is managed by a smartcontract so you have to do a view call to the LockedGoldProxy contract (the name is a holdover from when CELO was called cGLD):

0x6cC083Aed9e3ebe302A6336dBC7c921C9f03349E

The Celo explorer also exposes this information via its graphgl api, which you can hit with this GET request:

https://explorer.celo.org/mainnet/graphql?query={celoAccount(hash:%20%220x0000000000000000000000000000000000000000%22)%20{lockedGold,nonvotingLockedGold}}

Note: Be sure to replace 0x0000000000000000000000000000000000000000 with your address.
