### ISSUE TITLE
Imported contacts are not carried over on app upgrade

### ISSUE THREAD

**Issue by nityas** [celo-org/celo-monorepo#985]
### Expected Behavior

When updating the app version, the user should retain their synced contacts. If there are no contacts synced, on opening the send flow the user should be prompted to grant permission+ sync contacts

### Current Behavior

When updating the app version (from initial alfajores app version to 1.4.2), contacts that are synced were lost, and the user is not re-prompted to sync contacts

**Comment by jmrossy** [comment]
I'm unable to repro the original issue but I've confirmed that the latest Send screen works as expected. If users have not given contact perms, we show a button at the button to request it and import.
Given that we made lots of changes related to contacts and send btwn v1.4.0 and 1.4.2, I suspect this was just a quirk btwn those versions when upgrading. We'll be more careful with backwards compat going forward.
