### ISSUE TITLE
Audit combiner and signer endpoint error handling

### ISSUE THREAD

**Issue by eelanagaraj** [celo-org/celo-monorepo#9859]
Audit how we are sending responses & handling errors in the signer.
- Ensure that we are catching and responding to errors or handing off errors to Express's error handlers
- Likely add test cases for generic errors being thrown in unexpected places.
- Ensure that when returning failures, processes do not continue & do not attempt to send multiple responses (io is disconnected from performance; `perform` needs to return once errors have been reached as well -- ideally restructure like with the domain endpoints as this is cleaner)
  - seems like this may be an issue in the `quotaStatus` endpoint -- seems to be (in some test case) throwing an `ERR_HTTP_HEADERS_SENT` error in the controller after sending the first response; ensure that this is investigated and fixed

**Comment by arthurgousset** [comment]
Sprint planning: 
- Came up from db auditing
- Should probably check logic again, possibly write test cases to check errors are thrown/not thrown
- not huge

**Comment by arthurgousset** [comment]
Sprint planning: 
- Will finish this work this week before starting on SDK
