### ISSUE TITLE
Put all fail-open logic behind an env var

### ISSUE THREAD

**Issue by alecps** [celo-org/celo-monorepo#9863]
Any logic that allows ODIS to "fail-open" on error should be put behind an env var controlled by the combiner and each of the signers respectively. This will allow us to toggle fail-open logic on and off in response to outages without doing a full release 

See comment
 https://github.com/celo-org/celo-monorepo/blob/9d165f36452b7d031df5cb080fbe3f8da3b4d38e/packages/phone-number-privacy/common/src/utils/authentication.ts#L44

**Comment by arthurgousset** [comment]
Sprint planning: 
- Eela's comment on Alec's PR
