### ISSUE TITLE
Update ASv2 tutorial after new version of Identity SDK has been published

### ISSUE THREAD

**Issue by isabellewei** [celo-org/celo-monorepo#9936]
Also after new ODIS service has been deployed. update docs and example scripts

- check quota status
- use ODIS payments
- reference different bls blinding clients in SDK

Including: 
- [x] Example scripts
- [x] Code snippets in docs
- [ ] Emissianto

**Comment by arthurgousset** [comment]
Sprint: 
- Currently doing that on a separate branc

**Comment by isabellewei** [comment]
finished
