### ISSUE TITLE
Users SBAT inspect proxied contracts on blockscout

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-monorepo#995]
Right now, blockscout doesn't support the "proxy" smart contract pattern we use. Ideally it would understand that if a contract has a particular function/field, it should use the ABI of the value of that field instead of its current one.

**Comment by aaitor** [comment]
Implementation in progress in `https://github.com/jcortejoso/blockscout/tree/feature/get-proxied-code`

**Comment by aaitor** [comment]
Issue still in progress. By the time being the implementation made includes:

* Building a new blockscout table tracking the mapping between the proxied contract and their implementations
* Integration of the table in the blockscout `explorer` package
* Inclusion of this in the blockscout migration scritpt, allowing to create/drop the table when this is executed
* Modification of the RPC API allowing to check if a contract is proxied and if it's the case return the right API & source code  

Pending to wire everything together and some UT

**Comment by aaitor** [comment]
Issue implemented by: https://github.com/jcortejoso/blockscout/pull/1

This issue implements the following features:
- [x] Modification of the `getsourcecode` RPC api allowing to retrieve the source code of a proxied contract when is called using the proxy address
- [x] Modification of the contract source code view allowing to show the information of a proxied contract and an indicator that contract is proxied
- [x] Added indication in the view of a proxy contract indicating is a proxy

![image](https://user-images.githubusercontent.com/1726644/66401291-39ea1180-e9e3-11e9-941e-be8d2d7c4727.png)
