### ISSUE TITLE
Deprecate LEGACY_PNP endpoints

### ISSUE THREAD

**Issue by eelanagaraj** [celo-org/celo-monorepo#9961]
At ODIS 2.0.0 deployment, we will have the legacy & new PNP endpoints in operation. We eventually want to deprecate the LEGACY_PNP endpoints in the combiner and signer and only make it possible to use the new PNP rate limit (governed by OdisPayments.sol on-chain).

The output of this ticket is to have a deprecation plan (and possibly implement it depending on findings). This plan should include:

- setting a date for deprecating the legacy endpoints
  - make sure this is communicated to any external stakeholders
- whether we will deprecate by deleting the endpoints or just disabling the endpoints at the config level
depending on the time allotted for this ticket and decisions made, implementing these code changes and having 
- what other services are affected by this deprecation and what changes would need to be made to accommodate for this:
  - are there any additional SDK changes that need to be made? if so, have we reached out to the Applications team about this and is there anything else we need to do?
- have the plan reviewed by the DevOps team & make sure we have taken necessary steps before deprecating this

**Comment by alecps** [comment]
also delete old combiner
