### ISSUE TITLE
Users SBAT see Celo logo and color scheme on blockscout

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-monorepo#997]

**Comment by diminator** [comment]
Does this match the description?

PS: We've updated `blockscout` to upstream and applied changes from there

![image](https://user-images.githubusercontent.com/6178597/65888776-5e6d3a80-e3a0-11e9-8760-9092f140c8af.png)

Here's the footer:

![image](https://user-images.githubusercontent.com/6178597/65888491-ea329700-e39f-11e9-96c5-1f53ceea9fe7.png)

when switching networks:

![image](https://user-images.githubusercontent.com/6178597/65888348-a8a1ec00-e39f-11e9-9fed-f03a30f3799f.png)

**Comment by tjlahey** [comment]
![image](https://user-images.githubusercontent.com/3344589/66342804-1cdc1280-e8ff-11e9-8c78-fe469b29e2fc.png)

- Switch the bottom logo to the Celo color logo on dark bg
https://drive.google.com/file/d/1pKise20Gg8qO411HaNGL4_rrjZpykkyx/view?usp=sharing

![image](https://user-images.githubusercontent.com/3344589/66342848-33826980-e8ff-11e9-95cf-133b1cc7d63b.png)

- Change icons to white
- Ideally remove bullet points, if we can't customize change them to white.

**Comment by tjlahey** [comment]
For switching networks
![image](https://user-images.githubusercontent.com/3344589/66343138-d63ae800-e8ff-11e9-8752-527402d18250.png)
- Change the background from green to white. keep I'd like the opacity to be a lower. 
- I'm not super picky with the search field, I also doubt we can edit down to a very granular level but we use text fields with a stroke outline 
![image](https://user-images.githubusercontent.com/3344589/66343424-7a249380-e900-11e9-8c58-6f0954cfde01.png)
- For the radial field, follow this styling from the Celo community page
![image](https://user-images.githubusercontent.com/3344589/66343503-9fb19d00-e900-11e9-81b9-854ad5029962.png)

**Comment by tjlahey** [comment]
![image](https://user-images.githubusercontent.com/3344589/66343623-e43d3880-e900-11e9-8f97-01cf5deda83b.png)

Here are Celo colors you can sample from for the color sections.
![image](https://user-images.githubusercontent.com/3344589/66343708-1484d700-e901-11e9-81d4-0f730378ec68.png)

So the cells with titles such as "Blocks" and "Transactions". Remove I drop shadows and make the background a pure white. 

- Please take away the stroke on each of those sub sections and the gray background of those sections too. 
![image](https://user-images.githubusercontent.com/3344589/66343904-747b7d80-e901-11e9-8bc4-db94389a77bb.png)

- Make the lead green # on top of that section larger by 4px

**Comment by tjlahey** [comment]
![image](https://user-images.githubusercontent.com/3344589/66344311-5a8e6a80-e902-11e9-8c57-38cc15c46c36.png)

Match the header as close as you can to our website header

**Comment by tjlahey** [comment]
![image](https://user-images.githubusercontent.com/3344589/66344340-6ed26780-e902-11e9-8a28-f718505e19c6.png)

For this section, please give it a solid Celo dark background and change the gold lines to an off dark - #51565A

**Comment by tjlahey** [comment]
Plug in this adobe web font family and then follow the styling from celo.org

<link rel="stylesheet" href="https://use.typekit.net/dki6jkb.css">

![image](https://user-images.githubusercontent.com/3344589/66344840-9fff6780-e903-11e9-991d-232411f5723e.png)

An example you can reference
![image](https://user-images.githubusercontent.com/3344589/66344915-c6250780-e903-11e9-9bbb-15d20e7a8bef.png)

**Comment by Pedro-vk** [comment]
Hi @tjlahey, can you give me some feedback about the current progress=

![image](https://user-images.githubusercontent.com/1885747/66656497-664d9a00-ec3e-11e9-928b-1d73d692adc7.png)
![image](https://user-images.githubusercontent.com/1885747/66656511-6f3e6b80-ec3e-11e9-903b-58aede423b54.png)
![image](https://user-images.githubusercontent.com/1885747/66656525-782f3d00-ec3e-11e9-9f53-ba0355c32c7c.png)
![image](https://user-images.githubusercontent.com/1885747/66658617-1ffa3a00-ec42-11e9-9867-4fe03c531179.png)

**Comment by Pedro-vk** [comment]
> ![image](https://user-images.githubusercontent.com/3344589/66344340-6ed26780-e902-11e9-8a28-f718505e19c6.png)
> 
> For this section, please give it a solid Celo dark background and change the gold lines to an off dark - #51565A

@tjlahey Can you add more information? the grey one on both green sections?

**Comment by tjlahey** [comment]
> > ![image](https://user-images.githubusercontent.com/3344589/66344340-6ed26780-e902-11e9-8a28-f718505e19c6.png)
> > For this section, please give it a solid Celo dark background and change the gold lines to an off dark - #51565A
> 
> @tjlahey Can you add more information? the grey one on both green sections?

Yep yep, please change all of those green backgrounds to "celo dark" (#2E3338) which is our black. Take away all signs of gradient and drop shadow. 

Then change the gold lines to our secondary gray (#51565A)

**Comment by tjlahey** [comment]
> Hi @tjlahey, can you give me some feedback about the current progress=
> 
> ![image](https://user-images.githubusercontent.com/1885747/66656497-664d9a00-ec3e-11e9-928b-1d73d692adc7.png)
> ![image](https://user-images.githubusercontent.com/1885747/66656511-6f3e6b80-ec3e-11e9-903b-58aede423b54.png)
> ![image](https://user-images.githubusercontent.com/1885747/66656525-782f3d00-ec3e-11e9-9f53-ba0355c32c7c.png)
> ![image](https://user-images.githubusercontent.com/1885747/66658617-1ffa3a00-ec42-11e9-9867-4fe03c531179.png)

Make footer icons white - github, twitter, telegram

Flip "View all blocks" button to "celo green" #35D07F and white (#fff) text

Were you able to lose the drop shadows for the tiles?

Change the "x" in the top right of the hamburger menu to "celo dark" (#2E3338)

**Comment by tjlahey** [comment]
@diminator @timmoreton 

Web fonts package featuring Garamond and Futura PT from Adobe

<link rel="stylesheet" href="https://use.typekit.net/dki6jkb.css">

![image](https://user-images.githubusercontent.com/3344589/66939164-67444a00-eff7-11e9-8565-bd616e5302ca.png)

**Comment by Pedro-vk** [comment]
> > > ![image](https://user-images.githubusercontent.com/3344589/66344340-6ed26780-e902-11e9-8a28-f718505e19c6.png)
> > > For this section, please give it a solid Celo dark background and change the gold lines to an off dark - #51565A
> > 
> > 
> > @tjlahey Can you add more information? the grey one on both green sections?
> 
> Yep yep, please change all of those green backgrounds to "celo dark" (#2E3338) which is our black. Take away all signs of gradient and drop shadow.
> 
> Then change the gold lines to our secondary gray (#51565A)

The part of _Then change the gold lines to our secondary gray (#51565A)_ is not easy/safe, because we need to overwrite the `secondary` color of the palette and it can affect to different places. The line of the graph could be kept like that?
![image](https://user-images.githubusercontent.com/1885747/67200366-d8bf3680-f403-11e9-8960-20e26ecf5934.png)

**Comment by Pedro-vk** [comment]
> > Hi @tjlahey, can you give me some feedback about the current progress=
> > ![image](https://user-images.githubusercontent.com/1885747/66656497-664d9a00-ec3e-11e9-928b-1d73d692adc7.png)
> > ![image](https://user-images.githubusercontent.com/1885747/66656511-6f3e6b80-ec3e-11e9-903b-58aede423b54.png)
> > ![image](https://user-images.githubusercontent.com/1885747/66656525-782f3d00-ec3e-11e9-9f53-ba0355c32c7c.png)
> > ![image](https://user-images.githubusercontent.com/1885747/66658617-1ffa3a00-ec42-11e9-9867-4fe03c531179.png)
> 
> Make footer icons white - github, twitter, telegram
> 
> Flip "View all blocks" button to "celo green" #35D07F and white (#fff) text
> 
> Were you able to lose the drop shadows for the tiles?
> 
> Change the "x" in the top right of the hamburger menu to "celo dark" (#2E3338)

_Were you able to lose the drop shadows for the tiles?_
Do you mean the border on the left side? because I think that the boxes don't have a shadow. Or I'm thinking about different tiles.
