### ISSUE TITLE
Users SBAT see non-CG gas fees in correct currencies in blockscout

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-monorepo#999]

**Comment by jcortejoso** [comment]
Hi!

What is the expected UX for this? I have added the field `Gas Currency` to a link to the contract pointed by rpc response field `gasCurrency`. 
![image](https://user-images.githubusercontent.com/5635989/66134077-00d32b00-e5f8-11e9-98d0-6fb224a06fd1.png)

Is there any opinion about how this should be shown?
